### ISSUE TITLE
Implement sticky editor designs

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#10008]
## Describe the bug

Work on the sticky editor implementation.  This will need to use the quill editor for now then we can swap in the new editor when we get the mention plugin to work.

https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=1311-19927&node-type=frame&t=2lUehAq6USBhlo6w-0

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by burtonator** [comment]
There's one issue with the mobile design due to the fact that we're not on MDXEditor yet.

I'd like to propose a small change so we can implement it quickly.

I have the desktop version mostly working.

This is what it looks like on the desktop when active:

![CleanShot 2024-11-25 at 13 38 49@2x](https://github.com/user-attachments/assets/5f10b855-7461-4411-8efd-0d14b281d61e)

Then when you place your cursor in the textarea it becomes active:

![CleanShot 2024-11-25 at 13 39 27@2x](https://github.com/user-attachments/assets/dfde1d7b-1935-4562-a4d5-66b34f223cb8)

... and cancel will make it vanish again.

However this is the mobile implementation.

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/83bd3515-9f46-481e-950d-e34ff27e3290">

I can't implement this version without going and starting to hack with Quill which could take weeks and we'd just throw away this code at the end.

What we *could* do is make the text area just plain text for quick replies.

Then if you click the 'expand' button.

Aka this guy:

![CleanShot 2024-11-25 at 13 40 44@2x](https://github.com/user-attachments/assets/23ead2fc-02df-4056-b5a1-919e45dedccd)

Then we could activate the full quill editor like this:

<img width="444" alt="image" src="https://github.com/user-attachments/assets/048b429f-39f5-489d-a5a2-713977988b46">

Then when we cut over to MDXEditor we can get the design closer to this version.

**Comment by dillchen** [comment]
I think that's super acceptable to me thank you
