### ISSUE TITLE
Optimize chain initialization to remove query for past blocks

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#1003]
Maybe:

Inside initMetadata, the query for past blocks to calculate the blocktime could potentially be removed, if we have a better way to get blocktime. Also, we may not require a super accurate blocktime at this point.

**Comment by jnaviask** [comment]
I still want to fix this, by caching blocktimes.

**Comment by raykyri** [comment]
IIRC this related to Polkadot. Should we rewrite the ticket to be about caching recent blocks used for session key logins?

**Comment by jnaviask** [comment]
We still do block time derivation on chain load, so I was thinking this ticket is still relevant, although minor. Should open a separate ticket for block caching.
