### ISSUE TITLE
Namespace Mint Helpers

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#10074]
### Description

Context: https://commonxyz.slack.com/archives/C06TAS2SQUS/p1733176213949609

MintID(0) and others where able

### User Stories / Acceptance Criteria

for @ianrowan I guess

**Comment by ianrowan** [comment]
Just realized I added this a while ago: https://github.com/hicommonwealth/commonwealth/pull/8724

CC @dillchen
