### ISSUE TITLE
Placeholder for leaderboard page when there are zero entries 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#10087]
### Description

Currently this is what you see on the Leaderboard page when there are no entries. It looks like an error or the content is missing. 

<img width="709" alt="Screenshot 2024-12-03 at 9 55 46 AM" src="https://github.com/user-attachments/assets/d11913b3-634c-4804-8788-74654c7cf73a">

We should have a placeholder image (can be an icon that we use for empty states elsewhere or some other new image) when there are no entries, and the copy below the image should say "There are no entries in this contest yet" 

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- The sort filter should not be visible when there are no entries
- We should have a placeholder image with the copy "There are no entries in this contest yet" positioned at the center of the page

**Comment by sachben91** [comment]
@sssssabinaaa need your input on the above - are there any empty state icons or some other image that we can use here?

**Comment by masvelio** [comment]
@sachben91 @sssssabinaaa I think we just need "There are no entries in this contest yet" text. Not sure where would you like to add the image? The contest is running but the entries are not there, pretty normal. We just need to add text.
