### ISSUE TITLE
Leaderboard page does not display contest entries 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#10094]
## Describe the bug
Leaderboard page for Farcaster contest does not display contest entries even though there are entries to the contest 

### Initial conditions

**Environment:** 
demo

## Reproduction steps
- Create Farcaster Contest
- Post Frame in Farcaster and reply to the cast containing the frame
- Click on leaderboard in the frame 

## Actual behavior
- Leaderboard does not show any entries 

## Expected behavior
- Leaderboard shows all entries to the contest

## Reporter
@masvelio 

<img width="714" alt="Screenshot 2024-12-03 at 11 52 39 AM" src="https://github.com/user-attachments/assets/bcc0b67f-ebe5-48ba-b420-a8979f9b28cb">
<img width="719" alt="Screenshot 2024-12-03 at 11 52 52 AM" src="https://github.com/user-attachments/assets/261ad50a-130f-4493-ba87-ae982ffbc52a">

**Comment by rbennettcw** [comment]
Seems already resolved, tested on demo. Feel free to close if confirmed to be resolved.

**Comment by masvelio** [comment]
This should be resolve by #10119
