### ISSUE TITLE
Adding weighted votes to Farcaster contests 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#10149]
### Description

Currently, Farcaster contests are functioning as expected end to end, with payouts happening to the contest entry with the highest number of votes. The number of votes recorded on chain is represented by voting power which is currently equal to the amount of tokens that the user holds that the contest is funded with. So if a contest is funded with USDC on base, the onchain voting power is the amount of USDC on base that the voter holds. 

We need to add weighting to these votes so that:
1. users understand how the votes are tallied
2. the entries can be displayed in a manner that is legible to someone who wants to check the leaderboard to know the status of the contest 

The weighted voting can be added in the contest creation page for Farcaster. 
- The "Contest Funding" section should be replaced with "Primary token" section where the user can enter the token address and set the vote weight for the contest 

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- When the user is creating a Farcaster contest, they should see a section named "Primary Token" where the user can enter the funding token and the vote weight associated with it 
<img width="404" alt="Screenshot 2024-12-05 at 2 09 12 PM" src="https://github.com/user-attachments/assets/a38cfb2a-d915-4579-b289-9b24f1411400">

<img width="413" alt="Screenshot 2024-12-05 at 2 09 35 PM" src="https://github.com/user-attachments/assets/20f778ba-43ea-4737-a2b9-2337b20e1e33">

### Design Devlink

[Wireframes](https://www.figma.com/design/USMyfllHeTZZ6XgepAaRiq/Farcaster-Contest-changes?node-id=1-7&node-type=section&t=G1tXp0nGQkqniBPl-0)

**Comment by rbennettcw** [comment]
Platform work will be handled by: https://github.com/hicommonwealth/commonwealth/issues/10161
