### ISSUE TITLE
🟩 GetXps

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#10145]
## Description

We need to query the Xp projection to feed multiple UI views

### Consider the following filters:
- By user id
- By community using action_meta_id in log to associate ->quest->community
- By dates (weekly running balance, etc)
- Pagination 
- By event name

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @dillchen      | @masvelio  @Rotorsoft     |

## Engineering Requirements

1. **Authorization**
   - Current user auth
2. **Schemas** - Use [zod](http://zod.dev)
   - Input/Output schemas (TBD @masvelio)
3. **Routing**
   - tRPC internal router
4. **Query**
   - Xp table joined to community via quest action metas
5. **Response**
   -  TBD output schema

## Unit Testing
- Meets output schema

**Comment by dillchen** [comment]
Honestly, all these will be useful at some time a place.

If we need a rank order however, we should do

1. By user
2. By time period
3. Both user X time period
4. Event type
5. Communities
