### ISSUE TITLE
Show weighted votes on the leaderboard page 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#10150]
### Description

- The leaderboard page should show the number of weighted upvotes received by each cast. 
- The leaderboard page should be sortable by "Most upvoted"
- Sorting by "Most Liked" can be removed since likes do not impact contest outcome 

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- Leaderboard page should show weighted upvotes next to Farcaster embeds
- The Leaderboard should be sortable by "Most upvoted" 

<img width="751" alt="Screenshot 2024-12-05 at 2 16 10 PM" src="https://github.com/user-attachments/assets/4174e186-d2bd-4f63-9053-4749e758e9ef">

### Design Devlink

[Wireframe](https://www.figma.com/design/USMyfllHeTZZ6XgepAaRiq/Farcaster-Contest-changes?node-id=3-4&node-type=section&t=G1tXp0nGQkqniBPl-0)

**Comment by rbennettcw** [comment]
Platform work to be handled by https://github.com/hicommonwealth/commonwealth/issues/10161
