### ISSUE TITLE
After pressing launch token with the randomizer, nothing happens - no MM Prompt

### ISSUE THREAD

**Issue by markiscommon** [hicommonwealth/commonwealth#10151]
## Describe the bug
After pressing launch token with the randomizer, nothing happens - no MM Prompt
despite filling out all the info and going through the flow 

### Initial conditions

**Environment:** 
QA
**Branch/Release version:** 

**Browser:** 
Chrome
**Wallet:** 
MM

## Reproduction steps
use the randomizer launch token and go through the flown

## Actual behavior
nothing happens once oyu get to the end, no mm prompt 
<img width="1005" alt="Screenshot 2024-12-05 at 3 22 03 PM" src="https://github.com/user-attachments/assets/a242abd9-2849-4d6e-9ea0-02b46b300165">

## Expected behavior
Launchs token 

## Reporter
Mark

**Comment by Kellytimmins** [comment]
Hello @dillchen 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MM07638
Please see the link below to our dedicated support line:
[MM wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by dillchen** [comment]
Based on what I see above, we should ensure that we don't submit any values that don't match the createCommunity schema (looks like 255 is too long), we should try to ensure that the OpenAI API doesn't return anything too long

**Comment by dillchen** [comment]
![image](https://github.com/user-attachments/assets/f70a0cc8-7e90-43e9-8ff5-0d37215bc8ae)

This is a related error "The prefilled Community Name produces an error due to parenthesis. I only get this error occasionally not consistently reproducible "

**Comment by mzparacha** [comment]
> This is a related error "The prefilled Community Name produces an error due to parenthesis. I only get this error occasionally not consistently reproducible "

Will have to update the prompt for this, will take a look on this as well.
