### ISSUE TITLE
Help with floating action button (quick post) when posting outside of a community.  

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#10154]
## Describe the bug

I have a PR for posting within a community.  @dillchen wanted it to *also* make it work when you're *outside* of a community.

I'm implemented it all but this part.  

Here's what we need to change.

We'll need to define another route which doesn't have a scoped community.

```typescript tsx
  <Route
    key="/new/discussion"
    path="/new/discussion"
    element={withLayout(NewThreadPage, {
      scoped: true,
    })}
  />,
```

Then in NewThreadForm (which has a legacy and modern version) we need to update it so there's a dropdown to select the community.

Only worry about the 'legacy' version for now. The 'modern' version is for MDXEditor but that's not ready go to yet.

We probably either need to *hide* the community or have it automatically select the current community you're active on.

Then have a dropdown the users can pick the community.

To do the actual post we have to update the post page so that it doesn't use the app settings but posts via the communityId.  

The other thing I got stuck on is how the quill page is disabled and the logic behind that because I don't understand this existing 'app' system.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by burtonator** [comment]
Also, the Layout.tsx page will need this patch:

![CleanShot 2024-12-05 at 13 50 57@2x](https://github.com/user-attachments/assets/f2909972-b794-4338-8c6d-9982b25d9849)


Should be self explanatory when you jump to that file but we don't want a 404 when not on a community now.

**Comment by dillchen** [comment]
Here is the PR: https://github.com/hicommonwealth/commonwealth/issues/10011
