### ISSUE TITLE
SKALE Visibility in the Community creation page

### ISSUE THREAD

**Issue by egetekiner** [hicommonwealth/commonwealth#10349]
### Description

SKALE needs to be added as a top-level network.

### Bucket ID

#10347

### User Stories / Acceptance Criteria

SKALE should appear as a top-level network in the create community page once we will start supporting Skale Calypso Hub Mainnet.

**Comment by dillchen** [comment]
This should be addressed by #9911

**Comment by egetekiner** [comment]
I will update the bucket and close this one @dillchen
