### ISSUE TITLE
Social account address copy mechanism

### ISSUE THREAD

**Issue by egetekiner** [hicommonwealth/commonwealth#10348]
### Description

When a user create account and logs in via social authentication, the wallet address created for them is not copyable and/or visible for users. 

### Bucket ID

#10347

### User Stories / Acceptance Criteria

- The wallet address for social accounts should be displayed prominently in the top-right dropdown menu of the dApp.

- Users must be able to copy the wallet address directly from the dropdown menu.

- Ensure this functionality works across all devices and screen sizes.

- Provide clear UX feedback (e.g., 'Copied to clipboard' message) when the address is copied.

**Comment by dillchen** [comment]
should be addressed and on prod now
