### ISSUE TITLE
500 error on contest leaderboard

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#10350]
## Describe the bug

When user wish to see active contest leaderboard we have 500 error on api call

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

Master
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://qa.commonwealth.im/baseilija/
2. Create contest 
3. Fund contest and upvote 
4. Click on contest leader board 

## Actual behavior

```
https://qa.commonwealth.im/api/threads?bulk=true&page=1&limit=20&community_id=baseilija&includePinnedThreads=true&orderBy=mostLikes&contestAddress=0x1D2Abec6aa852C629e8AfFF49f90040b9D4F43d7
```

Returns 500 error with this payload
```
{status: 500, error: "relation "contest_ids" does not exist"}
error
: 
"relation \"contest_ids\" does not exist"
status
: 
500
```

## Screenshots / Video

https://app.screencast.com/ayHJGMRJ3yrtX

**Comment by rbennettcw** [comment]
@KaleemNeslit I could be wrong, but this appears to be a regression from one of your recent PRs. Please check the GetThreads query.

**Comment by rbennettcw** [comment]
@KaleemNeslit so the issue isn't just that line, but it's the fact that the count query includes the base query:
```ts
      const countThreadsQuery = models.sequelize.query<{ count: number }>(
        `
          SELECT COUNT(*) AS count
          FROM "Threads" T
          WHERE ${baseWhereClause}
        `,
        {
          replacements,
          type: QueryTypes.SELECT,
        },
      );
```

The query fails because the `contest_ids` relation isn't part of the base query– it was part of the original query.

I see what the intent was (to add pagination) and I'm working on fixing it.
