### ISSUE TITLE
Clean up mentions of individual chains

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#1035]
Refactor out mentions of specific chains by `id`, or chains by `network`. There are too many right now, including

- in the backend / address verification logic, all Substrate chains are named individually
- in the frontend address modal, CHAINS_WITH_CLI lists chains individually
- other places around the codebase - grep for stafi or plasm or kusama for example

It should be possible to basically only use ChainBase or ChainClass to look up chains functionality, e.g. wallet options (and we may be able to deprecate ChainClass too).

**Comment by jnaviask** [comment]
Still wish we had this.
