### ISSUE TITLE
Unread state bug for batched threads

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#1057]
- Create a thread in a community (eg Edgeware) as Account 1
- Log in as another account (Account 2) subscribed to new threads
- Mark all notifications read
- Return to Account 1 and create another thread
- Return to Account 2
- There is 1 unread notification for the thread, but it doesn't show as unread in the notifications list

**Comment by gdjohnson** [comment]
The behavior I'm seeing is:
- Any time I post a new thread, it doesn't show up in the notifications drop-down (despite the notif count being 1 higher)
- If I click on "See all notifications," the new notification is there
- If I then click on the drop-down component, the new notification shows up
- If I refresh the page (after all these steps), the new notification is no longer visible in the dropdown

Is this compatible with your experience? It seems to indicate that there may be a problem specific to the drop-down
