### ISSUE TITLE
Audit forum endpoints like editThread, createComment

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#1064]
Because of large additions to mentions, notifications, and version history logic across the forum, thread/comment creation/editing endpoints have ballooned to hundreds of lines of code and are becoming difficult to read and maintain. 

Scope of work:
- [x] List out thread loading endpoints, using information from https://github.com/hicommonwealth/commonwealth/wiki/Thread-loading-flow
- [x] Describe functionality provided by each endpoint and produce similar document (or update existing document).
- [x] Propose an updated breakdown of API routes for thread/comment/reaction viewing / creation / updating / deleting (write github ticket).

**Comment by jnaviask** [comment]
We need this ASAP

**Comment by rbennettcw** [comment]
Created wiki page to document descriptions of each forum endpoint: https://github.com/hicommonwealth/commonwealth/wiki/Forum-Endpoints-Audit-(WIP)

**Comment by rbennettcw** [comment]
Proposal ticket: https://github.com/hicommonwealth/commonwealth/issues/3989
