### ISSUE TITLE
Reactions popover disappears before a username can be picked

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#1091]
## Description

Hover over forum post reactions, a popover appears. That popover displays user components, but, when the mouse is removed from hover, disappears too quickly to be clickable. This can be confusing & frustrating for a user.

**Comment by zakhap** [comment]
@SpaceGoat97 this was merged, yeah?

**Comment by SpaceGoat97** [comment]
Yessir @zakhap
