### ISSUE TITLE
Change Manage Address Modal to show correct chain base rather than chain name

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#1163]
If a user is logged in, but does not have a wallet, it shows the chain name rather than the chain base

Make sure that this is capitalized.

![image](https://user-images.githubusercontent.com/5334557/117240587-27be9800-adff-11eb-8c85-580645350921.png)

**Comment by true-eye** [comment]
https://github.com/hicommonwealth/commonwealth/pull/1265
