### ISSUE TITLE
Polkadotjs extension is not recognized in localhost

### ISSUE THREAD

**Issue by true-eye** [hicommonwealth/commonwealth#1183]
## Description

Polkadotjs extension is not recognized in localhost

## *Who* is the bug affecting?

All supervisors

## *What* is affected by this bug?

Logging in

## *When* does this occur?

Logging in with polkadotjs extension

## *Where* on the platform does it happen?

Login modal

## *How* do we replicate the issue?

1. Go to homepage or substrate community page
2. click 'Login' and `Continue with wallet`
3. You can't see `Polkadotjs extension` in the list

## Expected behavior (i.e. solution)

It should display `Polkadotjs extension` option 

## Other Comments
The same codebase works on the released version. commonwealth.im

**Comment by raykyri** [comment]
This is broken in production too.

**Comment by true-eye** [comment]
Interesting, I couldn't reproduce this issue on the production.

**Comment by raykyri** [comment]
Seems to be fixed upon refresh 🤷
