### ISSUE TITLE
AAVE View Proposal Page Stylization 

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#1229]
## Description

See below: 
<img width="911" alt="Screen Shot 2021-06-21 at 12 44 21 PM" src="https://user-images.githubusercontent.com/16248081/122805203-6bc20b00-d28e-11eb-8946-3b11691b0ef4.png">

<img width="914" alt="Screen Shot 2021-06-21 at 12 43 47 PM" src="https://user-images.githubusercontent.com/16248081/122805149-5b119500-d28e-11eb-8503-7a41391b1202.png">

**Comment by gdjohnson** [comment]
@zakhap Is there a link to Adam's design docs, so I can pull hex + pixel-perfect info?
