### ISSUE TITLE
Discord link preview

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#1239]
When sharing a commonwealth.im link on discord, there is no preview.

**Comment by maxwellfoley3** [comment]
This is a tricky one. What we have looks like it should work in theory, but something must be slightly off. It's not Discord's fault, since it doesnt work on Telegram either. But I can't think of how I can test possible solutions and pinpoint the issue on localhost.

**Comment by maxwellfoley3** [comment]
It seems to have magically gotten fixed somehow
