### ISSUE TITLE
Integrate types into server-side models

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#124]
- Break all models out into their attributes
- Potentially look at usage with `io-ts` to do decoding/encoding of model properties
    - Decoding when we receive data in the route
    - Encoding when we send it back as a response

- Create a shared set of types between client/server

**Comment by jnaviask** [comment]
Note that I have a branch started for this: [jake.sequelize-typescript](/hicommonwealth/commonwealth-oss/tree/jake.sequelize-typescript).

**Comment by drewstone** [comment]
Sounds great @jnaviask I'll add it to the proper part of the sprint board.
