### ISSUE TITLE
Silent, address-based community invites do not give users the opportunity to accept TOS

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#1267]
We have [recently added the ability](https://github.com/hicommonwealth/commonwealth/pull/1268) for on- and off-chain communities to require TOS acceptance before joining a community.

Our address-based invite system automatically and silently registers new members, so that they are not shown the TOS nor given the opportunity to accept/reject them (by not joining). 

We'll need a new approach to address-based invites (e.g. making their flow similar to email-based invites) to ensure newly added users have this opportunity.

**Comment by zakhap** [comment]
We'll have to rethink our invite system or prevent auto-add/invites to communities with TOS.

**Comment by jnaviask** [comment]
Status on this?
