### ISSUE TITLE
Add X to TOS Banner

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#1279]
TOS banner is permanent currently. 

We want the banner to show when the user enters a TOS community, but have the ability to press an X button and it be closed for the rest of the time the user is in that community. 
If the user goes into another community with a TOS, the banner should come back. If the user goes back to the original community, the banner should also come back.

**Comment by true-eye** [comment]
@zakhap which branch is this? which community is TOS community?
