### ISSUE TITLE
Add interval/count based aggregator configuration to chain based notifications

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#128]
Certain chain based notifications occur every block such as:
- Block authoring
- TreasuryReward minting

We could add more configuration options to these chain events to aggregate certain chain events into a batch notification apriori (irespective of batching them for users as a UI thing).

For example, I could say I want:
- to batch every 10 treasury reward minting events into a single notifications
- to create a notification every 100 blocks instead or on every 100th event

**Comment by jnaviask** [comment]
Ongoing cc @timolegros.
