### ISSUE TITLE
Admins specific feature request

### ISSUE THREAD

**Issue by ShankarWarang** [hicommonwealth/commonwealth#1294]
## Description
This a feature request for admin specific options. It could save time if the 'Edit Stage' option made available inside the thread rather than just in the list view of discussions. Also, when you search an older thread, you can't edit stage tag from the search result list. Thus, finding an older thread by just scrolling turns out too much time consuming. (Workaround is to comment on the post so it gets up in the discussions' list and then tagging the stage.)

## *Who* is current scenario affecting?
Admins who update the discussion threads with stage tags.

## *When* does this occur?
Found out while tagging stage to the 2 months old OnFinality's thread.

## Expected behavior (i.e. solution)
1. Admins should be able to edit stage tag when the discussion thread is opened and not just from the main discussions' list.
2. Threads in search results' list should also have those 'v' (down arrow) options.

**Comment by jnaviask** [comment]
Still a good idea, cc @zakhap
