### ISSUE TITLE
Ensure invalid addresses trigger 404 & implement an updated 404 page

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#138]
Invalid address should 404, but just shows a spinner forever:
![image](https://user-images.githubusercontent.com/1273926/81145842-fb421880-8f2b-11ea-9a57-af8e3bf69e44.png)

404 page currently looks like this:

![image](https://user-images.githubusercontent.com/1273926/81145870-0d23bb80-8f2c-11ea-91ac-2c69cbad6211.png)

We can use the construct-ui empty state placeholder instead, with the x-octagon icon:

![image](https://user-images.githubusercontent.com/1273926/81145899-1b71d780-8f2c-11ea-835e-4083d104b19d.png)

**Comment by gdjohnson** [comment]
Any chance I can get more context on these tickets? Stack trace, the relevant files. E.g. I've spent 20 minutes and still have no idea where that spinner's coming from, and I'm kinda unclear what situations would get you to having an invalid address. When I corrupted my address in the backend, things loaded fine: 
![image](https://user-images.githubusercontent.com/22281010/82489418-9cde7380-9aaf-11ea-8805-6beba870142e.png)

**Comment by raykyri** [comment]
Yep, go to the profile for a valid address, and then delete a character off the end. You should get the spinner. How did you test by corrupting your address on the backend?

Are there are any other specific places where context would be helpful?

**Comment by gdjohnson** [comment]
Heh, I deleted a character off the end of my Edgeware address in postgres. I'll try now with changing it on the frontend, & message you about context.
