### ISSUE TITLE
Red error message upon trying to save newly uploaded avatar in Edit profile modal

### ISSUE THREAD

**Issue by 7racker** [hicommonwealth/commonwealth#1432]
## Description
Bug

## *Who* is the bug affecting?
I as a member of the Edgeware community. I tested on 2 of my member accounts. Could be affecting other members of other communities too.

## *What* is affected by this bug?
Getting the following error in red text at bottom of edit modal when trying to update my avatar. 

> column "id" of relation "IdentityCaches" does not exist

If I click Save, then nothing seems to happen. 
If I then close modal I don't see that my avatar has been updated.
If I reload the page I see that my avatar has been updated.

## Expected behavior (i.e. solution)
After clicking Save Changes button then 

1. the Edit modal should go away 
2. just the avatar should reload (not the full page) and show the new avatar.
3. a toast should appear saying "Changes have been saved."

**Comment by timolegros** [comment]
This is very likely related to the recent switch in chain-events systems. The new system uses an identityCache table in the database but neither the migration nor the model defines an id column so I'll investigate asap.
