### ISSUE TITLE
Search results/preview should prioritize thread titles

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#1449]
When a user types in a search string, threads that contain that string in their title are more likely to be pertinent to the searching user's interest.

![image](https://user-images.githubusercontent.com/22281010/135360169-449e7b30-d83e-40a4-81de-991387bd8f23.png)

**Comment by jnaviask** [comment]
Still open.

**Comment by jnaviask** [comment]
Discussions / Comment search now separate, so no longer relevant.
