### ISSUE TITLE
Notifications V3 - De-duplicate notifications in the UI

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#147]
- Identify notifications that have the same Type (new comments or reactions) and target (everyone commented/reacted on the same thread or comment), aggregating them into a singular row.
- When aggregate row is clicked, mark all sub-notifications as read.

[Link to spec in Notion](https://www.notion.so/hicommonwealth/Notification-V3-e7086804763845c4a99c2fa8a4de7c70#fe9bd260d58b41a88e0d41c944bd44c9)

**Comment by zakhap** [comment]
@drewstone are we okay with the deduplication happening in the UI on client, or did you want to discuss a server deduplication tomorrow during the eng. call?
