### ISSUE TITLE
Notifications V3 - Update notifications page with Construct-UI

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#152]
[Link to Notion Spec](https://www.notion.so/hicommonwealth/Notification-V3-e7086804763845c4a99c2fa8a4de7c70#dedf72df3994419fa3d74456236d92d7)

- There should be two Panes
    - Left Pane: List of Communities (which lists each community / chain)
        - if in a community / chain, only present that community / chain
        - Once we’ve clicked a community within the listing on the left
    - Right Pane: Listing of subscriptions
        - List of all subscriptions for that community chain (with
            - Mentions
            - ~~DMs~~
            - New Threads
            - Chain Notifs if applicable
        - Email Subscriptions
            - Frequency (toggle on and off)
            - Types of Notifs
            - Toggle for product Updates
            - Toggle for Hot Threads / Digests / Newsletter → (receive a sample?)

**Comment by raykyri** [comment]
Would it be possible to put together a PR for this without the titles? I think that would be greatly preferred to proposing one way to architect this or another. We can put the titles in afterwards.
