### ISSUE TITLE
"Don't see your token?" in Search Dropdown

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#1549]
In the searchbar, we should show them a button on the bottom that says "Don't see your token? Spin up a community for it!". Clicking that button, the user should be directed to the create community modal/page.

Bonus: open the ERC20 form by default

**Comment by gdjohnson** [comment]
@zakhap I think we need to spec slightly more... Right now, search bar stuff is scoped to the community the user is within; if there are no preview results, it asks the user if they want to search all of Commonwealth, and redirects them to a site-wide search results page.

In other words, the only time a user _would_ be able to search other communities, from a search bar, is on the logged-in landing page.

Do we want to only attach this "Don't see your token?" message to that landing-page-scoped search bar, for the time being? 

Furthermore, do we want to include a similar message/link to the Community tab of the Search Results page? It seems proper to be comprehensive in that way. We could even include it by default at the end of community results, so even if several near-matching token communities are listed, they have the option to spin up a community.

**Comment by liam-armstrong** [comment]
The next search version has a little less scoping by default (users are prompted to filter by their active community rather than forcibly scoped), but it still may be a hard to incorporate into the search preview window on the default search.

Otherwise, I do think it would be a nice addition to the community tab of the search result page, and also on the landing-page-scoped-bar as mentioned

**Comment by gdjohnson** [comment]
@liam-armstrong Good info, thanks for chiming in!

Given you're in the middle of search work, might be best for this ticket to wait; once you have a PR up, I can add the functionality on. You have any kind of rough ETA?
