### ISSUE TITLE
Set up scheduler & hooks to send emails

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#155]
Maybe these below steps are obsolete since we only have immediate emails right now?

---

- Add a daily Heroku scheduler job to trigger delayed email notifications
- Add a weekly Heroku scheduler job to trigger delayed email notifications
- Figure out how to grab plaintext from comments & threads @Raymond Zhong
- Actually send emails
- Change `sendBatchedNotificationEmails(models, 'monthly')`, put send hooks in the right places

**Comment by raykyri** [comment]
Merging into #568.
