### ISSUE TITLE
Can't generate invite link (404 response)

### ISSUE THREAD

**Issue by mikepsinn** [hicommonwealth/commonwealth#1644]
## Description
I can't generate an invite link. I get a 404 response.

![image](https://user-images.githubusercontent.com/2808553/149847800-dafb53c1-92d8-4f9b-9e42-9d4cf9df4a54.png)

## *Who* is the bug affecting?
Admins at https://commonwealth.im/curedao

## *What* is affected by this bug?
Creating invite link

## *When* does this occur?
After clicking create the "Get invite link" button

## *Where* on the platform does it happen?
in invite members modal

## *How* do we replicate the issue?

```
fetch("https://commonwealth.im/api/createInviteLink", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Microsoft Edge\";v=\"97\", \"Chromium\";v=\"97\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-requested-with": "XMLHttpRequest"
  },
  "referrer": "https://commonwealth.im/curedao/analytics",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "chain=curedao&time=none&uses=none&jwt=HIDDEN",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

## Expected behavior (i.e. solution)
Get an invite link

**Comment by jnaviask** [comment]
To investigate.
