### ISSUE TITLE
Resolve inconsistency between ws:// and wss:// URLs for nodes using Polkadot API

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#165]
The chain events system seems to expect node URLs of the form `ws://testnet1.edgewa.re`, while I believe the frontend API expects nodes of the form `wss://testnet1.edgewa.re:9944`.

If we change the node URLs in production to the former, the API will stop working and users will be unable to connect to chains. This might be hard to notice because CORS restrictions only apply when we are connected to a server with SSL, so this bug won't show up in development.

Possible solution 1: Munge the node URLs, specifically for Substrate chains, on either the client side, server side, or both.

Possible solution 2: Migrate the database to have separate client_url and server_url nodes. I feel like this is more scalable and easier to understand and generally a more straightforward position.

**Comment by jnaviask** [comment]
Responses from Jaco re node setup:

```
* does it have an appropriate (non-default) rpc-cors?
* does nginx allow all?
* is there any other proxy (e.g. cloudFlare rules)?
```

My responses:
* We're not passing in any rpc-cors flags.
* We don't have nginx up _at all_ as far as I can tell.
* Not sure how cloudflare is configured.

Let's discuss this.

**Comment by drewstone** [comment]
@jnaviask did I link this to the correct PR? It sounds like this is what you're currently working on.

**Comment by jnaviask** [comment]
Unfortunately this inconsistency was never resolved, we simply process the URLs differently on either side. wss:// still doesn't work on the server despite my PR.

**Comment by raykyri** [comment]
We're using wss:// on the client now, and ws:// on the backend, and it seems like this works?
