### ISSUE TITLE
Show profiles for the same address on other chains/communities

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#178]
Add a panel to the profile page that shows related addresses on other chains

This would require
1. adding an index of related chains as a property to each chain
2. adding a UI module that looks up related chains, and then re-encodes the current address to other chains (using Address.from) at which point it could just be passed into m(User) as a tuple of [address, chain]

And then, we’d want the UI module to look up whether you have created the profile on other chains using getProfile. If you have, it would display “Go to profile”. If you haven’t, it would display “Create a (KSM) profile” for you

**Comment by jnaviask** [comment]
Still need to fix this one up... But it is done.
