### ISSUE TITLE
Resolve onchain identity flashes when moving between pages, by implementing a cache for on-chain data

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#182]
Right now, when we move between pages, there is a flash when on-chain Substrate identities are loaded, which is visually disruptive / reduces the feel of polish on the site.

- Go to discussions page
- Go to any other page, e.g. a specific discussion page
- Return to discussions page
- On-chain checkmarks take a few msec to appear

We should try to eliminate the flash by implementing a cache at the frontend controller level for on-chain identities.

On how to architect this, I think it would be nice to take a first pass at a technical spec for how this would work, and then review it with @drewstone to confirm everything makes sense.

**Comment by gdjohnson** [comment]
@drewstone Maybe I make a pass at a spec with some potential approaches, and we review at next week's eng meeting?

**Comment by gdjohnson** [comment]
@raykyri To be clear, is this "flash" the empty forum-container that momentarily exists before the page content is loaded? Not totally sure I follow otherwise. Are there specific pages or cases when this happens, so I can compare, or is it site-wide?
