### ISSUE TITLE
Tagging user in text editor fails

### ISSUE THREAD

**Issue by paplco** [hicommonwealth/commonwealth#2047]
## Description
Bug report. Error message when tagging users in posts. 

Tried tagging various users. Tried logging out and back in. Tried Markdown and RichText mode. Tried clearing cache. Tried restarting browser. Tried saving and then editing post again.

## *Who* is the bug affecting?
End-users.

## *What* is affected by this bug?
Posts engagement.

## *When* does this occur?
Selecting user for tagging from auto-complete user select menu.

## *Where* on the platform does it happen?
In text editor. 

## *How* do we replicate the issue?
Try tagging a user.

## Expected behavior (i.e. solution)
User is tagged in post.

## Other Comments
Brave browser, Mac OS

![Screen Shot 2022-08-10 at 8 04 02 AM](https://user-images.githubusercontent.com/9093152/183889341-513b9187-216a-4441-929f-8d41f8030439.png)

![Screen Shot 2022-08-10 at 8 04 21 AM](https://user-images.githubusercontent.com/9093152/183889241-7cf4aab9-2774-4aa5-a9fb-9e36642049a8.png)

**Comment by jnaviask** [comment]
To investigate.

**Comment by jnaviask** [comment]
Fixed post-react.
