### ISSUE TITLE
Refactor refreshAll Controller Methods

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#222]
## Description
Per [recent PR comments](https://github.com/hicommonwealth/commonwealth-oss/pull/202#discussion_r425875416) and [Dill's followup](https://hicommonwealth.slack.com/archives/CEZBFR3TR/p1589559592001700?thread_ts=1589556129.000800&cid=CEZBFR3TR).

Right now, you have to pass `null`s to forum controllers' `refreshAll` methods, due to its params structure:
```
public async refreshAll(chainId, communityId, reset = false) {
```
The alternative implementation gestured at in the comments does not ameliorate this situation, as it is more eccentric and higher entropy (sometimes you have to pass a null, sometimes you don't, and distinguishing undesirable complexity). 
```
public async refreshAll(communityId?, chainId?, reset = false) {
```
Some possible implementations: 
1. passing an object, `activeEntity`, as first argument, which contains either a chainId or communityId key
2. having a single id param, `activeEntity`, which is either a community or chain, and having some parsing logic which distinguishes (since the function needs to know which is which, for making db calls)
3. replacing the chainId/communityId param couple with an activeEntity/type couple, e.g. `(activeEntity, entityType, reset = false)`, which seems a cleaner (read: more legible) way of implementing the first approach
4. doing nothing (you always pass null for the neglected argument)

## *Who* is this affecting?
Coders! 

## *When* does this occur?
Whenever a page is refreshed, and forum content is re-fetched.

**Comment by drewstone** [comment]
we could optionally use object notiation for these methods?

**Comment by gdjohnson** [comment]
@drewstone by object notation, something like `refreshAll({params})`, or other?

**Comment by drewstone** [comment]
Yep:
```
await this.app.threads.refreshAll({ chain: 'edgeware', community: null, reset: true });
```
```
refreshAll({ chain?: string, community?: string, reset: boolean }) {
   ...
}
```
