### ISSUE TITLE
Create a migration to update Substrate node URLs

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#224]
When migrating from the current prod database, the old ChainNode URLs are used, causing chain connections to break. Whoever deploys prod should not have to remember to change the database manually nor should developers have to reset their DB; we should write a find and replace migration instead:

- wss://mainnet1.edgewa.re -> ws://mainnet1.edgewa.re:9944
- same for mainnet2
- possibly same for Kusama

**Comment by raykyri** [comment]
@drewstone tagging you on this since Jake is gone right now, but feel free to re-assign

**Comment by drewstone** [comment]
Yea, my only qualm with this is we should get secure websockets to work, no? I had thought we previously used `ws://...:9944` and had chhanged.

**Comment by raykyri** [comment]
Let's use ws:// for now and move to secure websockets when we merge to master then.
