### ISSUE TITLE
Refactor tags code into a tags controller & break up tag_selector.ts

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#231]
1) Move the client-side code used for fetching and managing tags into a controller. 

This way, different views can access the current set of tags, without having to individually load it into their state.

This is blocking several design changes, so we should look at it asap.

2) The tag selector code is currently used for the sidebar AND the tag page. This is confusing and forces us to introduce lots of logic to patch edge cases. We should have separate files for the sidebar vs the page.

Since we should be fetching a list of tags from the tags controller, there should be minimal duplication of code.

**Comment by raykyri** [comment]
Hey guys - adding this for next week, let's talk about it on Monday.

**Comment by drewstone** [comment]
And include caching of tags so refetching doesn't occur each time.

**Comment by raykyri** [comment]
Closed as not addressed. Will make another ticket to handle this.
