### ISSUE TITLE
The "Add New Address" modal flow is buggy and needs an overhaul

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#240]
## Description
When joining a new community, users are prompted to add a new address, via the address modal flow. When this flow completes, however, the data does not update, and users are still told they must add a new address (the recent addition does not render as a selectable option). This is only fixed by a page refresh.

EDIT: 
from #bugs:
- in the subkey flow, after signing with a secret phrase, the modal preemptively closes before the flow is completed
- it inconsistently renders the chain address options: instead of consistently rendering the full list, it will show only a few chain cards

Since we will be de-commissioning this modal soon in favor of a page-based form, it may make sense to deal with these issues *via* the decommission, rather than (potentially redundantly) in advance of it.

**Comment by raykyri** [comment]
Putting this on the current sprint board, I agree this is a priority to fix

**Comment by gdjohnson** [comment]
from #bugs:
- in the subkey flow, after signing with a secret phrase, the modal preemptively closes before the flow is completed
- it inconsistently renders the chain address options: instead of consistently rendering the full list, it will show only a few chain cards
