### ISSUE TITLE
Investigate Node 18 memory settings on Heroku

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2438]
Given our best working hypothesis that ts-node startup are running afoul of the dyno's memory settings, we need to test these settings in Heroku to confirm if that is the problem or not.

**Comment by CowMuon** [comment]
What else do we need to do here? @timolegros This seems closable. outstanding concern here is unknown unknowns around deploying 18 to production.

**Comment by jnaviask** [comment]
Clear to merge #2405.
