### ISSUE TITLE
Roles and Permissions 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2440]
Work being done on [Roles & Permissions](https://www.notion.so/hicommonwealth/Roles-Permissions-System-0724318eea244204955d758190240cf6) C1.S2

- [x] Set up routes
- [x] Create reusable functions
- [ ] ~~Community Based Permissioning~~ Out of scope.
- [x] fixing remaining errors (9 type errors)

**Comment by CowMuon** [comment]
We also need to configure Kong to consume our OAS, using the community plugin openapi-2-kong, and add role handling routes to Swagger while keeping our sites on making authorisation (aka perms) a standalone library or service, but making sure we don't block shipping API v2 this week (to add post requests to end users) and we also said we would ship R&P this sprint, so let's identify what work needs to carry over to next sprint (C1.S3) @jnaviask

**Comment by rvmelkonian** [comment]
Just arranging a time to sycn with Kurtis now.

**Comment by jnaviask** [comment]
Current status:
- Created some CRUD permission routes to use in integration tests, so e.g. admin can update permissions.

Outstanding:
- Writing the integration tests.

Then, should be good to go.

**Comment by jnaviask** [comment]
Fixing type errors, hopefully ready to review EoD.

**Comment by CowMuon** [comment]
Sounds like this will be ready for QA tomorrow 1/13, @rvmelkonian is fixing/testing remaining 9 type bugs.
