### ISSUE TITLE
Layouts in Views

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2447]
Layouts in views is a problem. The layout component in our views seems like it's violating single responsibility with all the stuff it's loading, and needs to be cleaned up. This is just a placeholder ticket for now as this needs to be aligned with React Conversion epic, so tagging as such more for visibility, as it's not required for milestone.

**Comment by CowMuon** [comment]
What's the status on this?

**Comment by affordances** [comment]
I need a walkthrough of the actual problem because it's not clear to me from the description.
