### ISSUE TITLE
Make Context available to Components

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2454]
React expects Context to be available down through all child nodes, and React Router facilitates this by making match, location, and history context properties available via props. Currently, context doesn't seem to be available to child nodes? We need to decide how to pass context. Do we want to use Context.Provider (from Context API) to wrap components and pass context in as a prop? (to be consumed with useContext hook)? Do we want to use react-router-dom to expose context directly in the Route component so we handle routing and context together? 

Whatever we do, we need to decide how we are going to handle this and document what the solution looks like to be implemented. (In any case this does mean [Implement Routing Layer](https://github.com/hicommonwealth/commonwealth/issues/2434) is significantly more than 3 point complexity.

**Comment by CowMuon** [comment]
Where is our approach for this documented? Or do we prefer to reply on tribal knowledge and bus factor for our front end development?  

Where is React architecture for the app being documented?

**Comment by jnaviask** [comment]
Note that `this.context` and other context-related functions are available in ClassComponents, as they're extensions of the React.Component class. So this may turn out to be a non-issue. Would like to see examples of non-working things so we can clearly spec out the required tasks to mark this as closed.

**Comment by masvelio** [comment]
@MuonShot I don't understand why we would need context? 

> React expects Context to be available down through all child nodes
It does not

> and React Router facilitates this by making match, location, and history context properties available via props
React router has own hooks for functional components for that like `useLocation`, `useParams` etc. For class components we have HOC that supply components with proper props related to router

Generally React Context is a simple global state for react app and we don't need to implement it now as we are not gonna keep any data in the context (at least now, until we figure out how to get rid of controller/store layer).

@jnaviask `this.context` will not work until we provide the context but the class component. But this is not the way we should go. I mean, we don't need context now and if we would need in the future, we should try to use it with function components. 

Imo this task should be closed.

**Comment by CowMuon** [comment]
Definitely a 100 from me. We have said we didn't want to use Context API just because it's there, but rather only if we have identified a specific requirement that we can only meet with Context. (In fact, there's a section on reactantipatterns.com for [over-reliance on context](https://reactantipatterns.com/#context).
