### ISSUE TITLE
Reactify all the Things

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2455]
We need a list of remaining things to be Reactified in order to the Interop layer to work. For example we already know we have to [make context available](https://github.com/hicommonwealth/commonwealth/issues/2454), what else is needed for Interop layer to work? Let's use this issue, in conjunction with the main [React Conversion Plan](https://github.com/hicommonwealth/commonwealth/issues/2433) issue a a place to record what's needed. 

Moreover, we need this list not just for implementing, but to insure we are properly validating the solution as feasible. At this point (1/10) feasibility is still not confirmed.

**Comment by CowMuon** [comment]
Do we want to use this issue for remaining page conversions? @zakhap @affordances

**Comment by affordances** [comment]
It's plausible that the entire UI will be Reactified this week, but I'm not sure what that leaves re: controllers and so on. The data layer is what needs conferencing about.

**Comment by CowMuon** [comment]
The data layer may require fewer changes than we had previously discussed. In theory, everything should "just work"
