### ISSUE TITLE
New profile/Edit new profile pages

### ISSUE THREAD

**Issue by bonnichiwa** [hicommonwealth/commonwealth#2456]
## Description
Adding new profile page and edit new profile page

Notion:
https://www.notion.so/hicommonwealth/PR-1-NewProfile-Page-EditNewProfile-Page-8303af44aedd468eb09e10ef803ea24a

New profile page:
https://www.figma.com/file/SAHxCcKCul9zpXMZKuGzyW/Profile-%26-Management?node-id=943%3A46909&t=l4xNS6nsTHuIHrUH-0

Edit new profile page (designs seem to have been updated recently so the actual implementation looks a bit different):
https://www.figma.com/file/SAHxCcKCul9zpXMZKuGzyW/Profile-%26-Management?node-id=1582%3A115578&t=l4xNS6nsTHuIHrUH-0

To see the new profile page: `/profile/<address>`
To see the new edit profile page: `/profile/<address>/edit`

## How has this been tested?
- Tested new pages on staging
- Made sure editing capabilities are only available for user logged in
- If trying to access editing a profile that's not yours, will be redirected to profile to view only

## Does this PR affect any server routes?
YES

## If this PR affects server routes, what are the security implications?
New routes added to get/edit new profile

## Have proper tags been added (for bug, enhancement, breaking change)?
YES

## Additional notes -
Some discrepancies between design and implementation:
- Actions for comments/threads (edit and delete) have not been implemented
- Attempted but code gets messy because the comments/threads are not stored in the store as profile is unscoped from a community

- "Show more" for bio was not implemented
- Attempted but the function `renderQuillTextBody` was not functioning as expected, adding in `cutoffLines` as a param did not work. For now I think it's fine to not truncate the bio as we don't have the Badges and Crowdfunds section underneath it

Features that have been omitted after discussing with Zak:
- Communities and Addresses
- Badges and My Crowdfunds
- Delegate and Follow button

**Comment by CowMuon** [comment]
Blocked by #2819
