### ISSUE TITLE
Polkadot API types error setting on-chain identity

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#246]
![image](https://user-images.githubusercontent.com/22281010/82706265-3b510d00-9c47-11ea-9397-acc564d71ac6.png)

**Comment by raykyri** [comment]
Does this still happen? Maybe it has been resolved by an API upgrade.

**Comment by zakhap** [comment]
This seems to have been resolved by the upgrade. It also looks as though it might have been an 'insufficient ability to pay fees' issue, but that seems to be giving a better, user-readable error in the client now.
