### ISSUE TITLE
Set up database logging for performance in Datadog

### ISSUE THREAD

**Issue by jalfredr** [hicommonwealth/commonwealth#2463]
In preparation for further refactoring and architectural changes for performance improvement, monitoring services need to be set up in Heroku and Datadog.
1. Configure Heroku permissions and agent values
2. Set up Datadog dashboards using new sources
3. Fully document final process for reproducibility

Acceptance Criteria: 
- [ ] Heroku changes confirmed and documented.
- [ ] DB performance monitoring having live outputs from Postgres on at least one functioning dashboard
- [ ] Document "final process"

**Comment by CowMuon** [comment]
Jesse needs to catch up on documentation and publish it. What is key deliverable here? @jalfredr

**Comment by CowMuon** [comment]
Also what is meant by "final process" in the description?
