### ISSUE TITLE
Create missing RoleAssignments for 1inch

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2475]
## Introduction

We performed a discourse import for 1inch around 1:35 PM EST on 1/12. The `Users` and `Addresses` were migrated properly, but the full set of required `RoleAssignments` were not created.

The deliverable here is the creation and execution of a database command to create the missing `RoleAssignments`, without blowing away the existing + correctly created RoleAssignments.

## Useful Queries

To query the addresses created:

``` SELECT COUNT(*) FROM "Addresses" WHERE ghost_address = true AND chain = '1inch';```

To query the `CommunityRole` on 1inch that we will need to assign (should return id 2335):

```SELECT * FROM "CommunityRoles" WHERE chain_id = '1inch' AND name = 'member';```

To query the number of `RoleAssignments` that were successfully created (should be 183, as per the [members page](https://commonwealth.im/1inch/members)):

```SELECT COUNT(*) FROM "RoleAssignments" WHERE community_role_id = 2335;```

**Comment by zakhap** [comment]
testing this on a db dump shortly

```
INSERT INTO "RoleAssignments" (community_role_id, address_id)
	SELECT cr.id as community_role_id, a.id as address_id
	FROM "Addresses" a
	LEFT JOIN "CommunityRoles" cr
	ON cr.chain_id = a.chain
	WHERE a.chain = '1inch' AND ghost_address = true
;

```
