### ISSUE TITLE
Replace current popover components with popper.js

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#2480]
We want to remove construct but in the same time we want to keep the functionality of our popover component. We can't leverage react yet so there is an idea to use https://popper.js.org/ 

Would be good to check if there is any other lib that could be considered. 

[slack thread](https://hicommonwealth.slack.com/archives/C04D82MDZ3N/p1673622741697939)

**Comment by CowMuon** [comment]
This was bypassed bc MUI-base already uses poppsers.js.
