### ISSUE TITLE
Governance Proposals currently by default have their threads set to read only

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#249]
![image](https://user-images.githubusercontent.com/5334557/82838503-76974a00-9e9a-11ea-81a1-e3712b73b851.png)

**Comment by dillchen** [comment]
@zakhap not currently on the sprint for you, but this feels like something that you'd be able to address as you write more tests / coverage for createThread routes.

**Comment by thomivy** [comment]
Signaling on CW  — all Signals are read_only and users cannot comment
