### ISSUE TITLE
Add page: (View) Contracts List page (3/4) 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2494]
Displays all contracts that community has connected. 

Spec: [View Contracts List page](https://www.notion.so/hicommonwealth/Proposal-Templates-Spec-Bet1-0-1-1de19ef80d9a4bce80fbe686c34c6c63#7e3bc4527e4c43d99a68341d756fbd86) 

Also add:
- add/edit template modal
- delete contract/template modal

**Comment by masvelio** [comment]
I am bumping up to 5, mainly because apart from contracts list page, add/edit template modal has to be done and delete/contract template modal. Quite a lot of components

**Comment by alexyoung23j** [comment]
Completed
