### ISSUE TITLE
Node 18 Upgrade

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2497]
Not entirely clear what happened to our Node 18 branch that we were testing on Frick. It seems like Node was reverted back to 14 on that branch, which is still called "bump-node"   🙃

We need to cut a new branch for Node 18 and get it up on Frick. Ideally we will be testing this week (S3) and then upgrading production to Node 18 on Monday 1/24 (Cycle 1, Sprint 4) 

For this week (S3) ideally everyone will get up and running on Node 18 locally.

**Comment by timolegros** [comment]
Done.
