### ISSUE TITLE
Webpack > Rocket Loader 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2498]
Cloudflare runs rocket loader to serve our content. This lazy loads. The issue with this is that webpack already handles it, and is more intelligent about it. The Webpack runtime knows which bundles depend on each other. As a result of the the "uninformed" rocket loader lazy-loading, rocket loader loads in bundles one by one instead of in parallel like webpack would normally do

**Comment by jnaviask** [comment]
Fixed in #2482
