### ISSUE TITLE
Add page: Add New Template page (2/4) 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2499]
"Where Norf can paste a blob (and get validation)"

[Proposal Templates Tech Spec > Add New Template Page](https://www.notion.so/hicommonwealth/Proposal-Templates-Spec-Bet1-0-1-1de19ef80d9a4bce80fbe686c34c6c63#cf0ff93ebe2c4dbe9b00ddd4add354dd)

**Comment by alexyoung23j** [comment]
Needs whitespace removal
