### ISSUE TITLE
Add ERC-1155 to Token Balance Cache

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2503]
TBC is typically extended by adding a new "BalanceProvider" or BP. Currently, we bake ERC20 and ERC721 into a single 
 EthTokenBalanceProvider in `ethToken.ts`. 

To Add ERC1155 we'll have to do a few things:
1. Generate the type files for an 1155 contract (+ factory) => add them to `common-common/src/eth/types`. 
2. 1155 require a tokenId to check balance => add it optionally to the `EthBPOpts` and to `opts` 
3. Add a check to throw an error if erc1155 and not providing all the options needed for the case. 
4. Validate the tokenId provided as correct using Web3 utils (if possible)
5. Connect to the ERC1155 factory as api
6. Pass in address and tokenId arg to balanceOf call. 

We'll want to write tests in the tests folder.

**Comment by zakhap** [comment]
Just finished editing the stub above! 

For using on CW in the server, we'll do that as a second PR.

**Comment by dantrinh** [comment]
Validate the tokenId provided as correct using Web3 utils (if possible)

Is only possible if ERC1155 extends a certain abstract contract called ERC1155Supply. So In the most general case, the erc 1155 will not have this functionality. Web3 utils checking would not work

**Comment by CowMuon** [comment]
Changed assignee to Zak for full e2e testing.
