### ISSUE TITLE
Confirm needed components for Proposal Templates 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2505]
- [x]  Confirm what components are needed for each of the 4 new pages added in Proposal Template feature.  (by page) 
- [x]  Confirm what NEW components are needed for these pages that are not in our extant pattern library. 

Status: Blocked, waiting for delivery of Lo-fi page mocks. ETA: EOD Tue 1/18

**Comment by alexyoung23j** [comment]
Done
