### ISSUE TITLE
Implement updated community switching logic (dropdown community switcher, popup for selecting account after switching to new community)

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#252]

**Comment by dillchen** [comment]
I think the issue that I'm mentioning will be captured as Raymond works on this, but wanted to capture again as ran into while working on QA.

Starting from a `yarn reset-server`, there is no app.vm.activeAccount that gets set for a community. The following flow in particular.
1. Start on homepage
2. Click visit on any chain / community
3. In community, no `app.vm.activeAccount` is set in header.

This is even the case if a user has an address linked and that address has been added as a role within the community (through Postico)

Seems like this should be solved with the "in community" address switcher / default address selector. So the call to `updateActiveAddresses` is able to set the default address on the switch from homepage to community.

**Comment by raykyri** [comment]
Thanks for the report. Yes, this is being resolved here.
