### ISSUE TITLE
Add MolochDAO V3 to Token Balance Cache

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2524]
STUB: Following on work adding ERC-1155 to Token Balance Cache we'd like to add MolochDAO V3 as well. 

https://baal-docs.vercel.app/

**Comment by zakhap** [comment]
HMMM if TBC is already handling ERC20, and MolochDAOV3 token's are ERC20s => Then this might be moot.

**Comment by dantrinh** [comment]
@zakhap According to "In Moloch v3, both membership and loot shares are ERC20 tokens." from https://baal-docs.vercel.app/

**Comment by zakhap** [comment]
BalanceProviders for for entire classes/standards of tokens, so if there's nothing special we need to do to query MolochDAOV3, then we shouldn't special case an erc20 provider for them.

**Comment by dantrinh** [comment]
that makes sense, TBC ethToken.ts should be able to handle querying for the MolochV3 tokens!

**Comment by CowMuon** [comment]
Just need to make sure create community route, run through with Kurtis to make sure we can create a community to handle that case. 

NB: We still don't have member assigning based on roles (automatic permissioning) that's still manual until [#2526](https://github.com/hicommonwealth/commonwealth/issues/2526) lands (not until Cycle 2)
