### ISSUE TITLE
For You page updates

### ISSUE THREAD

**Issue by bonnichiwa** [hicommonwealth/commonwealth#2533]
Design: https://www.figma.com/file/6Wzvny1DGv5TB6Hzbk5a3u/For-You-Page?node-id=31%3A1035&t=VlpgJDfhkM56evsW-0

Notion:
https://www.notion.so/buildcommon/PR-4-For-You-Page-Up-to-2-days-Bonnie-b6bcac923e714f5c848888153e224dbf

**Comment by CowMuon** [comment]
Should be reviewed and merged today.

**Comment by jnaviask** [comment]
Any reason this PR was closed?
