### ISSUE TITLE
Fix duplicate addresses 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2534]
STUB: Placeholder for work to fix duplicate addresses.

**Comment by timolegros** [comment]
Relevant future spec: https://www.notion.so/buildcommon/Address-Refactoring-Tech-Spec-5f0f21e54ce4415391017d2c4624af6f
Relevant past analysis: https://www.notion.so/buildcommon/Addresses-DB-Cleanup-5b4ecb99a9994da485bb00d1fe36af53#37d10c36dbcc4b639d8bb44c1bb6fadc

**Comment by timolegros** [comment]
Some quick stats for context.

There are 10400 duplicate addresses (10188 if excluding duplicate invalid addresses).
```SQL
SELECT COUNT(*)
FROM (
    SELECT user_id,
           address,
           chain,
           ROW_NUMBER() OVER (PARTITION BY LOWER(address) ORDER BY created_at) AS row,
           ROW_NUMBER() OVER (PARTITION BY LOWER(address) ORDER BY created_at DESC) AS reverse_row
    FROM "Addresses") dups
WHERE dups.row + dups.reverse_row > 2 AND dups.row != 1;
```
Additionally, there are 979 invalid addresses (some of which are also duplicates). These addresses contain non-alphanumeric characters.
```SQL
SELECT COUNT(*) FROM "Addresses" WHERE "address" ~ '[^a-zA-Z0-9]';
```

**Comment by jnaviask** [comment]
See #2755 for details on first steps here, prioritized over #2712.

**Comment by timolegros** [comment]
Closing in favour of the new ticket #3072
