### ISSUE TITLE
MerkleRoot to Token Contract

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2555]
## Description

We want to be able to take a Merkle Root and be able to use it to mint tokens. 

We want to be able to use a factory contract (one for each) for ERC1155, ERC721, ~and ERC20s~, passing in the MerkleRoot and other needed args for the contract, and to produce a new token with the proper claiming/distribution mechanism (based on the root!). 

We will want this to be testable!

**Comment by dantrinh** [comment]
Spec: https://www.notion.so/buildcommon/MerkleRoot-Verified-Erc20-721-1155-Factory-Contracts-e5b2f367ce984c13a9165be85217267b

**Comment by dillchen** [comment]
is the story point estimate still accurate?

**Comment by 0xdantrinh** [comment]
I have to update, it is taking longer as expected because had to figure out how to implement and implement delegate.cash. As well as refactor out our old merkle contracts

**Comment by CowMuon** [comment]
Zak and Daniel talked about additional features such as support for delegate cash. Daniel designing so contract is not huge monolith.
