### ISSUE TITLE
Generalize Token Balance checking and add to API

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2565]
Now that we have added 1155 to TBC, we need to generalize how TBC handles chain calls. Specifically, we need to define the shape for API calls made to TBC to include:

- [x]  -chain node id ie what kind of chain is being checked. This should also give us our basis for verifying the requested balance provider is valid for that chain.~ 
- [x]  ~Need to be able to submit an array of addresses, not just a single address (which is current behavior)~ 
- [x]  ~Balance provider ID which needs to be validated against chain node. If balance provider is the chain's native token then contract address is not needed. (Apparently Jake already baked this in.)~ 
- [x]  ~Need a way to handle additional args that particular chain node data providers (eg. token_id in 1155 contract) This is shaped according~

Path forward here should be after adding this to API, then pointing common app to use new API version. Open questions around what if any interruptions should be expected(?)

**Comment by timolegros** [comment]
New TBC addresses these points. Additionally, once https://github.com/hicommonwealth/commonwealth/pull/6105 is merged, we no longer expose a public route for fetching balances. This means we no longer have a need for the concept of a balance provider.
