### ISSUE TITLE
Fix root_id 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2575]
Placeholder for work to fix root_id issue. 

Sprint 5:
- [x] @zakhap to write PRD
- [x] root_id BackEnd cleanup (data clarity) 
- [x] minor UI fix to add backlinks (but comments on proposals needs some UI to show backlinks)

Down the road:
- [ ] Refactor client side for better usability -> post-React

**Comment by zakhap** [comment]
Context: https://www.notion.so/buildcommon/Proposals-have-Threads-Only-no-comments-e104c7c84b3a435cbf26c899b86f49d4

**Comment by zakhap** [comment]
- [ ] fix query in `viewUserActivity.ts`

**Comment by kurtisassad** [comment]
view_count also needs to be refactored due to it relying on root_id. It was decided we would remove the table and move the view_counts as a column in the threads table instead.

**Comment by CowMuon** [comment]
Well here we are again.
