### ISSUE TITLE
Snapshot Notifications

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2578]
- [x] Complete [Snapshot Notifications TechSpec](https://www.notion.so/buildcommon/Snapshot-Notifications-Specification-2a4e54b9209b455cbbf522eba92a477a) (Here is [PRD](https://www.notion.so/buildcommon/Snapshot-Notifications-Rollout-944fadfdb38946d2a24a160558b94da0)) 
- [ ] Active snapshot proposals on overview page
- [ ] Add backlinks to all threads talking about proposal on proposal page.

**Comment by alexyoung23j** [comment]
Testing on staging- Can I set the staging consumer to the same queue as the prod consumer? That way snapshot events are actually handled. Want to make sure that doesnt break anything
