### ISSUE TITLE
Better Analytics Dashboard 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2580]
Analytics Dashboard Improvements needed (Community/Admin facing) 

- [ ] Clean Up analytics dashboard page
- [ ] Better batched columns
- [ ] Load time 
- [ ] Most active users
- [ ] For Each Topic, show comments, threads by day, week, month.
- [ ] Weekly Email with (Forum and Gov Section) 
- [ ] Analytics API 

(Sprint 6) 
pair: @affordances

**Comment by jnaviask** [comment]
Dupe of #2857
