### ISSUE TITLE
Community Homepage/Feed

### ISSUE THREAD

**Issue by bonnichiwa** [hicommonwealth/commonwealth#2597]
Notion doc: https://www.notion.so/buildcommon/PR-6-Community-Homepage-Feed-9485ab4f4c384722b84ad1a518acf1c8

**Comment by CowMuon** [comment]
Need spec. Zak will work on this today (2:00ET?) Let's do this work on the React branch (`master-react`) 
In the mean time, @bonnichiwa please help @affordances with the components needed for this page.

**Comment by zakhap** [comment]
Step 1 will be to work off the `merge-master-react` branch, cleaning up, reactifying/making work the UserDashboard components. These are the core components that will be used in the community homepage.
Step 2, once the spec is written, we will begin to work on the CommunityHomepage (more details to come)

**Comment by CowMuon** [comment]
Hoping this will have a PR today.
