### ISSUE TITLE
Add `Last Active` Column to RoleAssignments

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#2607]
Right now `Last Active` exists on addresses, as addresses get deduped, we won't be able to see community specific activity on a community. This does not let us run queries / analytics on a community-specific basis for visits

1. For internal analytics
2. Productized analytics for communities

Should be logged on visit to a specific community by a logged in user

Perhaps this is not the specific solution we'd want to move forward with, but tracking specific per community behavior is desirable

---
For:

1. Active (visits + actions: threads, comments, reactions etc)
2. Engaged (actions only)

**Comment by zakhap** [comment]
Let's group this with the adding of timestamps to `chains` as well. What other activity metrics do you want available? Would be best to understand it as a more comprehensive task (as it intersects with Address refactor + Chain=>Community + Roles/Permissions + "forum domain cleanup").
