### ISSUE TITLE
Utility batch staking functionality calls

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#261]
Similar to the Polkadot API, we can batch a bunch of calls into a single transaction. Namely, valiating/nominating under one umbrella.

**Comment by iqraabdulrauf** [comment]
Hi Drew, 
Can you please elaborate the requirement like where do you want to batch a bunch of calls ,
we have a file namely staking.ts at location '/hicommonwealth/commonwealth/client/scripts/controllers/chain/substrate/staking.ts', is it required to change those  calls ?

**Comment by drewstone** [comment]
It wouldn't be changing calls in that controller but creating new ones that execute the entire nominating/validating flow. I will likely include these sorts of tasks in the new phase 2 spec so don't worry about it yet :)!
