### ISSUE TITLE
Lazy Load Chains

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2617]
## Description

Context: https://github.com/hicommonwealth/commonwealth/issues/4976
Related to: https://github.com/hicommonwealth/commonwealth/issues/8756

Currently, we return all communities on `/communities` route, and query `/nodes` to get node data of all chains, which is called during app init. 

This causes multiple issues with page-load-speed/db-load etc, and most of this data is not needed.

With our recent trpc changes including of addition of get communities list and by-id routes and the decoupling of frontend chains by id state in 8779, we can query `/communities` only where its needed (the communities explore page) and deprecate the `/nodes` api.

### Engineering Requirements

- Remove calls to `/communities` and `/nodes` from `packages/commonwealth/client/scripts/state/index.ts`
- In the communities list page, implement the new filter params and pagination, and remove the old communities filter logic.

**Comment by NakulManchanda** [comment]
with caching time will be slashed to ~300ms
https://github.com/hicommonwealth/commonwealth/pull/3864

**Comment by mzparacha** [comment]
Will also be refactoring to use the newer `/communities` trpc route

**Comment by mzparacha** [comment]
Updated the ticket description to reflect the current app state and necessary changes.

**Comment by mzparacha** [comment]
Blocked by: https://github.com/hicommonwealth/commonwealth/issues/8882

**Comment by mzparacha** [comment]
Completed https://github.com/hicommonwealth/commonwealth/issues/8882 in https://github.com/hicommonwealth/commonwealth/pull/8877, https://github.com/hicommonwealth/commonwealth/issues/8882 is not a blocker for this ticket now.
