### ISSUE TITLE
Add failing tests for Token Gating by Rule 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2620]
Please refer to Token Gating by Rule [Tech Spec](https://www.notion.so/buildcommon/Topic-Gating-by-Rule-662359ad00614b12b4e9b7f436efe395) > [Testing](https://www.notion.so/buildcommon/Topic-Gating-by-Rule-662359ad00614b12b4e9b7f436efe395#a39156c43198440aa85527051cb7fb5a) for additional context. 

- Integration test is easiest to do — will just be checking a route for a rule.
- We should also have testing for setTokenThreshold and related routes to ensure the conversion into rules is working properly.
- Token Balance RuleType should also have unit tests, ideally using mock TBC.

**Comment by jnaviask** [comment]
Wont fix -- ruleTypes being deprecated.
