### ISSUE TITLE
Erc20 Merkle Root Contracts

### ISSUE THREAD

**Issue by 0xdantrinh** [hicommonwealth/commonwealth#2629]
Add ERC20 Merkle Root Contracts using the same class hierachy as done for the Non Fungibles

**Comment by CowMuon** [comment]
Daniel met with Timothee yesteday, updates in protocol channel and on [PR #118](https://github.com/hicommonwealth/common-protocol/pull/118)

**Comment by CowMuon** [comment]
Blocked today, Daniel will work with Timothee tomorrow on this.
