### ISSUE TITLE
Fix osmosis proposal loading page performance

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#2635]
## Description
https://www.notion.so/buildcommon/Bug-Tracking-240ba2774ea84347b13a4b0f348a5786?p=a886a72ae9c84bcb90b6afbfa85fc897&pm=s

**Comment by CowMuon** [comment]
blocked: waiting for new chain node (from Osmosis) haven't gotten it yet.

**Comment by jnaviask** [comment]
Fixed by #3151
