### ISSUE TITLE
Confirm everyone is receiving their Github notifications

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2636]
We had an issue or 2 slip through the cracks, so want to insure that everyone is receiving their Github notifications. 

Including but not limited to:
- [ ] When a story is assigned (to you) 
- [ ]  When a story is updated (on story) 
- [ ] When a PR changes status
- [ ]  When a new comment is added to your PR
- [ ] When code changes are requested on your PR (important)

**Comment by jnaviask** [comment]
Bumping this.
