### ISSUE TITLE
WIP: View Template Page + Template Parser

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2659]
## Description

Outline:
- View Template Page
  - gets contract + template from store (app state)
  - parses template into: (write parser method to take in Template, returning JSX components)
    1. form ui
    2. tx into onclickhandler for submit button
        - how to handle $reference from form state?

## View Template Page
- A simple page component that uses to a Parser method to render the Template provided into a form UI

## Parser
- The only valid components we're supporting are: 
  - "text" => h1, h2, h3, see CWText Component
  - "input" = see CWTextInput
  - "divider" => see CWDivider, just a divider
  - "dropdown" => see CWDropdown

- TX is made up of two parts
  - method call
  - args

**Comment by jnaviask** [comment]
If you have confusion about the transaction part, cc @0xdantrinh or myself. We have some existing work in `callContractFunction.ts` which may be able to support the transaction call out of the box.

**Comment by alexyoung23j** [comment]
Done.
