### ISSUE TITLE
Nominating validators design

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#266]
The logic exists in the system for selecting nominators, but we currently do not present it. Previous iterations were not robust solutions either.

A design would be useful here to work from when we decide to re-enable the functionality.

**Comment by nblogist** [comment]
Hey @drewstone!  Can you point out where in the code is this logic present, can you also please point me to Polkadot variant of this so I can understand it better, also is there a mock-up that we can build the design off of?

Thanks!

**Comment by drewstone** [comment]
There are many nominate files in the Polkadot Apps repo: here is one that is relevant: https://github.com/polkadot-js/apps/blob/master/packages/page-staking/src/Actions/partials/Nominate.tsx.

It will take some combing around the `page-staking` to see all the functionality they provide.

For us, we have it implemented in parts here: - - 
- https://github.com/hicommonwealth/commonwealth/blob/9f302b0810167adb597fb87996f6145248a6240a/client/scripts/views/pages/validators/substrate/validator_row.ts#L41
- https://github.com/hicommonwealth/commonwealth/blob/56566598eece1a96bb54cb24d97f32bb4603eeb5/client/scripts/controllers/chain/substrate/account.ts#L415

We'd want a better design that is likely implemented in a separate view. Stay tuned for a Phase 2 spec that clarifies.
