### ISSUE TITLE
Fix redraws in controller layer (with event emitter or refactoring).

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2671]
Most calls to `m.redraw()` can be replaced by `this.redraw()` in the interop ClassComponent. However, some redraws occur outside of components = in the controller layer. These redraws will require a little extra logic to fix.

In the simplest case, the redraw can be moved to the `Promise.then()` method of an async controller function call which previously would redraw at the end. In other words, we fix it by shifting the redraw from the controller to the view.

However, some redraws are more complex, occurring in the middle of larger blocks of code. The `ProfilesController` has a prototype of the solution we can use to resolve it. The logical flow is:
1. The controller initializes and exposes an EventEmitter at creation time.
1. The controller emits an event ("redraw"? doesn't matter exactly what) when the redraw would take place.
1. The view listens on the exposed event emitter and issues a `this.redraw()` (or the React equivalent outside of the interop layer) when it receives the emitted event.

To identify the cases where this conversion may (or may not) be required, search for `redraw` in the `controllers/` folder of the Commonwealth client.

**Comment by CowMuon** [comment]
It's not just notifications controller. It looks like there are still 23 instances of redraw across 11 files just in the controller layer.  Please fix the remaining redraws and resubmit. @0xdantrinh
