### ISSUE TITLE
Reactify Profiles Branch

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2672]
On a separate branch, forked off `react`, merge in the Profiles work and make work in React!

Might not be able to merge (still blocked on Address Refactor, possibly), but will then be ready when pulling the react switch.

**Comment by CowMuon** [comment]
Is there a draft PR for this? @bonnichiwa @zakhap

**Comment by CowMuon** [comment]
@zakhap @bonnichiwa What is the current status here? This PR was to ready for review but it is still just a draft.  What's the status here and what's left? (I bounced it back to in progress.)
