### ISSUE TITLE
Make Chat anew (in React)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2673]
Rather than trying to convert the current Chat Mithril implementation (window and sections) into react, let's just start anew on the front-end. 

The product will be: 
- A simple fire-hose style chat (think IRC)
- No fancy features, no mentions, no replies
- Just a reverse order feed scrolling up, with a simple 1 line editor at the bottom. 

Can use:
- useEffect
- useState

**Comment by CowMuon** [comment]
Closed as dupe.
