### ISSUE TITLE
Replace jQuery with Axios npm library.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2679]
Currently we only use jQuery for making HTTP requests. We can save significant bundle size by using Axios for HTTP requests instead, as jQuery is much larger due to DOM-related functions we do not use.

This should be first done against master, then merged into the react branch, as we will want that functionality both immediately and for the react conversion.

**Comment by masvelio** [comment]
dup https://github.com/hicommonwealth/commonwealth/issues/2939
