### ISSUE TITLE
Create database models for validators

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#268]
A new validator database model will be used to track validator state. We should aim to define what data lives on a validator database model entry and what addresses we are linking.

This model should have a relationship to the Address model, preferably the stash, but can also consider having a many relation to both stash and controller addresses (a validator model can link both or just be a link to one).

Will leave this as discussion too as we may not need this, but can depend on the ChainEvent models to gather historical data about validators. Thought, we should aim to make relevant data easy to grab.

**Comment by drewstone** [comment]
@jnaviask thoughts on this? We could store historical stats under validator models, adding entries in one of our event handler/enrichers when new events come in. Unless you think that indexing through all events is a better solution on-the-fly.

**Comment by jnaviask** [comment]
Yeah I think a special-purpose event handler just for validators, that doesn't necessarily store everything as ChainEvents, might be a good idea. My fear is that there will be a lot of validator events and it would take up a lot of space to store each discrete event, so perhaps better to aggregate-and-update.

**Comment by drewstone** [comment]
Yea I think potentially we should be creating these when we see new validators in events @jnaviask. This way we can start associating any future statistics to validator models instead of addresses or does it matter? Thinking about how to keep all the relations organized.

**Comment by jnaviask** [comment]
So -- to be clear -- the architecture in mind is that we have a `Validator` model, which hasMany `ChainEvents` and also an `Address`, and that we handle validator-related events, emit them as ChainEvents, and make the association, like we do with ChainEntities? Or would we discard the ChainEvents and simply update the Validator model?

**Comment by drewstone** [comment]
The former, I would say we simply associate ChainEvents to a Validator model and associate that model with an Address. One question is whether we associate to the stash or controller addresses or both for redundancy.

Then we can store long-term statistics in this model such as moving averages and APR for nominating against/profits it is getting from validating

**Comment by jnaviask** [comment]
cc @MuonShot for general interest.
