### ISSUE TITLE
New Toast components (use MUI Base Snackbar)

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2706]
Let's also look at react-toastify and react-notifications. 

NB.  Both these libraries provide their own implementation for displaying toasts. However, we can still use MUI Snackbar component if we think the Snackbar component looks better  or is functionally superior. 

So we could implements toasts using either react-toastify or react-notifications, and then display the toasts within MUI Snackbar component; eg. pass the message and type of the toast to the Snackbar component as props, then render the appropriate Snackbar.

Ideally, we can avoid introducing Context into the app just for toasts.

**Comment by alexyoung23j** [comment]
Am I good to try and implement with react-toastify? @MuonShot Seems like there is enough styling options that we shouldn't need MUI
