### ISSUE TITLE
Remove chain-event Substrate code for related deprecated client code

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#2722]
We are in the process of deprecating various substrate functionalities so if they are deprecated on the front-end the equivalent code in chain-events should be removed e.g. bounty/tip proposals/requests.

**Comment by CowMuon** [comment]
We can use filter to ignore certain events we don't want from substrate, should be no code specific to 'those' event types (in type parser- remove switch case for that event to remove, eg. bounties switch (type used to define event)).

**Comment by ianrowan** [comment]
@timolegros Getting the following errors after removing tips(maybe wasn't supposed to remove tip treasury?) 


![Image](https://user-images.githubusercontent.com/36428666/223262835-115ab6f7-df4b-47bb-a5bb-dbf73dcb1ba7.png)

@jnaviask is this functionality we a still using on FE

**Comment by timolegros** [comment]
> @timolegros Getting the following errors after removing tips(maybe wasn't supposed to remove tip treasury?)
> 
> ![Image](https://user-images.githubusercontent.com/36428666/223262835-115ab6f7-df4b-47bb-a5bb-dbf73dcb1ba7.png)
> 
> @jnaviask is this functionality we a still using on FE

To clarify, the list I provided was just meant as an example of what to remove not an actual list of removal. For that we need to look at this PR: https://github.com/hicommonwealth/commonwealth/pull/2657
```
Bounties
Councils
Collectives
Phragmen Candidacies
Identity Judgements
```
So it does look like tips are staying for now but bounties and a few others need to be removed.

Sorry about the confusion, entirely my fault. I should have clarified this much sooner.

**Comment by timolegros** [comment]
We should include removal of all `moloch` code as we don't use moloch anymore.
