### ISSUE TITLE
Fix Order Topics Modal (Drag-n-drop)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2745]
Requires fixing Dragula
or 
Using a new React Drag-n-Drop library and recreating the component.

**Comment by dillchen** [comment]
1. Use react-draggable (v 4.0.3) 
2. We may use => https://github.com/prevwong/craft.js/ (headless drag and drop page builder for our [future work](https://www.notion.so/buildcommon/Page-Specification-Dillon-9d27395fbfa44f5199ea6f7607dc3ab6?pvs=4))
