### ISSUE TITLE
Replace vnode.dom with React refs.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2746]
## Description

Mithril uses `vnode.dom` to access a component's DOM elements. We use `vnode.dom` 9 times in the codebase, currently, and we need to convert all of them as part of our React conversion.

While `vnode.dom` can be abused, in most cases we use `vnode.dom` to either trigger events, or to access the values of form fields. React provides a replacement in the form of `refs`. React provides a `createRef()` function which generates a reference to the DOM elements, that can be used to access the same data as we do with `vnode.dom`. For one example of a converted component, see `code_block.tsx`.

**UPDATE: As of 2/22, only `QuillEditorComponent` needs to have `vnode.dom` replaced. Other cases will be fixed by modal changes or chat deletion.**

**Comment by jnaviask** [comment]
Blocked by #2868

**Comment by jnaviask** [comment]
Last remaining vnode.dom is in `QuillEditorComponent`.

**Comment by CowMuon** [comment]
@rbennettcw for visibility as QuillEditor is the only component that needs to have this replaced.
