### ISSUE TITLE
Fix specific Quill rendering cases

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#2747]
See e.g.: http://localhost:8080/osmosis/discussion/3020-best-practices-for-drafting-proposals

Closed by #2827.

**Comment by CowMuon** [comment]
Haven't debugged yet, do we know where `failed to connect to Web3 provider` is coming from ?

**Comment by zakhap** [comment]
I see. In the comments the list of bullets is not rending the text (but the nested bullets just fine)

**Comment by jnaviask** [comment]
> Haven't debugged yet, do we know where `failed to connect to Web3 provider` is coming from ?

Database migration -- not related to this change.

**Comment by raykyri** [comment]
I think this is a missing `key` issue. The quill renderer creates a lot of arrays without setting keys - making a note to look at that.
