### ISSUE TITLE
Admin unable to change topics of threads

### ISSUE THREAD

**Issue by ryanchristo** [hicommonwealth/commonwealth#2752]
## Description

Attempting to change the topic of a thread produces the following errors in the console and a failed update:

```
Failed to load resource: the server responded with a status of 400 ()
```

```
Uncaught (in promise) Error: Failed to update topic
```

## *Who* is the bug affecting?

community admins

## *What* is affected by this bug?

maintenance, updating discussions

## *When* does this occur?

whenever an admin is attempting to update the topic of a discussion

## *Where* on the platform does it happen?

thread menu options

## *How* do we replicate the issue?

1. log into a community as an admin
2. click on any thread
3. click on the menu option to change topics
4. attempt to change the topic

## Expected behavior (i.e. solution)

topic updates with no error

## Other Comments

- reporting as an admin of https://commonwealth.im/regen
- we migrated to Commonwealth from Discourse, which might be related

**Comment by jnaviask** [comment]
@ryanchristo is this still affecting you?

**Comment by ryanchristo** [comment]
All seems to be working now with the latest updates. Thanks!
