### ISSUE TITLE
Add admin validation on routes

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#2786]
Post, Put, Delete routes on contracts (bet1) should be validated against admin role.

**Comment by jnaviask** [comment]
Why do they need to be admin validated?

**Comment by masvelio** [comment]
@jnaviask this is the product requirement that was passed to me by @alexyoung23j

**Comment by alexyoung23j** [comment]
I was under the impression that only admins should be able to upload contracts and connect them to communities, no?
