### ISSUE TITLE
React Bug Tracking Ticket

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2800]
Leave a comment with bugs you notice, even small ones, like:

- [ ] #2877
- [ ] #2856
- [ ] #2879
- [ ] #2880
- [ ] #2881
- [ ] #2882
- [ ] #2883
- [ ] #2884
- [ ] #2885
- [ ] #2886
- [ ] #2905
- [ ] #2906
- [ ] #2907

To do after profiles work is merged:
- [ ] UserComponent routing (profile links) go to wrong URL: /osmosis/osmosis/discussion/... should be resolved with Bonnie's Profiles work (Next Week)

**Comment by zakhap** [comment]
- [ ] "Add new voting option" on "New Snapshot Form" throws errors in console.

**Comment by zakhap** [comment]
closing this ticket being that the other tickets for all the child todos are in the board
