### ISSUE TITLE
Simple Email Digest Opt-In Work

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2838]
## Description

A simple UI on the Notification Settings Page to set the Users Email Digest Frequency. It should set the frequency of the email digest as just (Never, or Weekly) for the moment. User model attribute: `emailNotificationInterval` enum needs to be updated from (Daily, Never) to (Weekly, Never). Migration needed.

WIP Design:
https://www.figma.com/file/GAITgpjiE4xamopqhnLnQj/Email-Activity-Updates?node-id=99%3A10534&t=6DEfACVTgQ7pGM6g-0

**Comment by CowMuon** [comment]
Per Standup, this should have a PR by EOD 2/23
