### ISSUE TITLE
Instrument all Features

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2851]
We need to instrument *all* features, firstly with an eye on usages stats. 

This is a perennial concern, as we have shipped a lot of features that, absent usage, we would like to completely redo or even kill (and maybe re-implement later.) Obviously, we need this to be informed by usage stats. 

A specific case that has come up is how heavily used markdown is for creating posts. We raised the question in general on a partner call this month, to which we received 2 responses: 
1 power user said "i like writing things in markdown" qualified by saying they know they are in minority of users who like markdown 
1 Ipps said he wouldn't even notice if it was removed. 

We need actual, real data about feature usage.

**Comment by jnaviask** [comment]
Superseded by #3822
