### ISSUE TITLE
Investigate how to build and integrate responsive graphs into the system.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#286]
- Pick a graphing library
- List all graphs that you'll build beforehand
- List all data needed for graphs.

**Comment by nblogist** [comment]
I'd be using Charts JS as the Graphing library

I'd be making following graphs:

1. Stake over time
2. Rewards over time with amounts
3. Slashes over time with amounts
4. Offences over time
5. ImOnline messages over time
6. A histogram of ImOnline messages would also be cool, to understand a node’s uptime (can be paired with a simple 
    percentage Online statistic) 
7. Number of nominators over time

Working on the last part.

**Comment by nblogist** [comment]
Hi, @drewstone, here is the screenshot of the sample graphs created by the charts.js library. 
![graphs](https://user-images.githubusercontent.com/35498810/89857898-bd056680-dbb6-11ea-981b-e03141dd5d57.png)

It's easy to build graphs with this library over mithril. 
Another sample [here](https://adampotocki.github.io/mithril-chartsjs/public/index.html#!/line), checkout a sample implementation [here](https://github.com/adampotocki/mithril-chartsjs)

**Comment by drewstone** [comment]
Looks good!
