### ISSUE TITLE
Created Communities need to be Token Gate-able

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2860]
In order to finish API v2, we need for authorized users to be able to create communities via the API. 
However, such communities need to be rule gated, which in the near term still means token gateable. (Add token gating as first rule to rules engine) 

*However* for MVP, (authorized) users will be able to add a new community via API, and then log in to their new community and add a token gate to the `Join` button. 

Post-MVP we will circle back to enable token gating via the API, however MVP should be shippable in this fashion.

**Comment by dillchen** [comment]
@CowMuon please review the PRD here: just to make sure we're fully on the same page [here](https://www.notion.so/buildcommon/Join-Button-Gated-to-Rule-4a45a169065345728bb2e937a82471d7?pvs=4):

Also note, we have the integration, that once this PRD is `approved` it will auto-generate the issue, I think that as part of the "process review" we should make sure that the PRDs get tagged view a reviewer

**Comment by jnaviask** [comment]
Stale.
