### ISSUE TITLE
Kill Role Assignment 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2861]
IMO we can surgically remove the extant RoleAssignment implementation now, or let it poison the well. This is not a well thought out implementation we should be leaning on, rather the opposite- it's a quasi-janky fix that got thrown in there, and would otherwise be asked to act as a foundation for building on, when it's not load bearing code. 

As Gabe would say, kill with fire, villagers demanding blood pitchforks, etc. (It's actually quite funny when he alludes to pitchforks and angry villagers, because the extant codebase very much follows the "Frankenstein code" anti-pattern.

**Comment by jnaviask** [comment]
Suggested approach: return to the "old" role system, where we have a "role" field on the Address object, containing either the strings "member", "moderator", or "admin". Boolean permissioning gets removed entirely, and any actions based on permissions are made explicit as columns / fields, as they were prior to the migration / changes.

Review the original migrations that introduced the CommunityRole and RoleAssignment tables to see what changes may need to be made.

**Comment by kurtisassad** [comment]
I think this is a good idea. Just a little unsure the original reasoning why we moved off of the old role system for the new one. Is there some functionality that would be dropped by reverting to the old approach?

**Comment by jnaviask** [comment]
> the original reasoning why we moved off of the old role system for the new one. Is there some functionality that would be dropped

Great question. We had some functionality planned, but the implementation we landed on made it extremely difficult to implement, so we never went ahead with it. In other words, there is no functionality we lose, if this ticket is resolved correctly (I believe there is one config param that currently relies on permissions, so we will need to keep an eye out for that, but it's in the original migrations so you should be able to catch it).

What we want is to "reset" back to the simpler state we were in, to clear the way for a better implementation moving forward.
