### ISSUE TITLE
Database migration to upgrade names / icons from OffchainProfiles to new Profiles object.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2863]
Spec TBD

**Comment by zakhap** [comment]
## Description
The Migration here will be LOSSY.

1. For each Address in the DB =>
  a. Check if Profile (by `address.profile_id`) has `profile_name`, `avatar_url`, & `bio`. If NOT,
  b. get Address.OffchainProfile, and for each individually => 
      - if OffchainProfile.data (JSON Parse):
        - Profile.Bio is null + OP.data.bio is not null => set `Profile.Bio = OP.data.bio`
        - Profile.profile_name is NULL + OP.data.name is NOT NULL => set `.profile_name = data.name`
        - Profile.avatar_url is NULL + OP.data.avatar_url is NOT NULL => set `Profile.avatar_url = OP.data.avatar_url`. 

The lossyness in this migration is that the first address we get to that is owned by the user (by index, or in reversed) will be the first and "canonical" naming attempt for each Profile.

**Comment by zakhap** [comment]
Right now we are not considering the unique `username`. just the so-called "display name"

**Comment by jnaviask** [comment]
TODO: investigate scope of lossiness

**Comment by zakhap** [comment]
Knowing at least 2 entries per unique (the criteria for the query) => 2987 rows unaccounted for.

**Comment by jnaviask** [comment]
I note that this migration also doesn't look at Address.name -- and the question there is, where are we rendering Profile.name vs Address.name?

**Comment by zakhap** [comment]
```
	SELECT op.data::jsonb->>'name' as name, a.address, a.user_id, a.name as aname FROM "Addresses" a
		LEFT JOIN "OffchainProfiles" op ON op.address_id = a.id
	WHERE a.address IN (SELECT address FROM "Addresses" GROUP BY address HAVING COUNT(*) > 1)
		AND name NOT IN 
			(SELECT op.data::jsonb->>'name' as name FROM "Addresses" a
			LEFT JOIN "OffchainProfiles" op ON op.address_id = a.id
		WHERE a.address IN (SELECT address FROM "Addresses" GROUP BY address HAVING COUNT(*) > 1) AND op.data IS NOT NULL);
```
is close to being the right query, but seems like impact is smaller than expected?

**Comment by CowMuon** [comment]
How are we updating the 84 users with multiple active profiles? Is that a hard hat operation or just a migration?
