### ISSUE TITLE
Modify User component to support new Profiles work.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2864]
Main agenda: user component should display the Profile name and avatar. Needs #2863 for full effect, but not blocked by it.

To support this, ideally we should spin up a new controller + store for Profiles, where we store the address/name/id/avatar, perhaps expanding `getAddressProfileId` to support these fields. This controller should then back the User component, to avoid re-fetching that data on page navigations.

The store should ideally wrap the HTTP request in a method, so we can easily convert the remaining /account/ links to /profile/ links via controller access, making #2820 considerably easier.

**Comment by CowMuon** [comment]
Should be done today, just need to understand architecture here.

**Comment by CowMuon** [comment]
Seems like point complexity here turned out to be more like a 5 than a 3?
