### ISSUE TITLE
New Profiles work should only allow exactly 1 profile per user.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2865]
- Remove route that allows users to create multiple profiles.
- Remove button to add multiple profiles.
- Change copy on profile-related pages to singular.

**Comment by bonnichiwa** [comment]
Updates:
- Remove `/profile/manage` page and route
- Remove `getNewProfiles` endpoint
- Remove `/profile/new` page and route
- Remove `createProfile` endpoint
- Remove `username` field from `Profile` model
- Remove `/new_profile_redirect`
- Remove any links to `profile/:username` and update to `profile/id/:profileId`
- Make changes to `updateNewProfile` and `getNewProfile` to query by `profileId` only
