### ISSUE TITLE
Topics and Staging Filtering does not refresh when clicking or on refresh

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2870]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/14819225/222473990-c14c1da8-ec07-47e7-b933-ce20c58d1f5d.png">
The URL is changing but the list of threads is not filtered neither by stage nor by topics.

**Comment by jnaviask** [comment]
This is because the route parameters are not being passed as props. Should be a quick fix at the router level.
