### ISSUE TITLE
Linked Snapshot Proposals on Threads don't load on ViewThreads

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2872]
Also an issue on Prod.

**Comment by masvelio** [comment]
@zakhap @CowMuon this is not a case in react (anymore) 


![Image](https://user-images.githubusercontent.com/14819225/223440229-65b72830-6b5f-4cca-95f8-180007b2b0a6.png)

https://commonwealth-react.herokuapp.com/dydx/discussion/7872-drc-remove-stkdydx-from-lp-rewards-formulas

I was not able to check it on prod but on staging it seems to load fine.


![Image](https://user-images.githubusercontent.com/14819225/223440433-72d5c1c6-620b-454f-86b4-f5c5e0e5eb92.png)

https://commonwealth-beta.herokuapp.com/edgeware/discussion/5848-the-cutting-edge-conquest-a-community-campaigns-series-partially-postpaid

Please either close the ticket or move to the `master` board
