### ISSUE TITLE
Aave (dydx) proposal titles/descriptions loading inconsistent (dependent on IPFS fetching)

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2885]
## Description

dydx and other aave-based proposal systems rely on IPFS to load metadata about the proposals. On the React branch, this doesn't always get loaded and rendered properly. For example (some loaded, some aren't):

![2023-03-09-123215_950x922_scrot](https://user-images.githubusercontent.com/1860629/224108815-305ef068-befc-4266-ad70-287547d13c19.png)

## Acceptance Criteria
- Ensure titles/body content on the dydx proposals page all render properly

**Comment by zakhap** [comment]
Is this a force rerender issue or is the fetching in general broken or...?

**Comment by jnaviask** [comment]
Looks like the fetching works but it doesn't always hook to redraw once fetched.

**Comment by jnaviask** [comment]
Resolved problem with redrawing, but still having some issues fetching locally, likely related to endpoint limits. We should at some point add a cache to the IPFS route, but for now, not biggest concern.
