### ISSUE TITLE
White screen on Clicking View profile / edit profile

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#2888]
<img width="271" alt="image" src="https://user-images.githubusercontent.com/14819225/220761215-8cb6e9b6-be8e-4679-9d8c-422a4a3e574c.png">

**Comment by CowMuon** [comment]
Do we need to document in our Github Wiki steps to take to determine if WSOD is ephemeral? Eg. in some cases `yarn run db-all` can fix a WSOD, and we've also seen cases where db-all didn't fix it, but then clearing browser cache did.

**Comment by kurtisassad** [comment]
WSOD only appears on landing page (/ route) due to the db issue. So if you are getting the WSOD on the landing page, you need to yarn db-all. 

But this WSOD is a separate issue from the db problem.
