### ISSUE TITLE
Design UI to show rewards statistics

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#291]

**Comment by nblogist** [comment]
@drewstone It'll be great if you can link a good starting point in the codebase (file name, where to place slashes stats, what to show in rewards stats for a validator),
Thanks!

**Comment by drewstone** [comment]
@nblogist please have a look at:
- https://github.com/polkadot-js/apps/tree/master/packages/page-staking/src
- https://github.com/polkadot-js/api/tree/master/packages/api-derive/src/staking

For information about how we're storing events, you should look into:
- `ChainEvent` model
- https://sequelize.org/master/
