### ISSUE TITLE
Explore Communities should not be alphabetical 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2916]
Explore need to stop returning communities sorting alphabetically, which surfaces a lot of stale communities. Rather, we should sort by activity (score) so that Explore shows the most active communities, not our least active. 

To do this we need a scoring metric to use for ranking, could be cron job to start then refine later. Should have some floor for zero activity communities which probably should not be returned at all.

**Comment by jnaviask** [comment]
Cannot reproduce.
