### ISSUE TITLE
Discussion topics should re-order immediately on order topic modal save (should not require page refresh)

### ISSUE THREAD

**Issue by affordances** [hicommonwealth/commonwealth#2938]

**Comment by masvelio** [comment]
@affordances looks like it works fine. Or are you talking about another case that I am not aware of?

https://user-images.githubusercontent.com/14819225/224707630-209cedd3-d3ce-41f4-aad9-8f84925a820e.mov

**Comment by affordances** [comment]
Confirmed: already fixed.
