### ISSUE TITLE
Remove old (offchain) profiles code on Frontend

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2953]
To remove (TODO: enumerate list of each):

- Profiles related views (modals, pages)
- Profiles controller

**Comment by jnaviask** [comment]
IMO the place to start is the controller logic, and associated views that depend on it. Leave the routes / backend for later. I'll actually make a separate ticket for it.

**Comment by bonnichiwa** [comment]
Documentation of all usages of OffchainProfiles removed from the frontend: https://www.notion.so/hicommonwealth/Removing-Offchain-Profiles-e1cb096da57f4a3dbe4f17c94f027b82?pvs=4#d24744c1521f4a54b8129bd038c83ca0
