### ISSUE TITLE
Remove OffchainProfiles from backend.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2954]
Remove routes that touch OffchainProfile.

Leave database as-is, for now: required by #2863.

**Comment by bonnichiwa** [comment]
Documentation of all usages of OffchainProfiles removed from the backend: https://www.notion.so/hicommonwealth/Removing-Offchain-Profiles-e1cb096da57f4a3dbe4f17c94f027b82?pvs=4#b9d14cf7ee814b8cbb2a5eb1e44acf19
