### ISSUE TITLE
Updates to last_active on Users for analytics purposes

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#2955]
Per comments here: https://www.notion.so/buildcommon/Ops-Internal-KPIs-OKRs-Dashboard-0ae3351071ac4a39b2161718a738e222?pvs=4

**Comment by CowMuon** [comment]
What is this? (Also how it it teed up with out any assignees, labels, etc...?)

**Comment by alexyoung23j** [comment]
Duplicate of #2956 , closing.
