### ISSUE TITLE
Support "Weekly Active Community" in database

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2956]
An "active community" is defined as one where: _a logged in user has viewed and/or interacted with any page in the community_. We need to support querying which communities are active, on a week-by-week level.

Spec TODO

**Comment by alexyoung23j** [comment]
Plan:

- Add two columns: isWeeklyActive (boolean) and lastInteraction (date). 
- Create new middleware function inside databaseValidationService.validateChain that

1. Checks if the request comes from a logged in user.
2. If so, checks the lastInteractionDate. If this more than a week ago, update the lastInteractionDate and set isWeeklyActive to false. If less than a week ago, update lastInteractionDate and set isWeeklyActive to true.

This will create a good approximation of "weekly active" status. To make it fully robust we would need a cron job to check the lastInteractionDate once a week and set isWeeklyActive accordingly.

**Comment by alexyoung23j** [comment]
@CowMuon okay to close?
