### ISSUE TITLE
Bug: After changing topic for thread, the list and thread should be updated automatically

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#2958]
now: After saving new topic, it is saved on the backend properly, but front end does not reflect that.
expected:After changing topic for thread, the list and thread should be updated automatically 

The thread store has to be updated after save and then the view should be rerendered with new state

related to #3066 

https://www.loom.com/share/9d4b0c47320b43e194922df4df2a68e0

**Comment by mhagel** [comment]
Added blocked label because #3066 may resolve this, so that should be done first.

**Comment by affordances** [comment]
If I'm on a thread page and change the topic of that thread and then refresh, I get errors.

![Image](https://user-images.githubusercontent.com/13058678/226000698-ca9e55c0-97df-457d-b057-787215c5c8ce.png)

![Image](https://user-images.githubusercontent.com/13058678/226000712-d1b26971-2b83-45ba-9ba1-ce68f5380d21.png)
