### ISSUE TITLE
Handle issue with irreversible DB migrations

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#2964]
## Description
On the service we use to host our staging environments. We have an issue of db migrations changing the DB in a non-backwards-compatible way. As a result any unrelated commits that are tested on the staging environment will fail due to being out of sync with the db. We need to figure out a way to resolve this. This also has a knock-on effect of reproducibility with our production environment. This is because the state of the database is dependent on which commits and which order they are ran on the environment, not only on the current commit running.
## *When* does this occur?
Example: We have root-id-refactor. It removes the ViewCount table. Master requires ViewCount table in order to make the getGlobalStatistics call. As a result if you test master on staging after root-id-refactor it will fail.

## Other Comments
Possible solution: Reset the db every run. The problem is this could take a lot of time. Also we would need to store the db dump somewhere (like on s3 or something)

**Comment by CowMuon** [comment]
This should be resolved by #2840 @kurtisassad As such, marking as blocked by that issue. 

If you have a better approach in mind, pls note here; should be as straightforward as the command I added as a comment there.
