### ISSUE TITLE
Fix infinite loops in ViewThreadPage

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#2971]
ViewThreadPage has been converted to React FC but unfortunately with very bad practices(1,2,3). Basically there are bunch of 
(1)conditional setStates that are fired 
(2)during the rendering phase
(3) Also there are redraws from event emitter that should be placed in the useEffect instead of render.

All of these above cause infinite rerenders as shown in the video 

https://user-images.githubusercontent.com/14819225/222156863-44e4fff5-2594-4e8c-91dd-0b2a22ac9301.mov

**Comment by zakhap** [comment]
@affordances do you wanna revisit these components? or should @masvelio or someone else take a stab at it?
