### ISSUE TITLE
Upgrade to package manager that supports Plug-n-play

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#2975]
Migrate from yarn 1 to a package that supports plug-n-play:
1. yarn 3
2. PNPM

We should discuss in the comments which option we will go with.

## Description
Here is the RFC to back up my claims: https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-plug-an-play.md

In my view, there are two problems we currently have with using the old yarn.

1. Build time is long: This is due to the way node_modules works, we cannot cache modules that are already loaded because after the lock file changes, the node modules can change significantly, as a result basically a full rebuild is needed after each dependency change. [solution](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-plug-an-play.md#a-install-speed-now-reaches-new-all-time-highs)
2. Bundle size is larger than needs to be: We have many duplicate packages that are not being resolved correctly due to imperfect hoisting. plug-n-play achieves perfect hoisting, as a result it will reduce our bundle size by a bit. [solution](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-plug-an-play.md#d-perfect-hoisting-due-to-the-removal-of-the-filesystem-limitations)

**Comment by CowMuon** [comment]
> as a result it will reduce our bundle size by a bit.

That doesn't seem like a lot? I believe our bundle size is currently 4.11 (or 32,880,000 bits) so a bit would be 0.0000030413625304136253% of that.
