### ISSUE TITLE
Disable Redis - since we removed Chat? 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2980]
Given that we have removed legacy (to build back better) we need to: 
- [x] Determine if Redis plugin for Heroku was/is being used for anything else
        1 pointer or even 0 pointer if Tim has definitive answer.  (Redis DRI) 
        @timolegros Can you please 
- [x] ~~If not, disable Redis plugins in Heroku we are paying for (Don't do this yet, just need the answer here)~~

Verdict: Redis is used for Notifications.

**Comment by timolegros** [comment]
Redis is used by WebSockets (Socket.io) to sync the different socket.io rooms between CW app dynos. It cannot be removed.

**Comment by CowMuon** [comment]
Thanks for the particulars here @timolegros, can you pls make sure this is reflected on the wiki FFR
