### ISSUE TITLE
Database Migration for User Profiles 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2982]
In concert with Unified Profile rollout, we will need to run the database migration.

**Comment by zakhap** [comment]
For each Profile,
1. If just 1 address, copy name and avatar_url to Profile.
2. If multiple addresses and all addresses have the same Name, copy name and avatar_url to Profile
3. If multiple addresses and addresses have different names, 
  a. create a new user + profile for each address, copying the name and avatar_url to the new (siloed) Profile.
