### ISSUE TITLE
Fix large slug size in Heroku

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#2984]
## Description
If the slug is too large, heroku complains about it saying:
> Warning: Your slug size (413 MB) exceeds our soft limit (300 MB) which may affect boot time.

I think the slug is the final output of the build step, this includes our code + node_modules - devDependencies + webpack build. I think to reduce the final size of the slug, we can move the client side code into the devDependencies, because it is already included in the webpack build that we send to the client, and as a result not needed for the server side.

I think this can be further optimized by moving from JIT transpiling (ts-node) to a transpile step before runtime (tsc + node).  This way we could also remove type packages, which will also decrease slug size, and also decrease memory usage of the server.

For some extra slug size reduction, we could also remove the webpack-dev-middleware (its deprecated anyways) in favour of using webpack-dev-server for development, and just normally serving the build file via express.static. This will clean up our code and also slightly decrease the slug size.

**Comment by jnaviask** [comment]
Another potentially useful tool is `heroku local`, which _I believe_ executes the heroku build but locally. Proper usage of the command needs investigation and documentation for the wiki.

**Comment by kurtisassad** [comment]
> Several buildpacks exist such as [this](https://elements.heroku.com/buildpacks/vertragswecker/heroku-buildpack-slug-cleanup) which permit post-build, pre-slug-compilation cleanup, to remove unneeded intermediate build artifacts.

Yes the issue with this is we have the cleanup step to remove devDependencies that is run. So basically we have two avenues here:

1. don't build webpack during build time (see inside uncompressed slug [path-to-slug]/app/commonwealth/build/js), instead build it during deploy time
2. build webpack during build time, but move the front end dependencies to the devDependencies, so that this information is not duplicated (both in node_modules and webpack bundle).

Personally I prefer option 2 because it also is also in line with how people write multi-stage docker files in order to reduce their final docker image size.

**Comment by CowMuon** [comment]
Thanks for adding this Kurtis. What's the acceptance criteria for this story? Asking because it somewhat duplicates [reduce build slug](https://github.com/hicommonwealth/commonwealth/issues/2991) and also because we had specifically said it was not an immediate priority given consideration of impact. 

We absolutely should be revisiting how we are transpiling in CICD, tho again, it's not an _immediately_ pressing concern, however we literally only kicked off the Infrastructure epic this week. 

Finally, the biggest question here is what context you are seeing the soft limit warning, and when did we first start seeing that?

**Comment by kurtisassad** [comment]
For the soft limit warning, my guess is that it had always been there but I had never looked too deep into heroku. It was always a push then walk away type thing. My guess is that it has been there for a while since the slug size is 400mb which exceeds the soft limit of 300mb.

> We absolutely should be revisiting how we are transpiling in CICD 
I am not sure i fully understand. The CICD run is using github actions, and as a result doesn't feed into the heroku build. Are you suggesting it should? I could also  add this to a separate ticket and do some preliminary investigation if we agree we should do this going forward

**Comment by kurtisassad** [comment]
There are two ways to go about this:
1. bundle server with webpack as well. This has the added benefit of tree-shaking and code minification which will further reduce slug size. In this approach we bundle the client + server into the commonwealth/build folder, and then this will be our final slug size. 
Pro: Minimum achievable slug size
Con: Added complexity another webpack step will add.
2. Move client dependencies into devDependencies. These devDependencies will be pruned during the heroku build. The issue with this approach is that we need to manually go over all the dependencies in order to figure out which ones we will need.
Pro: Relatively easy to do
Con: Doesn't scale well (when more developers add dependencies, they will need to be put in the correct dependency/devDependency section.
