### ISSUE TITLE
ChangeTopic modal does not render.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2990]
Followup on #2970 -- make a thread, then hit "Change Topic" in the options dropdown.

**Comment by affordances** [comment]
Will be closed by https://github.com/hicommonwealth/commonwealth/issues/3000.

**Comment by martins87** [comment]
@jnaviask the ChangeTopic modal is rendering and changing/saving topic:

![image](https://user-images.githubusercontent.com/30223098/223517105-0db9833e-5a53-464e-aa29-c7b5a6415c80.png)

On 1) it is the first topic assigned to the thread. On 2) the second topic assigned/changed to the thread.
What is not happening is some user message like "Topic changed"

Thoughs?

**Comment by martins87** [comment]
> 

cc @masvelio

**Comment by martins87** [comment]
> can be closed then

Can anyone close an issue if it's ok to do so?
