### ISSUE TITLE
Remove node_modules to reduce build slug?

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2991]
Heroku build stage output includes the entire node_modules directory, needed for CICD. This is not needed subsequently and only serves to inflate the size of the build slug. After seeing what the savings would be (900M for node_modules, but there is other stuff that can be removed) we can decide to remove that from the build slug, which is currently at 497 MB out of a 500 MB total limit (at which points deployments all fail.) 

_If we decide it's worth it_, (pretty sure it is, we just need to decide together) we should remove node_modules for deployment. It currently weighs about 900MB (not bad for the heaviest object in the universe) but important to note this is highly compressed in the slug, so actual improvement could end up being under 90MB. (TBC,  code files won't compress as efficiently as JSON.) Still that's 20% of our limit, so we'll take it, esp if it is as straightforward as:  

(using heroku/nodejs buildpack)
- `heroku buildpacks:add heroku/nodejs --index 1`
- `echo -e '#!/bin/bash\nrm -rf node_modules' > $CW_HOME/heroku-postbuild`
- (deploy) 

This one change should be enough to get us down the road, and if we hit the limit again before migrating to cloud, we can either revisit how to reengineer our Heroku CICD (only to discard that when we migrate) or just scale production up to a bigger dyno.

**Comment by jnaviask** [comment]
For [background on heroku slugs](https://devcenter.heroku.com/articles/platform-api-deploying-slugs):

> Slugs are gzip compressed tar files containing a runnable Heroku application in the ./app directory.

The takeaway here is that, to inspect the contents of a slug, you can use `heroku run bash` and poke around in the application folder -- that folder, compressed, is the slug.

There are two methods of removing files from a slug:

1. [Slugignore](https://devcenter.heroku.com/articles/slug-compiler) which omits repo files from inclusion. This may cause the build to fail.

2. Several buildpacks exist such as [this](https://elements.heroku.com/buildpacks/vertragswecker/heroku-buildpack-slug-cleanup) which permit post-build, pre-slug-compilation cleanup, to remove unneeded intermediate build artifacts.

In either case, the possible affected areas should be enunerated (e.g. if it's an image, we should know where it loads. if it's a package, we should know where it is imported) and then tested on frack to ensure site functionality remains stable.

Another potentially useful tool is `heroku local`, which _I believe_ executes the heroku build but locally. Proper usage of the command needs investigation and documentation for the wiki.

**Comment by jnaviask** [comment]
Node modules is necessary at runtime, and devDependencies are already pruned in the slug. Wont fix.
