### ISSUE TITLE
Keep statistics on number of available connections in pool

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#2994]
## Description
In our server, the max connections in the connection pool is set to 10. This number should be increased (as well with changing the idle option) depending on the amount of traffic. The only issue is, we currently have no way to see any statistics on how many connections to pgsql are in use at a time.

We should:
1. set this number to an environment variable MAX_POOL_SIZE and POOL_IDLE_DURATION
2. log statistics into datadog regarding the number of idle connections in the pool. This way we can modify these environment variables depending on the availability of the pool.

**Comment by jnaviask** [comment]
Solved by #3343
