### ISSUE TITLE
Thread locking is broken

### ISSUE THREAD

**Issue by affordances** [hicommonwealth/commonwealth#3002]

**Comment by martins87** [comment]
[PR 3053](https://github.com/hicommonwealth/commonwealth/pull/3053)

**Comment by martins87** [comment]
> Has this been CA'd?

What does it mean?

**Comment by jnaviask** [comment]
"Click Around" tested.

**Comment by martins87** [comment]
> "Click Around" tested.

Thanks

**Comment by martins87** [comment]
> Has this been CA'd?

Yes, it was.
