### ISSUE TITLE
Some voting actions have clickable buttons even without permissions

### ISSUE THREAD

**Issue by affordances** [hicommonwealth/commonwealth#3012]
![Image](https://user-images.githubusercontent.com/13058678/222795325-36ca37a3-ed4d-43cb-a05a-84c586aba1c1.png)

![Image](https://user-images.githubusercontent.com/13058678/222795347-de7ee7cc-f247-4bd7-85b3-f782adf75c67.png)

**Comment by mhagel** [comment]
@jnaviask I can disable these buttons based on permission, but what are the specific conditions? Do they differ by community?

- logged in
- has staked token balance?
- anything else?

I see that there are already some checks for proposal state. Just need user conditions.

**Comment by jnaviask** [comment]
Logged in is most important, as that's how we know who to trigger the vote for. The other is the `completed` field on the proposal, but I will need to verify whether these conditions work or not.

There are other baked-in conditions we can use as UI hints, but they're not strictly necessary, and will depend on the governance system (e.g. x/gov vs aave will require different logic for hinting whether the logged in user is able to vote). So, I think the proposed solution here is fine.
