### ISSUE TITLE
Delete thread confirm dialog does not appear

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3013]
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'preventDefault')` when clicking.

**Comment by martins87** [comment]
@jnaviask is this the right confirm dialog to appear?

![thread deletion](https://user-images.githubusercontent.com/30223098/223444779-d0dcd2b0-cfb3-4216-b6d1-28755b368e42.png)

**Comment by martins87** [comment]
[PR 3053](https://github.com/hicommonwealth/commonwealth/pull/3053)

**Comment by masvelio** [comment]
@martins87 for now we have just native `window.confirm` which obviously does not look like this on the screen. We are gonna work on this on post-react stage
