### ISSUE TITLE
Reintroduce landing page token selector bar

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3014]
We removed the landing page search bar to get it rendering. At some point we need to reintroduce it to match the production site.

**Comment by CowMuon** [comment]
@affordances I see you currently have [search bar](https://github.com/hicommonwealth/commonwealth/issues/2989) in progress, this may be a good follow up for that.

**Comment by jnaviask** [comment]
I believe that unfortunately the components have nothing to do with each other.

**Comment by affordances** [comment]
Include it where/how?
