### ISSUE TITLE
Rename heroku boxes from staging/2 to frick/frack.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3026]
Need to make sure we update env var links on microservices (and potentially in code?!) as well as just the names of the boxes on heroku.

**Comment by CowMuon** [comment]
We had wanted to have this in place for Cycle 3 kickoff. Can we have this for EOW? 

I had thought we had Frick repointed, but just went there and wasn't there yet: 

https://commonwealth-frick.herokuapp.com/

**Comment by jnaviask** [comment]
@alexyoung23j do any existing airplane tasks currently in use regularly rely on the commonwealth-staging[2] environments?
