### ISSUE TITLE
Convert Chain Events EVM Event Listeners to polling

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3028]
### Issue
In its current implementation chain events opens up web socket subscriptions for every event it listens for. Websockets can become unstable over time and are not necessary for events that occur at defined intervals(the block time). Chain events should support http providers that poll for new events at a defined pace. This is foundational to consolidating each EVM chain(in the literal sense) into single, efficient listeners in the future

### Approach
New events are always emitted at a given rate, the block time. Chain event's can poll at an interval `b` corresponding to the given chains block time(12 secs for ethereum). This can be accomplished with either an http or wss provider created by the web3.js package. The following process is an example of what this could look like:

1. Define block time on startup
2. Instantiate a simple web3 provider and associated contracts(`myContract`)
3. Build polling logic to call a function designed to check for events ie `myContract.getPastEvents("allEvents", {fromBlock: lastBlock})`
4. Existing event processing binding on event
5. Record last checked block as `lastBlock`

Some important considerations from the above
* Always track last block, as polling can easily fall out of sync with exact block time and miss a block
* Async rpc call and processing of events to allow the polling listener to stay on pace
* Use event filter when possible, rather than excluding events

**Comment by ianrowan** [comment]
@jnaviask @timolegros @MuonShot

**Comment by timolegros** [comment]
Despite `queryFilter` being more efficient for singular event sources, I am going to poll logs using `getLogs` rather than `queryFilter` so that issue #3079 is easier to resolve.

**Comment by ianrowan** [comment]
@timolegros @jnaviask 
At the moment the built-in txs for the testing suite include:

![Image](https://user-images.githubusercontent.com/36428666/224752938-f98aa24b-7a6c-4ad5-80b9-d393e998b98c.png)

In summary, the ERC routes allow for balance queries, transfers, and approval. The ERC transfer route includes a 'fromBank' flag which gives the ability to transfer from the 'Binance Wallet'(ie large supply of almost any token. Likewise the dex route can make a dex swap using up to the 1000 ETH on each available account by default. 

The compound gov routes allow us to create a proposal and push it through stages either manually(casting votes, etc) or automatically(scripting token acquisition and voting) These methods include 'advanceTime + block' logic to allow the timelock to validate txs so in practice 1000s of blocks will be created between proposal stages(heads up for polling logic testing, etc). I'm working on including logic to change the voting delay to something smaller by choice(ie 1 block) for possible use cases.

Wanted to check if there's anything else on these existing routes that would be helpful to include and what additional routes(ie other governance contracts) are worth prioritizing next(or can a compound/governor bravo version to test most cases? mainly thinking testing chain-events logic, not contract specific logic)? 

Additionally, the test chain container includes logic to:
* fork any block or latest(default) with built-in eth mainnet rpc + include custom rpc for any evm
* unlock any wallet(Binance, compound admin by default) 
* set any blocktime(12s default)
* advance timestamps 
* advance blocks

**Comment by CowMuon** [comment]
oops looks like this is missing point estimation

**Comment by jnaviask** [comment]
Related to #3811.

**Comment by timolegros** [comment]
With the merging of #3857 this is now unblocked. The existing work needs to be modified to efficiently use bloom filters as @ianrowan has suggested. It also needs to be modified so the new EVM tests pass. The new React based branch is `tim/ce-polling-2`.
