### ISSUE TITLE
EVM testing infrastructure - test chains, contracts, scripts, etc

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3040]
### Issue

Infrastructure to test web3 based functionality is often built on an 'as needed' basis due to the varying needs of test cases and simulations. This creates issues for cross-functional building and testing. Testing should be as easy as calling `yarn start evm-chain`

Also, testing should be able to work like a typical staging environment(ie a branch or a fork of live data). For a blockchain this means staging data(in databases) should be consistent against a chain. In order to accomplish this a test chain should include the same contracts and functionality as the production version of our app to streamline the dev experience for devs who may not need to worry about contract addresses, simulating transactions, and managing mock addresses. 

### Approach & Ideas

Just like rabbit-MQ, configuring a private blockchain can be complex and inconsistent. In this sense docker is a favorable approach, as it abstracts the setup. To accomplish this the following environment can be created:

* A Docker container running a forked mainnet chain on startup. RPC interface exposed to the localhost
* A companion API with abstracted chain interaction logic running on startup exposed to the localhost
* The chain should
   * Run on a configurable block time by default, with option to automine(for contract testing)
   * Expose funded accounts for testing, and ability to hi-jack any existing account on the fork
   * give the user control of the timestamp
   * Expose logs 
* The API should
   * work as a proxy to create transactions on behalf of the private chain accounts
   * Create defined transactions on existing contracts on demand via a simple request
      * Create a dydx proposal
      * Vote on this proposal 
      * Transfer x token
      * etc
   * Capability to deploy new template contracts
  
### Goals and Developer experience   

With this approach so far the developer experience is as follows
1. Can write tests for interval based listening. Including control over the events that are created(via simple API calls) and listen to real forked contracts(via private chain RPC).
2. Script any available contract interactions without needing to know how to use the web3 lib
     * ie. Could call `api.CreateProposal('dydx');` `api.voteOnProposal('dydx', 1);` with logic to control timing and flow while 
        listening to chain
3. Choose any address and make transactions on real contracts(for app testing)
     * ie. Create a proposal on a real governance contract via bet 1 templates using an address with sufficient gov tokens
4. Write solidity tests that interact with real contracts with rich debugging and error logging 

![Image](https://user-images.githubusercontent.com/36428666/223508137-46660ff9-cba1-4205-be05-d9dcdaa572c8.png)

**Comment by ianrowan** [comment]
It would be great to get input from anyone working with any code that remotely touches web3 to understand more pain points

**Comment by jnaviask** [comment]
One addition here could be to allow the proposal to advance through various stages, so that we can test state and display logic relating to the different possible states of a proposal (e.g. created, voting, completed, failed, etc). Beyond that, this would be a huge boon to our web3 infra and addresses many of the open problems.

**Comment by dillchen** [comment]
One piece of [research / commentary](https://twitter.com/emilianobonassi/status/1629133975091572743?s=12&t=TMOq61wWYC0j0Yt5eRjJ2g) -> a lot of their goals seems similar, I have no idea how robust the infra is but worth taking a look at @ianrowan
