### ISSUE TITLE
Fix Address Login

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3047]
We have discovered a blocker to shipping Unified Profiles, which is that logging in (with address) produces anomalous behavior depending on what route the user is logging in from (basically, is it a community or are they on the home page.) 

We built and tested Unified Profiles to handle all the cases where we need to _display_ a profile to a user (based on their address.) However, this particular edge case for _logging in with_ said address was not caught, and does block shipping Unified Profiles. 

This is not a trivial fix, but we should be able to solve this before our shipping target for unified profiles. 

-- 

Expected behaviour: 
When signing in with an address that is already associated with an account, the user should be logged in as the user associated with that address. 

Actual behaviour: 
When signing in with an address that is already associated with a user/profile, a new profile may be created and associated with the address, IF the person is logging in from either a different community, or logging in from the home page instead of a community (or the opposite, logging in from a community, when you previously created your account from the home page. 

Affected routes:  verifyAddress

Other affected routes: What routes can be logged in on?

**Comment by CowMuon** [comment]
What's still needed to understand exactly what the _expected_ behaviour here is? @zakhap @jnaviask

**Comment by zakhap** [comment]
Expected user behavior: 
1. Thesis: If the user logs in with an address from the homepage (0x123, ethereum), logs out, and then logs in again from within a community with the same address (in dydx, for example):
  - They should be logged into the user+profile that originally logged in. 
2. Antithesis: If the user logs in with an address within a community, logs out, and then logs in again from the homepage:
  - They should be logged into the user+profile they originally logged in with.

Synthesis: If the user is logging in anywhere with an address that is present in the db (in Address.address column), we should log them in to that user. 


Current behavior: 
- If you log in on homepage, log out, and log in again within dydx: you get logged into a new user.
- If you log in via a community, log out, and log in again from homepage: you get logged into a new user.

**Comment by jnaviask** [comment]
Other routes affected besides /verifyAddress:
- finishEmailLogin (deprecated)
- finishOauthLogin (deprecated)
- finishSsoLogin (only for Axie, no work needed)

**Comment by jnaviask** [comment]
@zakhap will this render some users inaccessible? Is that a concern?

**Comment by jnaviask** [comment]
Number of users affected can be derived from:
```
SELECT COUNT(DISTINCT a1.user_id) FROM "Addresses" AS a1 JOIN "Addresses" AS a2 ON a1.address = a2.address AND a1.user_id != a2.user_id;
```

Getting 3851 on my local db.

**Comment by zakhap** [comment]
I see. This is an issue. Hmm. 

I think we should merge them into the same into the same user as it is quite clearly an accidental situation.

**Comment by jnaviask** [comment]
Subsumed by #3056.
