### ISSUE TITLE
Address Fix needed for Unified Profiles 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3056]
Some extant "users" have multiple "accounts" using the same address. (ie they have multiple rows in Users table with the same address.) The migration for this is not only needed for Unified Profiles, it needs to be run _prior_ to Unified Profiles roll out. What are the exact database changes needed? 

Completion tasks: 
- [ ] Complete migration plan/script which includes following items. 
- [ ] Identity which uses are affected (ie how many users have 1 or more addresses in common.)
- [ ] Identify/combine each "user's" profiles into a single Unified Profile.

Questions?
- Do we pull off-chain profile name or address name? 
- Can we assume 1 address (string) has 1 user, or 1 address + 1 community = 1 user?

**Comment by jnaviask** [comment]
Verified we have no Addresses that are duplicated given "address + chain_id", using:

```
SELECT * FROM "Addresses" AS a1 JOIN "Addresses" AS a2 ON a1.address = a2.address AND a1.chain = a2.chain AND a1.id != a2.id;
```

**Comment by jnaviask** [comment]
Re: "Do we pull off-chain profile name or address name?" -- non-question. We only care about names when dealing with merging the new Profiles as part of merging Users. We will take any "set" name (only possible via modal from last week) on merge.

**Comment by CowMuon** [comment]
This is the query I was using to see how many users as affected here: 

```SELECT COUNT(DISTINCT address)
FROM Addresses
WHERE address IN (
  SELECT address
  FROM Addresses
  GROUP BY address
  HAVING COUNT(DISTINCT user_id) > 1
);```
