### ISSUE TITLE
Load thread/comments with a unified route, paginated using a time parameter

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#306]
Replace the current way we are querying for threads/comments/etc with a unified route that fetches everything for a given thread. Paginate the results as well. For each thread in the paginated result, we should fetch its comments, tags, and reactions within that same route.

For proposals, we should aim to handle this the same way. Clients that choose to use the server as the proposal store should also have all this content returned at the same.

- Query the database to get latest X threads by time.
- Order the threads by when they were last updated.
- Aggregating comments for these threads should occur in this same route.
- If we do this, then we will remove the current way we fetch comments. Figure out how to proposals if there are any inconsistencies (i.e. when the client does not fetch proposals from the server).

Spec reference: https://www.notion.so/hicommonwealth/Offchain-data-loading-refactor-refreshAll-refactor-8772eb1f67a44a119178b928b0eae5a5

**Comment by jnaviask** [comment]
Kinda still want this.
