### ISSUE TITLE
Discussions Page is not rerendering when the action on specific thread is taken

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3066]
We need to find a way to refresh the list of threads in DiscussionsPage every time the action on specific thread will be taken.  Eg.
1. Filter list with some topic eg. General
2. Using kebob menu (3 dots) change thread topic to "Other Topic"
3. The thread still is visible, despite the fact that it has changed topic (to verify it, select "Other topic" from the dropdown and you will see that this thread is there, if you come back to General, it won't be visible)

This applies to many other actions like locking thread, changing thread status etc

relates to #2958 

https://user-images.githubusercontent.com/14819225/224046265-070e0513-5c40-4981-b98c-175bba889b37.mov

**Comment by dillchen** [comment]
To refresh the list of threads in `DiscussionsPage` every time an action on a specific thread is taken, you can use the threadUpdated event that is already being listened to in the useEffect hook. You can modify the handleThreadUpdated function to refresh the threads based on the current filters (topic, stage, etc.) when the event is triggered.

Here's an updated version of the `handleThreadUpdated` function that refreshes the threads based on the current filters:

```
const handleThreadUpdated = () => {
  // Refresh the threads here
  const pinnedThreads = app.threads.listingStore.getThreads({
    topicName,
    stageName,
    pinned: true,
  });

  const unpinnedThreads = app.threads.listingStore.getThreads({
    topicName,
    stageName,
    pinned: false,
  });

  setThreads([...pinnedThreads, ...unpinnedThreads]);
};
```


This function is already being used as an event listener for the threadUpdated event in the useEffect hook:

```
// Subscribe to the threadUpdated event
app.threadUpdateEmitter.on('threadUpdated', handleThreadUpdated);

// Cleanup the event listener when the component is unmounted
return () => {
  app.threadUpdateEmitter.off('threadUpdated', handleThreadUpdated);
};

```

With this setup, the list of threads should refresh every time an action is taken on a specific thread, such as changing the topic, locking the thread, or changing the thread status.

**Comment by masvelio** [comment]
waiting for #3034 to be merged

**Comment by martins87** [comment]
> We need to find a way to refresh the list of threads in DiscussionsPage every time the action on specific thread will be taken. Eg.
> 
> 1. Filter list with some topic eg. General
> 2. Using kebob menu (3 dots) change thread topic to "Other Topic"
> 3. The thread still is visible, despite the fact that it has changed topic (to verify it, select "Other topic" from the dropdown and you will see that this thread is there, if you come back to General, it won't be visible)
> 
> This applies to many other actions like locking thread, changing thread status etc
> 
> relates to #2958
> 
>  Screen.Recording.2023-03-09.at.14.52.02.mov

@masvelio I listed these actions to rerender Discussions Page:
- Pin thread
- Lock/Unlock thread
- Change topic
- Update status
- Delete
- Filter Discussions by topic
- Filter Discussions by stage

What do you think? Any more actions to be included?

**Comment by martins87** [comment]
> general concept makes sense as this is what we do in the app currently to force rerender in other component. My main concern here was about the pagination -- I am not sure how exactly `loadNextPage` works as I did not dig into it. When I am on the first page it should not be a problem, but what happens I am on the second or third page? Maybe `loadNextPage` will handle this automatically or maybe we need to modify particular thread and then update the list manually 🤔

This Tuesday I'll be investigating this. Ended up on a concept called windowing*, maybe this can help on the pagination

*
- https://blog.logrocket.com/how-to-virtualize-large-lists-using-react-window/
- https://www.npmjs.com/package/react-window

**Comment by masvelio** [comment]
> > general concept makes sense as this is what we do in the app currently to force rerender in other component. My main concern here was about the pagination -- I am not sure how exactly `loadNextPage` works as I did not dig into it. When I am on the first page it should not be a problem, but what happens I am on the second or third page? Maybe `loadNextPage` will handle this automatically or maybe we need to modify particular thread and then update the list manually 🤔
> 
> This Tuesday I'll be investigating this. Ended up on a concept called windowing*, maybe this can help on the pagination
> 
> * https://blog.logrocket.com/how-to-virtualize-large-lists-using-react-window/
> * https://www.npmjs.com/package/react-window

Don't understand how this would help us? I mean, we already have a library that handles virualization (react-virtuoso) and we have it implemented in exactly this place in `DiscussionsPage`. 
The idea to solve the issue is pretty simple:
1. Perform the action on thread
2. On success emit the event
3. Catch the event in DiscussionsPage
4. Refresh list of threads when event is caught

**Comment by masvelio** [comment]
> > We need to find a way to refresh the list of threads in DiscussionsPage every time the action on specific thread will be taken. Eg.
> > 
> > 1. Filter list with some topic eg. General
> > 2. Using kebob menu (3 dots) change thread topic to "Other Topic"
> > 3. The thread still is visible, despite the fact that it has changed topic (to verify it, select "Other topic" from the dropdown and you will see that this thread is there, if you come back to General, it won't be visible)
> > 
> > This applies to many other actions like locking thread, changing thread status etc
> > relates to #2958
> > Screen.Recording.2023-03-09.at.14.52.02.mov
> 
> @masvelio I listed these actions to rerender Discussions Page:
> 
> * Pin thread
> * Lock/Unlock thread
> * Change topic
> * Update status
> * Delete
> * Filter Discussions by topic
> * Filter Discussions by stage
> 
> What do you think? Any more actions to be included?

Basically all of these from dropdown menu (including those for regular user and admin) + topic/stage 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/14819225/229754689-d93eb039-4c08-46b6-a619-010c4032815f.png">

<img width="181" alt="image" src="https://user-images.githubusercontent.com/14819225/229754824-df5e5947-e0cd-4225-a740-891b0e1c6f6a.png">

**Comment by martins87** [comment]
> 

Ok, thanks
