### ISSUE TITLE
🪣 Cosmos SDK testing infrastructure

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3075]
## Description
To maintain information about Cosmos SDK testing, how it could work with the system being built as part of #3040.

Closed once the following go in:
- [x] https://github.com/hicommonwealth/commonwealth/issues/3440
- [x] https://github.com/hicommonwealth/commonwealth/issues/3441
- [x] https://github.com/hicommonwealth/commonwealth/issues/3563

**Comment by shikhar360** [comment]
Are assignees only allowed to solve the issues or anyone can do that?

**Comment by mhagel** [comment]
Bookmarking for reference: https://github.com/regen-network/regen-ledger/pull/1550

**Comment by mhagel** [comment]
The README here describes regen's sandbox solution.
https://github.com/regen-network/regen-ledger/tree/main/images/regen-sandbox

**Comment by mhagel** [comment]
Also https://github.com/osmosis-labs/osmosis/tree/main/tests/localosmosis
