### ISSUE TITLE
Combine all existing EVM Listeners into a single listener

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3079]
## Description
Combine the different EVM-based listeners like Aave and Compound into a single listener. This is the first step towards ABI-generated chain-events. A follow-up PR will need to introduce ABI parsing to fetch event sources and generalized event processing.

## Acceptance Criteria
- Single EVM-based listener that polls for events with `getLogs` rather than `queryFilter` thus supporting any contract type (Aave, Compound, ERC20, etc).
- Unique processor functions for each contract type.
- Chain-events working for all EVM types.

**Comment by timolegros** [comment]
This is more of a 3 pointer than a 2 pointer. We are still using more instances of Ethers.js contracts than I had anticipated post-polling PR. This means I have to refactor all of the supporting classes (Processor, Subscriber, StorageFetcher, and Filters) in order to merge the Listeners cleanly.

**Comment by timolegros** [comment]
The PR for this is now ready but will remain in draft as we have several outstanding CE PRs and the changes in this PR will need to be re-tested and possibly slightly altered (to resolve conflicts) once the other PRs (#4025 and #3991) are merged.

**Comment by CowMuon** [comment]
Aadding @mhagel as watcher (possible pair)

**Comment by timolegros** [comment]
Now that Substrate removal is in can move forward here. All that remains is to (potentially) clean up some types.

**Comment by timolegros** [comment]
Sad to backlog this after so much work but not worth reviewing/merging until we decide whether CE stays or goes especially since it is merely a code design improvement and not a performance improvement (not critical for Paris). I have tons of other notifications-related issues I can be working on. See #4373.

**Comment by timolegros** [comment]
Unfortunately, after all the work that was put into this issue, we have come to the conclusion that we will be moving forward with the removal of chain-events. This issue is no longer necessary.
