### ISSUE TITLE
Remove reactions and comments controller and re-integrate into ThreadsController/ProposalController

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#308]
Currently we have separate controllers for many portions of the code that are dependent on one another. Namely, comments and reactions exist within threads and we should directly treat them as such. 

The task is then to:
- Integrate comment and reactions controller functionality into the ThreadsController and thread routes, similarly with Proposals.
- Using the aggregate route from https://github.com/hicommonwealth/commonwealth/issues/306, we should be able to use the ThreadController to replace all calls within the comments and reactions controllers.
- Update links to these controllers in any views.

**Comment by drewstone** [comment]
This will work for proposals when the client uses the server as the proposal store, correct? @jnaviask

**Comment by jnaviask** [comment]
yeah it should be fine, it'll just send up a proposal-based ID rather than an OffchainThread one, I think

**Comment by jnaviask** [comment]
Still worth considering.
