### ISSUE TITLE
Post-deploy UP issues (Unified Profiiles) 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3081]
- [x] WSOD in private tabs - This was fixed by full purge of CloudFlare caches. 
- [x] User can add same address to profile multiple times - This is expected behavior, in advance of address deduplication fix.
- [x] User creating new account doesn't have profile - This is because there is no other profile to merge, and the error is not handled gracefully.  #3215 
- [ ] Can't update avatar in Dark Mode - User can't re-select a new avatar from edit profile page, but only in dark mode. #3212 (but likely won't fix as this is already working on React -not Master- branch.)
- [x] Some profiles don't display - Happening bc we shipped this in advance of root id fix (root_id needs to be for discussions only.)
- [x] [Dillon's profile](https://commonwealth.im/profile/id/17811) doesn't display - Unknown issue (and also [profile id # 16292](https://commonwealth.im/profile/id/16292)) -> also other Edgeware posts
- [x] One edge case we did not include is for a user who has comments on a since deleted community. In this case, data fetching will silently fail, resulting in a wsod. This has been addressed in a fix, so that such profiles now render (missing rows are simply no rendered.) We can consider this fixed, tho we will want to revisit.

**Comment by jnaviask** [comment]
How exactly does root_id get involved here?

**Comment by jnaviask** [comment]
@CowMuon OK to close this?

**Comment by jnaviask** [comment]
Completed. Will open new ticket for avatar issues if surfaced again, but potentially fixed by #3213.
