### ISSUE TITLE
The path to self-serve EVM based chain-events

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3084]
While working through chain-events polling a rough plan of how we can get to self-serve ABI based chain-events came to mind.

**PR 1:** polling CE -> I am refactoring subscribers in such a way that the method of parsing logs/events is the same for all existing EVM based listeners (Aave, Compound, etc) - Issue #3028

**PR 2:** combine the EVM listeners into a single listener (now possible since the subscriber is virtually the same and is contract agnostic) - Issue #3079

**PR 3:** switch `chain` in `Events` table to an `origin` like the old spec (origin being a combination of the contract address and some chainNode value like chain-name) -> this is part of the chain to community semantics refactor for CE. Requires client-side changes since `event.chain` will become `event.origin` so links to specific communities will need to be done via `Contracts` table.

**PR 4:** Transfer existing ABI's (Aave, Compound, etc) to the database (`ContractAbis` table) and initialize ethers contracts + subscribers using the abis from the database rather than local

**PR 5:** Generalize event processing away from specific networks like Aave, Compound, etc -> basically generalize the type parsing + enrichment of events

And that's it then CE supports custom ABI event's and all that's missing is client-side support to upload ABI's + enable `has_chain_event_listener`

**Comment by dillchen** [comment]
As a piece of research, worth reading [this thread](https://twitter.com/worm_emoji/status/1625204695525625856?s=12&t=cO7myhhRAf-vJbjAJV_pjw)

**Comment by timolegros** [comment]
PR 2 is almost complete #4290, PR 3 #3972  will be merged after EthCC, and PR 4 will be a very small PR once the other 2 are in. These 3 PRs will drastically reduce the size of CE by unifying and generalizing all EVM-related code. Once this generalized roadmap is complete CE will be in a place where the vast majority of future changes are performance improvements (something which we have not had the luxury to focus on much thus far).

**Comment by timolegros** [comment]
Chain-events will be deprecated per #4696.
