### ISSUE TITLE
Migration from staging/staging2 to Frick/Frack

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#3092]
## Description
As we have decided to move on with changing the name of our staging environments. We need to be extremely careful with it. The reason is, these changes will not be tracked by version control, and therefore not tracked or easily reversible. As a solution to these two problems we should perform two steps:

1. At the start, prior to the migration, everyone writes down where commonwealth-staging/staging2 are being referenced from.
2. When we go ahead with the migration, everything we touch that is external to the codebase should be written on this ticket. (for example changing some environment variable on heroku)

**Comment by CowMuon** [comment]
@jnaviask @kurtisassad Is this going to happen before the end of the quarter on Friday? We really want to be starting Q2 right (not to mention after root_id, the need for a REAL staging server has never been more apparent.)
