### ISSUE TITLE
[Dashboard] Chain events in Dashboard are not loaded in local environment

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3113]
Locally `/dashboard/chain-events` does not load events even though when `process.env.ENTITIES_URL` is set. Function `getBaseUrl` should be adjusted to be able to fetch chain events from remote server instead of from localhost:8081

![Image](https://user-images.githubusercontent.com/14819225/225039661-e55aef23-2ae9-4f82-be58-79e5ddaab980.png)

**Comment by masvelio** [comment]
Hey @timolegros would you be able to put your thoughts on this? Rather low priority for now but if this would be quick, maybe you would be able to take a look? If not, just your thoughts would be helpful

**Comment by jnaviask** [comment]
Just pushed commit acfa1afefea678b725a2e41e1eda9d57968bb615 to react branch which should fix this issue, cherry-picking https://github.com/hicommonwealth/commonwealth/pull/2765.
