### ISSUE TITLE
[Dashboard] Clicking on Community name takes user to [Object object]

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3116]
In dashboard/chain-events Clicking on Community name takes user to [Object object]. Not sure what is expected behaviour, please confirm.

https://user-images.githubusercontent.com/14819225/225042463-cfd01a36-f410-481b-ba18-badc4d52be74.mov

**Comment by mhagel** [comment]
I confirmed this also happens in Prod. What is the expected behavior here @jnaviask ? Link to the community's main page?
