### ISSUE TITLE
SDK wrapper for Chain testing tool

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3121]
It might be worth adding a lightweight API wrapper for the chain testing tool to make working with types defined within the API event easier. 

In this case we could import the sdk and build requests with the defined types for each `req.body` and call each as a function.

**Comment by CowMuon** [comment]
What was the point value on this one?

**Comment by ianrowan** [comment]
@CowMuon This took about a day end to end so 4 points?(not sure the scale we use yet)
