### ISSUE TITLE
Fix community subscription on-off button

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3125]
Subscriptions (Notifications On/Off) button on sidebar does not change state.

![Image](https://user-images.githubusercontent.com/1860629/225127942-e27d1bc5-3f84-417d-9b79-57428170bd14.png)

**Comment by martins87** [comment]
@jnaviask What is the expected behaviour? Besides change on button UI, should all the bell icons change?
For example, Subscriptions are ON. If button is clicked, should all community notifications change to "Unsubscribed" ?

![image](https://user-images.githubusercontent.com/30223098/225153403-cafaf309-b49c-407f-9afc-5716197d85ec.png)

**Comment by zakhap** [comment]
This is a case of confused UX, to be worked on ultimately with Design. 

Behavior is as expected.
Notifications Off in the lower left is about "New Threads" in the communities
Notification Bells on threads is about new comments on the thread (individually).

**Comment by zakhap** [comment]
For clarity, each button is independent. No one button should effect the state of another.

**Comment by martins87** [comment]
To be honest I find this button confusing. Like you see a "Notifications on" and think "Are the notifications on or if I click it I will turn them on?"

What do you guys think of changing the label to "Turn notifications on/off"? This way this problem is gone.

**Comment by zakhap** [comment]
How does the button look with all of that added text?

**Comment by martins87** [comment]
> For clarity, each button is independent. No one button should effect the state of another.

Ok, thanks!

**Comment by martins87** [comment]
> How does the button look with all of that added text?

![image](https://user-images.githubusercontent.com/30223098/225317615-72b2b813-c837-444f-9855-8c68e3069a50.png)

**Comment by martins87** [comment]
> How does the button look with all of that added text?

![image](https://user-images.githubusercontent.com/30223098/225318028-bfba813f-5197-4fff-a2d9-a7db660ef6dc.png)

![image](https://user-images.githubusercontent.com/30223098/225318209-c894952a-8d12-49c2-a623-e082116e221f.png)
