### ISSUE TITLE
Bug: Edit topic modal does not render correctly

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#3127]
NOTE: this occurs on the `ryan.global-quill-wrapper` branch, associate with #2934 – Must merge that before can repro this.

When the edit topic modal shows, it renders incorrectly. Ensure that it renders properly and that clicks inside the modal are handled properly.

![Image](https://user-images.githubusercontent.com/126922418/225132577-e9c517c6-504f-4efc-be6e-cf1fe32bde9a.png)

**Comment by dillchen** [comment]
Similar(?) behavior on branch / PR -> https://github.com/hicommonwealth/commonwealth/pull/3061



![Image](https://user-images.githubusercontent.com/5334557/225195009-5a0e63dc-91ab-4f6b-9055-6b481e2e5139.png)

**Comment by rbennettcw** [comment]
This appears to be a duplicate of #3103

**Comment by masvelio** [comment]
this should be gone after merging https://github.com/hicommonwealth/commonwealth/pull/3118

**Comment by jnaviask** [comment]
Both of the above are merged -- still a bit buggy. Maybe an incorrect merge?

**Comment by rbennettcw** [comment]
@jnaviask I'll push a PR shortly that triggers a refresh when a new topic is added. Already seems to work fine for editing a topic– in my testing.

Are there any other issues you see related to topics?

**Comment by rbennettcw** [comment]
Here's the PR: https://github.com/hicommonwealth/commonwealth/pull/3143

**Comment by jnaviask** [comment]
Amazing work!
