### ISSUE TITLE
[Notifications] Discrepancies in navigation to notifications page

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3135]
1. When I am not in the scope of any community (eg in dashboard), when I click bell icon => see all,  I am redirected to `edgeware/notifications`
2. When I am in the scope of community (eg dydx), when I click bell icon => see all,  I am redirected to `dydx/notifications`

What is desired behaviour for those two ☝ ?

3. Is there a difference for the user to see `/notifications` and `/:scope/notifications` ? 

https://user-images.githubusercontent.com/14819225/225301718-85788256-aa86-4dd1-8c02-e6efcb07dde7.mov

**Comment by masvelio** [comment]
@jnaviask @zakhap Can you clarify please

**Comment by jnaviask** [comment]
Confirmed on commonwealth-react that this is no longer an issue, does what Dillon suggests.
