### ISSUE TITLE
[Notifications] Mark as read does not work in notifications

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3136]
1. New notifications should have some background style that distinct from other notifications
2. Clicking `mark as read` a single notification does not work "real time" 
3. Clicking `mark all read` button does not work "real time" 

It should be fixed both in notification popover and notifications page

More info: to have notifications available on localhost, create two accounts and have interactions between them (eg creating the post and liking it) 

![Image](https://user-images.githubusercontent.com/14819225/225305863-d9a91ef0-02ea-4762-89f3-4cc9cb3cc166.png)

![Image](https://user-images.githubusercontent.com/14819225/225306304-bfeb1a5c-ca21-4342-94bb-edc082c1789c.png)

**Comment by martins87** [comment]
> 1. New notifications should have some background style that distinct from other notifications

@masvelio what makes a notification "new"?

**Comment by CowMuon** [comment]
@zakhap You wanna catch this one ^^^ kudasai.

**Comment by zakhap** [comment]
The notification is the sum of two models: 
- Notification (activity data, the notification itself)
- notifications_read model (has property "is_read" that designates "new" => "new" means `is_read === false`.

In the front-end, we only have the one `Notification.ts` model that has the "isRead" property. If "IsRead" is false, then it has not been read (thusly, is new)
