### ISSUE TITLE
Update app.login state with clearer separation between dynamic/static state.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#314]
This task includes:
- Move app.vm.activeAccount onto app.login, so we can get rid of app.vm
- Demarcate dynamic and static properties 
- Split app.login into things that change when you change community, and things that don't
    - **What do we call the renamed groups?**
- Change arrays on app.login to controllers
    - **What guarantees should the controllers provide?**
- Consolidate helpers and one-off checks into controllers. For example, we reimplement a bunch of checks for roles (`isMember`, `isAdmin`) in different places

**Comment by drewstone** [comment]
Do we want to have controllers for each part that deals with dynamic state and leave static properties as top level items?

**Comment by drewstone** [comment]
@zakhap want to take a first stab a what the new state object could look like? I can then provide feedback, there are comments above that should be helpful if you have ideas.

**Comment by zakhap** [comment]
@drewstone yeah! I can take a look at this tomorrow and check out the work you've done. Let me know if there's anything in particular I should look at first!
