### ISSUE TITLE
Bug: User profiles not accessible on custom domain

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3140]
## Description
No user profiles can be viewed or edited in any custom domain forums. e.g. click into a profile from https://forums.dydx.community/overview

Looks like the error is in reading the `name` property from `_refreshProfiles` in `controllers/server/newProfiles.ts`, where some MinimumProfiles do not have names.

Ticket: https://www.notion.so/buildcommon/User-profiles-not-accessible-in-custom-domain-forums-2319c8edab7e43bb8dde559b52eecd58

## Acceptance Criteria
- Profiles must display on custom domains.

**Comment by zakhap** [comment]
Problem: Accessing any user profile on any custom domain is not currently possible. Going to /profile/id/:id does not work. 

> Looks like the error is in reading the name property from _refreshProfiles in controllers/server/newProfiles.ts, where some MinimumProfiles do not have names.

Unsure what this has to do with it exactly? 

Upon first glance, it just seems like we don't have the route `/profile/id/:id` in our customdomain routes in the router. 🤷
