### ISSUE TITLE
Managing Staging Environment Access

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3147]
# The Problem
We currently see messages every day in the #cmn-devops slack channel asking whether or not a certain development environment is free (frick/frack). This is inefficient as it requires the person who needs a resource to wait until they get a response from another dev.

# The Solution
Rather than having to ask whether a resource is free, we can use something like https://github.com/connorads/lockbot. This is basically just a slcak bot that allows us to create mutex locks on resources. For example, if I need to test something on frick I simply need to check whether the resource is available or locked. If it is available I lock the resource (frick or frack) thus signalling to all others that the resource is in use. Once I am done, I unlock the resource thus making it available to other developers once again. The linked bot also allows for forced unlocks in the event that someone forgets to unlock a resource before leaving for an extended period of time.

Note that the lock is not related to Heroku at all i.e. locking a resource doesn't literally prevent someone from using the resource.

# Possible Issues
One possible issue is that developers will forget to unlock resources. If this is the case very often then this tool will not improve anything since developers will still need to ask if a lock is still valid/in effect. This can be avoided if every developer uses the locks appropriately.

**Comment by CowMuon** [comment]
Is it just going to be the case that developers will forget to unlock the resource until the next developer comes along and asks to use it?

**Comment by timolegros** [comment]
> Is it just going to be the case that developers will forget to unlock the resource until the next developer comes along and asks to use it?

This is a possibility that I highlight in `Possible Issues` but even if just 50% of developers use it properly that's a 50% reduction in the number of times a developer needs to wait before using a resource. In other words, this cannot make the process worse it can only improve the process.

**Comment by timolegros** [comment]
@jnaviask @CowMuon Can we get an update on this?

**Comment by timolegros** [comment]
The interim solution has been to use the channel topic in the Slack `eng-infra` channel.
