### ISSUE TITLE
EVM Testing Tool Additions

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3148]
As we test the EVM testing tool we can use this issue as a place to note 

* Modifications 
* Bugs
* Ideas
* Requests for additional web3 automations

**Comment by ianrowan** [comment]
Per conversation w/ @timolegros the initial implementation of the chain testing SDK had CORs related issues when used is some areas of the app. Fix to be included(adding all CORs perms to express) in #3232

**Comment by timolegros** [comment]
EVM testing has been working great for a few months now so I think it is safe to close this issue. If any problems arise in the future we should create new tickets.
