### ISSUE TITLE
Introduce cache to cosmosProxy

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3151]
## Description
Our Cosmos loading is very slow, particularly on Osmosis. This is becoming a severe usability problem.

One possible solution, which should be straightforward to build, is to introduce a cache to the CosmosProxy utility on the server. Currently it is a "dumb proxy" that simply forwards requests. It receives many repeat requests whose repsonses do not change, and the chain endpoints behind the proxy are not suitable for high volume requests. We should cache these for a performance win (and potentially make the proxy more robust with timeout/retry).

All cosmos queries we make via the proxy are in `client/scripts/controllers/chain/cosmos`. the only one we want to AVOID caching is gov.proposals() and only when a proposal is in PROPOSAL_STATUS_DEPOSIT_PERIOD or PROPOSAL_STATUS_VOTING_PERIOD. Otherwise, we can assume the content is historical and not subject to change.

The difficult problem is, as always, cache invalidation, especially when a proposal moves between periods. We could use a fairly quick TTL on a time-based strategy for all contents to start with, but we will need to think more deeply about how to trigger invalidations. However, we shouldn't think too hard, as we eventually will want to move to a data-driven, indexed approach for many items rather than relying on the proxy.

## Acceptance Criteria
- The cosmosProxy should cache cosmos chain requests, which should reduce errors and loading time in Cosmos communities.

**Comment by NakulManchanda** [comment]
this is the best and most safest caching opportunity we have where we don't have to worry about TTL too
block chain like cosmos has paging endpoints to get proposals etc

we can cache - where current page != lastPage
that is definitely immutable and won’t change





[2:06](https://commonxyz.slack.com/archives/D04S75E1CET/p1682446002286609)
we re thing to cache that too:
where current page != lastPage
[2:07](https://commonxyz.slack.com/archives/D04S75E1CET/p1682446021064149)
that is definitely immutable and won’t change

**Comment by mhagel** [comment]
Notes:

v1beta1:
`{"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0802","prove":false}` = voting period
`{"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0801","prove":false}` = deposit period

`{"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0803","prove":false}` = passed (main?)
`{"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0803220a0a080000000000000087","prove":false}` = passed
`"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0803220a0a080000000000000100","prove":false}` = passed
`{"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0803220a0a080000000000000189","prove":false}` = passed
`{"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0805","prove":false}` = failed. (TODO: "failed" UI tag)
`{"path":"/cosmos.gov.v1beta1.Query/Proposals","data":"0804","prove":false}` = rejected

**Comment by mhagel** [comment]
`{"path":"/cosmos.gov.v1beta1.Query/Votes","data":"089d02","prove":false}`
`{"path":"/cosmos.gov.v1beta1.Query/Votes","data":"08ed03","prove":false}` don't cache?
`{"path":"/cosmos.gov.v1beta1.Query/TallyResult","data":"08ed03","prove":false}` don't cache?

`{"path":"/cosmos.gov.v1beta1.Query/Params","data":"0a076465706f736974","prove":false}` = deposit params => prob cache
`{"path":"/cosmos.gov.v1beta1.Query/Params","data":"0a0874616c6c79696e67","prove":false}` = tally params => prob cache
`{"path":"/cosmos.gov.v1beta1.Query/Params","data":"0a06766f74696e67","prove":false}` = voting params => prob cache

**Comment by jnaviask** [comment]
We can cache TallyResult because it is only written once the vote completes and therefore will not change. Votes we should not cache, or if we do, it should be on a very short TTL that's invalidated if the user votes.
