### ISSUE TITLE
Profile Bug: On Proposal Pages, User component fails to find profile, never refreshes from Loading state.

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3157]
## Description

The problem is that no profiles are returned for these addresses as they are not registered users on commonwealth. We should present the vote's author address and _not link_ to an empty profile (should not be clickable). 

Zak believes the bulk of the work is in the User.tsx Component.

see: https://commonwealth.im/dydx/proposal/11-reduce-trading-rewards-by-45

![Screenshot from 2023-03-16 13-00-14](https://user-images.githubusercontent.com/16248081/225727291-5b5a390e-a58b-4f0d-9d05-5fc9de2ab65c.png)

## Acceptance Criteria
- For UserComponents that do not have receive a Profile, we should just display the address string and do not link to an empty/undefined profile from there.

**Comment by jnaviask** [comment]
Also an issue on snapshot proposals.
