### ISSUE TITLE
Load Testing: Simulation for high load on QA environment

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3161]
## Description
We have had deployments fail due to the application being in a high-load state, which was not reproduced in our testing or QA environments. We need some way to reproduce high load so we can verify that changes will succeed in a production context.

## Acceptance Criteria
- A script or testing plan which allows for simulation of high application load.

**Comment by timolegros** [comment]
https://www.artillery.io/blog/open-source-distributed-load-testing-with-lambda interesting tool for simulating API load (which translates to database load).

**Comment by NakulManchanda** [comment]
Three options for Load Testing:
- apache-bench - small scripting tool available on Macs command line by default
- JMeter - very popular java based tooling
- Locust - will have dashboard to visualize results etc

**Comment by NakulManchanda** [comment]
Tickets has few parts:
- setup load testing tool/library - send high request concurrently, visualization dashboard
- identify endpoints which returns lot of data - eg. Thread with most comments etc
- setup github CI automation for load testing - may be as job on schedule or on-demand job
- establish baseline - store old results/reports or retrieve from github CI if it stores them, or push them to S3
- run with each release & new version
- add new endpoints as and when needed

**Comment by NakulManchanda** [comment]
There is another aspect we can try load test:
- Creating large proposals, using heavy images etc
- https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/6423

![image](https://github.com/hicommonwealth/commonwealth/assets/4791635/feef7fec-3684-46a9-8ca5-79781c6a60b0)

**Comment by NakulManchanda** [comment]
High Load URLs
**Proposal pulls tons of addresses**
https://commonwealth-staging.herokuapp.com/aave/proposal/onchainproposal/235

**Proposal with over 1.5K comments**
https://commonwealth.im/stargatetoken/discussion/4353-proposal-guidelines

**Comment by timolegros** [comment]
Superseded broadly by https://github.com/hicommonwealth/commonwealth/issues/8013 and more specifically by https://github.com/hicommonwealth/commonwealth/issues/8011.

**Comment by timolegros** [comment]
Superseded broadly by https://github.com/hicommonwealth/commonwealth/issues/8013 and more specifically by https://github.com/hicommonwealth/commonwealth/issues/8011.
