### ISSUE TITLE
Using ViewControllers

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#317]
The intention of using view controllers would be to purify views, pull all state based calls into a single ViewController, inject all state-updating calls into views as component attributes.

This would benefit the following:
- readability of codebase
- identifying bugs (they'd likely occur in view controllers rather. than in views)
- fixing bugs (since theres less view code to read through we can more effectively catch them)

**Comment by jnaviask** [comment]
How close is this to hooks?

**Comment by jnaviask** [comment]
Stale post-react.
