### ISSUE TITLE
Updating mentions logic with rules or ways of improving user experience

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#318]
Currently, searching through mentions could be smarter. I want to start a discussion around it since we gave the ability for users to make infinitely many accounts.
![image](https://user-images.githubusercontent.com/13153687/83693645-b7d2dc80-a5b3-11ea-91fa-d405d8e32543.png)

For example, we could add certain rules over mention strategies. When I search for dillchen, if a dillchen account is present in the thread to restrict to that one. Curious to hear other rules people can think of to make this experience nicer.

**Comment by drewstone** [comment]
For more context, the 3rd dillchen is the one in that list that seemed relevant given the thread I was in. And at first I clicked the first one. So it's a bit annoying since we may have people mentioning each other's alt accounts when they intended the opposite.

**Comment by gdjohnson** [comment]
Hmmm, yeah. So the priority goes: 
1) In-thread [What're your thoughts on storing a list of "active addresses" on a thread? Could be a many-to-many assoc or an array.]
2) In-community
3) Side-wide

One question would be, will users know that this priority list exists? Will they be able to infer that the first listed address is the one they want to click, or will they still be confused by the big list? It seems like a hard balance to strike, in terms of both showing users the full list of mentionable addresses, and also ensuring that they're choosing the most relevant or most desired one. Perhaps a lil, 10pt grey copy that says 'In thread' or 'Community member' etc? OTOH, we're already crowded with pictures, names, and address previews... tho the 'In thread' copy could be hover-activated.
