### ISSUE TITLE
Connect New Account to previously created account 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3214]
## Priority
Not sure this is a priority. Will check with Zak. Ofc we need this to work, we just have a LOT right now that's higher Pri. 

## Behaviour
After creating an account, log out, and then log back in with another account and try to connect to previously created account, Marcin seemed to be having an issue with doing so, but Bonnie was able to successfully connect. See recording here: https://github.com/hicommonwealth/commonwealth/pull/3150#issuecomment-1474001235

## Expected Behaviour
New account is successfully connected to previous account. 

## Questions
- [ ] Why was Bonnie able to get this to work but not Marcin?

## Acceptance Criteria
(See Expected Behaviour)

**Comment by jnaviask** [comment]
I was having trouble getting this to work reliably on production as well.

**Comment by NakulManchanda** [comment]
didn’t quite understand the linking issue yet
- but if `react branch` fixed it then lets wait for that to deploy to `master`
- in addition, may be we can introduce extra middleware/or using the same middleware
   - to check if all info in **parsed session object is matching expected schema** if we are already doing this then good
   
 i believe i have noticed this on localhost as well as on prod app - but not sure yet!
