### ISSUE TITLE
Create New Account 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3215]
## Description
Is create new account working on master? (in production.) How many new accounts have been created so far this week? Last week? 

## Problem
In testing Unified Profiles, it seems there is a problem merging new profiles, because they don't have an old one. Can we assume this problem goes away when the grace period expires? 

## Acceptance Criteria
- Create account shown to be working.

**Comment by jnaviask** [comment]
Seems ok to me?
```
> SELECT COUNT(*) FROM "Users" WHERE created_at > CURRENT_DATE - 7;
 count 
-------
  2141
(1 row)
```
