### ISSUE TITLE
Thread Page crash when body has inputs

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3218]
**not working example in react:** 
https://commonwealth-react.herokuapp.com/dydx/discussion/3150-drc-liquidity-staking-pool-borrowing-requirementsframework

**the same thread working on stage:**
https://commonwealth-beta.herokuapp.com/dydx/discussion/3150-drc-liquidity-staking-pool-borrowing-requirementsframework

![Image](https://user-images.githubusercontent.com/14819225/226938571-2304424b-4d9d-4779-bb63-373a47515c88.png)

Please check other components if they render properly. It can be fixed in this ticket or new tickets might be created

**Comment by CowMuon** [comment]
`Failed to execute 'createElement' on 'Document': The tag name provided ('input[type='checkbox'][disabled]') is not a valid name`

**Comment by rbennettcw** [comment]
PR: #3278
