### ISSUE TITLE
Cross-community links on profile don't work on custom domains

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3219]
## Description
Go to a profile on a custom domain and click a link into another community. It should redirect you to commonwealth.im on the other community, but currently it redirects you to the discussions page on the custom domain community (error).

## Acceptance Criteria
- Profiles links must resolve properly.

**Comment by CowMuon** [comment]
Adding Marcin as assignee. Kurtis has #3300 as immediate priority; will the 2 of you please sync up on both these tickets at the top of the day, and we will expect both to land on 4/5, unless there's a change in estimation.
