### ISSUE TITLE
TOS Modal does not permit login on joining

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3221]
## Description

May only appear when already logged in on another chain base (e.g. on osmosis or juno) and then navigating to dydx.

https://www.loom.com/share/67c6818655a34692b6079fd8939312db

## Acceptance Criteria

Should allow user to join once the modal is clicked through.

**Comment by CowMuon** [comment]
Was unable to reproduce (successfully joined community) and not seeing this as top priority. Imma close and just re-open if it's really a problem.
