### ISSUE TITLE
Add AAVE and ERC721 endpoints to EVM testing env

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3232]
This issue covers the addition of API endpoints for AAVE and ERC721 functionality 

Proposed additions are
1. AAVE - Follow Igovernor interface 
    - getVotes
    - createProposal
    - vote
    - cancelProposal
    - queue
    - execute
    - full cycle
2. ERC721
    - transfer
    - mint
    - burn

**Comment by timolegros** [comment]
@ianrowan Per our discussion on slack: return txn block number for every relevant route in `chain-testing`.
tldr: With the returned block number we can repeatedly check whether the listener has processed the desired block. If the listener has passed the block and no message was produced then we immediately know the test has failed. This avoids waiting for the test to time out if the listener fails to process the event.
