### ISSUE TITLE
Deprecate Chain Event Notifications from Notifications Dropdown Menu / View All Page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3234]
Currently, our Notifications Dropdown Menu (on react) is a merged and sorted list of 2 types of notifications, 
1. Chain Event Notifications
2. Forum Notifications

For the purposes of cleanup (to get to react faster), we should _no longer show chain event notifications_ in the dropdown menu (nor on the View All Notifications Page). We should simply not show them for the moment. Any logic regarding the fetching of notifications from the backend (in controller/routes) should stay the same.
The Chain Event Dashboard Feed should be un-impacted by these changes (will be where chain events show up until we re-enable notifications for chain events. 

Acceptance Criteria: 
- Forum Notifications load fine in dropdown and on view all notifications page
- Chain Event Notifications no longer load in dropdown or on view all notifications page. 
- Chain Event Feed on User Dashboard should still work as expected. (

**Comment by zakhap** [comment]
If this ticket doesn't go in prior to React Migration, then we shouldn't do it => we should just fix any potential problems with Chain Event Notifications in the Dropdown menu instead of deprecation.

**Comment by zakhap** [comment]
Default: Don't Need

**Comment by kurtisassad** [comment]
I think this had already been solved. Things are working like as mentioned in the acceptance criteria. Can you reconfirm @zakhap
