### ISSUE TITLE
Displaying trimmed thread does not show up in search results

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3237]
The problem is in `QuillFormattedText` component when searchTerm param is passed. In mithril world it worked, but in react it does not (there is a problem with the way how we 1. parse quill delta to html 2. parse html to string 3. truncate string) ([this all clause is problematic](https://github.com/hicommonwealth/commonwealth/blob/8debc50a5100dee5f046feac7c3ffd6c2d5130bd/packages/commonwealth/client/scripts/views/components/quill/quill_formatted_text.tsx#L52)) 

It seems that QuillFormattedText works fine in other places but the problem is only when the `searchTerm` is passed down (look for `renderQuillTextBody` with `searchTerm`). Solution would be fixing the chunk of code in QuillFormattedText or come up with new logic that would work in react. 

https://user-images.githubusercontent.com/14819225/227262216-1d00bae7-753c-4d28-9ba7-b55bafb01496.mp4

**Comment by CowMuon** [comment]
Is this still a 3 pointer @rbennettcw ?

**Comment by rbennettcw** [comment]
@CowMuon Yes, I'd still rank this at a 3, since it requires debugging search state logic and quill rendering logic.

**Comment by rbennettcw** [comment]
I've noticed a few different issues with the search feature, including buggy state, unclickable search results, and some search results not showing an excerpt. So I'm fixing the trimmed thread issue + other peripheral issues that I've found that are just as impactful.

**Comment by rbennettcw** [comment]
PR: #3358

**Comment by rbennettcw** [comment]
Working on adding tests for the quill render components used for richtext and markdown. Just to cover the basics.
