### ISSUE TITLE
Update Profile External API to include Forum UGC

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3241]
## Description

- external Profiles api endpoint should return:
    - [x] Profile
    - [x] Addresses
    - [x] Threads created by any address owned by Profile
    - [x] Comments created by any address owned by Profile
      - [x] The threads the comments are on (as commentThreads).

This is so that our external route is in feature parity with our internal Profiles route. See internal profiles route for relevant logic.

## Acceptance Criteria
- external api route should return same data in same format as internal api route

**Comment by kurtisassad** [comment]
Also added (for getProfiles parity):
[x] Chains which address is associated with
