### ISSUE TITLE
[Canvas JWT] Add Canvas/Express authentication middleware - core routes only

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#3243]
- [ ] Generate signed actions items in our database
    - Option 1: Materialized view approach
    - Option 2: Adding logic to createThread/createReaction/createComment
- [ ] Add GET route for getting new signed actions
- [ ] Add alternate authentication middleware
    - Wrap passport.authenticate('jwt') for createThread/createReaction/createComment
    - In new authentication middleware, map exact routes to `serverVerify` calling `verifyX(canvas_action, canvas_session)`

**Comment by CowMuon** [comment]
Rolling this over to Cycle 4, given it's a 5-8 pointer that has not been started yet.
