### ISSUE TITLE
[Post #4545] "Total Threads" shows only total on page, not total available within filtered settings

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3244]
## Description

- If you are on the Discussions Listing Page, in the upper right hand corner where we show the Total Threads for view, we show the thread total for _threads that we've rendered into view_, but not the real "total" for what threads are available for the view. This is probably a legacy error from before we paginated these pages, but we should show a true "total" rather than "rendered" number.

![Screen Shot 2023-03-23 at 1 56 55 PM](https://user-images.githubusercontent.com/16248081/227302279-6102b988-b822-41f2-a289-27551ce8fae0.png)
![Screen Shot 2023-03-23 at 1 57 04 PM](https://user-images.githubusercontent.com/16248081/227302282-9bba3f17-d5f4-412c-8340-d89f26b4c540.png)

## Acceptance Criteria
- The total threads within filter (all, by topic, by stage) should be the total number of threads that satisfy the request, rather than the threads rendered into view.

**Comment by jnaviask** [comment]
Will be closed by #3534.

**Comment by mzparacha** [comment]
@jnaviask The total num of threads will be fixed by #3534 but I think we would have to do something else for the applied state/topic filter, #3534 added a new `numOfThreads` field from api but it includes all threads count for that community. The count will be different in case of a filter

**Comment by jnaviask** [comment]
Thanks for the update @mzparacha. We should consider our plan a little more deeply here, because it seems like we haven't yet landed on a proper solution for topic-based thread counts. We may want to include by-thread counts on the bulkOffchain call.

**Comment by mzparacha** [comment]
Coming from [this](https://commonxyz.slack.com/archives/C051XFN57FT/p1690402766357799?thread_ts=1690394733.299189&cid=C051XFN57FT) slack discussion

I think a simple totalPages field from the/threads?active=true route would be good to solve this.
This might be done by using a COUNT query, i remember we had a discussion that it might have performance impacts, if we run it on every /threads?active=true api call. But i believe it wont be much big of an issue considering we are using pagination (and 20 records per page).

Consider we only refresh thread count once per topic, then there is also this case

- Event-1: User A loads /discussions/general -- see's thread count
- Event-2: User B adds a thread to the same topic
- Event-3: User A scrolls (they will see user b's thread but the count will remain the same, we will have to guess on when to refresh the count)

2 ways to solve this
- Always return updated count on each page (during thread pagination)
- Use sockets

**Comment by mzparacha** [comment]
I am more inclined towards returning updated thread count on each paginated response. Something similar was suggested [here](https://github.com/hicommonwealth/commonwealth/pull/3534#issuecomment-1530136900) before

**Comment by jnaviask** [comment]
@mzparacha can you attempt to discover the performance impact? Maybe in a draft PR? The solution you propose seems workable but would love to ensure we're not going to see a major performance hit.

**Comment by mzparacha** [comment]
Sure, i am still on https://github.com/hicommonwealth/commonwealth/issues/4545 (complex changes), which is also related to threads.

Please LMK if this is higher priority? @jnaviask

**Comment by mzparacha** [comment]
In #4545 we did some state updates along with other changes. I think we should hold it until #4545 is merged. Updated the title to reflect that.

Please LMK if you disagree.

cc: @jnaviask @CowMuon

**Comment by mzparacha** [comment]
Coming from https://github.com/hicommonwealth/commonwealth/pull/4588#discussion_r1289019605.

To summarize, we are using these counters for threads in a community
1. The total number of all threads in a community
2. The total number of all threads in voting in a community
3. The total number of threads per the applied filter for the `/threads?bulk=true` API

From @jnaviask [here](https://github.com/hicommonwealth/commonwealth/pull/4588#discussion_r1288747247)
> Thinking about it -- the way around the thread counters issue could be to augment the react-query config for topics, so that each topic knows how many threads it has. Something that might be worth ticketing.

Also from [here](https://github.com/hicommonwealth/commonwealth/pull/4588#discussion_r1289101157)
> Feel free to add a comment to https://github.com/hicommonwealth/commonwealth/issues/3244 linking back here + explaining the considerations (existing solution, proposed solution) and that should suffice.

To solve 1, we could as @jnaviask said, update topics to know how many threads they have and show the sum where we need the total but not sure how it would work in the case of 2. I think we could potentially make a separate count API for that
To solve 3, ATM, I would say that we update the `/threads?bulk=true` API to return the thread count.

**Comment by ForestMars** [comment]
TDB PENG office hours, 6/3
