### ISSUE TITLE
Reading from S3 for local development 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3248]
## Description
We are aware of an issue in local development where images can be uploaded to S3, but then they do not display because: 
1. There seems to be an issue with reading from S3 from a development environment. 
2. Architecturally, we seem to rely on retrieving the thing 

## Questions
- Does this effect Frick/Frack, or only explicitly local development environements? 
- Does this affect use cases where you upload an image and it is _immediately_ not visible? Or when you come back to a page that should have the image displayed? (Because we should be handling the image upload itself optimistically, and tbh, it should be locally cached, so I'm puzzled why this is even happening) 

## Acceptance Criteria
- [ ] Understand why this is happening
- [ ] Decide if needed now
- [ ] If so, fix

**Comment by jnaviask** [comment]
@CowMuon is this the same as #3213? Can we close?

**Comment by jnaviask** [comment]
Closed by #3213.
