### ISSUE TITLE
Sync Canvas oplog to Canvas Hub

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#3249]
- [ ] Standardize on final Commonwealth spec (should include all relevant data)
- [ ] Clean up codebase
- [ ] Copy IPFS hash over to Commonwealth codebase
- [ ] Deploy the new core service

**Comment by dillchen** [comment]
For clarity, Commonwealth runs Canvas Hub Nodes?

And we determine replication? (Aka we could be the only people running nodes)

And we can add other people "at will" to run other nodes?
