### ISSUE TITLE
S3 read issue

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3255]
## Description
This is an issue which we have been generally aware of for a while but need to understand what's causing it, scope of impact, and what the fix is. 

## Acceptance Criteria
- Understand how it happened and make determination for fix.  

Tagging this as Code Cleanup, since we were previously aware of the problem, but did not do anything about it, or document anywhere.

**Comment by jnaviask** [comment]
Can't reproduce.
