### ISSUE TITLE
New React Quill is missing in `New Snapshot Proposal` page

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3259]
![Image](https://user-images.githubusercontent.com/14819225/227942824-16998d42-70a5-4f45-9bb7-b147f64ec95d.png)

**Comment by rbennettcw** [comment]
Since the whole page is a mithril component, I am converting the whole page to React, not just the editor.

**Comment by CowMuon** [comment]
Really appreciate the update, will look for the PR, and if the original estimate fell short please add actual points here as a comment.

**Comment by rbennettcw** [comment]
Increased from 1 to 2 points since the original scope only included the editor component, but the entire page is mythril and needs to be converted to React.

**Comment by rbennettcw** [comment]
PR: https://github.com/hicommonwealth/commonwealth/pull/3295
