### ISSUE TITLE
Bet 1 -> React Conversion

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3274]
## Description

Now that the master branch is merged into react, the primary item left is converting Bet1 from Mithril to React. 
The first step here is to review what's needed here, and to outline the plan for execution.  We should also identify whether this is a full week's worth of work, or can be completed in the current sprint. (sprint 6)

Expectation is that @masvelio will draft a plan and @alexyoung23j will review. 
Alex & Marcin will lead the charge on execution, assisted by whatever additional team resources are needed. 
Estimating 1 point for this story; execution story expected to be 5-8 points. 

## Acceptance Criteria
- [ ] General plan of execution, added as a story to Github, linked here (and estimated)

**Comment by CowMuon** [comment]
Unassigned Marcin to avoid confusion as he is out this week.

**Comment by alexyoung23j** [comment]
Notes on conversion:

- app_modals can't be copied over directly.

**Comment by alexyoung23j** [comment]
These PRs need to be tested together to make sure the end to end bet1 flow is working!
