### ISSUE TITLE
🪣 Search back to baseline (Post-React)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3276]
## Description

This is a bucket ticket that requires the following tickets to be completed:
- [x] #3238 
- [x] #3237 
- [x] #3144 
- [ ] #2943 

In order of priority.

**Comment by CowMuon** [comment]
#2943 is super low-priority and is not blocking shipping React, but moreover is not needed to return search to baseline. 

This should now be closable, @zakhap please confirm search is back to baseline and cc: @rbennettcw for visibility.
