### ISSUE TITLE
Repoint Fast-follower 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3277]
## Description
As part of this morning's deploy we spun up a new Production database on Heroku, (owing to missing transactions in a migration scrip that was approved.) So now our fast-follower database needs to be re-pointed to the new production database as Heroku doesn't do that for you automatically. 

## Acceptance Criteria
- Fast-follower db (RED) is confirmed to be synched to the new Prod DB, not the old one. 

 ## Questions
@jnaviask - would this make a `good first ticket` for Nakul? He needs to familiarize himself with our Heroku setup.

**Comment by CowMuon** [comment]
Guys where is this? I know Jake was off today, but this is a P0 HIGHEST PRIORITY issue, labeled as such, with no blockers, and it looks like it was not even worked on today. 

What's going on here? 

@NakulManchanda

**Comment by NakulManchanda** [comment]
Issue is addressed, attached open PR as follow up for changes to Dev environment

**Comment by jnaviask** [comment]
Conclusion is:
- Heroku does not allow "repointing" of followers, only re-creating them, which was done as MAROON.
- To solve the issue of changing follower URLs in the future, we now have an environment variable "CW_READ_DB" on commonwealth-beta that exposes the URL of the read-only follower. We will update this variable if the follower URL ever changes again.
