### ISSUE TITLE
Investigate Heroku Timeouts 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3281]
## Description
Following on this morning's deployment we have been seeing somewhat increased timeouts on Heroku than usual. We need to devote time and resources to understanding what the issue here is.

**Comment by CowMuon** [comment]
Added this to our board, but tbh we have a lot still to be completed before EOW, which is also EOQ.

**Comment by jnaviask** [comment]
Cannot reproduce.
