### ISSUE TITLE
Fix root_id refactor migration script

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#3289]
## Description
Root Id migration script failed to run on production. Also move all the mutating queries into the same transaction.

**Comment by CowMuon** [comment]
@NakulManchanda Will you please let Kurtis know when Beta's fast follower is pointed at PUCE so he is unblocked here? Kudasai.

**Comment by NakulManchanda** [comment]
its MAROON pairing with JAKE to make it RED again
