### ISSUE TITLE
Increase size of production database on heroku

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3291]
## Description

Currently hitting OOM errors on Standard-0. Let's bump to Standard-2 to take advantage of increased RAM.

https://hicommonwealth.slack.com/archives/C02QARJ3QG7/p1680295665545949
[#4624 10th error: SequelizeDatabaseError: out of memory](https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/4624?utm_campaign=exp_repeat_item_message&utm_medium=slack&utm_source=rollbar-notification)

- [ ] @jnaviask to provision
- [ ] Follow steps on heroku docs to promote
- [ ] Reattach follower

**Comment by NakulManchanda** [comment]
Hey @jnaviask 
Here is the plan as per heroku
https://github.com/hicommonwealth/commonwealth/wiki/database#scenario-change-db-plan-heroku

**Comment by jnaviask** [comment]
Either route is fine. Still want to set up instrumentation though, to determine which size is ideal based on resource constraints.

**Comment by NakulManchanda** [comment]
**Available Heroku Postgres Plans**
https://devcenter.heroku.com/articles/heroku-postgres-plans

<img width="766" alt="image" src="https://user-images.githubusercontent.com/4791635/229221210-c5e74585-3405-4b56-9a4d-0a68a0f19015.png">

**Our Current plans on Heroku:**
<img width="801" alt="image" src="https://user-images.githubusercontent.com/4791635/229221381-71a9c691-4ffc-4276-ac0e-df56f43e9c00.png">

**Comment by jnaviask** [comment]
Wont fix.
