### ISSUE TITLE
Infinite loop on thread page

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3300]
Probably caused by reactions.Both remote env and local

![Image](https://user-images.githubusercontent.com/14819225/229147843-028540bf-e2cf-4b00-94c9-7cb0ab8e2b89.png)

https://user-images.githubusercontent.com/14819225/229147874-577fe4bf-4736-4ee0-b517-453867554b08.mp4

**Comment by dillchen** [comment]
Probably should be critical pathed cc: @MuonShot / @zakhap

**Comment by CowMuon** [comment]
Teeing this upfor Kurtis. Can you please confirm 1 point estimation here @kurtisassad
