### ISSUE TITLE
Write tests for server-side action processing

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#3306]

**Comment by CowMuon** [comment]
Since you made the ticket Imma move it into backlog, only JTN we generally look for a higher level of detail on this board (than issue description provides as-it-currently-is.)

**Comment by CowMuon** [comment]
Is this done @raykyri? It's marked as Done on the other board.

**Comment by raykyri** [comment]
It's done, and part of the current session keys PR.
