### ISSUE TITLE
/viewUserActivity route query is very slow

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3316]
## Description
Update the notifications schema and/or `/viewUserActivity` route to improve performance. The route currently takes more than 2 seconds to return.

## Acceptance Criteria
- Sub 1 second response time for `viewUserActivity` route

**Comment by CowMuon** [comment]
Pair @NakulManchanda 

Do we have an idea what the solve for this is? If so, let's add that here kudasai.

**Comment by NakulManchanda** [comment]
yes, it has a open PR
https://github.com/hicommonwealth/commonwealth/pull/3317

We left comments, @timolegros approach is good will resolve the issue!
its a common theme actually, we can use for converting  a column out of JSONB attribute
Added Tim's idea to wiki as well:
https://github.com/hicommonwealth/commonwealth/wiki/database-optimization#slow-reads
