### ISSUE TITLE
Add payable field and logic - Bet 1

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3325]
#### Background

Ethereum transactions have two sets of parameters
* data params- the parameters passed to the smart contract logic
* Transaction params - parameters used to facilitate a tx(value, gasPrice, gasLimit)

Currently templates allow for form references for data parameters, but not transaction data. Many solidity/smart contract methods can be set as `payable` meaning a user must send some ETH along with the tx. In the current design these types of transactions could not be templated.

#### Proposed Approach

To start with payable as an initial tx param to support, we can treat it like any other param(text input with number formatter). The only change required would be to add a field in the tx_template key of the template like `tx_data`. Then from there place the ref of the `value` param in this new key and add logic at the function encoding step to encode this to tx data separately.

**Comment by jnaviask** [comment]
Need design / product context on this cc @zakhap
