### ISSUE TITLE
WalletConnect Mobile Broken

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#3327]
New bug though: I am unable to login to the forum via mobile. I’ve tried connecting my 1inch wallet (connection shows as successful in my wallet), but when I go back to the forum, it still gives me the login option. The email login link isn’t working for me either via mobile.

Able to reproduce:
- WalletConnect login on mobile (logging in on chrome on a phone) via Metamask and Rainbow, login fails.

Acceptance:

User is able to log in via walletconnect on mobile devices.

**Comment by alexyoung23j** [comment]
Pinned down the (first) error to `this._web3 = new Web3(this._provider as any);` in walletconnect_web_wallet.ts

This doesn't throw an error but this._web3 is not being initialized correctly because when, in `getRecentBlock()`, we attempt to `const block = await this._web3.givenProvider.request({
      method: 'eth_getBlockByNumber',
      params: ['latest', false],
    });`, this._web3.givenProvider is null.

**Comment by CowMuon** [comment]
@alexyoung23j Will you please add a comment with revised point estimation and a short note on what the complexity is? Thanks.
