### ISSUE TITLE
Ensure global activity cache initialization does not block application startup

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3329]
## Description
Currently, the global activity cache populates itself on startup. This is a blocking action, which prevents the server from spinning up in a reasonable amount of time. Currently, the cache itself is disabled on production / QA / staging with the NO_GLOBAL_ACTIVITY_CACHE env var. We want to turn it back on to unblock the global for you feed.

## Acceptance Criteria
- App startup should happen within 60 seconds even without NO_GLOBAL_ACTIVITY_CACHE.
- Global activity feed should display with expected information.

**Comment by CowMuon** [comment]
My understanding is this is fixed on React and will ship when we launch.

**Comment by NakulManchanda** [comment]
it looks like it is
https://github.com/hicommonwealth/commonwealth/commit/eea73aee4bd594b4ac5a4f2b1dd0af140604cf22

We can start redis async too, but thats not a blocker, thanks!
