### ISSUE TITLE
Set up database performance monitoring in Datadog

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3343]
## Description

In preparation for further refactoring and architectural changes for performance improvement, monitoring services need to be set up in Heroku and Datadog.
1. Configure Heroku permissions and agent values
2. Set up Datadog dashboards using new sources
3. Fully document final process for reproducibility

## Acceptance Criteria: 
- [ ] Heroku changes confirmed and documented.
- [ ] DB performance monitoring having live outputs from Postgres on at least one functioning dashboard
- [ ] Document "final process"

**Comment by NakulManchanda** [comment]
Random Notes:

https://us5.datadoghq.com/integrations/postgres
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/4791635/230176004-f20e9c75-4303-4318-9847-608d9d7f0773.png">

**Comment by NakulManchanda** [comment]
as per https://us5.datadoghq.com/integrations/postgres may require restart
- Create Datadog user
- Grant permissions to `pg_monitor` `pg_stat_database`
- postgresql.conf - `logging_collector = on`
- datadog.yaml file: `logs_enabled: true`
- sample postgres.d/conf.yaml - https://github.com/DataDog/integrations-core/blob/master/postgres/datadog_checks/postgres/data/conf.yaml.example
- 

<p class="druids_typography_editorial-copy__element" style="box-sizing: inherit; margin-top: calc(var(--ui-custom-line-spacing) * var(--ui-custom-reduced-vertical-spacing)); margin-right: var(--ui-max-width-margin); margin-bottom: 0px; margin-left: var(--ui-max-width-margin); --ui-max-width: initial; max-width: var(--ui-max-width); padding-top: var(--ui-custom-extra-padding); padding-bottom: var(--ui-custom-extra-padding); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: ; font-variant-east-asian: ; font-variant-alternates: ; font-weight: 400; font-stretch: ; font-size: ; line-height: ; font-family: NotoSans, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, sans-serif; font-optical-sizing: ; font-kerning: ; font-feature-settings: ; font-variation-settings: ; color: rgba(28, 43, 52, 0.98); letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Required environment variables on the Agent container:</p><div class="druids_typography_text druids_typography_text--md druids_typography_text--default druids_typography_text--normal druids_typography_text--left druids_typography_text--not-editorial-copy druids_table_table druids_table_table--size-md" style="box-sizing: inherit; font-family: NotoSans, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, sans-serif; line-height: var(--ui-header-line-height, var(--ui-base-line-height, inherit)); font-weight: 400; color: rgba(28, 43, 52, 0.98); font-size: 13px; text-align: left; --ui-base-font-size: initial; --ui-base-line-height: initial; --ui-header-font-size: initial; --ui-header-line-height: initial; --ui-header-font-weight: initial; --ui-header-letter-spacing: initial; --ui-header-text-transform: initial; --ui-header-size-h1: initial; --ui-header-lh-h1: initial; --ui-header-ls-h1: initial; --ui-header-tt-h1: initial; --ui-header-fw-h1: initial; --ui-header-size-h2: initial; --ui-header-lh-h2: initial; --ui-header-ls-h2: initial; --ui-header-tt-h2: initial; --ui-header-fw-h2: initial; --ui-header-size-h3: initial; --ui-header-lh-h3: initial; --ui-header-ls-h3: initial; --ui-header-tt-h3: initial; --ui-header-fw-h3: initial; --ui-header-size-h4: initial; --ui-header-lh-h4: initial; --ui-header-ls-h4: initial; --ui-header-tt-h4: initial; --ui-header-fw-h4: initial; --ui-header-size-h5: initial; --ui-header-lh-h5: initial; --ui-header-ls-h5: initial; --ui-header-tt-h5: initial; --ui-header-fw-h5: initial; --ui-header-size-h6: initial; --ui-header-lh-h6: initial; --ui-header-ls-h6: initial; --ui-header-tt-h6: initial; --ui-header-fw-h6: initial; --ui-hr-width: initial; --ui-max-width: initial; --ui-max-width-margin: initial; display: flex; flex-direction: column; --table-resizer-color: transparent; --colspan: 1; --rowspan: 1; --table-row-height: initial; --table-bulk-actions-height: initial; --table-auto-rows: initial; --table--has-border: initial; --table-outer-border: var(--ui-border); --table-inner-border: var(--ui-border); --table-inner-border-width: 1px; --table-border-radius: 4px; --table-cell-border-radius: 0px; --virtualized-offset: 0px; --has-virtualized-placeholder: 0; --table-extra-z-index: 1; --scroll-left: 0px; --table-header-height: 28px; --has-visible-bulk-actions: 0; --table--is-not-loading: initial; --table-cell-padding-x: 7px; --table-cell-padding-y: 8px; --table-row-background: initial; --table-passive-row-hover-background: var(--ui-background-secondary); --table-cell-color: inherit; margin-top: calc(var(--ui-custom-line-spacing) * var(--ui-custom-reduced-vertical-spacing)); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="druids_table_table__root-wrapper" style="box-sizing: inherit; --ui-custom-line-spacing: initial; --ui-custom-extra-padding: initial; z-index: 0; position: relative; flex-shrink: 1; min-height: 0px; display: flex; flex-direction: column;"><div class="druids_table_table__root" style="box-sizing: inherit; position: relative; flex-shrink: 1; border-radius: var(--table-border-radius); padding: var(--table--has-border, 1px); --bulk-actions-height: var(--table-bulk-actions-height, var(--table-row-height, 33px)); --header-groups-count:1; --columns-count:2; --columns-widths:minmax(calc(5px + 2 * var(--table-cell-padding-x)), auto) minmax(calc(5px + 2 * var(--table-cell-padding-x)), auto); --table-template:&quot;_0 _1&quot;;"><div class="druids_table_table__batch" style="box-sizing: inherit; position: relative; display: grid; align-content: start; grid-template-areas: var(--table-template); grid-template-columns: var(--columns-widths, repeat(var(--columns-count), auto)); grid-template-rows: repeat(calc(var(--header-groups-count) + var(--has-virtualized-placeholder)),auto); grid-auto-rows: var(--table-auto-rows, auto);">

PARAMETER | VALUE
-- | --
<DD_API_KEY> | api_key
<DD_APM_ENABLED> | true
<DD_APM_NON_LOCAL_TRAFFIC> | true

</div></div></div><div class="druids_table_table__footer" style="box-sizing: inherit; --ui-custom-line-spacing: initial; --ui-custom-extra-padding: initial; display: flex; flex-shrink: 0; flex-wrap: wrap; justify-content: space-between; align-items: center; margin-left: -8px;"></div></div><br class="Apple-interchange-newline">

**Comment by NakulManchanda** [comment]
https://docs.datadoghq.com/agent/basic_agent_usage/heroku/
