### ISSUE TITLE
Improve the performance of the query in `queryGlobalActivity.ts`

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3348]
## Description
We have refactored the query in `/viewUserActivity` but the query in `queryGlobalActivity.ts` is very similar and could use similar performance improvements once the global activity cache is fixed (#3329).

**Comment by NakulManchanda** [comment]
Blocked by PR - https://github.com/hicommonwealth/commonwealth/pull/3317

## Current query:
- return latest 50 notifications from thread based on recency of comments 
- latest notification id per community per thread - pre-computed can help with speeding up this query

## Plan 
- pre-compute max value of notification in thread table

## pros
- simpler faster query
- easy to implement - by adding another column like max_notification_id, like view count

## cons
- can get out of sync

## how to keep it updated
- can be synced nightly once - or every 2-3 hours as precaution

**Comment by timolegros** [comment]
Fixed by https://github.com/hicommonwealth/commonwealth/pull/6127
