### ISSUE TITLE
Migrate Kyve starter community to on-chain

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3353]
## Description
That thing that we do. 

## Due date
4/5/2023

**Comment by jnaviask** [comment]
```
=> SELECT id, name, default_symbol, network, type, bech32_prefix, chain_node_id FROM "Chains" WHERE id = 'kyve';
  id  | name | default_symbol | network |   type   | bech32_prefix | chain_node_id 
------+------+----------------+---------+----------+---------------+---------------
 kyve | KYVE | KYVE           | osmosis | offchain | osmo          |            20
```

We want to change network to "kyve", type to "chain", bech32_prefix to "kyve", and chain_node_id to the proper chain node id for kyve network, which is 1270. That node itself will need to be updated to use the correct URL.

These changes should happen after #3247 is shipped.
