### ISSUE TITLE
Zapier Webhook Support

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#3366]
PRD: https://www.notion.so/buildcommon/PRD-Zapier-Webhooks-1e262c787de94e6da4d15932c2382180?pvs=4

**Technical Spec:**
- Update `webhookNotifier.ts` to include a case for "url.indexOf('zapier')".
- Create the json object that stores the webhook data for Zapier

Awaiting BD confirmation on the shape of that object.

**Comment by CowMuon** [comment]
Is this approved??

**Comment by alexyoung23j** [comment]
It's on the bug board and Zak/Rhys discussed it, didn't know it was in question

**Comment by zakhap** [comment]
let's get this scoped in a lil PRD. Feel free to draft a stub and then we can get BD's approval on what it needs to be, and then I'll thumb up the scope and we can get this going

**Comment by CowMuon** [comment]
Just for additional context here, we're literally having the Refinement rn, and if already had that (Zapier request came in on Friday 3/31 I believe?) this could have been scoped for completion for next Sprint. Let's see if we can squeeze it in anyway, so we're not losing a full week. That means we would need a PRD for this by tomorrow.

**Comment by CowMuon** [comment]
Moving this out of backlog as it was never refined.

**Comment by alexyoung23j** [comment]
@CowMuon not sure what refinement means exactly but the PRD is attached to the ticket, was awaiting approval.

**Comment by CowMuon** [comment]
@alexyoung23j Right, backlog is for stories that have been refined. We may accelerate this one to jump queue, not sure yet as we also have React to launch.

**Comment by jnaviask** [comment]
@alexyoung23j going to tee this up post sprint planning because we really want this out.
