### ISSUE TITLE
Support Proposal Linking on Kyve (cosm gov v1)

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3367]
## Description
In order to support proposal linking in Kyve, we need to ensure Chain Events are present in the backend. This may require at minimum updating the subscriber, enricher, and storageFetcher logic within chain events.

## Acceptance Criteria
- We are able to link proposals to threads on Kyve.

**Comment by dillchen** [comment]
This also implies we will also be able to link proposals  across Cosmos as well, right?

**Comment by jnaviask** [comment]
Will be closed by #3357.
