### ISSUE TITLE
React Deploy to Production

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3368]
## Description
We need to deploy the React branch to production. There are two possible paths to doing this.

### Route 1: Github Pipeline
In this route, we follow our standard heroku process (push to `origin/master`, push to `heroku/master`) by manipulating github branches. We may want to perform steps 1-4 at least 24 hours prior to expected deployment on master, in order to allow us to validate the React branch against QA.
1. Remove Github branch protection on `master`.
2. Rename `origin/master` to `origin/archived-master`.
3. Rename `origin/react` to `origin/master`.
4. Push an empty commit to `origin/master` and allow React to deploy on commonwealth-beta. Verify deployment success.
5. Force push `origin/master` to `heroku/master`. Allow React to deploy on commonwealth production. Verify deployment success.
6. Reenstate Github branch protection on `master`.

**Pros**: deployment process is the exact same as for any other release.
**Cons**: requires force pushing over heroku git history. Requires multiple rebuilds for deployment.

### Route 2: Heroku Pipeline
In this route, we use Heroku's "promote" tool to send the React slug directly to master, bypassing all the git changes.

**WARNING 1**: we will still need to perform the above git steps once the deploy has succeeded, in order to ensure all incoming changes are against the new master branch.

**WARNING 2**: Heroku promotes the slug directly from one deployment to the next. This means that Webpack `DefinePlugin` changes **WILL NOT BE REBUILT**. See step 1 below.
1. Ensure the following environment variables are IDENTICAL on commonwealth-react and commonwealth production: `COSMOS_GOV_V1`, `DISCORD_UI_URL`, `DISCORD_CLIENT_ID`, `MAGIC_PUBLISHABLE_KEY`.
2. Ensure the buildpacks are identical on commonwealth-react and commonwealth production.
3. Push an empty commit to `react` and allow React to deploy on commonwealth-react. Verify deployment success.
4. Use either the web UI or the `heroku pipelines:promote` CLI to promote the commonwealth-react slug to commonwealth production.
5. Wait for the release phase to complete on commonwealth production. Verify deployment success.
6. Once deployment is completed, perform github steps above, per warning 1, without the force push to `heroku/master`.

**Pros**: the exact same slug is deployed in both cases, so we can know in advance that production will look the same as the React branch.
**Cons**: we have never performed a promotion-based deployment before. The github steps still have to be done anyway.

## Acceptance Criteria
- Current `react` branch must become `master`. Current `master` must become `archived-master`.
- Current `react` branch must be deployed on the production heroku environment.

**Comment by kurtisassad** [comment]
There should be a pre-deploy step where we copy the db from beta to react-staging, and then push an empty commit to react-staging in order to restart it with the latest react branch. This is because the migrations could have been run out of order on the react branch (due to cherry-picking changes in a different order), causing unexpected behaviours.
