### ISSUE TITLE
React Branch CI Pass

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3369]
## Description
Currently the React branch does not pass CI. We need to ensure the branch passes the following parts of the CI workflow:
- [x] e2e tests
- [x] unit tests
- [x] API tests (integration)
- [x] typecheck

## Acceptance Criteria
- React branch should pass CI with a nice green checkmark on github.

**Comment by kurtisassad** [comment]
Working on integration tests

**Comment by jnaviask** [comment]
All that's left CI-wise is typechecking.

**Comment by rbennettcw** [comment]
@jnaviask Here's a PR to fix typechecking for all components that use quill logic: https://github.com/hicommonwealth/commonwealth/pull/3423
