### ISSUE TITLE
Integrate React Testing Library into CI

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3383]
## Description
We want to use React Testing Library to test our components without needing to write full playwright tests that simulate the entire webpage loading.

Scope of ticket is to integrate the library and write at least one test case, as a demonstration of what it can do. Choose whatever component you'd like for the demonstration test. Use mocha for the test itself, as we already have existing uses of mocha in the repo.

Then, add a package.json command + a CI step so that our component tests run as part of our CI testing flow.

## Acceptance Criteria
- Command + CI step that runs React Testing Library-based component tests.

**Comment by Miaplacidus** [comment]
* First Attempt w/ Mocha: Worked to integrate Mocha  + Enzyme into the test suite. I've tried just using ts-mocha, but that ultimately results in an error having to do with babel dynamic imports (our component files use dynamic imports, thus mocha is unable to find relevant modules). I've also attempted to get the tests up and running with instant-mocha, which allows you to run tests using webpack. Got a bit farther wit that. However, it fails in the middle of the test, asking for a loader capable of processing the spec. If you're curious, you can find the work done on branch 3383_integrate_component_testing. Check out the commands 'test-fe' and 'test-feim' in the scripts section of package.json. All of the relevant test files can be found in the frontend directory of the tests folder. 

Will be attempting to get component testing working with Jest next.

**Comment by Miaplacidus** [comment]
* Second Attempt w/ Jest: Currently running into a Jest/Node issue where modules are assumed (despite our attempts at configuration) to be imported using CommonJS. Had a chance to pair with Kurtis on this one, where we made some progress, but are still running into the ESM vs CJS issue.
