### ISSUE TITLE
Unsticky RecentThreadsHeader 

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3387]
## Description
The RecentThreadsHeader is currently sticky, over the infinite scroll for the discussions page. This is not desirable behavior, as it takes up too much screen real estate / doesn't feel good to use.

## Acceptance Criteria
- The RecentThreadsHeader should no longer remain sticky and should instead scroll away as you scroll down the page.

**Comment by kurtisassad** [comment]
fixed by #2871
