### ISSUE TITLE
Cherry-pick notifications fix onto react.

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#3392]
Corresponding master ticket:
https://github.com/hicommonwealth/commonwealth/issues/3354

## Description
Notifications was broken due to the root_id refactor. Cherry pick these changes from master onto the react branch.

## Acceptance Criteria
- [x] cherry-pick changes from master onto the react branch

**Comment by jnaviask** [comment]
What is this for / what work is this?
