### ISSUE TITLE
🪣 Finalize react quill transition

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#3398]
✅ Currently, all instances of the quill editor have transitioned from using the mithril version (`QuillEditor`) to using the wrapped react version (`ReactQuillEditor`).

⚠️ However, when it comes to **rendering** quill content, some active rendering logic lives in the old `quill` directory while some lives in the new `react_quill_editor` directory.

What needs to be done:
- [x] #3548

Upon confirmation from Zak/etc. – implement the following into `ReactQuillEditor`:
- [x] #3549
- [x] #3550
- [ ] #3552
- [ ] #3551

Once complete, we can delete the `quill` directory.

**Comment by zakhap** [comment]
@rbennettcw all of these things a great to add. Tentatively confirmed by me, but in what ways does this impact the Quill Editor UI? Is there a new UX flow added for video/twitter embeds? Or does it _just happen_ as a part of a Quill Package? Just need some more information, prior to confirming

**Comment by rbennettcw** [comment]
@zakhap AFAIK, the UI/UX wouldn't change much for these features. They're just addons to the quill editor, so they enable the user to add custom "blocks" to their content.

One thing that would change the UI/UX is adding the Markdown toolbar controls. Currently, you'll notice that in markdown mode, the controls disappear. This was a workaround to get to production faster, but it's a regression. In markdown mode, the buttons apply markdown edits to highlighted code.

**Comment by zakhap** [comment]
Fantastic, then yes, I am 100% for these addons to Quill to be implemented. I do, however, want to pass any quill-toolbar updates to Design so that they have visibility on the changing Quill Editor here. If there is any advanced notice about which addons are being selected, I can take the relevant screenshots + circulate relevant info to Design as well.

**Comment by jnaviask** [comment]
I will ticket these separately so we can track each work item independently + will flag this as a bucket / tracking ticket.

**Comment by jnaviask** [comment]
@zakhap note that these product features have been ticketed, but are light on details. User Mentions + Markdown toolbar are fairly easy to reproduce from pre-React, but we should ensure we're aligned on how embeds should work.

**Comment by jnaviask** [comment]
Closing this ticket, as we have reached feature parity with and entirely removed the old quill components. Extra / new features will be tracked as such.
