### ISSUE TITLE
Show post preview before a new thread is created & allow thread creator to select whether to show an excerpt

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#340]
- [ ] Pop up a preview window before a thread is created, so the author can review what they've written in DiscussionRow and full page format
- [ ] Allow threads to be set as preview-visible or preview-hidden
- [ ] Allow setting whether the thread is preview-visible or preview-hidden from the edit thread interface

Overall goal is to make sure we don't have unreadable previews on listing pages:

![image](https://user-images.githubusercontent.com/1273926/84070267-b7a25a80-a980-11ea-859c-62432202954b.png)

**Comment by jnaviask** [comment]
Still a good feature idea.
