### ISSUE TITLE
Fix unique check when showing users that have replied to a thread & show tooltip when hovering over icon

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#341]
![image](https://user-images.githubusercontent.com/1273926/84070342-d86ab000-a980-11ea-9d5b-529fa3493d7c.png)

Currently, some addresses are shown multiple times. They should be deduplicated.

Hovering over an icon should show a tooltip (this is as simple as configuring the User component to set tooltips on)

**Comment by zakhap** [comment]
Upon inspection, it doesn't seem as though the profile is being shown more than once. 
Below is a dump of the addresses in the example. We can see Dillon's 2 near addresses and one of his edgeware addresses. Each of the address's individual Offchain Profile have the same/similar image set, resulting in the duplicating.

`0: (2) ["kusama", "H9i61N2WsHJ6z657cJ4wgH7p9p991FZTDyDfwa3HsdrqgXe"]
1: (2) ["edgeware", "kDyksb52FQmL7y4B7PcuMbf3SHhCmDKrbF8CRrXKJ9Zs1QF"]
2: (2) ["edgeware", "i1qK2WFRwvaBmCvgAaKmQw5JuKjmSW4SH63pvx244R2E6cR"]
3: (2) ["edgeware", "iCLdev9eJBSaUSD1qnbq1roqcV6jZmfLpbLJjTdmUocixcY"]
4: (2) ["near", "iamdillon"]
5: (2) ["near", "dillchen"]
6: (2) ["edgeware", "n3QXeWUUHS5dr1uMKrtvcJ9yYot1PovRjTzQ3ch7E71TFiy"]
7: (2) ["near", "suspendedreason"]
`
