### ISSUE TITLE
Threads sort is not persistent on menu item click

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3415]
Click between All and Overview (or any other topics). Also you can try dropdown with topic filter. The list of threads is different every time it loads

https://user-images.githubusercontent.com/14819225/231467588-e60516f4-409f-455f-8db5-9c57bddfc83c.mp4

**Comment by masvelio** [comment]
actually it looks like there is something off with the pagination. It is visible clearly on http://localhost:8080/dydx/discussions/5.%20Liquidity%20Staking%20Pool

- total threads number is 22 
- first page is 20
- second page is 2
- looks like clicking the topic each time is firing next page load until the response is empty and the page got blank

**Comment by CowMuon** [comment]
Teeing this up for @martins87. Please coordinate with @masvelio on what the correct approach should be here.

**Comment by masvelio** [comment]
I really believe that @kurtisassad can give more insights here as he worked extensively in this area recently
