### ISSUE TITLE
React: view thread page responds poorly to page resizing

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3417]
## Description
If you resize the view thread page, then following issues occur:
- Scrollbar disappears
- Text wrapping overflows off right side of page

https://www.loom.com/share/3dcc4fba49d6458698073e2348f340df

## Acceptance Criteria
- The view thread page should respond well to page resizing.

**Comment by jnaviask** [comment]
This is very much still a problem. See attached loom. https://www.loom.com/share/3dcc4fba49d6458698073e2348f340df

**Comment by masvelio** [comment]
This works fine for me, I checked chrome, firefox and safari both on stage and local and could not reproduce that

https://user-images.githubusercontent.com/14819225/232484773-03fa9903-0cbb-40ae-97b4-174df99ec9fb.mp4

**Comment by masvelio** [comment]
@jak
