### ISSUE TITLE
Investigate page load speed

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3424]
## Concern
[dydx overview on React branch](https://commonwealth-react.herokuapp.com/dydx/overview) seems to be loading significantly slower than [production](https://commonwealth.im/dydx/overview). We need to investigate to determine why this is. 

This is probably post-launch, and performance may even be improved  by one of the front end performance targets we have already identified. Or, it could be an unrelated issue, and those performance improvements might otherwise fool us into thinking it was fixed. 

## Acceptance Criteria
- Justified hypothesis on page load time and plan to fix.

**Comment by jnaviask** [comment]
Stale.
