### ISSUE TITLE
P0: 1inch Wallet Not Working -- FAILED QA

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3430]
## Description
Hot on the heels of the WalletConnect fix, it's been reported that 1inch wallet users are experiencing difficulties signing their login transaction (so presumably signing anything? Or is this limited in scope to the login module? And just to be clear we don't know that the reported login problem is because signing is broken; that's just a hypothesis based on other wallets working, so expectation is breakage is localized to transaction signing? )

TBC: The WalletConnect fix that was shipped to resolve #3327 failed QA. Except that QA was/is post-deployment, and they were told this is now working. That's a big deal.  We need to turnaround the real fix for them, stat. 

## Plan 
- @mzparacha  is very new to the team, but it's super important we turn this one around, so Teeing this up for him to work on, on the overnight (sorry, I know that's idiomatic.) 
- As soon as @ianrowan gets in, will you please take a look at this, and see if it's something obvious? I would start with Ray's Session Keys PR which recently went in (linked below) just to rule that out. 
- @alexyoung23j Same for when you get in, jump please jump right into this. First thing is track down answers to any/all questions, adding answers as comments as you go. 

I'm hopeful this will be a quick fix (because we do need to promote React to QA, which unfortunately will block hotfixes for an estimated 72-ish hours.) Best would be for this to go out first thing Thursday morning. (ie today.) 

## Questions (for Product/BD)
- [ ] How many 1inch users are experiencing the problem? 
- [ ] Have we tried to reproduce? 
- [ ] Can we get any additional context & colour here? 

## Questions (Engineering)
- [ ] Was this ever working? Or was this not caught in testing?
- [ ] Did we test 1inch wallet when we shipped [the WalletConnect fix](https://github.com/hicommonwealth/commonwealth/pull/3338)? 
- [ ] Which wallets DID we test explicitly when we shipped that? 
- [ ] This wasn't a breaking change introduced by [#3339](https://github.com/hicommonwealth/commonwealth/pull/3339/files) (Session Keys) , was it? **<---- check first.** 
- [ ] That PR bumped `ethers` from 5.4.3 to 5.7.2. That doesn't break a 1inch wallet dependency, does it? 
- [ ] The WalletConnect fix was merged a week ago, what day did it 🚚? @jnaviask 

## Acceptance Criteria
- 1inch wallet login works, _as does signing any / all transactions_
- Thoroughly test the bejezus outta this in 1inch. Stone turning should target 100% 

## Additional Questions
Some additional questions for context here such as how do most members of 1inch community log on? Because the expectation would be using 1inch wallet except that implies 1 of like 3 things, none of which are particularly good:
1.  If most 1inch users use 1inch wallet, no one has been logging into their community since we shipped the fix that didn't work. 
2. Worse than that, it obviously implies they were unable to login before that. So how were they using Common? 
3. Option 3 here is they just logged in with a different wallet and we didn't notice they're not even using their own wallet. 
Not sure what the answers are here, not blocking getting this fixed, but our overall process of kowing how our users are doing could stand major improvement. (cc. Sachin, Meesh)

## Dragons
Not needed here, but just for trackbacks: [Notion page for this bug](https://www.notion.so/buildcommon/3265-1inch-Mobile-Walletconnect-broken-ad8c23174a3b424e9408439e0f61e3e6)

**Comment by jnaviask** [comment]
Deployed, waiting for successful customer feedback to close.
