### ISSUE TITLE
Frequent Query: Add in-memory cache to validateChain middleware.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3434]
### Problem

As described in #3429, we are having connection timeouts. It was determined that one of the main offenders is the `validateChain` middleware, which is called a massive number of times.

### Proposed Solution

Add an in-memory cache to the `validateChain` middleware, to dramatically reduce the number of database queries required per request.

### Background

The validateChain middleware, added in #2339, was intended as a replacement for manual validation checks at the top of each route, which, when provided with a chain id, would validate that the requested chain (= community) existed in the database. All chain-scoped routes use this middleware to identify the community as context for serving the request.

### Technical Considerations

The validateChain query looks at three tables: `Chains`, `ChainNodes`, `Topics`.

- `ChainNodes` is highly stable. The table is only modified either manually as part of hotfixes, or at community creation (/createChain).
- The `Chains` table is also highly stable. New entries are added in 3 places: `/createChain`, `/putCommunities`, and `/getTokenForum`. Entries are only deleted in the `/deleteChain` route, which is only callable by commonwealth internal users. However, the rows of the Chains table may be modified by various community admin configurable routes.
- The `Topics` table has a set of CRUD routes (create / update / delete / edit Topic) as well as routes that perform additional editing, such as `orderTopics`. For some reason, topics can also be created in `createThread`.

Since these tables directly affect the properties of communities, and since so many routes affect these tables, we must use a very short TTL, and even include invalidation for certain routes so that admins can see the updates immediately. For example: a user creating a community (chain) should be able to access the community (chain) immediately.

However, even a very short TTL will bring us large gains, as community initialization triggers several chain-scoped calls in a short time window.

_**Please describe your implementation plan in this ticket, so we can sign off before implementation begins. Feel free to ask for any other information needed to proceed.**_

## Acceptance Criteria
- ValidateChain middleware should query from an in-memory cache, which should cause significantly reduced database load, per datadog / pg_stats analysis.

**Comment by NakulManchanda** [comment]
One question though @jnaviask 
- Chains, ChainNodes, Topics
are we piggybacking this middleware to pre-emptively fill data for next middleware in route?

chain_id exists or not is a much simpler call
`SELECT 1 FROM "Chains" as "Chain" where "Chain"."active" = $1 and "Chain`.id = $2`
or 
SELECT 1
 FROM "Chains" AS "Chain"
INNER JOIN "ChainNodes" AS "ChainNode" ON "Chain"."chain_node_id" = "ChainNode"."id" 
WHERE "Chain"."active" =$1 and and "Chain`.id = $2`
```
Do we need topics data?

instead our current call is:
```
 FROM "Chains" AS "Chain"
 LEFT OUTER JOIN "Topics" AS "topics" ON "Chain"."id" = "topics"."chain_id" AND ("topics"."deleted_at" IS NULL) 
INNER JOIN "ChainNodes" AS "ChainNode" ON "Chain"."chain_node_id" = "ChainNode"."id" WHERE "Chain"."active" = $1`
```

**Comment by NakulManchanda** [comment]
Here is screenshot of where its get used, its get used even in Magic_AUTH

if we are pulling more data we need, we can add another query to just check exists rather than getting all the details.
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/4791635/231810885-14baa9d4-5f0f-4199-a0a2-a0ca5357653a.png">

**Comment by jnaviask** [comment]
I agree that we _should_, in theory, pull additional data in the routes. However, do a search for `req.chain` to see use cases across the routes -- we want to avoid the implementation growing massively in scope.

**Comment by NakulManchanda** [comment]
yes, 
- we will keep `req.chain`  just creating new one without topics
- `createThread` - leaving current middleware as it is

**Comment by jnaviask** [comment]
Sounds good. Just make sure to add the topics query as needed back into the createThread route.
