### ISSUE TITLE
Cosmos SDK shared devnet

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#3440]
As a companion to the `csdk` sandbox community, deploy a live Cosmos SDK testnet node.
To be `gov` v1 testable, this should be at SDK v0.46.11

**Available now:**
https://cosmos-devnet.herokuapp.com/rpc
https://cosmos-devnet.herokuapp.com/lcd/

**Comment by mhagel** [comment]
very curious about deploying this on akash: https://docs.akash.network/

**Comment by mhagel** [comment]
https://github.com/akash-network/cosmos-omnibus/pkgs/container/cosmos-omnibus

**Comment by NakulManchanda** [comment]
its done, working
@mhagel setup up new app on heroku
we were able to deploy it using Docker

https://cosmos-devnet.herokuapp.com/rpc
https://cosmos-devnet.herokuapp.com/lcd/

thanks @mhagelfor writing all the tests and ui changes, now integration tests written can reply on this devnet url

**Comment by NakulManchanda** [comment]
once integration tests included in PR runs successfully
we can mark it done and close the issue
https://github.com/hicommonwealth/commonwealth/pull/3377

**Comment by NakulManchanda** [comment]
nginx conf example:

```
events {
  worker_connections  1024;
}

http {
  server {
    listen 80;
    server_name localhost;

    location /rpc {
      proxy_pass http://127.0.0.1:26657/;
    }

    location /lcd/ {
      proxy_pass http://127.0.0.1:1317/;
    }

  }
}
```
