### ISSUE TITLE
Add metadata viewing to templates on Contracts page.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3445]
## Description

> Add metadata about who (user profile/address) and where (community) the Contract action was created. The information about who and where the Contract action was created should be communicated to the user on the Contract page. Contract action is what we will be calling the actions executed using the template that has been created such as a treasury spend proposal or vote delegation. 

[Designs](https://www.figma.com/file/xXjVv3sPgaD9DjCmR0EGlt/Action-Templates?node-id=135-12926&t=S0unZfSy5h8E4cx7-0) Under Eng Refinement > Who created this contract action, when and where

## Acceptance Criteria

User browses the Contracts page. UI displays the user the Contract actions that have been created. User navigates to _Enabled by_ in the Contract actions card and sees who has created this action and in what community 

## Technical Requirements

The model `CommunityContractTemplateMetadata` needs several columns added: 'created_at', 'enabled_by' (an address). These will be added as params to the route  `createCommunityContractTemplateAndMetadata` and written as part of the row creation. The frontend models will need to be updated as well, and the `/bulkOffchain` route updated to return this new data. 

In anticipation of another page design is working on and will be created at a later date, updates to the model `template` will occur as well; addition of columns 'created_at', 'created_by' (an address), 'description', and 'created_for_community' (a chain id) are required. 

The frontend components `ContractTemplateCard` and `contract_card` will need to be modified to pass the correct data for display and to match the new designs. The create new template page will also add a new input that will write to the 'description' in `template`.

**Comment by zakhap** [comment]
Moreover, this ticket is not just about adding metadata viewing, but also _adding_ the proper metadata to the template model itself. Model changes should be described in spec.
