### ISSUE TITLE
React: Add bet 1 feature flag

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3450]
## Description

Per Product team: "bet 1 should be removed from react branch until we have these fast follows done. Bet 1 team determined that these fast follows were *required* to ship bet 1. Bet 1 should not go out with react if these are not done."

The fast follows in question:
- #3447
- #3446
- #3445 

We do not want to block React deployment on the completion of these three tickets, and we do not wan to remove the Bet 1 code from the repo (as this is a significant number of files affected + database schema changes), so we should instead gate Bet 1 behind a feature flag to ensure users cannot access the Bet 1 product features until we are ready to ship.

TODO: scope which UI items / pages should be gated by feature flag.

## Acceptance Criteria
- Bet 1 should not be visible or usable in any form if feature flag is disabled.
- Bet 1 should be fully usable if feature flag is enabled.

**Comment by masvelio** [comment]
From my perspective only these things should be behind feature flag:

- `Contracts` menu item in the sidebar (`admin_section.tsx`)
- Following routes in `customDomainRoutes.tsx` and `commonDomainRoutes.tsx`
  - `/contracts`
  - `/new/contract`
  - `/new/contract_template/:contract_id`
  - `/contract/:contractAddress`
  - `/:contract_address/:slug`
