### ISSUE TITLE
React: Remove Community Homepage Feed

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3454]
## Description

This is temporary but the Community Homepage _needs_ a design pass that we don't have time for prior to getting react live. We will remove it until it gets the attention it needs. During QA, @masvelio rightly identified that it is not ready for users to interact with. 

Most of the logic + changes made for the "community homepage" were in this PR: https://github.com/hicommonwealth/commonwealth/pull/2699/files

However, there were some further changes made to both the "community homepage" and the "user dashboard" via a "feed component" refactor in this PR: https://github.com/hicommonwealth/commonwealth/pull/2813/files

### Spec to be confirmed by @MuonShot + @jnaviask 

Zak's suggestion: 
- Make a PR that does 3 things:
  - Reverts #2699 
  - Removes any "community homepage" code lingering from #2813.
  - Leaves in codebase the refactored "feed" component used by the "user dashboard". 

## Acceptance Criteria
- We remove all code related to community homepage from react branch without breaking the user dashboard's usage of the feed component.

**Comment by masvelio** [comment]
if we want to keep homepage for the NEAR future, the easiest solution probably would be just hiding it for the user for now in couple places (where he can click + route). We can do that even with the feature flag or delete only the code that is responsible for accessing this feature. Not a best practice to leaving the dead code in the code base though. Just another idea.

**Comment by zakhap** [comment]
> if we want to keep homepage for the NEAR future, the easiest solution probably would be just hiding it for the user for now in couple places (where he can click + route). We can do that even with the feature flag or delete only the code that is responsible for accessing this feature. Not a best practice to leaving the dead code in the code base though. Just another idea.

Given that we _do_ have designs for this to be further implemented, this might not be a bad solution! However, as this feature is "stale" insofar as it has been in development for a long time (mostly waiting to be shipped), we might find there are product, design, + UX improvements we want to make prior to it going live. 

I think I still differ to my first suggested solution of removing it from the codebase until we're ready to handle it in a proper push.

**Comment by jnaviask** [comment]
I agree with Marcin's solution of removing access to it via the front-end and deleting relevant components. I'm hesitant to revert the code directly, because it involves a database migration, and we've validated the current state of migrations but this will change which migrations run on deploy, which is something we don't want to do.
