### ISSUE TITLE
Thread listing disappears on back button navigation

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3483]
## Description
Per @raykyri:
- go to http://localhost:8080/aave/discussions
- click into a thread
- go back
- thread listing is now empty

## Acceptance Criteria
- The back button should return the user to a properly populated threads page.

**Comment by masvelio** [comment]
this should be fixed after merging https://github.com/hicommonwealth/commonwealth/pull/3436

**Comment by martins87** [comment]
> this should be fixed after merging #3436

Indeed clicking back is now loading the threads it is supposed to.
