### ISSUE TITLE
Join button is visible even though I am already in this community

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3501]
Current behaviour: 
1. being not logged in, go to the community you are part of eg /dydx
2. log in 
3. Join button is visible

Expected behaviour:
3. Join button is not visible

https://user-images.githubusercontent.com/14819225/233046875-dd3f1f9d-ee5e-46b0-8692-9ee014c585f9.mp4

**Comment by jnaviask** [comment]
This could be caused by having logged in previously on a different community -- in which case, you will be logged in, but wont have joined DYDX yet, as correct behavior. Does this describe the situation?

**Comment by jnaviask** [comment]
Thank you for the clarification!
