### ISSUE TITLE
Notification settings - checkboxes and switches work in unexpected way

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3503]
Current behaviour: 
1. being logged in go to notification-settings page
2. play around with checkboxes and toggles & reload page
3. Sometimes the checkboxes and toggles have opposite values that they supposed to have

Expected behaviour:
3. After changing checkbox or toggle state and reloading the page, the state should be the same as before the reload

https://user-images.githubusercontent.com/14819225/233054024-7c67360f-e031-4dee-a4c9-a2622cbe4358.mp4

**Comment by mzparacha** [comment]
@masvelio Not able to reproduce point 3. I tried quickly switching states but that too worked fine. Can you share what repro steps you tried?

**Comment by masvelio** [comment]
> @masvelio Not able to reproduce point 3. I tried quickly switching states but that too worked fine. Can you share what repro steps you tried?

it can be reproduced when you check or toggle the item and reload the page. But the origin of the problem is in sort as you figured out!
