### ISSUE TITLE
Rework on sidebar toggle icon

### ISSUE THREAD

**Issue by martins87** [hicommonwealth/commonwealth#3514]
As discussed on this [Slack thread](https://app.slack.com/client/T04ATE49PM2/C050N2EF77X/thread/C050N2EF77X-1681926751.331249), make adjustments on the sidebar toggle icon:
- It must have an x on that < icon
- It needs to be more noticeable and also look clickable

**Comment by jnaviask** [comment]
In the future, please do not link to slack threads as ticket descriptions. The ticket should be self contained, giving the person reading it enough context to fully understand the problem described (and any proposed solutions to be implemented in a PR).

**Comment by martins87** [comment]
> In the future, please do not link to slack threads as ticket descriptions. The ticket should be self contained, giving the person reading it enough context to fully understand the problem described (and any proposed solutions to be implemented in a PR).

Ok.

**Comment by jnaviask** [comment]
Stale.
