### ISSUE TITLE
Show Treasury Balance in UI

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#353]
Currently, the Edgeware Treasury balance shows null. We should fix this so that the balance is accurately pulled from the chain.

This happens on both master + construct

**Comment by raykyri** [comment]
It should be possible to look up how this is calculated in the polkadot.js/apps code. Lmk if you need help tracing through it

**Comment by zakhap** [comment]
@raykyri This is a copy of my thoughts from the slack.

Spending some time looking through the polkadot api to get the balance of the treasury pot for CW, i've learned a few things:
- It doesn't seem that there's an explicit call to get the pot (like the `api.query.social.pot` for the amount of the account balance that is specifically for the next society round's bid).
- It's obviously not a const,
- nor is it a preimage, proposal, or tip in the storage module (`api.query.treasury.*`, directly)

While the pot is not accessible directly, it seems as though the treasury events `Rollover(balance)` and `Spending(balance)` return the `[budget_remaining]` which I assume to be the treasury pot's current state. Is this a fair assumption? If so, would be storing the treasury balance in our server via chain-events be the right approach for getting treasury balance in the UI?
