### ISSUE TITLE
Update Proposal Status modal throws unnecessary "Thread Chain must support snapshot" error message

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3538]
## Description
BD reported. See video: https://www.loom.com/share/e8c716989287440db6f0c7654ecac06e

## Acceptance Criteria
- User should be able to update thread stage without error message about snapshot, regardless of whether snapshot is enabled.
- User should be able to add/remove/update linked proposals without error message about snapshot, regardless of whether snapshot is enabled.

**Comment by mzparacha** [comment]
Not reproducible

**Comment by jnaviask** [comment]
Did you try on the right community? Try /regen to see if that works.

**Comment by mzparacha** [comment]
I thought it was on all communities, trying regen

**Comment by mzparacha** [comment]
Ok so i tried regen but was not able to create a thread there, so i created a new cosmos based community and there I got the error. Now working on a fix
