### ISSUE TITLE
Add controller stubs with failing tests for Linking system

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3539]
## Description
First step for #3357. If we stub out the controller logic, we can parallelize the front-end and backend work (separate tickets TBD) to close #3357 = implement a linking system without requiring chain events.

## Acceptance Criteria
- Should expose a controller file with failing tests, that permits backend and frontend implementation to be completed separately / in parallel.

**Comment by ianrowan** [comment]
Using this PR/Branch for Feature. Currently includes stubs for this issue
https://github.com/hicommonwealth/commonwealth/pull/3542
