### ISSUE TITLE
Consolidate quill rendering logic

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3548]
## Description

Some lingering instances of the old markdown renderer are still in use across the site, from before the React migration.

## Acceptance Criteria
- All markdown_formatted_text instances are from the react_quill_editor.
- Old (pre-react) quill folder is removed.

**Comment by rbennettcw** [comment]
Estimate: 2 – requires minor code updates + must test affected areas for regressions.

**Comment by rbennettcw** [comment]
This update is a bit more involved than simply replacing the instances of the old component. Bumping to a 5.

Some context:
- There's now a single component responsible for rendering all richtext/markdown content: `QuillRenderer`.
  - This component contains 2 subcomponents: `QuillFormattedText` and `MarkdownFormattedText` for rendering richtext and markdown, respectively.
- Throughout the frontend, there are a few old inconsistencies in how components are rendered. I'm working on consolidating all quill rendering to use the universal `QuillRenderer`.

Affected areas:
- Profile activity row
- Profile header
- Notification settings text row
- View snapshot proposal body
- Tip detail
- Notification comment preview

This required a bit of refactoring in some parts, and I'm still in the process of CA testing the affected features.

Once complete, dealing with rendering quill content will be much more simple and straightforward.
