### ISSUE TITLE
Quill: add Markdown toolbar controls + keyboard shortcuts

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3549]
## Description

We currently have a toolbar for the Quill richtext editor, and we used to also have a toolbar for the markdown editor. However, this toolbar was removed as part of the React migration.

## Acceptance Criteria
- Reintroduce the markdown editor toolbar controls and keyboard shortcuts, in accordance with pre-react site behavior.

**Comment by rbennettcw** [comment]
Estimate: 2 – can reuse some code from the pre-react implementation, though may require tweaks.
