### ISSUE TITLE
Quill: add User mentions

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3550]
## Description

User Mentions was a feature we had pre-React that was not delivered as part of React.

The existing controller logic around user mentions may need reworking as part of the new Profiles feature, so feel free to dig in and clean that up a bit, as we expect user mentions to be quite widely used.

## Acceptance Criteria
- Reintroduce User Mentions, in accordance with pre-react site behavior.

**Comment by rbennettcw** [comment]
Estimate: 3 – can reuse some pre-react code, but may require tweaks to accommodate new profile system.
