### ISSUE TITLE
Spin up Cosmos v1beta devnet + tests

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3563]
## Description
#3440 added a Cosmos v1 devnet + a suite of tests for Cosmos functionality on v1. We should extend this testing support to Cosmos v1beta as well, to ensure we don't have regressions against existing Cosmos communities.

## Acceptance Criteria
- Cosmos v1beta devnet deployed.
- Cosmos v1beta tests written + added to CI.

**Comment by mhagel** [comment]
@jnaviask FYI, optimizing this for minimal CI time added probably 2 points.

**Comment by mhagel** [comment]
I also looked into running mocha tests in parallel, but it is a finicky feature. I gave up after a couple of hours of attempts.
