### ISSUE TITLE
Images from ipfs:// links do not render in Snapshot proposal body markdown

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3567]
## Description
BD reported. See the content loaded for [this proposal](https://commonwealth.im/itheum/snapshot/itheumdao.eth/0xc40a21d5fa2ff4002afdfc14cbe6c8a792f27782f1a12dde249d4582e94f406b). The body contains the following text:

```
1. Option 1
 
![image](ipfs://bafkreihchboolscwy5xlojnbsolpox22xc3gy7belnn3zfufxlr33hw5fm)
    
2. Option 2 
 
![image](ipfs://bafkreihg4ah6ktjttdm7q43khbq5v3k43p6j5ay7xmxlnmmr53fn57l2ay)
```

This text does not render properly, as we do not support IPFS images in our markdown renderer.

## Acceptance Criteria
- ipfs:// image links should render if provided as image links in markdown.
- ipfs:// non-image links should remain broken if provided as image links in markdown (i.e. do not render text, etc).

**Comment by CowMuon** [comment]
Should be a 1 pointer. If that doesn't match your estimate @rbennettcw please update when you move this to in progress.
