### ISSUE TITLE
Quill: Links no longer get formatted as links unless they are specified as so in the menu

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3583]
## Description
BD reported. Links don't automatically populate when pasted into the editor. This is a regression from the pre-React editor. We can use this library to make it happen: https://github.com/visualjerk/quill-magic-url

Note from BD:
> Toyed around with it and turns out that hyperlinks break the formatting even in md for some reason

## Acceptance Criteria
- Quill should automatically populate links when pasted into the editor.
- Quill should properly format posts with hyperlinks both in rich text and markdown modes.

**Comment by rbennettcw** [comment]
Think this is a 1 pointer, as we can use existing code or the quill-magic-url library.

**Comment by jnaviask** [comment]
Awesome. We also received a bug report that hyperlinks currently break formatting, so hopefully this ticket will fix that issue as well.

**Comment by rbennettcw** [comment]
@jnaviask Pushed a PR to fix format URL on type/paste.

Can you clarify your last comment about hyperlinks breaking formatting? Are there steps to repro that?
