### ISSUE TITLE
Race condition causing /bulkThreads to fail if called prior to `app.chain.id` loading.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3598]
## Description
- Add `console.log(params);` to `loadNextPage` in `controllers/server/threads.ts`
- Go to network tab of chrome console and enable "Slow 3G"
- Navigate to http://localhost:8080/dydx/discussions
- Look at console output -- notice that `chain` is undefined, and that this causes /bulkThreads to fail.

We need to identify and fix the race condition so that /bulkThreads does not fail if thread loading occurs prior to app.chain initialization. The `chainAdapterReady` emitter may be of use here.

Check against #3603 once resolved as the two may be related.

## Acceptance Criteria
- /bulkThreads should not fail on slow network connections.

**Comment by mzparacha** [comment]
Will do this after #3673

**Comment by mzparacha** [comment]
Looks like its not happening anymore. testing...

**Comment by mzparacha** [comment]
@jnaviask I was able to reproduce this consistently some days but after pulling master not reproducible anymore

**Comment by jnaviask** [comment]
Cannot reproduce. Will reopen if reappears.
