### ISSUE TITLE
Threads should not refresh from server when navigating to/from discussions page

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3599]
## Description
Currently, when you click on various topics, or to members/proposals tab and then back to a discussion topic, we refresh the list of threads from the server. This is undesirable behavior, as the threads should be available in the store + it makes the site feel clunky to navigate (white flashes whenever you click around the sidebar).

## Acceptance Criteria
- Threads should not refresh from server on clicking around the site / sidebar.

**Comment by dillchen** [comment]
additional note (that may be addressed here). While the whole page does not flash, Navigating between topics via the sidebar, the search bar will disappear and then reappear. This is similar

**Comment by mzparacha** [comment]
> additional note (that may be addressed here). While the whole page does not flash, Navigating between topics via the sidebar, the search bar will disappear and then reappear. This is similar

Will be fixing that as well
