### ISSUE TITLE
Reproduce & fix "loading chunk failed" error

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3601]
## Description
In closing #3582 we re-introduced the old code to display an application update message on chunk loading error. However, this error page is persisting in showing post-deploy despite the reintroduced code. We need to come up with a way of reliably reproducing this error, and then deploy a fix that succeeds.

<img src="https://user-images.githubusercontent.com/1860629/234455617-abb1c55b-8d46-4374-8b97-bf136e2276cc.png" height="600">

## Acceptance Criteria
- Find a way to reliably reproduce chunk loading error.
- Ensure that chunk loading errors produce a message instructing the user to refresh the page.

**Comment by masvelio** [comment]
idea to reproduce: 
- build production version locally and serve it locally 
- run the app 
- try to change the name of the chunk in `build/js` directory
- see if error is visible
