### ISSUE TITLE
Navigating directly to a valid thread via URL sometimes displays Not Found error

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3603]
## Description
To reproduce, hard refresh the following page a few times: https://commonwealth.im/dydx/discussion/11149-requesting-to-setup-growth-topic

This bug may be related to initialization flow, and so we should re-test this bug against the solution for #3598 (or vice versa) to ensure the two do not have the same root cause.

## Acceptance Criteria
- Navigating to a thread directly via URL should always / reliably render the thread content.

**Comment by kurtisassad** [comment]
Can't reproduce either locally or on prod. Steps tried:

* Reloading with enabled + disable browser caching
* Reloading with being logged in + being logged out

**Comment by jnaviask** [comment]
Can't reproduce. Will reopen if we can find more details.
