### ISSUE TITLE
Investigate why Substrate identities store is sometimes missing

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#363]
- Navigate to settings page from a chain
- Use back button to navigate back
- deinit() is called and the identities module store is missing (this.store === undefined)

I am adding an if statement to avoid clearing the store for now, but we should figure out why it's missing

**Comment by raykyri** [comment]
Adding @jnaviask on this because it seems to be a problem in other parts of the app:

I mentioned on Slack one instance where this might happen. https://hicommonwealth.slack.com/archives/CT2302L7L/p1591754274011000

If you remove the if statement that I added on `raymond.construct` and follow the replication steps above, the root cause should be the same.

**Comment by jnaviask** [comment]
Removed the if statement, could not replicate :(

**Comment by raykyri** [comment]
Replication seems to depend on localStorage being cleared, these steps might work

- Use an fresh Incognito window, so localStorage is empty
- Enable polkadot-js on that window
- Log in to any EDG address using polkadot-js
- Clear out of any remaining login windows, navigate to edgeware homepage
- Go to settings menu and click “Profile”
- There should be a getById error (edited)

**Comment by jnaviask** [comment]
Cool -- was able to reproduce!
