### ISSUE TITLE
Forum Improvement: Show when a post is New

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3640]
## Description

We want to show users when a forum thread is new!

Task: Add a "NEW" tag to thread preview component when a thread is new.

Tag Design Specifications:
- NEW in text type caption, capitalized
- 4px padding top and bottom
- 8px padding left and right
- Tag height should be 24px in total (caption height _should be 16px_)

Tag Behavior Specifications:
- Tag should appear when a thread is younger than 2days / 48h (`createdAt < 2 days`)
- Tag should appear on thread preview cards on Discussion Listing Page and on Overview Page.

Screenshots: 
![Screen Shot 2023-04-27 at 3 47 21 PM](https://user-images.githubusercontent.com/16248081/235007477-b617ac76-397e-4868-a749-2238e7855b06.png)
![Screen Shot 2023-04-27 at 3 47 28 PM](https://user-images.githubusercontent.com/16248081/235007482-e70ccd0a-37a1-46ee-8d69-4b1eca461a47.png)

Link to Figma: https://www.figma.com/file/NGcMaoQ1xYgx1YuL8kaHou/Forum-Improvements?node-id=402-16999&t=vHi1hsivhwXvhzOo-0

## Acceptance Criteria
- Tag satisfies Design Specifications
-  Tag shows up properly on both Discussion Listing Page and Overview Page

**Comment by dillchen** [comment]
https://www.notion.so/buildcommon/Show-when-post-is-new-4b9b4f8faf414ddabb50288e55afcac4?pvs=4 this is the link for the V2

**Comment by kurtisassad** [comment]
Thanks for pointing this out. I had fixed the PR to reflect these changes
