### ISSUE TITLE
Fix update thread status modal

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3646]
## Description

The update thread status modal has been broken since react migration.

Update threads list after saving 'update status' modal.

![image](https://user-images.githubusercontent.com/14819225/235199725-b393d7f1-da9c-4a0c-bba5-301d96c8ed3a.png)

**Comment by masvelio** [comment]
https://github.com/hicommonwealth/commonwealth/pull/3542/commits/df122e2f60976f7e5a38189d6174987fc1cee2b6
