### ISSUE TITLE
Add descriptions on-hover over icons in validator list.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#365]
We are now showing icons for ImOnline, toBeElected, and potentially other messages. It would be worthwhile to be able to hover over these icons and see a description of their purpose.

**Comment by nblogist** [comment]
@drewstone 
1: I have seen the different icons on the page, can you tell me which icons represent what (ImOnline, toBeElected)?
2: What information do you want to display in the tool tip, apart from the names of the icons?

**Comment by drewstone** [comment]
Sure thing @nblogist 

The lines after each condition should be the corresponding icons: for example, the wifi icon corresponds to being online from the look of it. https://github.com/hicommonwealth/commonwealth/blob/7f32219b68f3064a12a2f45c818fc5c7c53000bd/client/scripts/views/pages/validators/substrate/validator_row.ts#L141

As for what information to be displayed, simple fillers should do for now. Anything that indicates "validator is online" or "validator is to be elected" is a good start.
