### ISSUE TITLE
React best practices and improvements doc

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#3669]
Create doc that will describe drawbacks of our current react project and propose improvements

**Comment by masvelio** [comment]
next steps: doc review => tickets creation

**Comment by masvelio** [comment]
moved to github wiki https://github.com/hicommonwealth/commonwealth/wiki/React-best-practices-&-improvements

**Comment by jnaviask** [comment]
This is really good, thanks Marcin! cc @CowMuon as well to take a look.
