### ISSUE TITLE
Add component for selecting Cosmos proposals to link in update proposal status modal.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3674]
## Description

Currently, the update proposal status modal uses the ChainEntitiesSelector to provide a list of Chain Entities for the user to select as links. We need a component with similar function for Cosmos proposals.

Alternatively, if easy, the ChainEntitiesSelector can be expanded to support Cosmos proposals from the store as well as Chain Entities (but I think separate components is a better solution).

## Acceptance Criteria
- Users should be able to link Cosmos proposals as they would link a proposal backed by a chain entity.

## Good to know
Existing fetch methods:
controllers/chain/cosmos/gov/v1/utils-v1.ts - `getActiveProposalsV1(lcd)`: 
controllers/chain/cosmos/gov/v1beta1/utils-v1beta1.ts - `getActiveProposalsV1Beta1(rpc)`

Existing hook for lazy-loading completed proposals:
hooks/cosmos/useGetCompletedCosmosProposals.tsx - `useGetCompletedCosmosProposals` works for v1beta1 and v1

You can use these methods for `CosmosGovernance` and `CosmosGovernanceV1` cases by accessing their APIs like this. These can then be passed into the methods like above (ask @mhagel if any questions):
```
const lcd = (app.chain as Cosmos).chain.lcd;
const rpc = (app.chain as Cosmos).chain.api;
```

**Comment by ianrowan** [comment]
Like with other links, to be clear, we want to save the link of a selected proposal like:
 ```
 {source: proposal, identifier: 'osmosis/proposal/496', title: 'Regular Incentive adjustment for 2023-05-01'}
 ```
 And when loading proposal links assign identifier as the hyperlink like other proposals

**Comment by ianrowan** [comment]
WIP on branch `ian.cosmos_linking` has included required components and logic for cosmos linking. Aside from some react related bugs 
- toggling away chain entities for cosmos chains 
- QueryList not rendering even though I can see it + the proposals loaded into it in the react component debugger
- sorting proposals 
From here there should only be minor bugs, if any to get a proposal linked. 
important files include:
1. `client/scripts/views/modals/update_proposal_status_modal.tsx`
2. `client/scripts/views/components/cosmos_proposal_selector/cosmos_proposal_selector.tsx`
3. `client/scripts/views/components/cosmos_proposal_selector/cosmos_proposal_selector_item.tsx`
