### ISSUE TITLE
Cosmos proposals not loading when landing on proposal page directly

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3683]
## Description
If you land on the proposal page directly, i.e. clicking link https://commonwealth.im/osmosis/proposal/28-semiautomatic-incentive-adjustments-for-08232021 -- you get "Proposal not found". Only works when navigating from Proposal page.

## Acceptance Criteria
- Should be able to directly access proposal pages without getting Proposal not found.

**Comment by mhagel** [comment]
Can confirm that this functionality relied completed proposals being included in chain init. (Still works for active).
