### ISSUE TITLE
Markdown thread previews display with markdown syntax

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3692]
## Description
BD reported: 
![image](https://user-images.githubusercontent.com/1860629/236033942-43a160d5-2457-44a6-b545-65cd6be8166d.png)

## Acceptance Criteria
- Thread previews should not render markdown syntax, but instead should render the same content as if the thread were created with richtext.

**Comment by rbennettcw** [comment]
@jnaviask Not able to repro. I scrolled through prod dashboard and didn't see any thread previews that looked like this. I believe this is already fixed by https://github.com/hicommonwealth/commonwealth/pull/3688

**Comment by jnaviask** [comment]
Closing as cannot reproduce.
