### ISSUE TITLE
Remove mithrilInterop layer

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3703]
## Description
Once #3701 #3702 and #3673 are closed, there will be no more "old style" ClassComponents remaining in the codebase. At this point, it is safe to deprecate the mithrilInterop helper completely. We should remove the file/folder and take any remaining helper functions in use into a more standard/agnostic location for utilities.

## Acceptance Criteria
- Remove the mithril interop layer!

**Comment by masvelio** [comment]
@jnaviask I think that we should have one more additional ticket before the cleanup that will handle replacing `_DEPRECATED_getSearchParams`, `_DEPRECATED_getRoute`, and `_DEPRECATED_dangerouslySetRoute` from `mithrilInterop/index.ts`

**Comment by jnaviask** [comment]
Yeah I figured we would move those to a util for the time being, but definitely worth removing.

**Comment by CowMuon** [comment]
What is this blocked by @jnaviask @masvelio @mzparacha

**Comment by masvelio** [comment]
@CowMuon blocked by #3702
