### ISSUE TITLE
Add caching to ipfsProxy route

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3708]
We use /ipfsProxy to load metadata for aave proposals. This metadata doesn't change, so we should add our redis caching here, with a relatively long TTL.

**Comment by NakulManchanda** [comment]
@jnaviask when does this endpoint trigger?
- https://github.com/hicommonwealth/commonwealth/pull/3898
- caching response for 24hours per `req.query.hash`
