### ISSUE TITLE
Investigate tanstack-query (react-query) use on client

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3709]
## Description
Please come up with some ideas for how we can best integrate a library like tanstack-query into the app. I believe we can massively streamline some parts of the codebase + improve the feel of the site as well, but I'd like us to do a little digging before we dive in and start coding.

Feel free to post ideas on this ticket, and we can make other tickets for the specific changes needed.

**Comment by dillchen** [comment]
Very interested to see the fruits of this / see updates here:

- Speaking from the user's perspective, if I may, the painpoints / visual glitches on the site seems very closely tied to state management. Like #3436. or other page flashes and more.
- So coming up with a holistic solution seems very useful.

My question here is, do you need product / design to make sure we have the proper user stories here?

**Comment by masvelio** [comment]
@dillchen I would consider this task as a spike so generally do the research and try to figure out how we can hook react-query up to our project and what kind of benefits we can get. Thus, proper user stories are not essential at this moment, but for sure they will be soon, so we will know what should we focus on from the user perspective, developer perspective and in holistic way - as you said!

Generally threads are super messy and in my opinion this area should be the first thing to improve - ideally with new state management approach. #3436 is definitely example of state management quirks -- we don't have single source of truth. On the other hand, flashes or glitches - I would say this is not super related to the state (related too but not as much as previous example), rather how we handle the flow of fetching data from multiple endpoints and visualise it to the user.

We will try to come up with some ideas and will keep this ticket up to date. For now I just finished zustand research https://github.com/hicommonwealth/commonwealth/pull/3731

**Comment by mzparacha** [comment]
With tanstack-query, I think we could make custom-hooks related to each entity(api resource) like a `useThreads` hook, that would handle thread related api calls with optimistic updates and rollbacks in case of error. The hook would return the fetched/cached value of threads. In case if any other entity(api resource) updates threads, then we would update thread state in that hook.

So something like this
```jsx
import React from 'react';
import { useMutation } from '@tanstack/react-query';

const useThreads = () => {
  const fetchThreadByIdQuery = useMutation({
    // triggered 1st: here we update state value optimistically
    onMutate: () => {
      const oldThreads = []; // fetch old threads from react query store

      // here we will calc optimistic value for threads and update store

      // return the value before optimistic update, we will use this to
      // fallback to previous state in case of an error
      return { oldThreads };
    },
    // triggered 2nd: here the actual api call happens
    mutationFn: async (payload) => {
      // fetch/mutate threads in api
      const fetchedThreads = post(`/api/....`, payload);

      // return the fetched threads
      return fetchedThreads;

      // alternatively, if we want to merge fetched threads with existing
      // we do so here and return the updated value, react query also has
      // an infinite query option for querying + caching paginated results
    },
    // here we will fallback to previous state + show error state
    onError: (err, originalPayload, valueBeforeOptimisticUpdate) => {
      // use the value before optimistic update to revert query store
    },
  });

  //   Add more queries

  //   const fetchThreadsQuery = ....

  //   const updateThreadByIdQuery = ....

  //   const deleteThreadByIdQuery = ....

  return {
    fetchThreadByIdQuery,
  };
};

export default useThreads;
```

and we will use it in a component like this
```jsx
import useThreads from 'client/scripts/hooks/api/useThreads';
import React, { useEffect } from 'react';

const DiscussionsPage = () => {
  const { fetchThreadByIdQuery } = useThreads();

  useEffect(() => {
    const payload = {}; // pass the payloa
    fetchThreadByIdQuery.mutate(payload);
  }, []);

  // we can show different states
  fetchThreadByIdQuery.isError;
  fetchThreadByIdQuery.isLoading;

  // and use the data
  fetchThreadByIdQuery.data;

  // or use other out of box things provided by react query

  return <>{/* ... */}</>;
};

export default DiscussionsPage;
``` 

For a demo, I will create a PR for the threads store to use react query. 

@masvelio curious as to what you think about ^

**Comment by masvelio** [comment]
need to spend more time to wrap my head around that!

**Comment by mzparacha** [comment]
I created [PR#3741](https://github.com/hicommonwealth/commonwealth/pull/3741) for some demo RQ implementation. Also used topics instead of threads for demo, as topics were a bit easier to navigate through

**Comment by masvelio** [comment]
update: tomorrow I will write some summary based on our research, PR and comments

**Comment by masvelio** [comment]
I summed up our discoveries and pointed out next steps we can take in this doc https://github.com/hicommonwealth/commonwealth/wiki/React-Query-foundations

I consider this ticket as done
