### ISSUE TITLE
Forum Improvements: Show Stage Tags

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#3716]
## Description

As part of the React migration, we lost stage tags on the discussions listing. This is now a top 3 BD reported ask from users, so we want to reintroduce the stage tags.

Design is as follows (only need to implement the stage tag):

![Image](https://user-images.githubusercontent.com/1860629/236573823-536e6d38-6ca9-46b6-9b34-2c259ef15ca4.png)

Clicking on the stage should take you to the stage filtered discussions page.

Designs may change after first pass, but this should be enough to get us ready to ship whenever.

## Acceptance Criteria
- Threads on discussions page display stage tags.

**Comment by masvelio** [comment]
1. Should default stage tag be visible in threads list? In View thread page we have logic like this so in thread page view default stage is not visible.
```
          thread.stage !== ThreadStageType.Discussion && (
            <ThreadStage thread={thread} />
          )
```
Others are visible 
![image](https://user-images.githubusercontent.com/14819225/236836318-178c9c47-0aad-48fe-bbc1-b14d1167b386.png)

2. If community has custom stages, what should be default stage assigned to the thread during creation? Right now there is a logic that takes first stage from the list if there are custom stages defined. Otherwise it takes `discussion` stage. Is this logic correct? 
```
        app.chain.meta.customStages
          ? parseCustomStages(app.chain.meta.customStages)[0]
          : ThreadStage.Discussion,
```

**Comment by masvelio** [comment]
@dillchen @zakhap can you help answer those, please

**Comment by jnaviask** [comment]
I want to also note that we want stage tags on the overview page as well as the discussions page, per BD ask.

@masvelio Will follow up with Zak/Dillon to get you the answer by EoD today.

**Comment by zakhap** [comment]
# Designed Spec

### Context
Figma: https://www.figma.com/file/NGcMaoQ1xYgx1YuL8kaHou/Forum-Improvements?type=design&node-id=606-31321&t=7zpBNb8ZepKFQpIP-0
Original PRD: https://www.notion.so/buildcommon/Re-adding-Stage-tags-in-Post-Previews-8f927147e8474bb3ba2fa52da00589d5

## Solution + Requirements
<img width="705" alt="Screen Shot 2023-05-08 at 7 39 24 PM" src="https://user-images.githubusercontent.com/16248081/236959568-702b12c5-efa2-4c46-857c-35b651af844a.png">

For the Discussion Listing + Overview Page Thread Preview Rows

### Design specifications
```
Background color: G/600 or #78A824
Font color: White or #FFFFFF
Font: Caption / Medium
Padding: 8px left & right, 4px top & bottom
Height: 24px
Copy: defined by default stages or by custom stages  
```
### Behavior
```
Appears under thread card description and above thread card actions, as seen in the design.
A stage tag should appear before any tags representing any linked proposals or referendums, as seen in the design.
Character limit: 20 Characters and then three dots symbol appears ... (ellipsis character)
```

> Should default stage tag be visible in threads list? In View thread page we have logic like this so in thread page view default stage is not visible.

No, the default stage (Discussion) should not be shown.

> If community has custom stages, what should be default stage assigned to the thread during creation? Right now there is a logic that takes first stage from the list if there are custom stages defined. Otherwise it takes discussion stage. Is this logic correct?

This is correct.


### Images from Figma to exemplify how
 
<img width="737" alt="Screen Shot 2023-05-08 at 7 41 09 PM" src="https://user-images.githubusercontent.com/16248081/236959751-788bd8ea-a6c4-4a22-b629-8e6af9d692e2.png">
<img width="622" alt="Screen Shot 2023-05-08 at 7 41 23 PM" src="https://user-images.githubusercontent.com/16248081/236959765-8739cecd-62a9-4f99-95a0-bba56f1fa553.png">
