### ISSUE TITLE
Convert TBC cache from in-memory to redis

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3732]
## Description
The Token Balance Cache, as its name implies, is a cache for user token balances. Currently it relies on a POJO (plain old javascript object) cache, which we would like to make persistent + accessible across instances of the webapp by moving to redis.

## Acceptance Criteria
- The TBC relies on redis rather than a POJO cache.
- The TBC's TTL/caching logic remains the same (no caching for insufficient balance, long TTL for sufficient balance)

**Comment by NakulManchanda** [comment]
From @jnaviask on slack:
```
we already have an in-memory cache defined in the token-balance-cache package, take look at how it works
the /tokenBalance route eventually queries it, as do the various /createThread /createComment /createReaction if a token threshold is set
this is not an instance of route caching or database query caching, but function caching may work
```

**Comment by NakulManchanda** [comment]
@jnaviask 
can we re-assign to somebody who is more familiar with TBC part of app?
I added this to my backlog, if we think its good win, please re-assign.
Also, I believe TBC familiar  assignee - can extract more out different caching type - function, routes.
Always, there to help!

**Comment by ianrowan** [comment]
Do we know how much delta in speed redis vs in-memory cache for TBC will provide on second request? First request is slow but second requests with current caching strategy are generally fast

**Comment by NakulManchanda** [comment]
TBC doe it go to external endpoint - http request? 
- less than 100ms if we have right caching approach, as we will be reading from cache!

Main question is do you see a path where this value which seems dynamic by name, can be cached properly?

**Comment by ianrowan** [comment]
Main point here is that this is an example of 1st call(takes 9.5s)


![Image](https://github.com/hicommonwealth/commonwealth/assets/36428666/f415e90e-776f-40fb-98c5-35a5cd76e170)

But with current in-memory caching approach, subsequent calls are extremely fast(~60ms)


![Image](https://github.com/hicommonwealth/commonwealth/assets/36428666/11f016fa-45a1-4a2a-9450-7127214583bc)

Is it worth converting this to redis as it wont speed up first calls?

**Comment by NakulManchanda** [comment]
ohh, yeah if its already cached - we have multiple servers
-  caching in redis will help all servers read from same cache - yeah i guess thats what ticket intend to do change caching location

If it get prioritized, i am happy to help with conversion! seems like its already on cache though!

**Comment by timolegros** [comment]
Fixed with TBC v2
