### ISSUE TITLE
Update Proposal Status modal does not support default stages in dropdown

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3753]
## Description
For communities without custom stages, the Update Proposal Status modal does not display the default stages, per the `ThreadStage` enum. Instead, it displays nothing:
![image](https://user-images.githubusercontent.com/1860629/236915000-d6c275a2-f1c4-4bbd-9b59-1d342b53221f.png)

## Acceptance Criteria
- Stage dropdown in Update Proposal Status modal should display the default `ThreadStage`s on communities without custom stages.

**Comment by ianrowan** [comment]
Is this a cosmos specific bug(ie related to recent linking changes) or existing issue? just context for looking for regression/breaking changes
CC: @jnaviask

**Comment by jnaviask** [comment]
Not cosmos-specific -- the stages bug in this ticket is for any community _without_ custom stages.

**Comment by ianrowan** [comment]
Issue here seems to not be the modal logic but how communities are initialized in the DB. 
For example Stargate has `Chains.custom_stages = true`


![Image](https://user-images.githubusercontent.com/36428666/236926445-f069838c-d98f-4c8b-bfcf-ad511fc5c97a.png)

But that column is supposed to be the stages themselves for custom stage communities


![Image](https://user-images.githubusercontent.com/36428666/236926590-47dbfc12-9a26-41d8-a950-5f65f4631474.png)

 So I think communities are being initialized with a bool = true when they are non-custom stage communities and this is breaking the simple modal logic that simply checks if theres anything in the custom_stage column, which is pretty much alwys true. When it tries to parse a value like 'true' theres obviously no stages there

For now I propose and will fix our logic in the modal to fallback further on this data issue, but I assume as a separate ticket we should investigate why the column is working like this

CC: @jnaviask
