### ISSUE TITLE
Remove/deprecate old linking tables/columns

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3761]
As soon as we're fully comfortable with the changes and migration regarding linking we should remove old db columns and tables including:
 
- ChainEntityMeta.thread_id column
- LinkedThreads Table
- Threads.snapshotProposal column 

Following this we will need to fix the models in the app as well

**Comment by jnaviask** [comment]
Feel free to knock this out, although note that we may still have lingering uses of each of these tables/columns throughout the codebase that we will need to clean up.
