### ISSUE TITLE
Convert ChainCategories and ChainCategoryTypes into a single column on Chain

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3765]
## Description
- ChainCategoryTypes is a table with 2 strings in it: "DeFi" and "DAO".
- ChainCategories is a table that maps some Chains to one or both of those strings, via a numeric id into the "ChainCategoryTypes" table.

We don't need two tables for this -- we can simply store an array of strings as a column on the Chain model, called `categories`. Most cases null, but we can migrate the strings from ChainCategories as needed. Then, we can drop these two basically unneeded tables.

Communities page and ManageCommunities helper file will need to be updated to ensure they get the correct data.

## Acceptance Criteria
- The ChainCategories and ChainCategoryTypes tables are no longer used.
- No app functionality changes or breaks.

**Comment by alexyoung23j** [comment]
Makes sense, switching the logic on the communities page shouldn't be much of a lift.

**Comment by ianrowan** [comment]
@jnaviask Have a migration written to move data from both of these tables to a new 'category' column. Result looks like this


![Image](https://github.com/hicommonwealth/commonwealth/assets/36428666/57e21630-3e62-4e81-8afd-0e81896724e4)

Semantically and technically is this what we want to do here?

**Comment by jnaviask** [comment]
Yep! Looks great to me. @ianrowan
