### ISSUE TITLE
Fix storybook "Buffer not defined" errors

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3769]
## Description
In order to publish on chromatic, we need all of our storybook components to load properly. Some of them do not load, because they import files that end up importing the ethers library, which breaks the storybook display.

We need to ensure that our components do not require dependencies outside of the various styles/UI tools they need. In particular, one issue may be importing from `models/index.ts` rather than the specific model file needed. Alternatively, relying on the global `app` object from `state.ts` may also cause bad imports.

## Acceptance Criteria
- All storybook components should load in the storybook UI, so that we can publish to chromatic.
- No changes or regression to app functionality.

**Comment by zakhap** [comment]
I would like to suggest we comment out the problem Components to get Chromatic all connected up asap.
