### ISSUE TITLE
Fix chain/community model/DB semantics - Child of #2535

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#3779]
## Description
The main goal of this task is to rename the `Chains` table to `Communities` and change column names of all foreign keys to `community_id` in the database. This will cover the bulk of the semantic changes in the database. 

- `Chains` table update: #5246
- Foreign key updates: https://github.com/hicommonwealth/commonwealth/issues/3779#issuecomment-1766622292

**Comment by timolegros** [comment]
Converted this ticket to a bucket ticket because it encompasses all tickets that deal with updating the database schema and Sequelize models.

**Comment by timolegros** [comment]
The updated list of columns that need to be updated (original https://github.com/hicommonwealth/commonwealth/issues/2535#issuecomment-1538884201).

- [ ] `Addresses.chain`
- [ ] `Bans.chain_id`
- [ ] `Comments.chain`
- [ ] `CommunityBanners.chain_id`
- [ ] `CommunityContracts.chain_id`
- [ ] `CommunitySnapshotSpaces.chain_id`
- [ ] `DiscordBotConfig.chain_id`
- [ ] `Groups.chain_id`
- [ ] `Notifications.chain_id`
- [ ] `OldChatMessages.chain`
- [ ] `Polls.chain_id`
- [ ] `Reactions.chain`
- [ ] `StarredCommunities.chain`
- [ ] `Subscriptions.chain_id`
- [ ] `Threads.chain`
- [ ] `Tokens.chain_id`
- [ ] `Topics.chain_id`
- [ ] `Topics.default_offchain_template`
- [ ] `Users.selected_chain_id`
- [ ] `Votes.author_chain`
- [ ] `Votes.chain_id`
- [ ] `Webhooks.chain_id`

This list was extracted from the result of this query:
```
SELECT
    table_name,
    column_name
FROM
    information_schema.columns
WHERE
    (column_name LIKE '%chain%' OR table_name LIKE '%chain%')
  AND table_schema = 'public';
```

**Comment by timolegros** [comment]
Points were not updated since this ticket was repurposed.
