### ISSUE TITLE
Convert EVM websocket endpoints to https

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3811]
## Description
Currently we depend on websockets for all of our EVM endpoints. This is not necessary, as most of our queries are "one and done", meaning we make a query and immediately disconnect. Also, not all EVM chains have public websocket endpoints available. We should rework the EVM-based code to rely on HTTP endpoints when possible, as this will improve efficiency (faster to fire off an HTTP request vs establish a websocket connection) and will make it easier to debug + maintain stable support for the various EVM chains we support.

Technically speaking, we will need to review the ChainNodes table, and audit how/where the url/alt_wallet_url/private_url fields are used, and then ensure that the main url is HTTP when possible. We will also need to correct uses of the URL so that it relies on HTTP endpoints rather than websockets.

## Acceptance Criteria
- EVM chains rely on HTTP endpoints rather than WS endpoints.

**Comment by jnaviask** [comment]
Feel free to do discovery here + come up with a proposed plan @ianrowan

**Comment by ianrowan** [comment]
Code across the app has been modified to mainly use HTTP with the ability to fallback to wss for existing wss endpoint or those provided by new communities. The following are ETH based chains 


![Image](https://github.com/hicommonwealth/commonwealth/assets/36428666/9407dc13-6f99-478a-a47b-fd5d71bbbf78)

Currently for testing I'm migrating our alchemy record to https. I wanted to get some thoughts on which/how we should go about migrating(if we want to in general in this PR) some of these lesser used endpoints. From running some queries it looks like almost every EVM community is on the alchemy eth endpoint with the exception of communities like hmny or cleo which are more uncertain as to if they support https

So main question is which endpoints do we want to update in a migration here beyond alchemy eth? 

@jnaviask

**Comment by ianrowan** [comment]
@jnaviask Upon more research it looks like we can migrate all of our evm endpoints. I just didnt want it to be a shot in the dark guessing that the a wss endpoint also served an https endpoint and as seen here we can typically use the alt_wallet_url but changes beyond just the protocol prefix are required(ie cleo needs the `/ws` route removed as well) 
<img width="1331" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/926e2b96-6338-49fc-81cb-9411f78d56c1">
These are all eth rpcs used by CE

**Comment by ianrowan** [comment]
Migration to convert these here https://github.com/hicommonwealth/commonwealth/blob/cbc3950c3976372065290b22ebdeac59d974b512/packages/commonwealth/server/migrations/20230524184241-convert-wss-rpc-endpoints.js

**Comment by jnaviask** [comment]
We should make sure we DO update the private_urls that we can't reveal from wss to https, if possible.

**Comment by ianrowan** [comment]
> We should make sure we DO update the private_urls that we can't reveal from wss to https, if possible.
> 
> & basically the list of nodes needing updates can be queried via `SELECT * FROM "ChainNodes" WHERE balance_type = 'ethereum';`.

@jnaviask got it will add any i missed. In this list so far there arent any with a private URL other than alchemy eth

**Comment by ianrowan** [comment]
Included in PR #3999
