### ISSUE TITLE
Sort + Filter Threads

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3821]
## Description WIP

There are a couple goals for this ticket: 
- Update UI + UX around sorting+filtering threads from the Thread Listing Page
  - Implement a new design+UX for Dropdown Menu
- Increase performance of the discussion listing page
  - Make API better

## Resources

PRD: https://www.notion.so/buildcommon/Sort-Threads-cd0eaca2b83249ada7f2e20817ff5632
FIGMA: https://www.figma.com/file/NGcMaoQ1xYgx1YuL8kaHou/Forum-Improvements---Part-1?type=design&node-id=665-35793&t=2ztNQQdWzqgLGDjH-0

## New Dropdown Menu Component
<img width="755" alt="Screen Shot 2023-05-14 at 8 27 04 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/6c932634-90af-4215-8ca1-463c01e1c474">
<img width="989" alt="Screen Shot 2023-05-14 at 8 27 16 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/d5cee620-42ec-4cf6-86c2-723026f22d3f">

**Specifications**
Icons Used:
- From: Phosphor icons
- Size: 16px by 16px
- Icon weight: regular
- Icons to use: Sparkle, Clockcounterclockwise, Heart, Chatdots, Carotup, Carotdown
- Link: [Phosphor figma](https://www.figma.com/file/lM2jxdx07aLNW7VTT22kdK/Phosphor-Icons-(Open-Source)?type=design&node-id=5941%3A7543&t=ei9TZIo7qa8rTiZf-1&fuid=954036909472314356)
<img width="253" alt="Screen Shot 2023-05-15 at 10 53 03 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/45efe69b-5233-4040-8ed2-72e30931ec61">

**Component**
*Width is always rounded to the next multiple of 8

**Dropdown button**
- Default width: 144px
- Max width: 264px  
- Max character count: 24 characters + ‘...’
**Dropdown list items**
- Default width: 224px
- Max width: 320px  
- Max character count: 34 characters + ‘...’

## Sorting
**Use the new dropdown component to create Sort and filter**

**Sort & Filter**
- [Sort & Filter copy: Body 02/Medium
](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=31-178&t=gViuPSAgxgsaaaBG-0)
- Spacing between sort & filter copy and the dropdown component is 16px

### Sort categories:
**Latest**
- Current Default Behavior: Ordered by recent activity, most recent thread or comment.

**Newest**
- Ordered by newest thread to oldest. 

**Oldest**
- Ordered by oldest to newest threads. 

**Likes**
- Ordered by most liked to least liked threads.
- If threads have the same number of likes, order from newest to oldest.

**Comments**
- Ordered by most commented to least commented thread.
- If threads have the same number of comments, order from newest to oldest. See Likes sort for example.  

### Sort + Filter in Context
Behavior notes: 
- When Sort and Filter are inline the spacing between the Sort & Filter copy and the dropdown button is 16px. 
- Whenever Sort and Filter stack on smaller pages, ensure that Sort and Filter have the same container size of 34px so that the dropdown buttons are  vertically aligned as seen in the designs. 
- When page hits under 906px Sort and Filter stacks.
- When page hits under 600px Sort and Filter stacks. Filter wraps. 
<img width="956" alt="Screen Shot 2023-05-15 at 10 53 37 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/fa6cf74b-0699-473b-8337-846a1af56885">
<img width="780" alt="Screen Shot 2023-05-15 at 10 53 46 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/6915b904-1cff-4183-8fc0-663b593d84fe">

## Acceptance Criteria
- All details from design documentation are implemented
- Passes design QA

**Comment by jnaviask** [comment]
Eng hint: we will have to update how thread fetching works on the API side, to ensure selected ordering is fetched.

**Comment by mzparacha** [comment]
Requested access for https://www.figma.com/file/NGcMaoQ1xYgx1YuL8kaHou/Forum-Improvements---Part-1?type=design&node-id=665-35793&t=2ztNQQdWzqgLGDjH-0

**Comment by mzparacha** [comment]
At 921px, should we wrap it to next line?
<img width="921" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/9c57a66a-c203-49c2-8339-52e0d7f47c65">
