### ISSUE TITLE
Magic Login Support for Cosmos

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3824]
## Description

Magic Link is a solution for allowing users to log in via email. The external provider generates addresses for the user on interaction via the login modal, which we then query on our backend to verify the user and log them in.

Useful context:
- server/passport/magic.ts contains the server-side logic for magic login.
- MAGIC_SUPPORTED_BASES will need to be extended to CosmosSDK.
- We will need to add the extension here: https://magic.link/docs/auth/blockchains/cosmos to the client.
- Client side Magic initialization happens in controllers/app/login.ts.

On the server side, we will receive both an ethereum address and a cosmos address. We will need to create Address rows (and Subscription rows, and maybe SSO Token rows, TBD) for each of these, if logging in on a Cosmos community. So, a new Magic user will receive two already-generated addresses rather than one, an address on Ethereum chain base and an address on CosmosSDK chain base.

We may also need to re-encode the Cosmos address to the bech32 format used on the selected chain (i.e. go from cosmosxxxxxx to osmoxxxxx). Magic provides a helper for reencoding: `magic.cosmos.changeAddress` -- however, we also have our own logic for this task, which may need to be extracted from `createAddressHelper` into its own utility file.

## Acceptance Criteria
- Cosmos users should be able to successfully login with Magic.

**Comment by jnaviask** [comment]
Want to note as a follow-up that we don't necessarily need to provide a valid RPC URL to Magic in order to generate an address -- only if we want to send transactions via Magic Link's proxy, which is explicitly OUT OF SCOPE for this ticket.

**Comment by mhagel** [comment]
> we don't necessarily need to provide a valid RPC URL

I went ahead and used the registration chain's RPC, since it was easy to do.
