### ISSUE TITLE
Document existing thread loading flow + logic

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3828]
## Description
Produce a document similar to [Initialization Flow Wiki](https://github.com/hicommonwealth/commonwealth/wiki/initialization-flow), explaining how threads get loaded: which API calls are made when, which stores back which functionality.

The goal would be to use this document to help rethink our thread loading approach / API more broadly.

## Acceptance Criteria
- A document that describes the thread loading flow in a step-by-step way.

**Comment by mzparacha** [comment]
Added a doc here [commonwealth/wiki/Thread-loading-flow](https://github.com/hicommonwealth/commonwealth/wiki/Thread-loading-flow)
