### ISSUE TITLE
Fix Subscription Tests

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3831]
## Description
Subscription tests have been skipped (`describe.skip`) since 2022-06-26 so many are out of date and no longer pass. These tests should be updated to reflect the current state of the API and DB schema. Once the tests are updated the tests should be re-enabled by removing `.skip`.

## Acceptance Criteria
- Passing subscription tests
- Subscription tests running in CI

**Comment by timolegros** [comment]
@jnaviask @MuonShot Should this be done immediately or following the upcoming MVP?

**Comment by jnaviask** [comment]
We'll review during sprint planning tomorrow. Thanks for creating this.

**Comment by timolegros** [comment]
Fixed in #4366.
