### ISSUE TITLE
Prettier not included in CI

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3832]
## Description
There are currently 69 unformatted files on master right now.

## Acceptance Criteria
- All files on master properly formatted.
- Prettier running on merge or in CI.

**Comment by jnaviask** [comment]
This is related to #3762, where it was suggested we use a precommit hook to run prettier rather than an on-merge hook. The on-merge hook integration failed because it would require pushing a separate commit to master, which is a protected branch.

**Comment by timolegros** [comment]
> This is related to #3762, where it was suggested we use a precommit hook to run prettier rather than an on-merge hook. The on-merge hook integration failed because it would require pushing a separate commit to master, which is a protected branch.

Even if it were possible to push the formatting directly to master that is not a good idea because while rare prettier can introduce bugs related to JS ASI or template literals. Pre-commit sounds like a great idea since CI will run after the formatting and catch any errors prettier introduced.
