### ISSUE TITLE
Enhance User component to support anonymous rendering of wrong-base addresses.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3840]
## Description
For original bug, see: https://commonwealth.im/webb/discussion/1567-docs-are-live

When reproduced locally:

![2023-05-12-124342_692x353_scrot](https://github.com/hicommonwealth/commonwealth/assets/1860629/f1fc256c-caa9-4297-a8ff-21dfea53c026)

Looks like cause is because the style prop on the Jdenticon is this string: 
```style: `width: ${avatarSize}px; height: ${avatarSize}px;`,```
rather than a proper map.

Not surfaced in most communities because AnonymousUser is only rendered in `CommentAuthor.tsx` and `user_gallery.tsx` when a cross-base address is present, which should not happen.

Note that thread authors do not load either, which points to an incomplete usage of AnonymousUser in general: 
![2023-05-12-131314_213x177_scrot](https://github.com/hicommonwealth/commonwealth/assets/1860629/bc44e442-5a52-4b99-8013-93e65a83cdb0)

Since we don't know the full scope of impact, so we should remove the AnonymousUser component entirely, and ensure that User can render "invalid" addresses as Anonymous sans tooltip.

## Acceptance Criteria
- Remove AnonymousUser component.
- Ensure the User component can render "invalid" (off-chain-base) addresses (that cause decoding errors).

**Comment by alexyoung23j** [comment]
@jnaviask I haven't actually seen how this _should_ display in the UI- if its an "anonymous address", the User component ought to display "Anonymous" and then not let you click on the user to get taken to their profile?

**Comment by jnaviask** [comment]
This is correct behavior @alexyoung23j .
