### ISSUE TITLE
Cache Function Wrapper and Background Task Runner

### ISSUE THREAD

**Issue by NakulManchanda** [hicommonwealth/commonwealth#3866]
## Description
- eg. sample `fn` function on backend

Wrap Function will cache values from `fn`
```
wrapFn = cacheWrap(false, fn, cacheKey, cacheDuration)
```

Daemon will run in background to prefetch/refresh cache value in background by running `fn` on schedule overriding/refreshing current cache values
```
wrapOverrideFn = cacheWrapOverride( fn, cacheKey, cacheDuration)
daemon.startTask(wrapOverrideFn, 60*5) //every 5minutes
```

`Daemon` is same as `cacheJobRunner`
- `cacheJobRunner` for in-memory cache
- `Daemon` to work with Redis cache

## Example of Usage
We can cache results of bulk queries, reducing load on DB
Replaced `getChainStatus` with `getChainActivity.queryWithCache`

**Sample Existing Function**
```
getChainStatus(model) {
 models.Chain.findAll()
 models.ChainNode.findAll(),
models.NotificationCategory.findAll(),
models.CommunitySnapshotSpaces.findAll()
}
```

**How to cache & run background task to refresh?**

**CacheWrapper Object**
```
const getChainActivity = new Activity(
  'getChainStatus',
  getChainStatus,
  'getChainStatus',
  60*5, // 5 minutes
  RedisNamespaces.Global_Response
);
```

**drop in-place replacement**
```
// replace wrapped function
const {
      chains,
      nodes,
      notificationCategories,
      chainCategories,
      chainsWithSnapshots
    } = await getChainActivity.queryWithCache(models);
```

**how to run in background**
```
// run background task eery 5mins
getChainActivity.startTask(models);
```

## Acceptance Criteria
- Replace all instances of `fn` with `wrapFn` to verify if cached resposne exists or not automatically
- Daemon - to help refresh cache value on set interval

**Comment by jnaviask** [comment]
@NakulManchanda Teed this up for you, but please add a point estimation! Thanks

**Comment by NakulManchanda** [comment]
Hi @jnaviask , it took me few days to crack this interface alongwith testing
- work is complete, added point estimation retrospectively.
- PR is ready for review
