### ISSUE TITLE
Poll tag not being removed if poll is deleted

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3878]
## Description
BD reported. Creating and then removing a poll does not remove the poll tag on a thread.

## Acceptance Criteria
- Deleting a poll should remove the poll tag from a thread.

**Comment by alexyoung23j** [comment]
So I cannot reproduce this but I found a bug with poll deletion that was fixed instead.

**Comment by alexyoung23j** [comment]
BD reported that this is NOT fixed despite being merged on 5/30. Reopening.

**Comment by jnaviask** [comment]
Yes -- we should do a migration to rectify the database state in accordance with our contract (= has_poll means it has a poll).
