### ISSUE TITLE
Wiki page: how to Storybook

### ISSUE THREAD

**Issue by martins87** [hicommonwealth/commonwealth#3895]
[Storybook wiki page](https://github.com/hicommonwealth/commonwealth/wiki/Storybook:-Introduction)

**Comment by martins87** [comment]
WIP:

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/6bb3d968-433c-4ddb-b4a4-67a0e48746df)

**Comment by jnaviask** [comment]
@martins87 can you implement the following changes
- Add "Storybook: " prefix to every page in the list.
- Add a table of contents in the introduction, to make it easy to see the entire list.

**Comment by martins87** [comment]
> @martins87 can you implement the following changes
> 
> * Add "Storybook: " prefix to every page in the list.
> * Add a table of contents in the introduction, to make it easy to see the entire list.

Will do.
