### ISSUE TITLE
Logging in with a totally new profile with metamask has incorrect flow

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3913]
## Description
When using a totally new account, signing the message and hitting "New Account" lands the user in this situation, rather than the edit profile stage of the modal:
![image](https://github.com/hicommonwealth/commonwealth/assets/1860629/96f19475-e379-4597-a4ba-e55e0cd506b4)

## Acceptance Criteria
- Logging in with a totally new address should take the user through the proper login flow.

**Comment by mzparacha** [comment]
https://github.com/hicommonwealth/commonwealth/assets/51641047/3ea3eda1-a71d-4948-a06c-1b4bc66242c9

@jnaviask I can't seem to repro on main latest commit 9033e1e444418d82487e7e4998008332231ae99e.

**Comment by mzparacha** [comment]
Nvm, reproduced in communities
