### ISSUE TITLE
Keplr requiring two login attempts + not updating profile properly

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3919]
## Description
Two bugs in following video: https://www.loom.com/share/8d541669f5e045cbbf6eca69b7adbf96

1. First login attempt fails.
2. Second login attempt succeeds, but profile is null until page refresh.

## Acceptance Criteria
- Keplr login should work successfully the first time, with a valid profile initialized.

**Comment by ianrowan** [comment]
Note this is more than just injective login. Logging in first time on landing page of live site with osmosis keplr yields
<img width="338" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/0a43a62c-c48e-4c18-a697-b2a96cc9cdec">

**Comment by jnaviask** [comment]
This is likely same issue as #3657, but will supersede it for now.
