### ISSUE TITLE
Comments are not refreshed properly when moving between pages

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#392]
To replicate: Create a thread with a few comments, then create a new post using the modal

**Comment by raykyri** [comment]
This appears to still be happening: Go to a thread with one comment, then use notifications to navigate to a thread without any, and then use the back button to navigate back, and there will be no comments shown

**Comment by gdjohnson** [comment]
Closing in light of PR #823 being merged.
