### ISSUE TITLE
Investigate magic login infinite hang when logging in with existing email

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3920]
## Description
BD reported: https://www.loom.com/share/9da3b90f4b4c454195934883bbbbc318

To reproduce: create a magic email against just ethereum, e.g. by logging in from homepage. Then, log out, and use magic to log in on a Cosmos community. The bobber should hang.

## Acceptance Criteria
- Track down root cause of magic login issue above + propose and potentially implement fix if easy.

**Comment by mhagel** [comment]
I was able to reproduce this 1 out of 4 tries in BETA.
I have not reproduced it in PROD in 4 tries.
No repro locally either.

I am on potentially slow wifi ATM, so maybe it has something to do with a timeout. 

@jnaviask

**Comment by mhagel** [comment]
>However I did find a bug when trying to join another Cosmos community while logged in with Magic. Join fails, and this error in console:

This is unrelated to magic, so I made a new bug: https://github.com/hicommonwealth/commonwealth/issues/3930

@jnaviask

**Comment by jnaviask** [comment]
@mhagel good catch. Definitely a separate bug. IME this issue is not a timeout; I was able to reproduce it at home on regular wifi.

One possible option to try is: reverting your magic changes locally, creating an account on ETH, logging out, then undoing the revert and trying to log in with it on a Cosmos community.

**Comment by mhagel** [comment]
> One possible option to try is: reverting your magic changes locally, creating an account on ETH, logging out, then undoing the revert and trying to log in with it on a Cosmos community.

Good idea. Tried this once so far. No problems. But I will try a couple more times. Maybe with a fresh db.

**Comment by jnaviask** [comment]
Closing as cannot reproduce. Will reopen if bug resurfaces.
