### ISSUE TITLE
Design System Foundations in Storybook

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3921]
## Description

- [x] [Icons](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=243-29&t=iLSnU3mo66AJEE7w-0)
  - Requirements: Enable usage of **ALL** Phosphor Icons. Please iterate and display _all_ phosphor icons, and be able to set the size & weight in the Story Options: "thin", "regular", and "fill". The phosphor components should already be in available via a package. This is simply to display them all. 
  -  Design Specifications: 3 sizes, (16px, 20px, 24px) sizes. Icons on Common should not be bigger or smaller than that.
- [x]  [Colors](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=46-599&t=Zt1yjtOIzRQo0gYZ-0)
  - Should be added as **new** SCSS Variables to our colors.scss file in the format `$blue-50, $rorange-700` so they can be referenced by name.
  - Needs to be viewable somehow in storybook.
 
<img width="1015" alt="Screen Shot 2023-05-18 at 10 22 43 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/56832168-77cf-4f18-9e68-bf9d489efbc2">

- [x] [Typography](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=2-52&t=OTuQvq0GRpLakafc-0)
  - This should be the CWText Component but with additional styling options added to the typography.scss file
  - Typography details should be clearly laid out in the typography figma link provide (too much to copy paste here)
- [x] [Elevation](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?node-id=2%3A58&t=FwwnccJmCd1diIw8-1)
  - Simply update the elevation scss, to reflect the new styles. This can immediately trickle through the app wherever we use elevation.
  - In the presentation Story, use a Card Component with different elevation Options.

<img width="737" alt="Screen Shot 2023-05-18 at 10 28 47 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/faee5c85-081f-4ef2-af2b-500fcff8a529">

- [x] [Borders](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=2-56&t=9mZXVRuejoQLYUWF-0)
  - Should be added to scss as variables to be used. Should display in Storybook with a Card component.
  - Spec: Borders have a stroke of Neutrals/200 (see colors) and a border radius of 6px. 
<img width="601" alt="Screen Shot 2023-05-18 at 10 28 41 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/cda0f9e3-36c0-43ca-99a7-aab1c4ab7812">

- [x] [Dividers](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=49-21&t=uQfqMLO3fnNvl7g1-0) 
  - Spec: Dividers have the color Neutrals/100, with 1 or 2px options.
  - Story: Should probably be displayed via the <br> element(?), but any presentation of a divider is acceptable.
<img width="627" alt="Screen Shot 2023-05-18 at 10 28 23 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/d0fc4a1e-f6f5-48e3-9437-6a3e1e2f5bf9">

## Acceptance Criteria
- All Foundations are added to Storybook as Stories under the Sidebar Header "Foundations". They need to be auditable just like any other component even though they are _foundation elements_ to the component kit.

**Comment by zakhap** [comment]
@MuonShot Need your input on how best to detail this ticket for dispatching. Hopefully prior to Refinement. WIll probably schedule 15m to do so synchronously.

**Comment by jnaviask** [comment]
@martins87 Try playing around on localhost:8080 -- see if you can manually locate the correct URL of the font (404 means not found) -- maybe it needs to be /styles/font.woff, for example. Then update the links in the preview-head file.

**Comment by martins87** [comment]
> @martins87 Try playing around on localhost:8080 -- see if you can manually locate the correct URL of the font (404 means not found) -- maybe it needs to be /styles/font.woff, for example. Then update the links in the preview-head file.

On localhost build creates this path:

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/24e9c754-4f45-45ad-94f9-b307f8979789)

I'll dig deeper into it tomorrow.

**Comment by jnaviask** [comment]
Take a look at this page: https://storybook.js.org/docs/react/configure/images-and-assets

May need to configure staticDirs.

**Comment by martins87** [comment]
> Take a look at this page: https://storybook.js.org/docs/react/configure/images-and-assets
> 
> May need to configure staticDirs.

Perfect, I'll make it work. Thanks!

**Comment by martins87** [comment]
> Take a look at this page: https://storybook.js.org/docs/react/configure/images-and-assets
> 
> May need to configure staticDirs.

:+1:

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/f794d278-5a3c-4fe4-b7e8-8d3e9a4ce3fd)
