### ISSUE TITLE
Moderation: Phase 1 (Moderator Only, Inline Spam)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3923]
## Description
**Goal: Allow admins/mods to mark content as spam so they can begin to clean up their forum, while still allowing community members to find and access content marked as spam for transparency purposes.**

### Affected Pages:
- Discussion Listing Page
- View Thread Page

### User Stories

Flag Functionality:
- As a moderator, I want to mark a thread or comment as spam inline to the thread or comment.
- As a moderator, I want to unmark a thread or comment as spam inline to that thread or comment.

Spam Suppression:
- As a moderator or community member, I [may] want my forum to hide spam posts by default
  - As a community member, I want to be able to view all threads marked as spam.
  - Maybe: As a community member, I want to interact with spam threads.
- As a community member, I do not want to see spam comments by default.
- As a community member, I want to view spam comments optionally.

### Design notes 
- Threads that have flagged should have a Spam flag at the top
- The three dot drop down moves from top of the thread to the bottom, near the like and comment buttons
- The subscribe button moves from the top of the thread to the bottom next to the comment icon

### Acceptance Criteria
- Community admin sees the option to "Flag Spam" when they click on the three-dot dropdown
- Click on "Flag Spam" brings up the confirmation pop up 
- On clicking "confirm" the post disappears from the thread 
- When the user (admin or normal user) checks "include threads and comments marked as spam" , the threads and comments marked as spam by the user should become visible with the "Spam" tag. 

### Figma designs and prototypes:
Flagging/unflagging posts as spam
:tv: [Loom walkthrough](https://www.loom.com/share/0991cf31a9474b348e05b0d8cbaee09c)
:arrow_forward: [Prototype](https://www.figma.com/proto/30dpVGV7zndfhS5V0jzf4W/Moderation?page-id=16%3A30537&type=design&node-id=16-47788&viewport=1427%2C354%2C0.09&scaling=min-zoom&starting-point-node-id=16%3A47788)
:art: [Figma file](https://www.figma.com/file/30dpVGV7zndfhS5V0jzf4W/Moderation?type=design&node-id=16%3A47788&t=0zZfWDNpLZesquzR-1)

**Comment by jnaviask** [comment]
Jake TODO: subticket FE/BE changes

**Comment by meeshlin** [comment]
This is the overall Moderation task, which includes the inline actions (https://github.com/hicommonwealth/commonwealth/issues/3977) but also requires a second ticket for the thread post page (with flagged spam—limited functionality).
