### ISSUE TITLE
Design System: (Forms) Text Input

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3935]
## Description

A text field is an input that allows a user to write or edit text.

We have two different sizes for text inputs, `isCompact` = `Yes` (`32px` height) and `isCompact` = `No` (`40px` height). The default width is `200px`. 

For each size, there are text inputs that (1) don't contain any visual elements such as icons, (2), contain a visual element before the text, (3) contain a visual element at the far right side of the field, and (4) contain a visual element before the text as well as at the end of the field. 

Text inputs can contain placeholder text, or they can also not contain any—it depends on the context. 

Text inputs have numerous states:
- `Default`
- `Disabled`
- `Hover`
- `Focus`
- `Typing`
- `Filled`
- `Invalid`

**Resources:**
- [Video walkthrough](https://www.loom.com/share/09319f3430544d7d8bab1a99fc4f59f6)
- [Figma designs](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=339%3A4862&t=hitJ0sAOSoNBXjbx-1)

<img width="1206" alt="Screenshot 2023-05-19 at 2 01 09 AM" src="https://github.com/hicommonwealth/commonwealth/assets/18157060/a52a2001-35fe-428c-82f2-3d54817d2259">

## Acceptance Criteria
- Text Input form field component should reflect all the behavior and the 7 states (disabled, focus, active, error, etc...) detailed in the figma.

**Comment by CowMuon** [comment]
Not seeing any follow up here @martins87 @zakhap - what's the current/correct status here?

**Comment by martins87** [comment]
> Not seeing any follow up here @martins87 @zakhap - what's the current/correct status here?

I'm addressing atm Marcin's comments on the PR
