### ISSUE TITLE
Design System: Radio Buttons

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3938]
## Description

A radio input allows users to select only one option from a number of choices. Radio is generally displayed in a radio group.

**Checked:** Yes, No
**States:** Default, Hover, Disabled

**Colors:**
- If `Checked` = `No` and `State` = `Default` , color is `Neutrals/400`
- If `Checked` = `No` and `State` = `Hover` , color is `Primary Blue/600`
- If `Checked` = `Yes` and `State` = `Default` , color is `Primary Blue/500`
- If `Checked` = `Yes` and `State` = `Hover` , color is `Primary Blue/600`
- If `State` = `Disabled`, the color of the component will be `Neutrals/200` and the background `Neutrals/100`

**Resources:**
- [Video walkthrough](https://www.loom.com/share/a8d97494cddb46189fe367e0910d68c3)
- [Figma designs](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=336%3A10123&t=hitJ0sAOSoNBXjbx-1)

<img width="189" alt="Screen Shot 2023-05-18 at 10 57 02 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/3ca8e253-42a9-4016-a17e-1ce3b1c38a68">

## Acceptance Criteria
- Component needs to be audited in Storybook with Story options for viewing each state.

**Comment by martins87** [comment]
Cc @jnaviask @CowMuon @zakhap 

This is a simple component but it is not on Mui Base at the moment (WIP on [Unstyled components progress #27170](https://github.com/mui/material-ui/issues/27170))

Current Mui Base unstyled components:

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/36a7d43a-52d1-49e2-9d4e-655157a0abf4)
![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/386d867b-484e-47d1-9978-8f144e867db1)

Regarding this component (and more until [#27170](https://github.com/mui/material-ui/issues/27170) is finished and ready to be used), what approach should we take?

Use Material UI and [customize the components](https://mui.com/material-ui/customization/how-to-customize/) (heavier)? Build and customize simple HTML + CSS components from scratch (lighter) ?

**Comment by CowMuon** [comment]
What's the actual ticket status here? Comment history shows a question and then no updates for a solid 2 weeks @martins87 @zakhap
