### ISSUE TITLE
Update Modal Styling

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#3941]
## Description

We have a lot of modals around the site, and with contract actions, we've updated the styling (outside of the login modal). There's no purple anymore.
- [ ] Edit Topic Modal
- [ ] Reorder Sidebar Modal
- [ ] All right sidebar within the Discussions Page (i.e. Poll Creation, Linking Threads, etc)

**Sample Before**
![image](https://github.com/hicommonwealth/commonwealth/assets/5334557/4739732f-c7c2-4549-9e54-9dc884b23501)

**Sample After**
![image](https://github.com/hicommonwealth/commonwealth/assets/5334557/f779740a-8b80-4f6e-a6ee-86416e275fd3)

## Acceptance Criteria
- The Widget page must display a TODO button.
-

**Comment by zakhap** [comment]
Action Items: 
- Decide that it is OK to move all existing modals to follow standard of second modal depicted above (new Template Modal design)
- Identify all modals that are going to be effected.
- Dispatch to Eng to apply new modal to all old modals. 

After Shipping:
- Document updates
- Re-prioritize (if needed) Modals in DS workflow to be updated top down across the newly consistent modals. 
- Design System updates for Modals get handed off in refinement => updated + audited in Storybook, then shipped
