### ISSUE TITLE
Logging in on user dashboard requires refresh to view For You feed

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3946]
## Description
Need to update state properly post-login.

## Acceptance Criteria
- User dashboard should allow you to view the For You feed immediately upon logging in.

**Comment by mzparacha** [comment]
There is also a bug when the user logs out, the for-you does not update. I think we should remove all data from the for-you field after logout and display a message to indicate a required login, something like 'Please login to view this feed'.

Thoughts @jnaviask @CowMuon?

**Comment by jnaviask** [comment]
@mzparacha ultimately this is a question for @zakhap or @meeshlin, as it's about product functionality.

I bumped this ticket to Teed Up, though, because the linked PR is currently a draft. Feel free to move it back to in progress once work resumes.

**Comment by mzparacha** [comment]
Thank you @jnaviask, i will wait for @zakhap / @meeshlin for thoughts about [this](https://github.com/hicommonwealth/commonwealth/issues/3946#issuecomment-1618732475) comment

**Comment by mzparacha** [comment]
Bump on [this](https://github.com/hicommonwealth/commonwealth/issues/3946#issuecomment-1622302747) @meeshlin / @zakhap

**Comment by zakhap** [comment]
> There is also a bug when the user logs out, the for-you does not update. I think we should remove all data from the for-you field after logout and display a message to indicate a required login, something like 'Please login to view this feed'.
> 
> When the user is logged out, they cannot navigate to the `/for-you` page, if they do they are redirected to the `/global` page
> 
> Thoughts @jnaviask @CowMuon?

1. If the user logs off, the "for you" page should refresh and remove all personal information.
2. Preferably, because the /for-you page is blocked for logged out users, we should _also_ redirect the user to /global dashboard page (current logged out behavior).

**Comment by mzparacha** [comment]
Thanks for the feedback @zakhap. Since the implementation details is the same as in https://github.com/hicommonwealth/commonwealth/pull/4395, so I have marked https://github.com/hicommonwealth/commonwealth/pull/4395 as ready for review
