### ISSUE TITLE
Sequelize: Limit Memory Usage by pulling limited column from data heavy tables

### ISSUE THREAD

**Issue by NakulManchanda** [hicommonwealth/commonwealth#3961]
**Proposed solution:**
New sequelize scope - to limit unecessary data out of text based columns eg. Comments & Threads 

If not already
exclude {version_history, text, plaintext, body, _search} etc

related comment here:
https://github.com/hicommonwealth/commonwealth/issues/3429#issuecomment-1552327071
https://github.com/hicommonwealth/commonwealth/issues/3429#issuecomment-1552358284

_Originally posted by @NakulManchanda in https://github.com/hicommonwealth/commonwealth/issues/3950#issuecomment-1553752593_

Acceptance Criteria:
- exclude unnecessary column with sequelize include
- load test with this on Frick https://commonwealth.im/stargatetoken/discussion/4353-proposal-guidelines
- when comments are primary include pagination on that page
- external/getThreads should return top 100 comments only

**Comment by timolegros** [comment]
I think we need to include pagination of comments. No need to be pulling 1.6k comments at once.

**Comment by NakulManchanda** [comment]
thanks @timolegros 
FYI @jnaviask @MuonShot

**Comment by NakulManchanda** [comment]
We do have pagination in external getThreads & getcomments
Lets do the same across app, as our users and comments are growing we cannot serve all the data at once.

We have same in external api s as well:
Referenced here:
https://github.com/hicommonwealth/commonwealth/pull/3643#issuecomment-1532019100

**Comment by jnaviask** [comment]
No problem identified -- no need to fix.
