### ISSUE TITLE
@-mentioning a user in quill shows jdenticon in tooltip instead of profile image

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3970]
## Description
Easy to reproduce: mention a user with a profile image by @ and witness the jdenticon.

## Acceptance Criteria
- Mentioning users should show their avatars.

**Comment by dillchen** [comment]
Will also note that:

- As a user, as I type in every other character flashes the mentions tooltip, which is an unexpected user experience
