### ISSUE TITLE
Integrate Inline Spam UI

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3977]
## Description

Ticket #3923 involves several UI changes, as showcased in the Figmas. These changes include a reworking of the thread preview card, to pull the actions over into a unified set of action components.

#### Requirements

1. **Combining all "destructive" actions as a dropdown under the new ellipses icon:** Add a `DotsThree (Bold)` from the Phosphor library (16 x 16px), color is `Neutrals/500`, and has 4px padding all around (left, right, top, and bottom) 
![threadPost](https://github.com/hicommonwealth/commonwealth/assets/18157060/2568aa81-8855-4231-aa0f-fc60464eccb5)

2. **Action components (bottom left of the thread post):** 
> - Each action component = [`Icon, 18 x 18px] with 4px padding and text (`Caption/Regular` and `Neutrals/500`)
> - Each icon + copy is in its own container with 8px horizontal padding and 4px vertical padding
> - Copy type is `Caption/Regular` = Neue Haas Unica, font size: 12px / 0.75rem, line-height: 18px / 1.125rem, spacing: 2%
> - Container has a radius of 6px

 **Actions:**
> - **Comment** = `[icon = ChatCenteredDots, Regular]`4px-spacing`[copy = "#comments Comments”]`
> - **Share** = `[icon = ArrowBendUpRight, Regular]`4px-spacing`[copy = “Share”]`
> - **Subscribe** = `[icon = BellSimple, Regular]`4px-spacing`[copy = “Subscribe”]`
> - **More actions/ellipses** = `[icon = DotsThree, Regular]` at 16 x 16px, with 4px padding on each side (vertically and horizontally) 

> **Default state (unselected)**
>> - Color of icon and type = `Neutrals/500` (#656167)
>> - Background color = Transparent

> **Hover state (hovering over component)**
>> - Color of icon and type = `Neutrals/600` (#514E52)
>> - Background color = `Neutrals/200` (#E0DFE1)

**Note:** If the user is hovering over the thread post listing, the whole thing will be highlighted `Neutral/100` (#F0EFF0) with a 6px radius around the full container as well

3. **Dropdown (after clicking ellipses):**
Dropdown menu container with 6px radius, 8px top and bottom. Each menu item = 20x20px icon + Action, all in a container with 6px top and bottom padding and 8px horizontal padding.
> - [icon = LockKey, Regular]4px-spacing[copy = "Lock"] — Neutrals/800 (#282729)
> - [icon = ArchiveTray, Regular]4px-spacing[copy = "Archive"] — Neutrals/800 (#282729)
> - [icon = Flag, Regular]4px-spacing[copy = "Flag as spam"] — Neutrals/800 (#282729)
> - [icon = Trash, Regular]4px-spacing[copy = "Delete"] — Rorange/600 (#D63200)
If a user hovers over a dropdown icon, the list item will be highlighted with a background color of Neutrals/100 (#F0EFF0)

#### Behavior

**Thread post listing**

1. User hovers over whichever thread post listing they want to take a flagging action on
![threadPost (Hover)](https://github.com/hicommonwealth/commonwealth/assets/18157060/11888971-02cd-4b6c-ae68-0007c772ee18)

2. User hovers over the `…` icon to show the hover state
![threadPost (Icon Hover)](https://github.com/hicommonwealth/commonwealth/assets/18157060/f5bdfc45-8a0c-4064-b81c-712432f316a2)

4. If a user hovers over a dropdown icon, the list item will be highlighted with a background color of `Neutrals/100` (#F0EFF0)
![threadPost (Dropdown)](https://github.com/hicommonwealth/commonwealth/assets/18157060/b3b282b0-fcc0-41df-a32b-c9fc44435159)

5. User clicks on `Flag as spam`
![threadPost (Dropdown Hover)](https://github.com/hicommonwealth/commonwealth/assets/18157060/7c52e141-fd69-4435-ab81-1595f6fffbb8)

6. `Modal` appears with `Curtain` overlay
![05 Flag as spam (Admin) - Feed - Post - Confirmational Modal](https://github.com/hicommonwealth/commonwealth/assets/18157060/7ea86d1a-9c7d-4400-914a-2048fcb3750c)

- Full screen Curtain overlay = `Base/Black` (#000000) at 20%
- Modal on top of it
![Modal - Default](https://github.com/hicommonwealth/commonwealth/assets/18157060/ad9a4768-277d-49f3-8c2d-04039d4d5d59)
- Modal specs should be in another ticket (@jnaviask)? Not sure, it’s part of design systems but we need more variations to cover all our use cases.
- Header copy (`Heading 04/Medium`, `Neutrals/800`) = `Confirm flag as spam?`
- Body copy (`Body 02/Regular`, `Neutrals/800`) = `Are you sure you want to flag this post as spam?` `[Linebreak]`  `Flagging as spam will help filter out unwanted content. Posts flagged as spam are hidden from the main feed and can't be interacted with. For transparency, spam can still be viewed by community members if they choose to "Include posts flagged as spam."` `[Linebreak]` `Note that you can always unflag a post as spam.`
- CTAs: `Secondary button/Small - State: Default` `[Cancel]` 8px spacing `Primary button/Small - State: Default` `[Confirm]` (include hover states, use button component if possible)
- User hovers over `Confirm`, button will switch to `Primary button/Small - State: Hover`
- If the user clicks `Confirm` , the post will then be flagged as spam and disappear from the feed unless the user has the checkbox selected for Include posts flagged as spam
- If the user clicks `Cancel`, the modal will close + curtain disappears, and returns to the feed in its default state

## Resources 
- [Video walkthrough](https://www.loom.com/share/efefcade1ea84abbae9772f14bd69cbb)
- [Figma prototype](https://www.figma.com/proto/30dpVGV7zndfhS5V0jzf4W/Moderation?page-id=16%3A30537&type=design&node-id=16-47788&viewport=1329%2C300%2C0.11&scaling=min-zoom&starting-point-node-id=16%3A47788&show-proto-sidebar=1)
- [Figma designs](https://www.figma.com/file/30dpVGV7zndfhS5V0jzf4W/Moderation?type=design&node-id=16%3A30537&t=71kIFHlEBxIYM6jn-1)

## Acceptance Criteria
- Adds controllers for moderation support, pending #3976
- Adds moderation UI for threads and comments as described above + on Figma.
- Passes design review.

**Comment by jnaviask** [comment]
@mzparacha Note you're only to build the front-end side here (the spam filtering should take place on the frontend, ideally). Feel free to stub out places where server-side calls need to take place, and then we can plug it in when #3976 is completed.

**Comment by jessmart1213** [comment]
Hi! Have just conducted a Design QA for this issue. Some updates aren't directly about Spam, but are related to moderation. 

**MODAL BUTTONS**

**Confirm flag as spam modal**
- _Currently implemented modal_
<img width="513" alt="Screen Shot 2023-06-12 at 10 25 19 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/81ed7a35-e86a-4fe0-b205-500861407132">

- Do not use small rounded / pill shaped buttons for these modals. Use square buttons. 
- Destructive buttons or red buttons should not be used, they are not part of the designs. 
- If we do not have the new design system buttons ready for use, then use the square buttons that are currently implemented, which can be referenced at [https://commonwealth.im/components](https://commonwealth.im/components).

- _The design_
<img width="510" alt="Screen Shot 2023-06-12 at 10 28 05 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/dc615c1a-553f-4944-848a-0f9e775cfa8f">

Fixes: 
- The Cancel button should be a secondary (outlined) black button. 
- The Confirm button should be primary (filled) black button.

**Unflag as spam modal**
- _Currently implemented modal_
<img width="519" alt="Screen Shot 2023-06-12 at 10 25 49 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/77c8ec1c-c44f-4967-b5dc-8394d3919a5c">

- Do not use small rounded / pill shaped buttons for these modals. Use square buttons. 
- Destructive buttons or red buttons should not be used, they are not part of the designs. 
- If we do not have the new design system buttons ready for use, then use the square buttons that are currently implemented, which can be referenced at [https://commonwealth.im/components](https://commonwealth.im/components).

- _The design_
<img width="393" alt="Screen Shot 2023-06-12 at 10 27 51 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/49c3804b-1c17-4ed5-81de-df6c7ecd944d">

Fixes: 
- The Cancel button should be a secondary (outlined) black button. 
- The Unflag as spam button should be primary (filled) black button. Remove the question mark from the buttom copy. 

------

**LOCK THREAD & SPAM**

- When a thread is locked and has no comments the  'Show comments flagged as spam checkbox' should not be present.
<img width="1440" alt="Screen Shot 2023-06-12 at 8 43 40 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/91032e78-ae4e-446a-831e-aa172ea239d6">

------

**LOCK THREAD ICONS**

- Switch icons used for locked and unlocked thread. 
- Currently the Lock thread action has an open lock icon , when it should have a closed lock icon, Phospohor icon 'LockKey'.
-  <img width="184" alt="Screen Shot 2023-06-12 at 8 27 54 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/0580a5cf-bdb2-45ea-b261-728e16fc23b6">

- Currently the Unlock thread action has an closed lock icon , when it should have an lock icon, Phospohor icon 'LockKeyOpen'.
- <img width="276" alt="Screen Shot 2023-06-12 at 8 27 41 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/4c7fb9b6-a297-4a3b-aef2-51286d0d0e19">

**Comment by jessmart1213** [comment]
@mzparacha Thank you for quick response! Im just edited previous Design QA comment to included some updates for the DotsThree or ellipsis icon as well

**Comment by mzparacha** [comment]
@jessmart1213 these are updated in pr

> LOCK THREAD & SPAM
LOCK THREAD ICONS

for "DOTSTHREE ICON", the icon has 16x16 px size but it has some padding which makes it 32x24, this padding is also applied to other buttons in the same row (like the comment and share button).

Just to confirm if we still want the size including the padding to be exactly 16x16? One issue i think is that there will be a visible height difference b/w other buttons in the same row (like the comment and share buttons)

**Comment by jessmart1213** [comment]
Hey @mzparacha! 

Not sure what the currently implemented padding is, but based on the designs in the design system the 'DotsThree' icon should be 16 by 16 px and the padding should be 5px top, bottom, left and right. The height of Overflow cta should be 26px.

I made a loom where I show the padding for each thread action. Please see, [Thread Action padding - 13 June 2023](https://www.loom.com/share/faf24d69c9dc49c9b889c618c69375e7?sid=f6ebf7b6-20bb-4e59-a337-eb2b9677efdc).

**Comment by jessmart1213** [comment]
So the padding for the other thread actions - comment / reply, share, (un)subscribe, upvote - is 4px top and bottom with a 18 by 18 px icons totaling a height of 26px. The icon and padding for the overflow cta are different, but still add up to a 26px height, so all ctas / buttons should have the same height.
