### ISSUE TITLE
Scale down CE dynos

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3978]
## Description
We recently turned off chain-events for all Substrate chains since the types, api, etc are all outdated and have not been working for a while (differs for each chain). Since Substrate chains were by far the most resource-consuming of all the chains, now that they are disabled we can likely scale the ChainEventsSubscribers down to a single mid-size dyno. This requires a PR to edit the chain-events Procfile as well as testing on chain-events-staging to ensure there are no memory issues.

## Acceptance Criteria
- chain-events scaled down both in the number of dynos and dyno size.

**Comment by CowMuon** [comment]
Let's knock this out top of the priority stack, as it's a 1 pointer and this should have been cleaned up long ago

**Comment by timolegros** [comment]
@CowMuon Didn't realize earlier but we should fix #4272 before this ticket.

**Comment by timolegros** [comment]
Chain-events will be deprecated per #4696.
