### ISSUE TITLE
Magic link: custom domain - no cosmos address

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#3983]
- New email login (with magic), on Custom Domain, does not work

or 

- with gov.osmosis.zone, login works, but "No Cosmos Address"

**Comment by mhagel** [comment]
Just rolled back to [4d20d5273455821acccc331ab4fb030878ca1758](https://github.com/hicommonwealth/commonwealth/pull/3906/) and confirmed working properly then. 

The failure now is on the initial user create. I wonder if something changed in the User db model since then?
@jnaviask

**Comment by mhagel** [comment]
Working at this point too: https://github.com/hicommonwealth/commonwealth/pull/3952

**Comment by mhagel** [comment]
Now working on master. Maybe an intermittent Magic API issue.

**Comment by jnaviask** [comment]
Can't repro.
