### ISSUE TITLE
🏐: Evaluate feasibility of Evmos proposal creation

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3986]
## Description
To investigate: how do Evmos proposals work? What would be required for us to support Evmos transactions?

Timebox: 2 hours.

**Comment by mhagel** [comment]
`Unsupported type: '/ethermint.types.v1.EthAccount'`

<img width="731" alt="Screenshot 2023-05-22 at 1 17 11 PM" src="https://github.com/hicommonwealth/commonwealth/assets/9438198/7b02d05a-f1a1-409d-bba9-20694db29ae6">

**Comment by mhagel** [comment]
Evmos has their own library for keplr/MM interactions. So we could set up another fork in the code for these Ethermint cases. https://academy.evmos.org/articles/advanced/wallet-integration

**Comment by mhagel** [comment]
Evmos uses Cosmos SDK gov v1beta1. https://docs.cosmos.network/main/modules/gov

So, the errors we are seeing may just be account lookup errors. Keplr TXs may work once that is figured out.

**Comment by mhagel** [comment]
The biggest lift here may be supporting Keplr AND MM. That would be the best Evmos implementation. But just supporting Keplr would be a good start, and so far that is not looking too difficult.

**Comment by mhagel** [comment]
May just need this patch: https://github.com/hanchon-live/cosmjs-patch
If so, this is very easy.

**Comment by mhagel** [comment]
relevant: https://github.com/cosmos/cosmjs/issues/1351

**Comment by mhagel** [comment]
Findings:

- Easiest solution: add [EvmosJs](https://github.com/evmos/evmosjs#installation), and if needed, create an EthermintGovernance code path for Evmos and fork-chains.
- CosmJs does not support ethermint, and it's not straightforward to patch on our side

Estimate for suggested solution: 5
Estimate for adding Evmos devnet: 2

It _might_ be easier than this, but adding another governance path means testing a lot of code. 
I haven't looked into adding the integration yet. There is a chance that we wouldn't need a whole new code path (governance-ethermint.ts, etc), if this somehow unblocks v1beta1 TXs.

@jnaviask

**Comment by jnaviask** [comment]
Great findings, thanks for diving in. Will review and follow up with work items.
