### ISSUE TITLE
Allow merging posts/comments from a different owned address

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#399]
If there are multiple addresses linked on 1 user, you should be able to pick any eligible address and merge it in the others with respect to content that is posted on others.

1. Present the modal for signature generation
2. New route to check the signature or within the same merge route.
3. Sign from the account being merged and disappearing.
4. TBD: Keeping the profile around or deleting it?

**Comment by zakhap** [comment]
When we say merge, do we:
1. show more than one address/profile for the post/comment
2. switch ownership from one address to another if they are linked to the logged in user

**Comment by jnaviask** [comment]
cc @zakhap

**Comment by jnaviask** [comment]
Technically unified profiles fixes this.
