### ISSUE TITLE
Remove CE Substrate

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3991]
## Description
All Substrate chain listeners have been disabled since their types, APIs, etc are all out of date and we are no longer creating any useful entities for any Substrate chain. All code pertaining to the subscription of Substrate chains should be removed and only existing linking/labeling should be maintained. This will increase the development pace of CE changes and move us closer to a generalized ABI-based CE.

## Acceptance Criteria
- No more Substrate Listener, processor, subscriberFunc, or filters (keep labeling).

**Comment by CowMuon** [comment]
In review, will hopefully be merged on Monday
