### ISSUE TITLE
Identify where isAdmin() and isAdminOrMod() checks are performed, and replace with address-specific checks if possible

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#401]
There are many places in the codebase where we perform isAdmin() or isAdminOrMod() checks that look at all addresses owned by the current user.

Since we have robust address switching now, we should always scope the check to the currently active address instead.

- [x] Enumerate all the places where these checks are used
- [x] Convert to a check that 
- [x] If possible: Reduce the number of duplicate helpers that do the same thing...we have many role helpers that all perform the same check

In the near future, I'll also be adding UI to inform the user when they have a different address linked that is relevant to a specific operation (e.g. if you're on a thread that you created with a different linked address)

UPDATE:
Most (if not all) of these checks exist on the UserController now, `app.user` and so would be worthwhile to read that and re-integrate where it isn't being used.

**Comment by zakhap** [comment]
Enumeration of current role checks: 
- `User` Component: `app.user.isAdminOrMod`
- `EditTagModal`: `app.user.isAdminOfEntity()`
  - [ ] check route to see if admin verification
- `Tags` page uses `app.user.isAdminOfEntity()` for all related button renders
  - [ ] check route to see if admin verification
- `Roles.ts`: `invite button`, `upgrade member button`, `ChainOrCommunityRoles` all use `app.user.isAdminOfEntity`.
- `TagCaratMenu` checks `app.user.isAdminOfEntity`

- `UpgradeMemberModal` uses old role techniques, but is not currently in use as its functionality was moved into the `Admin Panel`. There is a TODO about using `app.user` but this seems unnecessary if not in use.

**Comment by zakhap** [comment]
@drewstone @raykyri 
I have gone through each of these uses of an admin check, verified that they use `app.user` controller, and checked that these admin-only ui elements use routes that also check admin status of the requester on the server.
I did not see any cases of redundant checks on the client nor unchecked routes.
I believe this issue can be closed with no further PR.
