### ISSUE TITLE
Improve /activeThreads route performance

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4010]
## Description
Currently the /activeThreads route is slower than /status, likely due to a similar issue, of performaing a Promise.all over all topics in a community. We should convert the multiple dispatched query to a single query if possible, to speed up performance. Should be an easy win!

**Comment by dillchen** [comment]
Might be helpful to include acceptance criteria for merging (I.e speed up outcome we're looking for)
