### ISSUE TITLE
Fix edit tag button

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#402]
The edit tag button still has issues. I tried to refactor it today but I don't think quick fixes will work here:

- When "Edit tag" is clicked on the thread carat menu, 
  - [x] 1) the menu does not close,
  - [ ] 2) we jump to the top of the page so the user loses their position if they were scrolled down.
- [x] When the edit tag modal is open it now doesn't close after saving.

**Comment by zakhap** [comment]
More bugs: 
- After closing the edit tag menu (without updating anything), if you try and open it again for the same thread, it fails to open the dialog/modal.
