### ISSUE TITLE
Proposal links going to /proposal/id page rather than ChainEntityLinkRedirect

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4029]
## Description
See: http://localhost:8080/edgeware/discussion/5374-pallet_supersig-joint-funding-proposal-with-w3f -- the onchain proposal links are incorrect, as they use the Chain Entity ID rather than the on-chain proposal ID.

We need to identify which cases require us to generate a link to the redirect page rather than directly to the proposal page (perhaps just certain community types which rely on chain entities, such as dydx?), and then fix the links.

cc @timolegros for chain entity info if needed.

## Acceptance Criteria
- Proposal links on threads should send user to correct page.

**Comment by ianrowan** [comment]
```

**Comment by ianrowan** [comment]
```
Select id, chain, links from "Threads" 
WHERE links @> '[{"source": "proposal", "title": null}]'
```
That dydx looks to be the only non-edgeware instance missing title
@jnaviask @timolegros

**Comment by jnaviask** [comment]
Great, we can close the PR then, no need for a workaround. Should be easy for an admin re-create the links in prod whenever.

**Comment by jnaviask** [comment]
Wont fix.

**Comment by jnaviask** [comment]
Reopening, because we can at least fix substrate proposal links for legacy reasons.

**Comment by jnaviask** [comment]
Unfortunately looks like:
1. the proposal tags still use the ce_id instead of the on-chain id (maybe no way around this)
2. the links generated are like https://commonwealth-beta.herokuapp.com/edgeware/proposal/treasury-proposal/75%7D which is incorrect -- we may need to use proper url encoding.

**Comment by ianrowan** [comment]
@jnaviask 
1. Was aware of this one and yeah assumed there isnt a way around this unless we load ce data for these proposal when rendering the page. Not sure if this is worth it 
2. Ah, figure the link wasnt working b/c of my db dump but was correct. I can see now whats wrong there. Didnt modify the logic in CE redirect but looks like we'll have to

**Comment by ianrowan** [comment]
@jnaviask  
2 was just a tiny bug in the redirect code adding an incorrect `}` to link which got encoded. However even with the newly generated link `http://localhost:8080/edgeware/proposal/treasury-proposal/75` app hangs on cow bobber with not errors so not sure if this will need more investigation

**Comment by jnaviask** [comment]
@ianrowan you can use the ProposalType enum ideally, which will generate `/proposal/treasuryproposal/id` which should work (remove the dash in the route link).

**Comment by ianrowan** [comment]
@jnaviask still no luck at http://localhost:8080/edgeware/proposal/treasuryproposal/75 

I have been using the redirect helper. It was missing the chainEntityTypeToProposalSlug() which I added to get the above but the bobber is still all that I get

**Comment by jnaviask** [comment]
This is the correct URL, edgeware proposal loading is likely broken in other areas.

**Comment by ianrowan** [comment]
@jnaviask Do we want to address broken edgeware here or PR the fix to resolve the URL to the above for this issue?
