### ISSUE TITLE
Design System: Upvotes

### ISSUE THREAD

**Issue by meeshlin** [hicommonwealth/commonwealth#4035]
Users can upvote posts as an interaction to show positive feedback 

![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/5868b403-6d5b-4cd3-8ed9-c598e7d92647)

#### Design requirements
- This component can either indicate that a post **has been upvoted (`Upvoted=Yes`)** or has not been upvoted (`Upvoted=No`)**
- If `Upvote=No`, there are only 3 states`Default`, `Hover`, and `Disabled`
- If `Upvote=Yes`, there are 4 states`Default`, `Hover`, `Active`, and `Disabled`
- Max width for the container with numbers is 32px **(no overflow, use "k" or "m" to signify thousands or millions)**

#### Design resources
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/c8504afe-b05a-4d3f-9617-c5eec2b91cb4)
- 🎨 [Figma file](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=618%3A5101&t=ugnPgbpoK44T4NwU-1)

## Product Requirements
- Add component to Storybook with a story to be audited via Chromatic
- Replace current "Heart" system within the new Upvote component.

**Comment by CowMuon** [comment]
This is sufficiently scoped to be added to the back log in today's refinement, however we may / may not have resources to tee it up as soon as tomorrow's sprint planning. Will circle back and update when we can bring it into current scope of work (ie teeing it up.)
