### ISSUE TITLE
D&D Hover State

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4037]
## Summary of solution and design (UX/UI) requirements

**Updated the editor to**

- Have an obvious drag and drop state, meaning that when users select and drag  upload-able items the editor ui changes.

<img width="552" alt="Screen Shot 2023-05-25 at 4 51 28 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/c9d9744b-5d27-4a88-8c09-6b683cc04e8b">

**Design specifications**

- Text container border
    - Color: Primary / 500 or #338FFF
    - Line weight: 2px
    - Line type: dashed
- Drag and drop cursor
    - Color: Primary / 500 or #338FFF

**Behavior**

- Text container border
    - When users select and drag upload-able items the text container border changes from a solid to dashed blue line. This indicates to the user
    - that the Common editor does have the drag and drop functionality
    - and where the drop zone is.
- Drag and drop cursor
    - This cursor appears within the editor to indicate where the uploaded items will dropped: above or below certain lines of text.
    - It should not be a blinking cursor.

### Design Documents
- Design Solution Doc: https://www.notion.so/buildcommon/Design-Solution-D-D-Hover-State-e89c60a482544b20999bd862fcec7820
- Figma masterfile: https://www.figma.com/file/wt6LJdgoupZvhgOiGrn0JZ/Forum-Improvements---Part-2?type=design&node-id=136%3A11719&t=7bRlogg4TKwOxAGm-1
- Figma prototype: https://www.figma.com/proto/wt6LJdgoupZvhgOiGrn0JZ/Forum-Improvements---Part-2?page-id=229%3A20768&type=design&node-id=232-17885&viewport=386%2C106%2C0.16&scaling=scale-down&starting-point-node-id=232%3A16823
- Prototype walkthrough: https://github.com/hicommonwealth/commonwealth/assets/133259695/c46cf54a-e90d-4c07-a664-e28bdfb563c9

## Acceptance Criteria (reflections of the user stories as criteria)
- As a user, I should get visual feedback from an on hover drag+drop experience in the editor, based on the designs above.

**Comment by martins87** [comment]
@zakhap regarding the Drag and drop cursor, the only style added to it should be the change to #338FFF color?

I'm asking because there are other examples, like this one:

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/732c1da0-a2d5-4b2a-afc0-a0936eb84140)

**Comment by zakhap** [comment]
@martins87 We're not updating the mouse cursor but the cursor within the editor (the one that shows where the image is going to be dropped)!

<img width="206" alt="Screen Shot 2023-06-01 at 11 20 27 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/cc87d553-7aba-450b-85fe-0c5c0dc30178">

**Comment by martins87** [comment]
> @martins87 We're not updating the mouse cursor but the cursor within the editor (the one that shows where the image is going to be dropped)!
> 
> <img alt="Screen Shot 2023-06-01 at 11 20 27 AM" width="206" src="https://user-images.githubusercontent.com/16248081/242646430-cc87d553-7aba-450b-85fe-0c5c0dc30178.png">

Perfect, thanks.
