### ISSUE TITLE
Stand up Evmos devnet + test cases

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4056]
## Description
Per #3986, we should spin up an Evmos devnet and create test cases akin to other Cosmos chains.

Feel free to add more details to this ticket as needed.

**Comment by mhagel** [comment]
One hitch I am currently dealing with, just for transparency...

For a new address, the evmos devnet will generate an address with private key and passphrase. But when I import this mnemonic into keplr, the address is different, and it doesn't have the expected tokens. I am not sure yet if this is a new Keplr bug, or if I am missing something in my process. But I can't test integrations yet.

I decided to pause on the devnet and focus on the EvmosJs ticket for the moment. I can at least get to the point of testing the initial transaction submission to get an expected response (but I would need a live proposal on evmos or injective to test a full TX). 

Hopefully something will click for me on the keplr side. I didn't see any related issues raised on Keplr's repo, but I will check into it more.

**Comment by CowMuon** [comment]
Adding Ian as pair here, where did we land with this?

**Comment by mhagel** [comment]
Integrating a local node with our app via Keplr has been difficult. No matter how I configure the localnet, Keplr wants to denominate in TEVMOS (testnet tokens) instead of EVMOS (as configured).

I may try an injective localnet to see if the configuration is less complicated.

**Comment by mhagel** [comment]
I have a theory that Keplr is overriding token configuration, and setting non-mainnet tokens to TEVMOS. Pausing this to get some clarity from Keplr team.
