### ISSUE TITLE
GetAddressProfile blocks page loading on "Invalid Address" error

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4063]
## Description
To replicate:
- Join both redacted-cartel and osmosis.
- Load /redacted-cartel. Open network tab.
- Navigate to Osmosis via the quick switcher sidebar.
- Note the 400 error for /getAddressProfile causing infinite load.

## Acceptance Criteria
- /getAddressProfile errors should be handled gracefully.

**Comment by NakulManchanda** [comment]
Here is one page which never loads:
https://commonwealth-staging.herokuapp.com/aave/proposal/onchainproposal/235

Load Testing:
https://github.com/hicommonwealth/commonwealth/issues/3161
