### ISSUE TITLE
Allow Threads to be Linked on Snapshot Proposal

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4066]
User is unable to link a snapshot proposal to a thread. They are able to save and attempt to link but it doesn't get saved.

Steps to reproduce:
1. Create a new thread.
2. Click Link Proposal, select a snapshot.
3. Click save -> nothing will be saved.

**Acceptance Criteria:**
Users can link snapshot proposals to thread, save, and have the snapshot be permanently linked.

**Comment by jnaviask** [comment]
@alexyoung23j Please add:
- Bug and BD Reported labels
- Steps to reproduce

**Comment by alexyoung23j** [comment]
Waiting on that information now.
