### ISSUE TITLE
Add missing index - thread_id on comments

### ISSUE THREAD

**Issue by NakulManchanda** [hicommonwealth/commonwealth#4075]
## Description

Smaller focused ticket out this bigger ticket:

[Database Cleanup and Sequelize Model <> DB Schema Synchronization](https://github.com/hicommonwealth/commonwealth/issues/3349)

<img width="1239" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/2e937dc8-9969-4e24-a18e-acae70a25719">

## impact
It will speed up many queries

## Acceptance Criteria
- threads & comments are highly coupled and thread_id is foreign key too
- add thread_id index on Comments

**Comment by jnaviask** [comment]
@NakulManchanda please add points.
