### ISSUE TITLE
Forum Endpoints Refactor: Comments

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4086]
Parent ticket: https://github.com/hicommonwealth/commonwealth/issues/3989

## Summary

- Add a controller layer and refactor endpoints according to the below endpoints naming scheme
- Update the UI to use new endpoints
- Remove old endpoints and any references to them
- Add basic unit tests w/ mocked model?

## Endpoints:

`GET /comments` ✅ - Returns bulk comments
- Implements functionality from `searchComments` (not `bulkComments`)

`POST /threads/:id/comments` ✅ – Creates a new comment on a thread, returns comment
- Implements functionality from `/createComment`

`POST /comments/:id/comments` ❌ (this endpoint is redundant)– Creates a new comment (reply) on a parent comment, returns comment
- Implements functionality from `/createComment`

`PATCH /comments/:id` ✅ – Updates a comment, returns comment
- Implements functionality from `/editComment`

`DELETE /comments/:id` ✅ – Deletes a comment, returns nothing
- Implements functionality from `/deleteComment`

---

Also need to update comment reactions logic to return reactions along with comments, and fix the janky UI for comment reactions.

**Comment by rbennettcw** [comment]
There are a lot of unit test cases for this ticket. Going to take a bit longer, so I'd re-rank this as a 5.

**Comment by jnaviask** [comment]
I updated it for ya :P
