### ISSUE TITLE
Clicking on a batched list of "new thread" notifications should take me to the most recent thread on the listing page

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#409]
Right now it goes to an individual thread

**Comment by raykyri** [comment]
I'm not sure how long this will take as it requires adding some handling of pagination on the listing page.

**Comment by zakhap** [comment]
It currently goes to the most recent notification's path (`/discussions/thread`), and you're saying it should just go to `/discussions`? Should the related new thread be highlighted or is it safe to assume it's just the thread at the top of discussions?

**Comment by raykyri** [comment]
It should really be highlighted, but it's fine if we just scroll down to it. I think the ideal motion design would be similar to on Discord when you jump to a past thread

**Comment by raykyri** [comment]
Actually as a first pass it's probably fine if we just take you to the top of the page - I forgot that we have unseen state
