### ISSUE TITLE
cache /api/ce/events

### ISSUE THREAD

**Issue by NakulManchanda** [hicommonwealth/commonwealth#4090]
## Description
/api/ce/events is currently one of slowest call especially for cosmos communities eg. 

Redoing closed PR as this endpoint smaller focused PR.
Solution was already implement, just need a new PR for review 

## Acceptance Criteria
- add cache with relevant TTL

**Comment by jnaviask** [comment]
Caching is not the solution. Events are supposed to be real-time. Instead we need to modify the way the route works to support the actions we want.

In general, caching is not a hammer, or a tool we want to use everywhere, and especially when thinking in terms of arbitrary TTLs. We should use caching in a targeted way, rather than as a bandaid when things are slow.

**Comment by NakulManchanda** [comment]
@jnaviask 
> Events are supposed to be real-time.  

Or near real time.
- We are not blocking the logic to refresh events in database
- We are just caching result from CE Proxy, displaying new events to user every 5mins

**How is it different than caching Cosmos results, or any other third party results?**

Only question is degree of staleness here is acceptable or not?
Little stale data vs improved user experience - thats the trade off here!

**Solution 1:**
We can cache it for 30sec if that makes the cut for real-time.
There is no logic on main service to optimize this.

**Solution 2:**
We can always make a request to recompute result in background
But serve the cached result:
- get result from cache - still need TTL if its still a active key
- refresh result - in background for next time & refresh key - TTL & value

> closed this as [not planned](https://github.com/hicommonwealth/commonwealth/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22).  

**Are we not planning to improve the performance of this endpoint?**
I believe we are targeting every frequent endpoint, this surely makes the cut - called on every community page & thread.

Pose it as question atleast:
- can we find different solution? rather than closing the issue & marking it not planned.
