### ISSUE TITLE
Fix threadTitle usage in ProposalCard and ChainEntitiesSelector

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4094]
## Description
The threadTitle field on ChainEntities will be deprecated following #4025, and besides that, the links to threads are broken following the Unified Linking release. We should fix the backlinks in ProposalCard and ChainEntitiesSelector to query against the new linking system rather than the legacy database relation.

If fixes are large / require difficult queries, please ask for how to proceed, as we may be able to modify product constraints to ensure consistent / performant behavior.

## Acceptance Criteria
- Proposal Card "Go To Thread" should take user to linked thread, if any.
- Chain Entities Selector should display linked thread on entities, if any.

**Comment by ianrowan** [comment]
I think we left off on a UX question here when we were re-building linking: 

Proposals(prev chainEntities) can now be linked to many threads so In terms of "Go to Thread" should we create a UI element similar to `linked_proposal_card.tsx` on an individual proposals pages? As far as cards in the all proposals page this might be a bit trickier to display all links on a card.

Same UX consideration for the chainEntitiesSelector, if a proposal is linked to multiple proposals how would we want to visualize this in the selector?

I cant remember where but for the selector there was conversation(might have been office hrs) to just hold off on the thread in the chainEntitiesSelector b/c it wasnt as straightforward with multiple links 

CC: @jnaviask

**Comment by ianrowan** [comment]
@jnaviask Got it I will remove the thread title from chainEntitySelector as part of this ticket 

And I think the proposal view would need some design work. I got the 'go to thread' component to populate from hard coding some data and it looks as follows:
<img width="288" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/a830772c-9ec1-48f6-9069-cc37a2a04473">

And on the proposal page its just a button
<img width="798" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/4a087fa9-9f34-4444-9b31-a57269f43ee7">

I don't see a way to support/give options for multiple threads here out of the box and imo I would vote for us to add the thread links to the individual view_proposal page itself using a similar component design as linked_proposal_card on thread pages

**Comment by ianrowan** [comment]
@jnaviask Got it, I could try to replicate the 'Go to Discussion' across the # of linked threads(if > 1) and add thread titles. We have routes to get all threads linked to a given link object so the queries, should all be there. Mainly just Frontend changes

**Comment by jnaviask** [comment]
@ianrowan I think replicating the Go To Discussion is best -- don't want to introduce a new card at this time.

**Comment by ianrowan** [comment]
Was able to spin this up to produce buttons as follows: 


![Image](https://github.com/hicommonwealth/commonwealth/assets/36428666/ad72988c-2dd2-4117-b0b0-83438b3c99fa)

@jnaviask thoughts?

**Comment by jnaviask** [comment]
Looks great -- one fix is it should only show "Go to Thread:" if there's no title available. Otherwise the link URL can just be the title.
