### ISSUE TITLE
Open Threads/Proposals in New Tab

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4100]
### User Stories
- [x] As a user, I want to be able to right-click or control-click a thread from the listing page and it have the option to open in a new tab. -  handled in https://github.com/hicommonwealth/commonwealth/pull/4065/
- [x] As a user, I want to be able to right-click or control-click any activity row from any of the Dashboard Feeds to open them in a new tab.
- [x] As a mac user, I want to be able to command click threads in listing page or activity rows in dashboard and it automatically open a new tab.

## Acceptance Criteria
- the stories above are satisfied: right clicking and command clicking can enable opening pages in new tabs.

**Comment by mzparacha** [comment]
> As a user, I want to be able to right-click or control-click a thread from the listing page and it have the option to open in a new tab.

was added in https://github.com/hicommonwealth/commonwealth/pull/4065/ but control click opens it automatically in a new tab (which is the default behaviour for links) - just to confirm control click should open in a new tab, right?

**Comment by jnaviask** [comment]
Yes, ctrl+click should open a new tab, as per expected / standard internet behavior.

**Comment by jnaviask** [comment]
@mzparacha Looks like we still need to cover the UserDashboardChainEventRow in addition to the UserDashboardRow. Re-opening.
