### ISSUE TITLE
Delete deprecated social login + email login code

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4105]
## Description

We currently still have routes available for legacy social login (github and discord, iirc). These routes should be removed now that we can use Magic Link for login.

**Comment by jnaviask** [comment]
Apparently we still use /updateEmail, which uses the legacy email login flow?? Holy f! cc @alexyoung23j how can we remove this flow...

**Comment by alexyoung23j** [comment]
@jnaviask Well, looks like its only being used for email digest. So if our social login is setting their email and email_verified (need to check whether this is the case), they won't be prompted to change their email in the notifications page and will just get the digest sent to their social login email. If they don't then we have an interesting case. 

If they were to update their email here, and then login with a social login and connect that account, it would override their explicitly stated preference for which email to send the digest to. Not sure this is a big enough case to matter, but if we do want to prevent this from happening, we should probably add a new field to `Profile` thats just like `digest_email`. Then this will be defaulted to the users social email, if they have one, and if they want to set it manually they can.

But this gets complicated pretty quickly so I think @zakhap a product pass is needed to decide what we actually want to happen.

**Comment by jnaviask** [comment]
Marking as blocked + bouncing until we figure out how to handle this.

**Comment by jnaviask** [comment]
Plan is to keep the email login flow for now, and just deprecate social login in scope for ticket. Updating body to match.
