### ISSUE TITLE
Design System: Update thread post and address tags

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4118]
## Description

Update the styling of our tags to match the new typography and colors for thread post listings and thread post pages.

### Thread post tags
**Thread post (example with all tags present)**
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/82f4f9f2-3ff4-4c68-9e2e-c97f85a04879)

**Spam post**
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/b3fd471a-9de6-47aa-badf-de7df0b83c5b)

- **Status tags:** `New`, `Spam`, and `Trending` (which will replace the :fire: emoji)
- **Element tags** — `Poll` and `Snapshot`
- **Stage tags** — Standardized, can keep using [@Jessica Martinez](https://commonxyz.slack.com/team/U04QV8NURH9)
’s designs with the green tag in the product. However, to allow for customization of stage tags in the future, also build out the variations with the different colors.
- **Prop tags** — Update to match styling
- **User login tags** — This tag is meant to replace the wallet tag next to display names if the user signed in or is tied to a community they joined through social login—for example: with an address, it’s standardized but looks like our previous tags, but if a user logged in via social, they will not see an address but this tag denoting the means of login
- **Input tags** — Community and/or user tags that will go into the search field
- **Address tags** — In `Edit profile`, this shows the updated tags for Magic-generated addresses

### Edit profile page
**Linked addresses section in `Edit profile` page**
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/824e6a8d-f787-48c7-ae60-9637933325e2)

- **Address tags** — In `Edit profile`, these tags denote the Magic-generated addresses via social login

### Resources
- **(Main) Figma designs:** [Tags](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=252%3A2907&t=7FIml7Y2D38gkaRS-1)
- **(Additional context) Figma designs:** [Thread post listing](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=133%3A2278&t=7FIml7Y2D38gkaRS-1)
- **(Additional context) Figma designs:** [Edit profile page](https://www.figma.com/file/mJMPTzEnpEFIaR2wBWkElq/Login?type=design&node-id=126%3A37904&t=lsoYNJsAxtaXCxT3-1)

## Acceptance Criteria
- Above tags are added to the Component Kit + Auditable via Storybook stories for the tags.

**Comment by meeshlin** [comment]
Ticket description added!

@jnaviask @MuonShot @zakhap @dillchen

**Comment by Miaplacidus** [comment]
@meeshlin I don't need it for this current task, but would you mind giving me access to the Edit Profile Page?

**Comment by CowMuon** [comment]
2 QQ: 

1. Does everyone have the access they will need going forward? I want to insure we eliminate any "I need access" loops in the future by everyone having the access they need. (And we have use dev mode views in Figma is needed to only show components that are ready for development.) @martins87 

2. What is current state of this scope of work? (ie ETA) @Miaplacidus

**Comment by meeshlin** [comment]
I just gave you access, @Miaplacidus 

This is @jessmart1213's work, but I'm iterating upon it for aggregating addresses and will make sure that's visible to everyone
