### ISSUE TITLE
Design System: Search Bar

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4119]
## Description

Specification Update: 
- Radius of 6px with community and/or user tags in the field when viewing a community or user

<img width="1011" alt="Screen Shot 2023-06-01 at 1 13 29 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/95672ff4-09a2-49e1-9e37-50e801bf6804">

Figma:  https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=26-7637&t=6VU0CAdzZWtdhcxD-0

## Acceptance Criteria

- Updated component should be added to Storybook and auditable via the Stories.
- Live Search Bar(s) reflects updates in Design System figma

**Comment by zakhap** [comment]
Let's just make search bar a separate component that our textinput so that there aren't any accidental style cascade issues. it should **probably** use the mui-base autocomplete component: https://mui.com/base-ui/react-autocomplete/

**Comment by martins87** [comment]
@zakhap I have some questions about the behaviour of the component. Please check the images below.

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/b4a7e10c-7ce2-4259-a965-5b35c8d91e11)

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/43401bbd-908c-4b00-b0b6-c8284db71c06)

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/2d492d73-74f2-4721-a4ee-47bf7123e0ac)

1. What does the tag represent? Does it mean that whatever is typed in the input will be searched only in that community?
2. After clicking in a community, should the input be reset to '' ?

**Comment by meeshlin** [comment]
The tag is meant to let the user know when they are in a community—see how it's done in Reddit ([Loom walkthrough](https://www.loom.com/share/3fee916b19dc4510902e152b0063c1fa?sid=0fdc279b-42d3-4f58-a280-3c73c98bd397)).

However, Reddit allows users to search within the community...which, quite frankly, would provide a ton of value for community members navigating Common. Since we can't do that yet, we can stick to the original behavior of not showing an input community tag for now?

cc: @martins87 @Miaplacidus @zakhap

**Comment by martins87** [comment]
> The tag is meant to let the user know when they are in a community—see how it's done in Reddit ([Loom walkthrough](https://www.loom.com/share/3fee916b19dc4510902e152b0063c1fa?sid=0fdc279b-42d3-4f58-a280-3c73c98bd397)).
> 
> However, Reddit allows users to search within the community...which, quite frankly, would provide a ton of value for community members navigating Common. Since we can't do that yet, we can stick to the original behavior of not showing an input community tag for now?
> 
> cc: @martins87 @Miaplacidus @zakhap

Many thanks for the loom walkthrough, @meeshlin!

For the moment I'll just implement the following then:

1. User clicks on SearchBar, communities appear on the Combobox
2. User clicks on a specific community, community tag appears. Input is reset

Please let me know your thoughts on this, @meeshlin @zakhap @masvelio

**Comment by martins87** [comment]
> 

Sure. I'm atm addressing Marcin's comments. Will reply to each comment and tag the design team here and also Slack when ready.

**Comment by zakhap** [comment]
> The tag is meant to let the user know when they are in a community—see how it's done in Reddit

What Meesh wrote above, this makes sense to me: Show the tag in the search bar when the user is in a community.

What doesn't make sense to me: Searching first for a community, then searching for the thing you want. Users should just search for the thing you want.

**Comment by jessmart1213** [comment]
### Design review feedback

I have 2 points of feedback:
- On the demo app, when a user hovers/ mouses over the search bar once it's in its focus state, the inner border changes from primary blue/500 to primary blue/600. Desired behavior is that once the user selects the search bar triggering its focus state, the inner border stays at primary blue 500, regardless of where the user's mouse is. Please see [loom: Updated search bar feedback](https://www.loom.com/share/db10cfc9a80045cb940efea05450ee15?sid=42fc1115-8a6c-4b8b-b6cd-9482f7874c33) for more context!
- Update search bar text "Search Common" from Body 01 / Regular to Body 02 / Regular.

Aside from the points above, everything else looks good to me! Thank you!

**Comment by martins87** [comment]
> ### Design review feedback
> I have 2 points of feedback:
> 
> * On the demo app, when a user hovers/ mouses over the search bar once it's in its focus state, the inner border changes from primary blue/500 to primary blue/600. Desired behavior is that once the user selects the search bar triggering its focus state, the inner border stays at primary blue 500, regardless of where the user's mouse is. Please see [loom: Updated search bar feedback](https://www.loom.com/share/db10cfc9a80045cb940efea05450ee15?sid=42fc1115-8a6c-4b8b-b6cd-9482f7874c33) for more context!
> * Update search bar text "Search Common" from Body 01 / Regular to Body 02 / Regular.
> 
> Aside from the points above, everything else looks good to me! Thank you!

Thanks for the feedback, Jessica.

Both have been fixed. Please check on [demo](https://commonwealth-demo.herokuapp.com/communities) whenever you can.
