### ISSUE TITLE
Design System: Thread Actions

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4120]
## Description

- Upvote button and all states (default, hover, disabled)
- Actions and all states (default, hover, disabled)
  - Upvote (in responsive state)
  - Comment
  - Share
  - Subscribe
  - Overflow (…)
 

<img width="947" alt="Screen Shot 2023-06-01 at 1 16 52 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/402bf21f-1515-4e8e-95b4-352afb290cd7">

Figma: https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=618-5094&t=VH7p5dn2RgGO3Pgn-0

## Acceptance Criteria

- Above components are added to the Component Kit and are auditable via Storybook stories.
- All updates are used in context, Thread page + thread preview row components are updated to reflect these styles.

**Comment by martins87** [comment]
@zakhap on the ThreadActions, should every action component be a separate component or a unique one where you can pass props like action={"comment" | "share" | "subscribe" | "upvote" | "overflow} ?

**Comment by martins87** [comment]
Upvotes implemented on #4035

**Comment by masvelio** [comment]
@martins87 @zakhap I would say that `ThreadAction` should be one generic component that handles styles and hover/disabled states. But instead of passing `type` I would pass `icon`, `label` and `onClick`. Idea is that `ThreadAction` should be "dumb"

**Comment by martins87** [comment]
> @martins87 @zakhap I would say that `ThreadAction` should be one generic component that handles styles and hover/disabled states. But instead of passing `type` I would pass `icon`, `label` and `onClick`. Idea is that `ThreadAction` should be "dumb"

@masvelio @zakhap I implemented [the component](https://github.com/hicommonwealth/commonwealth/blob/daniel.4120.thread-actions/packages/commonwealth/client/scripts/views/components/component_kit/new_designs/cw_thread_action.tsx) the way Marcin mentioned.

You just have to pass the props 'action' as a string and the component handles all phosphor icons and styles:

![image](https://github.com/hicommonwealth/commonwealth/assets/30223098/14ced847-323a-4b67-a7a7-0906418acb72)

**Comment by CowMuon** [comment]
Bounced back to in progress for @martins87 to catch the CICD error.

**Comment by martins87** [comment]
> Bounced back to in progress for @martins87 to catch the CICD error.

Moved to Has PR as CICD error was fixed.

**Comment by masvelio** [comment]
@meeshlin that is all good - I am assuming that definition of your component vs our (react) component is a bit different. We are gonna have one generic component that will handle 5 different action buttons based on the prop. We will be able to handle all those examples you mentioned above 🙌
