### ISSUE TITLE
Design System: Tooltips

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4123]
## Description

- Base component and all directions
  - Max width of entire component = 232px
  - Max of two lines

<img width="520" alt="Screen Shot 2023-06-01 at 1 22 41 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/f4920a30-a75f-4b44-bbae-054ccf308274">

Figma: https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=481-4642&t=KXxdmSCtWpGv6n0A-0

## Acceptance Criteria

- New Tooltip component created so it doesn't trickle across the site or interfere with existing CSS.
  - Use MUIBase
- Add to component kit and make auditable via Storybook Stories.

**Comment by masvelio** [comment]
@MuonShot @zakhap should we teed this up for this week?

**Comment by CowMuon** [comment]
Please note a requirement here is to use mui-base.

**Comment by martins87** [comment]
> Please note a requirement here is to use mui-base.

The thing is: mui-base does not have the Tooltip component implemented yet: [here](https://github.com/mui/material-ui/issues/27170)

Options:
1. Implement from scratch
2. Use [Joy UI](https://mui.com/joy-ui/getting-started/). The library is similar to Base UI and already has the [Tooltip component](https://mui.com/joy-ui/react-tooltip/).

If yes to second question, Draft PR is here: https://github.com/hicommonwealth/commonwealth/pull/4514

Cc @jnaviask @zakhap @masvelio

**Comment by masvelio** [comment]
That's a bummer. Some time ago I proposed that we could use https://www.radix-ui.com/ as they have a lot of components and generally the lib has great reviews. If we don't want to use anything else though, we should keep using mui-base. In this case, we have to stick to their `popper`. We use it currently for the tooltip component. Maybe we can try using our current component (just adjust styling) instead of creating new one?

**Comment by martins87** [comment]
> That's a bummer. Some time ago I proposed that we could use https://www.radix-ui.com/ as they have a lot of components and generally the lib has great reviews. If we don't want to use anything else though, we should keep using mui-base. In this case, we have to stick to their `popper`. We use it currently for the tooltip component. Maybe we can try using our current component (just adjust styling) instead of creating new one?

I'm down for using only one ui library. We could use mui-base but it's on its early stages, so changing from library to library is not a good idea. I used mui on previous projects, they also have a lot of components already built.

Popper would be a good one.

@zakhap @jnaviask @MuonShot thoughts?

**Comment by martins87** [comment]
@zakhap component is ready for review. Just a last question about its behaviour:

Should the tooltip appear when element is clicked or just hovered?
