### ISSUE TITLE
Subscribe all Users to ChangeLog Topic in CMN-Protocol Community

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4124]
## Description

BD wants **all of our users** to receive a notification each time they post a new thread in a changelog topic in our community forum (cmn-protocol).

- As a user, I should receive a NewThread Notification every time a New Thread is created in a Topic that I am subscribed to. **=> this is a new Subscription type.**
- As a user, I should be auto-subscribed to receive a NewThread Notification for the /cmn-protocol community's "ChangeLog" Topic.
- As a user, if the topic i am subscribed to gets deleted, so does my subscription (so it doesn't show up in the subscription management page). 
- As a user, I should be able to unsubscribe on the notification subscription management page.

Out of Scope: 
- Allowing users subscribe to topics themselves. (needs design)

## Engineering Requirements

- A new Subscription Type

## Acceptance Criteria

- All users are subscribed to NewThread notifications within the cmn-protocol's "Changelog" topic.

**Comment by jnaviask** [comment]
Not planned.

**Comment by timolegros** [comment]
Lol - I know this is not planned but just saying this would have probably brought down production every time a new thread (in ChangeLog topic) is created lmao - will be doable in the new system tho :)
