### ISSUE TITLE
Design: Streamline Notifications, NotificationReads, Subscriptions

### ISSUE THREAD

**Issue by NakulManchanda** [hicommonwealth/commonwealth#4126]
## Description
- Large Notification Read table fanout

## Engineering Requirements
- Redesign schema Notification, NotificationRead, Subscriptions to 

### **Part 1: Improving relation between **Notification & Notification Reads****

**Current Lifecycle ->** 
**A)** Notification event occurred
**B)** User logs in -> Notification sent to user (what to show user already pre-computed in NotificationRead)
**C)** User see notification -> Notification read by user(if user reads it, update row in NotificationRead to mark it read)

**Alternate Suggestion->**
**A)** Notification event occurred
**B)** User logs in -> Notification sent to user (compute in real time join Notification & current Subscription, Left join NotificationRead)
**C)** User see notification -> Notification read by user(insert new row for read notification)

**Trade Off**
- Runtime query to generate notification might be slower but could be faster as Notification read table is huge
- We are not using subscription settings in that moment of time, instead always latest one 
     - which is fine if user unsubscribed we won't show him old notification when he was subscribed

**Pros**
- We don't need to generate any NotificationRead entry for user who never logs in
- We don't need to generate any NotificationRead entry for user who never see notifications

**Current Stats:**
- We are generating Notifications for all users and they are going unread
- 21M Notifications generated, only 150K read - **basically only 0.7% of notifications are read**
<img width="646" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/bbd55d1c-51d7-46de-ae80-e3e0732e8fbf">

**Three related entities**
- **Notification** - generates one row per notification
- **Subscription** - keep track of user subscriptions - changes with time, as he joins more communities etc
- **NotificationRead** - One row per user per notification - has extra read_ind too to check if user read the Notification

  
 **Current setup Query Simulation**
  **A)** Notification generated
  ```
  INSERT INTO NotificationRead
  SELECT user_id, not_id, sub_id, read_ind, created_time...
  FROM Notifications
  JOIN Subscription
  ```
  
   **B)** User logs in and we need to show Notification
  ```
  SELECT * 
  FROM NotificationRead 
  JOIN Notification on n_id
  where user_id=user_id 
  order by created_time
  ```
  
  **C)** User read notification
  ```
  Update NotificationRead
  SET mark_ind=true
  where <Not_read_id>
  ```

**Alternate Scenario Query Simulation Using subscription in real time:**

**A)** Notification generated
  ```
  Do Nothing in "NotificationRead"
  ```
  
   **B)** User logs in and we need to show Notification - generate Notification in real time by running SQL Query
  ```
  SELECT user_id, not_id, sub_id, ISNULL(nr.read_ind,false), created_time
FROM Notifications n
JOIN Subscription s where <s.user_id>
LEFT JOIN NotificationRead where <nr.user_id>

  ```
  **C)** User read notification - Insert into NotificationRead - if user reads Notification
  ```
  Insert INTO NotificationRead
  SELECT user_id, not_id, sub_id, true as read_ind
  ```
  
  
  
**Consideration**
Check if this approach is compatible for online users where we send Notifications via websockets

## Acceptance Criteria
- Less bloat in notification read
- Less load on system, db space etc

### **Part 2: Improving relation between **Subscription & Notification**** - Very Speculative
<img width="1361" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/97bf394f-eb9c-49bb-8000-85da7f65eb36">

Rows in "Subscription" table looks redundant, most users have default settings
We are repeating lot of data
We can organize them differently to reduce number of rows we save.

No. of Chains - 1656 - chain_id
No. of Users - 111463 - user_id
NotificationCategories - 13 - notif_cat_id

"NotificationCategories" to "Subscriptions" - 
"new-thread" 
   - every thread of every community qualify for this notification type 
   - 1656 possible combinations of this stream - **chain_id, notif_category_id**
   - if we create 
   Worst Case Scenario - every user joins every community
   1656 entry for all 111463 users with default options - **chain_id, notif_category_id,user_id** - 184M records
   Realistic case - every user joins every community
   7 entry for all 111463 users with default options - **chain_id, notif_category_id,user_id** - 777K

Instead we can just store overrides & default options can be stored with NotificationCategories - we dont have to repeat default options - store the negatives instead - if user want to turn off etc - could be other option
      
 
Here are some stats on average how many users are joined to how many communities:  
<img width="1318" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/1528a774-80aa-42b6-a201-785bd2df0c32">

**Comment by NakulManchanda** [comment]
if we like this approach, how fast would be this query - if fast enough could be good approach with all the Gotchas above

B) User logs in and we need to show Notification - generate Notification in real time by running SQL Query
```
SELECT user_id, not_id, sub_id, ISNULL(nr.read_ind,false), created_time
FROM Notifications n
JOIN Subscription s where <s.user_id>
LEFT JOIN NotificationRead where <nr.user_id>
```

**Comment by NakulManchanda** [comment]
Scenario: **ChangeLog Notification** for users
- Every User who logs in will see Notification - could be last 10 change logs at max
- if he reads ChangeLog it will be marked as Read and we make new entry to NotificationRead which helps UI to highlight to user that he already read this notification

**Comment by NakulManchanda** [comment]
Still need to visit every Notification Type and details behind each one to design it properly!
 Verify by running queries in Database - what kind of subscriptions are stored for each!

**Comment by NakulManchanda** [comment]
Query to calculate stats:

```
```
WITH cte AS (
    SELECT 
        user_id,
        COUNT(*) as address_count
    FROM 
        "Addresses"
    GROUP BY 
        user_id
), cte2 AS (
    SELECT
        user_id,
        address_count,
        CAST(PERCENT_RANK() OVER (ORDER BY address_count) AS NUMERIC(5,2)) as rounded_percentile_rank
    FROM
        cte
), cte3 AS (
    SELECT 
        rounded_percentile_rank,
        COUNT(*) OVER (PARTITION BY rounded_percentile_rank) as user_count_in_percentile,
        CAST(MAX(address_count) OVER (PARTITION BY rounded_percentile_rank) AS INTEGER) as max_address_count,
        CAST(MIN(address_count) OVER (PARTITION BY rounded_percentile_rank) AS INTEGER) as min_address_count,
        CAST(AVG(address_count) OVER (PARTITION BY rounded_percentile_rank) AS INTEGER) as avg_address_count

    FROM cte2
)
SELECT DISTINCT 
    rounded_percentile_rank,
    user_count_in_percentile,
    max_address_count,
    min_address_count,
    avg_address_count
FROM cte3
ORDER BY rounded_percentile_rank;
```


```

**Comment by NakulManchanda** [comment]
NotificationRead - is not only read receipt
- its receipts for everything!
- delivery receipts - email etc!
- read receipts 

We probably still need them in some shape or form to not send duplicate Notifications!

**Comment by CowMuon** [comment]
There is a lot here, but honestly this really looks like throwing good queries after bad to use an expression. More to the point, such an approach seems palliative at best, and doesn't really align with our architectural direction, which is to get notifications out of sql, and into a proper event logging system. Let's circle back next week to discuss our plan to decouple notifications architecture from sql. In the meantime closing this (without prejudice tho.)

**Comment by CowMuon** [comment]
Thanks for catching that Jake.

**Comment by NakulManchanda** [comment]
Sorry, its not architecture direction
Its a thought experiment
- to see what we can eliminate eg. Notification Read (they are pretty useful though)
- how we can reduce fan out factor etc.

We can be more event driven architecturally - streaming/batch data pipeline
Basically, We have 10+ Notification Categories
- Each Category is a event stream 
    - no of unique stream (depends on only system data - Forum, ChainEvents etc)
    - unique id based on primary key can be assigned to composite key 
       - (Unique Notification Categories + topics, threads, comments etc - more granular more nested composite)
       - we also have parent-child relationships between events eg. Threads & comments - helps with rollup summary too
       - we also have priority
    - Every new chain/community & topic will add new stream
    - Mentions & Replies - are subscription events
  
- Notifications are **Events** 
- Subscriptions are (Fan Out) - to be kept in memory 
     - continuously changing as users leave/join, new topics get added, new comments, new replies, new mentions 
     - delta should be continuously calculated to refresh subscription
- Delivery - decided by subscriptions - 
   - if user online - deliver websocket
   - if user offline - fallback - choose all subscribed delivery methods 
- Message  - it belongs to user - only thing system know is his category
   - message should not contain granular keys just flat schema unique_delivery_id, data, user_id, not_cat_type
   - message will always be save for historical purposes
   - message archive - can be based on expiry rules for each notification category to filter out

**Comment by NakulManchanda** [comment]
@jnaviask @CowMuon 
Sorry, how is it un-planned ?
 - as we clearly decided on yesterday meeting to open a speculative ticket
  - We don't use Notion in Engineering, so I was asked to open an issue and mark it as speculative
How can it become un-planned overnight?

Also, its part of **Database Improvement Plan**
This is third major piece in our plan - where we did not made progress yet

We need to green light at-least one issue/design to make any progress!

> Thanks for catching that Jake.

**Comment by NakulManchanda** [comment]
> architecture direction

<img width="630" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/f8fa8453-07bd-412f-804d-2412adb07d81">

**Comment by NakulManchanda** [comment]
> Thanks for catching that Jake.

Please don't close things - which were discussed as not planned, or shut down conversation unilaterally!

**Comment by NakulManchanda** [comment]
>  Let's circle back next week to discuss our plan to decouple notifications architecture from sql. In the meantime closing this (without prejudice tho.)

Lets continue discussion next week.
Really interested in getting on same page and moving things forward for Notification Refactoring/Designing.
We need to actively talk through this - to build consensus - and to put up one actionable item on board.

**Comment by NakulManchanda** [comment]
At super high level event driven approach is:
- Notification will enter system
- Subscription service is a Transformer
       - primary responsibility to attach user_id for each notification 
       - (notification + user_id) --> message
       - Subscription service itself will update incrementally based on events
- Dispatcher could be a different system if we like

Notifications (Base events  + System events configured in system)
        |. 
        |. 
        | (Subscription Service - first updates itself + process each notification ).  
        |. 
       V
Messages Out (notification + user_id based on subscription)

**Comment by NakulManchanda** [comment]
Bottlenecks:
- in-memory fast updates of subscriptions can help us with bottleneck issues we have.

**Comment by NakulManchanda** [comment]
There is comment from @CowMuon based on today's meeting about offset based system:
- we can explore time ordered/ ordered UUID as event_id for tagging events
- can help filter out already delivered message

**Comment by NakulManchanda** [comment]
There is a very good documentation here: RabbitMQ vs Kafka
- https://www.cloudamqp.com/blog/when-to-use-rabbitmq-or-apache-kafka.html?utm_source=flipboard&utm_content=nakul1986%2Fmagazine%2FGithub+And+Programming

**Comment by NakulManchanda** [comment]
All this discussion was moved to total refactoring of whole system holistically, rather than single issue of removing NotificationsRead etc
https://github.com/hicommonwealth/commonwealth/wiki/Notifications
