### ISSUE TITLE
Can't Create Arbitrum Community 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4130]
Reported by user Big Dog Woof (Reproduced) 

# Issue: 
Unable to create a new ERC20 community on Arbitrum One. 

# Details: 
Valid ETH address but common is returning "Must provide valid contract address" 

# Reproduced? 
Mark was able to reproduce. 

# Severity? 
How many users are affected? 
How often is this happening? (only on create community, apparently only on Arbitrrum?) 

# Loom:
https://www.loom.com/share/ad0abe04663e447e885050195f3f1f8b

**Comment by CowMuon** [comment]
This may be limited to just this particular case, however we need potential new users and communities to see we can move swiftly to resolve newly discovered bugs.

**Comment by jnaviask** [comment]
Please share the address so we can reproduce the specific case.

**Comment by jnaviask** [comment]
@alexyoung23j please add points.

**Comment by alexyoung23j** [comment]
This is the result of some bad state management patterns, trying to find best way to fix.
