### ISSUE TITLE
Make deferred chain loading the default 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4136]
## Description
For historical reasons, app logic needs to load a chain when a user lands in a community, however this is a legacy from when a chain *was* a community. (Refactoring the app & db to fix chain <> community is a something that's been needed, and we hoping to have done this quarter.) 
It makes more sense to flip the script here, to make not loading the chain until needed the default, and in doing so remove/clean up the deferral logic which is just adding to the mess in layout.tsx, and eliminate the need for hacky redirects, such as have been added to the app both historically, and even recently with the [fix](https://github.com/hicommonwealth/commonwealth/pull/4084) for routes [that promiscuously load unnecessary chain data](https://github.com/hicommonwealth/commonwealth/issues/4064).

## Engineering Requirements
On Friday we said we would have a call today (6/5, 1300hr ET) to decide whether to do this, however we would like to go ahead and  implement this, and then use our call this afternoon to review, and hopefully get merged today. 

## Acceptance Criteria
Switching between communities should not load chain data by default, unless actually required for what  page  the user has navigated to is doing (which can/should also be pre-loaded, but that's another story.)

**Comment by ianrowan** [comment]
Trying to scope this out. Is it as simple as creating `requireChain` logic that follows the reverse of the existing logic? : 
```
if (app.chain?.meta.type === ChainType.Token) {
    return true; //changed from false for defer chain
  }
``` 
and then propagating throughout the usage

And then second, the param for deferredChain that is used if not a Token will this be changed to requireChain as well or Removed to use the ChainType Token logic? If changed, I'm still in the process of investigating where/when this param is passed/used but on will that also require some logic changes, ie how a page sets this param? 

@jnaviask @CowMuon

**Comment by jnaviask** [comment]
> Trying to scope this out. Is it as simple as creating requireChain logic that follows the reverse of the existing logic?

Yep, should be.

The general goal of the ticket is _only load Chain data on pages that require it_. We can do this by inverting the param at the router level, or by removing it altogether and producing a direct dependency of some pages on the Chain Adapter.

So, the question then re ChainType.Token is, where do we use the Chain data for token communities, and how? It may be for TBC support, which doesn't actually require chain data, so we may even be able to remove that check altogether.

**Comment by ianrowan** [comment]
@jnaviask thanks. I can see the usage of deferChain at the router level now. Is it in the scope of this ticket to determine which routes should and shouldnt load chain? 

Currently many routes do not use the `deferChain` params which means they are loading chain data. After this change either all of those would need to start passing a true value or we'd have to granularly determine which routes dont need chain which are currently defaulting to using it. 

Mainly trying to understand if this is part of the ticket or if we are just doing the basic logic flip.

**Comment by ianrowan** [comment]
@jnaviask learning more here about chain Initialization. Wanted to check if this was expected or an exising bug. 

Existing code always calls `SelectChain` When switching or loading a communitiy(s)
<img width="699" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/92e4e52a-a54a-4633-a7da-b71f675b1bc8">

Whether defer/useChain is set or not, data is always loaded from the server for the chain it appears: 
https://github.com/hicommonwealth/commonwealth/blob/6b7da0572eae7a64325a3ea0f19005ff8deacc62/packages/commonwealth/client/scripts/helpers/chain.ts#L184

This happens whether deferChain is set or not. then deferChain controls if we `initChain` Which appears to just create RPC/api connections etc. Is the purpose of defer supposed to defer all loading of chain data or just creating an API connection(ie `initChain` but still allow `initServer`)? 

If this is the case(we just want to avoid init-ing the API) every route works with useChain = false from testing so far...

**Comment by ianrowan** [comment]
@jnaviask removing all deferChain = false(ie use chain) paths seems to work everywhere(ie never initChain on layout) I typically test. Am I missing something or do we never need to initChain on Layout, other logic appears to handle it where needed(ie when going to proposals page)?

**Comment by jnaviask** [comment]
@ianrowan deferChain controls when initData() gets called, initServer() is always called. We may have accidentally removed all cases where we even need to initChain, if (a) proposals pages, and (b) new proposals use other means to initialize blockchain data... This would be kind of incredible if it is the case.

**Comment by ianrowan** [comment]
@jnaviask With all initData/Chain on layout removed(all references and paths to deferChain) I tested: 
1. Loading multiple communities(cosmos, evm, non-token) 
2. Creating Threads + TBC gating
3. Loading snapshots
4. Loading On-chain proposals Page for EVM and Cosmos 
5. linking/loading to linking modal onchain proposals

And all worked as I'd expect(seeing rpc connections, etc happening in console when navigating to those pages)

**Comment by jnaviask** [comment]
@ianrowan to be clear -- do we only establish RPC connections when needed? Because we need to ensure we're NOT establishing RPC connections on e.g. the threads page.

**Comment by ianrowan** [comment]
@jnaviask Just added a log to both InitAPI and InitData - No sign of them on any page but proposals ie No it does not look like RPC or InitData is called on threads by default/with defer logic removed

**Comment by jnaviask** [comment]
@ianrowan awesome. In that case, we can rip out deferChain entirely (never load chain data automatically)! Feel free to put up a draft PR and we'll test it out.
