### ISSUE TITLE
Keplr 2.0 seems to be breaking Evmos community login

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4140]
## Description
Evmos login with keplr fails on `verifyAddress`. This is due to a breaking change in `signEthereum` method.

>BREAKING CHANGE: When EthSignType.TRANSACTION, it returned signed tx. However, since all other sign types return signature, it has been changed to return signature rather than signed tx to ensure the same usability as other sign types.

## Engineering Requirements

- Handle the signEthereum breaking changes so that verifyAddress gets the right data to verify
- 

## Acceptance Criteria

I can login to evmos with keplr

**Comment by jnaviask** [comment]
Problem is on Keplr side: https://github.com/chainapsis/keplr-wallet/blob/master/packages/provider/src/core.ts#L298

Seems they did not implement ethereum signing support that Evmos depended on in Keplr v1. Not something we can fix.

**Comment by mhagel** [comment]
Reopening. Keplr 2.0 has enabled signEthereum with a breaking change.
https://github.com/chainapsis/keplr-wallet/issues/736#issuecomment-1582514722

>Remember that EthSignType.TRANSACTION returns not signed tx but signature from now.

**Comment by mhagel** [comment]
Getting an address mismatch here, not sure why yet:

```
  } else if (
    chain.base === ChainBase.CosmosSDK &&
    (addressModel.wallet_id === WalletId.CosmosEvmMetamask ||
      addressModel.wallet_id === WalletId.KeplrEthereum)
  ) {
    //
    // ethereum address handling on cosmos chains via metamask
    //
    const msgBuffer = Buffer.from(sortedStringify(canvasMessage));

    // toBuffer() doesn't work if there is a newline
    const msgHash = ethUtil.hashPersonalMessage(msgBuffer);
    const ethSignatureParams = ethUtil.fromRpcSig(signatureString.trim());
    const publicKey = ethUtil.ecrecover(
      msgHash,
      ethSignatureParams.v,
      ethSignatureParams.r,
      ethSignatureParams.s
    );

    const addressBuffer = ethUtil.publicToAddress(publicKey);
    const lowercaseAddress = ethUtil.bufferToHex(addressBuffer);
    try {
      // const ethAddress = Web3.utils.toChecksumAddress(lowercaseAddress);
      const b32AddrBuf = ethUtil.Address.fromString(
        lowercaseAddress.toString()
      ).toBuffer();
      const b32Address = bech32.encode(
        chain.bech32_prefix,
        bech32.toWords(b32AddrBuf)
      );
      // TODO: address mismatch here
      if (addressModel.address === b32Address) isValid = true;
    } catch (e) {
      isValid = false;
    }
```

**Comment by mhagel** [comment]
It looks like the mentioned breaking change doesn't affect login because we use EthSignType.MESSAGE, not TRANSACTION.

However, the address mismatch shows that the way we validate evmos addresses does not match the expected way evmos bech32 addresses are generated. 

I think we may need to handle `WalletId.KeplrEthereum` in a separate code block and duplicate however Evmos is generating addresses..

cc @ianrowan

**Comment by mhagel** [comment]
At the moment I still think this is an error from keplr. Since these addresses matched before 2.0, there is no reason to think our validation is wrong in `verifyAddress`. I pinged the keplr team for clarification.

@jnaviask

**Comment by mhagel** [comment]
>However, in Brave, I am seeing a "Blocked by client" error. Something is quietly failing.

This was remedied with a fresh tab for me.

**Comment by jnaviask** [comment]
Great, marking this closed.
