### ISSUE TITLE
Create metamask mock for e2e tests

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4149]
## Description
Required to get #4148 off the ground -- we need a way to mock Metamask's various calls, so we can "log in" a user as part of automatic testing.

## Engineering Requirements
- Expose a helper for e2e tests that logs in a user using the test infra (i.e. injects the metamask provider, then performs the clicks necessary).
- Write a simple test that verifies login is successful using the helper.

**Comment by ianrowan** [comment]
Moving this to a 3 as the recreation of metamasks eth_signedTypedData_v4 is going to take some research effort and building

**Comment by ianrowan** [comment]
Additionally it looks like building a chromium extension might be a choice. The tough part here is the access extensions and chrome are given to inject things into the browser context. 

As far as playwright, the ability to do this is limited by the browser itself. So building the metamask-like provider into something like an extension might be more straightforward(if the chromium extension process is in general)

**Comment by ianrowan** [comment]
Now that we're moving forward with the app code approach, a few things to wrap this up.

1. Do we have an ETH RPC we can use for our provider. The alchemy provider does not have localhost on the whitelist so it currently doesnt work(I was testing with my personal infura before these final steps)?

2. Ok to use the existing ETH_RPC env var which currently toggles ability to use test net for this with the condition `ETH_RPC=e2e-test` as the on flag. If so, as mentioned where should I document(packages/commonwealth README?)
