### ISSUE TITLE
File uploads broken due to Quill 2.0

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#415]

**Comment by raykyri** [comment]
Is this in progress? It seems lower priority than some of the other requests - I'll move it back to Backlog for now, but feel free to move back if it's already WIP

**Comment by gdjohnson** [comment]
Alright I'm finally biting this off

**Comment by raykyri** [comment]
If you can document the different cases and status of each, that would be a nice place to start
