### ISSUE TITLE
Better Forms

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#4150]
## Description

Taking the example of the community starter form, ATM this is how we show field related errors
<details>
<summary>Video/Screenshot</summary>

https://github.com/hicommonwealth/commonwealth/assets/51641047/aa126e9b-7572-4f22-9819-14ca087f9d43

<img width="1277" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/317ee759-7e4a-4a78-952c-9cb98c67d8ff">

</details>

What we are doing here is to manually show the field error after the form submits and gets error data from the api. The difference here is how we validate data for its completeness (this should be on both the api and frontend) and how we make sure it is accurate (that is on the api side)

In the code we have state values to handle each changing field which gets redundant overtime (extra boilerplate)

https://github.com/hicommonwealth/commonwealth/blob/b7bda5423314e4c0fbe186047113e494b7916031/packages/commonwealth/client/scripts/views/pages/create_community/starter_community_form.tsx#L39-L55

Some problems here are 

- UX inconsistency (we can show field related error along with the field)
- More boilerplate (managing each field state separately)
- No proper data validation on frontend

We can use a form library along with a data validation library to accurately validate form, remove ux in-consistency and reduce a lot of boilerplate. Some good options
- [React hook form](https://www.react-hook-form.com/) - Form library
- [Joi](https://www.npmjs.com/package/joi) or [Zod](https://www.npmjs.com/package/zod) - Data validation library

React hook form provides consumption hooks (like https://react-hook-form.com/docs/useform and https://react-hook-form.com/docs/useformcontext) for deeply nested form field that are in the same context.

So we can imagine a usage like this

```jsx
<Form
  // the data from onSubmit will be validated by the joi/zod schema
  // so we can just fire and forget (on error we will have to show
  // which we can directly acess without much boilerplate since we
  // will be using react query)
  onSubmit={makeApiCall}
  // this is something we have to get from joi/zoi, lets say this is our schema
  // const formValidationSchema = Joi.object().keys({
  //     email: Joi.string().email().required(),
  //     phone: Joi.string().regex(/^\d{3}-\d{3}-\d{4}$/).required(),
  //     birthday: Joi.date().max('1-1-2004').iso()
  // });
  validationSchema={formValidationSchema}
>
    {/* The name for input will map to the validation schema and this field will
    be validated according to whats there in the schema, any field error will be 
    automatically shown for this field in its component, we wont have to manually
    render it */}
    <Input name="email"/>
    
    <Input name="phone"/>

    <Input name="birthday"/>

    {/* here we can decide to show any error that are not related to any specific 
    field, like an api error or a permissions error */}

    {/* on click of any type="submit" button the form will automatically submit */}
    <Button type="submit">Submit</Button>
</Form>;
```

## Engineering Requirements
- Make a `Form` component that uses [useForm](https://react-hook-form.com/docs/useform) hook from react query and provides a form context to the nested fields
- Update the `Input` component to listen to this form context if nested inside a form by the [useFormContext](https://react-hook-form.com/docs/useformcontext) hook and render validation messages or any other states that the form can potentially show.
- Update a single form to use the new form component (as a demo/guideline of how we move forward with this).

## Acceptance Criteria
Same points as engineering requirements plus 
- At the end any form should just look like this (notice there is no react state we are managing here).

```jsx
<Form
  onSubmit={the function that calls the api here}
  validationSchema={formValidationSchema}
>
    <Input name="{field name here}"/>
    {/* ... other fields */}

    {/* here we can decide to show any error that are not related to any specific 
    field, like an api error or a permissions error */}

    <Button type="submit">Submit</Button>
</Form>;
```
- The field specific errors are shown with the field
- No react state is used
- Properly validated data is sent to api
- Api errors are shown separately from field errors

**Comment by jnaviask** [comment]
cc @MuonShot, would love to hear your thoughts on the above approach to form handling before moving ahead.

**Comment by masvelio** [comment]
Our current way of handling form is indeed miserable. The standard way in react world is using react-hook-form and joi/zod, as @mzparacha rightly mentioned in the description. I believe that Gating could be nice place to start using new approach as there will be quite a lot of form-related work

**Comment by jnaviask** [comment]
@masvelio sounds good to me (react-hook-form for gating forms). Would love to learn more about the different resolvers supported by react-hook-form so we can pick the best one for our needs.

**Comment by mzparacha** [comment]
> Would love to learn more about the different resolvers supported by react-hook-form so we can pick the best one for our needs.

I believe most of our needs would be basic form field validation, there will be instances where input controls (tag-input / dynamic forms) will be needed.

The react-hook-form supports [many resolvers](https://github.com/react-hook-form/resolvers), **Yup**, **Zod**, and **Joi** seem to be the most famous ones. 

From what I can tell, Zod seems to be more type-oriented (typescript). Joi on the other hand is more customizable (custom validations) and has a powerful ecosystem (plugins). 

I think Joi is a better option given the customizability and the ecosystem. But curious about @masvelio thoughts.

cc: @jnaviask @masvelio

**Comment by masvelio** [comment]
I used to work with Joi on JS projects and it was fine, but I remember there were some issues with typescript projects that were frustrating. Heard a lot of good things about Zod and it works perfectly with typescript so I would go more into Zod direction. Whatever we picks, it should help us solve problems and make our life easier, not adding more problems, so probably it would need more investigation which way we should go.

**Comment by CowMuon** [comment]
Joi is more of a nodejs tool; Zod is more of a ts tool. (imo) +1 to Malik's suggestion to go in later direction.

**Comment by mzparacha** [comment]
It looks like we are aligning more towards Zod. I think the next step here is to decide the next steps. 

For starters, I think we would be creating the `Form` and updating current input controls to support the 'Better Forms' approach. From then, I see 2 approaches (maybe there are more)

1. Upgrade all existing Forms (pre-gating) in the app with the new Form approach
2. Follow an incremental approach, based on priority. I believe gating would be a priority, so we can use the 'Better Forms' there and later incrementally migrate the other forms.

Just brainstorming above. Thoughts on this?

cc: @jnaviask @CowMuon @masvelio

**Comment by jnaviask** [comment]
@mzparacha Incremental is definitely the way to go! Gating would be a fantastic first choice, and then we can move to create community page, which has a ton of form elements as well + is due for an overhaul.

**Comment by mzparacha** [comment]
Cool, so I will take on this ticket and implement the new `Form` component and add react-hook-forms composition API in existing form controls, for now only `Input` / `Checkbox`, also adding 3 point label.

I will start on this soon after some other tickets.

cc: @jnaviask @masvelio @CowMuon
