### ISSUE TITLE
Restore Topic Title to recent threads header

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4155]
## Description
For some reason we lost the topic title on all threads pages except "All Discussions":
![image](https://github.com/hicommonwealth/commonwealth/assets/1860629/4f30126b-9eec-4052-ba97-cf817ebaa805)
vs
![image](https://github.com/hicommonwealth/commonwealth/assets/1860629/c7667811-a729-4270-9b8a-0b0415cd82f8)

## Acceptance Criteria

- Topic Title should show on all topic pages.

**Comment by mzparacha** [comment]
@zakhap i updated it to be like this, Please let me know if it looks good?

![image](https://github.com/hicommonwealth/commonwealth/assets/51641047/fbc6c63f-5ec7-4701-b4cf-df814254429d)
