### ISSUE TITLE
Improve /ActiveThreads || Image Compression

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4158]
## Description

**Probably requires more engineering spec'ing.**
Based on a cursory dive on /activeThreads response, it seems like images are the biggest issue. 

Todo: 
- [ ] Compress images 
  - [ ] Avatars

Possible Todos @jnaviask to confirm feasibility: 
- [ ] delay image loading until /viewThread

## Acceptance Criteria

- Reduced latency / Increased Speed in /activeThreads
  - Reduce variability in /activeThreads across different communities.

**Comment by jnaviask** [comment]
What does the active threads route have anything to do with image loading?

**Comment by CowMuon** [comment]
Depends on #4238 (so, blocked until that story is completed.)

**Comment by jnaviask** [comment]
Scope unclear.
