### ISSUE TITLE
Only unread notifications in notifications dropdown

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4161]
## Description

- As a user I should only see unread notifications on the notifications dropdown. Once a notification has been marked as read in the notification dropdown, it should disappear from the dropdown
- As a user I should be able to go to the notifications page to see all my notifications (both read and unread). The notifications history should go back up to 30 days of notifications. 

## Acceptance Criteria
- Users of Common should be able to see all their unread notifications on the notifications dropdown and all the read notifications should disappear

**Comment by timolegros** [comment]
This issue is not possible if we move forward with #4308

**Comment by jnaviask** [comment]
No longer relevant per Tim's comment.
