### ISSUE TITLE
Improve Token Balance Cache error reporting 

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4163]
## Description
Currently we get errors from the TBC like `Balance query failed` with no additional information (e.g. /apeswap). We want to instead be able to understand what's going on when a balance query fails, without necessarily leaking that info to the client. Granular server-side error logging seems like the proper way to go about this.

## Engineering Requirements

- The TBC should log errors with enough detail to diagnose root cause when a balance query fails.

**Comment by timolegros** [comment]
Changes are implemented just needs client-side testing.

**Comment by timolegros** [comment]
Did some preliminary testing (what I've tested so far replicates behavior on master) but I'm not entirely sure what the actual desired behavior is for some edge cases (or if there are known bugs) so I've reached out to people who may know and am waiting on responses.

**Comment by timolegros** [comment]
Reverted the PR to draft as some of the user errors on specific routes for insufficient balance are reporting as 500 errors instead of 400 errors.

**Comment by CowMuon** [comment]
Will hopefully merge on Monday depending how review goes.
