### ISSUE TITLE
Notifications history and pagination on notifications page

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4164]
## Description
- As a user I should be able to paginate through the notifications page
- As a user I should be able to view the history of my read notifications for up to 30 days. 
- Any notifications over 30 days should get deleted 

## Acceptance Criteria
- Users of Common should be able to navigate to the notifications page and paginate through their notifications 
- Users of Common should be able to see the notifications history up to 30 days

**Comment by zakhap** [comment]
related: #3438

**Comment by timolegros** [comment]
@jnaviask @zakhap Same thing here about stalling until the legacy notifications system milestone is complete. See my comment [here][1].

[1]: https://github.com/hicommonwealth/commonwealth/issues/4162#issuecomment-1629803210

**Comment by ForestMars** [comment]
> As a user I should be able to paginate through the notifications page

Wunderbar. 

> As a user I should be able to view the history of my read notifications for up to 30 days.
> Any notifications over 30 days should get deleted

Confirming this means all notifications read and unread are deleted after 30 days. 

Does the user have the option of deleting the notifications? If so, does that send them to a recycle area for 30 days? @sachben91

**Comment by timolegros** [comment]
@ForestMars this ticket shouldn't be worked on right now (at least not in its current state). Notification fetching + pagination and read history will all be managed with Courier SDK. Will be able to update the ticket after the Courier prototype.

**Comment by dillchen** [comment]
Just wanna note @burtonator , and @timolegros , correct me if I'm wrong #7610 should power this feed

**Comment by timolegros** [comment]
> Just wanna note @burtonator , and @timolegros , correct me if I'm wrong, #7610 should power this feed

Indeed it will

**Comment by burtonator** [comment]
@dillchen @timolegros This is implemented already per knock so once we switch to knock this is resolved.
