### ISSUE TITLE
Update ToS

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4166]
## Description
- Update the current ToS page to [this](https://docs.google.com/document/d/1H5ApinU55_1H1_6-j06CQaE6MRH3YdBe/edit#)
- Move existing ToS to a new page (/tos-[date of previous implementation], and create link where applicable directly in the new TOS
- Upload a PDF version to the new ToS and link within the document

## Engineering Requirements

- The Widget route should return a TODO response.
-

**Comment by alexyoung23j** [comment]
Hm can you give page access to alex@common.xyz

**Comment by jnaviask** [comment]
Reverted PR because slug size increased by 50 MB. Need to come up with a solution that doesn't cause massive increase in dependency size.
