### ISSUE TITLE
Allow users to sort comments by recency

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4170]
## Description

# Design Solution | Sort Comments - Part 1

### Summary of solution and design (UX/UI) requirements

Adding the ability to sort comments by Oldest or Newest.

<img width="654" alt="Screen Shot 2023-06-01 at 10 45 27 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/28fbdee2-5481-4f96-bf3a-79dbd2e9a24e">

**Design specifications**

- Sort
    - Sort & Filter copy: Body 02/Medium
    - Spacing between sort copy and the dropdown component is 16px
    - Dropdown button / Compact: Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page '[🟢Dropdowns](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=340%3A6230&t=p9g3PLNJMHlx7Oaq-1)'
    - Note: This dropdown is a compact (smaller) version of the dropdown created for 'Sort and Filter on the thread listing page'. It is a new component that would need to be created. Please  escalate to design if the design specifications and resources in this docs are not sufficient to complete this task! Says Jess, the designer!
    
        
       <img width="1145" alt="Screen Shot 2023-06-01 at 9 53 22 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/698e8d6c-c424-4cb0-9418-c9ceb9394358">
        

**Sort categories**

- Oldest (default)
    - Ordered by oldest to newest threads.
- Newest
    - Ordered by newest thread to oldest. Edited comments or replies are ordered by their original date for now.

**Comment Settings**

<img width="609" alt="Screen Shot 2023-06-01 at 10 45 37 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/14255e2a-f189-4fb1-8a20-5fbd1ab4ea06">

- The Sort comments dropdown button and the Spam check box should be align center, not top or bottom aligned.

**Handoff resources**
- Figma masterfile: [Forum Improvements - Part 2](https://www.figma.com/file/wt6LJdgoupZvhgOiGrn0JZ/Forum-Improvements---Part-2?type=design&node-id=314%3A33488&t=MC2to4I4Ukop2bWr-1)
- Figma prototype: [Forum Improvements - Part 2
](https://www.figma.com/file/wt6LJdgoupZvhgOiGrn0JZ/Forum-Improvements---Part-2?type=design&node-id=314%3A33488&t=MC2to4I4Ukop2bWr-1)
- Loom Prototype walkthrough: [Sort Comments - Part 1](https://www.figma.com/file/wt6LJdgoupZvhgOiGrn0JZ/Forum-Improvements---Part-2?type=design&node-id=314%3A33488&t=MC2to4I4Ukop2bWr-1)

## Acceptance Criteria

- As a user, I want to sort comment by newest or oldest.

<img width="634" alt="Screen Shot 2023-06-08 at 10 40 30 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/f4ad7799-813c-439e-9967-19a06f1cf61d">

**Comment by jnaviask** [comment]
@mzparacha discussed with Zak: only sort by top level comment age, you can ignore the nested reply age.

**Comment by mzparacha** [comment]
@jnaviask can i use https://github.com/hicommonwealth/commonwealth/pull/4065 as a base branch for this ticket?

**Comment by CowMuon** [comment]
@mzparacha In general, we try to avoid using another branch as base for a different feature branch. In this case #4065 was blocked pending design review, so my preference here would be complete work on #4065 as I see [Jessica updated her comment](https://github.com/hicommonwealth/commonwealth/issues/3977#issuecomment-1587933441); when that PR is ready to go, we will either merge it with priority, or revisit using as base branch here, if you would otherwise be blocked until it gets merged. Does that make sense?

**Comment by mzparacha** [comment]
Sounds good, Thanks @CowMuon

**Comment by mzparacha** [comment]
> is sorting by most upvoted out of scope (which is available within Sort Threads) ? is there a reason it wasn't included in the ticket? (I don't have PRD in front of me for reference)

If you mean comment sorting by vote, I didn't knew it was out of scope. So maybe this ticket was created for that reason (not sure)

**Comment by zakhap** [comment]
@jessmart1213 

Above, @dillchen asked if Sorting by Most Upvoted comment was out of scope. It is not included in the PRD or Design document, however, I think it is a good suggestion. Being that the logic is trivial to develop, do you think adding a 3rd option to the sort by dropdown is acceptable? If so, the copy and icon need to be provided.

**Comment by jessmart1213** [comment]
Phase 1 of Sort Comments was to introduce the sort dropdown to our product with sort options: Newest and Oldest. 

Phase 2 of Sort Comments is to introduce sort by Popular.

If we want to include sort by most upvoted, we can do so, but it needs to go through the design process.

**Comment by dillchen** [comment]
That’s all fine with me, didn’t have the context in front of me. Thank you
for this, no other questions, consider my comment resolved

Sent via Superhuman iOS ***@***.***>

**Comment by mzparacha** [comment]
I took #4065 as base (as it had some relevant changes) and implemented this feature on that local branch. The current status is its done but i am not sure if i should make a PR as per [this comment](https://github.com/hicommonwealth/commonwealth/issues/4170#issuecomment-1589452267). 

cc: @CowMuon

**Comment by CowMuon** [comment]
Yes please rebase if needed and submit the branch in a PR

**Comment by jessmart1213** [comment]
I was told in refinement that this ticket is ready for Design QA, though I don't see a Design QA tag? 

Either way, here is my Design QA feedback. 

### Design QA Feedback

SPACING 
- Increase the total spacing between the metadata container (with the avatar and displayname) on the Comments component and the Comment Setting container (with the sort dropdown and spam checkbox) to 40px.
   <img width="427" alt="Screen Shot 2023-06-26 at 2 00 14 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/3191d06c-81e9-4f7d-872c-1cd28afbb006">

- Please see loom video below for more context.

DROPDOWN STATES
- This is design system level change. Should be applied to the regular and compact dropdown component.
- Update on hover and on click states to match those set in the Design System, [🟢 Dropdowns](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=1%3A49&mode=design&t=ysrU3yZzey2lVCUo-1)
 
  <img width="437" alt="Screen Shot 2023-06-26 at 2 03 28 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/fe5691b0-4cbb-4742-9e3b-94b71034b5f5">

FONT :no_entry_sign:
- Noting font issues as good practice, but issue is to be resolved in another work-stream that is handling current font weight and alignment issues. 
- Font weight is heavier than design specifications.
- Font is not middle aligned. 

Resources
- [Loom Design QA](https://www.loom.com/share/1c57551ee3d1452da84741c706a1307a?sid=d046a7ad-4896-40de-872e-2f3aea03aace)

**Comment by mzparacha** [comment]
Thanks for the review @jessmart1213. I made a new [PR](https://github.com/hicommonwealth/commonwealth/pull/4348) with the required changes as the existing one was already merged. 

> Noting font issues as good practice, but issue is to be resolved in another work-stream that is handling current font weight and alignment issues.
Font weight is heavier than design specifications.

I did not fixed/updated fonts styles here as the whole app got a heavy font after some pr (don't know which one) - again as you said it is in another work-stream

Please feel free to let me know if any issues. Thank you!
