### ISSUE TITLE
Cosmos Gov V1: Display Title/Description from metadata

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4184]
In gov module v1, there is a metadata field that can optionally be used to display proposal content.

Kyve, for example, has stored this as a url to an IPFS-stored file. In more recent proposals, this is the only source of title and content.

AC:

- Load and display metadata.title as main proposal title when it is available (and top-level title is not)
- Investigate if there is a standardized schema for metadata. 
    - If so, use this to display proposal description

Further Consideration (possible separate ticket):
- We may want to display the full metadata object, as Kyve does in their native view: https://app.kyve.network/#/governance/6. 
    - This would require a new design 
- Be conscious that not all cases will use IPFS. This metadata IRI could reference anything.

**Comment by jnaviask** [comment]
cc @mhagel to add point value
