### ISSUE TITLE
Cosmos Gov V1: Display all metadata

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4187]
Follow-up to #4184

Show the entire metadata object fetched from the proposal.metadata IRI

See https://app.kyve.network/#/governance/6

Requires design review

**Comment by mhagel** [comment]
@jnaviask Adding this as an optional feature. Feel free to change ticket details.

**Comment by zakhap** [comment]
@mhagel What's the Product/Design ask here? Does this need a mock of what the proposal card should look like?
