### ISSUE TITLE
Render sublayout/sidebar before main content loaded

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4196]
## Description

Currently all site content blocks on fetching of content. #4159 takes a step forward by rendering the layout before the content loads. However we can do better, by rendering topics etc (whatever is available post /bulkOffchain) before the main body.

**Comment by mzparacha** [comment]
Me and @jnaviask discussed to also move all the <SubLayout> and move it to <Layout>. These are the proposed changes

- `<Layout type=“community”/>` - header with sidebar and community sidebar - this is the most used layout
- `<Layout type=“default”/>` - header and sidebar - this is used in pages like terms/conditions etc (2nd most used layout)
- `<Layout type=“blank”/>` - a blank screen, no header footer or sidebar - this is only shown in the landing page (3rd most used layout)

we can make these 3 layout types and pass the `type`  prop from router file and chop <SubLayout> from all pages which is mostly just used a wrapper tag. This way we will have slightly reduced code and components will actually be doing their job like `<Layout>` will then be actually doing proper layout etc etc.

This is not a big change actually, and we can then “not drill” the `isAppLoading` prop along with having a centralized layout (which would be helpful in future usecases)

**Comment by CowMuon** [comment]
Not a big change, true, but tbh, hugely impactful. It's great to see we will actually be using layout.tsx for, um, layout, rather than tryna make it into a pseudo-router. +1 LFG!
