### ISSUE TITLE
🪣 Comments Overhaul Bucket

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4217]
## Description

# Design Solution | Comments Nesting Overhaul - Part 1

Last updated by @Jessica  Martinez  on June 12, 2023 

## Summary of solution and design (UX/UI) requirements

The goal for Part 1 in improving the overall experience of Common’s Comments and Reply Nesting features is to improve the UI and information architecture of the comment and reply component first. Part 2 will cover more improvements that focus on the nesting functionality of comments and replies. 

**READ ME**

The new comment and reply component is similar to the one currently implemented. This means the task in  the details of spacing, padding, overall sizing, fonts, colors, and behaviors.

---

## Parent Components

<img width="753" alt="Screen Shot 2023-06-12 at 12 32 15 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/a0579d5f-27ef-4582-b930-30b942b48068">

## Child Components

- [x] #4240
- [ ] #4218

**Definitions**

- Comment: comments are responses to the thread / post.
- Replies:  replies are responses to the comments or other replies.

### Redlining

<img width="728" alt="Screen Shot 2023-06-12 at 12 32 39 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/909f5c5b-f257-4db0-a2cc-bebe3667f5f5">

## Breakpoints

<img width="1423" alt="Screen Shot 2023-06-12 at 12 41 32 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/537993b3-e54c-48f9-9ede-5c06ac56da18">

## Resources
- Notion doc: [Design Solution | Comments Nesting Overhaul - Part 1](https://www.notion.so/buildcommon/Design-Solution-Comments-Nesting-Overhaul-Part-1-73ab320749664978a6767e56338ca2c8?pvs=4)
- Figma masterfile: [Forum Improvements - Part 3 - Comments and Replies](https://www.figma.com/file/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?type=design&node-id=1%3A3&t=vZzHaHoJLF3Hf5Ot-1)
- Figma prototype: Forum Improvements - [Part 3 - Comments and Replies](https://www.figma.com/proto/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?page-id=1%3A3&type=design&node-id=233-34775&viewport=274%2C-400%2C0.06&scaling=scale-down&starting-point-node-id=233%3A34775)
- Loom walkthrough(s): [User Types](https://www.loom.com/share/479c63f9acfe444db59f67eeaee2b555?sid=3a65a029-27b6-4112-9288-0a301a7cb32a) and [Comment and reply component
](https://www.loom.com/share/591330cbd9b84dd499d3d2cd6cee0064?sid=9f7302ad-f9ac-4395-a643-f682b09bfe15)

---

## Engineering Requirements

- The Widget route should return a TODO response.
-

**Comment by jnaviask** [comment]
Deprecating this bucket, as its related work is tracked by #4607 #4608 and #4609.
