### ISSUE TITLE
Comments Overhaul: Comment and Reply body

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4218]
_This is a sub-ticket of [Comments Overhaul Bucket](https://github.com/hicommonwealth/commonwealth/issues/4217#issue-1753645653). Please see parent ticket for more context and notion, figma, and loom resources._ 

## div.Thread-nestedline-body-footer**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/28f01807-910c-4df3-a2b2-fdb6d9ca3930)

Parent container to the following containers and components. 

- Nest line container
- div.thread body and footer

### Nest line container

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/8edfc5eb-13d8-41e0-bd50-0961f7f57bd4)

- Design specifications
    - Line
        - Width: 1 px
        - Height: Fills container
        - Color: Neutrals/200 or #E6E5E7
        - Aligned center
    - Container
        - Width: 24px
        - Height: Fills parent container, div.thread-nested line-body-footer
- Behaviors
    - Line is not visible on Comments.
    - Line is visible on Replies.

### div.thread body and footer

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/2183cc40-e452-4dd0-98f0-fe75ac5d9758)

Parent container to the following containers and components. 

- Content
- div.thread-footer-row

### Content

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/a4ef9698-1d26-49ea-8545-e2d05845ffb6)

- Design specifications
    - Element: text
    - Font: Body 1 / Regular

### div.thread-footer-row

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/56025843-67af-4a83-95d1-6344baf9a699)

- Parent container to the following containers and components.
    - Actions left

### Actions Left

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/cb14a05f-a17e-4748-9118-ee7e7c9afc3f)

- Design specifications
    - Made up of upvote cta, reply cta, share cta, and overflow cta
    - 0 px spacing between ctas

### Upvote CTA

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/7ab55e61-95f9-4c62-beb8-f94c99bb01a0)

- Design specifications
    - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Thread Actions ](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707%3A11225&t=u5CFzuhG1mHd7e8K-1) and look for Upvote.
- Behaviors
    - Users can only upvote a comment or reply once.
    - First click on the ‘Upvote CTA’ is an upvote. Second click on the ‘Upvote CTA’ undoes the upvote.

**Reply CTA**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/d9e71de4-dbc0-4314-aba0-2825209cfdb7)

- Design specifications
    - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Thread Actions ](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707%3A11225&t=u5CFzuhG1mHd7e8K-1) and look for Reply.
- Behaviors
    - Reply CTA triggers editors to appear. Should function as currently implemented.

**Share CTA**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/a7156e69-5e9c-4340-b216-ed9935ba35bb)

- Design specifications
    - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Thread Actions ](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707%3A11225&t=u5CFzuhG1mHd7e8K-1) and look for Share.
- Behaviors
    - On click, share popover is triggered. Should function as currently implemented.

**Share popover**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/afeada9a-6bc4-4411-967a-d952d1283bda)

- Design specifications
    - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Dropdowns](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=336%3A9952&t=u5CFzuhG1mHd7e8K-1)' and look for Compact Dropdown menu.
    - Phosphor icons used: Link, TwitterLogo
    - Update ‘Copy URL’ copy to ‘Copy link’.
- Behaviors
    - Should function as currently implemented.

**Overflow CTA**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/8a8857cd-75f7-4c59-9ea7-764ba172b30b)

- Design specifications
    - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Thread Actions ](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707%3A11225&t=u5CFzuhG1mHd7e8K-1) and look for Overflow.
    - Phosphor icons used: DotsThree
- Behaviors
    - On click, overflow popover is triggered.

**Overflow Popover**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/d018d2c9-789c-45fc-bfad-404806b10fde)

- Design specifications
    - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Dropdowns](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=336%3A9952&t=u5CFzuhG1mHd7e8K-1)' and look for Compact Dropdown menu.
    - Icons used: NotePencil, LockKey, Trash, ArchiveTray, Flag
- Behaviors
    - If the user is not the author of the comment or reply and is not an admin of that community, then the ‘Overflow CTA’ does not appear.
    - If the user is the author of the comment or reply and is not the an admin of that community, then the ‘author popover’ is triggered.
    - If the user is not the author of the comment or reply and is the an admin of that community, then the ‘admin popover’ is triggered.
    - If the user is the author of the comment or reply and is the an admin of that community, then the ‘admin + author popover’ is triggered.

**Comment by jnaviask** [comment]
Superseded by #4608
