### ISSUE TITLE
Use Skeleton Loader for Governance Pages

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4219]
## Description
As a follow-up to #4197, mentioned here:

Improve the loading state of governance pages by loading the header (which we should always have) and using SkeletonPages for each as the loading state. This will provide a better user experience since threads will appear to populate, rather than the entire component loading at once. Apply this approach across all pages when initializing is done and update the design accordingly.

## Engineering Requirements
- Implement the SkeletonPages for each page as the loading state
- Use skeleton loading state across all pages before page-specific data is applied/loaded.

## Acceptance Criteria

Skeleton Loading the follow Targeted pages:

1. **snapshot_proposals**
   - [Permalink](https://github.com/hicommonwealth/commonwealth/blob/e2484d5ca2df5964a3937915af9114a64e0dd722/packages/commonwealth/client/scripts/views/pages/snapshot_proposals)

2. **view_multiple_snapshot_spaces**
   - [Permalink](https://github.com/hicommonwealth/commonwealth/blob/19057f7608098b18d96c93821b05c384ee506a15/packages/commonwealth/client/scripts/views/pages/view_multiple_snapshot_spaces)

3. **View_snapshot_proposal**
   - [Permalink](https://github.com/hicommonwealth/commonwealth/blob/658ed2c0a6ed9e883c971bb1fbe07e14c751231a/packages/commonwealth/client/scripts/views/pages/view_snapshot_proposal)

4. **view_proposal**
   - [Permalink](https://github.com/hicommonwealth/commonwealth/blob/658ed2c0a6ed9e883c971bb1fbe07e14c751231a/packages/commonwealth/client/scripts/views/pages/view_proposal)
   
   
   ----
Note this ticket may have follow ups or extensions that detail other pages), however these are the most critical

**Comment by zakhap** [comment]
Superseded by #4546
