### ISSUE TITLE
Comments Overhaul: Left Metadata Row Updates

### ISSUE THREAD

**Issue by jessmart1213** [hicommonwealth/commonwealth#4240]

**Comment by jessmart1213** [comment]
## **Left Metadata**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/46004ab2-03f3-49dc-8c3a-d2da427e2a0c)

- Design specifications
    - Made up of the ‘user popover wrapper’, interpunct / middledot [•], and ‘timestamp’.
    - 8px spacing between
- Behavior
    - Contains metadata

---

### div.user-popover-wrapper

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/c9037377-1438-46a9-b81a-0901f3997411)

- Design specifications
    - The ‘user popover wrapper’ is made up of the ‘avatar’ and ‘display-name’ component.
    - Width: varying widths as wrapper hugs interior components
    - Height: 24px
    - Components are 8px apart.
- Behavior
    - The ‘user popover wrapper’ has hover-able components within it.
        
       ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/545c8fd8-17b7-4e11-8141-d0d500a60dd2)
        
        READ ME: The user popover components, I recreated in Figma in order to showcase updated behavior. It looks similar to the user popover that is currently implemented, but is not the same.
        
        Leave the user popover as currently implemented.

---     

### Avatar

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/dc51555d-4945-4ed7-9de7-f886d6f32eba)

- Design specifications
    - Width: 24px
    - Height: 24px
- Behavior
    - On hover, ‘user popover’ is triggered.
        - If the user is not the author of the comment or reply and is not an admin of that community, then the ‘non-admin user popover’ is triggered.
        - If the user is the author of the comment or reply and is not the an admin of that community, then the ‘non-admin user popover’ is triggered.
        - If the user is not the author of the comment or reply and is the an admin of that community, then the ‘admin user popover’ is triggered.
        - If the user is the author of the comment or reply and is the an admin of that community, then the ‘non-admin user popover’ is triggered, because a user can not ban themselves.
        
        ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/b058cdd6-f26e-48a3-87ff-0caa05019b49)        

### Displayname

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/4303b869-9052-4871-bb7c-6add40e559c3)

- Design specifications
    - Element - text
    - Font: Caption / Medium
    - Color: Nuetrals/800 or #282729
- Behavior
    - On hover, text is underlined.
    - On hover, ‘user popover’ is triggered.
    - See user popover behaviors under component ‘Avatar’ as they are the same.
        
        ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/194f5bbc-aa7a-4c52-bd5e-43499135883f)
        
---    

**Timestamp**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/7cbbf856-cad5-4e0b-ae60-c726f77f4b0b)

- Design specifications
    - Element - text
    - Font: Caption / Regular
    - Color: Nuetrals/800 or #282729
- Behavior
    - Displays relative timestamps. Please see relative timestamp section for more.
    - On hover: A tool tip displaying the corresponding absolute timestamp is triggered. Please see absolute timestamp section for more.

**Relative timestamp rules**

- When post time is 59 secs or less
    - Show “Less than 1 min ago”
- When post time is 59 minutes or less
    - Show “X min ago”
    - Ex: 1 min ago
    - Ex: 2 mins ago
- When post time is 23 hours or less
    - Show “X hour(s) ago”
    - Ex: 1 hour ago
    - Ex: 2 hours ago
- When post time is 3 weeks or less
    - Show “X week(s) ago”
    - Ex: 1 week ago
    - Ex: 2 weeks ago
- When post time is 12 months or less
    - Show “X month(s) ago”
    - Ex: 1 month ago
    - Ex: 2 months ago
- When post time is 1 year or more
    - Show “X year(s) ago”
    - Ex: 1 year ago
    - Ex: 2 years ago
    - Note: 4 weeks does not accurately reflect the calendar months of the year. Change from months to year happens once the 13th months is reached or the 52nd weeks is reached.

Round down
- For example if 1 hour and 45 mins have passed the relative timestamp should say ‘1 hour ago’ not ‘2 hours ago’



**Absolute Timestamp**

- Date
    - Dates are no longer formatted as
        - MM/DD/YYYY
    - New date format
        - Month D YYYY
        - [Full month name] [Day expressed using ordinal numbers] [Full year]
        - Ex: June 5th 2023
- Time
    - Time format: 12 hour clock
        - Clock should reflect the the timezone the user is currently in. Time zone, however, does not appear in UI.
    - Examples:
        - 6:37 PM
        - 12:45 AM
- Date and time within the tooltip
    - Format: [[Full month name] [Day expressed using ordinal numbers] [Full year] • [12 hour clock]]

**Comment by jnaviask** [comment]
Superseded by #4609.
