### ISSUE TITLE
Reactions state management with react query

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4244]
## Description
Follow-up for #4186. We should use react-query to store + mutate the state of reactions, rather than relying on raw HTTP requests + event emitters. See client/scripts/state/api/topics as a reference.

## Engineering Requirements
- Logic for reactions encapsulated with react-query.
- New state folder for reactions that adds react-specific hooks.
- Use react-specific hooks for reactions rather than existing business logic.

## Acceptance Criteria
No product-facing changes or regressions.

**Comment by CowMuon** [comment]
Looks like this is set to in progress but has no point estimate? @kurtisassad 
Please see #4258 (literally the first item on the sub-task list.)

**Comment by mzparacha** [comment]
Did some work and apart from the reaction thread controller we have some API calls of reactions endpoints in the threads and some controllers. These are all the files that have some /reactions related API calls
- [ThreadReactionsController.ts](https://github.com/hicommonwealth/commonwealth/blob/ecac186ed8bdf2e75f2c01586c639d7a1338da67/packages/commonwealth/client/scripts/controllers/server/reactions/ThreadReactionsController.ts)
- [reactions.ts](https://github.com/hicommonwealth/commonwealth/blob/1648bf6f45c062b3c752d284024e576116ab06f3/packages/commonwealth/client/scripts/controllers/server/reactions.ts)
- [reactionCounts.ts](https://github.com/hicommonwealth/commonwealth/blob/f03f10b7d7c6ec2dd4f06a962135af9284b66d50/packages/commonwealth/client/scripts/controllers/server/reactionCounts.ts)
- [threads.ts](https://github.com/hicommonwealth/commonwealth/blob/0ca45768a7f2d5e38fd2d8fce72a71eb101b424e/packages/commonwealth/client/scripts/controllers/server/threads.ts)

what I am concerned about is threads.ts. Should we move the reaction-related API calls from `threads.ts` to the new react query /reactions state/folder for better organization

cc: @jnaviask @CowMuon

**Comment by jnaviask** [comment]
@mzparacha feel free to move the reactions functions around as needed -- if it makes sense to move them from threads.ts, then that's fine (see the old TODO anyway!).

**Comment by CowMuon** [comment]
This is under review and should be mergeable once @masvelio marks his comments as resolved.
