### ISSUE TITLE
Migrate WalletConnect from v1 to v2

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4251]
## Description
WalletConnect is dropping support for v1 at the end of June. We should upgrade according to the [upgrade path doc](https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps#web3-provider). We are currently using web3-provider, so we will need to migrate to ethereum-provider.

## Engineering Requirements
- Upgrade the WalletConnect web wallet controller to support v2.

## Acceptance Criteria

WalletConnect login succeeds using v2 instead of v1.

**Comment by ianrowan** [comment]
Does not appear to require/blocked by ts 5. Tested with changes in PR and login works as expected
