### ISSUE TITLE
Remove & prevent duplicate for ChainNodes with eth id 1

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4253]
## Description
ERC20 community creation keeps failing, because we have a second ChainNode that keeps getting recreated that references ETH mainnet, but has a different set of URLs. We should figure out why, prevent new duplicate ChainNodes from being created, and ensure that the existing duplicate is removed.

## Engineering Requirements
- Diagnose reason for duplicate ETH mainnet chain node creation & fix.
- Remove duplicate ETH mainnet chain nodes.

## Acceptance Criteria

ERC20 creation works again.

**Comment by jnaviask** [comment]
@alexyoung23j I discovered the cause: line 309 in /createChain -- need to change how we search, or ensure URL client is using matches the url we're expecting.

**Comment by alexyoung23j** [comment]
Actually caused by this: https://github.com/hicommonwealth/commonwealth/issues/4283

**Comment by timolegros** [comment]
After fixing the URL on the client side I think it is redundant to add additional checks in the `/createChain` route given that unique URLs in ChainNode _is_ what we want and this was caused by an isolated incident (due to a hardcoded url).

**Comment by alexyoung23j** [comment]
Agreed
