### ISSUE TITLE
Clicking rapidly on sidebar topics causes page content to get stuck

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4254]
## Description

See loom: https://www.loom.com/share/b8184030a0724b96bdf17a51320b5096?sid=9da17a82-f180-478f-8a28-b4fc556b4d31

## Expected Behavior
Changing topics from the community sidebar should load threads correctly in the thread list without getting stuck. (by stuck we mean that they dont update accordingly to the new topic selected)

## Actual Behavior
Threads get stuck in list when changing topics from the community sidebar rapidly/quickly.

## Steps to Reproduce 
1. Go to any community that has a lot of threads
2. From the community sidebar, click on the different topics quickly (make sure the topics you click have loaded a lot of threads by scrolling - this is just to get a safe thread number)
3. Verify the threads in thread list dont get stuck.

## Acceptance Criteria

Topics should reliably change when when clicked rapidly.

**Comment by mzparacha** [comment]
Generally this class of bugs was not surfaced before the layout refactor because we were re-rendering the page component which took more time plus these bugs were not visible. Right now the page may seem stuck but it takes some time to refresh which i ATM think is a bug with either our list component or some state.

**Comment by mzparacha** [comment]
I am atm working on this one cc: @CowMuon

**Comment by mzparacha** [comment]
This is now handled in 4280

**Comment by CowMuon** [comment]
So, unfortunately this is not resolved by #4280 (or rather #4264 which was merged into #4280, even though we generally try to avoid that, and here we have a case  *IN* point)** and TBC, it is better now, it doesn't always get stuck, but there's still an edge case where it looks like maybe it wasn't tested "fast" enough? 

That's actually an important part of this ticket, if we have tests where test accuracy correlates to or resolves to test run granularity or frequency. Also, intuitively, seems like that may be just reducing the size of whatever that memory leak is below the threshold of immediate impact (while still leaking.)

**Comment by mzparacha** [comment]
This is still happening on prod, but not on local for me. It could be due to cache issues or data differences, will need a fresh db dump to test on local
