### ISSUE TITLE
Migrate Google Analytics

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4260]
## Description

![image (10)](https://github.com/hicommonwealth/commonwealth/assets/16248081/2f5534d2-e526-45c4-99d7-468f86477e7c)

Q: Who needs what access/keys/boilerplate to make this happen? 

## Acceptance Criteria

- We update to GA4 so we continue to process data after June 30th.

**Comment by CowMuon** [comment]
So many 6/30 upgrade deadlines, Typescript 5.0 (for Wallet Connect 2.0), Google Analytics 4, what else?

**Comment by CowMuon** [comment]
Removed monitoring label since we do not use GA for monitoring (rather, BA.)

**Comment by dillchen** [comment]
Done: https://analytics.google.com/analytics/web/#/p384888170/reports/intelligenthome?params=_u..nav%3Dmaui
