### ISSUE TITLE
Discobot Ticket 1: Listener Service

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4266]
## Description
This ticket encompasses the work required to spin up the new server responsible for 1) connecting to our discord bot via websockets and 2) passing the relevant data along to a queue for handling by a separate worker service. 

## Implementation Details
- [x] Spin up express server will be set up in a new repo.
- [x] Establish connection to discord bot -> likely needs the keys from existing bot.
- [x] Service will be polling the CW DB on regular intervals to find the `Topics` that have a non null `discord_forum_id`. (This is how we will associate discord forum channels with topics in communities on CW.)
- [x] Filters out the incoming discord events that do not correspond to a connected Topic. 
- [x] Passes discord events (processed/cleaned if needed) on to a RabbitMQ queue. "See chain events for similar setup."

# Acceptance Criteria
- Checks all the boxes
- Tests written - **Need better scope definition here**
- Service deployed successfully to a new Dyno.

**Comment by ianrowan** [comment]
There will be useful functions in common-common for the discord-bot listener services, so I think we should add new service to the main repo. It is similar to chain-events so it wouldnt break any patterns by creating a new package

**Comment by ianrowan** [comment]
PR(still draft curr) linked here also include some work for #4267 but given we are not spinning these up yet it might make sense to merge them and work off a new branch to formalize the worker service so that CW migration(column addition) can be available for CW side dev.
