### ISSUE TITLE
WIP Discobot Ticket 3: Commonwealth Changes

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4268]
**Description:**
These are the changes that will need to be made to commonwealth in order for the 1-way sync with discord to be complete.

Admin Panel:
- Admin panel will be updated so after a bot is installed (using existing installation flow, crucially), the admins can see a list of forum channels. They can select any number of these to create a new topic and establish a sync with common. If they unselect, it will pause the sync. See comment for discussion about this.

Threads:
- `Thread` model and `Comment` model will need to update in order to store the author data coming from discord. This is so that down the road, Common users will be able to claim their discord account and associate their activity on discord with their common profile.
- If we want posts to not just be authored by "Discord bot" and instead have a discord user as an author, the UI needs to be changed to handle this case. 

**Implementation:**
1. Product/Design need to come up with a design for the admin panel portion.
2. Thread and Comment (potentially Reaction) models need to be updated with new column(s) to store discord user metadata.
3. New role needs to be added to common db ("bot"). Discussed in #4267

**Comment by alexyoung23j** [comment]
@zakhap @MuonShot In discussions today Ian and I realized that the proposed slash command solution is not ideal. Here's why:

Slash commands are meant to be used within messages to channels. So in normal channels, it makes sense to use a slash command to connect that channel to common. But in this case, we are connected to the new discord _forums_ product. We want threads in that forum to correspond to threads in Common, under a Topic that corresponds to the Forum Name. But you cannot use slash commands at the "forum level". You can only use them within threads/comments. So if we use a slash command to connect the forum to common, the discord user UX would be: 1. go to forum 2. randomly choose a thread in that forum 3. slash command from inside that thread, leaving a strange comment unrelated to the specific thread.


The proposed solution here is to just build a simple component in the CW admin panel to handle this. We already have UI there to connect the bot, so its arguably even simpler to have the topic <-> forum connection happen there too. The UI simply needs to:
- Show the forums in a connected discord server
- Let user toggle forum <-> CW topic connection on and off. Simple checkbox would suffice.

**Comment by ianrowan** [comment]
> @zakhap @MuonShot In discussions today Ian and I realized that the proposed slash command solution is not ideal. Here's why:
> 
> Slash commands are meant to be used within messages to channels. So in normal channels, it makes sense to use a slash command to connect that channel to common. But in this case, we are connected to the new discord _forums_ product. We want threads in that forum to correspond to threads in Common, under a Topic that corresponds to the Forum Name. But you cannot use slash commands at the "forum level". You can only use them within threads/comments. So if we use a slash command to connect the forum to common, the discord user UX would be: 1. go to forum 2. randomly choose a thread in that forum 3. slash command from inside that thread, leaving a strange comment unrelated to the specific thread.
> 
> The proposed solution here is to just build a simple component in the CW admin panel to handle this. We already have UI there to connect the bot, so its arguably even simpler to have the topic <-> forum connection happen there too. The UI simply needs to:
> 
> * Show the forums in a connected discord server
> * Let user toggle forum <-> CW topic connection on and off. Simple checkbox would suffice.

Just to add here. Using slash commands vs allowing forum syncs to be set up on common UI creates a lot of messy permissions/etc to allow the slash command access to our CW database. 

Likewise if users use slash commands anywhere outside of the forum they'd need to specify the channel they wish to create a topic for. That data isnt very useful for us because we're interested in channelId which we would need to fuzzy match if just given the string name of the forum.

Adding this to the admin UI would be efficient in 2 ways
1. We have access to channel names/ids for easy set up
2. We have direct access to the models we need to update(ie topics) from the common UI

On top of that it seems like a cleaner user experience for admins to set up CW Topics on CW rather than a slash command on discord to keep it straightforward and avoid the confusion of request/response of slash commands. (ie user can have visual proof their new topic was created on CW)

**Comment by alexyoung23j** [comment]
After discussion with Zak, here is a description of the Admin panel component:

A list view of all "forum channels". Next to each channel name, a dropdown will display all the available topics in that community. If a topic is selected, it means that new threads from the forum channel will be populated in that topic on CW. If no topic is selected, a small text message will indicate that the forum channel is "not synced".

**Comment by alexyoung23j** [comment]
Addition to ticket:

The step of connecting a CW community to a Discord server (creating an association between the two in DiscordBotConfig) currently requires an intermediate step with the discord bot ui. We want to cut out that UI entirely, so this ticket will also include the following:

1. Update callback url on discord oauth link to point back directly to commonwealth.
2. Create a new callback page on Common that has the express purpose of hitting `/setDiscordBotConfig` before immediately redirecting to the community management page again.

This adds a few points to the ticket.

**Comment by ianrowan** [comment]
Changes look like they're working well. A couple things I did notice were
1. I get this error pop-up when saving a forum/topic. The Topic in the DB does get updated and bot works but always seeing this message on both original and feature branch 


![Image](https://github.com/hicommonwealth/commonwealth/assets/36428666/7cfd1e9c-97a2-4d59-9441-62130361c5da)

2. I think the test bot is hardcoded into 'connect bot' functionality. Connect bot was also a bit buggy in terms of updating the UI once bot was connected  

CC: @alexyoung23j
