### ISSUE TITLE
Subscriber 2 running out of memory in production

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4272]
## Description
```
2023-06-16T12:33:36.882977+00:00 heroku[subscriber2.1]: Process running mem=1263M(123.4%)
2023-06-16T12:33:36.887645+00:00 heroku[subscriber2.1]: Error R14 (Memory quota exceeded)
```

## Engineering Requirements

- The subscriber should not exceed 100% memory usage.

**Comment by CowMuon** [comment]
This is blocking #3978

**Comment by timolegros** [comment]
Since we removed some chains from chain-events the memory error is now on subscriber-3. This confirms that the issue is related to a specific chain.

**Comment by timolegros** [comment]
Update: heap snapshot turns out to be completely useless. It is clear from the heap timeline that objects and arrays are continuously taking more room in memory but these are anonymous objects and arrays that cannot be connected to an object directly in the code.

Also tried using https://clinicjs.org/ to debug to no avail.

The following possible sources of memory leaks have been eliminated:

1. Unresolved promises from `eth_getLogs` calls
2. Event pile-up
3. Aave vs Compound listener issues (not chain differences just listener differences i.e. memory issue still occurring in #3079)

**Confirmed: the memory leak is a direct result of listening to Celo chains. If these chains are turned off, the memory leak no longer occurs.**

**Comment by timolegros** [comment]
Unfortunately, after all the work that was put into this issue, we have come to the conclusion that we will be moving forward with the removal of chain-events. This issue is no longer necessary.
