### ISSUE TITLE
Forum Endpoints Refactor: Consolidate Thread Fetch Endpoints

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4282]
Parent ticket: https://github.com/hicommonwealth/commonwealth/issues/3989

## Summary

- The problem is that we have multiple old endpoints for fetching threads (`getThreads`, `bulkThreads`, `activeThreads` and `searchDiscussions`)
- The goal is to consolidate them into RESTful endpoints `GET /threads` and `GET /threads/:id`
- The original plan was to take the logic from the old endpoints to consolidate into a single method on the `ServerThreadsController` class, continuing the pattern that's been set forth in parent ticket (https://github.com/hicommonwealth/commonwealth/issues/3989)
- However, since each of the old endpoints takes different query params and returns different data structures with different pagination strategies, then it's going to be a big lift to fully refactor all of it, frontend and backend.

## Endpoints:

`GET /threads` - Returns bulk threads
- Implements functionality from `/getThreads`, `/bulkThreads`, `/activeThreads` and `/searchDiscussions`

`GET /threads/:id` - Returns a single thread by ID
- Implements functionality from `/getThreads`

**Comment by CowMuon** [comment]
QA (Acceptance Testing) passed; this is ready to ship.
