### ISSUE TITLE
🪣  First-time community member frictions | Onboarding 

### ISSUE THREAD

**Issue by jessmart1213** [hicommonwealth/commonwealth#4306]
### Subtasks
- [x] #4377 
- [x] #4378 
- [x] #4375  
- [x] #4380 

# Design Solution | Non-Community member frictions

**Summary of solution and design (UX/UI) requirements**

This is a quick fix to solve for escalated user pain points. This is part of ‘Login and onboarding work stream.

This Ticket uses the new Tooltip component. In the process of working on this ticket, please also execute #4123 if it has not been assigned to someone else. 

### Full mock

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/96bc790c-c1e8-4372-bb4f-109e0b1113ca)

Resources
- Figma masterfile: [Non-joined community member frictions](https://www.figma.com/file/u0FhSHNnQZlzPSXEVZvXWt/Non-joined-community-member-frictions?type=design&node-id=1%3A38&mode=design&t=tQKKHLFYPIUns0ka-1)
- Figma prototype: [Non-joined community member frictions](https://www.figma.com/proto/u0FhSHNnQZlzPSXEVZvXWt/Non-joined-community-member-frictions?page-id=1%3A38&type=design&node-id=26-46186&viewport=282%2C63%2C0.08&scaling=scale-down&starting-point-node-id=26%3A46186&mode=design)
- Loom prototype walkthrough: [Solution for Non-community member frictions](https://www.loom.com/share/d9e2ddd810184631b55a46ae51c0e4cf?sid=02f8d682-126e-46d9-a5e4-0f4e8700102e)

**Comment by CowMuon** [comment]
NB. Tool tip is not documented here/yet. Thanks to @masvelio for catching this!

**Comment by masvelio** [comment]
@jnaviask @MuonShot last Two tickets ready to review! 
https://github.com/hicommonwealth/commonwealth/pull/4521
https://github.com/hicommonwealth/commonwealth/pull/4493
