### ISSUE TITLE
Comments Overhaul - P2 

### ISSUE THREAD

**Issue by jessmart1213** [hicommonwealth/commonwealth#4307]
## Description

# Design Solution | Comments Nesting Overhaul - Part 2

## Summary of solution and design (UX/UI) requirements

The goal for Part 2 in improving the overall experience of Common’s Comments and Reply Nesting features is to Increase the nested replies from 3 to 8 and add functionality that makes it easy for users to follow the discussion as it branches into different nested threads.

---

## 8 Nested Reply Layers

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/cb94c7e1-ab11-4029-8a8b-205af6c25c0c)

- User Story
    - As a user I want deeper nested replies so that I can respond more directly to a reply or a user.
- Design specifications
    - Please see figma file Forum Improvements - Part 3 - Comments and Replies, page ‘[🟢 Comments P1 - JUN 12](https://www.figma.com/file/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?type=design&node-id=1%3A3&mode=design&t=lWMOEg3JK1ecDczA-1)’ for design specifications on the comment and reply components themselves.
    - Total spacing between comments and replies is always 32px.
- Behavior
    - 8 nested reply layers
        - Layer 1 is a comment
        - Layers 2-8 are replies
    - A post / thread can have an unlimited amount of comments.
    - Comments can have an unlimited amount or replies.
    - Replies can have an unlimited amount of replies.

## Disabled reply CTA

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/8a0a9f25-9fb8-4194-b386-366945405909)
- User Story
    - As a user I want to know when I can no longer respond to a reply.
- Design specifications
    - Reply CTA
        - Use disabled state of the Reply CTA.
        - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Thread Actions](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707%3A11225&mode=design&t=Ye3ZmEsEvSoAW5i7-1)’ > and look for Comment / Reply.
    - Tooltip
        - Use copy, “Nested reply limit reached”
        - Use currently implemented tooltips.
- Behavior
    - The Reply CTA on the 8th nested layer is disabled. On hover, a tool tip is triggered.

## Accordion Button

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/7fb47235-8ce0-4beb-ad34-ae8c3739c859)
- User Story
    - As a user I want to be able to ‘Hide replies’ so that I can only see comments to the post and view the discussion without the clutter of threaded replies.
- Design specifications
    - Accordion Button
        - This component has a line, tertiary button with trailing icon, another line.
        - Height: 32px
        - Width: Should reflect the width of the body content of the Comment component. (In the figma I set a 32px left padding, but implement as you see fit)
        - Copy for collapsed state: Show replies
        - Copy for expanded state: Hide replies
    - Line
        - Line weight: 1 px
        - Color: Nuetrals / 200 or #E0DFE1
        - Length: Fills parent container
    - Tertiary button
        - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Buttons](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=69%3A1963&mode=design&t=Ye3ZmEsEvSoAW5i7-1)’ > and look for Tertiary small.
            
            ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/1d9822ed-22a2-4206-86da-fd446922396a)
            
        - Icons used: CaretUp, CaretDown | 16 by 16px | weight: regular
- Behavior
    - Accordion / Collapsed
        - On click, show hidden replies and change Accordion state to expanded.
    - Accordion / Expanded
        - On click, hide shown replies and change Accordion state to collapsed.

## Show X more replies’ text button

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/bcb1cd0f-60b4-4ed7-9ed7-888ca12a9041)

- User Story
    - As a user I want lower level replies after a certain # to be hidden so that I don’t have scroll too much to follow the discussion on comments and higher level replies.
- Design specifications
    - Text that acts like a button.
    - Copy: Caption / Medium
    - Active color: Primary Blue / 500 or #338FFF
    - On hover color: Primary Blue / 600 or #338FFF
- Behavior
    - By default up to 8 replies are shown per comment. If a comment has more than 8 replies, those replies are hidden until the ‘Show X more replies’ text button is clicked.
    - On click, hidden replies are shown and the ‘Show X more replies’ text button disappears.

## Comment Settings

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/c205aefc-29bc-4961-9a6d-1ae564a7335c)
- Design Specifications
    - Replace ‘Include comments flagged as spam with a comment settings dropdown.
        
        ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/253561eb-d712-4f3f-981e-32b20b576f74)        
- Dropdown
    - Dropdown button / Compact: Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢Dropdowns](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=340%3A6230&mode=design&t=Ye3ZmEsEvSoAW5i7-1)’ > and look for Dropdown button / Compact.
    - Dropdown list item / compact with toggle
    - Dropdown button / Compact: Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢Dropdowns](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=340%3A6339&mode=design&t=Ye3ZmEsEvSoAW5i7-1)’ > and look for Dropdown list item / compact with toggle.
- Behaviors
    - ‘Hide replies by default’ toggle
        - On: Hides or collapses all replies
        - Off: Show or expands all replies
    - ‘Hide spam’
        - On: Does not show comment and replies flagged as spam.
        - Off: Shows comments and replies flagged as spam.

## Breakpoints

**1440+**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/f6688aa9-889c-4029-ac1f-6dd6fb7f51a9)

**600-906px**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/d3cfbc0f-3b6c-40f3-8471-db2bf7a85c43)

**0-600px**

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/75aa1b95-2507-4a90-b86a-83cd5b47291a)

- Mobile breakpoint adjustments
    - Compress spacing between nested layers to fit mobile screens
    - Note, that the thread action row should wrap when needed, to prevent overflow.

---

### Resources
- Figma masterfile: [Forum Improvements - Part 3 - Comments and Replies](https://www.figma.com/file/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?type=design&node-id=346%3A33737&t=d0zI8lnSNpY54JMG-1)
- Figma prototype: [Forum Improvements - Part 3 - Comments and Replies](https://www.figma.com/proto/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?page-id=346%3A33737&type=design&node-id=374-84525&viewport=219%2C210%2C0.17&scaling=scale-down&starting-point-node-id=374%3A84525&show-proto-sidebar=1)
- Loom prototype walkthrough: [Comment Nesting Overhaul Part Two](https://www.loom.com/share/29228a98cdf646f5849b79e30999d9f5?sid=b9165d97-a514-44b2-abe4-53e8d3f81326)

---
## Engineering Requirements

- The Widget route should return a TODO response.
- 

## Acceptance Criteria

- As I user I want deeper nested replies so that l can respond more directly to a reply or a user.
- As a user I want to easily identify comments  (response to the post ) from replies (response to comment or another reply ) so that I can easily follow the discussion as it branches into various layers.
- As a user I want to be able to ‘Hide Replies’ so that I can only see comments to the post and view the discussion without the clutter of threaded replies.
- As a user I want to be able to ‘Hide Replies’ so that I can only see comments to the post and view the discussion without the clutter of threaded replies.
- As a user I want lower level replies after a certain # to be collapsed to that I don’t have scroll too much to follow higher level comments.
- As user I want to be able to show collapsed lower level replies when I choose to so that I have more control over when I view them.  
- As a user I want to be able to see all nested replies on mobile, so that I can access this content on the go.

**Comment by ForestMars** [comment]
Is this something that needs to be re-scoped, or can it be closed? @jessmart1213 @jnaviask

**Comment by dillchen** [comment]
done
