### ISSUE TITLE
[Community Homepage] - Enhanced Page

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4334]
## Description
In our application, we've encountered an issue where the feed is not being displayed correctly in the FeedPage component, for displaying a community feed. Although the data is being fetched and passed to the Feed component, the feed items are not visible on the screen. This issue needs to be resolved in order to display the feed data properly to the users.

## Engineering Requirements

Investigate the FeedPage, Feed, and UserDashboardRow components to identify the root cause of the display issue.
Ensure that the data is being fetched, passed, and rendered correctly in the components.

Check and resolve any styling issues that might be causing the feed items not to be displayed, such as the height of the Feed component collapsing to 0px.

Implement a solution to update the label.linkUrl in the handleLinkClick function by removing the leading /${app.activeChainId()} from the URL before navigating to the updated URL.

## Current Features
- The feed data should be correctly fetched and passed to the Feed component.
- The Feed component should display the feed items using the UserDashboardRow component.
- The feed items should be visible and correctly styled on the screen.
- The handleLinkClick function should be refactored to update the label.linkUrl as required.

## Enhancements 
- [x] Displays and allows users to toggle between active snapshot votes within a community
- [x] Limit characters in the body of feed item to first 280 characters (for both comments, threads, and "Quote OPs"
- [x] Interactions such commenting, reacting, and more work as expected on the FYP and Community Homepage, if I am allowed to based on the community / topic threshold. (Right now the re-implemented gating doesn't allow it to work)
- [x] Links handling no longer opens a new page (always just opens via navigation)
- [x] See more / Click to expand on feed items
- [x] If a feed item is a comment on a thread, we should display the OP in line, or like some string limited amount of context, and the OP Card should fetch and display the Thread Author using the `Avatar` Comment (I should see the thread author information as I do elsewhere on the site, not as address)
- [x] Ensure that the Explore Communities shows up as expected on homepage and in-community
- [x] Fix threads incorrectly labeled as 'new'

**Comment by dillchen** [comment]
Updates:



![Image](https://github.com/hicommonwealth/commonwealth/assets/5334557/8ff55fe2-54a9-471c-b974-4d883cf219f3)

**Comment by dillchen** [comment]
Superseded

**Comment by ForestMars** [comment]
Do we have the superseding ticket yet? @dillchen Or does it need to be written up? 

Dropped the refinement tag here to bookmark; @sachben91 If you can have new ticket for Refinement this week, this will go into v1.3.5 ship target 5/20.
