### ISSUE TITLE
Active proposal status and vote tally not updating after fetch

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4343]
Intermittent UI bug in Cosmos and possibly other communities:

Repro:

1. http://localhost:8080/kyve/proposals
2. http://localhost:8080/kyve/proposal/7-efficient-frontier-kyve-market-making-proposal

![Image](https://user-images.githubusercontent.com/9438198/248964842-6bf8f934-6ffe-4de4-8f6e-9cadf1b88f9c.png)
![Image](https://user-images.githubusercontent.com/9438198/248964843-d352cff0-0488-4d8c-80f4-fe2d3f9e35fd.png)
![Image](https://user-images.githubusercontent.com/9438198/248964844-b2185357-491b-4dab-9c3b-fd7129a5bb5a.png)

Expected: Once the http://localhost:8080/cosmosLCD/kyve/cosmos/gov/v1/proposals/7/tally completes, the votes and status should update without needing and extra clicks or refreshes

**Comment by CowMuon** [comment]
What's the status here? This is a good example of why we don't re-open closed issues to work on them, as the originally closed issue now links to 2 different PR's, 1 of which links to this issue in a comment (but not as a workflow step.) 

[For context: #4181, which was previously completed, was re-opened as a 'regression" which we should not do. Closed tickets should not be re-opened as part of development workflow.]

Does this ticket being opened mean that we can now close #4181? I'm genuinely confused what the status is here. (Growth team was informed this was just a 1 pointer and would be resolved today.)

**Comment by mhagel** [comment]
>What's the status here? This is a good example of why we don't re-open closed issues to work on them, as the originally closed issue now links to 2 different PR's, 1 of which links to this issue in a comment (but not as a workflow step.)

This is a new ticket for a scope outside of the work done for #4181. 

>[For context: https://github.com/hicommonwealth/commonwealth/issues/4181, which was previously completed, was re-opened as a 'regression" which we should not do. Closed tickets should not be re-opened as part of development workflow.]

Sounds good. I thought I had previously seen this workflow, but I understand it creates confusion.

>Does this ticket being opened mean that we can now close https://github.com/hicommonwealth/commonwealth/issues/4181? I'm genuinely confused what the status is here. (Growth team was informed this was just a 1 pointer and would be resolved today.)

No, this is a separate scope of work. #4181 dev work was completed yesterday.
