### ISSUE TITLE
Templates for bugs and features 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4344]
## Description
We currently have a a single template for filing github issues in our repository. We would like to have separate templates for bugs and features, as there is different information needed for each case (An example of which is the "Reproduced?" property on bug reports. 

## Engineering Requirements

- [ ] Decide that yes, we want to do this. 
- [ ] add file `.github/bug_report.md` for the bug template.
- [ ] add file `.github/feature_request.md` for the feature template.

## Acceptance Criteria
When opening a new issue, reporter is given choice of bug or feature templates.

**Comment by CowMuon** [comment]
Let's make sure we have this for new cycle kickoff!

**Comment by dillchen** [comment]
Seems like a good idea
