### ISSUE TITLE
Create Notifications Pipeline Definition

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4347]
## Description
Create a minimal Apache Beam pipeline definition according to Forest's Notification System Design doc.

## Engineering Requirements
Specified in doc: https://docs.google.com/document/d/14Pq82r-BE5KlajcDtESyugxRju35X83e4Ux9-Ljdvro/edit

## Acceptance Criteria
See doc

**Comment by rbennettcw** [comment]
Status update:
- I created a minimal Beam app that can use the "direct" runner (invokes code in the Node app), but that's not what we want
- I've been working on getting the Beam TS SDK to connect with the Docker Flink job service
- Using the officially supported method (setting the the runner to "flink") does not work, because the TS SDK attempts to fetch a jar file at runtime and there's a 404. Tried a few different things to no avail. That's an undesirable pattern anyway.

![Image](https://github.com/hicommonwealth/commonwealth/assets/126922418/cd08081f-df5c-4751-aa64-7f149325582a)

Now I'm trying an unofficial way of using the "portable" runner, which is supposed to connect to the Docker Flink service via gRPC (which is the more desirable approach).

I'm currently debugging a connection issue.


![Image](https://github.com/hicommonwealth/commonwealth/assets/126922418/b4920b6a-3bbf-4dce-b557-6e2765e95607)


Latest code is pushed up to Tim's MVP branch: https://github.com/hicommonwealth/commonwealth/pull/4342/files

cc @CowMuon @timolegros

**Comment by rbennettcw** [comment]
Fixed the connection issue with Tim's help.

Now the Node.js Beam app can deploy/execute a pipeline on the Flink runner, but it fails for some unobvious reason. Debugging the cause.

![Image](https://github.com/hicommonwealth/commonwealth/assets/126922418/904da15d-0151-4ef9-84db-07b2a54ed06a)

**Comment by rbennettcw** [comment]
Update:
- The Apache Beam SDK has dismal support for TypeScript (it just plain doesn’t work according to the official examples provided, and we’ve tried numerous workarounds). The Java/Python/Go variants of the SDK seem to have better support.
- GPT 3.5 will give you fake code hallucinations and GTP4 throws a blank due to the 2021 cutoff.

I have a few concerns:

Firstly, the usage of Apache Beam/Flink means that we’re starting with a high baseline level of complexity. At minimum, we’d have:
1. Application logic for handling events
2. Flink job manager
3. Flink task manager
4. Beam job service

Whether we run it in Docker or not, that’s already a lot of complexity for an initial implementation of an event pipeline.

Also, even if we got TypeScript to work, the documentation and resources available for the Apache Beam TS SDK is not great in terms of long-term maintainability.

So my questions are:
- Is it a hard requirement to use Apache Beam/Flink?
- Is is a hard requirement to use TypeScript?

cc @CowMuon @timolegros

**Comment by timolegros** [comment]
> 

@rbennettcw has a very valid point here about the Typescript SDK. The documentation is very poor, there is only a single maintainer of the SDK and on top of that, there is no well-tested support for the Flink Portable runner which is the runner we require. In fact, the portable runner class was just released last month and doesn't work with our setup.

I think this leaves us with 2 options:
1. Use Python, Java, or Go.
  - This would likely include having to set up a separate HTTP or gRPC server using one of these languages to which we can send requests with events from our CW TS server. This is a terrible idea as the new server itself then becomes a bottleneck and a possible failure point that we have to scale accordingly. Thus, I don't think using a separate language is something we should do.
2. Look at other pipeline tooling options that are more Typescript compatible, developer-friendly, and well-maintained.

**Comment by CowMuon** [comment]
In review, not looking good for Typescript in Beam. (Java, Python & Go seem to be main, well-supported, first class languages in Beam.

**Comment by timolegros** [comment]
Gonna go ahead and close this considering we aren't defining a Beam pipeline for the MVP and I want to clean up the Notifications Pipeline MVP milestone so we can restart without the mess of issues we had/have.
