### ISSUE TITLE
Clicking on addresses leads to /profile/undefined

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4357]
BD reports that a user clicked on an address and was redirected to an undefined page.

**Acceptance Criteria:**
Any address clicked should redirect to a correct profile.

**Comment by jnaviask** [comment]
Steps to reproduce?

**Comment by jnaviask** [comment]
cc @alexyoung23j to fill out steps to reproduce -- ticket is not addressable as-is. Bouncing to no status until we have a reproduction plan.

**Comment by alexyoung23j** [comment]
Checked in with BD- appears that a UI change on our end makes this unnecessary to address. We are no longer displaying the list of voters in the proposal view so the faulty click cannot occur.
