### ISSUE TITLE
Diagnose slow cosmos proposal loading

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4362]
## Description

- We have a cache, but it isn't populated frequently enough for end users to experience the benefit of the cache. 
- Desired Outcome:  We want the proposal pages to consistently load quickly, even if it isn't frequently visited.

## Acceptance Criteria

- Loading a cosmos proposal page is never slow.

**Comment by CowMuon** [comment]
Jumped directly to Teed Up (marked as backlog in Refinement yesterday)

**Comment by CowMuon** [comment]
(mis-assignment)

**Comment by CowMuon** [comment]
Slow here is doing a lot of work. 

And this is somewhat more general of an issue than is, er, generally, actionable. But that's really just an acceptance criteria problem.

**Comment by mhagel** [comment]
IMO, we need to move all of the fetches out of the controller `init`, and lazy-load them in a more React pattern: UI components fetch the data they need. Probably a 5 - 8.

This would give performance gains, but again, not quite the scope of this ticket.

**Comment by mhagel** [comment]
This has been split into 2 more actionable tickets: #4472 and #4473 

There may be more tickets that come out of this, but these are the quickest impactful wins.

**Comment by mhagel** [comment]
Added #4495 to capture scope of some easy cache tuning - longer TTLs

**Comment by CowMuon** [comment]
Closing this ticket as work is being done in and #4470, #4472, & #4495. 

Having said that, @mhagel do feel free to add any additionally recognized issues here, either as tickets or hypotheses.
