### ISSUE TITLE
Terra Users unable to comment on threads

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4363]
Reports of Terra users being unable to comment on threads in the terra community.

**Acceptance Criteria:**
Terra users (and all users) can comment on threads.

**Comment by jnaviask** [comment]
Steps to reproduce?

**Comment by alexyoung23j** [comment]
Trying to determine. Potential bug with terra station wallet that I'm trying to figure out

**Comment by alexyoung23j** [comment]
Steps to reproduce: Log in with terra station, attempt to comment on anything. Suspicions the fix here is related to #4356, working with @mhagel to resolve.

**Comment by alexyoung23j** [comment]
Unfortunately, while we found an error in mark's PR that would break the terra forum, his work is not an actual fix for this problem. There is something wrong with how TBC is working for terra right now, investigating further.
