### ISSUE TITLE
Kill `Subscriptions.object_id`

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4366]
## Description
The `object_id` column of the `Subscriptions` table is a legacy method of uniquely identifying subscriptions that is similar to the old root_id issue #2575 which has now been resolved. This object_id is used throughout the API and the client with no centralized definition of what a proper `object_id` is supposed to be (it is simply manually created every time it is needed). This reduces readability and clarity.

## Engineering Requirements

- Uniquely identify a subscription directly from the existing columns (`subscriber_id`, `thread_id`, `comment_id`, `chain_id`).
- Centralized function for retrieving the columns that uniquely identify a subscription for each notification category type.
- Removed `object_id` from `Subscriptions` table and models.
- Replaced all find subscription functionality with a single `findSubscriptions` function which, again, maps a category to the values needed to uniquely identify a subscription.

**Comment by timolegros** [comment]
@jnaviask per #4373, #4370 and #4368 should be teed-up + completed before this issue. This order of completion leads to a minimal amount of changes. If this issue is completed first, then the other 2 issues will need to refactor some of the changes necessary for this issue.

**Comment by jnaviask** [comment]
They've all been teed up for you. @timolegros

**Comment by timolegros** [comment]
99% of the work is done. The PR affects a lot of files (basically anything related to subscriptions across the entire app) so working on creating an exhaustive list of all functionality to QA (with steps on how to QA) on the client given that playwright is not ready to test subscriptions. Once I have created the list and QAed everything on it myself the PR will be ready. I will be keeping it in draft until #4370 and #4368 are merged per #4373.

**Comment by timolegros** [comment]
PR is now ready for review but will remain in draft to avoid accidental merging until #4368 is merged.
