### ISSUE TITLE
Unable to add Topic thread templates

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4367]
When users save a new topic thread template (with topic modal) and then go make a new thread with that topic, the template doesn't populate into the editor.

**Acceptance Criteria:**
When a topic has a saved template, switching to that topic in the thread rich text editor should populate the editor with the template.

**Comment by CowMuon** [comment]
What's the priority here? Severity? Affected communities? Who reported? Have we been able to reproduce? 

At the very least, this issue needs a priority ranking.

**Comment by alexyoung23j** [comment]
Low severity, low priority, affects all communities.
