### ISSUE TITLE
Remove `offchain` prefix from the `Subscriptions` table

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4368]
## Description
The `Subscriptions` table and model still have `offchain_thread_id` and `offchain_comment_id`.

## Engineering Requirements

- Table columns should be renamed to `thread_id` and `comment_id`
- Model properties should be renamed as well (includes all uses of those properties).

**Comment by timolegros** [comment]
This issue was accidentally teed-up in Cycle 4 instead of Cycle 5. Just updated it so it's on Cycle 5.

**Comment by CowMuon** [comment]
PR is still marked as draft, so setting this back to In Progress. If it is ready for review please leave a comment here.

**Comment by timolegros** [comment]
> PR is still marked as draft, so setting this back to In Progress. If it is ready for review please leave a comment here.

https://github.com/hicommonwealth/commonwealth/pull/4482#issuecomment-1633124590 - This has already been noted on the PR itself.

**Comment by timolegros** [comment]
PR is ready for review since #4479 is merged.
