### ISSUE TITLE
New Join Button Design

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4375]
### Join Button

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/5fc5ad5f-4c39-49e9-b0d2-69c8b7163e6a)
- User story
    - As a user, I want better visibility around joining a community.
- Design specifications
    - Replace current ‘Join CTA’  with a small square button.
    - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page '[🟢 Buttons](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=29%3A3238&mode=design&t=HyobTlUa6qSug8qe-1)’ > and look for Primary button, size small.
        
    ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/e5d977fb-f154-4519-ad5c-cc6b69394453)
        
    - Copy: Join community
- Behavior
    - No changes to behavior. Should function the as is.

**Comment by masvelio** [comment]
@zakhap @meeshlin 
1. I can see that the scope of this ticket overlaps with [`Session Keys` PRD](https://www.notion.so/buildcommon/Design-Solution-Doc-Session-Keys-a62193862a30472cb29efa4a4cd02c19) (image below).  Seems like the join button is designed in totally different way and position in the other specification. Please confirm which one will be the source of truth and what will be the final scope of this ticket.
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/c8511aec-b75d-47af-bf67-9654be00c749)

**Comment by zakhap** [comment]
This ticket should not be considered blocked. While the designs change in the session key work, it is important in the mean time to reduce the ambiguity around the join button by using the new button.

**Comment by meeshlin** [comment]
@masvelio The button is taking up the container in this mock, which is the only difference. I know we have two sizes for them and I don't want to add another, so I'm curious if it's possible to make it so there are two sizes but also a size for a button to take up the width of the container like in this mock. 

Could be good to refer to these [resources](https://www.notion.so/buildcommon/References-Other-Design-Systems-4061fb2c32124507ad696386d27130c8?pvs=4) on how to best create this component.

cc: @zakhap @martins87 @Miaplacidus

**Comment by masvelio** [comment]
I would not mix size with the width, especially that we have two properties already for button:
- buttonHeight which is kinda size
- buttonWidth which is narrow or wide
@martins87  We should add third option `full`  to `buttonWidth` and this way the button should take the entire container
