### ISSUE TITLE
Disabled Editor with Tooltip

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4377]
### Disabled Editor

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/75e9fd42-b63e-4769-a6d0-52b6e99831de)

- User story
    - As a user, I don’t want to error out when creating a thread or comment.
- Design specifications
    - Editor
        - Have the editor in a disabled state
        - Change user’s displayname copy color in ‘Comment as [displayname]’ to Neutrals/400 or #B2AFB4.
        - Use disabled state for ‘submit’ button.
    - Cursor
        - Change cursor to, cursor: not-allowed; when user hovers other any portion of the editor.
    - Tooltip copy: Join community to comment
- Behavior
    - Users can not use the editor until they have joined a community.
    - When a user hovers over any portion of the editor, cursor changes to cursor: not-allowed; and a tooltip appears that follows the cursor.

**Comment by masvelio** [comment]
@zakhap @meeshlin @jessmart1213 
1. I already worked on Quill [in other PR](https://github.com/hicommonwealth/commonwealth/pull/4359), which is based on [this figma file](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=337%3A3536&mode=design&t=eS1RjfyIoa5agT5T-1). Again, I can see inconsistency in the designs (editor toolbar, right hand icons, disabled state). I would love to see an agreement on which quill design is the source of truth. Please take a look and play around on https://commonwealth-demo.herokuapp.com/components and at the very bottom of the page you can find new version of the editor with updated icons, colors and state. I would opt to stick with this design.
2. This is a new tooltip, but we didn't implemented it yet. Do we want to deliver this #4123 first or use the old tooltip here and swap it later? [As we talked on Slack](https://commonxyz.slack.com/archives/C05CHATCCUV/p1688046769984459), we still need to decide if we want to keep going with MuiBase or start using Radix.
3. Keep in mind that the tooltip which follows the mouse is not native behaviour of any library (mui base, radix etc). We have to create custom solution for that. It should not be high lift to create it but probably can produce some edge cases (eg with proper positioning). Just wanted to let you know that this is doable but makes things a bit more complicated.
4. Should the tooltip appear when I hover over the `Submit` button?

**Comment by jessmart1213** [comment]
Responding to @masvelio @zakhap 

> Let us not add new behavior to the default tooltip at this time. Unless design (@jessmart1213) thinks it is crucial here, we should add that as a later update to our tooltip component.

Let's not implement the cursor following the tooltip behavior.

Responding to 

> Should the tooltip appear when I hover over the Submit button?

Taking from Meesh's feedback, let's not have a tooltip over the Submit button. The not-allowed cursor should be fine.

**Comment by jessmart1213** [comment]
I would be fine with having the older tooltips, but will default to @zakhap

**Comment by masvelio** [comment]
@martins87 to avoid conflicts it should be started only after merging #4380

**Comment by martins87** [comment]
> @martins87 to avoid conflicts it should be started only after merging #4380

Ok.
