### ISSUE TITLE
Disable Thread Actions if not Joined Community

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4378]
## Description

- Disable Thread actions if not a joined community member.

### Disabled thread actions

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/10642763-b9ff-43c5-bc79-d647ef5d7be3)

- User story
    - As a user, I need to know that I must join a community to participate in any way.
- Design specifications
    - Thread Action CTAs
        - Change to disabled states
        - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘[🟢 Thread Actions](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707%3A11225&mode=design&t=HyobTlUa6qSug8qe-1)’ > and look for disabled state.
    - Cursor
        - Change cursor to, cursor: not-allowed;
            
            ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/0323fcd2-59de-4f05-90ff-97bba461cba0)
            
    - Tooltip
        - Copy: Join community to [thread action cta]
            
            ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/85fb97b7-1163-4e84-8ddc-529844a3841d)
            
- Behavior
    - Actions non-joined community members can not do are disabled and have the cursor: not-allowed; triggered on hover.
        - Non-joined users CANNOT
            - Comment
            - Reply
            - Upvote
            - Cant edit or delete or do any action under the overflow cta (ellipsis)
            - Admin actions
        - Non-joined users CAN
            - view the discussion
            - Share the thread
            - Share a comment or reply
            - Sort comments
            - Hide replies by default
            - Hide spam by default
            - Hide and show replies
            - Show X more replies

**Comment by masvelio** [comment]
@zakhap 
1. Similar situation with tooltip as in previous ticket 

> This is a new tooltip, but we didn't implemented it yet. Do we want to deliver this https://github.com/hicommonwealth/commonwealth/issues/4123 first or use the old tooltip here and swap it later? [As we talked on Slack](https://commonxyz.slack.com/archives/C05CHATCCUV/p1688046769984459), we still need to decide if we want to keep going with MuiBase or start using Radix.

2. We need #4358 to be merged in order to start working on this ticket!

**Comment by zakhap** [comment]
I will review #4358 today and make sure this is unblocked asap

**Comment by meeshlin** [comment]
1. Defaulting to y'all for the tooltip implementation. I will say, I'm not sure we need it for the `...` because users shouldn't even be seeing that unless they're an admin or the post creator. 

**Behavior**

**Comment by masvelio** [comment]
@martins87 to avoid conflicts it should be started only after merging #4380

**Comment by martins87** [comment]
> @martins87 to avoid conflicts it should be started only after merging #4380

I'll keep an eye on it. Thanks, Marcin.

**Comment by masvelio** [comment]
Bumping to 5. Spent a lot of time adjusting components and tiding things up and not even started implementing ACs. Eg we have 3 implementations of reaction button and the fourth was from new https://github.com/hicommonwealth/commonwealth/issues/4120 so decided to unify this. Also, new ThreadAction component has to be modified as not every case has been covered (eg for handling two icons in one button -- subscribe/unsubscribe or voted/unvoted). 

Draft PR #4521 but keep working on that
