### ISSUE TITLE
Flarum Database Import Script - Work Plan

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4384]
## Description
Following on our [spike investigation](https://github.com/hicommonwealth/commonwealth/issues/4352) we need to plan the scope of work to refactor our existing Discourse import script, (@gdjohnson _where_ is that located?) which takes in an sql database dump from a Discourse forum, and imports that community into Common. (NB. The current script is janky in that it requires post-hoc database surgery for the community to be up and running.) 

What's needed here is a complete scope of work plan for converting this database import script (which only works for Discourse) to be able to work for a "similar" sql database dump for a community using the Flarum forum platform. 

## Engineering Requirements
A document that outlines exactly all the steps needed (starting with just with the extant import script and a sample database dump from Flarum) to have a working import script for Flarum. 

Note we do not plan on doing this work ourselves, rather one of the communities expressing an interest in making this transition has said they would do the development work to execute to refactor/create the working script. So, this ticket scope is to create the document we can send them to get them started (by which we mean, self-contained instructions expected to be sufficient for completion.) 

## Acceptance Criteria
Document is delivered to this community, and they confirm it is sufficient for them to execute. (tbh, if they have good engineers on this, all they should need is a document surfacing the steps and any additional nuance they would otherwise have had to guess at, or have common knowledge.

**Comment by ianrowan** [comment]
Here is the first draft of this document:

https://docs.google.com/document/d/1DI2cTGLJoSMTU3uMnBEnV5WsGApqtcj01NyJTefd5es/edit?usp=sharing

In summary I:

- Provided a researched mapping of Flarum tables to Common tables
- Provided a link to the discourse import and a summary of how to navigate 
- Provide some mock steps to follow to build a migration tool
- Provided a summary of requirements

What I'm expecting them to do
- Research/implement the specifics of data relationships(ie column by column + foreign keys) I think any competent dev can take these two db dumps and infer what needs to be bridged given the info provided. 
- Host a flarum DB instance or provide credentials for one.  

It might need some polishing but wanted to confirm approach. There are some items here that I dont know/have access to:

- Providing Access to a Common Db dump
- Providing Access to the Discourse import script

**Comment by CowMuon** [comment]
As discussed with Growth, Synapse is planning to do a pit stop run via Discourse, since there are already ETLs for both sides of that operation, rather than writing a new ETL. 

Bummer as we were looking forward to working with them! (As I think were some other DAOs that are also interested in this.)
