### ISSUE TITLE
Update Neutral-500

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4385]
## Engineering Requirements

- Update Color.scss variable `$neutral-500` to be `#757575`.

## Acceptance Criteria

- Color updated wherever it is used.

**Comment by CowMuon** [comment]
Grab-n-go for @Miaplacidus or @martins87 (should be _less_ than a 1 pointer.)

**Comment by martins87** [comment]
> Grab-n-go for @Miaplacidus or @martins87 (should be _less_ than a 1 pointer.)

Done.
