### ISSUE TITLE
Discobot deployment and ops setup

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#4399]
# Summary

This task will encompass the deployment of the discord bot service. At a high level this includes deploying the Listener service and an instance of the consumer service, both connected to our RabbitMQ instance. Expected tasks include

- [x] Creation of 2 new dynos(within a new heroku app)
- [x] Configuration of environment variables for new dyno(incl any configuration on the DB side to allow the bot to use the DB). Variable setup will be documented 
- [x] Creation of Bot's CW API key(to access new bot endpoints) on CW side, then in config of consumer dyno
- [x] Dyno stability configuration(auto restart, monitoring, etc). This is most important for the listener.

**Comment by CowMuon** [comment]
This is still showing as in backlog?

**Comment by CowMuon** [comment]
Given we shipped this, presumption is scope of work in this issue is complete. I still have some outstanding questions around how we track our environment variables, as this is an area where we have had communication drops and oversights.
