### ISSUE TITLE
Edgeware Login/Join Community Failure

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4401]
"BD reports"* a user is unable to join Edgeware community. This is occurring AFTER they have logged in. This was partially addressed by #4154, which fixed the polkadot login, but join community is still broken.

To reproduce: https://commonxyz.slack.com/files/U04N23Y7BBR/F05BK0CE4JY/screen-recording1.webm

**Acceptance Criteria:**
After logging in with polkadot, users are able to successfully join the Edgeware forum and all other substrate forums.

**Comment by timolegros** [comment]
@alexyoung23j The bug is #3747 - there is a stale open PR #3847. I proposed some alternate solutions in a comment on the PR. I confirmed yesterday that the issue linked is the source of the bug.

**Comment by jnaviask** [comment]
Direct link to Tim's comment: https://github.com/hicommonwealth/commonwealth/pull/3847#issuecomment-1620456200

**Comment by alexyoung23j** [comment]
Good catch.

**Comment by CowMuon** [comment]
("BD Reports" = everyone should be completely aware of this, as Edgeware has been broken for a very long time. Just making explicitly clear in this ticket scope this is not a new report, this is an issue they have been complaining about for literally weeks now.
