### ISSUE TITLE
Design System: Banners and Alerts

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#4407]
## Description

Some initial work on `banners and alerts` will be done in #4380 so make sure that the code is aligned. Extend or subsume that existing work.

[DevMode Figma Link
](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=793%3A10990&mode=dev)

## Specifications:
There are 5 types of banners: `default`, `informational`, `success`, `warning`, and `error`.
- Each type has corresponding colors associated.
- The `Error` type also specifies the "destructive" button type when there is a primary action. 

**The Component should have options for the following:** 
- type: takes the above options (required)
- title: string (required)
- body: string, (required)
- primary action label?, string (optionally rendered, requires both label + callback)
- primary action callback?, function (optionally rendered, requires both label + callback)
- secondary action label + callback? (optionally rendered, requires both label + callback)

**behaviors**: 
- clicking the X in the corner, should close the banner. the banner should return, by default, on refresh + whenever the conditions for presenting it are still valid.
  - in the future, we should figure out a way to specify timeframes for when a banner should return as an optional value to the banner component. 
- The Primary Action Button should trigger the primary action and if successful, close the banner.
- The Secondary Action button should trigger the secondary action and, if successful, close the banner. 
- The banner should stretch to fit the width of the container it is in.

## Acceptance Criteria

- All 5 types of banners are implemented as options within a single banner component.
- The required and optional arguments to the component are implemented. 
- The colors and buttons are correct for each type.
- The banner stretches to fit the width of its parent container.

**Comment by CowMuon** [comment]
The next type needed here (after **default**, which should be done as part of CTA) is **informative** 

Main difference between each of the types is color. Estimating this (remaining 4 types)

**Comment by jnaviask** [comment]
For @Miaplacidus to implement + pairing with @masvelio as needed.

**Comment by CowMuon** [comment]
Would like @masvelio & @Miaplacidus to pair on this please

**Comment by masvelio** [comment]
@jnaviask @Miaplacidus because most of the work I have done during the previous PRs, and now I am also adding some code to the banners in terms of https://github.com/hicommonwealth/commonwealth/issues/4413, I will take care of this entirely
