### ISSUE TITLE
Lists don't work as expected in Quill x Markdown

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#4427]
Current behaviour :
When the markdown editor is empty, selecting ordered, numbered or todo list does nothing. It works only when the user selects the text and then click one of those three option.

https://github.com/hicommonwealth/commonwealth/assets/14819225/0cbba304-ea6f-4e9e-8617-68b1bdec11b2

Desired behaviour: 
It should work similar way as the editor in github. Clicking back and forth should select and unselect choosen list syntax.

https://github.com/hicommonwealth/commonwealth/assets/14819225/dfb2fd0d-0073-4331-8897-6f9eb9b3027f

**Comment by lzach83** [comment]
@masvelio I can't trigger this behavior locally, is this ticket still needed? 

cc: @ilijabojanovic 

loom: https://www.loom.com/share/c782b17ca4bf495bbcfd3d6d2110a682?sid=94f4983a-f75a-47a3-8006-35e96bd361d8

**Comment by masvelio** [comment]
not reproducible anymore on master and QA env
