### ISSUE TITLE
Server side loading on proposal + council pages

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#443]
Load from the client side after proposal data has been initially loaded.

Wait times are around 6 seconds right now.

Check back in after #384 and #444 have been addressed. We may or may not need this

**Comment by jnaviask** [comment]
How we doing on this?

**Comment by timolegros** [comment]
We don't have council pages anymore and we load EVM proposals from the server. Cosmos proposals are cached on the server as well.
