### ISSUE TITLE
Investigate Stage Tags Logic

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4451]
~~BD~~ Growth has noticed that the first stage tag option on a thread never has a tag that is actually displayed. 

Note that the "Pre-voting" tag is visible, but if the stage is changed to "Discussion" (the first stage option in the dropdown), no such tag is present.
![Image](https://github.com/hicommonwealth/commonwealth/assets/31940965/478c44bf-6439-41ce-8d5a-88485cdad25b)

It is unclear whether this was intentional or the result of some hacky logic. We should investigate the reason this is occurring. 

@zakhap can you provide some insight about the decision/lack of decision on this functionality?

**Comment by CowMuon** [comment]
(It was completely intentional.)

**Comment by jnaviask** [comment]
We will open another ticket to clean up the stages feature. Thank you @raykyri for the context that, yes, not displaying the first stage was an intentional product decision.
