### ISSUE TITLE
Snapshot Proposal UI Copy Update

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4454]
Currently, the copy for a complete snapshot proposal reads "This poll is complete". It should read "This proposal is complete". 

This can be seen on the poll card in a thread view, as below: 

![Image](https://user-images.githubusercontent.com/31940965/252424812-e82f4283-85a1-4973-9e93-3739d8bcd3f8.png)

**Acceptance Criteria:**
The copy should read "this proposal is complete" when a completed snapshot proposal is being displayed by the PollCard.

**Comment by RhysCommonwealth** [comment]
@alexyoung23j (from Dillon), in the future, if we want non engineers to tackle this, we need to specify the exact file that this is in, or else it's way too much friction for anything to happen

**Comment by sachben91** [comment]
- [ ] The copy reads "this proposal is complete" when a completed snapshot proposal is being displayed by the PollCard.
