### ISSUE TITLE
[2.0 Site Integration]  - Alpha: On Chain Community Create

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4464]
## Description
We are in the process of revamping the 'create page' user experience, including a new "tab" feature on the page, assuming we've successfully integrated backend components for namespace + 4337 creation. This update will be released on `alpha`. The objective is to provide a more streamlined and user-friendly interface for our users.

## Engineering Requirements

This work should keep pace with and conform to any changes on production that touch the community creation flow. This includes but is not limited to #4533 and #4550.

## Deployment 

This ticket builds of of #4442 as a base branch, as that is the branch that implements the on chain flow

- Merge the "4337 + namespace creation" to "starter community".
- Correctly associate new community templates (if created) to a community, relevant only for Ticket 3
- Make it easy to add new "sub templates" to the relevant community creation pages, and ensuring that the on-chain community creation process is easy / seamless.
- Redesign the "create new" form into a three-step process divided by horizontal CWDividers, ensuring the layout is consistent with the "Create Template flow". That is, one column with several subsections split by horizontal dividers.
- The steps in the process should include:
  - Step 1: Basic settings (name, description, image upload)
  - Step 2: Membership access
  - Step 3: Seed your community wallet (optional)
- The other 'create community' subpages might need to be updated for consistency. (Refer to this design: https://www.figma.com/file/xXjVv3sPgaD9DjCmR0EGlt/Action-Templates?type=design&node-id=256-27987&mode=dev)

## Acceptance Criteria

- Creating a community remains seamless and "admins and other offchain elements are added"

**Ticket 1:** Layout / Navigation Changes
- On the 'create page', we should include an "in community sidebar" into the page.
- This sidebar should replace the current tabs, enabling the user to switch between different options.
- The sidebar should rename the newly added namespace + 4337 "form" to "Create". This should be the default page that people land on.
- All other existing options should be under 'link existing token or DAO' (Solana, Cosmos, etc.)

**Ticket 2: Update the Copy and layout of the create community pages, without updating logic**

- **Title**: Create a community
  - Subheading: Your community comes with a community wallet to pool your ideas, resources, and more. Create your community wallet with a few clicks.
- **Step 1**: The Basics
  - Subheading: Set a name, description, and image upload
  - Form: Include the relevant form components
- **Step 2**: Set membership access—
  - Subheading: Invite specific friends, or gate access using NFT ownership, anyone with X type of address
  - Form: Select List, that expands when clicked
  - Options: Currently only 1 => anyone with X type of address (allows users to choose the base chain, for now this should be limited to EVM based chains)
- **Step 3**: Seed your community wallet (optional): 
  - Subheading: choose to link an existing Gnosis Safe, or fund with some of your assets.
  - Form: Select List, in line (not dropdown). When an option is selected, the correct template should appear in line.
  - Choice 1 /  "Template 1: " - includes a transfer to the CREATE2 address of the Community Wallet send money to this.
  - Choice 2 /  "Template 2: " - prompts user (must be owner on multisig), but sends proposal/tx to Multisig to "withdraw all" to the CREATE2 address of the community Wallet
  - Choice 3 /  "Template 3: " - creates a proposal to send to a Compound DAO Contract, with a request for X amount of funds.

**Ticket 3: Update the Logic of Steps 2 and 3, to include relevant templates or on chain actions.**

## Current Implementation Details
This update is loosely related to the [current PRD](https://www.notion.so/buildcommon/Actually-Good-Community-Creation-20a0b9b071d243ceab7bf47e63ad96be?pvs=4), this work, in particular the "default decisions" around layout / copy as they ship to prod are subject to design revision, therefore those changes are meant to be minimal. Note, the PRD itself is related to reliability and bugs as well. I do not see it overlap there either.

This work will be used as discovery / exploration after it gets merged to Alpha.

----
Out of scope: 
To circle back (how we handle) "linking existing communities" => I think it can follow the same pattern, copy and more.

**Comment by ianrowan** [comment]
@dillchen I think we might need a rough sketch of what this should look like. Mainly just need context of what the 'sidebar' should look like. 

The multi-step form makes sense for the most part but mainly just that navigation point in ticket 1

**Comment by dillchen** [comment]
Gotcha, I’ll get u that

Sent via Superhuman iOS ***@***.***>

**Comment by ianrowan** [comment]
@dillchen Do you have an example of this type of component? 
'Form: Select List, in line (not dropdown). When an option is selected, the correct template should appear in line.'

**Comment by dillchen** [comment]
Status Update on Friday:
- 1 pointer for the navigation
- Need to plugin + use the contracts

**Comment by dillchen** [comment]
Added this line here

> @ianrowan adding this (ensure that create + quick switcher always stay up on root URL on desktop) after https://github.com/hicommonwealth/commonwealth/issues/4115 is merged, users will be able to hide it

**Comment by dillchen** [comment]
Needs feature flag
