### ISSUE TITLE
dydx and aave proposals error: address undefined

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4466]
Steps to reproduce:

1. Visit dydx or aave community
2. Visit any proposal in those communities

The page will never load- you will see that an infinite cow is present. The following error is logged:

![Image](https://user-images.githubusercontent.com/31940965/252720403-5adfe4a0-8940-4ecd-913e-4fc0d6b3c588.png)

Potentially related to #4465 

**Acceptance Criteria:**
Aave and dydx proposals should load as expected.

**Comment by CowMuon** [comment]
@alexyoung23j  please confirm this is 1 point estimate.

**Comment by alexyoung23j** [comment]
@CowMuon Would need to do a deeper dive, but likely yes

**Comment by alexyoung23j** [comment]
Error message (above screenshot) is no longer appearing, but infinite cow remains nonetheless. Diagnosing.
