### ISSUE TITLE
Archive/spam routes should be properly RESTful

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4467]
## Description
Currently we have a PATCH route for updating threads and comments, but we also have /markThreadAsSpam, /unmarkThreadAsSpam, /markCommentAsSpam, /unmarkCommentAsSpam and soon /archiveThread and /unarchiveThread. These routes should all be subsumed by PATCH /thread/:id and PATCH /comment/:id, as they are updates to the state of the object. The logic for each should otherwise remain the same, including role-based checks on the requester.

## Engineering Requirements

- Marking threads/comments as spam and archiving threads/comments should be performed via PATCH.

## Acceptance Criteria

No changes to product functionality or regressions.

**Comment by rbennettcw** [comment]
As a result of additional context (these routes use server-side data to perform mutations), the routes will be updated like so:

- Mark thread as spam: `PUT /threads/:id/spam`
- Unmark thread as spam: `DELETE /threads/:id/spam`
- Mark comment as spam: `PUT /comments/:id/spam`
- Unmark comment as spam: `DELETE /comments/:id/spam` 
- Archive thread: `PUT /threads/:id/archive`
- Unarchive thread: `DELETE /threads/:id/archive`

cc @Miaplacidus

**Comment by rbennettcw** [comment]
The backend PR (#4440) is good to go.

All aforementioned routes updated + spam works without regressions.

cc @jnaviask
