### ISSUE TITLE
Cosmos Rate Limiting Problem

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4468]
It appears that we are often getting rate limited when displaying cosmos proposals (429 errors). Not easy to reproduce reliably- Tim suspects that this is occurring when we have enough users simultaneously trying to view the data.

We need to investigate a solution to this. Dillon suggests Mintscan, setting up our own infra, etc. 

This ticket will involve a thorough research pass at the problem and some proposed solutions to move forward with.

**Comment by mhagel** [comment]
This will be addressed in #4362
