### ISSUE TITLE
DiscoBot Follow Ups

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4469]
Based on the X functional sync, there are some updates to the discobot that need to be made:

- [x] Add a tag to the threads and comments to indicate that the thread is coming from Discobot
- [x] Show discord author to the side of the "discord bot" User component
- [x] Make posts locked
- [x] Add a link to the forum post as a comment 
- [x] Switching topic connection on a channel causing duplicates
- [x] Buggy connection- investigating further
- [x] Switching channel connections refresh not working

**Comment by zakhap** [comment]
An addendum to the current work: 
- [ ] The thread metadata row should include the following information: `[avatar] Disco Bot [dot] discordUsername [discord tag] [dot] Bridged from Discord [dot] date [etc…]`

While the image below does **not** reflect the request above exactly, it can be used as guidance for how to display the discord tag as well as the "bridged from discord" addition:
![Screen Shot 2023-07-12 at 1 52 38 PM](https://github.com/hicommonwealth/commonwealth/assets/16248081/e6555ab9-3aba-4562-8063-138d34faab03)

**Comment by alexyoung23j** [comment]
Further work is detailed [here](https://docs.google.com/document/d/1ulwylKIzCThmiLWOjXPgOv8MLNRg3b-fAplyTza1gIk/edit)
