### ISSUE TITLE
Cosmos gov - cache-warming

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4473]
AC:
- Proposals load quickly

Details:
- Regularly refresh Redis cache so that users do not have to endure the slow uncached load time.

**Comment by mhagel** [comment]
Part of solving #4362 

@NakulManchanda Could you add some brief recommendations here?

**Comment by mhagel** [comment]
@NakulManchanda 
Where would this daemon run? 
Is it realistic to have it run for every cosmos chain?
Is this a good solution for our use case?:

_Refresh every (Cosmos) community's cache every X minutes_


Maybe we should move away from TTL and cache-warming, and use a write-through strategy instead?

**Comment by NakulManchanda** [comment]
> Refresh every (Cosmos) community's cache every X minutes

How many such communities are there?
Daemon will run on main server, basically its just a wrapper over js `setInterval` function
**We can create separate heroku worker for such updates if we like**

> Is this a good solution for our use case?:

Frankly, i need to understand the use case first
- Are we solving for `rate limiting` or `performance`?
  As running background process will increase number of request not decrease.

**Comment by jnaviask** [comment]
We don't plan to create a specific cache warming solution at this time. Once we've diagnosed the underlying performance issues, we may re-evaluate whether cache warming is worthwhile, but for the time being, this ticket is closed.
