### ISSUE TITLE
Deleted threads still show loading state

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4476]
BD reports that deleted threads are still showing cow bobber loading states after being deleted.

Why it matters: Communities that use webhooks end up with an archive of dead links. 

To reproduce: [Example](https://commonwealth.im/oraichain/discussion/12144-oraidex-pools-and-apr-emissions)

**Acceptance Criteria:**
The page should display to a "404, page not found. Thread may be deleted" instead of the infinite cow.

**Comment by CowMuon** [comment]
What's the estimation here @alexyoung23jde? Also can we confirm this is a product bug? (viz. the backend route does not need need to be updated)

**Comment by alexyoung23j** [comment]
Should be a one pointer. Just checked, looks like the route is returning what we expect, so should be a client side fix.

**Comment by alexyoung23j** [comment]
Appears this is now broken again.
