### ISSUE TITLE
Bug: Admin Triple Dot Menu doesn't appear within Thread Page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4487]
## Description

**Bug as it is:**
- Admins + Moderators of communities cannot currently access the Admin Options popover menu on the thread page.
  - Site-admins do not have this problem.

**Expected Behavior:**
- As an admin or moderator, I should be able to access and use the designated actions in the `AdminActions` component menu within the `Options` row at the bottom of the thread page.

**Where it Should Show up:**
<img width="904" alt="Screen Shot 2023-07-12 at 4 09 20 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/9e7a93c9-49e1-47d1-bdd3-7b97202e7eae">

**Similar to the Thread Listing page triple dot!**
<img width="813" alt="Screen Shot 2023-07-12 at 4 09 25 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/efd3ca54-f355-464f-9fa4-c67aacbf0571">

## Acceptance Criteria

- The Admin Options Triple Dot + Menu appears on the Thread page for Admins + Mods, not just site-admins.

**Comment by CowMuon** [comment]
Hopscotch.
