### ISSUE TITLE
Cache Cosmos Proposals longer

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4495]
AC:

- cache individual proposal requests for a longer time (1 week?) to ensure they load faster for most users
- review and increase cache TTLs where helpful for other Cosmos requests

**Comment by CowMuon** [comment]
Would be helpful to know what current TLL's are? Also, some question why caches are being expired based on time? Is the cached resource expected to have changed during the TTL period (if it's set too high?) @mhagel
