### ISSUE TITLE
A new user cannot post or contribute to a discussion.

### ISSUE THREAD

**Issue by ChinmayPatel** [hicommonwealth/commonwealth#450]
## Description
Bug: A new user cannot post or contribute to a discussion. 

## *Who* is the bug affecting?
Pretty much all the new users. I've attempted to create a new account with Github, Email, and Polkadot.js extension. The issue persist on all of them.

## *What* is affected by this bug?
- Create a new post
- Contribute to a discussion

## *When* does this occur?
Every few seconds (almost 30 seconds), an error message is shown. Please see the screenshot. 
![edgeware](https://user-images.githubusercontent.com/684063/85862783-388a9000-b790-11ea-8051-e5d297a04ad7.png)

###  New post page
It keeps saying that I need to login, but I'm already logged in.
![new-post](https://user-images.githubusercontent.com/684063/85862731-2872b080-b790-11ea-9eb3-165679927530.png)

### New discussion (thread) page 
All the fields are disabled and I can't click anywhere.
![new-discussion](https://user-images.githubusercontent.com/684063/85862748-2e689180-b790-11ea-954d-11c3a0f4c003.png)

## *How* do we replicate the issue?
- Create an account using email. 
- Click on the login link received in the email. 
- Go to create a post.
- Or go to create a new thread.

## Expected behavior (i.e. solution)
A user should be able to post or discuss on the platform.

## Other Comments
None.

**Comment by ChinmayPatel** [comment]
Hi guys, any updates on this one?

**Comment by jnaviask** [comment]
On the bottom two screenshots, you need to link an address to your account in order to create a post.

I will look into the "InvalidStateError" issue.

**Comment by jnaviask** [comment]
Using Firefox, I made a new account and linked an address, and I was able to successfully post a comment on a thread.

The InvalidStateError did happen randomly as I was linking the address -- my guess is it relates to the websocket connection -- but I was unable to reliably trigger it, it only happened that one time.

**Comment by raykyri** [comment]
It seems like this was resolved as you've got a live thread on the site. Hopefully the redesign (launching soon) will make this process a little easier - but thanks for creating this issue and please let me know if it happens again.
