### ISSUE TITLE
Create Design Branch and Associated App

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#4515]
A new branch called 'design' will house all of the design work being developed. This branch will be utilized almost exclusively by the design team. Pushing to this branch will result in an automatic deploy (via Github Actions) to a Heroku app where Meesh and Zak can review the design team's work. 

@jnaviask @MuonShot - tagging for review

**Comment by jnaviask** [comment]
As discussed, we will be using `demo` for this purpose.
