### ISSUE TITLE
Cache other Cosmos data client-side

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4527]
## Description

Implement client-side caching for Cosmos data fetches.

## Engineering Requirements

- Leverage React Query to store the following for a user's visited communities:
    - individual proposal page 
    - chain params (pool, staking, etc)
    - proposal votes, deposit, and tally
    - anything else that can be reasonably cached

## Acceptance Criteria

As a Cosmos community member, when I visit {chain}/proposals or chain/proposal/{id}, I would like previously-fetched data to be available immediately while new data is loaded in the background.

## Additional context

This should be implemented after #4561

**Comment by jnaviask** [comment]
Why not vote data?

**Comment by mhagel** [comment]
>Why not vote data?

Nevermind on that. Thinking out loud, but I see React Query will work for most cases.

**Comment by jnaviask** [comment]
Can you put up a point estimate?

**Comment by mhagel** [comment]
I'm thinking this should include a refactor of how we fetch proposals. Move from chain `init` to the proposals.ts page and use React Query on this fetch. Lazy-load proposals only when needed. This will have benefits in individual proposal pages where we chain init and fetch proposals we don't need.

I didn't consider this in my initial estimate. I will bump it to an 8. I will also think about breaking this up into smaller chunks.

**Comment by jnaviask** [comment]
@mhagel will this refactor just be for Cosmos, or can we extend the architectural changes across all proposal controllers? We can deprecate some of the complicated computations for substrate in particular if it makes it easier.

**Comment by mhagel** [comment]
@jnaviask 
I think it feels right to start with Cosmos, especially since we already have cosmos lazy-loading hooks available in the proposals page. 

It may make sense to make those hooks more generalized getProposals (which then call the appropriate chain fetch hook). But I think it would slow this ticket down a lot if we try to do that for all chains. If I dig in and find otherwise, I will circle back on this.

**Comment by mhagel** [comment]
To break this up,

#4561 will be first - proposals-by-type to React Query (5)
Then this ticket: other queries. (3)

Lowering this estimate to 3, accordingly.

**Comment by mhagel** [comment]
Questions:

There are some fields on the gov controller that we don't seem to use. Can we delete them and the requests for them? :
```
  private _votingPeriodS: number;
  private _yesThreshold: number;
  private _vetoThreshold: number;
  private _maxDepositPeriodS: number;
```

Is it ok to refactor the ViewProposalPage to load proposal from RQ?

**Comment by CowMuon** [comment]
I see that we are not blocked here given answers coming out of discussion. 

JTN in general would like us to follow the 2 step model, where legacy functions are first deprecated, and then removed in a separate, subsequent release. 

We have only just started using releases, so just to surface this as general goal, rather than as strict protocol to be adhered to. In the case at hand, we do need 100% certainty the named functions are no longer used or needed.  

Let's have the non-blocking discussion during office hours on 9/7, with target of merging this PR into release `0.6.8`

**Comment by CowMuon** [comment]
(@gdjohnson To make sure our deprecation model is documented.)

**Comment by gdjohnson** [comment]
@CowMuon Just the docs are as clear as possible, what sorts of code-actions does deprecation typically entail, as contrasted with deletion?

Reading this thread history, my guess would be that when deprecating, all _invocations_ of code are removed, but the invoked code itself remains. Is that a fair summary?
