### ISSUE TITLE
Audit / Review Environmental Variables 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4534]
## Description
Placeholder stub for auditing environmental variables, aligning all environments and documenting on wiki. 
## Engineering Requirements

t/k

**Comment by gdjohnson** [comment]
This seems like a good opportunity to create documentation for .env variables (e.g. so engineers know what they need, when working in different areas of the codebase). In that regard, meaningfully connected with #4999, our "develop onboarding docs" ticket.

**Comment by gdjohnson** [comment]
Marking this as closed, and proceeding with #5227, which will result in an opened PR.
