### ISSUE TITLE
Script to compress existing images

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4538]
## Description
Many images prior to #4238 are still on the site + may be large both in filesize and dimensions. We should write a script to compress these images.

## Engineering Requirements
Script which compresses existing images on site to 1000x1000 and webp so that cloudflare magic can kick in.

## Acceptance Criteria

No user-facing changes.

**Comment by kurtisassad** [comment]
Blocked because cloudflare blocks the script when it makes too many requests. Investigation here:
https://github.com/hicommonwealth/commonwealth/issues/4857

**Comment by kurtisassad** [comment]
Unblocked. I think I can just read from the aws bucket directly, avoiding the captcha
