### ISSUE TITLE
Topics contents disappear when clicking rapidly on sidebar

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4541]
## Description
See loom: https://www.loom.com/share/b0d0594597f84c08a126cc2f674bfe4a

## Acceptance Criteria

Topics contents should not disappear regardless of how rapidly a user clicks around on the sidebar.

**Comment by alexyoung23j** [comment]
@mzparacha Has a fix for this in #4588 (we have confirmed the fix works).

**Comment by mzparacha** [comment]
This is fixed in #4545
