### ISSUE TITLE
Improve Empty Loading States on Governance/Proposal Pages

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4546]
_Note: Similar work to #4197, but for governance-related pages_

Goal: Improve the loading state of Governance/Proposal pages, both listing pages + the specific proposal pages. This should provide a better user experience as the page will appear to populate. 

### **Acceptance Criteria:**
**Apply improved loading states for the following pages:** 
  - [x] Snapshot proposals listing page, [live site example](https://commonwealth.im/dydx/snapshot/dydxgov.eth), `/dydx/snapshot/dydxgov.eth`
  - [x] Multiple Snapshot Spaces page: if a community has multiple snapshot spaces connected, then there is a selection page that appears.
  - [x] View Snapshot Proposal Page: [live example](https://commonwealth.im/dydx/snapshot/dydxgov.eth/0x0ea7f312f0970e0a9e4e34bd38af59dd79babcd11169282971df1fc210228359). 
  - [ ] View Proposal Page (for non-snapshot proposals): **[example](https://commonwealth.im/kyve/proposal/7-efficient-frontier-kyve-market-making-proposal)**

**Comment by CowMuon** [comment]
This should probably be a bucket ticket, breaking this out into 4 tickets.

**Comment by mzparacha** [comment]
> This should probably be a bucket ticket, breaking this out into 4 tickets.

Just to confirm, are we going to make 4 tickets?

**Comment by mzparacha** [comment]
The first 3 checklist items are done. For the 4th one, Tim was working on a refactor in https://github.com/hicommonwealth/commonwealth/pull/4025, we had a chat to not do the view proposals page ATM
> View Proposal Page (for non-snapshot proposals): [example](https://commonwealth.im/kyve/proposal/7-efficient-frontier-kyve-market-making-proposal)

**Comment by jnaviask** [comment]
Closing as full scope of work is complete or not planned.
