### ISSUE TITLE
Improve Sidebar Loading

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4548]
## Description

Introduce an interstitial loading state to the sidebar so that we can load it more quickly without necessary content to hydrate it.

We want the "in community" sidebar to load as soon as it can, shortly after the top nav and quick switcher (leftmost sidebar).

Goal: Improve the perceived load time and whitespace on screen around the sidebar and navigation within the community.

## Acceptance Criteria

- [x] The sidebar loads first with an interstitial state as soon as possible, without the sidebar content, and then hydrates later. 

## Additional context

Preliminary conversations occurred on ticket #4311 which has been closed.

**Comment by mzparacha** [comment]
@zakhap bump on [this](https://github.com/hicommonwealth/commonwealth/issues/4548#issuecomment-1669635236).

**Comment by zakhap** [comment]
For me, the sidebar loads a few seconds after the quickswitcher and top nav appear. 
The goal would be for the sidebar to load more immediately with the loading/interstitial state, prior to the rest of the content.

https://github.com/hicommonwealth/commonwealth/assets/16248081/a06c0f38-f5b8-4a69-b488-ea07401833d7

**Comment by mzparacha** [comment]
I added skeleton loader for sidebar in the same pr https://github.com/hicommonwealth/commonwealth/pull/4776.

cc: @dillchen
