### ISSUE TITLE
Fix UI mystery affordance 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4551]
## Describe the bug
QA noticed we have a new "weird" visual element which is not supposed to be there. 

## To Reproduce
Please see [Zak's comment on PR 4258](https://github.com/hicommonwealth/commonwealth/pull/4517#issuecomment-1644174258)

## Expected behavior
The weird green thing is gone. Also, we understand what happened. 

## Additional context
t/k

**Comment by alexyoung23j** [comment]
@CowMuon This is actually a production bug. See reproduction below. This must have been caused by a different PR.

https://github.com/hicommonwealth/commonwealth/assets/31940965/45708047-a951-4443-8633-b5778f766ab7

**Comment by alexyoung23j** [comment]
Fixed by #4552

**Comment by CowMuon** [comment]
> Fixed by #4552 

Then please add the branch under development, so the issue will automatically be closed @alexyoung23j
