### ISSUE TITLE
🎯 Add iOS Magic

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4554]
**Description:** 

- Gets iOS Magic Login Working (across all devices)

This task involves several crucial updates to get the iOS magic login working as options for our mobile PWA

**Note:** We should discuss the security implications of these changes with the team.

**Acceptance Criteria:**

1. As a user, I should be able to log in using Magic SSO options on mobile and see the app in the logged-in state.
2. On mobile, I should see the Apple iOS login option on apple browsers + pwa

**Engineering Considerations:**

**Product Considerations**

There are no product improvements on this ticket noted. Please use #4633 to log any (small or large) improvements to login flow on mobile should be. There are currently 5 - 7 small items, and several more not written down)

**Later**
- [ ] #5320

<sub>[COM-13](https://linear.app/hicommon/issue/COM-13/[login]-🎯-add-ios-magic)</sub>

**Comment by CowMuon** [comment]
Implementation from last summer out of sync with current designs. Superseded by #6509
