### ISSUE TITLE
Remove attachments from API

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4555]
There are currently references to "attachments" in the API (particularly when creating a comment).

We don't use the `Attachments` table apparently.
- The quill editor uses s3 file uploads and URLs placed in richtext/markdown.
- The DB contains only a few entries from 2019, suggesting that this table is obsolete.

## Acceptance Criteria
- Remove all code references of attachments
- Add a migration to remove the `Attachments` table

**Comment by rbennettcw** [comment]
@jnaviask Please confirm that if we can/should remove attachments.

**Comment by jnaviask** [comment]
Have at it.
