### ISSUE TITLE
Removing reaction from thread causes invalid reacted state

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4556]
## Describe the bug

See loom: https://www.loom.com/share/cda7a3893f0c4a25850eaae6b9a20f4d

## To Reproduce

1. React to a thread from the topic view.
2. Click into the thread and un-react.
3. Click back onto the topic via the sidebar.
4. Click back into the thread -- you will see the reaction is still showing inside the thread.
5. Clicking to un-react again causes an error (invalid state)

## Expected behavior

Reacting to a thread and removing the react, from the topic or thread view, never causes an invalid state. The state of the react always matches.

**Comment by mzparacha** [comment]
Ok so this is a pretty weird bug, I did some digging and the state always updates correctly i.e when we remove the reaction, it's cleared from the thread reactions array. Logging the console also gives the same thing. But when we log the actual property it will still display even after removal. Example: 
```
console.log("thread => ", thread"); // the associatedReactions fields will not have the deleted reaction
console.log("thread.associatedReactions => ", thread.associatedReactions"); // this will still show the deleted reaction
```

Going to try more things
