### ISSUE TITLE
Add React Query to Cosmos Proposals fetches

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4561]
## Description

Implement client-side caching for Cosmos proposals-by-type fetches

## Engineering Requirements

- Remove proposals fetching from Cosmos chain init
- Use React Query on useGetCosmosProposals hooks to enable client-side caching

## Acceptance Criteria

As a Cosmos community member, when I visit {chain}/proposals, I would like previously-fetched content to be visible immediately while new data is loaded in the background.

## Additional context

Related to #4527

**Comment by CowMuon** [comment]
As discussed in parking lot we'll do this one first, then circle back on #4527
