### ISSUE TITLE
Reaction counter does not update correctly on rapid clicking

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4569]
## Describe the bug

Per @mzparacha: "the counter [is] not updating quickly if the reaction is added/removed very fast (but the blue highlight updates)"

## To Reproduce

Click rapidly on the reaction button and note the numeric result.

## Expected behavior

Reaction button should maintain proper state.

**Comment by mzparacha** [comment]
The issue is on both FE+BE. I tried to add a reaction quickly and it was there even after page reload (i.e API accepted double requests).

I have updated the FE side in [this commit](https://github.com/hicommonwealth/commonwealth/pull/4588/commits/c3447f68d65ef722a5bd78e07d382a87503f077e), @rbennettcw can you please check BE when you get a chance. 

cc: @jnaviask

**Comment by rbennettcw** [comment]
On the master branch, I've tested rapid clicking of the reaction button for threads and comments.

Locally with low latency, it works fine with rapid reactions. If I open the network tab and set speed to 3G (higher latency), then rapid reactions results in errors because of a race condition in the code that performs the wrong operation. This is expected behavior if we don't have UI logic in place to handle it nicely.

The backend code for creating/deleting reactions looks fine.

Is this an issue of latency or code?

**Comment by mzparacha** [comment]
Thanks for having a look @rbennettcw. With the react query migration, I believe the frontend state will mostly be unreliable if we have race conditions (which happen with slower internet as you mentioned).

I will try once again and will update here.

> Is this an issue of latency or code?
not sure, but looks like a state sync issue in frontend

**Comment by mzparacha** [comment]
Ok so I confirmed again and looks like a backend issue. I removed the guard clause in frontend that prevented multiple 'like' reactions API calls and just pressed the like button multiple times, and the API accepted those calls. Also they stayed there after reload the page (where we essentially get data from the api)


https://github.com/hicommonwealth/commonwealth/assets/51641047/59835949-9bfb-47d5-9188-789377e0a5d8

**Comment by mzparacha** [comment]
bump @rbennettcw ^

**Comment by rbennettcw** [comment]
@mzparacha I just tested by performing the reaction API request outside of the browser multiple times (via Postman), and it doesn't show the same result– multiple reactions but only 1 is shown in the UI.

Is it possible that the frontend is caching the old reactions?

**Comment by rbennettcw** [comment]
You can confirm this by seeing that each of those payloads returned should show the same `id`, which would mean it's returning an existing reaction.

**Comment by mzparacha** [comment]
Thanks for having a look, i gave it a try again and it seems like it return unique ids. You would have to modify the frontend to only make `like` calls or try via a rest client. I applied this diff
```diff
--- a/packages/commonwealth/client/scripts/views/components/ReactionButton/helpers.tsx
+++ b/packages/commonwealth/client/scripts/views/components/ReactionButton/helpers.tsx
@@ -56,9 +56,10 @@ export const onReactionClick = (
   // if it's a community use the app.user.activeAccount.chain.id instead of author chain
   const chainId = app.activeChainId();
 
-  if (hasReacted) {
-    dislike(userAddress);
-  } else {
+  // if (hasReacted) {
+    // dislike(userAddress);
+  // } else {
+    console.log('coming here')
     like(chain, chainId, userAddress);
-  }
+  // }
 };
diff --git a/packages/commonwealth/client/scripts/views/pages/discussions/ThreadCard/ThreadOptions/ReactionButton/useReactionButton.tsx b/packages/commonwealth/client/scripts/views/pages/discussions/ThreadCard/ThreadOptions/ReactionButton/useReactionButton.tsx
index 3b87b1bf7..f3616fa1a 100644
--- a/packages/commonwealth/client/scripts/views/pages/discussions/ThreadCard/ThreadOptions/ReactionButton/useReactionButton.tsx
+++ b/packages/commonwealth/client/scripts/views/pages/discussions/ThreadCard/ThreadOptions/ReactionButton/useReactionButton.tsx
@@ -91,7 +91,7 @@ export const useReactionButton = (thread: Thread, setReactors) => {
       hasReacted ||
       isLoading
     ) {
-      return;
+      // return;
     }
 
     setIsLoading(true);
```

and this is the result (its giving unique ids in response)


https://github.com/hicommonwealth/commonwealth/assets/51641047/4351119d-b30a-4c98-8e66-28811309343e

**Comment by rbennettcw** [comment]
https://github.com/hicommonwealth/commonwealth/assets/126922418/d8ccbd8a-f947-4abe-8cc8-f7974c680043

Using the latest code on the master branch and removing the guard according to your instructions, I'm seeing that each response has the same ID and the UI doesn't show beyond a single reaction even after page refresh.

Can you show what the request payload looks like for 2 of those requests? If the request payload is different, then it's a hint of what the issue might be.

**Comment by mzparacha** [comment]
Thanks for the feedback again. I did some investigation yesterday but still got the same results. Will do some more digging' and update here

**Comment by NakulManchanda** [comment]
if you would like to test performance of reaction API in 

git checkout load-testing && cd load-testing
yarn install
yarn test:load #local

load-testing/.env file - 
get JWT token, thread on which you want to post comment and reaction, user_id of logged in user
```
JWT=ey
USER_ADDRESS=0x19
POST_THREAD_ID=11875
ENV=frack
REPORT_DIR=output
TEST_NAME=commonwealth-api-rw
```


This breaks the target environment - everytime we run load test
![image](https://github.com/hicommonwealth/commonwealth/assets/4791635/3acc8cd6-7a99-48d2-8d93-80b80b56747a)
![image](https://github.com/hicommonwealth/commonwealth/assets/4791635/7674e4f1-f314-4d51-832f-b307a8668b81)

Bottleneck seems to be
- emitNotification
- especially "Insert NotificationRead"

**Comment by NakulManchanda** [comment]
This PR has some bottleneck fixes:
[track-max-notid-by-user](https://github.com/hicommonwealth/commonwealth/pull/4179)
Would be great if @mzparacha @rbennettcw  if you can try your test locally against that branch as well

**Comment by mzparacha** [comment]
looks like you are getting new reaction's each time (ids are change)?

**Comment by NakulManchanda** [comment]
<img width="235" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/cce2f6e2-ef7d-4920-bc13-3747ab01f3c4">
9->10-11>12

**Comment by rbennettcw** [comment]
It appears that @NakulManchanda is deleting each reaction after creating it? (`DELETE /api/reactions/:id`)– which is why the ID is incrementing.

**Comment by rbennettcw** [comment]
Hey guys, if we're going to test this, I recommend we do so via process of elimination.

We should all be testing via an HTTP client like Postman and bypass the browser entirely so we can be sure if it's a frontend or backend issue.

In this video, I show the steps for doing so. It's really easy! In Chrome, copy the request as cURL. Paste it into Postman. Everything including auth token is populated automatically.

@mzparacha @NakulManchanda Please follow this and attempt to reproduce.

https://github.com/hicommonwealth/commonwealth/assets/126922418/3e6da2b8-8fe7-4f97-a445-2f33a1126136

**Comment by CowMuon** [comment]
Given that we are unable to reproduce, let's bounce this to backlog and circle back with Jake when he's back as to how the issue can be reproduced.

**Comment by CowMuon** [comment]
Given the prolix discourse here I'm not going to pull this into Cycle 6, but rather we can open a new issue to resolve. 

To recap: we have chased this bug across 2-3 tickets, each time reducing the time interval where "fast clicking" will produce the error. Since we don't have a solid hypothesis as the the root cause, my sense is the next fix may just push it below the threshold of observability, but without actually fixing the problem. 

My suggestion is we zoom out to understand the root cause architecturally. Or are we just missing client debouncing here? Will debouncing simply solve the problem? @rbennettcw @mzparacha

**Comment by mzparacha** [comment]
> My suggestion is we zoom out to understand the root cause architecturally. Or are we just missing client debouncing here? Will debouncing simply solve the problem? @rbennettcw @mzparacha

I think debouncing would be again
> my sense is the next fix may just push it below the threshold of observability, but without actually fixing the problem.

A proper solution would be to correctly update state in frontend along with correct API calls made from frontend. Since we now have #4545 merged now. It would be much simpler todo than before.

cc: @jnaviask @CowMuon
