### ISSUE TITLE
Refactor routes for fetching reactions

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4575]
There are some routes that should be updated to conform to RESTful endpoint patterns.

The old routes take both a thread ID and a comment ID, to return reaction data from either threads or comments. The RESTful approach would be to split out the routes so that they can work with either threads or comments, but not both.

## Acceptance Criteria:

Update the routes accordingly:

- Change `/reactionsCounts` to
  - `GET /threads/:id/reaction-counts`
  - `GET /comments/:id/reaction-counts`
  - `GET /proposals/:id/reaction-counts` (not sure if this is necessary, but the existing route uses proposal ID)
- Copy `/getReactions` as
  - `GET /threads/:id/reactions`
  - `GET /comments/:id/reactions` (already exists)

- Since `getReactions` is an external route, we should NOT remove it, but should still create RESTful internal routes based on it.
- Move all relevant business logic into the appropriate ServerControllerXXX file, consistent with the existing functions/handlers.
- Update the UI in all affected places, ensure no regressions

**Comment by rbennettcw** [comment]
It looks like this isn't needed anymore since Malik found a more efficient way to get this data using existing thread data.

**Comment by rbennettcw** [comment]
@mzparacha – just for confirmation, this work is now obsolete since the UI no longer uses `/reactionsCounts`, correct?

**Comment by mzparacha** [comment]
@rbennettcw yes, we completely removed `/reactionsCounts` in pr #4588 (issue #4545), when its merged we can completely remove this route.


> GET /comments/:id/reactions (already exists)

after #4545 I plan to remove this API call from the front end in favor of existing data. Which would improve performance as well. I would suggest any work on `GET /comments/:id/reactions` to maybe hold since we can clear this up.

**Comment by CowMuon** [comment]
We should be good here.

**Comment by mzparacha** [comment]
We can also remove the `GET /comments/:id/reactions` from API. https://github.com/hicommonwealth/commonwealth/issues/4662 just got merged and we are not using `GET /comments/:id/reactions` on the frontend anymore.

@CowMuon @jnaviask @rbennettcw
