### ISSUE TITLE
[Push Notifs] - Create Delivery Mechanisms

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4579]
### Description

This issue pertains to the extension of our current data model to support multiple delivery mechanisms for subscriptions. We aim to enable push notifications, and potentially other mechanisms, while providing users the ability to control delivery intervals for each subscription.

### Engineering Requirements

1. **Add the `DeliveryMechanism` model to our Sequelize schema.**
   This model should include fields for `type` (to denote the type of delivery mechanism), `identifier` (to store unique identifiers like FCM tokens for push notifications), and `user_id` (to associate the delivery mechanism with a user).

2. **Add the `SubscriptionDelivery` model to establish a many-to-many relationship between `Subscriptions` and `DeliveryMechanisms`.**

3. **Update the `Subscription` model to include the `interval` attribute.**
   This allows each subscription to have its own delivery interval.

4. **Create necessary database migration scripts to reflect these changes in our production database.**

5. **Update Sequelize associations to include the new `DeliveryMechanism` and `SubscriptionDelivery` models.**

6. **Update business logic to handle the creation, updating, and deletion of `DeliveryMechanism` and `SubscriptionDelivery` instances.**

7. **Adjust validation or serialization code to account for these changes.**

8. **Update any affected API endpoints to ensure they correctly handle new fields and associations.**

### Acceptance Criteria
- A user should be able to create, update, and delete delivery mechanisms.
- A user should be able to specify which delivery mechanisms are used for each subscription.
- A user should be able to specify a unique delivery interval for each subscription.

The system should be able to correctly deliver notifications based on the specified delivery mechanisms and intervals.

### Additional context

This change is motivated by the desire to support more granular control over notifications, as well as the ability to support multiple delivery mechanisms, including push notifications. The implementation must be thoroughly tested to ensure no existing functionality is affected.

**Comment by jnaviask** [comment]
Superseded by Notifications epic.
