### ISSUE TITLE
cw.path statsd variables incorrectly reporting new threads/comments/reactions API

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4587]
## Describe the bug
cw.path variables in router.ts are reporting each thread/comment/reaction as separate queries (i.e. the id is included within the metric path) rather than as aggregated "by route" queries.

## To Reproduce

See: https://us5.datadoghq.com/s/3c2fb346-1cad-11ed-9f61-da7ad0900005/um3-iks-di6 -- note how the reactions API is reported.

## Expected behavior

The reported paths should be aggregated across ids.

**Comment by rbennettcw** [comment]
This has turned out to not be so simple. The goal is to extract the original route pattern, rather than parse the request path.

So far I've been unable to access the route pattern via the request object inside the middleware, but there are other possible solutions.

**Comment by jnaviask** [comment]
@rbennettcw what solution(s) would you propose? None of the datadog configuration is set in stone; I hacked it together quickly to get a basic look at route usage. Totally open to better configurations that would enhance what we can do with the data.

**Comment by rbennettcw** [comment]
We may be able to use the `app` object to iterate over all routes and somehow inject the original route pattern into the request object, and use the existing StatsDController middleware to capture that.

I believe we're already doing something similar with the new `registerRoute` function.
