### ISSUE TITLE
🪣  DiscoBot Fastest Follows

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4601]
A growing list of things that ought to be addressed as soon as possible for DiscoBot.

- [x] #4612 
- [x] #4614 
- [x] #4610 
- [x] #4655
- [x] #4716 
- [x] #4721 
- [x] Verify that "create snapshot" one click works for discoposts. If not, ticket and create.
- [x] #4834 
- [ ] Start verification application again

**Comment by CowMuon** [comment]
Let's make this a bucket, and PR each item separately.

**Comment by alexyoung23j** [comment]
@dillchen Verification application content [here](https://www.notion.so/buildcommon/Discord-Bot-Verification-efe6d477c8ae4ab380a42a7325ea949d?pvs=4)

**Comment by jnaviask** [comment]
@alexyoung23j what's outstanding for this bucket to be marked closed?

**Comment by alexyoung23j** [comment]
@jnaviask Final item is just having Dillon start the discord bot verification process again (he's the only one who can start it as the account owner).
