### ISSUE TITLE
Audit routes for permissioning configuration

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4603]
## Description

We currently have ~150 routes registered as part of the Common API. Many of these routes require permissioning, as they are write / update routes.

The output of this ticket should be a categorization of routes by permission required, followed by one or several tickets to use a generic function or configuration (such as `validateOwner`) for authorizing requesters. This documentation will live as a wiki page to start with, and will eventually be moved into the repo itself, following #4350.

**Comment by gdjohnson** [comment]
It's pretty tricky to keep up with changes to the GitHub wiki. I can track and note changes on individual pages, but there are 93 pages to track. Devs have already been adding or changing information to the GitHub wiki and I'm using non-trivial amounts of time keeping it regularly sync'd against both these dev changes and against master—with obvious risks of losing documentation along the way.

If we could get #4350 merged, immediately deprecate the GitHub wiki, and complete these sorts of tasks in our new Docs-As-Code system, it would be tremendously helpful and let me get new work done. (I also can't improve any of our Wiki pages until the initial migration PR clears, as I want to ensure all non-obvious changes to information and wording are reviewed to ensure clarity and accuracy.)

**Comment by jnaviask** [comment]
Closing this ticket as not planned -- we will revisit route documentation after @ilijabojanovic creates OAS doc.
