### ISSUE TITLE
Comments Overhaul: Deeper Nesting

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4607]
## User Story

As a user, I want deeper nested replies so that I can reply directly to a particular comment. This would also give me a clear visual hierarchy of the thread. 

This above user story was implemented, however, the visual layout of the reply lines (vertical) and mobile handling were not considered at the time. This has led to some visual glitches on mobile as well as mediocre UX when you arrive at 8 levels deep and don't know why you can't reply deeper. Below are improvements to the above Story such that this is a more considered experience.

## Behavior
- 8 nested reply layers
- Once the 8th layer of replies is reached, the user will not be able to nest comments further. They can reply to the 7th layer but not to the 8th nested reply (clarified in the design further). 
  - Reply button will be disabled and there is a tooltip, see designs. 
- Vertical lines should be beneath avatars
  - Spacing between lines change for mobile breakpoint, see designs.

## Figma Dev Mode 
You can view the designs in dev mode within figma for all the design details broken down and easily readable - [Link](https://www.figma.com/file/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?type=design&node-id=346%3A33737&mode=dev)

## Acceptance criteria 

- [x] nested reply for up to 8 layers 
- [ ] user not able to nest replies further after 8 layers, tooltip present
- [ ] glitches in lines are fixed, mobile breakpoint updates applied
- [ ] Design details as per the Figma dev mode 
- [ ] no regression of existing functionality on the replying to comments 

Designer: Jessica Martinez 
PM: Zak 

![Image](https://user-images.githubusercontent.com/38763242/256597500-f455dfb4-c5db-47c6-91e8-405895d7fe75.png)
<img width="446" alt="Screen Shot 2023-08-31 at 2 40 34 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/dad62ba1-d6d0-424c-86e1-d660de491c59">
<img width="131" alt="Screen Shot 2023-08-31 at 2 41 41 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/a200e4c6-3c32-4ad8-90d5-902ee01c151e">

**Comment by CowMuon** [comment]
This was previously refined for cycle 5, but not brought to refinement for cycle 6 (?) @zakhap

**Comment by masvelio** [comment]
@sachben91 accordion button, "show x more replies" button and comment settings (all 3 visible in the designs), are not scope of this ticket, right?

Considering they are not, work to do here:
- disable reply button
- fix lines comment
- adjust styles to mobile
I am assuming that it will be tricky to make everything pixel perfect here, thus this would be one day of work, so 3.

**Comment by masvelio** [comment]
@sachben91 is out sick but he confirmed on slack that accordion button, "show x more replies" button and comment settings are not in the scope
