### ISSUE TITLE
Update Comment and Reply Body Components

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4608]
## Description

_This ticket is a re-write for clarity of a #4218. It is a subset of work around the comment section._

The goal of this PR is to update the style of the comment section components and their nested actions.
- [ ] Reply "Line" to show nesting of Replies
- [ ] Comment Container
- [ ] Comment Body
- [ ] Comment Action Footer
  - [ ] Upvote Button
  - [ ] Reply Button
  - [ ] Share Menu
  - [ ] Triple Dot Menu

Dev Link to Figma File:  https://www.figma.com/file/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?type=design&node-id=1%3A3&mode=dev

Design Solution Document: 
https://www.notion.so/buildcommon/Design-Solution-Comments-Nesting-Overhaul-Part-1-73ab320749664978a6767e56338ca2c8

## Acceptance Criteria

Styles and all behaviors detailed in the Figma file are updated for the following components/sections:
- [ ] Reply "Line" to show nesting of Replies
- [ ] Comment Container
- [ ] Comment Body
- [ ] Comment Action Footer
  - [ ] Upvote Button
  - [ ] Reply Button
  - [ ] Share Menu
  - [ ] Triple Dot Menu
- [ ] No regression of any functionality.

## Additional context screenshots

<img width="365" alt="Screen Shot 2023-07-27 at 12 07 34 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/d1ce63b6-d236-45f7-8239-01f3a578bc00">
<img width="341" alt="Screen Shot 2023-07-27 at 12 07 47 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/cf912556-1eef-4eba-be52-149dfd830cea">
<img width="473" alt="Screen Shot 2023-07-27 at 12 08 08 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/be7ef8ef-7396-4fa9-9694-9d2e6da27dc2">

## Peoples
- Design: @jessmart1213 
- PM: @zakhap

**Comment by CowMuon** [comment]
This work should precede work on https://github.com/hicommonwealth/commonwealth/issues/4607

**Comment by CowMuon** [comment]
This is another issue that was brought to refinement for Cycle 5 but not included in our Cycle 6 refinement yesterday (?) 
As such leaving it in No Status, but we can potentially pull it in if it needs to jump up in stack ranking (not as matter of habit tho)

**Comment by masvelio** [comment]
Work to be done:
- adjust CSS styling across comment-related components
- swap some icons (twitter, edit comment)
- locking and archiving comment is not implemented so this won't be in scope of this ticket @zakhap 

Should be no more than half day, so 2.
