### ISSUE TITLE
Comments Overhaul: Left Metadata Row Updates

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4609]
## Description

_This is a rewrite of the ticket #4240. Using FigmaDev links for clarity_

**Figma DevLink:**  https://www.figma.com/file/wh0geIjiATx2vmEMuy2gT0/Forum-Improvements---Part-3---Comments-and-Replies?type=design&node-id=576-8862&mode=dev

**Components to update:** 
- [ ] Avatar + Display Name
  - [ ] include on hover states and popover
- [ ] Timestamp (Relative Time shown, detailed in Figma Comment) 
  - [ ] Timestamp Popover: shows Absolute Timestamp, detailed in Figma Comment

## Acceptance Criteria

- [ ] All components above are implemented to spec, design details and behavior
- [ ] No regressed functionality within avatar popover.

## Additional context screenshots

<img width="216" alt="Screen Shot 2023-07-27 at 12 19 58 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/b21d511c-fa22-40d1-95e3-812debc9270a">
<img width="287" alt="Screen Shot 2023-07-27 at 12 20 07 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/57d6ec1a-c848-47d4-b17e-65a295b39bc6">

**Comment by CowMuon** [comment]
This work should precede work on #4607 (Comments nesting)

**Comment by masvelio** [comment]
Work to do:
- adjust CSS styling for metadata items
- adjust look & behaviour for metadata component
- create timestamp tooltip and util for formatting dates

Should be half day of work, so 2.
