### ISSUE TITLE
Prevent UI Error on failed searchbar query

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4623]
It appears that (intermittently) a UI error is being thrown when a search in the searchbar doesn't return any results. This should just be a silent failure.

[Screenshot](https://commonxyz.slack.com/files/U04N23Y7BBR/F05KPSME7MF/screen_shot_2023-07-28_at_3.58.07_pm.png)

**Acceptance Criteria:**
When no results are returned in the searchbar, no toast error should be thrown in the UI.

**Comment by rbennettcw** [comment]
FYI: the screenshot shows the old `/searchProfiles` route, which has now been moved to `/profiles`. Perhaps the bug was encountered on an old version of the app? @alexyoung23j  @jnaviask

**Comment by alexyoung23j** [comment]
@rbennettcw I cannot reproduce this and see that you've overhauled that route. Appears likely to me that this was encountered with an older version of the app as mentioned, and the bug has been resolved.
