### ISSUE TITLE
[Mobile Navigation] - Draggable Sidebar

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4630]
**Description**

The Community Sidebar should be draggable and slideout rather than pop out, and while using Capacitor (platform === ios, or android only), be draggable, from the edge of the left screen. Exactly like Slack or Twitter Native Apps

**Eng Considerations**

This branch will need be be based off https://github.com/hicommonwealth/commonwealth/tree/mobile-push (this is currently merged into experimental).

**Acceptance Criteria**
- As a user, while I am on Capacitor (platform === ios, or android only), I should be able to drag the sidebar using my finger.
-- If I do not drag out far enough (more than 20% of the sidebar), then the sidebar should stay hidden
-- If I drag far enough (more than 20% of the sidebar), then the sidebar should use momentum and show the whole sidebar

- As a user, I should be able to use the same movement to close the sidebar, dragging to close

- As a user, while I am on Capacitor, I should be able to drag anywhere on the Sublayout - minus the header (essentially the full screen)

- As a developer, I should include a loom demonstrating the functionality (open and close, with the 4 possible states), and show that desktop and browser functionality remains unaffected.

**Notes**

- This has been split out from #4592 
- Potential Solution(s): https://web.dev/css-scroll-snap/ (use snap scroll) and [mouse event listeners -- mouse up, down, etc etc](https://www.perplexity.ai/search/b9cd8e29-6271-40ee-9ddd-08cc339f0a66?s=c)

**Comment by alexyoung23j** [comment]
Have some code working for this, but I need phone testing to be able to really see if its working as expected. Drag/swipe on desktop simulator is probably not the best.
