### ISSUE TITLE
Firefox chronological thread sort is broken 

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4637]
## Describe the bug

On Firefox, sorting by "newest" is resulting in threads being sorted by oldest instead. Reported on this community page: [thread](https://commonwealth.im/divastaking/discussions)

See loom: https://www.loom.com/share/a85e92edc5064819af00e3de12517e2d?sid=eb7607d0-f3a1-4125-9d16-febb2d0953d4

## To Reproduce

Visit a thread page on Firefox, click sort by new. This will display the threads in reverse chronological order.

## Expected behavior

On all browsers, sort by new should be displaying the most recent threads first.

**Comment by mzparacha** [comment]
we are not doing this, correct? @jnaviask

**Comment by jnaviask** [comment]
we can backlog it for now @mzparacha

**Comment by CowMuon** [comment]
Firefox is 3% of users (or, 100 address logins a month.) This was brought to TOW (top of week) but we're going to send it to back of line for now.
