### ISSUE TITLE
Reacting to deleted comment gives 500 rather than 400 error

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4640]
## Describe the bug
Reacting to a deleted comment gives a 500 ServerError instead of a 400 AppError as expected.

In general, errors such as "acting on a non-existent entity" should throw 400 and not 500 errors.

## To Reproduce

Create a comment, reply to the comment, delete the original comment, then try reacting to it.

**Comment by rbennettcw** [comment]
Expanding scope to apply to all core forum routes (e.g. that I refactored previously)– since I know that the AppErrors/ServerErrors are not applied correctly in those routes.
