### ISSUE TITLE
Upvoting Users List - Design Update #2

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#4643]
Currently, when you hover over the reaction button on a thread, you see a tooltip containing a list of users who have upvoted that thread. We need to decide a couple things: 

1. if the tooltip will remain
2. if the tooltip remains, what the new design will be

@meeshlin @zakhap

**Comment by CowMuon** [comment]
If this is design update #2, it should link to design update #1, kudasai.

**Comment by jnaviask** [comment]
@Miaplacidus any updates on this ticket, or can it be closed?
