### ISSUE TITLE
Styles for thread collaborators tooltip are broken

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#4648]
## Describe the bug

- as in the title

![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/9ee5d173-143f-4998-81d9-41ca8cca0fa7)

## To Reproduce

- create a thread
- add collaborators
- hover over the authors
- see that the tooltip is without proper styling
## Expected behavior

- tooltip should be styled properly
## "How We Fixed It"

- probably the styles were removed during one of the latest merges so the git history will come in handy
## Additional context

-

**Comment by sachben91** [comment]
Tested, tooltip styling seems accurate
