### ISSUE TITLE
Spike: research alternatives to heroku for custom domain support

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4656]
## Description

Currently we use [heroku's internal custom domain support](https://devcenter.heroku.com/articles/custom-domains) to provide white label endpoints for customers. For example, https://gov.1inch.io.

The configuration of the custom system is as follows:
1. 1inch provides Common with the custom domain they want to use (gov.1inch.io, e.g.).
2. We manually provide Heroku with the domain, via the custom domain management tool or domains CLI.
3. Heroku generates a DNS target for the custom domain, which we provide to 1inch.
4. 1inch configures their DNS provider to point to the heroku-generated custom domain.
5. Heroku refreshes the certs (either automatically, or via manual refresh) and confirms the custom domain is correctly configured. Traffic from the provided domain is now accepted by heroku.
6. Common adds the provided custom domain to the Chains table. It is then returned by the /domain route, and is used to configure separate custom domain / white label routing when a user lands on the custom domain vs commonwealth.im.

The benefit of this system is that it's easy to configure, since it's supported by heroku by default. The downsides of this system are:
1. Requires manual intervention to configure; the community admin can't do it themselves.
2. The DNS configuration is tied to our heroku application, making it difficult to transition to another heroku tier requiring a migration, or to another service entirely.

The scope of this ticket is to research alternatives for custom domain support, keeping in mind the two downsides above.

## Deliverables

Report comparing different alternatives for supporting custom domains on the Commonwealth site, with sketches of implementation strategies for each.

## Timebox

3 hours max.

**Comment by rbennettcw** [comment]
Here's the doc where I'm documenting the solutions: https://docs.google.com/document/d/1cryQVF-LKRaFf6NSZ8h8VqisPv4H8C1H-mFG-r3AGaM

It takes some time to verify the capabilities of a DNS service and draft out the full workflow. So far I've done so for Cloudflare, but I'll need more time to check out other alternatives.

**Comment by jnaviask** [comment]
@rbennettcw feel free to take additional time, please note on the ticket how many hours so we can update the timebox

**Comment by rbennettcw** [comment]
Expanding from 3 hours to 8 hours

**Comment by rbennettcw** [comment]
I've created sequence diagrams for a Cloudflare API solution and a custom Nginx solution.

I looked into AWS (since we're moving in that direction), but there doesn't appear to be a full turnkey solution like what Cloudflare provides– handling domain verification + SSL certs.

From what I've seen, it seems like the only viable options are either Cloudflare or custom Nginx.

@jnaviask Feel free to take a look at the doc and provide feedback.

**Comment by jnaviask** [comment]
Overall feedback is that Cloudflare custom domains seems like exactly the use case we have in mind. I am not worried about vendor lock-in because we already use Cloudflare extensively.

@rbennettcw Can you open a placeholder ticket with a brief description of steps required to get there (although we wont necessarily tee it up for this week/next), and then we can mark this ticket completed?

**Comment by rbennettcw** [comment]
@jnaviask Added a ticket with implementation details overview: #4882
