### ISSUE TITLE
New mention and new collaboration subscription settings don't show on notification settings page

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4657]
## Describe the bug

The new-mention and new-collaboration subscriptions don't show up don't he notification settings page so users cannot manage the settings for those subscriptions.

## To Reproduce
Go to the notifications settings page.

## Expected behavior
Both subscriptions should show on the notification settings page so a user can manage them.

**Comment by lzach83** [comment]
Had a meeting with @kurtisassad about this ticket, seems like the backend is returning an empty array. He will take over the work for the backend then if there's any frontend work i will resume.

**Comment by CowMuon** [comment]
Removed ZachLee's assignment here. 
@kurtisassad - If there is outstanding product work after you have updated the back end, pls assign back to him.

**Comment by ForestMars** [comment]
This can be closed as stale
