### ISSUE TITLE
Snapshot Subscriptions don't show up on notification settings page

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4658]
## Describe the bug
If you create a snapshot proposal subscription from a communities snapshot page e.g. [https://commonwealth.im/dydx/snapshot/dydxgov.eth][1], the subscription will not show up on the notification settings page even if you refresh.

## To Reproduce
Same as above.

## Expected behavior
After subscribing on the snapshot page, you should be able to view and manage the subscription from the notification settings page.

## Additional context

[1]: https://commonwealth.im/dydx/snapshot/dydxgov.eth

**Comment by CowMuon** [comment]
Suggest @lzach83 to pair with @alexyoung23j on this

**Comment by lzach83** [comment]
state object of `discussionSubscriptions` has no chain related identifying factors for the category `snapshot-category` , built the function that will render the notifications correctly once we get the state object updated.

**Comment by lzach83** [comment]
This should be nearing the finish line. Took a break due to #5093 needing so much attention. 

I believe the code is finished, just have to do some more testing and ensure it covers all cases.
