### ISSUE TITLE
Cannot resubscribe to a comment I authored

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4659]
## Describe the bug
When I create a comment, I am automatically subscribed to reactions and sub-comments. If I delete these subscriptions from the notification settings page, there is no way for me to resubscribe. This is either because we don't show a subscribe button next to comments you have authored or because we delete rather than disable subscriptions from the notification settings page.

## To Reproduce
1. Create a comment on any thread you have not authored.
2. Go to your notification settings page and delete the reaction + comment subscriptions on your comment.

## Expected behavior
I should be able to resubscribe to reactions and sub-comments on a comment I have authored after either disabling the subscriptions or deleting them.

**Comment by CowMuon** [comment]
Can we get an estimate here, as well as what the severity is?

**Comment by timolegros** [comment]
I would say the severity is quite low.

**Comment by CowMuon** [comment]
Given low severity here, adding grab-n-go label, as Marcin has #5471 and #5273 teed up ahead of this one.

**Comment by CowMuon** [comment]
If this is still an issue, let's tag this as a low priority (low severity) follow on for current scope of work in 0.9.1, and merge in there if pos.
