### ISSUE TITLE
Chain Event WebHooks broken on server + client

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4663]
## Describe the bug
WebHook code still references `chain_event_type_id` on the server. This means chain-event WebHooks are not being sent. Furthermore, client-side WebHook settings for chain-related events are not functioning properly. Adding Governance events increases the count of WebHook events (displayed on client) disproportionately indicating the client likely still bases WebHooks off of chain-event types as well. Client-side WebHook settings need to be rebuilt to account for multi-contract communities.

## To Reproduce
1. Become an admin of any community.
2. View WebHook settings

## Expected behavior
An admin should be able to pick chain events from a specific contract on a specific chain rather than just a generic 'Governance Events' and the CE WebHooks should actually be dispatched successfully.

**Comment by CowMuon** [comment]
Can we break this into 2 stories, for server and client changes. Then this ticket can be closed (preferred) or turned into a bucket (if you must)

**Comment by timolegros** [comment]
New tickets #4988 and #4987
