### ISSUE TITLE
Update /threads?active=true to include pinned thread if any via a query param

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#4671]
## Description
As part of a cleanup in #4545, we updated the frontend to use the new threads state. This change removed the old thread controller which also removed complex pinned thread calculation.

As a simplification process, we can update /threads?active=true to return pinned threads via a query param

## Engineering Requirements
- /threads?active=true should accept a query param to return pinned threads if any and also respect the existing `threads_per_topic` param.

## Acceptance Criteria
Same as ENG requirements

## Additional context
N/A

**Comment by rbennettcw** [comment]
@mzparacha is this ticket still relevant and something that should be done?

**Comment by mzparacha** [comment]
I believe yes @rbennettcw, we would need to include pinned threads with response if any, also updated the title to reflect that.

For context this was done via the bulkOffchain API before #4545

**Comment by rbennettcw** [comment]
@mzparacha From what I can tell, the active threads route already returns pinned threads (along with non-pinned threads).

Do you need to a flag that filters and _only_ returns pinned threads?

**Comment by rbennettcw** [comment]
Closing since there's nothing to do here.
