### ISSUE TITLE
Related Communities / "Directory" page

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4679]
### User Story
When I’m managing my community as an admin for an ecosystem (such as Near or Solana), I want to be able to automatically create a directory of projects/communities that are in the same ecosystem so that community members can explore and join these other projects. The automation is important to me since there could be several projects that I’m not aware of that could get missed in manual curation 

As a community admin, I want to be able to turn on/off the directory page. 

[Design solution doc](https://www.notion.so/buildcommon/Design-Solution-Related-communities-directory-page-add775d6bd6f425f9be51cd2bfb5e1cd)

[Designs on Figma](https://www.figma.com/proto/QD7yD6pPd9JQO5CjTBEmdz/Related-Communities-Directory-Page?page-id=3%3A38&type=design&node-id=269-91999&viewport=201%2C313%2C0.21&t=3d8UdMQ7WqllIZKZ-1&scaling=scale-down&starting-point-node-id=269%3A91999)

[Prototype on Figma](https://www.figma.com/proto/QD7yD6pPd9JQO5CjTBEmdz/Related-Communities-Directory-Page?node-id=269-91999&starting-point-node-id=269%3A91999)

[Loom](https://www.loom.com/share/9b26a9f07db848c88f868944a9d80735?sid=f97a2504-f2fe-4925-8601-9e024edc5ecb)

### Behavior 
- Admin should be able to see the option to toggle the directory page on in "manage community" page 
- Admin should be able to select the chain for the directory page. The default chain should be the underlying chain of the community that the user is an admin of. The user should have the option to change this to another chain
- The directory page that a normal user sees should have a table view and card view as shown in the design. The columns Community, Members and Threads should be sortable in alphabetic order (community) and ascending or descending order numerically (Members, Threads) 
- User who is visiting the directory page should be able to search by Community. 

### New Components:
- Typeahead search drop down #4680 
- Table component #4682 
- Related communities table search #4681  
- Community Card Component #4828 

### Screenshots 
Directory page set up
<img width="597" alt="Screenshot 2023-08-17 at 10 37 06 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/eb86c387-971b-4e3c-b8cd-d5c295417f45">

Directory page view 
<img width="1439" alt="Screenshot 2023-08-17 at 10 37 24 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/8cb06f1c-8d26-4c00-a674-07f502e29fac">

### Acceptance criteria 

- [ ] Admin see the directory page option in the manage community page
- [ ] Admin is able to toggle the directory page on and off
- [ ] Admin can select the chain for which they want to display related communities in the directory 
- [ ] user visiting the page can toggle between card view and table view in the directory 
- [ ] user visiting the page search for communities on the directory page

--- 
PM: @sachben91 
Designer: @jessmart1213 
This ticket is a blocker on onboarding some Enterprise Ecosystems we're courting.

**Comment by Miaplacidus** [comment]
@jessmart1213 @sachben91 @zakhap 
The directories page provides an option for both a table view and a card view. The cards will vary in height depending on the length of the community description. Do we want the cards to all have the same height? In addition, some of the cards have a call to action. What is the CTA and under what conditions will it appear?

**Comment by jnaviask** [comment]
@masvelio Tagging you as the core developer on this screen. The two components needed to address this ticket are #4680 and #4682 which should both be nearly complete.

Please sync with @Miaplacidus to make sure you have full context regarding any updates design/product may have surfaced since ticket creation, and then please update the body of the issue to correspond with the final decisions.

**Comment by jessmart1213** [comment]
It has come to my attention that the loom I created was recorded without sound. So I just re-recorded the with sound. 

Here is the new [Loom](https://www.loom.com/share/bbd946532c06499681c952f3b3eaec91). 

@masvelio @sachben91 @zakhap @Miaplacidus

**Comment by masvelio** [comment]
After my review and sync with @Miaplacidus, I am attaching my thoughts and questions. 

**Work that has to be done here.** 

**Frontend**
- add “directory page” section to “manage community” page
- add “Directory” list item in left sidebar
- create “directory” page 

**Backend**
- add boolean field to ChainInfo model for directory page section toggle
- add string field to ChainInfo model for selected community’s chain
- update updateChainData method to support those two values above
- prepare data that are displayed in directory page (list of communities with description, members, threads)

**Questions**
- @jnaviask Where should I get the list of community’s chain dropdown from? Is this something we already have in app store or we should prepare it on the backend specifically for this page? 
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/d6692606-6d89-4fd6-8229-5bec6f2a1d1a)

- @jnaviask Should we create new endpoint that will be serving data for directory page (list of communities with description, members, threads etc)? Should this list be paginated?
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/feb02feb-1e19-4271-aaa1-464eb3e26c81)

- @jnaviask To what endpoint the seachbar should be hooked up to? 
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/7712403d-880a-4901-96ba-ce29549a7932)

- @jessmart1213 Requirement is that “Directory” list item in left sidebar should appear right after the toggle is turned on. However, we have already similar situations that left sidebar is updated eg for changing the order of the topics, update the name of the topic or showing homepage. All of these actions are reflected in left sidebar after pressing the save button. Both from UX and technical point of view, it would be good to follow this pattern. If we turn the toggle on and show the Directory list item in left sidebar, but we do not click “save changes”, after leaving the “manage community” page, the list item will be not visible anymore and the new value for toggle won’t be save neither. I am adding video below to show the current behaviour.

https://github.com/hicommonwealth/commonwealth/assets/14819225/c7f54e0b-0903-4656-a6c8-7c9112830a47

**Comment by masvelio** [comment]
@sachben91 another question that came to my mind - do we support related directories for custom domains? For example `explore communities` is not available on custom domains:
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/6ca2e490-71e6-4f46-b0d2-e3f7c46a1be9)

**Comment by masvelio** [comment]
@jnaviask thanks for the answers. In this case I am gonna start with the front end part as it seems that backend needs more clarification.

**Comment by jessmart1213** [comment]
@masvelio responding to

> @jessmart1213 Requirement is that “Directory” list item in left sidebar should appear right after the toggle is turned on. However, we have already similar situations that left sidebar is updated eg for changing the order of the topics, update the name of the topic or showing homepage. All of these actions are reflected in left sidebar after pressing the save button. Both from UX and technical point of view, it would be good to follow this pattern. If we turn the toggle on and show the Directory list item in left sidebar, but we do not click “save changes”, after leaving the “manage community” page, the list item will be not visible anymore and the new value for toggle won’t be save neither. I am adding video below to show the current behaviour.

I see what you are saying here. Thank you for bringing this up. From my understanding, to adhere our UX patterns and best practices of clicking "save changes" lets change the user journey to the following: 
- As an Admin who wants to enable the "Directory page" I go to the "Manage community", I scroll down to the Directory page section, I click the toggle on, I ensure the dropdown is populated with the chain I want, I scroll further down the page, I select "Save changes". Once changes are saved, I see the "Directory page" appear within the sidebar, but I decide to scroll back up to the Directory section and I see the tertiary button "Go to directory page" has also appeared and I select that button to be taken to the Directory page. 

Let me know if what I wrote is clear enough to be actioned on. If not, I will update the designs.

**Comment by masvelio** [comment]
This is all good @jessmart1213 thanks for adjusting it

**Comment by sachben91** [comment]
@masvelio re:do we support related directories for custom domains?  what is the effort on supporting related directories for custom domains? and how many communities have custom domains?  If the effort is medium to low, we should support related directories, if its high, lets have a discussion to look at the custom domains and how important they are.

**Comment by sachben91** [comment]
@jnaviask A base chain is all the chains that a community can be connected to, so the list to be queried would have all the chains that we have nodes for. cc @zakhap for more clarity

**Comment by zakhap** [comment]
We can drop the term "Base Chain", as it is simply the "Chain" that a community is "based on". 

The logic for the dropdown would be to show all the possible "Chains" that a community can be based on. The suggested/pre-selected default input should be the "Chain" that the community is currently associated to. For example, if the Community "Zak's Clubhouse" was created as an Ethereum Mainnet Community, then the pre-selected input should be "Ethereum Mainnet".

**Comment by masvelio** [comment]
> We can drop the term "Base Chain", as it is simply the "Chain" that a community is "based on".
The logic for the dropdown would be to show all the possible "Chains" that a community can be based on. The suggested/pre-selected default input should be the "Chain" that the community is currently associated to. For example, if the Community "Zak's Clubhouse" was created as an Ethereum Mainnet Community, then the pre-selected input should be "Ethereum Mainnet". For example, "Freedom DAO" is based on the XDai chain and then the pre-selected input would be "XDai Chain".

@zakhap Thanks for giving the examples, that helps. Spreadsheet is also helpful.

1. So my understanding is that the dropdown list will always have the same set of items (chains), regardless of the community we are looking at. The list will be basically the same as the one [in spreadsheet ](https://docs.google.com/spreadsheets/d/1g1KGr8BgR0qEgVq_GFICWk7CAuJw4D45PD3sQ4YBwPA/edit#gid=0) and it can be accessed from `app.config.nodes` as @jnaviask [mentioned above](https://github.com/hicommonwealth/commonwealth/issues/4679#issuecomment-1766716515). 
2. What will be different between communities though is the default value in the dropdown. Eg for "Freedom DAO" community, default value will be "xDAI" chain, for "dydx" community, default value will be "ethereum mainnet" chain, etc.
3. When I click "Go to directory ->" button, I use selected value from the dropdown eg "xdai" or "ethereum mainnet" to fetch  every community that is based on this chain and display them in the table. So if I have "ethereum mainnet" selected, then in the directory page I list every community that is based on "ethereum mainnet", so "dydx", "aave", "alchemist", "alpha venture dao" etc.

Sorry for being so verbose here, but I really want to understand the logic, relation and the flow here.
cc @kurtisassad for visibility

**Comment by sachben91** [comment]
@masvelio your understanding is accurate

**Comment by masvelio** [comment]
@ForestMars @jnaviask Eng update: I run into issue with searchbar. I am not able to reuse[ recently created `CWSearchBar` ](https://github.com/hicommonwealth/commonwealth/pull/4462)because it is not generic design system component. When I import and use it, it has all the logic for searching communities/members/threads etc, exactly the same as searchbar for top navbar (see image). I need to refactor it to make it reusable. Shouldn't be high lift, but want to inform that it will take a bit more time than I expected. 


![Image](https://github.com/hicommonwealth/commonwealth/assets/14819225/20e3b1b8-9d76-493c-afc4-418f72e9a1c2)

**Comment by CowMuon** [comment]
Setting status to In progress to catch the last remaining merge conflict, and then we're GTG.
