### ISSUE TITLE
Typeahead search component for related communities page

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4680]
### Context 
- This component is part of the directory page redesign, currently thats the only place it will be used. 

### Design 

![Image](https://user-images.githubusercontent.com/38763242/258175549-3d1b9c06-6896-44f5-922c-45e5fa665b82.png)

[Related communities figma ](https://www.figma.com/proto/QD7yD6pPd9JQO5CjTBEmdz/Related-Communities-Directory-Page?page-id=3%3A38&type=design&node-id=269-91999&viewport=201%2C313%2C0.21&t=3d8UdMQ7WqllIZKZ-1&scaling=scale-down&starting-point-node-id=269%3A91999)

### Behaviors

- The dropdown component used in the design above is a Dropdown select button with type-ahead (auto-suggest) functionality.
- This means a user can scroll and select as they would with any other dropdown select button AND they can type-ahead within the input field container and have the dropdown menu auto-suggest items.
- The default state for the drop-down for the Directory page would be the chain that the community is on is selected from the drop-down by default. 
- When the user clicks on the dropdown it should show the list that is available to be selected (in this case "base" chains) in alphabetic order 
- When the user types in the first character of the search, the dropdown should suggest selections that have the character that the user typed in
- The user should be able to select only one of the results (no multi select option)
- If the user types in a string that is not available in the dropdown, the dropdown should display the message "no matches found"
- Please see this link for expected type-ahead (auto-suggest) behavior (It's not part of the spec but is a good example of the typeahead behavior):
- https://ericgio.github.io/react-bootstrap-typeahead/  - the example that is useful here is "single selection"

**Comment by Miaplacidus** [comment]
@jnaviask @MuonShot @masvelio @mzparacha @jessmart1213 

My work is built using a component @mzparacha is currently working on. I'll wait until he merges, pull in his changes, and make any updates to the typeahead dropdown that are necessary. Based on what I've seen of his work, I don't expect too many changes (expecting mostly styling fixes). Will update if this expectation is incorrect.

However, in the meantime, @jessmart1213 can still review my work on [demo](https://commonwealth-demo.herokuapp.com/components) and I can make any required changes.

**Comment by ForestMars** [comment]
> My work is built using a component @mzparacha is currently working on.

@Miaplacidus Please reference blockers by issue, and tbh it would be nice to say which component you need (rather than "a component" which is vague.)

**Comment by ForestMars** [comment]
It also seems like we need to clarify the process here @Miaplacidus, is there a specific question you have for Jessica? Is the work supposed to be done? (assuming no, since you said you need a component Malik is working on.) Did you confirm that it matches the design before tagging Jessica? (assumption here is yes, you did.) The concern is what seems to be asking Jessica to review work that isn't done. (?)
