### ISSUE TITLE
Update styles for search bar component 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4681]
### Context 
- The current search component on the top looks like this: 
<img width="667" alt="Screenshot 2023-08-17 at 8 08 38 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/0920cff7-2f5f-4fd3-b504-3ed7f4e7c825">

This was redesigned by @jessmart1213 for the design of the directory page to have less rounded corners. We'd like to apply this design to all search bar components including the one above since its cleaner/sleeker 

### Design specifications

- See ‘Search’ page within design system figma - [Link](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=26%3A7637&mode=design&t=jPeSRfNVQvO09tXa-1)

- The current component is named SearchBar. The UI should change to the one in the figma design above. 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/dbdd86c0-9260-476e-90e8-d53f96ff9276)

### Behaviors

- no behavior changes to the existing component

**Comment by masvelio** [comment]
@mzparacha @sachben91 This is already done in this PR https://github.com/hicommonwealth/commonwealth/pull/4462 and we should merge it instead of introducing new styles specifically to the searchbar

**Comment by mzparacha** [comment]
Yeah, I think we can close this in favor of  #4462.

**Comment by jnaviask** [comment]
Superseded by #4119.
