### ISSUE TITLE
Table component (for related communities)

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4682]
### Design specifications

The table component will be used in the related communities directory page and for designs related to gating. Tables display tabular data in a basic grid composed of cells, columns, and rows. This format makes it easy for users to scan and compare different types of data.

### Specifications 

-  Tables have a header that describes the information in the columns below the header. Headers may have sorting functionality which the user can use to sort the columns in ascending or descending order, either alphabetically or numerically

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/55053fcc-81a0-4af3-b652-a46c43433846)

- The user is able to sort a column by clicking on the header. Clicking on the header will sort the table in ascending or descending order. The arrow icon next to the header will indicate whether the sort is active or inactive. When the sort is active, the arrow icon will be blue. 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/0b51d71e-cf4e-4790-990e-8bf4abcb051a)

- The cells of the table contain the information that is described in the header of the table. The information contained in the cells can be simple text, numbers, text with an icon/logo next to it, tags or actions as indicated in the screenshot below 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/c4a685f4-eeb1-4b65-bebe-7a0a0ce018ba)

example of the table used in Related Communities/Directory page 

![Image](https://user-images.githubusercontent.com/38763242/264735108-ec7c3eee-8f9b-46cd-93aa-ea53f9ebdc93.png)

### Designs 

[Component in Figma ](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=2046-14826&mode=design&t=DcPX7I4zkA5YVmbB-0)

[Loom describing the sorting behavior of the tables](https://www.loom.com/share/fbb5b886317845388283c6b2c6d8b37b?sid=30d28968-e591-4173-9896-b7b2f11689a7)

note: The expand and collapse functionality described under base body cell can be avoided at the moment 

### Not in scope 
the functionality for this component will expand when gating is implemented, that is out of scope for this ticket

--- 
PM: @sachben91 
Designer: @jessmart1213

**Comment by sachben91** [comment]
updated the design specifications for this ticket, but the figma and other links remain the same as before

**Comment by Miaplacidus** [comment]
Per conversation with @sachben91, the portion of the design labeled 'Expand' and 'Collapse' will not be addressed in this unit of work. Expect future cards with more details around that specific functionality.

**Comment by Miaplacidus** [comment]
Per conversation with @jessmart1213, the behavior of the table in regards to sorting is as follows: only for some headers will sorting be enabled. For those with sorting disabled, the arrow button should not be present.

**Comment by Miaplacidus** [comment]
@jessmart1213 @sachben91 @zakhap @MuonShot 

In the Loom attached above, data in the table is sorted, by default, according to the first column of the table. However, the arrow on the associated column is not active. This UI seems a little odd to me as the very first click, from the user's perspective, does nothing. Yes, the arrows primarily exist to let the user know what sort they've clicked on, but they also just let the user know what the current sorting is. 

In addition, I'm using Tanstack to build this component and the library is such that what is sorted is closely intertwined with the arrow icon that is active. One option is to sort data received by the component "manually", which would get around the active arrow issue. This isn't difficult to do, but it does feel a little...off. I'd be sorting manually data that Tanstack sorts for me AND it usefully lets the user know that the data is sorted and how it is sorted. What I'm doing is hiding information from the user, and I'm not sure why. 

I hope my reasoning makes sense. Please do let me know what you think and thanks for reading this!

**Comment by jessmart1213** [comment]
> In the Loom attached above, data in the table is sorted, by default, according to the first column of the table. However, the arrow on the associated column is not active. This UI seems a little odd to me as the very first click, from the user's perspective, does nothing. Yes, the arrows primarily exist to let the user know what sort they've clicked on, but they also just let the user know what the current sorting is.

I agree with the above. I think the loom explaining the sorting arrow behaviors should be an examples of how the sort functions and its various states. I think from there we can decide in what state the sort arrow is in (active or not) on a case by case basis, so the default sort per table is contextually specific.

For the directory page, that would mean that by default the the sort arrow should be in state `Active Ascending`.

> In addition, I'm using Tanstack to build this component and the library is such that what is sorted is closely intertwined with the arrow icon that is active. One option is to sort data received by the component "manually", which would get around the active arrow issue. This isn't difficult to do, but it does feel a little...off. I'd be sorting manually data that Tanstack sorts for me AND it usefully lets the user know that the data is sorted and how it is sorted. What I'm doing is hiding information from the user, and I'm not sure why.

As for Tanstack and  sorting manually, Im unclear as to what this would mean, specifically for the user, and what this means for the UI. Is there an example of how this would look? I need a bit more context / explanation.

**Comment by Miaplacidus** [comment]
Hey, @jessmart1213! 

Gotcha! So, I'll make it such that, the arrow always indicates if data is sorted or not. In regards to the Tanstack bit, I was just trying to explain that the arrow's direction always corresponding to the sort (as opposed to doing an additional sort on the table cells, but hiding that in the arrow UI) is Tanstack's default behavior and, as such, makes things easier on the developer side.

**Comment by jessmart1213** [comment]
### Design review

**Sort**

- Update sort arrow on:hover and on:click zone to be limited to the Icon CTA. Currently the sorts can be activated or deactivated by clicking anywhere within the header cell.
    - I want to reserve clicking the header cell for more advanced table actions we will most likely implement in the future.

**Alignment**
- Update body cells to be aligned top. Currently, they are middle aligned.
    
    
![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/7b588297-0d67-4b4e-a2ac-343bc5e99313)


**Body cell text**
- Ensure all body cells have text size of 14px ( Body 02 ).
- Update body cell text for cell type, User (no role) & User (role tag), to Body02/medium. Currently it is Body 01/reg or 16px height.
    
    ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/1739b6da-d7ab-4141-9be3-8ba39990496f)

---    

Questions: 

- Have tags had a review? Are these our new tags or old ones? Asking because the padding on this tag doesn’t match the padding within the figma designs.
    
    ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/19cafea6-562f-4ab8-9708-b00839d26a7e)
    
- I have the same question for buttons. I see our old buttons are being used in this table. Do they also need a design review & approval?

---

**Table body on hover and on click states**

- This is something that slipped through the cracks - where I designed a hover state for the Directory table but I don’t see it anywhere is the ticket. So I need to talk to product about next steps.
- See this [[loom](https://www.notion.so/Design-Solution-Related-communities-directory-page-add775d6bd6f425f9be51cd2bfb5e1cd?pvs=21)](https://www.notion.so/Design-Solution-Related-communities-directory-page-add775d6bd6f425f9be51cd2bfb5e1cd?pvs=21) at 5:00 min for table hover behavior.
