### ISSUE TITLE
Tag Consolidation, Using the New Kit

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4683]
## Description

The goal of this ticket is to replace all current uses of Tag components on our site to use our new Tag Component.

- Pull over the "discord" TagType (recently added by @ianrowan for Discord bot work) into the New Tag Component, (see in the designs the "loginUserTag"). 
- Tag instances to use New Component:
- [x]   Element Tags: "Poll", "Snapshot"
- [x] Stage Tags + Proposal "Prop" Tags
- [x] Spam, New, + Trending Tags 

## Acceptance Criteria

- [ ] All tags above are replaced,
- [ ] OR if there's any Tags that there are difficulties in replacing, document them here in the ticket and we'll subsequently dispatch the requisite work on the New Tag Component required to replace the trouble cases.

If we are able to replace all instances of the Old Tag Component with the New Tag Component, then we should also _remove the old component from the repository_.

## Additional context
@Miaplacidus Implemented the New Tag Component, let's get them in use!!! 

DevMode Link to Component + Component Usage: https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=2219-580&mode=dev

**Comment by Miaplacidus** [comment]
@zakhap @jessmart1213 @sachben91 
Not necessarily a blocker, but there are a few tag types we haven't accounted for - has a decision been made as to how stage, badge, and role tags will be used in the app, i.e. what state each corresponds to or are we waiting until a later card to implement those?

**Comment by Miaplacidus** [comment]
@zakhap @jessmart1213 @sachben91 

In regards to stage tags - in the designs we have 9 distinct, numbered stages corresponding to 'phase-1' through 'phase-9'. However, we do have default stages such as 'Discussion', 'Pre-voting', etc. I'm guessing the default stage color is `green-600`, but I just want to confirm.

**Comment by Miaplacidus** [comment]
@zakhap @jessmart1213 The updated tags are available on the demo branch. Take a look at the [1Inch discussions page](https://commonwealth-demo.herokuapp.com/1inch/discussions) (it's got lots of tags to view) and don't forget to check the 'include spam' checkbox up top to see the spam tag!
