### ISSUE TITLE
[FC Bot] - FC Listener / Worker / UI Updates

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4693]
### Current Point Estimation

- Listener: 5
- consumer: 3-5
- CW route updates: 1

### Description

We would like

Similar to Discord Bot, we would like to create a listener, consumer, and more for Farcaster, that creates a thread object.

There are differences here:

- Because Farcaster is default open, in this case we don't need to ask for authentication, 
- Instead we just need to grab Farcaster IDs and allow a user (or admin) to create a filter for (users), in this case we want to filter for posts that mention `CommonLogLine` or (whatever the user wants to filter by
- We should display the "OP" that CommonLogLine was a reply to as the post -> with the post that `CommonLogLine` was tagged on
- We should 

On the client side:

1) creates a Thread Object Similar to what we do by Discord Bot

Actually as a technical requirement, it's not necessary to even build the thread object, as long as we can query for Farcaster and have the item display into the Listing Pages and View Thread Page. We need this to facilitate functionality such as Templates and more.

----
### Reference Tickets

- https://github.com/hicommonwealth/commonwealth/issues/4266
- https://github.com/hicommonwealth/commonwealth/issues/4267
- https://github.com/hicommonwealth/commonwealth/issues/4268
- https://github.com/hicommonwealth/commonwealth/issues/4374

---
### Reference PR 

Here is previous combined Feature Branch and PR for Farcaster ([link](https://github.com/hicommonwealth/commonwealth/pull/4323/files#diff-5340745d3968dab37d406a21195d6170bce5648cfdd619262be88a62323e03c3))

**Comment by alexyoung23j** [comment]
Technical Spec: https://www.notion.so/buildcommon/Logline-Listener-Spec-ca59e068609f4c38ae8a13c0f38a5ab0?pvs=4

**Comment by dillchen** [comment]
Additional Considerations: More Extensibility would need to be added separately
