### ISSUE TITLE
Deprecate all Substrate proposal loading

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4699]
## Description
Since we are moving towards deprecating CE (#4696), we are moving all proposal loading to the CW API. Given that we currently only support loading past/old Substrate proposals that are already in chain-events it seems unnecessary to support Substrate proposal loading via the CW API. Therefore, Substrate proposal loading should be entirely deprecated and all forums should be converted to regular off-chain communities.

## Engineering Requirements
- Remove proposal pages from Substrate communities.
- Remove all Substrate controllers that are not required for login or basic forum functionality.
- Delete all Substrate events and entities from the chain-events database.
- Delete all Substrate chain-event subscriptions and their associated notifications, and notifications read.
- Replace existing proposal links with links to Subscan.
- Delete unused Polkadot node-modules/packages

**Comment by jnaviask** [comment]
Would love to include in scope, or ticketed separately:
- A migration to replace current substrate proposal links with block explorer links in currently linked threads
- A way to view the "web" type links on threads
- A way to add add "web" links to threads

**Comment by timolegros** [comment]
> Would love to include in scope, or ticketed separately:
> 
> * A migration to replace current substrate proposal links with block explorer links in currently linked threads
> * A way to view the "web" type links on threads
> * A way to add add "web" links to threads

I'll look into web linking and see what we need there. I'm not familiar with regular linking (outside of proposals).

**Comment by jnaviask** [comment]
As part of #3357 we added a generic link object that has a `LinkSource` with an unsupported "web" option. Time to leverage this forward-thinking piece and flesh it out.

**Comment by timolegros** [comment]
For clarity, "web" links will be handled in #4829.

**Comment by timolegros** [comment]
PR is ready for review but I'm leaving it in draft until #4829 is merged.

**Comment by timolegros** [comment]
Blocking #5247
