### ISSUE TITLE
Wire Together items for SnapshotX as trustedOracle

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4705]
References:
- https://github.com/snapshot-labs/sx-evm/blob/main/src/Space.sol
- https://docs.snapshotx.xyz/protocol-sx-evm/space
- [Conversation and Discussion](https://commonxyz.slack.com/archives/C05CD20JCTU/p1691179524238259)

**Comment by ianrowan** [comment]
Code for [this](https://whimsical.com/crowdfund-x-snapshot-x-x-farcaster-AU7NHyKBWW4giFtt11PRJm) implementation is in the commonxyz repo 

Will work on deployment/testing via Deploy ticket + fix any bugs there.

additionally this PR is open for snapshot(https://github.com/snapshot-labs/sx-evm/pull/239) we'll need to either get more context from them, or use our own fork of their contracts for our voting infra

**Comment by dillchen** [comment]
Closed because ticket on wrong repo
