### ISSUE TITLE
[Core Thread] - Additional Feeds on Thread Pages (i.e Votes, Contributions, and more)

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4709]
### Description

Create a feature that displays feeds on the thread page. Feeds are a list of actions and suggestions made by users, such as comments, likes, votes, contributions, bounties, ~~and forks~~. The feeds should be organized into swipeable tabs, similar to Twitter, allowing users to switch between different types of feeds easily.

### Engineering Requirements
- Implement ~~swipeable (out of scope, to be implemented in the Mobile followup ticket)~~ tabs at the top of the thread page to switch between different feeds.
- Implement the functionality to view and interact with the feeds, including likes, comments, votes, contributions, bounties.
- If a thread has a poll, snapshot, any templates, or proposal, we should see these in different "tabbed feeds" where we would normally see comments.
- Implement the tabs for different feed types, such as likes, comments, votes, contributions, bounties
- Add to the action row with buttons for `contributions` and `bounties`.

### Designs
[Figma](https://www.figma.com/file/kZm7Jdbgsb81eTBTetxbRI/html.to.design-(Community)?type=design&node-id=7%3A23902&mode=design&t=0N1h6OryUZpr94C9-1)

### Acceptance Criteria
- Users should be able to swipe left and right to switch between different feeds.
- The main div should display the feeds in a clear and organized manner.
- The action row should include buttons for contributing and forking.
- The tabs should allow users to view different types of feeds, such as likes, comments, votes, contributions, bounties, and forks.
- Icons for [contributions](https://www.flaticon.com/free-icons/contribution) and [rewards](https://www.flaticon.com/search?type=icon&search-group=all&word=reward&license=&color=&shape=&current_section=&author_id=&pack_id=&family_id=&style_id=&type=) should be integrated be used (find similar Phosphor Icons).

### Additional Context
- The feeds should be displayed in a visually appealing and user-friendly manner.
- The feeds should be responsive and work well on mobile devices (allowing a user to swipe back and forth between comments, votes, and other things)
- The design should follow the provided reference documentation for the feeds on the thread page feature.

-----

### Later
- [ ] #4753

**Comment by dillchen** [comment]
@kurtisassad do you have the PR for this?

**Comment by kurtisassad** [comment]
Sorry, wasn't linked.
