### ISSUE TITLE
Bug: Signing from Polkadot Chrome Extension Disabled

### ISSUE THREAD

**Issue by thomivy** [hicommonwealth/commonwealth#471]
## Description
This bug arises when attempting to sign transactions using Polkadot Chrome Extension. 
<img width="1285" alt="Screen Shot 2020-07-07 at 12 13 30 PM" src="https://user-images.githubusercontent.com/38070512/86854285-23620b00-c086-11ea-89c7-aaac61d2b1a2.png">

## *Who* is the bug affecting?
Some users try to participate with Polkadot Chrome Extension.

## *What* is affected by this bug?
The ability to sign transactions when interacting with Commonwealth.

## *When* does this occur?
On any attempt to sign a transaction.

## *Where* on the platform does it happen?
In the transaction signing modal popups.

## *How* do we replicate the issue?
1. Login
2. Ensure you have Polkadot Chrome Extension installed and setup with an account.
3. Go to Signals tab
4. Click into a Proposal
5. Click Vote
6. Grant application access in popup for Polkadot Chrome Extension
7. Notice that the button to sign the transaction is inactivated, with the message 'Signer not in Web Wallet'

## Expected behavior (i.e. solution)
Module should detect that signing is enabled.

**Comment by jnaviask** [comment]
Interesting -- for me, the button changes to "Sign and send transaction" once I grant application access. Does this only happen if you have a certain address selected?

**Comment by thomivy** [comment]
Solved. Polkadot Chrome Extension was to blame. Closed issue.
