### ISSUE TITLE
Bug: active address not persisting across refreshes

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4741]
## Describe the bug + Expected Behavior

While we don't yet have Session Keys live, the expected behavior when entering a community where the user has joined with multiple addresses, the last used address persists as the address selected when returning to the community.

For example, let's say I joined a community and I've selected my one admin address, that address should remain the selected address upon returning to the community. 

## To Reproduce

<img width="501" alt="Screen Shot 2023-08-09 at 12 49 50 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/19113075-8544-4600-9403-bc1b4f19d0a1">

## Additional context

- A community most likely to churn elevated this concern.

**Comment by CowMuon** [comment]
This should really be 2 tickets, 1 to fix the persistence bug on the engineering side (on the assumption it should persist) and separate from that the product ask around "default should be admin" that will either be resolved by the engineering fix, or we will have clarified the product ask in terms of the domain model.
