### ISSUE TITLE
Update <title> Tag to show Thread Title

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4746]
## Description

Currently, whenever you are on a view thread page (within a community), the Title of the Page (in the browser tab and in the html) stays simply "Commonwealth – [COMMUNITY]". The desired behavior is for the title to be content specific. (This is important for browser history as all history in chrome shows up as "Commonwealth – Community" => not useful for finding threads or other content.)

<img width="1018" alt="Screen Shot 2023-08-09 at 2 23 33 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/38b46e93-f7d8-422f-973c-c1cb66ab6d13">

### Desired outcome: 
- [x]  The Title Tag is "[Community] – [Thread Title]" when on a View Thread page.

### Extended Nice To Haves: 
- [x]  The Title Tag is "[Community] – Discussions" when on `/discussions`
- [x] "[Community] – Proposals" when on `/proposals`
- [x] "[Community] – Snapshots" when on `/snapshot/[spaceid]`
- [x] "[Community] – [Snapshot Proposal Title]" when on a view snapshot proposal page. 
- [x] Nice to Have: The Title Tag is "[Community] – [Proposal Title]" when on a View Proposal Page.
- NOTE: If for some reason the content title cannot be found to set the Title Tag, default to "[Community] – [Scope]" e.g. "Proposals", "Discussions"

## Acceptance Criteria

- Title Tag updates to include Thread Title when on a View Thread page.

## Additional context

- Requested Specifically by 1inch, an enterprise partner. 

------ 
Project: SEO Improvements
Project Lead: @zakhap

**Comment by CowMuon** [comment]
Super great to see this ask, really weary of products around the web neglecting page titles (so all my bookmarks have the same title) but it's not really selfish, this will be huge if we get the SEO right.

**Comment by CowMuon** [comment]
We are still using divs for titles instead of h tags, so fixing that across the site should be low hanging / high impact.  Should probably make that its own ticket.
