### ISSUE TITLE
Update design of council & governance pages

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#475]
Just styling and copy changes:

Note that we should always show the status of a proposal (right now we do not always show if it's completed).

![proposals listing](https://user-images.githubusercontent.com/1273926/88572486-12a51500-cff4-11ea-81a3-bbe904e93c4a.png)

**Comment by gdjohnson** [comment]
![image](https://user-images.githubusercontent.com/22281010/88582284-76433880-d01c-11ea-83c3-e4312621b8b6.png)

This is what my Proposals page looks like now. Do you want me to fully revamp the design to match the screenshot (moving sidebar to the top, revamping proposal row layout) or do you want just the more cosmetic styling stuff addressed? Should I leave the webfont for now, or?

I guess I'm a little uncertain as well about the different organizational schemas for proposals. Do you want me to leave them broken up as-is, by type, and just add "Active" vs "Inactive" statuses, and if so, how ought active vs inactive be determined?

**Comment by raykyri** [comment]
From our chat:

- Yes, we we want to separate Active and Inactive (basically re-grouping everything)
  - Neither Active nor Inactive proposals should be visually broken up by type, but we can keep the grouped in the ordering
  - No need to change the Like reactions
- We want to make sure the status of a proposal is always displayed. For treasury proposals, it's either "Waiting" or "Completed"/"Approved"/"Rejected" (I don't remember)
- Use your discretion on copy, some copy isn't ideal. "Will not pass" should become "Needs more votes" probably
- Comments probably displayed like in Discussion Rows
- Proposal titles should include arguments if they are short; long arguments should be truncated (e.g. binary blobs)
- Have not finalized how to display hashes yet but something like "unknown 0x340340948" will work and we can format it later
- For Treasury Proposals, generate strings on the frontend e.g. "570.89k EDG to Commonwealth Grants" for the title
