### ISSUE TITLE
Avatar Related Bugs

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4750]
## Describe the bug

2 bugs:
1. The vertical comment line in a thread is overflowing onto the user avatar component, as in the image. 
2. Also the user avatar component is not centered in it's circular container.

![image (5)](https://github.com/hicommonwealth/commonwealth/assets/31940965/c64374ba-a67e-491f-b5ef-b81ce2fa485c)
<img width="348" alt="Screen Shot 2023-08-09 at 6 43 32 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/90e15a59-7701-482e-b3f9-908c7fd43949">

## To Reproduce

Using a user profile with a profile image, create a comment in a thread. To see the non centered behavior more clearly, hover over the user component to trigger the dropdown. 

## Expected behavior

- [ ] Comment line should be beneath (z-index?) the Avatar
- [ ] In the popover, the avatar should be center in its circle.

**Comment by CowMuon** [comment]
Gentle reminder that tickets _must_ be estimated before moving to in-progress.

cc. @gdjohnson to confirm this is well documented.

**Comment by Miaplacidus** [comment]
@jnaviask @CowMuon 
The bug fixes in this card are now contained in PR #4885, alongside a reversion of the original avatar designs in issue #4750
