### ISSUE TITLE
Regression: spam reporting and filtering does nothing

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4765]
## Describe the bug

Discovered in #4545 -- comments and threads marked as spam are not hidden, and the checkbox does nothing.

## To Reproduce

Attempt to mark a thread or comment as spam, attempt to view it.

## Expected behavior

Should conform to spec laid out in #3977.

**Comment by mzparacha** [comment]
@jnaviask i did some digging on this but it looks like this issue is also on the comments spam as well, which is not updating its spam status. 

Can you please verify that and if we should create a separate ticket for it? 

cc: @jnaviask

**Comment by jnaviask** [comment]
Please use this ticket for both thread and comment spam fixes. @mzparacha

**Comment by mzparacha** [comment]
Bumping up the points
