### ISSUE TITLE
Templates should support struct input and encoding

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#4771]
## Description
Noticed that our CAT code/schema is missing support for a type of solidity arguments - structs. 

In early versions of Solidity structs as parameters were not supported but since about a year ago, this is a common way to save stack space in complex contracts. Most new state of the art contracts use structs for their params in some way. 

A struct looks like an object or dictionary in solidity and is encoded like a tuple of values in calls.

Therefore templates need a way to support a form that might take 2+ arguments and include them as a tuple at the struct arg. This will probably involve a new type a some input tag + logic to encode correctly 

## Engineering Requirements
- Can include a multi-arg form_field
- multi-arg are encoded into tuples 
- Can send tuples as structs to contracts
- ABI verification works for structs

## Acceptance Criteria
- Can define form fields for any length of struct 
- Structs transactions work

## Additional context
- This is required to use newer contracts like snapshot or uniswap as well as erc4337 related work

**Comment by ianrowan** [comment]
Proposing we write this pointing to master(as long as we plan to update experimental with master as well). Its a general use case and something that templates should support so probably makes more sense to include it globally 

CC @dillchen @MuonShot @jnaviask

**Comment by jnaviask** [comment]
Fine by me. Adding to C6 board. @ianrowan

**Comment by dillchen** [comment]
worth while also re template links as well (can deal with that next week tho)
