### ISSUE TITLE
Create, Refine, and Review Notifications MVP Spec

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4772]
## Description
Now that we have come to an agreement on the general architecture for the notifications system we can move forward with the MVP. We need a spec for setting up the AWS and developer environment written in a Google Doc.

## Engineering Requirements
- [ ] IAM/Account permissions
- [ ] SQS configuration
- [ ] Lambda configuration
- [ ] LocalStack configuration
- [ ] Developer processes set up

**Comment by timolegros** [comment]
This issue is not blocked but I suggest it be put on hold until larger CW issues are resolved. With the legacy notification system fixes that have been merged, the performance of the legacy system has greatly improved thus delaying the necessity for a new system. Furthermore, notifications on the client side are buggy and not feature-complete. It seems superfluous to create a stellar, scalable, event-driven architecture backend for a front-end that isn't 'there' yet. IMO, this issue should be revisited when any of the following occurs:

- Client-side issues with notifications are resolved
- Legacy system edges closer to the scalability ceiling
- Engineering specs for feeds need to be created

Additionally, it seems like CW could benefit from more eng bandwidth being applied to resolving existing goals like login/community creation flow improvements, Cosmos governance/onchain interactions/devnet testing, Webhook + email testing/bug fixing, forum moderation functionality expansion, etc which directly affect user retention/churn.

@jnaviask @MuonShot let me know if this makes sense or if I should march forward with this issue. If I shouldn't start working on this issue, please update the ticket status.

**Comment by timolegros** [comment]
> This issue is not blocked but I suggest it be put on hold until larger CW issues are resolved. With the legacy notification system fixes that have been merged, the performance of the legacy system has greatly improved thus delaying the necessity for a new system. Furthermore, notifications on the client side are buggy and not feature-complete. It seems superfluous to create a stellar, scalable, event-driven architecture backend for a front-end that isn't 'there' yet. IMO, this issue should be revisited when any of the following occurs:
> 
> * Client-side issues with notifications are resolved
> * Legacy system edges closer to the scalability ceiling
> * Engineering specs for feeds need to be created
> 
> Additionally, it seems like CW could benefit from more eng bandwidth being applied to resolving existing goals (which directly affect user retention/churn) like login/community creation flow improvements, Cosmos governance/onchain interactions/devnet testing, Webhook + email testing/bug fixing, forum moderation functionality expansion, etc.
> 
> @jnaviask @MuonShot let me know if this makes sense or if I should march forward with this issue. If I shouldn't start working on this issue, please update the ticket status.

@jnaviask bumping this comment. I think this issue should be on hold until the [Legacy Notifications Clean-up milestone][1] is complete and maybe even until chain-events is deprecated and replaced. Simply does not seem like a priority right now given everything else.

**Comment by jnaviask** [comment]
I agree that we should put this on hold until we have clear product specifications for what the enhanced notifications pipeline will be used for.

**Comment by timolegros** [comment]
The proposed notifications architecture was built upon incomplete PRDs/requirements and was done before Roger joined the team. Therefore, this ticket can be closed since the work that led to this ticket will essentially be redone. That said, this ticket and linked tickets + work can still be referenced in the newer model.
