### ISSUE TITLE
Snapshot creating hundreds of thousands of useless notifications

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4782]
## Describe the bug

328,341 of 342,765 notifications (~95.8% of all notifications) are snapshot proposal notifications and yet there are only 6610 `NotificationsRead` records associated with snapshot notifications. This indicates that we are storing a huge amount of notifications that never actually reach any users or feeds.

## To Reproduce

```
SELECT COUNT(*) FROM "Notifications" WHERE category_id = 'snapshot-proposal';
SELECT COUNT(*) FROM "NotificationsRead" WHERE notification_id IN (SELECT id FROM "Notifications" WHERE category_id = 'snapshot-proposal');
```

## Expected behavior

Only store snapshot-proposal notifications that have an associated community or subscribed user.

**Comment by jnaviask** [comment]
Great catch!! Please include within scope a migration to remove unused notifications.
