### ISSUE TITLE
Add website and chat fields

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#479]
The community info module currently has two links that are hardcoded to Edgeware:

![image](https://user-images.githubusercontent.com/1273926/87390104-fbc6e300-c55c-11ea-8b26-dfcee31e2067.png)

We should add a migration to add these fields to the backend, and let community admins set them from the Manage Community modal. The first should be called website and the second chat. The two fields should be directly underneath the Description field in the Manage Community modal.

Placeholder for website: `https://example.com`
Placeholder for chat: `https://discord.gg`

If either website or chat is filled without an http:// or https:// prefix, the modal should throw an error and prevent the user from saving. The fields can be empty though (in which case the corresponding rows should not show up in the community info module). https://, http://, and www. prefixes should be hidden when the link is displayed on the frontend.

**Comment by gdjohnson** [comment]
To be clear: do we want this for both chain and offchain communities, or should I stick to the latter for the time being?

**Comment by raykyri** [comment]
Both chain and offchain communities, consistency is better here (also I think we will want to integrate offchain communities w Discord eventually too)
