### ISSUE TITLE
QA + Fix: default addresses aren't saving

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#480]
I have two addresses on Edgeware and every time I open up the community, "Select an address" shows. After I pick one address that selection should be sticky...not sure why it isn't happening now, can't really look until the end of the week

**Comment by gdjohnson** [comment]
Interesting, this isn't happening for me on construct branch. The Select Address component may lack an address for a split-second, but once the data is fetched it populates correctly/consistently with my latest-used address (even if I have 2+ added to the chain) on refresh/navigation. Are you still experiencing this?

**Comment by drewstone** [comment]
This could be something to do a larger QA on with different chains and communities.

**Comment by gdjohnson** [comment]
Unfortunately, having issues with Moloch/Kusama (unable to join communities with existing chains; see #bugs) so I can only QA this on communities + Edgeware, but at least, there addresses (at least for me) are sticking properly.
