### ISSUE TITLE
Improve createChain error handling

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4808]
## Describe the bug

Currently /createChain call failures return very little information about the cause of failure. This information is accessible to the client in the return message, but is not being surfaced to the user. We need to ensure that the cause of error is surfaced.

## To Reproduce

Attempt to create a cosmos chain and provide an invalid RPC url. Notice the lack of context provided about reason for failure.

## Expected behavior

The cause of error is displayed to user either via error text or via a failure notification.

**Comment by alexyoung23j** [comment]
@jnaviask It seems that the error returned by the route is actually displayed to the user- in the example you provided, the user sees an error indicating that the rpc url is invalid. Was this error message not coming up for you?

**Comment by jnaviask** [comment]
Only error I get is "Creating new Cosmos community failed" -- nothing about RPC.
