### ISSUE TITLE
Migrate Profiles controller to react query

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4819]
Currently, profiles are loaded in a way that the state is not synced with React. This results in race conditions and rendering bugs.

Here's some example code that we use to asynchronously load (and cache?) profiles in the background:
```ts
NewProfilesController.Instance.getProfile(thread.chain, thread.author);
```

We should have a reliable pattern for loading and rendering profiles.

We can also clear a lot of [this](https://github.com/hicommonwealth/commonwealth/blob/f31844fa913e6b3577d9fe557d0c8667bffb902b/packages/commonwealth/client/scripts/views/components/user/user.tsx#L90-L168) logic in user.tsx.

## Acceptance Criteria
- Create a React-friendly pattern for loading and rendering profiles (hook?)
  - If there are API changes that can make this more efficient, feel free to make a suggestion
- Refactor all uses of `NewProfilesController.Instance.getProfile` to use the new pattern
- Ensure that all affected components render profiles correctly
- The User.tsx should be simplified

**Comment by rbennettcw** [comment]
@mzparacha Can you take a look at this?

**Comment by mzparacha** [comment]
sure @rbennettcw. Will start on it later today

**Comment by mzparacha** [comment]
I believe we should just migrate the [newProfiles](https://github.com/hicommonwealth/commonwealth/blob/25ea2c8f15b43857ab16ab4c493fb8073c53e26c/packages/commonwealth/client/scripts/controllers/server/newProfiles.ts) controller to react query, which would be the best way forward IMO.

cc: @jnaviask @CowMuon

**Comment by jnaviask** [comment]
@mzparacha sounds good to me as a scope of work!

**Comment by mzparacha** [comment]
> @mzparacha sounds good to me as a scope of work!

Great, updated the title to reflect that

**Comment by mzparacha** [comment]
Bumped up the point as the changes are a little complex
