### ISSUE TITLE
Ledger support for V1 CommunityPoolSpendProposal

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4821]
## Description

Amino support for creating a CommunityPoolSpendProposal was done in #4731 , but in `v1` chains there is an error in the chain response: `Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (9799), sequence (2) and chain-id (kyve-1): unauthorized`. 

## Engineering Requirements

Debug the amino encoding for this case, and ensure it is formulated correctly.

## Acceptance Criteria

In `csdk` community, I can create a Community Spend proposal with a ledger account

## Additional context

(Cosmos SDK ticket)
- The error described above is misleading - this is a common cosmos sdk error which can occur for many reasons. Part of this effort will be investigating root cause.

**Comment by jnaviask** [comment]
Wont fix.
