### ISSUE TITLE
Some cosmos /proposals not loading

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#4822]
## Describe the bug

Observed in juno and injective, but not other Cosmos chains:
Page loads, but "No active proposals" and "No past proposals" when there should be.

## To Reproduce

- https://commonwealth.im/juno/proposals
- https://commonwealth.im/injective/proposals

## Expected behavior

Proposals match those on 
https://wallet.keplr.app/chains/juno?tab=governance, 
https://wallet.keplr.app/chains/injective?tab=governance

## Additional context

osmosis, regen, evmos, stargaze, kyve, quasar-finance seem fine.

**Comment by mhagel** [comment]
cause unknown so estimating at 3

**Comment by mhagel** [comment]
It was very easy fix, so made it a 1

**Comment by sachben91** [comment]
Tested
- Proposal page on Keplr matches that on Common for Injective and Juno
