### ISSUE TITLE
Add Mature and regular e2e test jobs on CI

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#4827]
## Description
e2e tests are difficult to write due to their flaky nature. They often require an iterative approach to resolving the flakiness. As a result we have taken them out of the required runs for the CI.

To make the tests more useful, it would be good if we had two jobs in the CI suite.
1. e2e tests (not required for PR merge). These are new e2e tests that we deem as potentially flaky. These will be put in this suite to be run so that flaky failures can be brought to light
2. Mature e2e tests (required for PR merge). These are the e2e tests that have withstood many runs through the CI without flaky failing. They are extremely likely to indicate a issue with the PR. 

The new workflow for e2e tests in the CI will be as follows:

1. developer writes e2e test.
2. When this e2e test passes multiple runs on the CI we move it to the Mature e2e tests folder

(Optional) We can add a github actions script in order to log the last failure of an e2e test if the CI is run on master (# of passed CI runs on master merge). If this number exceeds a certain number of runs, it could auto-create a PR in order to move it from the flaky folder to the mature one.

## Engineering Requirements
- Have two folders in repo for Regular and Mature e2e tests.
- Make two github jobs, one that runs regular e2e tests and one that runs Mature e2e tests.
- (Optional) Add github actions script to keep count of (merges since last accident) for each e2e test.
- (Further Optional) If it passes a certain threshold, automatically open a PR to move that test from the regular folder into the Mature folder.

## Additional context
Please discuss optional and further optional engineering requirements in comments. They may be too ambitious for a single PR, or not worth the effort.

**Comment by jnaviask** [comment]
@kurtisassad a lot of e2e tests failing currently -- feel free to include fixes as part of this PR.

**Comment by kurtisassad** [comment]
They look to be mostly an easy (2 line fix). They are failing due to the timeout I introduced in the CI being too short. I will fix this as part of this PR, but it could also be a separate quick hotfix merge into master.

**Comment by jnaviask** [comment]
Even the database-related issues? @kurtisassad

**Comment by kurtisassad** [comment]
No. Database brought up in the PR are directly related to the PR (This ticket). The timeout fix is more broadly related to the CI suite in general.

**Comment by jnaviask** [comment]
@kurtisassad I see the database piece is marked "optional" in the original ticket description. Since we're having so much trouble, can we just emit the artifact and leave the automatic "flaky" PRs as a fast follow, so we can get the bulk of the work in?

**Comment by CowMuon** [comment]
+1 Jake's suggestion here. Please leave off flaky tests and just emit the artifact so we can get this into release `0.6.8`

**Comment by kurtisassad** [comment]
Proposed changes (excluding optionals) in separate PR ready to go
https://github.com/hicommonwealth/commonwealth/pull/4963

**Comment by jnaviask** [comment]
@kurtisassad can you open a follow-up ticket with the remainder of the work involved?
