### ISSUE TITLE
Move linking routes to patch thread route

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4831]
Currently, the logic for adding/removing links from a thread exists in dedicated routes:
- `DELETE /linking/deleteLinks`
- `POST /linking/addThreadLinks`

We should move that logic to the unified `PATCH /threads/:id` route.

## Acceptance Criteria
- Backend: Move logic to patch threads route (preserve permissions)
- Backend: Delete old linking routes
- Frontend: Update linking logic to use patch threads route

**Comment by jnaviask** [comment]
@rbennettcw this is a matter of some debate in terms of how we want to conceptualize the "linking" domain -- we may not want to subsume linking under threads -- linking may need to stay more general. Adding this to the backlog until we get @zakhap eyes on it, as it's a product-level question.

**Comment by zakhap** [comment]
I'm fine with the merging of the two routes into a single PATCH route, but wary of pulling it into the Thread domain explicitly at the moment. There is some amount of product attention being placed on Linking Proposals (and external content), though nothing is yet aligned on definitively in such a way that it can be used as a north star / product guide here.

**Comment by jnaviask** [comment]
Not planned.
