### ISSUE TITLE
Replace "Gate Discord" with "Connect Discord"

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#4832]
## Description

The old "gate discord" option in the sidebar menu has been replaced with a connect discord option. This allows users to connect discord to set up a bridged forum, same as in the manage community panel. 

## Engineering Requirements

Remove the gate discord option from universal create, and put it in the community create section. Then, replicate the connect discord flow from manage community page. Only admins should be able to see this option, and only when discord isn't already connected.

## Acceptance Criteria

Admins can add a discord bot via the sidebar in addition to the manage community page.

## Additional context

This was initially a bug report, but on discord sync we talked about fixing it with this functionality.

**Comment by sachben91** [comment]
Tested and verified.
