### ISSUE TITLE
Chain-specific settings & notification settings pages

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#485]
Going to the settings page right now switches you away from the current chain. 

We should just render the same settings page at /edgeware/settings, /kusama/settings, etc.... and /settings to avoid this UX interruption (and same for /notification-settings etc).

We should make sure any links to the settings page respect the user's current chain and maintain that (this may require a helper, we should avoid repeating code unnecessarily, etc).

**Comment by gdjohnson** [comment]
If the user is in a community, do we just route them to /settings?

**Comment by zakhap** [comment]
it's just changing `/settings/` to `:scope/settings`, i believe. and then checking to see if there are unexpected effects

**Comment by gdjohnson** [comment]
Yeah by "community" I should've specified "offchain community."

**Comment by gdjohnson** [comment]
AFAICT there are no navigations, in the codebase, to /notification-settings where a chain/community is also present. Here's the only case, rendered when both app.chain and app.community are absent: 
![image](https://user-images.githubusercontent.com/22281010/87971778-daea1a80-ca93-11ea-9eac-2e63833f80af.png)

I've added a `:scope` in the router, and updated the two cases of /settings routes where a chain would be present, but there's not all that much to be done here if I'm understanding the prompt right, so wanna check in.

**Comment by raykyri** [comment]
That sounds right! 

Will need to double check during QA, but I don’t think we will have links to /notification-settings until we add more ability to reconfigure notifications

**Comment by gdjohnson** [comment]
Closing on account of #494 merging.
