### ISSUE TITLE
Create a lightweight Cosmos notification generator

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4864]
## Description

Chain-events currently creates proposal-submitted notifications for `osmosis` by subscribing to all blocks and parsing the relevant messages within. This functionality needs to be replaced with a lightweight event filtering schema. This is likely to be one of the following solutions:
1. Query historical chain data directly by filtering by `message.action`
2. Subscribe to specific events.

The system should contain a receiver or retriever of events and a formatter of events.

## Engineering Requirements

- A new dyno (either on CW App or a new app) which retrieves or receives events and formats them before calling `emitNotifications`.

## Additional context

This issue requires more in-depth discussion and speccing.

**Comment by jnaviask** [comment]
@timolegros Problem with using websockets is that Cosmos chains only support HTTP. Feel free to investigate scope on message.action filtering. Curious what you have in mind specifically, implementation/architecture-wise.

**Comment by timolegros** [comment]
@jnaviask Mark and I have agreed to change course here implementation-wise. I looked into event fetching and it isn't a well-developed feature. Additionally, it seems to be deprecated on some API's. I think the solution we've come up with is much better.

Rather than fetching Cosmos events, we can fetch the objects we need to emit notifications about directly. The example flow would be:
1. Check the database for the latest emitted new proposal notification for Osmosis (suppose it's for proposal #3).
    - Note the case exists where we've added a new chain for which notifications should be emitted. In this case, there is no prior notification so we start fetching from the latest proposal or any proposal that was submitted less than X minutes ago.
3. Query the chain for proposal #4.
4. If 404 -> no new notification needs to be generated. If 200 -> generate a notification for proposal #4 and repeat 1-4.

This supports the basic notification (proposal submitted) that chain-events supported but we can go a step further. In the proposal object, we also get timestamps for when voting starts and ends. Using this information we can emit notifications about the proposal lifecycle to drive engagement with proposals.

Where this repeated call executes is up for debate. That said, considering how lightweight it is, a separate dyno seems excessive. This could be a simple setTimeout job or a scheduled cron job depending on https://github.com/hicommonwealth/commonwealth/issues/4901 (if we run the job every 10 minutes we could just use Heroku Scheduler).

This is the most lightweight solution possible. We never parse blocks and we never needlessly parse all proposal data we don't need. Quick to implement and easy to maintain.

**Comment by mhagel** [comment]
I like where this is headed. Some things to keep in mind:

1. Scaling - In a world where the appchain model continues to grow, the number of polling workers does too. So 1000 chains * 1 request per x minutes = maybe too many in the future? Maybe this isn't a big concern for us because we don't "turn on" notifications by default. However, if this is a possible caching solution, we want to think about scaling.
2. Let's keep _Subscribing to events_ option open. I don't know yet how standard it is to keep a Web Socket available, but it may be a default option to open a websocket address on a node. I can look into this a bit.

**Comment by timolegros** [comment]
> I like where this is headed. Some things to keep in mind:
> 
> 1. Scaling - In a world where the appchain model continues to grow, the number of polling workers does too. So 1000 chains * 1 request per x minutes = maybe too many in the future? Maybe this isn't a big concern for us because we don't "turn on" notifications by default. However, if this is a possible caching solution, we want to think about scaling.
> 2. Let's keep _Subscribing to events_ option open. I don't know yet how standard it is to keep a Web Socket available, but it may be a default option to open a websocket address on a node. I can look into this a bit.

Scaling to 1000x blockchains is a concern regardless of what method we use but this method is probably the best for scaling. With WebSockets it's 1k persistent connections vs now it's 1 request per chain per minute. We can keep subscriptions open but if we can do it this way I don't see why we would subscribe. Subscribing means having to deal with missed events during server restarts/downtime and I realllly don't want to have to do that.

**Comment by jnaviask** [comment]
I like the new approach, although I worry about having to replace it wholesale when we move to a new notification system (still TBD). For that reason we should ensure the logic is well modularized.

Main question I have is what's our estimate for how long it will take to implement?

**Comment by timolegros** [comment]
> I like the new approach, although I worry about having to replace it wholesale when we move to a new notification system (still TBD). For that reason we should ensure the logic is well modularized.
> 
> Main question I have is what's our estimate for how long it will take to implement?

It should fit really well with whatever system we want. We can run it as a scheduled Lambda on AWS, Heroku scheduled job, or in a persisted container/dyno. Given that I have nothing else on the board I got a head start on this today. Probably looking at 1 more day to have notifications being generated and another day after that for tests + client-side adjustments. My main concern is interoperability with the existing chain-event-based notification system i.e. removing dependency on CE App for loading notifications (will cause friction since EVM notifications will still require CE while Cosmos notifications won't).

**Comment by timolegros** [comment]
Will complete #4667 prior to marking this issue as ready to go so that we can QA more effectively.

**Comment by CowMuon** [comment]
What's the ~~expected~~ ETA for this one #4864 being R2G? (Obviously, the Test Plan section here will need to be filled in prior to that.)

**Comment by timolegros** [comment]
> What's the ~expected~ ETA for this one #4864 being R2G? (Obviously, the Test Plan section here will need to be filled in prior to that.)

Likely Sept 7 EOD. Facing some issues with Cosmos devnet tests which I am working through with Mark. If devnet tests are resolved then I will put the PR up for review.
