### ISSUE TITLE
Gating | Groups Core | Groups Module set up

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4868]
### Context 
This ticket describes the back-end functionality for setting up groups in Gating.  

### User Story

As an Admin, I want to organize my community into Groups, defined by attributes that are verified. 

The attributes I want to group members by are:
- I want to group members by minimum balance of tokens
- I want to group members by using their addresses to add them to an allowlist

[User Story described here in more detail](https://www.notion.so/buildcommon/PRD-Gating-MVP-fd8933234c1e44b38987a2e6ac2fe11a?pvs=4#d32779be58d74d63882fc22e50bc4a53)

### Designs

[Clickable prototype for Gating. ](https://www.figma.com/proto/ePuGFatYQI6GL72i27sVwj/Gating?type=design&page-id=3%3A38&node-id=431-11420&viewport=136%2C246%2C0.02&t=at668i3oZO4OZRG8-1&scaling=min-zoom&starting-point-node-id=431%3A11420) The first few pages show the groups functionality

### Functionality 
The groups module should have the following functionality:

- Admins to Create / Edit / View and Delete Groups.
    - Editing includes Metadata + requirements (new + updated).
- Get route that returns all Groups with metadata and requirements.
- GroupCheck service that validates whether a signer (address) passes the Requirements.
    - Logic around the Set of Requirements is ALL or SOME (and number), allowing for the spectrum between ALL and OR.
    - Allow Forum + other (internal) applications to use the GroupCheck route, like a “pre-action hook”. => Topic can require a Group.
        - Minimally, route should take a signer (an address) and 1 group id returning yes/no.
        - More generically, route to take a signer and many group ids, returning boolean for each Group.
        - Not yet useful, route takes many signers and many group ids, returning some organization of signers and groups they are in/not.
- At Sign-in, we should validate all of a User’s signers in communities to their respective community’s Groups. This information should be provided to the client for enhanced UX around the site regarding what the user can and cannot do. See Ticket 3 for usage.
    - After some interval, if a GateCheck request is made, we should re-validate the signer against the Group requirements. Makes sense if same length as Session Key.
- As a developer / repository contributor, adding new Requirement Types should be straight-forward.
    - Tests included, required.

-  Technical Specifications: TBD

**Comment by jnaviask** [comment]
To be clear: there is no method to list all current members of a group?

**Comment by sachben91** [comment]
@jnaviask all the current members of the group should in the "groups" tab on the members page as shown in the screenshot, just corrected that.  



![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/0c24d2ec-471b-4af4-91fc-4a502240bb45)
