### ISSUE TITLE
Gating | Groups Core | Migration and Depreciation

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4870]
### Context
This ticket describes the migration from the existing token gating mechanism to the one defined by this new feature set. 

### User Story

As an admin I want all the rules from the current token gating mechanism to be migrated and available in Groups so that I do not have to create the rule sets again 

### Behavior 
- Migration should do two things:
    - For each unique token threshold within a community, create a Group with a Requirement defined by the threshold information. For Each topic with the same threshold, set each Topic’s to the same, respective Group.
        - For example, if an ERC20 community has 2 different thresholds set (“10 tokens” for X topic, and “2 tokens” for Y,Z,A,B,C topics), create 2 different Groups each with their own requirement using the thresholds; Group 1 of Requirement Type “ERC20”, contract pulled from community, Chain pulled from ChainNode, and greater than or equal to “10 tokens”; same for Group 2 but “2 tokens”. For Topics Y, Z, A, B, and C, they should all be set to Group 2.
        - For “Cosmos” communities with Thresholds set, use the “Cosmos Base Token” Requirement Type for the Groups’ Requirements.
    - Remove “Threshold” from Topic Model.
- Deprecation should remove all Topic Threshold related logic from the Client and Server.

### Technical Specifications
TBD

**Comment by jnaviask** [comment]
Blocked by interface design from #4868.
