### ISSUE TITLE
Implement Custom Domains via Cloudflare

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4882]
# Overview

## Motivation
Currently all our assets are cached on our CDN (cloudflare). Because we only run our custom domains on heroku, when we give this custom domain to the clients, the resources that it requests are uncached. This has two problems:
1. This increases the strain on our servers
2. This increases the response time because the connection has to make a round trip to our server instead of the closest edge node. This is especially noticeable for clients in different regions

## Initial Setup
- Setup Cloudflare account to enable “Cloudflare for SaaS”: https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/start/getting-started/
- Get the API key

## Migration
- Ideally, the Cloudflare implementation should coexist with the Heroku implementation, allowing users a grace period to reconfigure their domains without disruption
  - Specific details of the hybrid implementation TBD
- Database migration should add tables/columns for tracking domain verification status (TBD)
  - This is not strictly necessary, as we can treat the Cloudflare API as the single source of truth for domain status

## Routes to add (paths TBD)
- Create custom domain
- Edit custom domain
- Delete custom domain (?)
- Check custom domain verification

## Env vars to add (specific naming TBD)
 - Cloudflare API Key

## Testing
 - Will need dedicated domain so we can test the verification flow

## Draft Sequence Diagram

![Image](https://github.com/hicommonwealth/commonwealth/assets/126922418/bc727b42-6da3-4c04-b748-0b12f313491f)

**Comment by kurtisassad** [comment]
#### For testing
I think we shouldn't spend time on TDD for integration tests for this one since CNAMEs could take up to a few hours to propagate. The integration tests wont be able to run in real time so should probably be skipped.

I am in the process of writing e2e tests for custom domains, so this can also be skipped (I can modify the existing tests to work with this new method).
