### ISSUE TITLE
Docs Improvement: Table of Contents Audit + Reorg

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#4889]
Would like to keep this open a little while before Teeing Up—will use it to begin thinking through how we might organize our docs, but this will take time, and premature optimization is the source of all suffering.

The first step will involve an audit of the documentation we presently have in our knowledge base. 

Another step will be deciding whether to have a "flat" directory structure + multi-org TOC, or else do a single hierarchical organization.

**Comment by gdjohnson** [comment]
Blocked by #6334.

Once we have a developed domain model we can organize the ToC around it.

**Comment by ForestMars** [comment]
conflicts.
