### ISSUE TITLE
Unify polls routes into polls controller

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4902]
## Description

Currently we have the following routes relating to polls:
- getPolls
- createPoll
- deletePoll
- viewVotes
- updateVote

We should refactor these routes into a polls controller, to continue with our standard backend route style.

Ideally we can have a standard endpoint which allows creation (createPoll), querying by poll id (viewVotes), deleting by poll id (deletePoll), voting by poll id (updateVote), and querying by thread id (getPolls -- noting that a single thread can have multiple polls).

The last case, getPolls, may be an outlier, so we should determine exactly how to lay out the routes to make that specific case clean / sensical. Would love to see a comment with a proposed route schema.

**Comment by rbennettcw** [comment]
Proposed route changes:
- Get polls by thread: `GET /threads/:id/polls`
- Create poll by thread: `POST /threads/:id/polls`
- Delete poll: `DELETE /polls/:id`
- Get poll votes: `GET /polls/:id/votes`
- Update poll vote: `PUT /polls/:id/vote`

I assume that you mean that `updateVote` is the outlier. Yes it is, though I think `PUT /polls/:id/vote` can work, as it implies an upsert of the poll vote (singular).

**Comment by rbennettcw** [comment]
Ranking as 3 for code cleanup, updating logic to use latest patterns, and adding tests.
