### ISSUE TITLE
TextInput Design Implementation

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#4904]
Design for the new TextInputs has been completed. This card goes towards replacing existing TextInputs with the new designs. 

One important thing to note is that the new component has two additional (required) props. Every replaced input will have to be checked for appropriate sizing. 

We'll want to implement TextInputs section by section (this will be determined somewhat arbitrarily; the "element" could be as large as a page depending on the number of text inputs to check) to make each card easier to review. 

See #3934 for context.

Tagging @martins87, @jessmart1213, @zakhap  for further details and creation of new cards.

**Comment by jnaviask** [comment]
Ticket is not ready to go, needs details from tagged parties.

**Comment by martins87** [comment]
> Ticket is not ready to go, needs details from tagged parties.

Details given [here](https://github.com/hicommonwealth/commonwealth/pull/4293#issuecomment-1705466704).

**Comment by jnaviask** [comment]
> > Ticket is not ready to go, needs details from tagged parties.
> 
> Details given [here](https://github.com/hicommonwealth/commonwealth/pull/4293#issuecomment-1705466704).

I don't see how the linked comment has anything to do with this issue.

**Comment by Miaplacidus** [comment]
Hey, @jessmart1213 @zakhap!
Please do take a look at this card to fill in any remaining details!

**Comment by jnaviask** [comment]
Superseded by #5273.
