### ISSUE TITLE
[2.0 Site Integration] - Crowdfunding UI Component cards

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#4906]
### Description 

As discussed we will build custom cards to support farcaster crowdfunding due to the complex nature of the contract interactions.

#4905 (blocked until complete) is building contract interaction helpers with basic types to define the required input data. As long as the correct data is sent to these methods the contract interaction should just work, meaning the UI work is abstracted from the on-chain interactions. 

In this issue we need the following simple cards built using the links sidebar/style:

1. Create Campaign
2. Back Campaign 
3. Withdraw backing
4. Withdraw proceeds

Card input will be generally self explanatory although data passed to helpers will be comprised of input + existing metadata on the thread. Should be mostly intuitive, but consult @ianrowan if needed on where to get data.

UX for these cards should be as follows. 

- Define a way to know if a thread should show crowdfunds at all(ie we only want this on farcaster currently)
- On a thread that is fund-able the following behavior should be present:
    - If no crowdfund is initiated(check links column and see more later as to why) -> Only show Create Project card
    - Upon creating a a project, save project data as a link in links column(create a new link enum called crowdfund) 
    - If a crowdfund link exists and is still active(Deadline not met yet = check contract via helper) -> Show Back Campaign and Withdraw backing card
    - If deadline or goal met(check helper) show Withdraw Proceeds card.
- The above mentioned helpers to get contract data will take some kind of identifier(contract address), this would be best to use for the link identifier of a crowdfund

### Acceptance Criterea 

- Creation of the 4 cards and proper data collection + passing to helper functions 
- Loading/waiting states for contract interactions while helpers are called
- Definition of the new crowdfunding link type
- Dynamic visibility of cards based on crowdfund state

**Comment by fgfhhjkjkklklkjhgfddsdsdsfghj** [comment]
I can perfectly help you with your crowdfunding campaign
I have a lot of my previous work with.
Kindly respond to me so that I can share you

**Comment by dillchen** [comment]
**Create Campaign**

Prefilled Template Link with inline display -> should have prefilled values

1. Minimum amount
2. Beneficiary => inferred to whom the OP / FID is
3. Description
4. Voting Criteria (prefilled -> a quorum of X specific holders)

**Back Campaign**

![Image](https://github.com/hicommonwealth/commonwealth/assets/5334557/28f2b57e-08fb-4cce-b8e1-886115e56841)

**Withdraw Backing** and **Withdraw Claim**

![Image](https://github.com/hicommonwealth/commonwealth/assets/5334557/bdd31d7a-c82f-4f14-adcb-b2ba8b37cd48)

**Comment by dillchen** [comment]
Use existing form component
