### ISSUE TITLE
Add Sort by "Latest Activity" option

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4908]
## Description

We used to have a Sort By Latest Activity option for Threads. We deprecated that feature when updating our routes + sort options, but have since received a lot of requests for this option to be brought back.

"Latest Activity", as a sort option, should use a timestamp as its sorting criteria. The initial timestamp used should be the Thread's creation time, but once there are comments on the Thread, the Comment's creation time should used for the sort. 

## Engineering Requirements

Suggestion: we might keep this timestamp on the Thread itself, distinct from created + updated at.

**Comment by alexyoung23j** [comment]
Encountering some strange bug where the threads keep being rapidly re-fetched, extending the estimate.
