### ISSUE TITLE
Add a e2e custom domain test

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#4921]
## Description
Custom domains are a bit of a pain and afterthought to CA. It would be good to have a basic custom domain smoke test in our E2E suite.

## Engineering Requirements
- Create an e2e test(s) that tests the landing page for some (or multiple) communities to make sure it loads correctly

## Additional context
wiki/Custom-Domains.md contains the steps we currently use to test custom domains. We will need to modify the CI in order to replicate these steps (modify /etc/hosts, then start up the ssl-proxy)

**Comment by jnaviask** [comment]
@kurtisassad we should be clear: the Commonwealth landing page should not appear at all on custom domains, it should instead load the community's home page as the landing page.

**Comment by kurtisassad** [comment]
Taking a bit longer than expected due to the CI being a lot of work to debug. Bumping up to a 2 pointer
