### ISSUE TITLE
Copy on-chain identity names & verification statuses to OffchainProfiles

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#493]
- Add a `verified` column to OffchainProfiles. This can be a JSON blob of {registrar => attestation}s since it is not obvious how to clean that data
- Copy on-chain identity names & verification statuses automatically to OffchainProfiles, as blocks are processed
- There should also be a manual migration that can be run by running e.g. `COPY_ONCHAIN_IDENTITIES=true yarn run start` that scans all identities. The deployer can run this after we push it to prod

**Comment by jnaviask** [comment]
How should we handle the fact that "data" is currently just a JSON blob (not even a JSON type in POSTGRES but a string, so we can't even query it)? Should I also add an "identity" column?

**Comment by raykyri** [comment]
Yeah, “identity” sounds good. Or “onchain”?

**Comment by jnaviask** [comment]
Waiting for #481 before doing this.
