### ISSUE TITLE
Incorrect Rollbar Error Reporting

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4932]
## Describe the bug

Rollbar is reporting that there have been numerous `SequelizeDatabaseError: out of memory` errors, but upon further inspection of the stack trace, it is apparent that the error is actually `SequelizeDatabaseError invalid input syntax for type integer: "NaN"`. The original/actual `SequelizeDatabaseError: out of memory` error needs to be found and differentiated from the incorrectly labelled error.

## To Reproduce

View the [rollbar error][1].

## Expected behavior

The title of the Rollbar error should be `SequelizeDatabaseError invalid input syntax for type integer: "NaN"`.

## Additional context

[1]: https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/4603?utm_campaign=item_velocity_message

**Comment by timolegros** [comment]
@jnaviask this issue is much more widespread than initially anticipated. There are lots of other examples of Rollbar grouping incorrect errors together though all of them seem to be related to `SequelizeDatabaseError`. I have not found examples of incorrect grouping outside of that error class. 

To list just a few that I have found:
- https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/4603#detail
- https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/4598
- https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/7234
- https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/7185
- https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/4139

I believe the reason for this is that Rollbar's default grouping algorithm primarily uses the error's class name (SequelizeDatabaseError) to group.

In order to resolve this issue, we can setup a custom fingerprinting rule specifically for SequelizeDatabaseError. This would look like the following:
```
[
  {"condition": {"path": "body.trace.exception.class", "eq": "SequelizeDatabaseError"},
    "fingerprint": {{ body.trace.exception.message }},
    "title": {{ body.trace.exception.message }}
  },
]
```
This fingerprinting rule matches all errors that have a class name of "SequelizeDatabaseError" and assigns their fingerprint as their error message. In other words, SequelizeDatabaseErrors will be grouped by their error message.

More info on custom fingerprinting can be found in the [rollbar docs][2].

To test out the solution we should add the rule and review 1 week later whether any `SequelizeDatabaseError` reports were incorrectly grouped.

[1]: https://docs.rollbar.com/docs/custom-grouping

**Comment by CowMuon** [comment]
This is so 🚀.

Only thing for me –other than execution– is confirming point estimate once the PR is up. Thanks Timothee, really good forensics here.

**Comment by timolegros** [comment]
> This is so 🚀.
> 
> Only thing for me –other than execution– is confirming point estimate once the PR is up. Thanks Timothee, really good forensics here.

Point estimation remains the same. There is no PR to be made, if the proposed solution is accepted, I need to add the fingerprinting rule in the Rollbar dashboard which takes all of 3 seconds.

**Comment by timolegros** [comment]
The custom fingerprint rule has been added to both projects on Rollbar. Let's review in a few days to ensure SequelizeDatabaseErrors are being properly grouped.

**Comment by timolegros** [comment]
@jnaviask I'd like to change the fingerprint rules to:
```
[
  {
    "condition": {
      "all": [
        { "eq": "SequelizeDatabaseError", "path": "body.trace_chain.0.exception.class" },
        { "contains":  "invalid input syntax", "path":  "body.trace_chain.0.exception.message" }
      ]
    },
    "fingerprint": "{{ body.trace_chain.0.exception.class }}: Invalid input syntax",
    "title": "{{ body.trace_chain.0.exception.class }}: Invalid input syntax"
  },
  {
    "condition": {
      "eq": "SequelizeDatabaseError",
      "path": "body.trace_chain.0.exception.class"
    },
    "fingerprint": "{{ body.trace_chain.0.exception.message }}",
    "title": "{{ body.trace_chain.0.exception.class }}: {{ body.trace_chain.0.exception.message }}"
  }
]
```

Namely adding the class name to the title as well as adding a new rule to group together the `invalid input syntax` SequelizeDatabaseErrors which are most commonly associated with spam.

**Comment by jnaviask** [comment]
Looks good to me. After this change goes in, we should identify continued outliers and make a PR to ensure that our error handling itself is correct.

**Comment by timolegros** [comment]
@jnaviask let's close this issue if we are satisfied with the fingerprinting rules. The custom error can be viewed along with all of its occurrences [here][1]. I'm not seeing any Sequelize errors being misreported.


[1]: https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/7771
