### ISSUE TITLE
Add uniqueness guarantee to ChainNode's eth_chain_id

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4955]
## Description

Akin to #4951, Ethereum Chain Nodes need a canonical identifier. We should ensure that the eth_chain_id field suffices for this purpose, by adding guarantees that it is unique.

## Engineering Requirements

- Add validation logic or schema changes to ensure eth_chain_id is unique.
- Ensure locations where eth_chain_id is set (e.g. CreateCommunity pages) do not permit the creation of duplicate eth_chain_ids.

**Comment by mhagel** [comment]
There are 2 rows with eth_chain_id = 1. "Ethereum (Mainnet)" and "testxyz"

Should I delete the one named "testxyz", or just change its ID?

`1360 | https://eth-mainnet.alchemyapi.io/v2/BCNLWCaGqaXwCDHlZymPy3HpjXSxK7j_ | 1 | https://eth-mainnet.alchemyapi.io/v2/BCNLWCaGqaXwCDHlZymPy3HpjXSxK7j_ |   | ethereum | testxyz `

@ianrowan @jnaviask @timolegros

**Comment by timolegros** [comment]
> There are 2 rows with eth_chain_id = 1. "Ethereum (Mainnet)" and "testxyz"
> 
> Should I delete the one named "testxyz", or just change its ID?
> 
> `1360 | https://eth-mainnet.alchemyapi.io/v2/BCNLWCaGqaXwCDHlZymPy3HpjXSxK7j_ | 1 | https://eth-mainnet.alchemyapi.io/v2/BCNLWCaGqaXwCDHlZymPy3HpjXSxK7j_ |   | ethereum | testxyz `
> 
> @ianrowan @jnaviask @timolegros

I don't see the second one (testxyz). `SELECT id FROM "ChainNodes" WHERE eth_chain_id = 1;` yields only a single result on the production follower database.

**Comment by mhagel** [comment]
>I don't see the second one (testxyz)

My mistake lol. I must have added it to my local and forgot.
