### ISSUE TITLE
Tooltip Preview for Links in Threads and Comments

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4959]
## Description

Unlike Discord where link destinations are hidden, we should let users see the link destination before they click with our tooltip component. 

## Acceptance Criteria

- Wherever there is a link in a comment or thread, on:hover should open a Tooltip that displays the link destination.

## Additional context
One of the reasons we need to add this is for security, as for example on Discord bad actors can hide unsafe links with no way to preview the actual link destination. This is a problem (for Discord) obvi and one we wish to avoid ourselves, by allowing users to see actual link destination before they click.

**Comment by CowMuon** [comment]
How are we handling shortened URLs here?
