### ISSUE TITLE
Add boolean for whether an OffchainCommunity should be visible on the homepage 

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#496]
Fairly self explanatory:
- If false, the community should be hidden on the homepage but otherwise visible.
- Doesn't require any management routes on the backend, since we can just set it manually from the SQL prompt
- All our current communities should be set to visible on the homepage, but future created ones should not default to true

**Comment by gdjohnson** [comment]
Can you give a little more context? What do you mean "set it manually from the SQL prompt"? I'm assuming this will still be a column on the OffchainCommunity table.

Should I not worry about ways for users to set or update the value, and just write a migration that manually adds true values to all current communities, and then change the createCommunity route so it default to setting the column value to false on community creation? Should the column just be called "visible"?

**Comment by raykyri** [comment]
Yeah, there's no need for users to set the value, and calling it visible seems fine!

**Comment by gdjohnson** [comment]
Manually closing on account of #504 merging.
