### ISSUE TITLE
Use v1 gov interface for Cosmos v1 testing, instead of v1Beta1 legacy interface

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4965]
## Describe the bug

The devnet tests currently take advantage of the fact that the devnets have a legacy gov interface which makes v1Beta1 requests compatible with the newer v1 interface. This has been very useful to ensure v1 transactions work but it means that v1 gov-specific code (mainly within the Cosmos notification generator) is not being fully tested.

## To Reproduce

Run Cosmos devnet tests.

## Expected behavior

v1 gov interactions should be made through the latest v1 gov interfaces.

**Comment by mhagel** [comment]
Probable separate ticket: Add `messages` input to `v1` proposal creation.

Right now, we have TextProposal. Our current interface wraps "/cosmos.gov.v1beta1.TextProposal" in a "/cosmos.gov.v1.MsgExecLegacyContent". In this ticket, we probably want to see if v1 natively does something other than "legacy" wrapping.

In the "messages" ticket, we will want to see if multiple messages should be added to a TextProposal or some other proposal-type.
