### ISSUE TITLE
Make thread dropdown menu compact

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#4969]
The thread dropdown menu (which appears when you click on the 3 dots on the bottom right hand corner of a thread card) is too spread out, i.e the distance between adjacent list items too large.

 @jessmart1213 Please add relevant designs in comments!

**Comment by zakhap** [comment]
https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=2849-3583&mode=dev

Here is the dev link to the dropdown component with the _compact_ version

**Comment by ForestMars** [comment]
Given this is a 1 pointer, it can be jumped ahead of #5156 & #4904 assuming they have higher point estimates. So, (while) absolute prioritisation is:

5156  →  4904  →  4969 

This one can leapfrog them as a 1 pointer (and generally most times you have a 1 pointers teed up they can jump ahead of more involved work.)

**Comment by Miaplacidus** [comment]
@jessmart1213 @zakhap Please take a look at this on the [demo](https://commonwealth-demo.herokuapp.com/1inch/discussions) branch!
