### ISSUE TITLE
[Discussion] Package script removal discussion

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#4970]
## Description
We can discuss the package.json wiki page. Clarification or suggestions can be added to the comments of this issue.
For reference: https://github.com/hicommonwealth/commonwealth/blob/master/wiki/Package-Scripts.md

## Additional context
- PR should only be made after we finalize the changes for this issue.

**Comment by kurtisassad** [comment]
After a reading through the package.json, I have some suggestions. I am not too picky so we can consider them as nits.
- italics: description suggestions
- bold: removal suggestions
- normal: clarifications

_build-all_: Builds app -> Builds front end (more specifically, it runs web pack on the front end code)
_Build-app_: allocating max 4096MB memory to Node -> specifically, runs webpack with that allocated memory to node (This does not persist into the production server).
**Build:css** - We can remove it since it doesn’t even work (we don’t have a script named "build").
**start-CI** - I think it can be removed, we don’t use it for anything currently (double check during standup)
Wait-server - It is in a script because it is a lot of code to put in the CI, and we use it in many places (DRY). Also it needs to be run in the same job as the start server, so it would look messy and complicated without this naming abstraction.
**Create-migration** - It is part of the sequelize docs. I think it should be removed, because we are just remember another alias (and a less common one)
**Migrate-db** - I have the same issue with this. Why alias a more command when it is part of the sexualize docs
Migrate-db-down - same issue
**Mobile** (needs further discussion) - Will be used in 2.0 branch, I am undecided wether we should keep them in preparation for work being merged, or remove it
**Compress-images** - It was a one-off script, should definitely be removed
**Gen-e2e** - Can probably be removed (same reason as sequelize aliases) and documentation added to the e2e test spec describing how to generate e2e tests

**Comment by gdjohnson** [comment]
Thanks so much @kurtisassad!

Some follow-up comments:

Given that `build-app` is just an aggregate of `build-app` and `build-consumer`, are we sure it's necessary?

That makes perfect sense to me re: `wait-server`.

I agree re: the default migration scripts. Should we keep `db-all`, which relies upon `migrate-db`, or re-define it, using the full Sequelize command instead of the `migrate-db` alias?

Very curious your thoughts on how we might better name `migrate-server`. There are a few naming notes I've left where I think we could use better consistency. 

@jnaviask, think you could lend an opinion on `clean-db`? Tim pointed me your way for an opinion; here's the documentation for reference:

```
Definition: `ts-node --project tsconfig.json server/scripts/cleanDb.ts`

Description: This executes series of 'cleaner' functions that delete unnecessary data from the database, particularly notification and subscription data. For more documentation, see databaseCleaner.ts. On prod, the cleaner functions run daily. 

Considerations: Engineers will almost never need to use this locally (unless they have purposefully create a large number of test notifications). This script was authored at the request of Jake Naviasky; we should confer with him as to the long-term value of this script. **Flagged for possible removal.**
```

**Comment by gdjohnson** [comment]
The other big area I think we could stand to clean up pretty drastically is the linting commands. Do we have a "linter guy" or someone whose DRI this would fall under?

**Comment by kurtisassad** [comment]
> Given that build-app...
This is probably best discussed with @timolegros. We might still be using build-all in heroku somewhere

> Should we keep db-all...
In my opinion we should just replace the db-migrate inside the db-all with the `npx sequelize db:migrate`.

> migrate-server...
It can probably be renamed to db-migrate-heroku. But I am not sure if we use it. We might be able to remove it, but Probably best to check with @timolegros 

> linter guy
It is hard to evaluate this section, since I think almost every member has added a lint/formatting related script or two. So figuring out which ones to remove will take a lot of communication between various people.

**Comment by jnaviask** [comment]
I have never once used clean-db and I wouldn't be comfortable running it, I have no recollection of its intended use case.

**Comment by timolegros** [comment]
> I have never once used clean-db and I wouldn't be comfortable running it, I have no recollection of its intended use case.

https://github.com/hicommonwealth/commonwealth/issues/4589

**Comment by timolegros** [comment]
> > Given that build-app...
> 
> This is probably best discussed with @timolegros. We might still be using build-all in heroku somewhere
> 
> > Should we keep db-all...
> 
> In my opinion we should just replace the db-migrate inside the db-all with the `npx sequelize db:migrate`.
> 
> > migrate-server...
> 
> It can probably be renamed to db-migrate-heroku. But I am not sure if we use it. We might be able to remove it, but Probably best to check with @timolegros
> 
> > linter guy
> 
> It is hard to evaluate this section, since I think almost every member has added a lint/formatting related script or two. So figuring out which ones to remove will take a lot of communication between various people.

`build-app` logic should be moved to `build-all`. From what I can tell, `build-app` isn't used anywhere else.

`migrate-server` can and should be removed. @jnaviask to confirm.

Also, I like having aliases (`migrate-db`) for frequently used Sequelize CLI commands. Rather than having to dig through the docs, it's right there. We should remove them if everyone else disagrees but I like them.

**Comment by gdjohnson** [comment]
I'll mention some of this in one-on-one with Forest tomorrow. I'll ask at tomorrow's stand-up about the linting situation, see if we can crowd-source what is actually being used.

**Comment by gdjohnson** [comment]
Noting in the record that the `profile` alias should be removed per #4695.

**Comment by gdjohnson** [comment]
@jnaviask Would be awesome to get confirmation re: `migrate-server` and `clean-db`, per Tim's comments above.

Going to split off the linter aliases into its own ticket—having heard back from engineers, it appears the team uses many different ad hoc linting procedures. We may want to remove one of our linting packages (in addition to scripts/aliases) and come up with a single, team-wide linting procedure.

**Comment by jnaviask** [comment]
@gdjohnson migrate-server can be removed. We'll keep clean-db as it is something we may want available in the future.

**Comment by gdjohnson** [comment]
Closing this down, given the discussion has migrated to #5058.
