### ISSUE TITLE
Tooltip implementation

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#4971]
This card is a holder for details around tooltip implementation.

**Comment by jnaviask** [comment]
@Miaplacidus what is the purpose of this ticket? We already have tooltips implemented, I believe.

**Comment by Miaplacidus** [comment]
@jnaviask 
We have a newly-designed tooltip, but we have not yet replaced existing tooltips with it.

**Comment by jnaviask** [comment]
Can we at least detail that much so it's clear from the title / placeholder description what the eventual goal of the ticket will be? @Miaplacidus
