### ISSUE TITLE
Implement breadcrumbs across the site

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4985]
## User Story 

Community member and admin browsing experience would be improved if there were breadcrumbs on every page of the site. This would provide a secondary means of navigation.  

Implementing breadcrumbs also requires that every page have a page header that communicates to the user what the page is about. This is covered in #4986 

<img width="481" alt="Screen Shot 2023-09-07 at 10 54 30 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/60e93be1-0ed0-48ce-b78b-10b77a410ccc">

## Glossary of terms 

<img width="420" alt="Screen Shot 2023-09-07 at 10 56 06 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/ec0a90bd-6441-4e88-b468-3a4a07bef691">

**Parent page** Is a top-level page, with lower-level (child) pages nested under it.
Example -> Profile page (parent page) and Edit Profile page (child page). 

A **child page** is lower level page nested within a parent page. A child page can only have one parent page, but a parent page can have multiple child pages. 

**Parent Section:** Within our product we currently have 3 three parent sections: Admin Capabilities, Discussion (App), Governance (App). 

**Stand-alone pages** are those that don’t have a parent page or parent section.

## Behavior 

**Placement** 

- Breadcrumbs should sit within a larger container that has a white background. 
- Breadcrumbs are position: fixed. Breadcrumbs sit above content as user scrolls.
- Left padding should be the same as the left padding (or margin) of page content (this varies across the site)
- _Notes on mobile:_ 
   - When breadcrumbs overflow, horizontal scrolling behavior is activated.   
   - On mobile, or screens 600px and under, breadcrumbs are no longer sticky. 

[view breadcrumb scroll behavior on figma](https://www.figma.com/file/FzgJacREDF9Axs7WjFpGVT/Breadcrumbs?type=design&node-id=37-37065&mode=design&t=IiNHMlOQ5HFW3ECE-0)

**Behavior for different pages**

_Stand alone pages_ 

- Show only one breadcrumb in its active state. 
- On:hover triggers Hover state. 
- On:click does nothing, as the user is already on said page. No slashes should be present. Breadcrumb copy mirrors page header copy.

_List of stand-alone pages where this style of breadcrumbs should be implemented_:

- Home (For you, global, On chain)
- Explore
- Notifications
- Notification settings
- Create community

[View stand-alone pages on Figma](https://www.figma.com/file/FzgJacREDF9Axs7WjFpGVT/Breadcrumbs?type=design&node-id=19-12594&mode=design&t=63d2QGmwR3b6ywhU-0)

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/abdc3127-a03d-4c80-a32d-9e7ef1c3b5d7)

_Parent Pages_ 

- Show all relevant breadcrumbs. The last breadcrumb is the page the user is currently on and should be in state: Active. All other breadcrumbs are in state: Inactive.
- On:hover triggers Hover state for Active and Inactive breadcrumbs. 
- On:click for Active breadcrumbs does nothing, as the user is already on said page.
- On:click for Inactive breadcrumbs takes the user to that page. 
- In all current cases, the Breadcrumb copy mirrors page header copy.

List of parent page relationships where this style of breadcrumb should be implemented 

- Profile / Edit Profile 

[View Parent Pages on Figma](https://www.figma.com/file/FzgJacREDF9Axs7WjFpGVT/Breadcrumbs?type=design&node-id=21-13763&mode=design&t=63d2QGmwR3b6ywhU-0)

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/95dae93b-5dd7-4b1c-86df-cace41bf59cb)

_Parent Sections_ 

A parent section behaves slightly differently from a parent page in that its not a selectable page. 

- On:hover triggers a tooltip not a hover state.
- Tooltip copy for Admin capabilities: _This is a section, not a selectable page._
- Tooltip copy for Discussions and Governance: _This is an app, not a selectable page_. 

[View parent section on figma](https://www.figma.com/file/FzgJacREDF9Axs7WjFpGVT/Breadcrumbs?type=design&node-id=21-13766&mode=design&t=63d2QGmwR3b6ywhU-0)

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/4405b9aa-1d1b-4248-838a-d5f15ee65c8c)

## Sitemap 

[View the breadcrumbs site-map on Figma ](https://www.figma.com/file/FzgJacREDF9Axs7WjFpGVT/Breadcrumbs?type=design&node-id=1-40&mode=design&t=LB3Z62Bq3jUyFgXG-0)to understand which pages are parent sections, parent pages and child pages. 
   

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/3867db00-4673-4641-87b7-7419bb4815c9)

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/cb12c52f-c797-421c-8d8a-9f596a41f995)
![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/7a56070d-2a9f-490e-abf3-a23a4176d112)
![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/cb66b522-8ec3-461f-9e65-c9b6ae58cdd0)

**Comment by sachben91** [comment]
@zakhap @jnaviask updated with screenshots of the sitemap

**Comment by CowMuon** [comment]
- [ ] Confirm this scope precedes related work in #4986 @lzach83

**Comment by lzach83** [comment]
Was talking with @masvelio about my most recent iteration on this ticket, I took a route of implementing the Breadcrumbs that is seemingly not going to work. I build a component and put it in the body in the <Sublayout/> the issue is, padding/margin is not unified across the app. So pages where the header is centered like: /createCommunity/starter, design wants the breadcrumbs offset to the left of the centered header.. which is extremely difficult or impossible due the structure of the app/pages without adding a bunch more breakpoints or adding the <Breadcrumbs />to each individual page.

I am gathering all of the pages now.

cc: @jnaviask

**Comment by lzach83** [comment]
pages: 

left-aligned: 
/dashboard - padding 56px
/discussions - padding 40px
/discussion - padding 56px
/members - padding 24px
/overview - padding 56px
/profile - padding 16px
/profile/edit - padding 50px
/notification-settings - padding 176px
/proposals - padding 24px
/discussions/:section - padding 40px

center-aligned:
/createCommunity/starter

--list is in progress--

**Comment by jnaviask** [comment]
@lzach83 is this list complete?

**Comment by lzach83** [comment]
@jnaviask Should be good to go

**Comment by lzach83** [comment]
Review is blocked by #5241 due to sidebar affecting the styling / visibility of the breadcrumbs

**Comment by lzach83** [comment]
Putting this ticket back into Teed up until Eng is back from OOO to discuss next steps.
