### ISSUE TITLE
Add headers (titles) to pages missing headers

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#4986]
## User Story 
The browsing experience for both community admins and members can be improved by adding page headers that describe what the current page ~~the user is on~~ is about. This ~~would~~ will provide better visual hierarchy to the page and also contribute to the implementation of breadcrumbs in #4985 

## Designs 

<img width="477" alt="Screen Shot 2023-09-07 at 10 59 50 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/560f9c3e-d2f7-4943-aab9-75fc77171884">

[View header and breadcrumbs positioning on figma](https://www.figma.com/file/FzgJacREDF9Axs7WjFpGVT/Breadcrumbs?type=design&node-id=17-12564&mode=design&t=63d2QGmwR3b6ywhU-0)

## Titles to add (UX Copy)

Pages that are currently missing Page headers and the copy for the header on the right side of ":" : 

- [For you page](https://commonwealth.im/dashboard/for-you) :  Home 
- [Explore Communities](https://commonwealth.im/communities): Explore Communities
- [Analytics ](https://commonwealth.im/cmn-protocol/analytics)(within admin capabilities): Analytics 
- [Manage Community](https://commonwealth.im/cmn-protocol/manage) (within admin capabilities): Manage Community
- [Notifications](https://commonwealth.im/cmn-protocol/notifications): Notifications 
- [Proposals listing ](https://commonwealth.im/dydx/proposals) : Proposals 
- [Snapshot listing](https://commonwealth.im/dydx/snapshot/dydxgov.eth): Snapshots 
- [Create thread](https://commonwealth.im/cmn-protocol/new/discussion): New Thread 
- Profile pages -> Profile page headers will be the user’s [displayname]’s + profile
  - Example: 
    - jessmart’s profile
    - Bobbie24’s profile

## Acceptance Criteria 

- [ ] Design for page headers implemented according to Figma
- [ ] Copy added for the page headers

**Comment by CowMuon** [comment]
- [ ] Confirm this scope precedes related work in #4985 @lzach83
