### ISSUE TITLE
Fix chain-event WebHooks (client-side)

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4988]
## Describe the bug

Client-side WebHook settings for chain-related events are not functioning properly. Adding Governance events increases the count of WebHook events (displayed on client) disproportionately indicating the client likely still bases WebHooks off of chain-event types. We don't support chain-event type filtering for webhook notifications so this should be updated to a simple on/off toggle.

## To Reproduce

As an admin try to setup governance event webhooks from a chain community such as dydx.

## Expected behavior

- Selecting chain-events for Webhooks on the client should be done in the same way that chain-subscriptions are done. That is, a WebHook for chain-events should be enabled or disabled for the given chain (no choice in specific events). 

## Additional context

In the future, we will want to update this so that communities can select specific event sources for their Webhooks. This will be done when Subscriptions are updated in the same way.

**Comment by jnaviask** [comment]
Consult with @mw2000 who's also working on webhooks.

**Comment by timolegros** [comment]
@jnaviask @lzach83 I actually fixed this as part of https://github.com/hicommonwealth/commonwealth/pull/5207 but forgot to link/close.
