### ISSUE TITLE
Gating | Members Page Updates (w/ Groups)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4989]
## Description

Members Page overhaul to refresh designs and add functionality related to Groups.

### Behaviors + UI, acceptance criteria:
- Members page should be both searchable by profile name (as it currently is) and filterable by group names.
- A user should be able to filter the members by Group Names, using a Single-Select Dropdown component that displays all of the Groups in a community as options.
- Members list should use the new table component, with on-scroll pagination #4682 
- Members listed should show their Groups as tags.
- Add Tab to Groups Page (beneath Members in hierarchy) (page to be implemented in #4990 )

- Default table sort
    - User column is sorted by ascending alphabet.
    - Each role type is grouped and sorted alphabetically. Roles types are displayed in the following order: Admins, Mods, and Members. Admins + Mods are _always_ at the top of the table, sorted alphabetically within each role. 
- Design system adds → Table - user (role tag): 
  <img width="462" alt="Screen Shot 2023-09-20 at 4 41 33 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/e041e1c0-89d6-4566-bd60-cf0a01e0c267">

DevLink: https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1221-31744&mode=dev

## Additional context

<img width="1440" alt="Members - active ascending by default" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/9fbd472e-59b7-4001-ac07-652851822168">

**Comment by mzparacha** [comment]
This depends on https://github.com/hicommonwealth/commonwealth/pull/5116. cc: @jnaviask

**Comment by Miaplacidus** [comment]
@mzparacha @jnaviask 
Responding to design's review now. The PR should be good to go later today. I'll ping you both again when it's ready!

**Comment by rbennettcw** [comment]
> > Members listed should show their Groups as tags.
> 
> per this ^, Can we update the `GET /groups` API to include a members array, @rbennettcw?
> 
> cc: @jnaviask @rbennettcw @CowMuon?

It already does: `http://localhost:8080/api/groups?include_members=true&chain_id=ethereum`

**Comment by mzparacha** [comment]
i see, thanks!
