### ISSUE TITLE
Gating | Create + Edit Group page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4991]
## Description

This form page is used both for creating and editing Groups information.

Requires: Groups API

DevLinks: https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=3-38&mode=design&t=YotqyxzZxIGCRSuK-0

### Behaviors:
- Page has 2 modes, “create” + “edit”
    - “create”: for New Groups, no information filled out.
    - “edit”: requires an existing Group’s information + should pre-populate all fields. All information can be edited, including the adding, removal, and editing of Requirements. Pre-populating may be non-trivial for Requirements.
- Depending on the “Community’s Ecosystem” / “Community Type” / “Base”, different Requirements will be shown as options within the dropdown. For example, the “Cosmos Base Token” Requirement does not need to be shown to “Ethereum” Communities.
- Create Groups Form Page designs as provided in the Figma DevLink should be implemented to specification
- This is an admin-only page.
- There is a delete button for the entire Group. => opens confirmation modal (see devlink)

URLS:
- /scope/members/groups/create
- /scope/members/groups/edit

## Additional context

<img width="613" alt="Screen Shot 2023-09-06 at 9 20 20 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/cfbf524c-bb89-4a7d-8f3f-6c596d89ca55">
<img width="589" alt="Screen Shot 2023-09-06 at 9 20 31 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/388d24f9-c4dd-4776-95ac-cd13e0931305">

**Comment by jnaviask** [comment]
@zakhap @jessmart1213 I suggest adding a big warning box of some sort to say that current group members will be cleared if requirements are edited for a group. This is because changing requirements mean we no longer know if an address which previously passed the set of requirements still passes given the new requirements, and also because we don't check all members upfront -- only when they visit the site. So, changing requirements clears the group.

**Comment by mzparacha** [comment]
Update the point label

**Comment by jnaviask** [comment]
@mzparacha let's make sure we get this page behind a feature flag so we can merge it while we work on the rest of the pages.

**Comment by mzparacha** [comment]
sure, sounds good @jnaviask 

Just to confirm if we follow/use any labels for that?
