### ISSUE TITLE
Update view Thread Page (Gating)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4993]
## Description of Behaviors

- Approach mirrors that of when a user is logged in but has not joined a community where certain actions are disabled and a banner appears informing users why those actions are disabled and offering next steps to enable to those actions.

- **If the User is not In the accepted Groups, the user cannot:**
    - Comment
    - Reply
    - Upvote
- The above actions should be disabled in the UI. 
- **If the User is in the accepted Group(s), the user can do all creation actions:**
  - Comment, Reply + Upvote

- All users, regardless of group status, can: 
    - view the discussion (everyone can, at this point)
    - Share the thread
    - Share a comment or reply
    - Sort comments
    - Hide replies by default
    - Hide spam by default
    - Hide and show replies
    - Show X more replies
  
- **Author Rules**
    - If you're author and topic later gets gated (and you are in group) => nothing changes, you are the author and you can do all the current author actions (edit, create comment, delete, connect proposals, etc). 
      - reiterated: if you're an author in a gated topic, and you still have group access, you can participate in all ways.
    - if you're author and topic later gets gated (and you are NOT in group) => you can only edit your thread, no longer can you participate because you are not in the group => future create actions are disabled.
      - reiterated: if you're an author in a gated topic, and you lose your group access, you can no longer participate through create actions.

## UI Updates: 
~~- [ ] Callout Explaining Groups, showing which Groups are allowed to participate, and links directly to Group page.~~
- [x] All disabled actions have the Disabled Cursor. 
- [x] The disabled Quill Text Editor has a tooltip that says "The Topic is Gated"

DevMode Link: https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1221-31749&mode=dev

<img width="449" alt="Screen Shot 2023-09-25 at 6 33 19 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/9127668c-45dd-4f92-9c9f-2588ef626fed">

**Comment by mzparacha** [comment]
@zakhap just a minor thing

We already show the tooltip text on 
- upvote button
- comment button
- reply button

so following a similar approach, I have added the "This topic is gated" msg on those buttons as well (in https://github.com/hicommonwealth/commonwealth/pull/5465 and its easily revertable if not needed).

**Comment by CowMuon** [comment]
That should be fine Malik, thanks.

**Comment by mzparacha** [comment]
> Callout Explaining Groups, showing which Groups are allowed to participate, and links directly to Group page.

will be done in https://github.com/hicommonwealth/commonwealth/pull/5481, so removing it from action items
