### ISSUE TITLE
Make community routes RESTful

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#4996]
### Description

Currently, the community-related routes are using the pre-RESTful logic. We want them to be updated to the RESTful standard. These routes should be updated

- `/starCommunity`
- TODO: add other remaining community routes

### Engineering Requirements
- All community-related routes should be made RESTFul
- Frontend should be updated accordingly
- Ensure no regressions occur.

### Acceptance Criteria
Same as "Engineering Requirements".

**Comment by mzparacha** [comment]
@jnaviask Coming from https://github.com/hicommonwealth/commonwealth/pull/4994#issuecomment-1710307816, i am not sure about the full list community related routes. 

For now I have only added `/starCommunity` in the ticket description.

**Comment by rbennettcw** [comment]
Closing in favor of #7247
