### ISSUE TITLE
Audit & remove all unreferenced ENV variables

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#5009]
Sub-ticket of #4534, requested by @jnaviask. 

Right now, many of our `.env` variables are not used. These should be identified and removed.

**Comment by gdjohnson** [comment]
@jnaviask To get started on this, I'll need a comprehensive .env file. Possible to get one (or be pointed to someone who can get me one)? Want to make sure I'm not just working off an engineer's partial file, but the "single source of truth" (if we have one—if not, we probably should?)

**Comment by CowMuon** [comment]
@gdjohnson Sending you env files (plural) presently. By way of saying we should have both an .env file (for non-secret configuration) and an .auth file (for secrets & keys). I sent you a zip of both, however I believe most engineers are still using legacy single file combining both.

**Comment by gdjohnson** [comment]
Documentation is taking place in #5227
