### ISSUE TITLE
[Gating API]  Write migrations + models for Groups and Memberships tables

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#5019]
Parent ticket: #4953

## DB models

Group:
  - id: `number`
  - chain_id: `string` // reference to community -- indexed
  - metadata: `json` (MetadataJSON)
  - requirements: `json` (RequirementsJSON) // must be validated

Membership:
  - group_id: `number`;  // fk: Groups
  - address_id: `number` // fk: Addresses (easier property querying than string)
  - last_checked: `Date`

## Non-DB models

MetadataJSON:
  - name: `string`
  - description: `string`
  - required_requirements?: `number` // undefined = all
  - membership_ttl?: `number` // seconds for Membership to be stale -- what is default?

RequirementsJSON:
…

**Comment by jnaviask** [comment]
@rbennettcw why would the result depend on ordering of requirements? In theory it can be any of N requirements, ordering notwithstanding.
