### ISSUE TITLE
Incorrect on-chain identity loaded

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#502]
- Go to http://localhost:8080/edgeware/proposals
- Wait for chain to load
- Click on "Discussions"
- The incorrect display names may appear. For example, here BlockX Labs appears instead of Thom's profile:

![image](https://user-images.githubusercontent.com/1273926/88256373-088bbb00-cc70-11ea-9307-34255bb777e3.png)

![image](https://user-images.githubusercontent.com/1273926/88256373-088bbb00-cc70-11ea-9307-34255bb777e3.png)

**Comment by jnaviask** [comment]
There is no bug here: the address listed as author on that thread is registered to BlockX Labs on edgeware mainnet, despite having a profile in our database that says "Thom Ivy".
