### ISSUE TITLE
CE 2.0 migration and Sequelize models

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5023]
## Description

Create the migration per the changes described in [the spec][1]. This is the first task of #4863.

## Engineering Requirements

- Migration created according to spec
- Sequelize models for the new tables created in the migration

## Additional context

[1]: https://www.notion.so/buildcommon/Chain-Events-2-0-5d6d913720944ffbb1658a94c85a2409?pvs=4#338f7376e5444b9d883ca84850fb6adc

**Comment by timolegros** [comment]
Blocked by #5066

**Comment by timolegros** [comment]
Keeping in draft until PR #5067 (issue #5066) is merged.

**Comment by jnaviask** [comment]
@timolegros any reason this ticket is still blocked?
