### ISSUE TITLE
[Template Link] - Merge Experimental Work to Master

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#5040]
Creating this issue to track the work(will require slight modifications/conflict resolution, enough to make it a task) required to merge Template Links to master. Experimental PR and work: #4537 

Beyond creating a clean branch with the cherry-picked changes this will include the following:
- Feature flag
- Optimizations(experimental -> production-grade code) 
- Covering any behavior that wasnt included(ie enable/disable on valid threads)

**Comment by dillchen** [comment]
Does this supersede #3910
