### ISSUE TITLE
Connected Address not showing in landing/for you page

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5047]
### User Story

If I’m not on a community page, it appears as if I have no addresses connected to my profile. There is no affordance to the user (either in drop-down or in profile) about what addresses I have connected unless I'm on a community page 

[Loom](https://www.loom.com/share/bf2fbd65e3c543eeb7cedab999af99a7?sid=b587572f-e4f1-4ee8-acc0-79b22124cb3d)

### Solution

We should fully hide the “Connect an address” button and the empty “addresses” title in the Profile dropdown when not in a community page. Users who are on the landing page or For you page will not see the below screenshot section of the profile dropdown 

### Screenshot

![Image](https://user-images.githubusercontent.com/38763242/267162918-241e7aaf-87a8-43d3-a2aa-7fed2321015c.png)

**Comment by masvelio** [comment]
One pointer, should be taken at the end, when all other more important issues are fixed

**Comment by masvelio** [comment]
fixed in this commit https://github.com/hicommonwealth/commonwealth/pull/3426/commits/a80b47d68c3248b89f454738d6f4014ed70795b4
