### ISSUE TITLE
Magic Login not allowing user to sign into a session

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5049]
### Environment 
- Desktop on Chrome 

### Steps to reproduce 
- Login https://commonwealth-frack.herokuapp.com/ with one of the magic link options (email, discord, social)
- Go to a community page and join the community
- Check left side bar to see the status of the address that is assigned to the user during magic login (joined/not joined)
- Check the profile drop down to see the status of the address that is assigned to the user during magic login

[Loom](https://www.loom.com/share/c4fe034511494f9e9ef5f8c8dbfba364)

### Expected behavior 
Shows that you have joined the community and the address that you were assigned during magic link is active 

### Actual behavior 
The left side bar shows that I have joined the community, the profile drop down shows that I have been signed out. There is no way to sign back in using that address since it was randomly assigned to me at login 

### Priority for launch 
blocking the launch since this breaks the sessions keys flow for magic login

**Comment by masvelio** [comment]
Tried couple times but was not able to reproduce. Every time I log in with google, my session key is active.

https://github.com/hicommonwealth/commonwealth/assets/14819225/a01caeba-f9d2-48da-8d27-c013caae449c

**Comment by masvelio** [comment]
Need some more info to figure out why this might be broken @sachben91 we can take a look on that together

**Comment by kurtisassad** [comment]
+1 unable to reproduce, tried on dydx

**Comment by sachben91** [comment]
unable to reproduce consistently on the product side. Tried new and old magic logins

**Comment by raykyri** [comment]
Doesn't replicate for me.
