### ISSUE TITLE
‘Send feedback’ icon CTA and ‘Help doc’ icon CTA should not be separated

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5051]
### Design Guidelines 

Currently the 'send feedback' icon and the 'help' icon are separated in the top nav as shown in the below screenshot. This leads to the icons taking up too much space in the top nav. The send feedback icon seems unnecessary and should be removed 

![Image](https://user-images.githubusercontent.com/38763242/267192406-124a26c7-94be-4787-82d1-94e6b9c76eaa.png)

The below screenshot shows the design the nav bar should be: 

![Image](https://user-images.githubusercontent.com/38763242/267195355-6c429647-582d-4fb9-81f7-101ad49ebce2.png)

[Figma link with more details about the design ](https://www.figma.com/file/mJMPTzEnpEFIaR2wBWkElq/Session-Keys-and-Login?type=design&node-id=667-60803&mode=design&t=rvcCg8mVab2jKZE6-0)

### Priority 
not a blocking change but ideally finished before the launch

**Comment by sachben91** [comment]
Seems like this was something that did not go through product or design (jess). Perhaps Meesh added it in, on further review, current design team does not find this necessary

**Comment by masvelio** [comment]
fixed in this commit https://github.com/hicommonwealth/commonwealth/pull/3426/commits/82fe7a52decae428bd0bd8fa4a684ddd0c7315f4

**Comment by jessmart1213** [comment]
Amazing! Just checked and it looks GREAT! Don't see a PR so giving Design sign-off here.
