### ISSUE TITLE
Bug: From Dashboard, logged in, clicking "View Profile" goes to /profile/id/undefined

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5053]
## Describe the bug

Signed in, on the dashboard page, clicking "View Profile" in the Profile dropdown goes to `/profile/id/undefined`. 

## To Reproduce

- Sign in
- Go to Dashboard
- Open Profile Dropdown + Click "View Profile"
- Bam, empty error page

## Expected behavior

- Goes to user's profile page

**Comment by alexyoung23j** [comment]
Unable to replicate this on prod or locally. @zakhap Are you still able to reproduce?

**Comment by alexyoung23j** [comment]
Closing for now. Unable to replicate after repeated attempts, likely resolved in another PR.
