### ISSUE TITLE
Session key sign in pop up for magic should be uniform

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5060]
### Environment 
- Chrome on Desktop

### Steps to replicate 
- Login with magic and join a community 
- Check that the address is connected. 
- Clear local storage and see that the magic link address signed out 
- Try to submit a comment and notice the pop up 
- Try to sign in again from the profile drop down, notice the pop up

[Loom](https://www.loom.com/share/ad9e0b8e2ef64f91b97ffccd3f44259a)

### Actual behavior 
- The pop up when you submit the comment is different from the pop up when you sign in again from drop down using the magic link address

### Expected behavior 
- The pop-up when you sign in from the drop-down using the magic link should be the same as the one when you try to submit a comment. Only the magic link option that the user used for that address should be presented to the user to sign in again.

**Comment by masvelio** [comment]
fixed with this commit https://github.com/hicommonwealth/commonwealth/pull/3426/commits/fbfecc668cf2084e1ab2ddfa96d1b122226c0fdd
