### ISSUE TITLE
Dashboard: Previous search stays in search bar

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5064]
## Describe the bug

Previous search input always stay in search bar
## To Reproduce

1. Go to https://commonwealth.im/
2. Sign in with wallet or Email
3. In search bar type e.g ether
4.  From dropdown select some search result 
5.  In Search bar remove previous search and type new search data

## Expected behavior

When user removes previous search and type new search topic we should remove previous data
## Additional context

Note: This issue is visible only if we select topic from search results in drop down menu
Reproduction video:
https://app.screencast.com/yUt9Ec3A50FYQ

**Comment by CowMuon** [comment]
Good issue write up Ilija, and thanks for including labels. 

We may need a loom here (or a replay) to show what's happening.  (@sachben91?)

**Comment by cowballzach** [comment]
Recreation Loom: https://www.loom.com/share/Commonwealth-12-September-2023-54a5a2faf3d94769b03b68c3ff90ee6b?sid=8052855f-fc02-4504-bdf3-23da218a564f

**Comment by CowMuon** [comment]
This is growth's lowest priority bug. Backlogging until TOW on 11/06. @mzparacha

**Comment by mzparacha** [comment]
Still not reproducible for me.

cc @jnaviask @ilijabojanovic

**Comment by CowMuon** [comment]
This is a low priority issue, however if we wish to resolve we will need a loom showing the bug is reproducible. @RhysCommonwealth

**Comment by CowMuon** [comment]
@RhysCommonwealth Seems like we may need a loom here to show reproducibility?

**Comment by RhysCommonwealth** [comment]
Looks like we can't reproduce either. This seems to have been fixed. Another search issue has come up likely replacing this one. I'll record a loom and ticket separately
