### ISSUE TITLE
`ContractAbis` inconsistent encoding and hashing

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5066]
## Describe the bug

- The unique constraint on the `ContractAbis.abi` column is problematic for ABIs that are larger than 2704 bytes since 2704 bytes is the largest possible B-tree index entry. The solution to this is to hash the ABI and create a unique index on the hash but that raises another issue as described in the next bullet.
- We have an inconsistent encoding of ABIs in the `ContractAbis.abi` column. Some ABIs are stored as raw objects and others are stored as stringified objects. This causes situations like [line 516][1] of `contract.ts` where we have to do conditional parsing based on what the type of `ContractAbi.abi` is. This also causes issues for hashing the ABI because the hash of a raw object is not the same as the hash of that same object stringified.

## To Reproduce

View the `ContractsAbis` table.

## Expected behavior

- All existing ABIs (and future) ABIs should be stored as objects rather than stringified objects.
- A new `abi_hash` column should be created and it should contain the sha256 hash of the abi. The hash should be generated using [`node-object-hash`][2] and it should only hash the sorted ABI since a user-provided ABI is not guaranteed to have the same ordering as another user's ABI.
- Remove the unique constraint/index on the `abi` column and recreate it on the `abi_hash` column.
- Existing queries that lookup an existing ABI should use the new `abi_hash` column rather than matching on the entire abi.

## Additional context

[1]: https://github.com/hicommonwealth/commonwealth/blob/master/packages/commonwealth/client/scripts/controllers/server/contracts.ts#L516
[2]: https://www.npmjs.com/package/node-object-hash

**Comment by CowMuon** [comment]
Given this is a bug, cc @ilijabojanovic for visibility
