### ISSUE TITLE
Create "Reveal" page within Magic Link

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5072]
## Description

Doc: https://help.magic.link/knowledge/how-can-i-allow-users-to-view-and-export-their-private-key

A community admin recently airdropped tokens to all the addresses in their community on Common. Unfortunately, some of their users are Magic users and they need access to their Magic private key to the tokens to an address that they own. 

Based on my own research (and Jake sent me that link above), this seems to be the best/only real solution here where we don't take their keys or authorize transactions on their behalf; the user will take control over their account by gaining access to their private keys via the magic link reveal page.

## Acceptance Criteria

- A magic link reveal page that we can send to impacted users so they can claim their magic-generated private keys.

**Comment by ianrowan** [comment]
Given that " This page is only made for your app upon request*." first step here will be to get in touch with magic to request a reveal page, which will subsequently be deployed on their end the following friday. 

@jnaviask Who has access to the magic dashboard and can assist in requesting this(or can I get access somehow)?

In the meantime from a product design side, we can decide on the UX/components to support this 

CC @zakhap

**Comment by jnaviask** [comment]
@dillchen should be able to add you to the magic dashboard

**Comment by dillchen** [comment]
Pretty sure I gave access like a week or so ago btw

**Comment by jnaviask** [comment]
@ianrowan are you still blocked here?

**Comment by dillchen** [comment]
made this unblocked now

**Comment by ianrowan** [comment]
Our reveal pages via magic are now live - next question is where/how we should deliver this to affected users. 

Are we intending for this to be a docs/whiteglove based feature or serve the link in-app with a description of how to use the key? 

CC: @zakhap

**Comment by jnaviask** [comment]
cc @zakhap @ianrowan not sure what next steps are here but would like to resolve, as we have an oustanding growth request

**Comment by zakhap** [comment]
> Our reveal pages via magic are now live - next question is where/how we should deliver this to affected users.
> 
> Are we intending for this to be a docs/whiteglove based feature or serve the link in-app with a description of how to use the key?
> 
> https://reveal.magic.link/commonwealth https://reveal.magic.link/cosmos/commonwealth
> 
> CC: @zakhap

@ianrowan Let me sync with Growth Today about this.

**Comment by jnaviask** [comment]
Closing as completed -- please follow up with explicit integration details.
