### ISSUE TITLE
Investigate scope of impact on power users who have multiple accounts.

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5079]
See #5078.

There exists some number of addresses that share a signer but different accounts on Common. We need to understand the impact of this (they are all power users) prior to signing off on a solution for merging Accounts (automatic or UI guided).

Would like to see: 
- Number of _Users_ Potentially Impacted
- Number of _Accounts_ that share addresses with one public key

**Comment by CowMuon** [comment]
> See https://github.com/hicommonwealth/commonwealth/issues/5079.

This is 5079. @zakhap

**Comment by mhagel** [comment]
```
SELECT user_id, COUNT(DISTINCT address) AS num_unique_addresses
FROM "Addresses"
WHERE address NOT LIKE '0x%'
GROUP BY user_id
HAVING COUNT(DISTINCT address) > 1
ORDER BY user_id;
```

This returns 1289 Users for me.

**Comment by mhagel** [comment]
```
SELECT user_id, COUNT(DISTINCT address) AS num_unique_addresses, array_agg(DISTINCT address) AS unique_addresses
FROM "Addresses"
WHERE wallet_id = 'keplr'
GROUP BY user_id
HAVING COUNT(DISTINCT address) > 1
ORDER BY user_id;
```
This returns 562 Users. 
It assumes that we are only checking keplr addresses, and not Magic-derived Cosmos addresses.

**Comment by mhagel** [comment]
To find the "Number of Accounts that share addresses with one public key," we would have to come up with some sort of script that runs addresses through the Cosmos address-derivation algorithm for a given chain (ie convert osmo123... to a juno address), see if it matches anything in the DB.

Kinda complicated, but possible. But maybe this is unnecesary since we are getting an idea of the scope already.

If we truly need to figure out the shared Signer, though, this extra work _may_ be necessary.

Please see my previous comments @zakhap for any idea of scope.

**Comment by mhagel** [comment]
Reading through the ticket again, I may have been going down the wrong path so far. 

We want to identify all the Addresses that share a pubkey, but not a `user_id`. So that we can merge them to the same `user_id`.

Thinking out loud, that means we need to query for all (keplr) cosmos addresses, and figure out how many can be derived into a different chain address that:
1. exists in the DB 
2. has a different user_id

**Comment by mhagel** [comment]
Findings:

- Number of Users Potentially Impacted: [**2767**](https://github.com/hicommonwealth/commonwealth/pull/5162/files#diff-5f9e6a7cd0498f4d1208e0d5a57522ec4571700ff42511b32d889f47e5cbbdfaR153-R155)
- Number of Accounts that share addresses with one public key: **[3282](https://github.com/hicommonwealth/commonwealth/pull/5162/files#diff-5f9e6a7cd0498f4d1208e0d5a57522ec4571700ff42511b32d889f47e5cbbdfaR170-R174)**

See links to see how I got to these numbers from latest prod DB dump.

I can relay some data to you if it helps (addresses grouped by signer, showing separate `user_id`s)


@jnaviask @zakhap @CowMuon

**Comment by mhagel** [comment]
Moving to "has PR" for investigation review, although I will leave it in draft, as it is just for reference.

**Comment by mhagel** [comment]
- Number of Signers with multiple User IDs: **[1221](https://github.com/hicommonwealth/commonwealth/pull/5162/files#diff-5f9e6a7cd0498f4d1208e0d5a57522ec4571700ff42511b32d889f47e5cbbdfaR128-R138)**

I believe this gives a good sense of "individuals who have created accounts for different chain addresses"

**Comment by mhagel** [comment]
The common identifier is a hex, which can be decoded from any bech32 address:

```
            const dataA = fromBech32('cosmos1xyz123abc').data;
            const dataB = fromBech32('kyve1xyz123abc').data;

            const aHex = toHex(dataA); // '9d4e856e572e442f0a4b2763e72d08a0e99d8ded' 
            const bHex = toHex(dataB); // '9d4e856e572e442f0a4b2763e72d08a0e99d8ded'

            dataA === dataB
```

We can use this to identify exisiting signer accounts. 

It probably means we want to add a `hex` or `cosmos_signer_id` column to the Users table? And use that to connect new cosmos addresses to the appropriate user_id.

**Comment by jnaviask** [comment]
cc @zakhap to review these results

**Comment by jnaviask** [comment]
Surfacing from call: ask to close this spike is to determine number of active _human beings_ affected, with "active" defined as 3mo or 6mo (should get both numbers).

**Comment by mhagel** [comment]
After refining my query I am getting some smaller numbers:

hexAddresses with a profile_id: 36325
signers: 31729
signersWithMultipleProfiles: **473**


**signersLast12Months: 298
signersLast6Months: 81
signersLast3Months: 10**

So, in terms of active users, we are looking at 81 in last 6 months, 10 in last 3 months.

473 total would be impacted.

@jnaviask @zakhap

**Comment by CowMuon** [comment]
Great to see these numbers, basically confirming what we said earlier today that distribution would be similar as eth addresses we needed to migrate earlier this year. marking this as done.
