### ISSUE TITLE
Discussions page flashes when chain loads

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#510]
The chain seems to reload unnecessarily in a few places:

- when you go from proposal page to a view discussion page, the chain is reloaded (reported by Jake)
- when you're on a discussion page the chain loads, and this seems to cause a flash (reported by Raymond, check with him for more details)

**Comment by raykyri** [comment]
It seems like there aren't consistent replication steps for this right now, and that it's a little lower priority than the other chain issues. (I tried to replicate and could only get flashing to happen once, even after calling `localStorage.clear()`)

When we figure out consistent replication steps, we should post them here

**Comment by jnaviask** [comment]
Unable to reproduce...

> when the chain loads, the profile store is cleared

When does this happen? The only "clearing" I see of the profile store is when `app` gets constructed.

**Comment by jnaviask** [comment]
> when you go from proposal page to a view discussion page, the chain is reloaded (reported by Jake)

Can't reproduce this, unfortunately -- maybe fixed.

> when you're on a discussion page the chain loads, and this seems to cause a flash (reported by Raymond, check with him for more details)

Yes the flash is related to identity/profile loading, but I wonder if using the identities stored in the db rather than fetching them from chain will resolve this?
