### ISSUE TITLE
 Select active address by default

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5110]
### User Story

As a community member, when I sign into my community, I should be signed in with the address that is currently active, that I signed in with. Currently if I have two addressed connected to a community and my session signed out of the first address, when I log back into the community with the second address it still shows the first address as selected and signed out. It should show my current active address as selected and signed in instead.

Rule; the address selected by default should have a session key. Among the ones that have session keys, the most recently active one should be selected. 

### Steps to replicate
- sign into a community where you have two active addresses signed in and active 
- check the address that is currently selected. clear the local storage and sign out 
- sign back in with the other address, the one that was not selected
- In the community, check which address is selected 

### Actual behavior 
- The address that is signed out of and was selected previous to the session being signed out is the one that is selected 

### Expected behavior
- [x] In the "Connected Address" Sidebar Module, the address shown should _always_ be the address selected in the Address Selection Dropdown (Profile Dropdown in the upper right hand corner). 
  - [x] Inversely, when I select an address from the Profile/Address Selection Dropdown, the address displayed in the "connected Address" Sidebar Module updates to reflect the choice made.  
- [x] The active address should always default to the address with an active session key, and if not available, default to the address last used within the community.

### Screenshot 

![Image](https://user-images.githubusercontent.com/38763242/269036430-47b1a191-6da0-4f90-9d05-57afe066b909.png)

**Comment by CowMuon** [comment]
What's the status on this @sachben91 ? 
I see it was opened on 9/19, tho I don't think it's been brought to any subsequent refinements?

**Comment by CowMuon** [comment]
Would like to get @Rotorsoft's feedback here, as this is the main area of the site that still retains some legacy MC Escher-isms (ie the underlying model bears some resemblance to Relativity, one of his most famous illustrations.) 

After Roger's review, thinking this is for @mzparacha to execute.

**Comment by Rotorsoft** [comment]
Seems like we have a simple rule to follow:
1. Sort all connected addresses by ValidSessionKey, LastUsedTime
2. Select the top 1.
3. In the case of selecting an address with an invalid session key, the user will be able to view the community but will be required to sign in to perform actions requiring auth. @zakhap @jnaviask - please confirm

If we have addresses with valid session keys, they will be clustered on top of this query, otherwise the last used address without a valid session key will be selected. (last rule on expected behavior)

TODO: Confirm how we store addresses (locally and in server), including last used time. @rbennettcw @masvelio

**Comment by masvelio** [comment]
I am adding this PR as a context as well because there was a requirement some time ago that active address should be persisted across the page reload https://github.com/hicommonwealth/commonwealth/pull/4907

@Rotorsoft On frontend we have user controller that holds `activeAccounts` and `activeAccount` and we retrieve it across the codebase via `app.user.activeAccounts`

**Comment by Rotorsoft** [comment]
So, to clarify the issue of address persistence:
1. Do we store a list of community addresses, including last used time? Client and/or server?
2. Do we have an API to access/sort that list? Client->` app.user.activeAccounts` (see above)
3. What is the order of precedence to select the active address? client first, server second?
@kurtisassad also tagging you for input

**Comment by kurtisassad** [comment]
I think we already persist the last_active to the database. The goal should be to also pass this into the client (since it is not currently on app.user.activeAccounts objects).

> What is the order of precedence to select the active address
I am a little unsure what you mean by this. In my mind this should be a client side only fix. Ideally when we setAccount we should just make sure that we find the latest last_active in the list, and use that one, regardless of whatever order the database returns.

**Comment by Rotorsoft** [comment]
> I think we already persist the last_active to the database. The goal should be to also pass this into the client (since it is not currently on app.user.activeAccounts objects).
> 
> > What is the order of precedence to select the active address
> 
> I am a little unsure what you mean by this. In my mind this should be a client side only fix (maybe a bit of server side to make sure the client gets "Addresses.last_active"). Ideally when we setAccount client side, we should just make sure that we find the latest last_active in the list for the community, and use that one, regardless of whatever order the API returns.

That's what we are trying to define here, **what is the default address of a community** given the use history and active session keys. 

Just to reiterate what we have been discussing above:

1. On the client side, we must have a list of addresses (by community?) with active keys, and we can pick the last used
2. In case we don't find any, we can pick last used on client side (user will have to sign in for operations requiring auth)
3. Last resort (not finding anything on the client side - new browser, clean cache, etc), we can query the server for last active

Questions:
1. Is this the correct functionality?
2. Do we have APIs both on client and server sides to support it?

**Comment by jnaviask** [comment]
Where are we at with this ticket? cc @Rotorsoft @kurtisassad @masvelio

**Comment by Rotorsoft** [comment]
@jnaviask who can answer the questions above?

**Comment by masvelio** [comment]
- `app.user.activeAccounts` => this is a list of all client side addresses in currently visited community. 
- [this function](https://github.com/hicommonwealth/commonwealth/blob/b887dc9ce11cd2c4dbde4b4d896563d7bee3a30d/packages/commonwealth/client/scripts/controllers/app/login.ts#L34) - sets activeAccount when the community is being loaded or when user change the active account. it uses currently `is_user_default` to determine which account should be set as default on load.
- we are missing piece of logic that would check if the default address has valid session key so this has to be added. We do not have the list of addresses that have valid/invalid session keys. Check is done via api that is exposed from `ISessionController` ([see here](https://github.com/hicommonwealth/commonwealth/blob/1bd8d3f56d7226b08726edbb1795be8df401b017/packages/commonwealth/client/scripts/views/components/Header/UserDropdown/useCheckAuthenticatedAddresses.ts#L29)).

**Comment by Rotorsoft** [comment]
So @masvelio, there is this section inside `updateActiveAddresses` in `login.ts`
```
 if (existingAddress) {
      const account = app.user.activeAccounts.find((a) => {
        return (
          a.community.id === existingAddress.community.id &&
          a.address === existingAddress.address
        );
      });
      if (account) await setActiveAccount(account, shouldRedraw);
    }
```
- Is this the place to insert the missing piece of logic to check for valid session key (before setting active)?
- Is this the utility to check for valid session?
```
const isAuth = await app.sessions
        .getSessionController(chainBase)
        .hasAuthenticatedSession(canvasChainId, activeAccount.address);
```
@mzparacha is this enough for implementation?
