### ISSUE TITLE
Flatten the comments hierarchy

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#513]
- Migration
- Change in logic of creating comments
- Do any comments reference a parent? How will this change?

**Comment by raykyri** [comment]
Discussed with @gdjohnson, we can patch over the issues we have for now, and revisit whether we really want to pull all of this out later (or if there's a way to refactor/cleanup that lets us keep threading)

**Comment by gdjohnson** [comment]
I can pick this up if desired; I don't have a ton on my plate this week.
