### ISSUE TITLE
DS: R&R Tabs

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5141]
## Description

Blocked by New Tabs Implementation: #5140 

For each case of Tabs used across the UI, replace with the new tabs component keeping the expected labels the same. There is no need to include the "New" StatusTag on any Tab that previously existed. 

Non-exhaustive list of existing tabs:
- Admin Panel
- For You / Dashboard
- Mobile/Tablet view of View Thread Page / View Proposal Page

## Acceptance Criteria

- All old tabs are replaced with new tabs
- All tabs are functional and properly trigger the tabbed views accordingly.
  - To Test: every instance of updated Tabs. 
- A list of all updated instances in the PR for QA

**Comment by masvelio** [comment]
@Miaplacidus @zakhap unblocked!
