### ISSUE TITLE
Switch display of avatars in NotificationRow from Facebook-style (1 avatar/notification) to Twitter-style (row of many avatars/notification)

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#515]
Because "dillon and 3 others" should show the 3 others' avatars.

If there is >X avatars (e.g. >10) the remaining ones should be collapsed into a gray avatar that shows the number of additional avatars that were collapsed. We should also apply this limit to the list of commenters' avatars on the DiscussionRow

**Comment by raykyri** [comment]
Maybe we want to create a component that represents a stack of Users, that automatically limits the number of Users shown?

**Comment by gdjohnson** [comment]
@raykyri Thoughts on moving the avatars from the left-side to the top of notifications, following Twitter? Open to counter-suggestions, just trying to figure out how to best lay everything out:
![image](https://user-images.githubusercontent.com/22281010/88827421-f0e49300-d197-11ea-9185-f44306c95db8.png)
![image](https://user-images.githubusercontent.com/22281010/88827447-f6da7400-d197-11ea-8f09-50970a33366a.png)

**Comment by raykyri** [comment]
yep, they should move to the top!
