### ISSUE TITLE
Update Create Community Page to Use Groups Form UI

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5151]
## Description

The Create Community Page has not been updated, almost ever. The Create Groups Page UI and Form State is exactly what we need for creating communities 1) setting a description for the group / community 2) setting the base requirement 3) and gating / adding additional context / apps / contracts

## Engineering Requirements
- In the UI, we need to add `Verified Addresses` as a "Type of Requirement" to join the community.

## Acceptance Criteria
- Implementation follow same form and other validation noted for [creating groups](https://www.figma.com/file/kZm7Jdbgsb81eTBTetxbRI/2.0-Designs?type=design&node-id=380-7429&mode=design&t=WNGxYXMidp5e6Edr-4)

## Additional context
- Useful to coincide with #4464 which should be hidden behind feature flag

**Comment by zakhap** [comment]
Can we close this ticket and remove it from 2.0 work as it was incorporated in the Q4 planning?
