### ISSUE TITLE
Add Inline Scroll for Mobile / Smaller Screensizes on Table

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5156]
## Description

The table component created in Issue #4682 and PR #5116 doesn't work well here on non mobile screens.

See the loom for the current behavior. https://www.loom.com/share/a9f6f65304f2443e9beded6f03fda60f

Semi-responsive for the mobile not able to scroll all the way left (I.e community name) 

## Engineering Requirements
- Implement Inner Scroll for any width that’s smaller than the table width.

## Acceptance Criteria
- As a user, I'm able to see the full contents of a table, viewable by scrolling (horizontally and vertically), if the table size is too large

## Additional context
- (Later for design — with no deadline): Specify the behavior on mobile (it’s below priority for any Q4 item)
- Mobile makes up 40% of our users

**Comment by Miaplacidus** [comment]
@jnaviask Pinging for reference!

**Comment by ForestMars** [comment]
What should be merged in @Miaplacidus? This is an issue, and there is no linked PR. (?)
