### ISSUE TITLE
Cosmos node liveness solution

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5157]
## Description

Use proxy endpoints provided by cosmos.directory as first choice for RPC or LCD.
Fallback to community-chosen endpoints if proxy fails

## Engineering Requirements

`{rpc | rest}.cosmos.directory/{cosmos_chain_id}`

One possible solution:
- try/catch proxy from the front end.
- If proxy fails, use `url` for v1beta1 chains, `alt_wallet_url` for v1 chains

## Acceptance Criteria

For any Cosmos chain community, if either the proxy or the ChainNode `url` is "available," proposals load, and I can make a TX.

## Additional context

See if any whitelisting headers are needed with proxy maintainers (ecostake)

**Comment by jnaviask** [comment]
Related to #4153

**Comment by mhagel** [comment]
https://docs.leapwallet.io/cosmos/cosmos-nodes/coming-soon-monitoring-blockchain-node-performance

**Comment by mhagel** [comment]
LOE depends on findings from #4153

**Comment by mhagel** [comment]
Would be good to use the batch client in this process too.

**Comment by mhagel** [comment]
Q: Should we fallback to the node in our DB, or fallback to proxy, or neither?

A: Assuming we move to a strategy where a new chain doesn't _need_ to provide a node, we can give the DB node higher priority. Because that means the trusted node has some advantage to it. Therefore, Use our node first, fallback to proxy.
