### ISSUE TITLE
On-chain notifications display as "Loading..." when a chain isn't loaded

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#517]

**Comment by raykyri** [comment]
it seems like we have quite a few open bugs on Commonwealth with the chain connection issues so it might be worth pacing out an approach to address them over the next couple of weeks.

**Comment by jnaviask** [comment]
Yeah -- I'm a little worried about our initialization flow. I would like there to be clearer "landmarks" where we mark certain views as ready to go. But I will investigate this directly before making an effort to redesign that.

**Comment by jnaviask** [comment]
@raykyri I can't reproduce this.

**Comment by raykyri** [comment]
Okay, this seems to be resolved now!
