### ISSUE TITLE
User dashboard failing to render

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5176]
## Describe the bug

The `QuillRenderer` component fails to render notification with id = 6094405 with the `QuillFormattedText` component. This is because [line 73][1] of the `QuillFormattedText` component expects either an array or undefined `element` variable whereas when rendering the above notification the `element` variable is the following string: `"what do you think for dydx future?"`

The quill render component is invoked for the user dashboard on [line 106][2] of the `user_dashboard_row_top.tsx` component. It is invoked by passing `comment_text` which is found in the `notification_data` property of notification with id = 6094405:
```
"%7B%22ops%22%3A%5B%7B%22insert%22%3A%22what%20do%20you%20think%20for%20dydx%20future%3F%22%7D%2C%7B%22attributes%22%3A%7B%22header%22%3A1%7D%2C%22insert%22%3A%22%5Cn%22%7D%5D%2C%22___isMarkdown%22%3Afalse%7D"
```

## To Reproduce

**Prerequisite: full database dump**
1. Run the following command from `packages/commonwealth/`:
```
pg_dump $(heroku config:get CW_READ_DB -a commonwealth-beta) --verbose --no-privileges --no-owner -f latest.dump
```
2. Run the `yarn db-all`
3. Run the following queries (this will remove all rows from the user dashboard except the row that causes the error):
```
DELETE FROM "NotificationsRead";
DELETE FROM "Notifications" WHERE id != 6094405;
```
4. Join the `dydx` community.
5. View the `For You` page.

## Expected behavior

Every row should render properly and rows that fail to render should throw silently and not cause the entire page to fail to render.

## Additional context

[1]: https://github.com/hicommonwealth/commonwealth/commit/dc60e946e0e4e5b371012f4ac6d6d3a3ad46a8a7#diff-8d49224870edeb0102d8d0fc735fdd1a1181b76144c01f892eafc6ea020920f0R73
[2]: https://github.com/hicommonwealth/commonwealth/blob/master/packages/commonwealth/client/scripts/views/pages/user_dashboard/user_dashboard_row_top.tsx#L106

**Comment by jnaviask** [comment]
Related to #5197

**Comment by jnaviask** [comment]
Can't reproduce.
