### ISSUE TITLE
Wallet login is not available on some threads. 

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5189]
## Describe the bug

When public user (not authenticated) open some discussion or search over dashboard, is not possible to do login with wallet. 

## To Reproduce

1. Go to https://qa.commonwealth.im/dashboard/global
2. In search type `Some Chain`
3. Select 1st result from drop down menu
4. On thread page click on Login

## Expected behavior

User should be able to log in on application with wallet.

## Additional context

Please see reproduction video:
https://app.screencast.com/u8fUPC5Jy5Ivc

**Comment by jnaviask** [comment]
Wallets displayed as available options depend on the support of the community the user is visiting, as well as which wallets are detected as installed in the browser. The community here, terra, only supports "terra station" wallet, which you may not have installed.
