### ISSUE TITLE
Update hardcoded URL checks on server

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5198]
## Description

There are some instances where we do hardcoded checks against [commonwealth.im](http://commonwealth.im/) url (bad practice but they're in there) which could cause failures when running on alternative domain names, such as common.xyz.

## Engineering Requirements

Commonwealth application should be agnostic to the production domain name used.

We may want to configure the canonical production domain name via an environment variable, if there are places where providing a production domain is unavoidable and not possible to derive, such as on the server-side.

## Acceptance Criteria

common.xyz should be functionally identically to commonwealth.im as a production instance of the site.

**Comment by jnaviask** [comment]
Wont fix, as common.xyz is now a redirect rather than a separate DNS pointing to the same instance.
