### ISSUE TITLE
I should be able to configure the User component to show the User's role

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#52]
We should add a `showRole?: boolean` attribute to the User component, which will render either "Member", "Admin", "Mod", or nothing, depending on whether the User is a member of the current community.

**Comment by raykyri** [comment]
There's already code here which should be straightforward to migrate onto the User component:

![image](https://user-images.githubusercontent.com/1273926/84093504-4201b300-a9af-11ea-9be9-0eee29e83047.png)

**Comment by zakhap** [comment]
I updated the label as this took me quite a while to finish up as scope kept creeping.
