### ISSUE TITLE
Thread posting failed on Terra Custom Domain

### ISSUE THREAD

**Issue by alexyoung23j** [hicommonwealth/commonwealth#5209]
## Describe the bug

A user was unable to post a thread on terra custom domain site, but was able to on commonwealth.im/terra.
![image (6)](https://github.com/hicommonwealth/commonwealth/assets/31940965/16260c10-fc95-40da-ae08-39b1e51b407b)

## To Reproduce

Attempt to post in terra on the custom domain site.

## Expected behavior

Posting should be possible on both sites.

**Comment by jnaviask** [comment]
@kurtisassad working assumption here is that their DNS configuration is causing the bug -- your task is to confirm that working assumption.

**Comment by kurtisassad** [comment]
Runs fine locally. Reading up on it, it looks like this error response is produced by Cloudflare. I cannot go into our settings because I get an authorization error after login, so I can not effectively debug if its our DNS issue or theirs.

**Comment by kurtisassad** [comment]
Our custom domains don't run on cloudlfare yet. This means that this is an issue with their cloudflare.

**Comment by jnaviask** [comment]
Growth team to follow up with issue on Terra's side.
