### ISSUE TITLE
Preview tool tips are not always visible

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5222]
## Describe the bug

ENV:
https://qa.commonwealth.im/
Branch/tag:
v0.6.12-3

## To Reproduce

In several cases on several discussions we have different behaviour for URL tooltips preview.

Reproduction steps:
1. Navigate to: https://qa.commonwealth.im/osmosis/discussion/3020-best-practices-for-drafting-proposals
2. Observe text

## Expected behavior

We should have consistent behvior on tooltips preview.

## Additional context

Video:
https://app.screencast.com/ZYz3IsvJtwrAQ

Related task:
https://github.com/hicommonwealth/commonwealth/pull/5130

**Comment by mzparacha** [comment]
I am not able to reproduce on both quill/markdown formatted text. I also tried locally with different nesting variations but had no luck with reproducing the issue.
