### ISSUE TITLE
Spike: Leap/Cosmoskit Wallet integration

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5236]
## Description

Per [chatter](https://buildcommon.notion.site/Cosmoverse-Takeaways-9c267863d3054fd3a180bed7f4d88a42) at conferences, we should consider adding Leap wallet support for Cosmos users:

What is the level of effort and impact of adding Leap wallet?
Is it time to add [CosmosKit](https://docs.cosmoskit.com/integrating-wallets)? (multiple wallets supported in one component)

## Engineering Requirements

2-hour timebox

## Acceptance Criteria

Report recommendations:
- Add Leap - yes or no?
- Add Cosmoskit?
  - This would entail wrapping Keplr and Leap integration into a unified Cosmos sign-in button
  - This give the option of adding other leading wallets. Should we add some of them? All of them?
- T-shirt size of total effort
- To support transactions (beyond just sign-in), would there be extra dev work for each wallet type?
- First dev ticket written

**Comment by dillchen** [comment]
Definitely worth a spike, I don't have a ballpark on the trade of effort v time, but either way this is definitely something to be looked at

**Comment by mhagel** [comment]
https://docs.leapwallet.io/cosmos/for-dapps-connect-to-leap/add-leap-to-existing-keplr-integration

**Comment by zakhap** [comment]
> https://docs.leapwallet.io/cosmos/for-dapps-connect-to-leap/add-leap-to-existing-keplr-integration

This seems promising

**Comment by mhagel** [comment]
Leap adds support chain-by-chain. They have 50+ so far. So not all cosmos chains are supported. That just means we would have to show it as an option only if the chain is supported.

**Comment by mhagel** [comment]
CosmosKit has support for MM snaps via Leap. I will look into this too.

**Comment by mhagel** [comment]
Recommendations:

Add Leap? - Yes

Via Cosmoskit? - Yes

T-shirt size of total effort: 5 points for CosmosKit with Keplr/Leap, 3 more points to add MM snap

To support transactions (beyond just sign-in), would there be extra dev work for each wallet type? - Maybe a bit

First dev ticket written: #5378

**Comment by mhagel** [comment]
Ready for review: @CowMuon @jnaviask @zakhap 

See recommendations above.

**Comment by dillchen** [comment]
Zak, let’s sync up tmrw to see when we want to do this if there are any
other login related items. If work begins next week and tickets are drafted
for staking, then we I would prioritize that

Sent via Superhuman iOS ***@***.***>

**Comment by mhagel** [comment]
MM Snap ticket: #5379
