### ISSUE TITLE
BUG: Tooltips text missing on several icons

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5249]
## Describe the bug

ENV:
https://qa.commonwealth.im/
BRANCH/TAG:
v0.6.12-4

Tooltip text missing on several icons (Communities, Feedback and Documentation)

## To Reproduce

1. Go to: https://qa.commonwealth.im/
2. Sign in with wallet or magic link
3. On top navigation hover with mouse over icons

## Expected behavior

User should see tooltips text for all icons.

## Additional context

Video:
https://app.screencast.com/RRsIO01JH2m9G

**Comment by masvelio** [comment]
duplicate https://github.com/hicommonwealth/commonwealth/issues/5286
