### ISSUE TITLE
Refactor to RESTful routes for Notifications

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#5256]
# Notifications

- Get Subscriptions for Current User: `GET /subscriptions`
  - Original: `/viewSubscriptions`
- Create Subscription: `POST /subscriptions`
  - Original: `/createSubscription`
- Delete Subscription: `DELETE /subscriptions/:id`
  - Original: `/deleteSubscription`
- Update Subscriptions: `PATCH /subscriptions?ids[]=1&ids[]=2…`
  - Originals:
    - `/enableSubscriptions`
    - `/disableSubscriptions`
  - Will update multiple subscriptions in batch
- Get  Notifications: `GET /notifications?category=XXX`
  - Originals:
    - `/viewDiscussionNotifications`
    - `/viewChainEventNotifications`
  - Combine original routes, filter notification type via query param

## Acceptance Criteria

- Move business logic into `ServerNotificationsController`
- Add tests for controller
- Rename routes according to RESTful outline
- Update routes to use `validateOwner` for simplified role check

**Comment by rbennettcw** [comment]
Originally was going to update these routes to adhere to the current MVC architecture, but with the new DDD approach, this is probably obsolete now. cc @Rotorsoft

**Comment by Rotorsoft** [comment]
the new DDD approach shouldn't stop anything in the roadmap... the idea is to incorporate changes incrementally without disrupting the plan.

**Comment by rbennettcw** [comment]
Closing in favor of #7254
