### ISSUE TITLE
[Research] Offline/Persistant mode with react query

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#5259]
React query provides support for persistent store which in turn can support offline mode.

This ticket is a research work to find out the feasibility of using [persistQueryClient](https://tanstack.com/query/v4/docs/react/plugins/persistQueryClient) from react query for offline support.

Basically we want to find out if
1. How [persistQueryClient](https://tanstack.com/query/v4/docs/react/plugins/persistQueryClient) can help for offline support
2. If step 1 goes in the right direction, then find out what needs to be done for existing react query controllers to support this persistant/offline mode
3. Not all API state code in frontend is on react query, if 1 and 2 goes well, find out what needs to be done to make this persistant/offline mode work with other features that can't be on react query yet like login/wallets and other features which directly involves chains.

This list is non-exhaustive.

**Comment by jnaviask** [comment]
Timebox to answer Qs 1-3: 2 hours.

**Comment by mzparacha** [comment]
> 1. How [persistQueryClient](https://tanstack.com/query/v4/docs/react/plugins/persistQueryClient) can help for offline support

This is done, it can setup the intermediate layers to use indexeddb/localstorage and manage everything in b/w with a few config options, [this commit](https://github.com/hicommonwealth/commonwealth/pull/5296/commits/16c5028b8aaf8a5526462f7d565d88403281e649) adds that in https://github.com/hicommonwealth/commonwealth/pull/5296.


Now going for 2. 
> If step 1 goes in the right direction, then find out what needs to be done for existing react query controllers to support this persistant/offline mode

**Comment by jnaviask** [comment]
Closing as completed.
