### ISSUE TITLE
Tags do not load in sync with discussions

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#526]
- from the homepgae, click into Edgeware
- go back to homepage, click into another community
- go back to homepage, click into Edgeware

before the discussions are shown, sometimes the "no tags" placeholder will show, and sometimes the tags loading spinner will show

**Comment by zakhap** [comment]
I couldn't replicate this on my machine on the latest `construct` branch.

**Comment by raykyri** [comment]
Looks like this is resolved by the chain loading changes that Jake made, and we can close this now.
