### ISSUE TITLE
Text Input Fields (Part 2)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5273]
UPDATE Nov 30, 2023: The design system page for this component was more thoroughly fleshed out, as not all states used in the designs below were documented on that page. The design has not change, nor have new states been added, but the figma file for the component is now much much clearer. [The link to that page is here](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=3308-16147&mode=dev). The details below are the **enumerated list of known problems** with the current implementation. 

## Description

Work done in #4293 wasn't complete to design specifications in Figma. [See comment here](https://github.com/hicommonwealth/commonwealth/pull/4293#issuecomment-1724022008)

I am moving that comment's requests into the Acceptance Criteria for this Issue for clarity of scope.

## Project Owner

PM: @zakhap 
Designer: @jessmart1213 

## Acceptance Criteria

- 1 - There are default and compact inputs at custom widths 250px, 275px, and 300px. This is not in the designs. 
    - [x] a - Q:  was there a purpose for this? => if not. 
    - [x] b - Reminder: all components, including inputs/form fields should have lengths divisible by 4, unless adjusting for responsive behavior.

- [x] 2 - Update ‘field label’ font weight to Caption/Medium.
- [x] 3 - Ensure disabled background color is Neutrals / 50 or #F7F7F7 not Neutrals / 100.
- [x] 4 - Icon color, Update blue icons to Neutrals / 400.
  ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/cd9d9f90-bdb5-46b4-a2e8-dc44087135a9)
- [x] 5 - Update spacing between error/success icons and message to 4px. Currently it is 8px.
  ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/44ee321a-7101-4001-bc54-65813381fa23)
  ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/39be932c-09bd-4081-8741-23c5c47efa8a)

## Error management (also for both form sizes)

  ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/f59c6ac9-273f-455b-a06b-2867b4b01c07)

- [x] 6 - Update so that the Invalid state is triggered immediately once user enters an invalid character. Currently Invalid state is triggered when user clicks away from the form field and in some cases after 3 or more characters are provided (see loom video attached at bottom). 

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/756be42e-ee0f-4e3c-a2c8-74080002acf5)

- [x] 7 - Update border styles (remove red) to match ‘Form field’ state `Typing - Invalid` which can be seen [[here](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=337%3A3535&mode=design&t=3NdJagkEObnyAZh1-1)]

  ![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/ea4c685a-b293-4964-801e-c3773ac1b668)

- [x] 8 - Update background and border styles to not be green to match ‘Form field’ state `Typing - Valid` which can be seen [[here](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=337%3A3535&mode=design&t=3NdJagkEObnyAZh1-1)]

## Loom prototype walkthrough for error management
https://www.loom.com/share/7d9b754cdb804f6d9506a633b8b9d3aa?sid=b89a79da-c88e-4150-83c4-f38b89c72959
Jessica created a loom for expected error management behavior. Please watch as it includes more examples for input invalidation errors et. al described above.

---

Please ask questions if anything is unclear, please reach out to @zakhap.

**Comment by mzparacha** [comment]
Just some notes:

Our recent form validation updates separated field validation logic (into CWForm powered by react-hook-form + zod) from the form control (text input, radio etc) and supports many validation approaches i.e "validate as we type" OR "validate on form submit" OR "validate on focus" OR "validate on blur". 

Currently `CWForm` is configured to validate on type (or any kind of input), so if/when any form field (text input, radio etc) is used with `CWForm` it will validate as we type (or any kind of input).

**Comment by mzparacha** [comment]
For 
> 2 - Update ‘field label’ font weight to Caption/Medium.

I checked the font-weight for the text input label and it is already set to 'caption' (both 'caption' and 'medium' have font-weight of `500`)

**Comment by mzparacha** [comment]
I am not completely sure about the "1a" item from the checklist in the ticket description, but from what I understood, the custom widths are only for showcase purposes on the `/components` page. So I will mark it as done for now.

cc: @zakhap
