### ISSUE TITLE
BUG: Minified React error #31

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5276]
## Describe the bug

ENV: Prod
Branch: Master

When user visit specific thread we have error on page

```
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bimage%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

## To Reproduce

1. Go to: https://commonwealth.im/oraichain/discussion/13426-join-our-beta-testing-program-experience-futures-trading-on-oraidex
2. Observe

## Expected behavior

We should render this page with data from db

## Additional context

https://app.screencast.com/oGEQxPd2YWl5g

**Comment by jnaviask** [comment]
Steps to reproduce:
- Go to create thread page.
- Insert an image into the thread body using the quill editor.
- Select the image and choose "h2" (i.e. put the image inside an h2).
- Submit the thread.

The page should crash.
