### ISSUE TITLE
h1/h2 styles not rendered correctly in comments/threads

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5280]
## Describe the bug
Once #5279 which fixes bugs introduced by #4794, it has been revealed that h1/h2 tags do not in fact change the font size in the rendered text, or do much at all except apply boldface.

The reason is a `font-size: 14px !important` style added in #4065, since upgraded to 16px in #5138. These `!important` styles completely blow away the h1/h2 sizing in the `formatted-text` mixin, which should theoretically be the source of truth for thread/comment body text styling.

The question remaining is, what SHOULD the style guidelines be for h1/h2, and can we remove the `!important` override? Likely we can remove the override by adding a `font-size` style to divs within `formatted-text` (i.e. as a default), itself automatically overridden by the child h1/h2 styles. Need to surface the specifics from design, though.

This is also a great opportunity to clean up the styles around formatted text, if needed.

## To Reproduce

Add h1 and h2 text elements, both in richtext/quill or markdown, and observe that they aren't larger.

## Expected behavior

TBD

**Comment by jnaviask** [comment]
Feel free to consult with @mzparacha and @masvelio (tagging for visibility).

**Comment by jessmart1213** [comment]
Hi @jnaviask, my understanding is that you need to know which headings from our design system correspond to H1 and H2 in our editor. Is this correct? 

If so I have mapped the headers below: 

**Headers** 
- An H1 in the editor will translate to design system “Heading 3 / Medium”
- An H2 in the editor will translate to design system “Heading 4 / Medium”

**Body copy**
- Body copy in the editor and on the thread page is “Body 01 / Regular”

I also illustrated the above in [figma file editor improvements](https://www.figma.com/file/ArBB0hnZzAxvD3UCQF6AQj/Editor-improvements?type=design&node-id=10%3A8120&mode=design&t=Qb41QKdisGaUJqaF-1). 
<img width="923" alt="Screen Shot 2023-11-01 at 11 22 52 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/0eb2ef29-d76d-438c-81d6-bee499c9656c">

Note: This figma file does not follow set EPD processes and was created to support what is believed to be a quick and easy improvement to our editor and forum experience. 

---
@jnaviask  this is not what you need, please let me know.

**Comment by mzparacha** [comment]
Hey @Israellund -- just syncing up to make sure we are not duplicating stuff.


I am working on https://github.com/hicommonwealth/commonwealth/issues/5297 which only changes styles for the rendered thread and comment body, that ticket only updates the paragraph style for b1 (body 1) to b2 (body 2), and from the description it looks like this ticket only deals with updating h1/h2 styles for thread/comment body. If this is the case then I think the work isn't duplicated, but lmk if its anything else.

**Comment by Israellund** [comment]
@mzparacha Yes, I will only concentrate on the h1/h2 and you can concentrate on the body so there are no conflicts. Thank you.
