### ISSUE TITLE
Right sidebar issues on screen resize

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#5289]
## Describe the bug

The video below shows multiple issues 
- 

https://github.com/hicommonwealth/commonwealth/assets/14819225/2b24b75d-405b-4bac-9ddc-c6fccb57af8b

- (0:16 sec) - `Linked Proposals` and `Linked Discussions` cards show up above the thread title
- (0:22 sec) - On second resize the cards are duplicated
- There are two tabs called `Links` but they show different cards
- (0:44 sec) - `Snapshot`, `Polls` or `Template` tab do not show any cards
- (0:47 sec) - After clicking `Thread` tab, now the content does not show cards as previosuly, only the thread

## To Reproduce

- on https://qa.commonwealth.im/dydx/ but also reproducible on master
- create thread to be able to see cards in right hand side
- resize the screen and observe how the layout changes desktop vs mobile

## Expected behavior

- On mobile view, cards should appear under the proper selected tab
- cards should be persistent and not duplicated over the page resizing
- when Thread tab selected, no cards should be visible, only thread 
- Double `Links` tab should be unified or better named

**Comment by Israellund** [comment]
I pulled the latest master and created a new branch, followed the steps from your video, but am unable to replicate the errors. Outside of the Polls information showing up under the Polls tab, which I have separate ticket for, everything seems to be resolved. Can you give me more clarification on this card? Am I missing something?
