### ISSUE TITLE
Create documentation for platform code structure guidelines

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#5292]
We've been incrementally applying new code guidelines to the platform API to make endpoints RESTful and decouple business logic. The guidelines are well-defined but not documented.

Here's the original proposal: https://github.com/hicommonwealth/commonwealth/issues/3989

Per discussion with Roger, this should be documented so that the backend team has a clear recipe for writing backend features. It will also help facilitate discussions about transitioning to DDD architecture.

# Acceptance Criteria
- Create a wiki document outlining the platform API coding guidelines

**Comment by gdjohnson** [comment]
Love this idea. Let me know if I can help in any way, and reach out any time with docs questions!
