### ISSUE TITLE
Update Typography for Thread+Comment bodies

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5297]
## Description

Example of Wonky MD page that should feel better after the below styles are resolved: https://commonwealth.im/juno/discussion/13332-juno-charter

- [x] Update MD Checkboxes to have same style as Design System Component, remove extra bullet to left of checkbox.
- [x] Codeblock should be monotype-1 (16px) and maintain spaces for proper ascii display
- [x] Around Dividers add 16px on top and bottom.
- [x] Lists should not have blockquote line to the left. 
- [x] Lists should support bullet, lettered, and numbered lists.
- [x] body text (p) should be Body 01, not Body 02.
- [x] 1px border, color: neutral-200, for borders on MD Table (for the cells)

DevMode Link to Complete Typography: https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=979-14&mode=dev

## Project Owner

PM: @zakhap

**Comment by jnaviask** [comment]
Related to #5280

**Comment by CowMuon** [comment]
Added grab-n-go label for Malik, Ifu & Israel, whoever gets to it first. (per comment above this is related to h1/h2 ticket Israel has.)

**Comment by mzparacha** [comment]
grabbing it

**Comment by mzparacha** [comment]
>  Lists should support bullet, lettered, and numbered lists.

Markdown already supports this. cc: @zakhap
