### ISSUE TITLE
Database tables private_thread_roles and read_only_roles_threads should be renamed

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#53]
These tables do not follow our naming conventions, nor is it clear from the table names what function the tables fulfill.

**Comment by zakhap** [comment]
These tables were generated as part of an association I added to the `OffchainThread` Model. Initially they were part of the privacy spec, to allow the thread creator to curate a list of people who could 1. If read_only, comment on thread, 2. if private, see thread. This feature was ultimately removed from the spec, as only community admins were to use the private feature and read_only was to have no extra permissioning. As of now, the tables will just remain empty, unused. 
Two options: 1. If we think we want those features in the near future, we could just rename them, 2. If we don't think these features are necessary in the near future, I can remove the association from the model and create a migration to remove the tables.
