### ISSUE TITLE
Include Magic Embedded Wallet into UI if Address Source is from Magic

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5309]
## Description

When we click on transactions that require a TX to be signed and a user has logged in with Magic, we should display the Embedded Wallet: https://magic.link/docs/universal/features/wallet-widget

## Project Owner
@dillchen 

## Engineering Requirements
- [ ] Toggle the Magic Wallet Widget
<img width="1448" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/0e67caeb-d1bd-4682-83b1-a88b1a0481d0">

## Acceptance Criteria
- Includes copy to notify the user that a wallet has been created
- Supports Fiat On-ramp at point of purchase or claim of rewards (by following designs)
- Supports viewing of address and balance, with clear prompt to look at their embedded wallet
- Clearly include link and copy to export (aka the magic reveal page)
- Adds an Icon that identifies the wallet SSO source in the sidebar
- Allows Magic Wallet users to participate in contests

## Design Dev Link

Design figma: https://www.figma.com/design/rBTow8pp1mvKyWmEM8z3aP/Magic-Wallet?node-id=1-52&t=HaIqsdg2Go8ndpHV-1

## Additional context

[Slack Conversation](https://commonxyz.slack.com/archives/C06TAS2SQUS/p1730745256105619?thread_ts=1730742186.127069&cid=C06TAS2SQUS)

also included (for design) with the [60 second audit](https://www.figma.com/board/0PhE2dOhL2IxMvSzf3ubzX/60-Sec-Audit?node-id=0-1&t=9XJ4bRKeRgcb8RZk-1)

**Comment by sssssabinaaa** [comment]
Design figma: https://www.figma.com/design/rBTow8pp1mvKyWmEM8z3aP/Magic-Wallet?node-id=1-52&t=HaIqsdg2Go8ndpHV-1
