### ISSUE TITLE
Enable Sidebar Toggle State

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5311]
## Description

Allow sidebar toggle to be shown on Homepage and All Pages so that sidebar that includes options to create and explore communities, and  remove the `FLAG_SIDEBAR_TOGGLE`

https://github.com/hicommonwealth/commonwealth/assets/5334557/0ad8af5a-7ad2-43fc-b190-53358219ce36

## Team
PM: @dillchen / @sachben91 
Design: @jessmart1213 / Jared

## Acceptance Criteria

**Sidebar Real Estate and Information on FYP and non community pages**

- Display a “home” and Home Title instead of the Common Logo, where we might see community "In Community Name" 
- Display active wallet on the homepage
- Display Create Community Button, similar to what we see on on the homepage

**Desktop Behavior**
- [ ] Animation
- [ ] Toggle should only appear on hover
    
![image](https://github.com/hicommonwealth/commonwealth/assets/5334557/cace3afb-e1b2-4b0c-bb1e-1d2306502175)

![image](https://github.com/hicommonwealth/commonwealth/assets/5334557/d5e35087-17e2-48a0-9cb3-c823d9499d81)

<img width="351" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/284e0a0e-63ae-48f5-a126-178e2e1c0760">

**Mobile Behavior**
- [ ] Minimum screensize and how it should either hover or slide over

**Comment by jessmart1213** [comment]
Hi team, cc @zakhap, per our conversation yesterday, here is an updated prototype for the collapsible sidebar.
- [Loom walkthrough](https://www.loom.com/share/d67f7db258cc47b9bcec9562518021b5?sid=8c660b86-78f5-45ab-81cb-ab1712128bdc)
- [Figma file](https://www.figma.com/file/w6Tli9ApqBqgsZa7kB0Vk5/Mobile-ideation-Q4?type=design&node-id=512%3A21904&mode=design&t=BGuy6vurg16RWsxH-1)

**Comment by dillchen** [comment]
@jessmart1213, this LGTM -> it's probably worth making a note to show tmrw the "future state" and exploration tmrw as well. making a mental note to self to bring it up tmrw

**Comment by CowMuon** [comment]
We now have a loom walk thru as well as a figma file on this. Slated for v0.9.2.
