### ISSUE TITLE
Add SMS Login

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5320]
Our user model

Client Side: use `magic.loginWithSMS` (or w/e) and include a new WalletSSOSource

Server Side: requires `email` and `emailVerified` we do not use any validation on the email string, because we assume that Magic will do that. if we want SMS login, we _could_ just save the phonenumber and _verified_ on callback in `auth/magic`

https://magic.link/docs/dedicated/login-methods/sms/integration/web

**Comment by ForestMars** [comment]
Not sure how this even got assigned, tbh.
