### ISSUE TITLE
`Topics` table + model semantics - Child of #3779

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5330]
Child of #3779
Prerequisite: #5246

## Description

Update the `Topics` table and model to replace `Chain` references with `Community` references.

## Project Owner

@timolegros 

## Engineering Requirements

- [x] Rename the `chain_id` column to `community_id`
- [x] Rename any foreign keys or indexes associated with the column
- [x] Update all direct (non-variable) references to the `Topics.chain_id` sequelize property

**Comment by CowMuon** [comment]
Now that we have RESTful routes for topics let's at least get this into backlog

**Comment by timolegros** [comment]
Bumping to 3 points since these semantic tickets always seem to take more time than expected. Also will need to very diligently test gating after the changes.
