### ISSUE TITLE
Create Poll modal doesn't expand when more than 2 fields added

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#5366]
## Describe the bug

When adding a Poll inside a new Thread, if the user selects more than 2 fields all inputs and buttons get pushed to outside of the modal boundary

## To Reproduce

Create a new thread and add a Poll. When the poll modal shows, add more than 2 Choice fields. Observe how the fields and buttons exceed the modal baoundaries

## Expected behavior

All text, fields, and buttons should stay bounded inside modal, either having modal grow, or adding in a scroll bar function within modal to account for growing information. 

## Additional context

![Image](https://github.com/hicommonwealth/commonwealth/assets/69872984/007a47f6-e65c-4311-ae1d-0f23ff883d35)

**Comment by masvelio** [comment]
@Israellund Please make sure you are on the latest master because recently modals have been updated and this issue should not be a case anymore

**Comment by Israellund** [comment]
Hi Marcin,
I thought that I had deleted that ticket. Sorry about that.
