### ISSUE TITLE
BUG: Community page does not render

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5373]
## Describe the bug

ENV: Production 
Branch: Master

When signed user visits https://commonwealth.im/horizen-eon, page does not render. 

## To Reproduce

1. Go to https://commonwealth.im
2. Sign in with wallet 
3. Go to horizen-eon community page

## Expected behavior

Page should render. Currently for non-signed users page is rendered. 
## Additional context

Image:
https://app.screencast.com/lhgaUmf9oQlTl

**Comment by jnaviask** [comment]
Crash seems to be thrown from `chainBaseToCanvasChainId`, specifically
```
  } else if (chainBase === ChainBase.Ethereum) {
    return idOrPrefix.toString();
```

**Comment by jnaviask** [comment]
Horizen EON chain node seems to lack an ETH chain id. Should be set to 7332 per https://chainlist.org/chain/7332.
