### ISSUE TITLE
Email Cleanup

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5386]
## Description

Similar to the recent Webhook clean-up, email functionality needs to be updated for clarity and testability, and to remove bugs.

## Project Owner

@timolegros

## Engineering Requirements

- Easily readable and testable email utility functions
- Fully typed email functionality
- Script for emitting emails at will

**Comment by jnaviask** [comment]
Relates to #5385

**Comment by timolegros** [comment]
This issue is blocked because I am unsure about the requirements for emails. We have 2 primary email templates/scripts:

Newer digest emails created in https://github.com/hicommonwealth/commonwealth/pull/2940. These emails contain activity data directly extracted from tables like `Threads`. When this issue was created I was not even aware of this email type because its logic is entirely contained in a single script file and it is only invoked in Airplane (soon to be Heroku: https://github.com/hicommonwealth/commonwealth/pull/6564). These emails may contain forum activity data that is unrelated to a users notifications.

Legacy immediate and weekly digest emails. These emails on the other hand are based on notifications generated for a specific user. The template for these emails is extremely outdated. Immediate emails are sent per notification and digest emails include all notifications for the week.

**Blockers:**
- What are the product requirements for emails? Should we support both notification and non-notification based digest emails or do we delete the legacy digest email?
- The legacy immediate email template on Sendgrid needs some love from design + front-end eng.
- Does the digest email need to support more than a 'weekly' interval i.e. do we want to allow users to specify daily, bi-weekly, or monthly digest email intervals?

**Additional Issues**
- Commonwealth emails can appear in spam rather than the main inbox
- `Sign in to your account` is not clickable in the login email template

**Comment by sachben91** [comment]
Based on discussion with @timolegros, heres the update on email notifications 
- We'll be keeping the weekly digest emails and legacy digest emails
- We should be deprecating the legacy immediate notifications - it would just be a barrage of notifications to the user at this point. We will revisit which specific user events we want to sent immediate notifications for 
- The templates for legacy digest emails needs to be updates - Jared will work on it for notifications V1
- The templates for weekly digest email may also need small updates 
- For email notifications, as part of the current push notifications PRD - **the goal is to have working, readable weekly digest emails.** 

cc @zakhap @dillchen

**Comment by timolegros** [comment]
This ticket is blocked until we have an email developer and working email templates that render beautifully in all email clients. Since this may be a while (it has already been several weeks), I am moving this to the backlog.

**Comment by timolegros** [comment]
All email logic has already been replaced and all the old logic should be removed when the Knock integration goes live.
