### ISSUE TITLE
Members Table UX improvements (Gating)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5392]
## Product Requirement

**1. Members Table Sorting**

When members have multiple Groups, sorting should be recursively alphanumeric; first sorting the Group names within the set for display, and then sorting table rows by the first item’s letter.

Example, three rows have the following groups: 

- Aa, Ab, B, C
- Ab, C,
- C

They are currently sorted alphabetically. Now in reverse they would be:

- C
- C, B, Ab, Aa
- C, Ab

****************************************2. Many Groups in a Row****************************************

Problem: what does it look like to have 4 + groups?

Solution: The group tags should wrap within the table cell, rather than overflowing to the right.

********************************************************************************************************3. Members + Group Page For Logged Out Users******************************************************************************************************** 

Problem: What do show to logged out users? 

Solution: 

- [x]  When a user is signed out and viewing the Members + Group Page, the Status Tags (”In group”/”out group”) are hidden.
- [x]  When a user is signed out and viewing the Groups Page, the filter dropdown is hidden (only useful for filtering by “in group” or “out group”).

**Comment by jnaviask** [comment]
Note: we would like screenshots/images but we will attempt to proceed without them due to bandwidth constraints.

**Comment by CowMuon** [comment]
If the estimation here exceeds 3 points, let's revisit scope before execution.

**Comment by CowMuon** [comment]
@zakhap Given we requested screenshots _last_ week, any chance we can have them for _next_ week?
