### ISSUE TITLE
Admin Growl For Introducing Groups

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5398]
## Description

Problem: We need to present to community admins that Groups nows exist and that they should create them for their community. 

Solution: Use our Growl Component and show it to community admins within their community.

DevMode Link: https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1784-312&mode=dev

## Project Owner

@zakhap 
@jessmart1213 

## Engineering Requirements

- [ ] Within the context of the community, if the active user is an admin of the community, show them this Growl component.
- [ ] Use our existing Growl component, use the SVG attached below (or export it again from Devmode)

![Image](https://github.com/hicommonwealth/commonwealth/assets/16248081/7329cd1c-b709-4f24-8573-8e8c71dcea4c)

## Acceptance Criteria

- [ ] Growl Design implemented to spec in Devmode Link provided above. 
- [ ] Growl should **only** appear within the context of a community + **only** to admin users within that community.
- [ ] Pressing the "X" button in the corner closes the Growl. The Growl should not reappear based on existing behavior of other Growls (I believe it uses localstorage). 
- [ ] "Learn More" should link to our Blog Link

## Additional context

There will be a subsequent ticket for a general member-centric growl. This ticket is for Admins only within the context of their community. 

![Image](https://github.com/hicommonwealth/commonwealth/assets/16248081/14f26ca9-02d9-4067-9930-83ccebbf391e)

**Comment by CowMuon** [comment]
Backlogged and can be tee'd up once it's no longer WIP. Should be <=2 points. 

Also jtn- "this" happened.

**Comment by CowMuon** [comment]
@Israellund possible pair here

**Comment by CowMuon** [comment]
@sachben91 @zakhap what do we need to do to get the WIP tag removed here?

**Comment by CowMuon** [comment]
@zakhap Is this still WIP?

**Comment by CowMuon** [comment]
Still waiting for WIP, but optimistically tteeing up. We can also re-assign to @Israellund if that's helpful to work directly with PD on this copy change.

**Comment by CowMuon** [comment]
Still nothing on this? What are we waiting on @zakhap ?

**Comment by CowMuon** [comment]
Ok, this will not make it into MVP (v0.7.5) shipping tomorrow, but will have to be a subsequent FF (v0.7.5-1)

**Comment by mzparacha** [comment]
this isn't `high priority`? so we can remove the label

cc @zakhap

**Comment by zakhap** [comment]
@lzach83 @Israellund UPDATE: the devmode link has changed to reflect copy updates from @jessmart1213. The Design and Functionality have otherwise not changed
