### ISSUE TITLE
BUG: Long titles are not truncated

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5406]
## Describe the bug

**ENV**: QA
**Branch**: Master/v0.7.2 tag

Logng titles are not truncated well and breaks page design. Related to: https://github.com/hicommonwealth/commonwealth/pull/5307

## To Reproduce

1. Go to: https://qa.commonwealth.im/1inch/discussion/11573-verifying-my-forum-identity-for-1inch-governance-addr-0x6a67421e77ef3fb718d2e6d01570fe96cdf7b520-sig-0x25e418017101292bc9d9f51d527f6a4a598ac086c68e1c694fc6e3950cd851e97f6aaa37a285f1845757659f2f1b345332b09694aa1e3f6a2cb89205bd7822b81b-1inchgovernance
2. Observe 
## Expected behavior

Thread Title char limit => 140 characters and truncate with Ellipsis to two rows max on discussion listing page

expected behavior discussed with @jessmart1213 and @dillchen 

## Additional context

Image:
https://app.screencast.com/TX9PmsUHzDciH

**Comment by dillchen** [comment]
This is also a good catch, It seems like the specific case here is that it's not the whole title is long, but specifically that one word was really long.

**Comment by lzach83** [comment]
> This is also a good catch, It seems like the specific case here is that it's not the whole title is long, but specifically that one word was really long. 

Ah. Yes, this is exactly it.

**Comment by lzach83** [comment]
PR: #5421 Fixes this issue.
