### ISSUE TITLE
Ensure padding left and right on mobile is 16px

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5413]
## Describe the bug

Through Mobile Friday, we have discovered that certain pages have 24px, 16px, or other widths on mobile. 

The design system specifies that 16px be used as the standard across mobile environments.

Here is one example:

<img width="1512" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/0fa43939-165b-467c-a454-dc4bd0009b9d">

cc: @lzach83.

## To Reproduce

Visit any mobile env and check inspector for padding

## Expected behavior

Update the following list of pages to have the proper padding on Mobile: 

- [x] /dashboard - current padding 56px
- [x] /discussions - current padding 40px
- [x] /discussion - current padding 56px
- [x] /members - current padding 24px
- [x] /overview - current padding 56px
- [x] /profile - current padding 16px
- [x] /profile/edit - current padding 50px
- [x] /notification-settings - current padding 176px
- [x] /proposals - current padding 24px
- [x] /discussions/:section - current padding 40px
- [x] /manage - current padding 24px
- [x] /new/discussion - current padding 24px
- [x] /snapshot - current padding 56px
- [x] /analytics - current padding 36px
- [x] /new/snapshot - current padding 24px
- [x] /new/proposal - current padding 24px

## Additional context

**Comment by zakhap** [comment]
@dillchen we should get the master list in this ticket so that this work can have clear acceptance criteria.

**Comment by dillchen** [comment]
https://github.com/hicommonwealth/commonwealth/issues/4985#issuecomment-1743439356

> left-aligned:

/dashboard - padding 56px
/discussions - padding 40px
/discussion - padding 56px
/members - padding 24px
/overview - padding 56px
/profile - padding 16px
/profile/edit - padding 50px
/notification-settings - padding 176px
/proposals - padding 24px
/discussions/:section - padding 40px
/manage - padding 24px
/new/discussion - padding 24px
/snapshot - padding 56px
/analytics - padding 36px
/new/snapshot - padding 24px
/new/proposal - padding 24px

center-aligned:
/createCommunity/starter

Note: These are all for the 1440px breakpoint.

**Comment by Miaplacidus** [comment]
@dillchen @lzach83 

Since "mobile" is not clearly defined in the ticket, I'm setting the padding to 16px for any screens smaller than the maximum breakpoint for small devices, i.e. the value of the scss variable `$breakpoint-small-max`, which is 904px.

**Comment by zakhap** [comment]
> @dillchen @lzach83
> 
> Since "mobile" is not clearly defined in the ticket, I'm setting the padding to 16px for any screens smaller than the maximum breakpoint for small devices, i.e. the value of the scss variable `$breakpoint-small-max`, which is 904px.

This is an acceptable solution!
