### ISSUE TITLE
Sort and Filter Desktop and Mobile Refinement

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5415]
## Description
Refinement of the Discussions Listing Page's filter and sorting functionalities. 
Goals:
- optimize filter display across various pages 
- introduce a compact dropdown + mobile icon representation.

## Project Owner
@dillchen (via Mobile Friday)

## Engineering Requirements
1. "Topic Filter" only on "All/Overview" page.
2. No "Filter by Time" on "Newest", "Oldest", and "Latest Activity".
3. Implement Compact Dropdown Menu, rather than full
4. Replace "Sort and Filter" text with Phosphor icon on mobile.

## Acceptance Criteria
1. "Topic Filter" exclusive to "All/Overview".
2. Absence of "Filter by Time" on specified pages.
3. Streamlined dropdown menu in use.
4. Clear Phosphor icon for mobile `Sort` and `Filter`.

## Additional context

<img width="323" alt="image" src="https://github.com/user-attachments/assets/6758bedc-ca5d-47fb-9c5e-23f17e3e15ce">

https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=742-62150&t=p541baAUwOZrTGKU-4

**Comment by CowMuon** [comment]
Added `needs design` label following conversation with @jessmart1213

**Comment by KaleemNeslit** [comment]
@dillchen  @sssssabinaaa  @Israellund  in this design we are using tab to switch btw all and overview .
in recent ticket #9501 we use dropdown to switch btw views  .Should i implement tabs or we use dropdown ?

**Comment by sssssabinaaa** [comment]
I think dropdown going forward, right @dillchen ?

**Comment by dillchen** [comment]
Keep Dropdowns for changing views and apply the new sort and filter within the same row on mobile

**Comment by KaleemNeslit** [comment]
@sssssabinaaa  @Israellund  i have one query 
on mobile we show fillter button when user clicked we show modal and in modal we show filler options 
![image](https://github.com/user-attachments/assets/ae650be4-9b64-4076-a303-e65fa2813b06)
 base on above conditions
