### ISSUE TITLE
Overview page should exclude any posts that are spam or archived

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#5426]
This is a fast-follow ticket on issue #3924 and is the result of a conversation had on PR #4338 (the PR associated with #3924). 

Currently, the Overview page displays threads that are spam or have been archived. This behavior is incorrect and these should not be present on the page at all. 

@zakhap feel free to add any details you think might be necessary.
Pinging @jnaviask @ForestMars to request that this be prioritized.

**Comment by CowMuon** [comment]
Ifu can you estimate this please? Would like to get this out for sure.
