### ISSUE TITLE
Increase Session Length on Magic and Server

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5428]
## Description

Based on #5368, we should be able to increase session length

## Engineering Requirements
- [x] Go into Magic Dashboard and increase session
- [x] Go into DB and update session
- [x] Update Canvas Session length? (unclear @raykyri) 

## Acceptance Criteria
- The user faces no regressions while updating sessions
- The user should face no mismatch in terms of session length between Magic, Canvas, or JWTs)

**Comment by raykyri** [comment]
We're not enforcing session lengths inside the Canvas validators right now, so no change needed, but when it does happen, I would recommend setting it to Common Client session length +7d or +10d, so infrequently logged-in users only end up seeing the regular login flow (vs the session revalidation flow). Not that there is a very big difference between them anyway -- it's like being logged out of Google.

For more sensitive scenarios we might want to enforce more frequent session revalidations but I can't think of any that would involve Common Client offchain data at this point. Those would be uses like editing private Google Docs or Notion docs, reading/writing email, and secure private messaging.

Tagging #5368 so this note is backlinked there.

**Comment by ianrowan** [comment]
@dillchen Our current magic session length is 7 days, what's the new length we want to use? 
CC @jnaviask

**Comment by dillchen** [comment]
Can we do 2 weeks for everything?

Sent via Superhuman iOS ***@***.***>

**Comment by CowMuon** [comment]
Let's roll this into `v0.9.3` as it didn't make it in to `v0.9.3`
