### ISSUE TITLE
[STEP 1] Address Hex column : One Signer, One Account

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5429]
## Description

For all Cosmos addresses, we need a way to identify a pubkey. Let's add a hex column to the Addresses table, and run the conversion algo to populate for each address.

## Engineering Requirements

- Determine if it is necessary to update magic-generated addresses. Otherwise, focus on sefl-custodied wallet addresses (Keplr and variants)

## Acceptance Criteria

- Add optional `hex` column to Addresses table
- Document the purpose of this
- All Cosmos addresses that are used as wallet sign-in (Keplr) have their hex value filled
- when I sign in with any new cosmos address, a hex value is populated

## Additional context

- This is required before #5078 and #5226 can be implemented

**Comment by mhagel** [comment]
After testing this migration in frick, I see that it would be a good idea to run this as a background job. It ran ok, but I could tell the server was struggling a bit. 

This will take a bit more dev, so updating points to 3.

**Comment by mhagel** [comment]
@zakhap 

Something to note, which I didn't fully consider until now: Ethermint accounts are derived differently from standard Cosmos accounts (because of their interoperability with EVM).

So an `evmos1...` and `inj1...` address may share a signer, but their siblings on other chains `osmo1...`, `juno1...` will have their own common signer.

Of course, users can still manually link them into a single profile, but we won't be able to do it ourselves (AFAIK). Is that still acceptable?

**Comment by zakhap** [comment]
> @zakhap
> 
> Something to note, which I didn't fully consider until now: Ethermint accounts are derived differently from standard Cosmos accounts (because of their interoperability with EVM).
> 
> So an `evmos1...` and `inj1...` address may share a signer, but their siblings on other chains `osmo1...`, `juno1...` will have their own common signer.
> 
> ~Of course, users can still manually link them into a single profile, but we won't be able to do it ourselves (AFAIK).~ ^ actually, our UI won't make this easy as is.
> 
> Is that still acceptable?

This seems acceptable to me. The primary case we're working toward here is general interoperability within the standard cosmos experience. Addresses derived differently and from different signers should be handled like we hand other EOAs linked to single account+profile.
