### ISSUE TITLE
[STEP 2] Notify affected users: One Signer, One Account

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5430]
## Description

There are some Cosmos users who will have their profiles consolidated:

- num signersWithMultipleProfiles: 473 as of 10/19/23

We need to let them know that all their Cosmos addresses (that share their current sign-in pubkey/hex) will soon be consolidated to a single profile. This should be done with a modal upon sign-in. They can then make adjustments to their current profile if they want, so that it persists in the coming migration.

## Acceptance Criteria

- As a user who signs in with Keplr, if I have more than one CW Address sharing the current pubkey, I should be notified that all of my cosmos Addresses will be consolidated to the current Profile, so I should update it if needed.
- I am given a specific date of the coming change
- If I do not meet the above criteria, I do not see a modal.

## Additional context

Recently active users under this criteria:
- num signersLast12Months: 298
- num signersLast6Months: 81
- num signersLast3Months: 10

#### **Unanswered Questions**:
  - How much time do we give before the migration date? 1 month? 2 weeks? AKA: what is the merge date?
  - Are we aligned on the consolidation strategy: _**Merge to most recently used Profile**_ ?
  - Should we also be emailing these users? LOE may go up if so.
  - Need copy for this.
    - Do we recommend updating username (and other info), so that this Profile reflects the user's public identity across communities?
      - Ex: my name is "mhagel | Common" in /osmosis, but it is "mhagel | Cosmos dev" in /juno

**Comment by zakhap** [comment]
@mhagel This is acceptable to me.

Do you mind making a csv file export of all the impacted signers with their profiles that will be merged? That way we can come through and reach out to specific KOLs

**Comment by mhagel** [comment]
@zakhap 

> Do you mind making a csv file export of all the impacted signers with their profiles that will be merged?

Happy to. I will have to do some query editing to get the right data in there. Should have it tomorrow.

**Comment by mhagel** [comment]
>Do you mind making a csv file export of all the impacted signers with their profiles that will be merged?

@zakhap emailed it to you

**Comment by mhagel** [comment]
Revisiting, since this has been on the backburner.

@zakhap Is this still something we want to do? I haven't revisited the data lately, but there should be about 300 users who may have some addresses attached to multiple accounts. Do we want to consolidate them, pre-empted by some sort of notification?

**Comment by mhagel** [comment]
JTN this may be addressed by updates to the Address and membership model, which is currently being spec'd.

**Comment by mhagel** [comment]
1. How should we notify users that their addresses will be consolidated - email or banner?
2. Will we consolidate to the most recently used profile?
3. Need copy

@jnaviask @zakhap
