### ISSUE TITLE
Add CW721 Support to Groups/Gating

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5438]
<img width="731" alt="Screen Shot 2023-10-24 at 1 42 33 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/75369769-1f4d-4200-8b0d-133cab7e95b0">

## Description

The Cosmos Chain "Stargaze" is one of the largest chains and has an ever-growing community of NFT collection holders. On Stargaze, contracts are prefixed with stars: e.g. `stars1vsqjr98w6e4x34nqxjgc8xy8hgkzenvfz3c9j9wnj227wvhzuz8sg8tc4z`. 
CW721. 

CW721 contract addresses refer to an entire collection. Our first **requirement type** will only care if a user has some balance of tokens within the collection, not any particular id from the collection nor any particular "nft attribute" on their particular id owned. 

Admins who want to create a Group with the CW721-Requirement type should _only_ have to include the collection's contract address + a threshold info. 

- The work in two parts: 
  1. Front-end, a new requirement option in the Edit/Create Group Form. It is only a copy change from 
      -  [DevLink](https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1451-55794&mode=dev) 
  2. Backend, the CW721 Requirement should being able to access/query for the balance of tokens a specific users has within that contract ("of the collection"). They should be able to own any of the ids within the collection. This balance will be used with the threshold ("more than 5") to evaluate if the member passes the requirement.

## Project Owner

@zakhap 

## Acceptance Criteria

- As an admin creating or editing a Group, I want to be able to use a balance of tokens from a single CW721 as a requirement.
- As an admin using the CW721 Requirement, I want to be able to set the threshold.
- As a member getting checked to see if I'm in a Group with a CW721 Requirement, if my connected address posses some balance of the tokens with the collection and I meet the threshold required, then I will be added to the Group.

## Additional context

- [Github Link to the CW721 Documentation, specifically around querying the contract](https://github.com/CosmWasm/cw-nfts/blob/main/packages/cw721/README.md#queries).  See: `OwnerOf` and `numTokens`.

- [Stargaze query interface for testing](https://studio.stargaze.zone/contracts/sg721/query/?contractAddress=stars1vsqjr98w6e4x34nqxjgc8xy8hgkzenvfz3c9j9wnj227wvhzuz8sg8tc4z)
-

**Comment by CowMuon** [comment]
Assigning to Dillon because he said this is 3 points.

**Comment by mhagel** [comment]
That query tester seems to be blocked by CORS, but following the code, we may want to refer to this:

https://github.com/public-awesome/stargaze-studio/blob/488d3306231a80747d9f440b1810f1becba2aa7e/contracts/sg721/contract.ts#L379-L384

Note the `tokens` query is probably what we are looking for.

**Comment by zakhap** [comment]
@dillchen Can we pass this ticket off to someone else?

**Comment by dillchen** [comment]
Yes

Sent via Superhuman iOS ***@***.***>

**Comment by mhagel** [comment]
batch client video: https://vimeo.com/771505975

We may need to extend it for our purposes
