### ISSUE TITLE
Proposals Not Showing in Sidebar

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5447]
## Describe the bug
- Bug affecting [Sentinel community](https://commonwealth.im/sentinel): Under governance category in left sidebar, ‘proposals’ tab is not showing up. They have proposals and the proposals page does exist tho: https://commonwealth.im/sentinel/proposals

## Expected Behavior
- ‘proposals’ tab in the left sidebar should show up for this and all communities that have proposals. 

## Affected Community / Reported By 
- [Sentinel community](https://commonwealth.im/sentinel):

**Comment by jnaviask** [comment]
Resolved via a manual SQL query to upgrade Chain (Community) type from "offchain" to "chain".

**Comment by CowMuon** [comment]
@jnaviask Please document required query either here or in knowledge base. Ideally the latter would be on the PR resolving the issue. (Also left some questions on that PR.)
