### ISSUE TITLE
On Create Thread page, page title removed and tab should be hidden

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5456]
## Describe the bug

On a New Discussion Page, It says "Proposals" + has a tab at the top. 

![image](https://github.com/hicommonwealth/commonwealth/assets/5334557/5c15cf0e-7185-42b7-98bd-a19d620d7a9c)

## To Reproduce
- Go to the Create Thread page.

## Expected behavior

- rename title to Create Discussion. 
- remove tab.

**Comment by CowMuon** [comment]
Is this page supposed to have breadcrumbs? @sachben91
