### ISSUE TITLE
Contract Helpers and ABI for Deployment for Namespace

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5473]
## Description

Build out client side helpers that abstract all blockchain interactions for Deployment of namespaces. This means Components can directly call given functions to submit or view data from the chain using methods on a contract object that contains the abstracted logic

## Project Owner

@ianrowan 

## Engineering Requirements

- Use the proposed contract structure of #4926 to create a base contract object which injects a web3/wallet instance of contract to expand on.
- Only require Component input and contract address to use/instantiate a helper
- Abstract multi-call contract actions into single helpers where applicable
- provide view methods with cleaned response data for use in UI/UX
- use a miminal abi(only necessary functions) for optimization

## Acceptance Criteria

The following should be possible with the Namespace deployment helpers
- Check if namespace is reserved
- Check if name is already taken
- get address of a name
- deploy a namespace
- configure and id for use with community stakes

- **Added by Dillon:** Add lite documentation on "how to use helpers" for a product engineer

## Additional context
Link to the [tech planning meeting](https://docs.google.com/document/d/1kMmYZXL1hzfHTIT35C5CLVovFrQfZVJ8_zIRAMPkbVE/edit)

**Comment by ianrowan** [comment]
@dillchen should this ticket encompass CommunityStakes helpers as well or just namespace deployment?

**Comment by dillchen** [comment]
Good Q, let’s do two tickets.

One for namespace

One for communitystakes helpers

Sent via Superhuman iOS ***@***.***>
