### ISSUE TITLE
DS: Add New Button States (for Community Stakes)

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5475]
## Description

As part of community stake we are including three new button types.

- [ ] #5560

<img width="409" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/812b5f8c-41c5-4f29-9097-7ba2cab1b890">

- [ ] #5561

<img width="106" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/feecd187-5f19-4ad4-b5e6-b9133c947253">

- [ ] #5562

<img width="582" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/62c082af-5b2b-48f4-9d0f-bf6b1f44909b">

## Project Owner
PM: @zakhap
Designer: @jessmart1213 

## Acceptance Criteria
- Add the Button to the Design System (described on each ticket)

## Additional context

**Comment by masvelio** [comment]
@dillchen @jnaviask @CowMuon not sure if this ticket is necessary 🤔 we should have 3 different PRs for 3 different tasks included in the description

**Comment by dillchen** [comment]
You are right we could delete it. it was intended to be a kind of Button Bucket ticket, but seems silly to have this here now because there are the three separate issues. I will close
