### ISSUE TITLE
Implement Manage Stake Modal

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5476]
## Description

A Modal that allows a user to purchase or sell stake, depending on how it's been accessed. For context, it can be acted via `Buy Stake` and `Sell Stake` accessible in #5477 or `Buy Stake` #5505

Requires #5504 (for tooltip)
Requires #5475 (for buttons)

[DevLink with all states](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Staking?type=design&node-id=1117-201449&mode=design&t=BVH8vX8wmVfLSNNr-4)

[Design Solution Notion Doc](https://www.notion.so/buildcommon/Design-Solution-Community-Stake-c0f4a573fb2f4195bf625a253d5c7a85?pvs=4#b1f8d0b18a724d3d9590734609f58cd6)

## Project Owner
PM: @dillchen 
Designer: @jessmart1213 

## Acceptance Criteria

[Here is the PRD where the user stories](https://www.notion.so/buildcommon/PRD-Community-Bond-Stake-eb1805840777495c8e257447af4d0520?pvs=4#470bc44145264aa1846b4ab01c1fcf9a) come from. 

As a user, I can use the increment and decrement buttons to set how many stakes I want to buy/sell, seeing my total vote weight and price/cost related information update immediately.

As a user, depending on if I access this via, `Buy Stake` and `Sell Stake` accessible in #5477 or `Buy Stake` #5505, I should show the `Buy Stake` or `Sell Stake` modal.

This is a form, I will list proper form state
- As a user, I should be able to select my address based on current active addresses based on chain

Display Information
- **In Current Balance:** As I select my address, I should display my current ETH balance
- **Number of Stake**: Requires: https://github.com/hicommonwealth/commonwealth/issues/5480 to display
- **Total ETH Price of Stake**: Display the Price of ETH in USD. 
  - This will have to come from sort of price feed. Realtime updates are not necessary here, but it should update on refresh. Some research may be necessary to select an adequate source. 

**Form Input 2: You Buy / Sell**
- As I toggle via `-` or `+`, I should update the the number
- As I toggle, I should display **my total upvote weight** requires Upvote Power API (and is calculated via number of sum (current stakes + num of stakes bought / sold) * vote power per stake

**Information Display**
- **Fees**: requires #5480 
- **Total Cost**requires #5480 and current ETH price feed
- **Points**: num of stakes bought / sold) * vote power per stake

On click of `Buy Stake / `Sell Stake` should use the number of Stake bought or sold to create a transaction and open the wallet modal. From here we should show success or error state(s).

Error States: Transaction Failed (due to) 1) out of gas and more

([link to error states figma](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Staking?type=design&node-id=1117-201938&mode=design&t=BVH8vX8wmVfLSNNr-4))

- As I generate a valid transaction, I should be able to click into a link to Etherscan to follow along with my transaction. [DevLink](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Staking?type=design&node-id=1117-202207&mode=design&t=BVH8vX8wmVfLSNNr-4)

<img width="304" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/250912bd-b3ac-4a64-9ce1-726adfda5076">

## Additional context

<img width="504" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/a29daeb6-b6a2-4a84-a482-643740900512">

**Buy Stake With Explainer Open**

<img width="542" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/e045ab6e-679a-4471-bf93-da8437e9fc3d">

**Sell Stake With No Explainer**

<img width="175" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/eeb468a7-f971-4e74-883b-32bf136ece86">

**Mobile Breakpoints**

**Comment by masvelio** [comment]
blocked by #5560 #5561 #5504

**Comment by masvelio** [comment]
@dillchen also here, I would suggest to build first the scaffold for modal(s) with static data and we should wire it up later on

**Comment by dillchen** [comment]
I think that makes sense to me. Is static modal with data blocked

**Comment by masvelio** [comment]
> I think that makes sense to me. Is static modal with data blocked

The ticket is blocked to be fully finished but we are not blocked to start working on it. We can add new buttons/tooltips by the end of this story.

**Comment by dillchen** [comment]
Perfect. Makes sense. And per last comment on the call. I will work with
Jess to update ticket with dev link

Sent via Superhuman iOS ***@***.***>
