### ISSUE TITLE
Add VoteWeight Module in Sidebar

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5477]
## Description

When a community has stake enabled, this module is shown in the sidebar. It displays the current address' point balance, ETH price of purchase, and includes a prompt to buy or sell

Defines Balance Information, which we will say
- **Vote Weight**:  for displaying "vote weight" (I.e 5 or 50x)
- **Number of Stake**: Requires: #5480 to display
- **Total ETH Price of Stake**: Requires: #5480 to display

DevLink (to be updated): https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Weekly-contests?type=design&node-id=478-54190&mode=design&t=ZQlRIoqmIQJbucwY-4

## Project Owner
PM: @dillchen 
Designer: @jessmart1213 

## Acceptance Criteria

- As a user if a community has stake enabled and I do not have stake, I should show the "Zero state", I.e only "Buy Stake"
- As a user if a community has stake enabled and I do have stake, I see my current balance information
- As a user after I purchase or sell stake in the #5476 modal, I should see my balance information refresh.
- As a user I should receive more information if I hover over the "I" icon.

## Additional context

<img width="529" alt="Screen Shot 2023-11-22 at 2 28 51 PM" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/679e63d2-ccd5-4081-8f6c-a22415d76b03">

- When users have no stakes, they have:
    - A vote weight of 1
    - One button, “Buy stake”
- This info icon is always present. On:hover triggers “Vote weight explainer” popover.

<img width="483" alt="Screen Shot 2023-11-22 at 2 30 23 PM" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/cd86960f-6a99-434b-a2bd-13eb6b7d216f">

- When users has stakes, they have:
    - A vote weight that corresponds to their stake
    - Two buttons, “Buy stake” and “Sell stake”
- This info icon is always present. On:hover triggers “Vote weight explainer” popover.

Mobile ([link](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Staking?type=design&node-id=1153-224753&mode=design&t=BVH8vX8wmVfLSNNr-4))

<img width="307" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/40daf4be-0d31-45bb-b245-0cecf633cad2">

PRD with [Additional Context](https://www.notion.so/buildcommon/PRD-Community-Bond-Stake-eb1805840777495c8e257447af4d0520?pvs=4#636269506fac4a32b01dc0462bad1f38)

- Product will finalize the Vote Weight Explainer Copy in QA

**Comment by masvelio** [comment]
@dillchen To move things forward and to not wait for data layer to be done, I would suggest create a static component first with hardcoded values. When we will have data available, we can glue it together.

**Comment by masvelio** [comment]
blocked by #5560 (we need green button, apart from it, work can be started)

**Comment by masvelio** [comment]
2 points for static component without dynamic data and without clickable buttone

**Comment by Miaplacidus** [comment]
Updating the points to include work for mobile styling/functionality and button styling.
