### ISSUE TITLE
Contract helpers and ABI for Community Stakes

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#5480]
## Description

Build out client side helpers that abstract all blockchain interactions for CommunityStakes. This means Components can directly call given functions to submit or view data from the chain using methods on a contract object that contains the abstracted logic. Areas of interest here are: 
- buy/sell stake
- get price w/ fee breakdown
- stake balances

## Project Owner

@ianrowan 

## Engineering Requirements

- Use the proposed contract structure of #4926 to create a base contract object which injects a web3/wallet instance of contract to expand on.
- Only require Component input and contract address to use/instantiate a helper
- Abstract multi-call contract actions into single helpers where applicable
- provide view methods with cleaned response data for use in UI/UX
- use a miminal abi(only necessary functions) for optimization
- Properly update TBC on buys/sells regardless of caching

## Acceptance Criteria

The following should be possible with the CommunityStake helpers
- get current price w fee breakdown, given a namespace name(as a type/object)
- buy an amount given namespace, properly calculate exact payable amount abstractly 
- sell an amount and provide expected proceeds
- TBC is reset/updated on above actions
- quotes occur given an amount, final numbers fetched from chain, not calculated client side 

- **Added by Dillon:** Add lite documentation on "how to use helpers" for a product engineer

## Additional context
Link to the [tech planning meeting](https://docs.google.com/document/d/1kMmYZXL1hzfHTIT35C5CLVovFrQfZVJ8_zIRAMPkbVE/edit)

**Comment by dillchen** [comment]
Just leaving a note here and thinking forward that implementors of the front end should be tagged as reviewers as that PRs get drafted on this #5473
