### ISSUE TITLE
Mixpanel: Forum + Topic Events

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5488]
## Description

For all of the following events below, we'd like to collect events for them in Mixpanel. 

Next to each item after the colon, I have expressed toward what end we care about the event so you have the necessary context for the dashboards we want to make. 

With each event, we should _always include_: community id (where), user id + address id (who)

### Topics
- [x] Topics Created: average, max
- [x] Topics Edited: frequency, # per week/month/quarter

### Forum
- [x] Threads Created: frequency over time
- [x] Comments Created (include thread_id): frequency over time, distribution across threads,
- [x] Reactions Created (include thread or comment id): total, average per thread, min/max
- [x] Proposals Linked To Thread: feature usage, total uses
    - by Type (Snapshot, Governance)
- [x] Discussions Linked to Thread: feature usage, total uses
- [x] URLs (Links) Linked to Thread: feature usage, total uses

### Polls

- [x] Polls Created: usage
- [x] Votes on Polls Created: usage

## Project Owner

@zakhap

**Comment by Miaplacidus** [comment]
@zakhap 
Just to make absolutely sure: either user_id or address is acceptable (depending on the context, of course)?

**Comment by Miaplacidus** [comment]
@zakhap 
In regards to proposals, I've created the 'Link Proposal Button Pressed' event, which tracks when the user hits "Save Changes" on the link proposal modal. In addition, there is a 'Linked Proposal' event, which occurs for each type of proposal saved and indicates what its type is.
