### ISSUE TITLE
Mixpanel: Groups + Gating

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5492]
## Description

For all of the following events below, we'd like to collect events for them in Mixpanel.

Next to each item after the colon, I have expressed toward what end we care about the event so you have the necessary context for the dashboards we want to make.

With each event, we should always include: community id (where), user id + address id (who)

### Groups and Gating Related Events, sorted by Page event is triggered

- Members Page
  - [x] Page Viewed: feature usage
- Groups Tab on Members Page
  - [x] Page Viewed: feature usage
- Create Group Page
  - [x] Page viewed: admin interest in feature, # of page views
  - [x] Groups created: follow-through on form, usage, # of form completions
- Edit Group Page
  - [x] Page Viewed: # of page views, interest in updates.
  - [x] Successful Edits: # of successful updates, follow-through + completions
- Informative Banner Clickthrough to Groups Tab on Members Page
  - [x] From View Thread Page (when trying to comment on a thread in a gated topic): # of impacted users who want more info
  - [ ] From Create Thread Page (when trying to post in a gated topic): # of impacted users who don't complete the thread

## Project Owner

@zakhap

**Comment by CowMuon** [comment]
Switching assignees here as Gating is top priority and Israel has some other priorities in his queue.

**Comment by Miaplacidus** [comment]
@CowMuon @jnaviask
Just adding timing context here. This card isn't expected to be finished by end of day. 
Implementation of this can follow that of gating.

**Comment by zakhap** [comment]
@Miaplacidus It would be great if some amount of metrics can go in before Istanbul

**Comment by Miaplacidus** [comment]
@zakhap 
Working on it. 
Furiously typing!
