### ISSUE TITLE
Mixpanel: Growth Metrics

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5493]
## Description

For all of the following events below, we'd like to collect events for them in Mixpanel.

Next to each item after the colon, I have expressed toward what end we care about the event so you have the necessary context for the dashboards we want to make.

With each event, we should always include: community id (where), user id + address id (who)

EVENTS FOR GROWTH TEAM TEAM PRIORITIZATION:
- [x]  Signed-in: total events, total unique users => # of users who visited commonwealth per quarter
- Create Community Page: frequency, weekly, monthly, quarterly
  - [x] Page Viewed: total number of attempts  
  - [x] Communities Created: successfully completed form
- [ ] Joined Community: # of users becoming communities members, by community, over time

## Project Owner

@zakhap

**Comment by Miaplacidus** [comment]
@zakhap 
I've included the community id on the community created event just in case you want to do something with that information. If not, let me know.  In addition, I've added one of the user's addresses on the community creation page view event, even though no address is technically active.

**Comment by Miaplacidus** [comment]
> > In addition, I've added one of the user's addresses on the community creation page view event, even though no address is technically active.
> 
> The API should pick an address that becomes admin. Can we use that Address for the event?

@zakhap 
Noted! Will update (you and the code, hopefully)!

**Comment by Miaplacidus** [comment]
@zakhap 
No, that address is not accessible outside of the `onClick` action on the button to actually create the community.
