### ISSUE TITLE
BUG: Bold formatting not working for Edgeware 

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5501]
## Describe the bug

ENV: Production

Bold formatting not working for Edgeware 

## To Reproduce

1. Go to: https://qa.commonwealth.im/edgeware/discussions
## Expected behavior

Edgeware had some special Bold formatting. Currently that feature doesn't work.

## Additional context
Any other context here, such as communities affected, growth team links, etc
### Reported by:
Edgeware

**Comment by CowMuon** [comment]
Pretty sure this is not just Edgeware, but is affecting any community? (Ie it was first reported by Edgeware, which in itself is interesting.)

**Comment by Israellund** [comment]
Unable to replicate bug. Went over with Rhys and Mark in Growth, we were able to apply bold to the text, even with markdown

**Comment by Israellund** [comment]
Rhys says no longer a problem, bug is fixed.
