### ISSUE TITLE
Create new Upvote Popover

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5506]
## Description

As part of Community Stake, as a user upvotes, on hover, we should show the most recent upvotes, number of upvote, and the upvote power that a user upvoted with.

This task is to implement the design for a new Upvote Popover that will later replace our existing one.
This component should display recent Upvotes from users as well as the total upvotes.

More context for the component: In communities without Weighted Voting + Stakes, we will use this component but not display weights next to Upvotes.

[Devmode Link](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Weekly-contests?type=design&node-id=533-84187&mode=design&t=F3Z9OJWz936TlYdh-0)

## Project Owner
PM: @dillchen 
Designer: @jessmart1213 

## Engineering Requirements
- Note from @masvelio: we should not modify existing component, instead creating a new component

## Acceptance Criteria
- Create the component to the design specification and add it to the Component Kit.
- Do not use it in context as we will roll it out across the site later.

<img width="390" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/c0c50775-0249-45ac-864e-b48e32aa9548">

- On Mobile, there is slightly different behavior.
- On Mobile, Thread Listing Page (because there is no on hover state), we display text, "show upvotes". On Click we will show the "popover".

<img width="228" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/823dc984-d67c-497f-be01-0f8ad220566b">

[DevLink for mobile behavior](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1212-59947&mode=design&t=DBm4kNl6EHwpN04N-4)

**Comment by masvelio** [comment]
blocked by blocked #5504

**Comment by Miaplacidus** [comment]
Updating points to include mobile functionality/styling.
