### ISSUE TITLE
ETH Price Feed for Stake

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5508]
## Description

Fetches a ETH price feed in USD denomiation from [idk] and uses it to calculate information for fees in #5476

## Project Owner
PM: @dillchen 

## Engineering Requirements
- Choose an acceptable price feed
- Create easy helper for use client side

## Acceptance Criteria
- Provide ETH price in USD to pages + components that may require it, such as #5476. 
- It does not matter to product if the data comes from the front-end or back-end.

## Additional context
ETH Price refreshes obviously real-time, so we really we just have to be solid around what the tradeoffs are. We do not need tick level accuracy. I would say we should just have on page refresh accuracy. Because all purchases are ETH denominated

**Comment by zakhap** [comment]
Migrated over to #5476.
