### ISSUE TITLE
Keep Sidebar Header Present between communities

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5529]
## Describe the bug

The Sidebar header disappears between communities. It should stay present, but empty, while loading the next community.

https://github.com/hicommonwealth/commonwealth/assets/16248081/755f4ed6-146c-4e59-ae63-de9729f9c7d0

## To Reproduce

Use leftbar quick switcher to toggle between communities.

## Expected behavior

The sidebar header (where the community name + avatar lives) should stay present, but empty, when switching between communities to prevent the visual up/down glitchy movement.

**Comment by CowMuon** [comment]
Added both Malik and ZachLee here, whoever can get to this the fastest, please grab it and go! 

This is our highest priority ticket for sprint #6 (mixpanel analytics notwithstanding)

**Comment by mzparacha** [comment]
I am assuming that we are talking about this part, plz correct if wrong

<img width="545" alt="Screenshot 2023-11-03 at 7 46 56 AM" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/2878fc04-0e0f-4e48-aff2-08b92adf729d">
