### ISSUE TITLE
BUG: Console error when admin navigates thru pages

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5543]
## Describe the bug

ENV: Production
Branch: Master

When super admin or community admin navigates thru pages on kunji-finance we have console errors

## To Reproduce

1. Sign in on https://commonwealth.im/
2. Go to https://commonwealth.im/kunji-finance/discussions
3. Navigate thru pages
4. Observe

## Expected behavior

When user navigates thru pages we should not throw any errors.

## Additional context

Video: https://www.loom.com/share/7b2da259b9fe4227b3361e495d1d395b?sid=a3c1c240-6682-48cb-984b-0ee026da0c8b
## Reported by
kunji-finance

**Comment by CowMuon** [comment]
Anyone from peng/enablement can grab kudasai

**Comment by mzparacha** [comment]
Going to grab this one

**Comment by mzparacha** [comment]
Not reproducible on local


https://github.com/hicommonwealth/commonwealth/assets/51641047/21805b5b-91a6-4fc3-b282-bcca70ab1042

**Comment by lzach83** [comment]
I wonder if this is related to #4382 in someway.

**Comment by CowMuon** [comment]
Reassigning to Malik.
