### ISSUE TITLE
BUG: Error occurring when trying to reach the topic token threshold

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5546]
## Describe the bug

ENV: Production 
Branch: Master

“When someone is trying to add umee tokens to reach the 500k threshold, this error appears. It's been like this in the past, any idea how to fix/surpass this and add funds to a proposal?”

## Expected behavior

Should go through with no errors when threshold is reached
## Additional context

<img width="606" alt="Screenshot 2023-11-01 at 21 47 43" src="https://github.com/hicommonwealth/commonwealth/assets/8557292/4557e6f4-61b4-4fe4-935e-725836080584">

**Comment by mw2000** [comment]
Some searching around leads me to cosmjs, which is where this error seems to be originating from.

**Comment by mw2000** [comment]
Error likely in this directory https://github.com/hicommonwealth/commonwealth/tree/master/packages/commonwealth/client/scripts/controllers/chain/cosmos

**Comment by jnaviask** [comment]
Adding @mhagel to help with reproduction.

**Comment by mhagel** [comment]
Duplicate of https://github.com/hicommonwealth/commonwealth/issues/5469

Will be fixed by #5520

**Comment by mw2000** [comment]
@mhagel ahh okay, sounds good

**Comment by mhagel** [comment]
closing duplicate
