### ISSUE TITLE
Discord Env Var Clean-up

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5548]
## Description

Discord environment variables are in dire need of a clean-up. There are 5 environment variables that are no longer used. Additionally, the staging environments have incorrectly set Discord environment variables (envs linked to personal/deprecated Discord applications/bots).

## Project Owner

@timolegros 

## Engineering Requirements

- Delete `DISCORD_OAUTH_CALLBACK`, `DISCORD_OAUTH_SCOPES`, `DISCORD_UI_URL`, `DISCORD_BOT_SUCCESS_URL`, `DISCORD_BOT_URL`
- Update `DISCORD_BOT_TOKEN`, `DISCORD_CLIENT_ID`, `DISCORD_CLIENT_SECRET` on Frick, Frack, and Beta.

## Additional context

@gdjohnson once this PR is merged these env var should be updated in the list (or is it all in the wiki now?).

**Comment by gdjohnson** [comment]
Environmental variable purge has been put on the backburner temporarily, as due diligence was taking a lot of time & higher-priority documentation projects started coming up. Hopefully I'll finish it off soon, would be nice to cut down & get docs in.

In the meantime, I'll make a note in the spreadsheet, thanks for tagging me!
