### ISSUE TITLE
Add an optional address parameter to /getRewards, /getOffences, /getSlashes, /getImOnline, /getX routes.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#555]
- Many of these routes will use the new HistoricalValidatorStatistics table (look at this database model to see what data is on it).
- Other routes such as rewards/slashes should grab from ChainEvents directly.

**Comment by nblogist** [comment]
@drewstone  kindly have a look at the changes https://github.com/hicommonwealth/commonwealth/commit/2b3f73090d15ccb4ec5d8dbdbac7b5873a56fd05, also please make the tickets for  /getSlashes, /getImOnline routes.

**Comment by nblogist** [comment]
@drewstone please review the changes.

**Comment by drewstone** [comment]
Please open a PR @nblogist when you have changes you want reviewed.
