### ISSUE TITLE
Spike: architectural feasibility for community namespaces / staking

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5555]
## Description

In order to implement the community staking project, under investigation in #5552 and #5553, community admins will be able to attach namespaces and community staking contracts to their communities.

Assumptions:
- A community namespace may be deployed prior to the community's creation on the platform side, but the tx information will be available and provided to the backend.
- A community namespace may be deployed after community creation.
- Community namespaces and corresponding groups may exist with or without community stake, and the community should be able to enable and disable stake-based functionality without affecting the status of the contracts.
- We can assume #5494 will be shipped.

The scope of this ticket is two-fold:
1. Create a brief proposal of changes required to "attach" namespaces and stakes to a community, such that communities can own a namespace and a staking contract and will automatically have a group created. Pay particular attention to _where_ and _how_ the contract information will be stored such that it's flexible enough to support more, similar "attachments" in the future. The outcome of this proposal will become an implementation ticket.
2. Determine what clarification is needed from product to fully architect and implement the above, and ideally seek clarification to complete the architectural proposal.

Ideally we can also update the [Miro board](https://miro.com/app/board/uXjVNZ8oB3U=/) to clarify the flow within this red box:
![2023-11-02-111405_1450x833_scrot](https://github.com/hicommonwealth/commonwealth/assets/1860629/4d578f09-344c-4a99-bbeb-c8ab01b8db59)

## Project Owner

@jnaviask for general questions
@rbennettcw for questions about groups on the platform side
@dillchen for product-related questions (and @zakhap for consultation)

## Additional context

Timebox: 3 hours.

**Comment by ianrowan** [comment]
https://docs.google.com/document/d/16_QYXyiNjeg8_W97puVQhrCvrLKoJVemtN2ex_6BiBM/edit?usp=sharing

Spike research and propositions here. Note the first section "Namespace Reservation" Includes out of scope decisions that need to be made before the specific objective of the spike's architecture can be finalized. 

The doc is much more thorough but the end result from a ticket summary perspective is: 

+ Column to Communities: namespace = the on chain name(should be the same as id, but given the preambles issues I dont know if this will always be true)

+ Column to Communities: stake_id = the id on the ERC1155 of the configured community stake

+ Logic to existing create community route to facilitate community creation + verification of on-chain deployment to package into model(ie txhash + namespace name) 

+ New route(CRUD) to handle post-config of Community Stakes Ids

+ New route to add namespace to existing communities

**Comment by ianrowan** [comment]
One item of note, I chose to go in a different direction for "how contract information will be stored" 

One of the benefits of the namespace design is the ability to derive contract addresses from a name. In this case, there is no need to store the confusing an unnecessary contract address of the namespace per community when it can always be cheaply derived from its name.

There are no other contracts than the namespace that will need to be "attached" to the community as CommunityStakes is a singleton so building a system for attaching contracts doesn't seem to be the most effective way to complete THIS objective. 

Emphasis on THIS b/c I think attachments are still valuable for other potential features

**Comment by dillchen** [comment]
The Google doc is great.

Key product / platform engineering decisions align. The key decisions are

1. Legacy chain_id / community_id treatment.

As a philosophy, @ianrowan has circled "option 1 (in Google Doc)" here as what we want to choose.

This aligns with the [answer given here](https://commonxyz.slack.com/archives/C062S2DFUF8/p1698962393768099). We are a client of the protocol, we are not a privileged client (option 3 add'l reservations added)

2. Event driven vs link with namespace

We have also moved towards the unevent driven model for namespace -> community creation. Which is also contemplated in the Slack Message

-----
Out of scope.

We should claim / setup ENS for Common.xyz, when users claim a name they should receive a subdomain.

Namespace creation onchain is currently free (outside of gas). We should communicate that this pricing model may change, explicitly--as Namespace Alpha. We would like to move for a "Commons-driven" model. Where a registration fee may / will be charged based on domain registration. We can state that namespaces registered during alpha period may be a user's for X amount of time, but will after X amount of time, the fee model will apply.

**Comment by dillchen** [comment]
@ianrowan 

On the Namespace contract we hardcode / set the name.

```

function initialize(bytes32 _name, address initAdmin, address _feeManager) public initializer override {
    name = _name;
    feeManager = _feeManager;
    factory = msg.sender;

    _mint(initAdmin, 0, 1, "");
    _mint(factory, 0, 1, "");
  }

```

**Comment by jnaviask** [comment]
I'm wondering about
> 6. Presence of this group x id will alert all future logic that stakes is configured 
We may want an explicit flag, so the group can be configured as a gate without requiring weighted voting.

Beyond that, really great analysis. Agree with @dillchen on both counts.

**Comment by ianrowan** [comment]
I think this should help sum up the overall flow of deploying namespace, configuring community stakes and creating the community after those steps have completed. Notes include the client side methods that can be called after PR #5523 goes in as well for simplification of Client side development. 



![Image](https://github.com/hicommonwealth/commonwealth/assets/36428666/3a8a6e96-c255-44e8-b419-d1753d3d3c9a)

CC @jnaviask @dillchen
