### ISSUE TITLE
BUG: Custom-length pool duration always fallback on 5 days

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5556]
## Describe the bug

ENV: Production 
Branch: Master/0.7.2 

When user create Custom-length pool e.g with 3 days, it always fallback on 5 days.

## To Reproduce

1. Sing up on application
2. Create new pool
3. Set duration on 3 days
4. Save

## Expected behavior

Pool duration should be 3 days, not 5 days.

## Additional context

Video Loom:
[Custom-length pool ](https://www.loom.com/share/651f8f1838a3421084ad5a20056501d1?sid=2145786f-c219-4c8e-8de8-174bd37dbcb5)

**Comment by rbennettcw** [comment]
Ranking as 2.

Should be a very simple fix. Worst case scenario, there's some strange timezone issue.

**Comment by CowMuon** [comment]
Throwing this to @rbennettcw  to confirm whether there is a server side bug on this, or if this is just a bug in client side logic, @mzparacha should be able to have this fixed for the EOD.

**Comment by mzparacha** [comment]
> @mzparacha should be able to have this fixed for the EOD.

@rbennettcw fixed it in #5559.

**Comment by rbennettcw** [comment]
@CowMuon This is done and merged– will need to be deployed
