### ISSUE TITLE
Proposal data not visible when using IPFS

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5557]
## Describe the bug

No proposal metadata displayed when source is IPFS request
IPFS proxy is not properly caching responses.

## To Reproduce

- go to https://commonwealth.im/dydx/proposals
- If the cache has expired, you may see proposal titles and descriptions to lazy-load in
- Refresh -> the defaults are shown instead of different titles and descriptions:
<img width="1209" alt="Screenshot 2023-11-09 at 10 07 20 PM" src="https://github.com/hicommonwealth/commonwealth/assets/9438198/cd261901-eb6c-492e-9fd0-6c6287f72e1d">
- same problem for Cosmos gov v1 proposals: https://commonwealth.im/regen/proposals or https://commonwealth.im/kyve/proposals
- same problem for Snapshot Notification avatars (dydx)
- upon refresh, you get a missing image: <img width="1243" alt="Screenshot 2023-11-09 at 10 09 10 PM" src="https://github.com/hicommonwealth/commonwealth/assets/9438198/db225206-dab4-432e-ab82-4aabdf6b5312">

- Titles and description do not show. 
- Cosmos metadata shows buffer instead of JSON object

## Expected behavior

- Instead of fallback titles like "Proposal # 123", the IPFS data is loaded then parsed to show real titles
 <img width="665" alt="Screenshot 2023-11-02 at 11 11 46 AM" src="https://github.com/hicommonwealth/commonwealth/assets/9438198/d18cf281-850a-4c20-ba36-e97cf2fd3d4c">

- All expected metadata (in readable JSON) is visible if IPFS request succeeds
<img width="755" alt="Screenshot 2023-11-02 at 11 12 13 AM" src="https://github.com/hicommonwealth/commonwealth/assets/9438198/dc5704e2-25cf-4fef-9186-a6166579094c">

*You can view the expected behavior by disabling cache in the browser

## Additional context

https://github.com/hicommonwealth/commonwealth/pull/5244/files#diff-0d68a72e72a4b56f2ce62ce99c12a7cf459abb70978013d7ca724e6c18c04d94

^ arraybuffer is needed for images/avatars, but not otherwise.

Either add a query param to handle images differently, or decode arraybuffers from response.

**Comment by timolegros** [comment]
I think this is related to rate limiting not arraybuffer. Case in point: dydx proposal IPFS data loads fine. Probably related to: https://github.com/hicommonwealth/commonwealth/issues/4925

**Comment by timolegros** [comment]
Actually, this may be a mix:

Juno error `"timeout of 5000ms exceeded"`

But I know that Aave is rate-limiting related. `arrayBuffer` shouldn't affect how data is returned to the client given that we return the response type that the client requested.

Have you tested that juno works without `arrayBuffer` @mhagel?

**Comment by mhagel** [comment]
>Actually, this may be a mix:

>Juno error "timeout of 5000ms exceeded"

>But I know that Aave is rate-limiting related. arrayBuffer shouldn't affect how data is returned to the client given that we return the response type that the client requested.

Yes I think both problems exist. I have seen lots of 429s causing 500s. 

>Have you tested that juno works without arrayBuffer @mhagel?

Yes, removing the arrayBuffer request fixes the returned data. However, I think there is also a redis caching element here. We may need to bust the cache to get rid of the arraybuffer responses. @timolegros

**Comment by timolegros** [comment]
> > Actually, this may be a mix:
> 
> > Juno error "timeout of 5000ms exceeded"
> 
> > But I know that Aave is rate-limiting related. arrayBuffer shouldn't affect how data is returned to the client given that we return the response type that the client requested.
> 
> Yes I think both problems exist. I have seen lots of 429s causing 500s.
> 
> > Have you tested that juno works without arrayBuffer @mhagel?
> 
> Yes, removing the arrayBuffer request fixes the returned data. However, I think there is also a redis caching element here. We may need to bust the cache to get rid of the arraybuffer responses. @timolegros

I think the cache lasts for 24 hours, for local testing simply not enabling Redis should allow you to test but in production we can either wait 24 hours or manually clear the cache with a command like:
```
redis-cli --scan --pattern '/api/ipfsProxy_*' | xargs -L 1 redis-cli del
```
Note: UNTESTED

**Comment by mhagel** [comment]
I found that the problem is the redis cacheDecorator. We cache the returned data, but not the headers.

Therefore, when we hit the cache, there is no `content-type` returned to give to the browser, unlike in the original request/response. The cache-decorator loses this nuance.

So, we need to either avoid caching IPFS data, or modify the cache-decorator to keep track of response headers along with response body.

This explains why data may look correct at first - this is uncached. Refresh, and it will just be raw arraybuffers with no content-type.

thoughts @timolegros ?

@timolegros

**Comment by timolegros** [comment]
> I found that the problem is the redis cacheDecorator. We cache the returned data, but not the headers.
> 
> Therefore, when we hit the cache, there is no `content-type` returned to give to the browser, unlike in the original request/response. The cache-decorator loses this nuance.
> 
> So, we need to either avoid caching IPFS data, or modify the cache-decorator to keep track of response headers along with response body.
> 
> This explains why data may look correct at first - this is uncached. Refresh, and it will just be raw arraybuffers with no content-type.
> 
> thoughts @timolegros ?
> 
> @timolegros

Ahhh nice very catch/discovery. We definitely do not want to remove ipfs caching - will make the rate limiting issue even worse. We could update the cache decorator to cache some headers but we need to be careful here because some headers are time sensitive or client specific. Not sure how well this would fit into the cache decorator logic though.

**Comment by mhagel** [comment]
>Ahhh nice very catch/discovery. We definitely do not want to remove ipfs caching - will make the rate limiting issue even worse. We could update the cache decorator to cache some headers but we need to be careful here because some headers are time sensitive or client specific. Not sure how well this would fit into the cache decorator logic though.

How about we just skip caching for IPFS images, and restore caching for JSON?
