### ISSUE TITLE
Create new /getX routes

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#556]
- own stake over time
- total stake over time
- other stake over time
- nominators over time

These routes will grab directly from HistoricalValidatorStatistics table.

**Comment by nblogist** [comment]
@drewstone  please review the following changes: https://github.com/hicommonwealth/commonwealth/commit/4f87ace2869252f30feed9c73536515694ebad99

**Comment by nblogist** [comment]
@drewstone  if you get time, kindly review the changes https://github.com/hicommonwealth/commonwealth/commit/4f87ace2869252f30feed9c73536515694ebad99

**Comment by nblogist** [comment]
@drewstone If you get time, please review the changes.
