### ISSUE TITLE
DS: Add IconOnlyButton

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5561]
## Description

Add IconOnlyButton to design system

## Project Owner
PM: @zakhap
Designer: @jessmart1213 

## Acceptance Criteria
- Add the Button to the Design System (not sure how to write DS Acceptance Criteria)

## Additional context

**IconOnlyButton** [Link to Figma](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=3131-4457&mode=design&t=hNGFvW3nX9Y59eyL-4)

Note from Jessica: I created this component as we have used them in designs before but have officially added to the design system.  For community staking, we will only use size small. Will leave to product on how to task. 

<img width="912" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/7f7154b0-89ac-4dd5-b988-9f7a27728588">

**Comment by masvelio** [comment]
For Eng: as agreed with @jessmart1213 we are gonna use only Phosphor icons for those buttons
