### ISSUE TITLE
Opportunity to refactor Canvas functionality in Value Object to keep it DRY

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#5566]
## Description
Evaluate the use of canvas in threads, comments, and reactions to extract common structures and functionality 

## Project Owner
@Rotorsoft 

## Engineering Requirements
TBD

## Acceptance Criteria
TBD

## Additional context
Internal ERD model in Miro

**Comment by ForestMars** [comment]
Closing as stale
