### ISSUE TITLE
Bug: Edit Topic Threshold Modal still exists

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5583]
## Describe the bug

On Demo, where Groups+Gating is, the "Edit Topic Threshold Modal" is still an option for setting. We do not need this modal now that we have Groups + Requirements. This Modal should be Removed. 

## To Reproduce

Go into community, be admin, click "Edit Topic Thresholds" in left sidebar.

## Expected behavior

There is no longer a sidebar option that says "Edit Topic Thresholds".

**Comment by mzparacha** [comment]
Since we are using a feature flag for gating --  I will hide the "Edit topic thresholds" modal when gating is enabled. We will have to remove all related logic for "Edit topic thresholds" when gating is a normal things (not a feature flag anymore)
