### ISSUE TITLE
Adding Topics to a Group should NOT be Required.

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5584]
## Description

Adding Topics to a Group should **NOT** be Required as they currently are in the "Create/Edit Groups Form". 

## Project Owner

@zakhap 

## Acceptance Criteria

- An admin can create a Group without adding Topics.

**Comment by mzparacha** [comment]
> Adding Topics to a Group should NOT be Required as they currently are in the "Create/Edit Groups Form".

@zakhap Does this mean that an admin can remove all topics from an existing group? -- @rbennettcw I am not sure if we do any special op's when this happens/should-happen?

**Comment by rbennettcw** [comment]
Backend doesn't require a group to be assigned to any topics.
