### ISSUE TITLE
Error States (and small copy updates) for Create/Edit Groups Form

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5596]
### Group Name Input
![Screen Shot 2023-11-06 at 5 28 00 PM](https://github.com/hicommonwealth/commonwealth/assets/16248081/a7d17786-40b2-4d81-b6be-1c4833419e21)
- There is no error thrown for group name past 40 characters.
- Please see design for errors states needed detailed in the [[figma](https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1130%3A208420&mode=design&t=hRVqorkr9udcEDsn-1)](https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1130%3A208420&mode=design&t=hRVqorkr9udcEDsn-1).
- Remove the period “.” from helper text copy.

### Group Description Input
![Screen Shot 2023-11-06 at 5 28 07 PM](https://github.com/hicommonwealth/commonwealth/assets/16248081/fdc62143-4ae4-4d48-bc5a-1326975d1490)
- There is no error thrown for group name past 250 characters.
- Please see design for errors states needed iin the [[figma](https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1130%3A208421&mode=design&t=hRVqorkr9udcEDsn-1)](https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1130%3A208421&mode=design&t=hRVqorkr9udcEDsn-1).
- Remove the period “.” from helper text copy.

## Project Owner

@zakhap 

Design: @jessmart1213

**Comment by CowMuon** [comment]
All hands on deck to get Gating for Groups out before Ethstanbul.

**Comment by CowMuon** [comment]
Whoever can grab this first, please go for it

**Comment by kurtisassad** [comment]
I got it
