### ISSUE TITLE
Memberships not computed when Group has no topics

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5602]
## Describe the bug

In #5601 topics were made optional for a group. But when this is the case, we now no longer compute group memberships at all. Need to ensure we do create memberships even when a group has no associated topics.

## To Reproduce

Create a group without topics that you would be a part of. Notice that your membership does not get computed.

**Comment by rbennettcw** [comment]
Tested latest code on master– memberships *are* computed when no topics are specified for a newly created group.

**Comment by mzparacha** [comment]
Seems like its not reproducible anymore, just confirming -- @rbennettcw?

**Comment by rbennettcw** [comment]
@mzparacha Correct

**Comment by mzparacha** [comment]
Ok so i think we can close this cc: @jnaviask

**Comment by jnaviask** [comment]
Can't repro.
