### ISSUE TITLE
Can't join Cosmos community with Github sign-in

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5606]
## Describe the bug

Can't join/osmosis community with Github magic sign-in

## Expected behavior

Sign-in to /osmosis with github results in "connected" with magic-generated `cosmos1...` address

**Comment by jnaviask** [comment]
@mhagel is this still an open issue?

**Comment by mhagel** [comment]
>@mhagel is this still an open issue?

yes

**Comment by jnaviask** [comment]
May be related to #6230

**Comment by mhagel** [comment]
Fixed by #6230

**Comment by jnaviask** [comment]
Not fixed as of 0.9.4.

**Comment by mhagel** [comment]
Moved back to boom because this wasn't part of 0.9.4
