### ISSUE TITLE
UI Bugs and Amount input field update, Create/Edit Form Field Inputs

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5612]
## Description + Acceptance Criteria

- [x] overflow on bottom of Chain selection. should not overflow, see:
    <img width="271" alt="Screen Shot 2023-11-07 at 12 48 25 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/28149e66-8217-4d2e-be67-2785b0469ce1">

- [x] Disabled styling still weird. Disabled background should fill selector component:
    <img width="265" alt="Screen Shot 2023-11-07 at 12 49 20 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/c343f5be-03b0-4ccc-af3b-b5b78ffd6993">
- [ ] ~~Also for above, update copy to: “More than or equal to”~~ -- NOT updating as per https://github.com/hicommonwealth/commonwealth/issues/5612#issuecomment-1802403380

- [x] "Amount" input label within Requirements, for ERC20 and EVM Base tokens: 
![Screen Shot 2023-11-08 at 12 01 15 PM](https://github.com/hicommonwealth/commonwealth/assets/16248081/865c3e99-a5cf-4b7a-a1e2-804be7e7bca1)

- [x] After clicking “Add Requirement” Button, the “on:click” styling stays present until I click elsewhere. "Onclick" styling should only be "onclick": 
  <img width="1202" alt="Screen Shot 2023-11-07 at 1 25 08 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/c6c28108-4bf7-46b0-90c7-342f29e57375">

## Project Owner

@zakhap

**Comment by mzparacha** [comment]
> Also for above, update copy to: “More than or equal to”

I think the backend only does "More than"? -- @rbennettcw plz confirm

**Comment by zakhap** [comment]
>  I think the backend only does "More than"? -- @rbennettcw plz confirm

Yes! Please confirm. I believe our original threshold logic was ≥, but if that's not the case now, nothing to update.

> Also how does this ticket relate to https://github.com/hicommonwealth/commonwealth/issues/5611 ?

We should update it in both locations if confirmed.

**Comment by rbennettcw** [comment]
Currently, the balance check is "greater than", not "greater or equal to".

See `validateGroupMembership.ts` line 125

**Comment by mzparacha** [comment]
>  "Amount" input label within Requirements, for ERC20 and EVM Base tokens:

This is just UI right, we don't actually convert the amount while in the form? @zakhap

**Comment by zakhap** [comment]
> > "Amount" input label within Requirements, for ERC20 and EVM Base tokens:
> 
> This is just UI right, we don't actually convert the amount while in the form? @zakhap

Correct. Our input field will stay as an integer for the moment. We only want to change the display to decimal format as it is more user-readable.
