### ISSUE TITLE
BUG: Wrong publishing date on snapshot

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5619]
## Describe the bug

ENV: Production 
Branch: Master

On some snapshots we have wrong publishing date.

## To Reproduce

1. Go to https://commonwealth.im/stargatetoken/snapshot/stgdao.eth/0x57dfc29fe901e154f294e9e5fc6f7b26e58e4f9446d2d131168bb4531bd2a448 and https://commonwealth.im/stargatetoken/snapshot/stgdao.eth/0x2e079e8ead1d586cb3fd95e60d14e5ffba29ab7ff377a07d91037ee138989e4a
3. Check publishing date

## Expected behavior

We should display correct publishing date.

## Additional context

Image:
https://app.screencast.com/oYsz5jpTUR2VV

**Comment by Israellund** [comment]
There were two tickets for the same bug, so I'm closing mine and adding my description below:

Published date is reverting to default Unix time. This should be looked into as to why this is happening and put in guardrails to not allow this to become incorrect. This needs to be fixed to prevent [Y2K38/Epochalypse](https://en.wikipedia.org/wiki/Year_2038_problem)

[This could be a solution to fix date displaying incorrectly](https://stackoverflow.com/questions/70747322/javascript-date-object-keeps-on-returning-the-default-date-mon-jan-19-1970-191#:~:text=1%20Answer&text=The%20Date%20constructor%20from%20Javascript,the%20unix%20time%20by%201000.)
