### ISSUE TITLE
Design Blocker 2: Create/Edit Form Field Error States

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5624]
## Description

All the error states for the Create/Edit Form Field need to be implemented. 

Titles and Description Error States were implemented in #5596. Let's double check that the implemented states here are those reflected in the design.

Error states for the "Necessary Requirements" section are currently missing. 
 
The behaviors in full are detailed in the sticky note in the figma and illustrated in this designs which can be found in the [figma](https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1130%3A208423&mode=design&t=1LLnAeRZjf0Q6Vjb-1).

![Screen Shot 2023-11-07 at 8 49 21 PM](https://github.com/hicommonwealth/commonwealth/assets/16248081/ce2ca5d8-7951-43af-9ce5-42fe2d6ceda1)

## Project Owner

PM: @zakhap 
Design: @jessmart1213 

## Acceptance Criteria

- **Double checking:**
  - [x] The error states for the Title input are implemented to the design specifications
  - [x] The error states for the Description input are implemented to the design specifications
- **New:**

The error states for the "Necessary Requirements" section are implemented to the design specifications

- [x] Option ‘All requirements must be satisfied’ by default is checked.
- [ ] ~~User can uncheck both options leaving this input in a state where nothing has been checked.~~ Not doing
- [x] When a user checks option ‘At least [#] of all requirements’ the text-field state ‘Focus’ is triggered, indicating to the user that it must be filled.
- [x] Helper text is also triggered when a user checks this option. If user uncheck this option, helper text is hidden. 
- [x] If parent radio button is checked, then textfield must be filled.
- [x] Only acceptable characters are numbers
- [x] Number can not be 0
- [x] Number must be less than or equal to number of requirements added. 
- [x] Rather than throwing a unique error for each of these, there will be helper text detailing these requirements and general error message.
- [x] Disable the textbox inside label if its radio is not selected

## Additional context

Originally dispatched as a part of #5150.

**Comment by mzparacha** [comment]
> User can uncheck both options leaving this input in a state where nothing has been checked.

@jessmart1213 Just confirming if this should be done? -- Usually in native HTML5 we can't uncheck a checked radio.

**Comment by zakhap** [comment]
You can remove that line from the Acceptance Criteria! If it isn't possible, let's not worry about it 👍

**Comment by jessmart1213** [comment]
What Zak said ✅
