### ISSUE TITLE
Select Community Type

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5633]
## User Story
When I attempt to create a community on Common,  I should be provided with options for different ecosystems that my community in Common can exist in. Once I have selected an ecosystem, I should be prompted to connect the wallet or sign in with magic link that is compatible with the ecosystem that I have selected 

## Product Specs 

**options for ecosystems**: Ethereum, Solana, Polygon, Cosmos

compatible sign-in options: The Figjam lists out the flow for a user creating a community. Depending on what ecosystem the user selects their sign-in options are limited to ones that are compatible with the ecosystem. For example: If the user selects Ethereum, their options are to connect to Metamask wallet or sign in with magic link. If they are already signed in, we must check if the method of sign-in is compatible with an Ethereum community (also detailed out in the Figjam)

12/4 update after call with Marcin: If a user is not signed in and they land on the create community flow, they should be allowed to select an ecosystem without signing in. Once they have selected an ecosystem they will be prompted to sign in with a wallet that is compatible with the ecosystem they selected. 

Once the user picks "connect a wallet" or sign in with magic, they are directed to sign in. This sign in component will reuse the existing components we have When a user is signing into an Ethereum, Cosmos, or Solana community. 

[Link to Figjam ](https://www.figma.com/file/LzDHu1mIJIpB26c9IqyN4S/Create-Community-Process?type=whiteboard&node-id=0-1&t=RUKDOy9zpC6Hcz48-0)

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/8e6aa44d-69d5-42ea-8195-f060dc2c55ab)
- Once the user has selected an ecosystem, they are prompted with a modal to connect a wallet or select an address if they already have a wallet compatible with the ecosystem connected 
<img width="463" alt="Screenshot 2023-11-09 at 3 06 45 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/7f36552e-2b8e-45bd-8499-6a5cdaf60fe5">
<img width="323" alt="Screenshot 2023-11-09 at 3 06 30 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/495516f1-5f55-4e5b-a86c-72b70ce3d698">

## Designs

[Link to figma
](https://www.figma.com/file/WLN4nRpVGQJ9AjuxiJwuDS/Create-Community?node-id=508%3A13184&mode=dev)
[Mobile Screens](https://www.figma.com/file/WLN4nRpVGQJ9AjuxiJwuDS/Create-Community?node-id=393%3A13558&mode=dev)

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/2a4f4f03-4545-4a01-b8f9-5fdca08eb7f1)

### New Components
- https://github.com/hicommonwealth/commonwealth/issues/5640
- https://github.com/hicommonwealth/commonwealth/issues/5642
- https://github.com/hicommonwealth/commonwealth/issues/5646
## Acceptance Criteria
- The user is able to select an ecosystem and sign in with a compatible sign-in method to proceed to the next step in creating a community

**Comment by masvelio** [comment]
point 2 because it is assumed that other components/subtickets are completed so this is a matter of putting it all together into one piece
