### ISSUE TITLE
Community Selector

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5640]
## Description
Community selector is used in the select community type screen for the Create Community flow. It enables the user to select an ecosystem for their community. 
[
Figma dev link ](https://www.figma.com/file/WLN4nRpVGQJ9AjuxiJwuDS/Create-Community?node-id=440%3A13984&mode=dev)

## Behaviors 
- The community selector has a default state and hover state 
![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/7cb5b5dd-d3fd-47c0-b375-c16a902196a9)
- Additionally, the community selector for Ethereum has a recommended tag  

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/76f2befe-c319-45d8-9e6f-96518d5ea2d1)

- the padding for the community selector is as shown below (also in the figma) 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/0f0f7beb-ec88-4442-b2a1-8fc051e20207)

- The icons to be used in the screen for create community flow are: 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/c3cb3c30-ebc5-4959-aaff-d659befd5439)

**Comment by masvelio** [comment]
@sachben91 
Questions:
1. We have `default` and `hover` state. What about `selected` state? I think we should also have it? 
2. Let's confirm the flow: If user selects the community tile, the tile is not getting selected? Instead, the `New community admin` modal pops up? What happens if I close the modal with `X`? User sees community selection page again with no community selected?

**Comment by sachben91** [comment]
> @sachben91 Questions:
> 
> 1. We have `default` and `hover` state. What about `selected` state? I think we should also have it?
> 2. Let's confirm the flow: If user selects the community tile, the tile is not getting selected? Instead, the `New community admin` modal pops up? What happens if I close the modal with `X`? User sees community selection page again with no community selected?

1. We don't need a 'selected' state because the selector is essentially acting like a button, and the action that happens when you click it is that the sign in modal pops up
2. If the user closes the modal, they will see the community selection page again with no ecosystem selected. They will have to choose their ecosystem again
