### ISSUE TITLE
Convert group membership refresh endpoint to script

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5641]
The problem with running the membership refresh code as a route is that it interferes with the site performance due to running on the web dyno. If it's a script, we can run it in a separate dyno, with an isolated CPU, so it can take its time without blocking web dyno requests.

Ideally we make it a yarn command, like `yarn refresh-all-memberships`, and then we can deprecate it once the migration goes live.

**Comment by rbennettcw** [comment]
The logic for membership refresh is a bit more sophisticated than the existing scripts AFAICT.

I'm attempting to create a TS script which imports and reuses the existing refresh logic.

**Comment by rbennettcw** [comment]
Okay, I'm seeing some of the existing TS scripts actually 😁
