### ISSUE TITLE
Decimals in Requirements

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5649]
## Description

DevLink: https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1706-3645&mode=dev

NOTE: Please read the stickies next to each requirements updated designs. All the of the acceptance criteria and behaviors detailed below are also detailed in context to the components.

For our four Token Balance Requirements (ERC20, ERC721, EVM Base Token, and Cosmos Base Tokens), their onchain references _may_ store decimals with differing levels of precision.  In this issue, we want to make explicit that all token balance requirements will have a _default decimal precision_.  For some of the requirements, users will be able to set a custom decimal precision. We must store that input such that our conversion and presentation of their input remains consistent in the UI. 

Regardless of how we store the user input (as an integer), the user's "amount" input and what the user sees in the presentation of the requirement should always be the same number. For example, if the user inputs "10.01" into an EVM Base Token Requirement (which uses 18 decimal point precision), we store it as 10.01 * 10^18 (integer). We should always present it to the user as "10.01". 

Default Decimal Precision by Requirement: 
- ERC20: 18
- ERC721: 0 (no decimal input valid, no conversion necessary)
- EVM Base Token: 18
- Cosmos Base Token: 6

Both ERC20 + Cosmos Base Token Requirements will allow the user to set a custom decimal precision to override the default. See the designs. 

EVM Base Token and ERC721 do not allow the user to set a custom decimal precision. 

## Project Owner

@zakhap 

## Engineering Requirements

(@jnaviask) Note that JS numbers may be lossy when dealing with large numbers, and also that common libraries such as BN.js do not support decimals out of the box. My recommendation is to do all computation and storage of numbers in their integer form (i.e. store the big 100000...000 + use it with the API), and only convert to decimal for display.

## Acceptance Criteria

- [ ] ERC20 Requirement displays the new helper text, "set custom" button, and allows the user to set a new decimal precision. Default decimal precision: 18
- [ ] Cosmos Base Token Requirement displays the new helper text, "set custom" button, and allows the user to set a new decimal precision. Default decimal precision: 6
- [ ] For **all** requirements, the Amount Input should validate against the decimal precision (default, or set).
  - e.g. If the Amount is 1.05 and the decimal precision is 1, the amount input is invalid.
- [ ] Custom decimal precision input field should only accept integers, no special or alphabet characters.
- [x] EVM Base Token Requirement displays the new helper text. Default decimal precision: 18
- [x] ERC721 Requirement displays does not change. Amount input should only accept integers, no decimals. Default decimal precision: 0
- [x] On the Groups Tab of the Members Page, the requirements display the input exactly as the user provided in the "Create/Edit Groups Form". 

## Additional context

<img width="803" alt="Screen Shot 2023-11-09 at 8 54 01 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/f7529a6a-64b9-4d62-82a8-9f7cb0e09301">
<img width="869" alt="Screen Shot 2023-11-09 at 8 54 16 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/34f5d23f-ae20-4206-9038-0bc1a57b7054">
<img width="875" alt="Screen Shot 2023-11-09 at 8 54 24 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/ae4c9c22-f935-435f-b6af-755d0c2786ea">
<img width="885" alt="Screen Shot 2023-11-09 at 8 54 41 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/61ae0f38-bf85-48d0-9fd5-07c4c096c074">

**Comment by jnaviask** [comment]
@mzparacha what's the status on this ticket?

**Comment by mzparacha** [comment]
> @mzparacha what's the status on this ticket?

This ticket was introduced to address the decimal precision for various tokens and the option to add custom decimal precision. The decimal precision was addressed for the Cosmos/EVM/ERC-20/ERC-721 tokens but the custom decimal part was not done (was not intended for MVP) -- it needed changes on both frontend/backend.

I think @zakhap can confirm if we want to do the custom precision part on priority?

cc: @jnaviask

**Comment by zakhap** [comment]
We should no add the custom decimal precision in MVP. Let's postpone this ticket. As a part of Gating Follow tickets in Product, we may be write a ticket to supersede this one (but that's still TBD).

**Comment by CowMuon** [comment]
🥶 Iceboxed.

**Comment by zakhap** [comment]
Going to be superseded by a guardrail solution where we check on behalf of the user.
