### ISSUE TITLE
Multiple chain notifications are being incorrectly collapsed into one + We should show a datetime on chain notifications

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#566]
This hides chain notifications beyond the first unread one, so it just looks like notifications beyond that are missing.

![image](https://user-images.githubusercontent.com/1273926/89344468-c775ac80-d65a-11ea-8398-38d0b1c97758.png)

As a solution to this, we can just avoid collapsing chain notifications in general. If we can't do that, we should list the metadata (e.g. block number) for all events in the collapsed block.

If possible can we also show the date and time the chain notification occurred? As estimated by a created_by field would be okay.

**Comment by drewstone** [comment]
I think this is something @zakhap had worked on. Can you comment on this @zakhap ?

**Comment by zakhap** [comment]
The batchNotifications function I wrote is definitely causing this issue. I can have it filter all notifications from chain-events into their own Notification Row in the dropdown.

**Comment by raykyri** [comment]
Good catch, thanks @drewstone!
