### ISSUE TITLE
Dropdown menu, to design specifications

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5665]
## Description

<img width="754" alt="Screen Shot 2023-11-06 at 6 10 06 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/7875df01-d64f-4f38-b4a0-2d86063ef036">

- On:hover state persists even when mouse leaves list item.
- Above you can see selected list item and on:hover. Currently they are the same color. Update selected list item color to Neutrals / 50.
- Right now, Selected vs Onhover states are the same => they should not be the same

## Project Owner

@zakhap 

## Acceptance Criteria

- [ ] Remove persistence of "on:hover" styling when cursor leaves dropdown.
- [ ] Update dropdown styling to reflect the differences between "selected" and "on:hover"
  - See [devlink](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=535-5009&mode=design&t=Gx0te27UrVSfygeT-0) for specifics for each of the two states. Below attached, are screenshots of the relevant information as well for each state.

## Additional context

<img width="695" alt="Screen Shot 2023-11-09 at 1 45 35 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/7bbf6bf0-7f54-4681-92fa-3c6dd8bb0d21">
<img width="525" alt="Screen Shot 2023-11-09 at 2 16 16 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/b143a215-6fd2-483f-a95a-f583ea906d3f">

**Comment by mzparacha** [comment]
hm - these were working correctly yesterday.

**Comment by mzparacha** [comment]
i cant reproduce on both demo and local -- @zakhap is this still reproducible?

**Comment by zakhap** [comment]
No longer reproducible
