### ISSUE TITLE
Add 3 new EVM chains to our ChainNodes options

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5675]
## Description

- AVAX, chain_id: 43114
- Base, chain_id: 8453 [docs](https://docs.base.org/network-information/)
- Optimism, chain_id: 10 [docs](https://community.optimism.io/docs/useful-tools/networks/#)

## Project Owner

@zakhap 

## Acceptance Criteria

- [ ] The three options should be available for users to select in Groups as well as in the Chain selection in Community Creation.

**Comment by ianrowan** [comment]
Just for clarification - this ticket includes 2 tasks
1. Add new chainNodes 
2. Update create Community and Groups to make these available

Correct to include (2) as part of this PR? 

CC @zakhap @jnaviask

**Comment by jnaviask** [comment]
@ianrowan I assume adding them as ChainNodes should automatically make them available in the Create and Group pages? LMK if this is incorrect

**Comment by ianrowan** [comment]
@jnaviask yes you're right, became available upon adding
