### ISSUE TITLE
Fix Topic Selection Dropdown on New Thread Page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5681]
## Description + Acceptance Criteria

Update copy in Disabled Topic Tooltip: "You are not in the requisite group to select this topic" 

<img width="856" alt="Screen Shot 2023-11-09 at 5 53 38 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/2e6b6675-6265-42c6-a313-f87a82c52c88">

## Project Owner

@zakhap

**Comment by mzparacha** [comment]
![image](https://github.com/hicommonwealth/commonwealth/assets/51641047/c3fa4c29-d343-4614-b3e6-4a45980beee2)


This will conflict with 

https://github.com/hicommonwealth/commonwealth/issues/5397 which has an open pr https://github.com/hicommonwealth/commonwealth/pull/5638.

In 5397 we have a requirement

> Mirroring the solution for when a user is signed out but on the create thread form page, we should show an inline Callout when the user is not in the required Group for the Topic that they selected. If the user selects a Topic they can post in, the Callout should not appear. If they change the Topic to a topic they are not in the required Group for, the Callout will appear.

and if we follow this ticket the callout banner on new thread page will never show.

What should be the next step here? 

cc: @jnaviask @zakhap

**Comment by zakhap** [comment]
@mzparacha Great catch! Let's scratch this ticket and just go with the work on #5638.
