### ISSUE TITLE
Notifications code review

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#569]
New notifications UI looks good! Just wanted to collect my remaining questions here, as well as some minor requests for design changes.

- NotificationsSettingsPage uses wells, while ChainEventSettingsPage uses tables/table rows. For consistency both should use the same styling. I think the table rows design looks better.
- I know the original design used checkboxes, but can we change that to use a single dropdown for each row? The dropdown should have these options:
    - "Notifications off"
    - "Notifications on (app + email)"
    - "Notifications on (app only)"
    - I know this introduces some inconsistencies if the checkbox was in an indeterminate state. If the user is subscribed to comment notifications, we should treat that as notifications on, and if the user is subscribed to reaction notifications, we should treat that as notifications off.

Code review:

- on NotificationSettingsPage and ChainEventSettingsPage:
    - why set vnode.state.chains on the page, instead of using app.config.chains.getAll() directly?
    - why set vnode.state.communities on the page, instead of using app.config.communities.getAll() directly?
    - we should move both files into /subscriptions since they are classed .SubscriptionsPage
    - both files should follow camelCasePage.ts instead of hyphenated-snake-case-page.ts
    - can we use the appropriate enum in client/scripts/models/types.ts instead of strings like 'edgeware' etc.?
- on NotificationSettings Page:
    - why do we go through a multi-stage initialization in oninit and then oncreate? It seems unusual to have some initialization happening before render, and some after.
- on ChainEventSettingsPage:
    - why is the titler only used for edgeware and edgeware-local?

**Comment by zakhap** [comment]
Just gonna repost the issue as a series of TODOs: 
- [ ] NotificationsSettingsPage uses wells, while ChainEventSettingsPage uses tables/table rows. For consistency both should use the same styling. I think the table rows design looks better.
- [ ] I know the original design used checkboxes, but can we change that to use a single dropdown for each row? The dropdown should have these options:
    - [ ] "Notifications off"
    - [ ] "Notifications on (app + email)"
    - [ ] "Notifications on (app only)"
    - [ ] I know this introduces some inconsistencies if the checkbox was in an indeterminate state. If the user is subscribed to comment notifications, we should treat that as notifications on, and if the user is subscribed to reaction notifications, we should treat that as notifications off.

Code review:

- on NotificationSettingsPage and ChainEventSettingsPage:
    - [ ] why set vnode.state.chains on the page, instead of using app.config.chains.getAll() directly?
    - [ ] why set vnode.state.communities on the page, instead of using app.config.communities.getAll() directly?
    - [ ] we should move both files into /subscriptions since they are classed .SubscriptionsPage
    - [ ] both files should follow camelCasePage.ts instead of hyphenated-snake-case-page.ts
    - [ ] can we use the appropriate enum in client/scripts/models/types.ts instead of strings like 'edgeware' etc.?
- on NotificationSettings Page:
    - [ ] why do we go through a multi-stage initialization in oninit and then oncreate? It seems unusual to have some initialization happening before render, and some after.
- on ChainEventSettingsPage:
    - [ ] why is the titler only used for edgeware and edgeware-local?
