### ISSUE TITLE
Deleting Threads After Banning an Address

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#5706]
## Describe the bug
After you ban an address you can't delete the threads they posted

## To Reproduce
ban a user and try to delete a thread from them

## Expected behavior
the thread should delete

## Additional context
![Screenshot 2023-11-14 at 3 20 29 PM](https://github.com/hicommonwealth/commonwealth/assets/144931524/735ca6af-f507-47a4-a846-4d72e173e1e0)

**Comment by CowMuon** [comment]
@zakhap Is the affordance for admins to globally delete all threads of a banned user, or fine grained control over which threads are deleted? Assuming the former, but can support the latter if needed.

**Comment by mzparacha** [comment]
looks like a backend issue

https://github.com/hicommonwealth/commonwealth/assets/51641047/8a25e019-8d72-4b4f-b192-cb30cfdc058b

Tossing it over to @rbennettcw 🙏
