### ISSUE TITLE
`--forbid-only` not failing for integration or devnet tests

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5709]
## Describe the bug

The `--forbid-only` mocha flag which prevents `.only` calls in CI tests, is not catching `.only` calls for integration or devnet tests. When `.only` is used in integration/devnet tests, `ts-mocha` just hangs forever or fails silently (no error exit code) instead of throwing an error.

## To Reproduce

- Run `yarn integration-test --forbid-only` (`scheduleNodeProcessin.spec.ts` has `.only`)
- Run `ts-mocha ./test/integration/evmChainEvents/scheduleNodeProcessing.spec.ts --forbid-only` (this ignores the tests as if we skipped them).

## Expected behavior

Just as with unit tests, `ts-mocha` should throw when an integration test or devnet test uses `.only`.

**Comment by kurtisassad** [comment]
Forbid only works as intended, it basically skips the .only tests, not fails them. I had verified this by running in with a debugger and making sure it doesn't hit the breakpoint placed inside the .only test.

**Comment by timolegros** [comment]
> Forbid only works as intended, it basically skips the .only tests, not fails them. I had verified this by running in with a debugger and making sure it doesn't hit the breakpoint placed inside the .only test.

So we've discussed this on Slack but to be transparent on the ticket: `--forbid-only` does **not** work as intended. `--forbid-only` should result in a failure state and not simply 'skip .only tests'. This is evident from `mocha` documentation:

> Enforce a rule that tests may not be exclusive (use of e.g., `describe.only()` or `it.only()` is disallowed).
> `--forbid-only` causes Mocha to fail when an exclusive (“only’d”) test or suite is encountered, and it will abort further test execution.

Additionally, mocha _does_ throw an error when you use `.only` on a unit test, it simply fails to do the same for our integration tests:
![Screenshot from 2023-11-21 17-10-57](https://github.com/hicommonwealth/commonwealth/assets/62490329/c80b57e5-96d0-41b1-83ba-669de1af217e)

**Comment by timolegros** [comment]
Seems to be resolved: https://github.com/hicommonwealth/commonwealth/actions/runs/8049021680/job/21981548000?pr=6798.
