### ISSUE TITLE
Update design of council page

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#574]
not pixel perfect:

![image](https://user-images.githubusercontent.com/1273926/89448031-d9fbee80-d70b-11ea-8d50-ce23e56e0245.png)

- we should use the same date formatter, reaction button, and hover interactions/typography as the discussions page
- when clicking on a row, it can still just pop up the list of voters...not ideal UX but any changes there should be in a different branch
- for the "Set council vote" button, we can change how Sublayout works to allow injecting a new button into the header

**Comment by gdjohnson** [comment]
We want reaction buttons on council members? I'm a little confused... What do we pass it, the member? Do you want me to set up backend support for that?

**Comment by raykyri** [comment]
Oh, oops - no reaction buttons needed on council members for now!

**Comment by raykyri** [comment]
This is a duplicate of #475 now, closing
