### ISSUE TITLE
Generate Image is failing on Image Upload Component

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5773]
## Describe the bug

Generate Image Button is failing due to 405 on the Image Upload Component -> https://commonwealth.im/components

## To Reproduce

<img width="1418" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/ad904143-8a6d-4dcd-807f-df79207f1867">

## Expected behavior

- Allowed to generate image

## Additional context

- Should upgrade to DALLE3
- Should be a quick fix
- Should make the site way more fun

**Comment by Miaplacidus** [comment]
@dillchen @ForestMars @jnaviask 
This was fixed by updating the `OPENAI_API_KEY`. Checked the feature and it works on prod.
