### ISSUE TITLE
Choose Network - Cosmos Starter Community 

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#5775]
## Description

As a community creator, I want to be able to create a Cosmos starter community, and have it associated with my preferred chain (network).

## Acceptance Criteria

- Change "Base Chain" label to "Ecosystem" 
- In createCommunity/starter, after selecting Ecosystem = 'cosmos', I see a dropdown "Network"
- When I click "Network," I see a list of all available Cosmos chains. I can choose my preferred chain
- After I create a community, when I sign out and sign in again with Keplr, my address from the preferred chain is used to sign in.
- Example: If I chose Injective as my community network, my sign-in address should be my `inj1...` address.

## Additional context

- For Communities using ethermint chains (like Injective, Evmos, etc), we will need to make sure `keplr_ethereum_web_wallet` is used for sign-in. The Keplr "sign ethereum" flow should appear.

**Comment by jnaviask** [comment]
Completed with Create Community V1.
