### ISSUE TITLE
Deprecate `symbol` property on Community

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5780]
## Description

We currently don't appear to use `symbol` for anything on the Community model. We should remove the field (and replace instances remaining, if any), as it is not present in the designs for Create Community V1 anyway.

It was originally used to display onchain data involving balances, which I believe we now determine via other means.

**Comment by kurtisassad** [comment]
@jnaviask So to make sure we are not talking past each other, I took `symbol` to mean `default_symbol` in the Communities table. So if this is incorrect let me know.

Currently we currently use it to display the currency code of the voting results (see coin.format() in voting_results.tsx, `deom `of the coin comes from default_symbol). Do you have any suggestions how we could keep this functionality (is there some data in some other related table we can use)?

**Comment by kurtisassad** [comment]
Product is aware of this, and will implement it via the admin panel in a followup:
https://github.com/hicommonwealth/commonwealth/issues/5636#issuecomment-1839377549

Closing this ticket for now
