### ISSUE TITLE
Account lost admin access cannot setup webhooks

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#5791]
## Describe the bug
Profile issue from stride, "Nice! I'm trying to set up the webhook right now but it looks like my account no longer has admin access, maybe it was removed on the CW side? The account page for the address that was previously admin is now showing empty and if I connect with it, CW says it has never connected before"

## To Reproduce
n/a

## Expected behavior
the profile should be able to create webhooks and their admin status should not waiver

## Additional context
https://commonwealth.im/stride/account/stride133df0rz42d49jl3hzh6gtv6gf42x8vqac7wz70

**Comment by mw2000** [comment]
@cowballzach The account listed here doesn't seem to exist as there's an error loading the profile when I click on the link.

**Comment by cowballzach** [comment]
The person never reached out again, ticket is from so long ago so it's not super top of mind. I think we can close for now and if they reach out again we can reopen.
