### ISSUE TITLE
Profile id 127667 showing now activity history after #5762 fix

### ISSUE THREAD

**Issue by RhysCommonwealth** [hicommonwealth/commonwealth#5798]
## Describe the bug
This profile was the profile effected in this ticket: https://github.com/hicommonwealth/commonwealth/issues/5762
The user profile is [here](https://commonwealth.im/profile/id/127667)
RoundElephant (the effected user), is one of the most active members in the 1inch forum but is now showing 0 activity history in his profile. 

## To Reproduce
Visit the linked profile in the bug description section

## Expected behavior
The profile should be showing his activity history

## Additional context
There was two RoundElephant profiles in the db before the bug fixed. I'm unsure if they got merged
I am unsure if the profile activity history was removed when his account went to anon or if it happened after the fix was deployed.

**Comment by jnaviask** [comment]
Will re-create if needed.
