### ISSUE TITLE
Set `cacheRefresh` option to `true` for balance fetching on site visits

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5804]
## Description

- Per discussion on Slack:
  - Admin updates requirements -> use cached balance
  - User visits site (or page refresh) -> refresh cache
  - User takes gated action -> use cached balance

This caching strategy means we need to ensure that `cacheRefresh` is set to `true` when fetching a users balance for the first time of their session.

## Engineering Requirements

- Find where initial balance fetching occurs for site visits and set `cacheRefresh` to true in balance fetch options.

**Comment by timolegros** [comment]
@rbennettcw Note here that https://github.com/hicommonwealth/commonwealth/pull/5802 is a prerequisite for this ticket since it introduces the `cacheRefresh` option.

**Comment by rbennettcw** [comment]
> @rbennettcw Note here that #5802 is a prerequisite for this ticket since it introduces the `cacheRefresh` option.

Oh ok, good to know. Will review.

**Comment by timolegros** [comment]
@rbennettcw #5802 was merged so this ticket is unblocked.

**Comment by rbennettcw** [comment]
Updated from 1 to 2 since the new refresh policy required a bit more than simply enabling the `cacheRefresh` option.
