### ISSUE TITLE
User Growl for Introducing Groups

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5805]
**Very Related to #5398** 

## Description
Problem: We need to present to community **members** that Groups nows exist and that they _"should"_ know about them.

Solution: Use our Growl Component and show it to community members (NOT Admins) within their community.

DevMode Link: https://www.figma.com/file/ePuGFatYQI6GL72i27sVwj/Gating?type=design&node-id=1784-312&mode=dev

## Project Owner
@zakhap 

## Engineering Requirements

- [ ] Within the context of the community, if the active user is **not an admin** of the community, show them **this** Growl component.
- [ ] Use our existing Growl component, use the SVG attached below (or export it again from Devmode)

![Image](https://github.com/hicommonwealth/commonwealth/assets/16248081/7329cd1c-b709-4f24-8573-8e8c71dcea4c)

## Acceptance Criteria

- [ ] Growl Design implemented to spec in Devmode Link provided above. 
- [ ] Growl should **only** appear within the context of a community + **only** to **non-admin** users within that community.
- [ ] Pressing the "X" button in the corner closes the Growl. The Growl should not reappear based on existing behavior of other Growls (I believe it uses localstorage). 
- [ ] "Learn More" should link to our Blog Link
- [ ] "View Groups" should take them to the Groups Tab of the Member's Page.

## Additional context

There will be a subsequent ticket for a general member-centric growl. This ticket is for **Non-admins** only within the context of the community in scope.

**Comment by lzach83** [comment]
This work is completed in #5841
