### ISSUE TITLE
Improve Refresh Batch Prep

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#5809]
The current implementation of community membership refresh uses batching, but preparing the batch operations is CPU intensive due to multiple nested loops. Change it to a single SQL query that fetching and formats data in one go. That should offload the work to the DB and be more performant.

Discussion for context: https://github.com/hicommonwealth/commonwealth/pull/5757#discussion_r1408158679

@timolegros wrote this query as an example:
```
SELECT
    DISTINCT ON (source_data.source_type, source_data.source)
    source_data.source_type AS balanceSourceType,
    source_data.source,
    array_agg(DISTINCT a.address) AS addresses
FROM
    (SELECT
         g.id AS group_id,
         jsonb_extract_path_text(jsonb_array_elements(g.requirements)->'data'->'source', 'source_type') AS source_type,
         jsonb_array_elements(g.requirements)->'data'->'source' AS source
     FROM
         "Groups" g
    ) AS source_data
        JOIN
    "Memberships" m ON source_data.group_id = m.group_id
        JOIN
    "Addresses" a ON m.address_id = a.id
GROUP BY
    source_data.source_type, source_data.source
ORDER BY
    source_data.source_type, source_data.source;
```

---

NOTE: The query must be fixed to include *all* addresses within a community– whether they having an existing membership or not.

## Acceptance Criteria
- Update the `refresh_community_memberships.ts` file to use SQL in place of the existing `makeGetBalancesOptions` call
- Even better if the SQL can also replace the existing DB calls for groups and addresses
- Ensure that community refresh works without regressions (empty memberships table should become populated, existing stale memberships should be updated)
- Add tests for the refresh logic

**Comment by rbennettcw** [comment]
@Rotorsoft This is the alternative approach we're considering for the CPU-intensive code. Curious of your thoughts on other possible solutions to improve performance?

**Comment by Rotorsoft** [comment]
This is the query that loads all addresses belonging to the community/groups affected by the event that triggered the new projection right? 

I understand there is still some logic that matches these addresses with group rules affected by on-chain attributes (balances), required to complete the projection, and also CPU-intensive?

In general (as discussed), CPU-intensive tasks are better handled by async worker processes to avoid unresponsive apps - and blocking the event loop.

Not sure if we have other worker process scenarios, but this is probably a pattern that will repeat in other areas, worth investigating.
