### ISSUE TITLE
Move Membrane from ETH Starter community to Cosmos Starter community 

### ISSUE THREAD

**Issue by markiscommon** [hicommonwealth/commonwealth#5811]
## Describe the issue
- New community [Membrane](https://commonwealth.im/membrane) needs to be "migrated" from ETH Starter community to Cosmos Starter community. 
- They want their users to be prompted with cosmos wallet logins. 
- (This came out of last week's create Cosmos community issue.) 

## Proposed Solution: 
- [ ] Make sure to save off list of extant Eth addresses in this community in case it is needed.
- [ ] Confirm no one in this new (1 week old community) has created any content with their Eth addresses (so no orphaned content.) 
- [ ] Except for[ the single post](https://commonwealth.im/membrane/discussion/14227-proposal-guidelines) we already know about.) 
- [ ] Manually delete all users from community. 
- [ ] Manually change base chain from Eth to Cosmos.
- [ ] Re-add Admin users
- [ ] Test Test Test 
- [ ] Inform Membrane community is ready for members for re-join with Cosmos addresses.

## Additional Context 
- Spinning up new community not an option: 
I asked if i could just spin up a new community howev
<img width="326" alt="Screenshot 2023-11-30 at 2 07 09 PM" src="https://github.com/hicommonwealth/commonwealth/assets/128752305/ce1dccfc-6855-4971-88ca-4053aa08680a">
er

**Comment by CowMuon** [comment]
We should be good here as they have just the one published content (in description) and we are told none of other addresses joined to community have created content, reacted, etc. 

Still some significant unknowns here as we've never done this before, but it does seem fairly straightforward. Can we please get this estimated @kurtisassad and _ideally_ ship for EOW? Or is that too ambitious? Would really like to turn this around for them as they are in holding pattern until we do.

**Comment by mhagel** [comment]
>Spinning up new community not an option:
I asked if i could just spin up a new community howev

It looks like they are concerned about the link changing? commonwealth.im/membrane 

If we delete the community, then re-add it with the same id, the links should stay the same. @markiscommon

**Comment by kurtisassad** [comment]
Yeah I agree with mark here. We just delete the community and make a new one.

If he is worried about the only thread on the community changing:
http://localhost:8080/dydx/discussion/11167-discourse-launch-post-community-vote

We can just add some functionality in the admin panel to change a thread id. In this case it will look like

1. admin panel delete thread
2. Trix creates new cosmos membrane community
3. He creates a thread with the same title as the old thread
4. We use admin panel to change the id to the 11167 (It will have functionality to bump old thread id to a new unused id on conflict)
