### ISSUE TITLE
BUG: User is able to create two accounts with same wallet address

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5818]
## Describe the bug

ENV: QA/Local
BRANCH: Master/v0.8.1

Validation for existing addresses does not work and user can create two profiles with same address. Currently reproduced with Leap wallet. 

Related to: https://github.com/hicommonwealth/commonwealth/issues/5762

## To Reproduce

1. Create fresh wallet address 
2. Go to https://qa.commonwealth.im/
3. Click log in 
4. Create new profile
5. Navigate on default communities
6. Click on Log out
7. In browser navigate to https://qa.commonwealth.im/csdk-beta
8. Click on log in

## Expected behavior

When existing user click log in we should navigate him on dashboard page. Currently user is pointed to create new profile. 

## Additional context

Please see reproduction video:
https://app.screencast.com/nbZyi9bp4MmS8

**Comment by mhagel** [comment]
This is existing behavior, unrelated to Leap. 

It will be resolved by https://github.com/hicommonwealth/commonwealth/issues/5429

**Comment by mw2000** [comment]
@CowMuon looks like it's resolved already by #5429
