### ISSUE TITLE
🪣 Community Stake: Platform Integration

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5826]
## Description

Tracking ticket for the platform-side integration of community stakes.

## Project Owner

Responsible: @Rotorsoft
Accountable: @jnaviask 
Consulted: @timolegros @rbennettcw @ianrowan 
Informed: @dillchen @sachben91 @jessmart1213 

## Model Bridge
[Event Storming](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764568054266249&cot=14)

### Projections
- [x] #5883 

### Commands
- [x] #5894
- [x] #5882
- [x] #5884 

### Policies

- None

### Refactoring Technical Debt
These are the refactoring tickets we are considering as part of the scope:
- [x] #5927 
- [x] #5981 
---

## 12/4: Notes from Scoping Call
Ian:
namespaces:
- frontend: basic information page in CC V2 => namespace field, populated based on community name proposed
  - confirming namespace reservation, at time namespace entered into field (call using helper SDK)
  - on next button, trigger tx to deploy namespace for community => user prompted, then once tx sent, loading state, on completion + success => create community (via normal routes incl namespace detail)
- backend: confirm tx receipt + claiming user match (onchain checks); new column for communities holding the namespace field

configure community stakes:
- frontend: page to enable or not. if they click yes, then using existing namespace we trigger another tx. on success, call new route which says we've created the community stake id with specific details (what token, what scalar, etc)
- backend: either a table with FK to communities, or JSON column on communities to hold stake information (existence of stake info tells rest of flow whether enabled or not) => TBD exactly how
  - upon creation of community stakes, it was proposed we also create an 1155 group out of the box

Tim:
- on upvote route, we check user stake before modifying their weight via TBC
- ensure we use cache refresh so we don't actually cache value and instead cache a fresh value
- buying/selling will only require UI update, nothing needed on our side

Ryan:
- pointing strategy: translates from amt stake to amt upvote => interface IVotingStrategy, calculates voting weight given stake + maybe user-provided parameters if customized on FE, then returns a number
- Dillon: multiplier fine => may be useful to have a complex point strategy, but not within scope

Clarifications TBD

**Comment by dillchen** [comment]
adding #5934 for context here, the design for the autogenerated stakeholder group

**Comment by jnaviask** [comment]
@dillchen is #5934 a requirement for the MVP? or a follow-up?

**Comment by dillchen** [comment]
Some context: We have a design for stakeholder group enablement: 
[@jessmart](https://commonxyz.slack.com/team/U04QV8NURH9) has finished it ([here](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1671-174760&mode=design&t=r2SPqIVi2vu68V0A-4), dev link will be ready tmrw and added to the WIP Ticket)

It wasn’t explicitly requested in the PRD, therefore fast follow -> there will be several of them (how should those be labeled?)

3. I created the WIP in progress ticket there. There was a comment I believe left by [@Ian Rowan](https://commonxyz.slack.com/team/U04T0U795CG) on stakeholder group creation (in Figma / Github and can’t find it) + I think it was mentioned during last design crit
