### ISSUE TITLE
Mobile thread editing issues

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#5833]
## Describe the bug
On a mobile device a user trying to expand the text box during the editing process and lost all editing progress. 

Smaller issue: trying to create a new line of edits on mobile wouldn't work unless there was text in the line. User had to type 'd' or a random letter before creating a new line. 

## To Reproduce
When editing a thread on mobile, Expand the screen and editing progress should be lost and not saved. 

When editing a thread on mobile, hit enter and a no new line will populate. 

## Expected behavior
Editing progress should be saved no matter the view in which text is being edited on mobile. 

A new line should populate whether there is writing in the line or not. 

## Additional context
![image](https://github.com/hicommonwealth/commonwealth/assets/144931524/e67ff88c-1c0b-4f55-a0cc-adf2806e3d4e)

**Comment by CowMuon** [comment]
@zakhap What are the 2 tickets this is split into?

**Comment by CowMuon** [comment]
@mzparacha For estimation. (hold off execution 4 now.)

**Comment by mzparacha** [comment]
> @mzparacha For estimation. (hold off execution 4 now.)

I am not able to replicate this locally
> When editing a thread on mobile, Expand the screen, and editing progress should be lost and not saved.

For initial estimation, looks like a `2`, but can get more.

**Comment by CowMuon** [comment]
@cowballzach We likely will need reporting user's device-os-browser combo. Going forward we should be getting that up front for *all* user reports, but especially for reports that we can't reproduce which are often because of a browser versioning issue (e.g. we're testing in verson 127, but they are using version 119.)

**Comment by cowballzach** [comment]
understood, will ask for that moving forward. What is the easiest way to explain to them how to find what version of chrome they are using?

**Comment by CowMuon** [comment]
My suggestion is make requesting browser version conditional on device = desktop. That is, NOT device = mobile.

Getting their browser version on Desktop is as easy as clicking the app name in the menu bar >> about [app] , or equally easy for Windows peops. 

On the mobile side, getting your version number is more annoying (deeper nested) but really that's part of the bargain for OS providers (of which there are really only 2 rn) offering somewhat stronger assurances of consistent behavior across var. version combos.) 

All that being said, if they're on mobile, it's the device and os version that is much more important. if they're on desktop it's super easy for them to find that.

**Comment by cowballzach** [comment]
Malik and I were unable to recreate on mobile, safari, chrome. We can archive archive for now and reopen if the user reaches out again.
