### ISSUE TITLE
BUG: User can't edit Thread name

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5836]
## Describe the bug

ENV: QA
Branch: v0.8.2/Master

When user tries to edit Thread name, input filed is disabled
## To Reproduce

1. Go to: https://qa.commonwealth.im/
2. Sign in
3. Create some thread
4. On thread details page click on three dots (...) and try to edit Thread name
## Expected behavior

Since user has created thread, user should be able to edit thread name. 
## Additional context

Video:
https://app.screencast.com/oqrkMgJEo3Ref

**Comment by CowMuon** [comment]
Grab-n-go for either ZachLee or Malik (or anyone.) 

Marking as high-priority as it is a regression in the `v0.8.2` release which we would like to ship today.
