### ISSUE TITLE
BUG: Input field is disabled on magic link login form

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5840]
## Describe the bug

**ENV**: QA
**Branch**: v0.8.2/Master

When user tries to type email address in magic link input field, field is disabled. 

## To Reproduce

1. Go to https://qa.commonwealth.im/
2. Click on Login
3. On login form click on 'Sign in with another email address`
4. Try to type email address 

## Expected behavior

Email address input field should work and accept input text. 

## Additional context

Video:
https://app.screencast.com/ZvjqyuQvP1iqn

**Comment by CowMuon** [comment]
Noted as high-priority, as it is a **regression** that is a release blocker on [v0.8.2](https://github.com/hicommonwealth/commonwealth/releases/tag/v0.8.2)
