### ISSUE TITLE
DS: Remove legacy log-in button

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5864]
## Current Behaviour
Design System currently has both old/legacy "log in" button as well as our current "sign in" button. 

## Expected Behaviour
Design System only contains current sign-in button, not old buttons we do not use. 

## Additional context
#5862 is the related story for executing button cleanup across the app.

**Comment by Israellund** [comment]
I was mistaken, the old/legacy 'log in' button is not in the design system according to [this Notion doc](https://www.notion.so/buildcommon/Design-System-Component-Progress-Tracker-c52e0e9e044a4bc495acd0e95c9eaa0c) The previous "Login" button label has been changed to "Sign in" and both "Sign in" buttons are now using the `CWButton` component from `new_designs`. Those changes can be seen in [PR #6093](https://github.com/hicommonwealth/commonwealth/pull/6093)
