### ISSUE TITLE
Unable to Search within a Community (p3)

### ISSUE THREAD

**Issue by RhysCommonwealth** [hicommonwealth/commonwealth#5866]
## Describe the bug
Searches within a community (with the community tag within the search bar) shows all results across the site. Search preview (before pressing enter) and the search page (after pressing enter) both are global searches. 

Communities are also showing as "undefined" in both "within community" searches and searching across all communities
<img width="817" alt="Screenshot 2023-12-05 at 5 48 15 PM" src="https://github.com/hicommonwealth/commonwealth/assets/88511608/e9de7a80-d885-4606-94e8-719b41157ce5">

## To Reproduce
Search anything _within_ a community

## Expected behavior
If selected, searches should only show results within the chosen community.

Community names should show up in the search results rather than "undefined"

## Additional context
https://www.loom.com/share/b419fa5c59b8416caf01039c8cc3dc1a

**Comment by CowMuon** [comment]
Product roadmap question here: Please confirm working assumption that users will want to have global search preserved as an option, not the default. (ie, a checkbox that says "Search _all_ communities on Common" either in the current scope, or as a FF @zakhap 

ENG question: Given that we already have global search, please confirm LOE for preserving that behind said checkbox (as opposed to total do-dover that does not preserve a global search option) @Miaplacidus

**Comment by Miaplacidus** [comment]
@CowMuon 
Pardon the delay in the effort estimation. Will take that on on Monday.

**Comment by CowMuon** [comment]
@Miaplacidus Thanks for the update and no worries, Monday is fine. Have a great weekend!

**Comment by Miaplacidus** [comment]
@CowMuon 
In regards to your question as to the level of effort required to put the global search behind a checkbox, I'm thinking that's a 1-2 pointer. 

However, I don't think that would necessarily be visually pleasing. In addition, I think a global search is implied by removing the chain tag sitting at the left of the search bar input. That would make a checkbox feel redundant.

**Comment by jessmart1213** [comment]
@Miaplacidus  cc @CowMuon 

> However, I don't think that would necessarily be visually pleasing. In addition, I think a global search is implied by removing the chain tag sitting at the left of the search bar input. That would make a checkbox feel redundant.

The above is correct. When the community tag is present within the search bar the results shown should be community specific. 
<img width="658" alt="Screen Shot 2023-12-11 at 2 01 24 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/274cc141-1784-4a47-bcb1-b3207d9a16db">


When the community tag is removed then the results are global.
<img width="676" alt="Screen Shot 2023-12-11 at 2 01 43 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/1afc1fa1-002a-4696-9a2e-34eb96f5b165">

There should be no need for an additional checkbox.

**Comment by Miaplacidus** [comment]
Thanks for the clarification!

**Comment by Miaplacidus** [comment]
@ForestMars @jnaviask 
Was hoping this was a straightforward missing chain attribute kind of bug. That doesn't appear to be the case. Might have to do some digging into SQL. Hence, I'm updating the point estimate.

**Comment by Miaplacidus** [comment]
@ForestMars @jessmart1213 
I've fixed the bugs described above and will release a PR in a bit.

However, it turns out, that the way search is described above, is not the way it actually works. Removing the community tag does not result in a global search. To get a global search, you have to be on a page that isn't associated with any community. 

We should create a separate ticket that makes the search global when the tag is removed.

**Comment by RhysCommonwealth** [comment]
> @ForestMars @jessmart1213 I've fixed the bugs described above and will release a PR in a bit.
> 
> However, it turns out, that the way search is described above, is not the way it actually works. Removing the community tag does not result in a global search. To get a global search, you have to be on a page that isn't associated with any community.
> 
> We should create a separate ticket that makes the search global when the tag is removed.

the community name showing up instead of 'undefined' should also be addressed. https://www.loom.com/share/7628a8570fdb4221a840965e1d2f898d

**Comment by Miaplacidus** [comment]
Hey, @RhysCommonwealth! The "undefined" bug was also addressed in the fix.
