### ISSUE TITLE
🪣 Community Stake: Product Integration

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5870]
## Description

Read more about Community Stakes here

Users creating a new community will now have the option to enable Community Stakes within the community they create during the create community flow. This will be the third step in the new create community flow. **Only users who have an Ethereum wallet will be able to enable Community Stakes. Users who select other wallets (such as Keplr or Phantom), will not be shown the option to enable Stakes** 

Users who enable Community Stakes must register their ENS namespace within Common (their .common address). When users enable Community Stakes, two transactions will take place, both with their associated gas fee. These transactions are: 
- namespace registration 
- Enabling Community Stakes 

Since, there is a chance that the transactions associated with Community Stakes might fail, it is important that the Community that the user creates is deployed before the transactions happen. The new community that the user creates should be deployed when the user clicks on the CTA "launch community" at the end of the second step (basic information page). 

[This Figjam ](https://www.figma.com/file/LzDHu1mIJIpB26c9IqyN4S/Create-Community-Process?type=whiteboard&node-id=0%3A1&t=77w7DqfYJ48sW6gb-1)gives an overview of the flow for enabling community stakes 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/b96e9d08-de04-4414-9498-7f155f0978ce)

## Project Owner 
PM for create community/enabling stakes questions: Sachin Benny
PM for protocol/Community Stakes related questions: Dillon 
Designer: Jared Bell 

## Product Specs 

Enabling Community Stakes will have a new screen and two separate steps within that new screen. First step is for the user to opt in or out of stakes and the second step is to sign two transactions if they have opted into Community Stakes

- https://github.com/hicommonwealth/commonwealth/issues/5878 
- https://github.com/hicommonwealth/commonwealth/issues/5905

**Comment by masvelio** [comment]
@sachben91 Questions
1. > Users who select other wallets (such as Keplr or Phantom), will not be shown the option to enable Stakes

Does it mean that Third step will be not visible whatsoever (image below) and after completing step 2 (the form), user gets redirected to "your community is live" page?
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/0586e5a8-6b97-4633-af01-c1d36aaad1b0)


2. Can we clarify this? Description says:

> Only users who have an Ethereum wallet will be able to enable Community Stakes.

However on [figjam](https://www.figma.com/file/LzDHu1mIJIpB26c9IqyN4S/Create-Community-Process?type=whiteboard&node-id=0-1&t=ndVzJbxa0zcKquJ4-0) it says Ethereum-Mainnet. Do we want to enable Community Stake for every EVM based community (including "polygon") or only EVM community that selected Ethereum-Mainnet from the "Select your chain" dropdown in step 2 form?
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/078b8dd6-f2b5-4918-842d-5d4f9c85b1ed)

3. Currently we work on v1 of create-community and we don't have `tags` in second step form. [In the designs](https://www.figma.com/file/WLN4nRpVGQJ9AjuxiJwuDS/Create-Community?type=design&node-id=610%3A31536&mode=dev) for second phase I can see those tags in second step. In this case we need additional ticket for adding the tags.
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/71a2d94f-8eaa-4ad2-b95f-ab3d197e4287)

**Comment by sachben91** [comment]
> @sachben91 Questions
> 
> 1. > Users who select other wallets (such as Keplr or Phantom), will not be shown the option to enable Stakes
> 
> Does it mean that Third step will be not visible whatsoever (image below) and after completing step 2 (the form), user gets redirected to "your community is live" page? ![image](https://private-user-images.githubusercontent.com/14819225/289067903-0586e5a8-6b97-4633-af01-c1d36aaad1b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDgwOTksIm5iZiI6MTcwMjA0Nzc5OSwicGF0aCI6Ii8xNDgxOTIyNS8yODkwNjc5MDMtMDU4NmU1YTgtNmI5Ny00NjMzLWFmMDEtYzFkMzZhYWFkMWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE1MDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMmEzMmE3ZTAwYTUyNTM2NTc3MmY1YTVjNGUxNDI3Yjg5YjBkYzRhNGVkYTQ2OGE2YTFlNWRhNGI4NGVjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CZSiPjlvH94FlFC9nkYIbA5iEzU5xbwzgoVKWZ84XVM)

yes, third step will not visible to non-Ethereum wallets. They should be directed to the community is live screen 
> 2. Can we clarify this? Description says:
> 
> > Only users who have an Ethereum wallet will be able to enable Community Stakes.
> 
> However on [figjam](https://www.figma.com/file/LzDHu1mIJIpB26c9IqyN4S/Create-Community-Process?type=whiteboard&node-id=0-1&t=ndVzJbxa0zcKquJ4-0) it says Ethereum-Mainnet. Do we want to enable Community Stake for every EVM based community (including "polygon") or only EVM community that selected Ethereum-Mainnet from the "Select your chain" dropdown in step 2 form? ![image](https://private-user-images.githubusercontent.com/14819225/289069390-078b8dd6-f2b5-4918-842d-5d4f9c85b1ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDgwOTksIm5iZiI6MTcwMjA0Nzc5OSwicGF0aCI6Ii8xNDgxOTIyNS8yODkwNjkzOTAtMDc4YjhkZDYtZjJiNS00OTE4LTg0MmQtNWQ0ZjljODViMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE1MDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMjNiODI1OGZiZDI0MjRiMjJkMGMyMzBjZGQyZjkzZTllYTljMGI1OWIxM2QwOTZiZjMwZDA5ODRhZGE4ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKRDoHhXF9tSIsM6oyl28ht9trznYXp1dcsJOSi-Edg)
- It wont be for all EVM, it will just be for communities who have selected ethereum mainnet from the drop down
> 3. Currently we work on v1 of create-community and we don't have `tags` in second step form. [In the designs](https://www.figma.com/file/WLN4nRpVGQJ9AjuxiJwuDS/Create-Community?type=design&node-id=610%3A31536&mode=dev) for second phase I can see those tags in second step. In this case we need additional ticket for adding the tags.
>    ![image](https://private-user-images.githubusercontent.com/14819225/289070893-71a2d94f-8eaa-4ad2-b95f-ab3d197e4287.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDgwOTksIm5iZiI6MTcwMjA0Nzc5OSwicGF0aCI6Ii8xNDgxOTIyNS8yODkwNzA4OTMtNzFhMmQ5NGYtOGVhYS00YWQyLWI5NWYtYWIzZDE5N2U0Mjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE1MDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NTJjODcxN2JhMmI0NjIyNWUwYzVlODUyMDhhODZhYmFkNWNjZmYzMDM1OWVkOTBjN2Y2ODQ0NjM3YjgyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kIa3KHC68rQFkVZ_TuyOnWg8_BsQ72sfr_Mo-CgrCyk)

- We wont be doing tags, we explored that design but since the create community flow has already become complex, we will remove that from the flow. It will reflect in the design
