### ISSUE TITLE
Update Farcaster Bot Queue Config

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5876]
## Describe the bug

https://github.com/hicommonwealth/commonwealth/pull/4740 updated the RabbitMQ configuration so that each Heroku app only defines the minimal subset of the RabbitMQ configuration that it needs. For example, this means that if we deleted all queues and then only turned on the snapshot bot, only snapshot-related queues would be created.

Unfortunately, the farcaster bot was not updated with this change so the existing farcaster bot is recreating unused queues (such as those for the old ChainEvents app).

To resolve this do the following:
- [ ] Create a new value in the `RascalConfigServices` enum for the farcaster bot
- [ ] Modify objects in `rascalConfig.ts` to add the required RabbitMQ components for farcaster bot (e.g. add an exchange, queue, subscriptions/publications).
- [ ] In `common-common/src/rabbitmq/rabbitMQConfig.ts` add a new condition to create the minimal RabbitMQ config using the configuration options created in the previous step
- [ ] When creating the RabbitMQ controller instance in the farcaster bot, pass in the URI and the new enum value you created in the first step in order to initialize the controller with the correct minimal RabbitMQ configuration.

**Comment by CowMuon** [comment]
What's our change management solution WRT supported bots? (That _should_ be indicated in the technical specification.) TBH when I see things like this I am tempted to add a #BrentEffect label to our GH.
