### ISSUE TITLE
Update RabbitMQ Server Version

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5877]
## Describe the bug

We are running an older version of RabbitMQ that CloudAMQP no longer supports. We should update to the latest version of RabbitMQ from the CloudAMQP dashboard accessible from the Heroku Resouces tab.

**Comment by timolegros** [comment]
To upgrade in production:
1. Shutdown the message relayer, commonwealth consumer, and Knock worker
2. Put the Discord bot app in maintenance mode
4. Upgrade Erlang and RabbitMQ from the management panel (may need to upgrade multiple times)
  - Update to at least RabbitMQ v3.12.12 and Erlang v25.3.2.7 (running and confirmed working on Frick)
6.  Turn the workers and app back on in any order

**Comment by jnaviask** [comment]
Sounds good, execute whenever.

**Comment by timolegros** [comment]
Executed.
