### ISSUE TITLE
Integrate Mava Chat Widget on Demo Environment

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5880]
## Description

Growth + Product want to test out a Comms + Feedback widget called Mava within the context of Common. We will want to test it for a few days to see if it satisfies our needs (managing feedback and bug reports from users). 
**Testing will be done in our demo environment.** 

[Mava's official installation instructions are here](https://mava-app.notion.site/Integration-Set-Up-Web-Chat-Mava-96f90f0b73474e6eb228ce83dd0fd032).

Installation TLDR:
- Add script to head on all pages. 

Below is the code that they generated for our use:
```
<!-- Mava Widget -->
<script defer src="https://widget.mava.app" id="MavaWebChat" data-token="(pls-dont-leak-access-tokens)"></script>
```

## Project Owner

@zakhap + @RhysCommonwealth 

## Engineering Requirements

TBD

## Acceptance Criteria

- Mava widget is available for Growth and Product to test on our Demo environment.

## Additional context

- If it passes our testing usage, we plan on rolling this out to all users. It may be useful to have this feature behind a feature flag for custom domains, unsure of its impact at this time.
- We want to be able to maybe release this before the code-freeze, given Growth + Product team demo approval

**Comment by jnaviask** [comment]
Duplicate
