### ISSUE TITLE
Setup Datadog Alerts

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5881]
## Description

We have a ton of useful metrics on Datadog but it is only utilized when we manually check the dashboard. To catch issues earlier on, we should set up email and Slack alerts for various outlier metrics that indicate that there is a problem.

## Project Owner

@timolegros

## Engineering Requirements

Set up alerts for the following:
- Postgres
  - Abnormally low Postgres cache hit rate
  - Abnormally large Postgres index size
  - Nearing maximum PostgreSQL storage limit
  - Using all (or nearly all) available PostgreSQL connections (100% connection usage)
- Redis
  - Nearing maximum Redis memory usage
  - Abnormally high Redis ping latency
  - Using all (or nearly all) available Redis connections (100% connection usage)
- RabbitMQ
  - Any message in the RabbitMQ DeadLetter queue
  - High RabbitMQ latency or low throughput
  - Nearing maximum RabbitMQ queue length
  - Nearing maximum RabbitMQ memory usage
- Dynos
  - Nearing maximum dyno memory usage
  - Nearing maximum dyno CPU usage

**Comment by jnaviask** [comment]
cc @rbennettcw who worked on similar stuff

**Comment by timolegros** [comment]
Not very difficult but bumping to 2 points since it is quite tedious. Datadog does not make creating simple metric monitors as easy as I thought.

**Comment by timolegros** [comment]
Created monitors for all of the metrics listed above except the following:
- Abnormally low Postgres cache hit rate
- Abnormally large Postgres index size
- High RabbitMQ latency or low throughput
- Nearing maximum RabbitMQ memory usage

The postgres monitors can't be created because we don't have the associated metrics yet. These will be created when the need arises. As it stands our database is still very small/performant (and is still shrinking with clean-ups + refactorings). The RabbitMQ monitors are simply unnecessary at this point since our current usage is so far below the plan maximum and our RabbitMQ usage does not scale linearly with users.
