### ISSUE TITLE
Weighted Reactions on Content

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#5883]
# Description
Reflects community stake weights in content (threads, comments) after user reactions. 

## Context

Currently, threads and comments contain a `reaction_count` property, which is a cache of the number of reactions for that content– intended to improve performance for thread/comment queries.

It uses Sequelize hooks to update the `reaction_count` property on threads/comments whenever a reaction is created or deleted. See the `afterCreate` and `afterDestroy` hooks in the `reaction.ts` model file. A new `reaction_weights_sum` property will be added to threads/comments, which updates via same mechanism as `reaction_count`.

## Stakeholders
| Product   | Engineering |
| --------- | ----------- |
|     | @rbennettcw        |

## Model

https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764572225232598&cot=14

### Projector

_How to reflect/persist what just happened in a read model_

1. **Projection Schema** - Use [zod](http://zod.dev)
    ```ts
    z.object({
      ...existing reaction data,
      reaction_count: z.number(),
      reaction_weights_sum: z.number() // new
    })
    ```
2. **Projection Rules**
    ```ts
    // afterCreate
    const balance = getBalanceForAddress(address, contractAddress, tokenId)
    const stakeWeight = community.stakeWeight
    const reactionWeight = balance * stakeWeight

    // afterDestroy
    const reactionWeight = reaction.calculated_voting_weight // see #5894 (React on Content)
    ```
3. **Persistence**

    - Add `reaction_weights_sum` (number, nullable) column to `Threads` and `Comments` tables

    - Hook DB operations should pass `options.transaction` as the transaction to make the operation ACID - see https://sequelize.org/docs/v6/other-topics/hooks/#hooks-and-transactions

    ```ts
    // entity is Thread or Comment

    // afterCreate hook
    entity.increment('reaction_weights_sum', reactionWeight)

    // afterDestroy hook
    entity.decrement('reaction_weights_sum', reactionWeight)
    ```

### Query

_How to query the projection (read model, materialized view)_

1. **Authorization**
   - Anyone, public
     - `validateCommunity` middleware to attach Community to request context
2. **Routing**
  - `GET /threads?bulk=true` (getBulkThreads)
  - `GET /viewComments`
3. **Query Filters**
  - Query param: `thread_id` for getBulkThreads route
5. **Response**
  ```ts
  {
    ...existing data,
    reactionWeightsSum: number
  }
  ```
## Unit Testing
- GIVEN a thread with community staking enabled, WHEN thread is queried via bulk threads route, THEN expect response to include `reaction_weights_sum` property
- GIVEN a comment with community staking enabled, WHEN comment is queried via view comments route, THEN expect response to include `reaction_weights_sum` property
- GIVEN a content with community staking enabled, WHEN a reaction is created on content, THEN expect content `reaction_weights_sum` to increment by the weight of the reaction
- GIVEN a content with community staking enabled, WHEN a reaction is deleted on content, THEN expect content `reaction_weights_sum` to decrement by the weight of the reaction

## Additional Context
N/A

**Comment by jnaviask** [comment]
Few questions for @rbennettcw and @Rotorsoft:
- Is it `postDelete` or `postDestroy`?
- We're using `const stakeWeight = community.stakeWeight` for both create and delete -- what happens if a user's stakeWeight changes between when the reaction was made and the present?

Otherwise, LGTM

**Comment by rbennettcw** [comment]
@jnaviask I've correct the terminology it's `afterCreate` and `afterDestroy`. Also addressed the issue with afterDestroy– it should use the reaction's `calculated_voting_weight` and not the community stakeWeight.

#5894 is a prerequisite for this ticket
