### ISSUE TITLE
Set Community Stake

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#5884]
# Description
Links community with a namespace to the Stake contract

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
|      | @kurtisassad        |

## Model
https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764572069863637&cot=14

## Engineering Requirements
1. **Authorization**
   - Admin of community
2. **Message Schemas** - Use [zod](http://zod.dev)
   The body of the message will include the following stake details:
```typescript
z.object({
   stakeId: z.number(),
   stakeToken: z.number().optional(),
   stakeScaler: z.number().optional(),
   stakeEnabled: z.boolean(),
 })
```

And will be inserted into a new table which we will write the migration for:
   ```
   CREATE TABLE CommunityStakes (
      id INT PRIMARY KEY,
      community_id INT,
      stake_token NUMERIC,
      stake_scaler NUMERIC,
      stake_enabled BOOLEAN,
    FOREIGN KEY (community_id) REFERENCES "Communities"(id)
);
   ```
3. **Routing**
   - PATCH /communities/:id
4. **Loading Aggregate**
   - `const community = await this.models.Community.findOne({ where: { id: id } });`
5. **Business Rules** 

  Condition | Error
  --------- | ----
  community !== null | InvalidInput("Community not found")
  on-chain validate namespace exists on community | InvalidState("Community missing namespace")

  For on-chain validation call result of: https://github.com/hicommonwealth/commonwealth/issues/6019

6. **Mutations**
   - `community.stake = body`
7. **Persistence** >>> @kurtisassad describe changes to db schema (json field or new table), migration, etc
   
   - schema changes
   ```typescript
        z.object({
          stakeId: z.number(),
          stakeToken: z.number().optional(),
          stakeScaler: z.number().optional(),
          stakeEnabled: z.boolean(),
         })
   ```
   - `await chain.save();`
9. **Events**
   - N/A
10. **Responses**
- response body: Updated community, status code: 200
- `success(res, updatedCommunity)`

## Unit Testing 
- GIVEN existing community, WHEN set community stake command invoked, THEN expect success
- GIVEN non-existing community, WHEN set community stake command invoked, THEN expect failure
- GIVEN namespace not belonging to user, WHEN set community stake command invoked, THEN expect failure

**Comment by jnaviask** [comment]
Similar to [my question](https://github.com/hicommonwealth/commonwealth/issues/5882#issuecomment-1852925242) on #5882, how will we confirm on the platform side that the provided community stakes contract is deployed + correct in relation to the namespace? cc @kurtisassad @Rotorsoft @ianrowan

**Comment by ianrowan** [comment]
#6019 created for the onchain validation

**Comment by kurtisassad** [comment]
A little bit unsure how we want the schema here. Ideally we add a new table "CommunityStakes" to hold Community Stake references to the community. But we have been going for more nosql type jsonb values recently.

Anyways I will do the natural relational way for now. If we decide against it I will change the ticket.

**Comment by jnaviask** [comment]
Thanks @kurtisassad -- last Q, can you add a point estimate?
