### ISSUE TITLE
Mixpanel: Community Stake (backend)

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#5885]
We could like to log data in Mixpanel for when a user interacts with Community Stakes. 

List of Events we care about: 
- Successful ~~Buy~~ (Mint) Events (community, user id, address, amount purchased, total amount held)
- Successful ~~Sell~~ (Burn) Events (community, user id, address, amount sold, amount still held)
- Failed OnChain Transactions (community, user id, address, reason: { insufficient gas, not enough funds, ...})

**Comment by dillchen** [comment]
We'll never touch the backend, following from domain model we will have to record these events on the front end
