### ISSUE TITLE
Mixpanel: Community Stake (front-end)

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#5886]
## Description

We will want to track the growth of communities with Community Stake feature enabled. Additionally  the growth rate of communities using community stake is trackable in mixpanel. This is both the users joining communities with stake activated and the overall population of communities with stake activated.

We could like to log data in Mixpanel for when a user interacts with Community Stakes.

## Project Owner
@HIM92 (Harris Innes-Miller)

## Engineering Considerations
- A new property for Community Stake being enabled for tracking the community.
- The log should include the community id and user id (and user active address).

## Acceptance Criteria

Implement the Following Events

**Admin Configuration Events (blocked by Admin Onboarding Milestone)**
- [x] Admin Enables Stake (via Admin Panel) Blocker #5878 
- [x] Admin Enables Stake (via Community Create) Blocker: #5905

**User Mgmt Events (not blocked)** -> moved into this ticket: https://github.com/hicommonwealth/commonwealth/issues/6734
- [ ] 'Buy stake' button in the `CWCommunityStakeBanner` is clicked.
- [ ] 'Manage Stake in the sidebar `StakeSidebarModule` is clicked

**On the Manage Stake Page (blocked by implementation of Manage Stake Modal)**
- [ ] Successful Buy (Mint) Events (community, user id, address, amount purchased, total amount held)
- [ ] Successful Sell (Burn) Events (community, user id, address, amount sold, amount still held)
- [ ] Failed OnChain Transactions (community, user id, address, reason: { insufficient gas, not enough funds, ...})

## Additional context
I want to be able to track the number of communities that are created with community stake activated. Additionally, I want to track the number of new users who sign up and join community a community that has stake activated on it.
----
These are all blocked until the requisite front end flows are implemented

-----
Adding in context from #5997 on desired implementation (that ticket might be worth closing)

**Comment by dillchen** [comment]
CC: @ForestMars and @jnaviask for context on this ticket, it may be best to pull from the backlog and or have @Miaplacidus also work on "unblocking tickets"

**Comment by CowMuon** [comment]
Ifu's plate is pretty full rn, tossing this over to @Israellund

**Comment by HIM92** [comment]
toss away

**Comment by CowMuon** [comment]
This should go into `0.9.5` going to QA on 2/8 and shipping to production on 2/12.

**Comment by CowMuon** [comment]
@Israellund Can you please add a comment why this is blocked, and which issue # is blocking it? kudasai

**Comment by dillchen** [comment]
I think this should be unblocked now, we previously had it marked blocked
because it was waiting on front end implementation

Sent via Superhuman ***@***.***>

**Comment by Israellund** [comment]
@CowMuon @dillchen I had a conversation with Marcin last Thursday and he said that is is still blocked as enabling stake in admin capabilities will be finished in v2. There is still nowhere on the Integrations screen to enable stake. 
![screen_shot_2024-02-07_at_1 18 39_pm_720](https://github.com/hicommonwealth/commonwealth/assets/69872984/e8099548-e71a-497e-a762-4f57acb232c2)
<img width="750" alt="Screenshot 2024-02-13 at 2 05 05 PM" src="https://github.com/hicommonwealth/commonwealth/assets/69872984/a9022179-eec3-43a3-ba12-de54abe9df11">

**Comment by HIM92** [comment]
@Israellund just so you can see it here is the stake enablement ticket: https://github.com/hicommonwealth/commonwealth/issues/6686

**Comment by Israellund** [comment]
@HIM92 Okay great, thank you

**Comment by HIM92** [comment]
Split into this ticket: https://github.com/hicommonwealth/commonwealth/issues/6734 @Israellund
