### ISSUE TITLE
Review emails

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#590]
Suggested process below.

This is probably best tracked in a Google spreadsheet:

- [ ] Create a list of all email sending calls from Commonwealth
- [ ] For each email, map it to each context where the email might be sent. For example, the address confirmation email might be used in 3 or 4 different places
- [ ] Go through the necessary steps to cause an email to be sent for each context
- [ ] Inspect each email and verify that it makes sense in the context that it was received in. Make a note of any emails that are out of place, missing data, or even just worth a second look, and I can review those.

Actually fixing any broken emails could happen during this review (if so, just start a branch and send a PR) or it could happen afterwards - it should be quick as long as we have the full list of emails and when they might be sent.

**Comment by raykyri** [comment]
@dillchen How did this go?

**Comment by dillchen** [comment]
My review is done. I was able to verify that all email notifications triggered appropriately (including chain notifications).

With the exception of chain notification email styling with work in #622 (More legible chain notifications), I don't think there are email specific changes that need to be made.

Made styling changes to several templates. I kept notes [in Evernote](https://www.evernote.com/l/AQ2pYcOWWN5OcbWyOfILOEi-UlKCK44NusU)

Notes copied below. There are three changes that should be implemented of which #622 is one of them. The other two are design or subscription related.

> 1. Login Button from top right (previously logged in) => send confirmation vs login?
> * Email Sent
> * Proper Email
> 2. Login Button from top right (creating new account)
> * Email Sent
> * Proper Email
> 3. Update Email Route => Clicked on 
> * Email Sent
> * Proper Email
>     * Updated the SendGrid Email to show Notification Body
>     * Updated Link to work
>     * Updated Styling for footer
> 4. Create Email Invite
> * Triggers
>     * New Thread (yes)
>     * New Comment (yes)
>     * New Mention (yes)
>     * New Link Thread (yes)
>     * New Reaction??? (none necessary)
> * Proper Email
>     * Update the SendGrid Email to show Notification Body
>     * Update Link to work
>     * Update Styling for footer
> 
> 5. Email Notification from Chain Events
> * **Update in server/scripts/emails.ts in #622 (immediate)**
>     * Should be fixed...
>         * Sends, but Malformatted
>         * Need to fix formatting
>         * Look at subscription email...
>     * Some ChainNotificationEvents don’t have a link to something useful on CW (yet)
>         * Mostly validator events
> * **Kusama Validator Events is Dangerous (many emails where all validators are notified if subscribed) (Later)**
> * **Chain Events Notification Page should be more descriptive (Later)**
>     * We removed the listing of all the specific events + frequency

**Comment by raykyri** [comment]
Great! Thanks for the update.

Everything looked okay in my pass - I made a couple of very minor copy edits to the signup email, but it looks like your pass caught everything basically. Immediate emails are turned off for all subscriptions right now so it's up to us to figure out how to turn those on when the time comes.

**Comment by raykyri** [comment]
I think we can close this now that #622 is active.
