### ISSUE TITLE
Allow Markdown in Topic Descriptions

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5900]
## Original Description

Right now, users can put links into their topic descriptions. These links render as plain text and not as clickable hyperlinks. We want urls put in topic descriptions to be rendered as links. 

**This was a direct request from a community admin.**

## Additional Details
We want to allow admins to use Markdown in topic descriptions. 
This means
1. Replacing the text input on the Admin Capabilities Topics page (`/manage/topics`) with the Quill editor (or our new editor)
2. Rendering the topic description using our markdown renderer on our topic pages (`/discussions/topic_name`). 

In addition, we'd like to add a 250 character limit to topic descriptions. 

See discussion below for reference to when decisions around topic descriptions were made. 

## Project Owner

@zakhap 

## Acceptance Criteria

- [ ] URLs placed in Topic Descriptions should render as clickable hyperlinks.
- [ ] Validation for 250 character limit

**Comment by Miaplacidus** [comment]
@zakhap @Israellund @jnaviask @jessmart1213 @jabell88

To solve the issue of clickable links, I'm rendering topic descriptions using our markdown parser. The result is that a user can use a markdown-syntax link or an HTML anchor tag in topic descriptions. I know we've had previous concerns around users inputing HTML (on a related note, users cannot use anchor tags in threads. Not sure yet why HTML links are allowed in the topic description). The first question here is: do we want to limit the user to markdown links? Also, should we add some visual indicator (such as a tooltip on the topic creation page, for instance) to let the user know that they can use markdown in the topic descriptions?

**Comment by jabell88** [comment]
@Miaplacidus Would it make sense to swap the text input with the markdown editor, or do we not want to give them all the formatting options?

**Comment by jnaviask** [comment]
I'm in favor of using markdown editor for topic descriptions. Would like approval from @zakhap though, as it is a product decision.

**Comment by Miaplacidus** [comment]
@jabell88 
Initially, I felt that would be overkill, but if you're going to allow links, you may as well allow other markdown elements. I'd say, however, that maybe we need an explicit character limit (if we don't already have one) on descriptions so they don't get out of hand.

**Comment by zakhap** [comment]
I think the formatting options of the markdown editor is good.  The character limit also makes sense in this case.
