### ISSUE TITLE
[Spike]: Enabling Metatransactions (Common paying Gas onbehalf of users) - 3 Hours

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5902]
## Description

Gas is expensive onchain, a blocker for making namespace and or stake enablement. For example it cost $50 (as of last week) to launch a new SAFE / Party. We want to find one that's:

1. Easy to integrate (from a dev ex perspective)
3. Works across EVM networks (with required support on Mainnet, and current L2s--Base, OP, Arbitrum at minimum)

There are 3rd party providers
1. https://thirdweb.com/sponsored-transactions
2. https://magic.link/docs/wallets/enterprise-features/gas-subsidy
4. https://www.gelato.network/relay

References: https://docs.openzeppelin.com/learn/sending-gasless-transactions

## Project Owner
PM: @dillchen 

## Engineering Requirements
- 3 Hours

## Acceptance Criteria
- A solutions doc that compares several options
- Rough bullet point for implementation - T Shirt Size Estimation of difficult

## Additional context
- Product should and will provide separate estimation on the value of adding these set of features as well. At current, it helps with web2 entry. (Gas is unfamiliar to mainstream)

Possible for @egetekiner to research this?

**Comment by egetekiner** [comment]
I just finished my research about metatransactions.

You can find the full report here:
https://docs.google.com/document/d/1kjWjshZmsCGwjn6a3H1t5ndXGsiB-91bLTfBMUyEUFo/edit?usp=sharing

I also would like to share my observations for quick reading:

- **Engineering cost of implementation (Protocol side)**: Low
- **Possible value will be added to our platform:** High -> We can increase user engagement and also allow new communities to join effortlessly.
- **Possible further implementations**:
    - We can integrate user voting mechanism in a way we discussed in the [Spike #6017](https://github.com/hicommonwealth/commonwealth/issues/6017) via meta transactions.
    - We can also integrate voting and proposal creation processes with the CommunityStakes contract and allow users to pay for transactions with communityStakes tokens while community admins pay for the transactions. 

Finally, you can find a screencast of an example transaction process of a meta transaction:
[Metatransaction_Screen Recording 2024-01-09 at 2.45.45 PM.mov](https://drive.google.com/file/d/1cJp-FYJKuo-tXTuGnhFjKApSzzmnQPr2/view?usp=sharing)

**Comment by dillchen** [comment]
@egetekiner I've gone through the report and it looks great. I just want to follow up here. Could you also look at it from the Product Eng side as well or is that inclusive of your estimate above.

And as a follow up, I see the implementation notes which serve as good constraints and design decisions, but could you revise it such that we have a small "tech spec" just bullet points on how implementation would go

**Comment by egetekiner** [comment]
For me to be able to make a good product engineering estimate, we need to decide what kind of ruleset we will set up for our services. But I would like to propose several scenarios here:

1) We will provide gas sponsorship for specific transactions coming from everybody.
- Overall: Low workload
- Detailed: The product engineering team will need to change the forwarding of the transaction button. For example, if we will be a gas sponsor to create NameSpace for everyone, the product engineering team will change the button forwarding to meta transaction creation flow prepared by the Protocol team and they will also check the transaction finalization via our special endpoint.

2) We will provide gas sponsorship for whitelisted addresses:
- Overall: Low workload
- Detailed: In that case, the product team will need to check the address to see if it is whitelisted by our metatransaction contract. If it is not, forward the user to our existing NameSpace creation flow to create a community. 

We can expand the scenarios as follows for the specific usecases requested in this spike.

So, the general workload will be on the protocol team for the implementation. As the protocol team we will:
1) Design and implement smart contracts
2) Create the funding scheme to be sure, our relayers always have enough fund
3) Decide, how we will protect the private keys of our vaults (HSm modules, multisig, etc.)
4) Design helpers for the product team:
    - Get Whitelisted addresses / Check address
    - Get Whitelisted functions
    - Send metadata
    - Return transaction hash for the metadata transaction

I hope this helps and provides more context about the overall implementation process. I can also work on special usecase analysis for more detailed scenarios of voting and using ERC 1155 CommunityStakes tokens as the payment model in exchange for gas sponsorhip.

**Comment by dillchen** [comment]
This is great, are there 3rd party meta transaction services you would
recommend so that we don’t not have to roll our own?

Sent via Superhuman iOS ***@***.***>

**Comment by dillchen** [comment]
And last, I believe we should get reviews from the product team on this

Sent via Superhuman iOS ***@***.***>

**Comment by egetekiner** [comment]
I would like to add some more updates and teed up the discussion points we talked about.

Decision-Making Phase:

**Stakeholder Alignment:** A collaborative session with management, product, and protocol teams will be needed to finalize the types of transactions eligible for gas sponsorship, and our plans for this project. This will also cover any additional gating/authorizing such as whitelisting, transaction limits, and user eligibility criteria (e.g., KYC completion).

**Third-Party Services Evaluation:** To be able to apply meta-transactions, we will need to create bespoke smart contracts that can handle our special transactions. So, there will be smart contract development will be needed in any case.  Third-party providers mostly give paymaster services and provide a dashboard view to manage the funds. Magic.link's service offering looks like the best option so far. 


Once all the decision-making phases are completed and we will decide on the product requirements, teams can start developing the platforms.

Protocol Engineering Tasks:

1) Smart Contract Development:

- Develop or adapt relayer and forwarder contracts tailored to our specific needs (e.g., namespace creation, communityStakes interactions).
- Update the NamespaceFactory contract to accept meta transactions, ensuring backward compatibility and no disruption to existing functionalities.

2) Meta-Transaction Helpers:

- Implement utility functions to streamline the creation and processing of metatransactions, implementing the agreed-upon rules and conditions set by the decision-making phase.
- Design a special monitoring mechanism for tracking and auditing of metatransactions. Metatransactions appear different than regular transactions in the blockchain.

Note: While CommunityStake.sol is not a fully upgradeable contract, we will not be able to add meta sponsorship to the buy and sell token transactions. 


Platform Engineering Tasks:

1) Integration and UX Design:

- Incorporate decision logic within the platform to dynamically route transactions through the metatransaction flow or standard flow based on predefined rules (e.g., KYC status, whitelisting).
- Design and implement user interface updates to reflect the new transaction options, ensuring clarity and ease of use for end-users.

2) Testing and Validation:

- Rigorous testing scenarios to cover all possible transaction flows, including edge cases and failure modes, to ensure a seamless user experience.
- Engage with the product team for user acceptance testing and feedback loops to fine-tune the implementation.

3) Possible timeline for development and integration:

![Image](https://github.com/hicommonwealth/commonwealth/assets/20884156/40ecbb40-285b-4ecd-948d-20058da1c811)
