### ISSUE TITLE
Pasting into Common's Editor does not work across all apps

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5909]
## Description

We have been receiving a lot of user feedback that formatting breaks when pasting into markdown. That said, it happens inconsistently because users use different apps to draft their documents. See for example#5906 

## Project Owner
PM: @zakhap 

## Acceptance Criteria
- Grab list of past bugs that have caused issues (add them as comments here)
- Use other apps like Google Docs (richtext? markdown?), Apple Notes (richtext), Markdown, Notion, HackMD, VSCode, and Telegram. each of these may paste to clipboard differently. Into the RTM (rich text mode), and Markdown mode.
- We ought to test CodeBlocks, JSON and other things 
- Formatting for lettered lists and numbered lists should be respected using markdown and more

## Additional context
- It's out of scope, but it's worth mentioning. We need a holistic solution to drafting and composing that users feel comfortable with.
- [Link to this document with relevant docs](https://docs.google.com/document/d/12szGBMgBTWUwmO9sxb5tZDVkHPM9o8uO0qqS_DA7aJQ/edit?usp=sharing)

**Comment by CowMuon** [comment]
Queuing this up for Ifu to take a look at and estimate. Ideally this is part of our larger editor cleanup, but we can also execute this straightaway to validate that users can paste rich text from other editors (Apple Notes, Apple TextEdit, Microsoft Office, & Google Docs) as well as Notion, which handles text differently. 

@Miaplacidus - if you run into any thing or get stuck, Ryan did a fair amount of work on the Qull editor and may have any answers you need. 

Finally JTN our top of mind question here is whether Quill is really the editor we want to be using here, or whether we should replace Quill (keeping in mind, that will be a "fun" migration of all the deltas.)

**Comment by CowMuon** [comment]
Teed up for estimation.

**Comment by Miaplacidus** [comment]
@CowMuon 
Thanks for the background!
Questions:
1. What is an editor blob unit?
2. Where can I see past related bugs related to an EBU?

**Comment by dillchen** [comment]
Editor Blob Unit, is anything in the clipboard that may be pasted into the
QuillEditor

EBU is not an exact term, fwiw.

I do not have the exact list of bugs. However, growth and or a search over
quill via GitHub I believe will surface most if not all

Sent via Superhuman iOS ***@***.***>

**Comment by Miaplacidus** [comment]
Thanks, Dillon! I'll search for those on Monday!

**Comment by Miaplacidus** [comment]
@jnaviask @ForestMars 
@Israellund and I had a chance to pair on this and #5829. The fix for both issues is identical and he'll be issuing a PR that contains that solution. I've added him as an assignee on this, as well.
