### ISSUE TITLE
Add Mava to Demo

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5912]
## Description
We would like to add the Mava chat service to the demo environment, in order to validate it meets our requirements (as a customer support chat widget.

## Context  
Currently, users file support requests outside of the Common app. Our preference is users should be able to get support, ask questions and provide feedback to the growth team entirely within app. ("co-located" as we say.) We believe Mava will provide the needed functionality, and just need to confirm. (NB. Mava website, documentation, etc, all foregrounds the AI aspects of their product, which we are assured can be turned off and won't undermine our use case.) 

## Engineering Requirements
Create new branch with Mava added and merge into Demo branch. It will need to have the following code added to `<head>`: 
```
<!-- Mava Widget -->
<script defer src="https://widget.mava.app" id="MavaWebChat" data-token="<OUR-TOKEN-HERE"></script>
```

## Acceptance Criteria
Product and Growth are able to test Mava on Demo servers. 

## Additional context
Mava handles acl on their side, and the following users have been added: (should have received invite in email) Dillon, Jake, Mark, Rhys, Kurtis)

**Comment by zakhap** [comment]
@CowMuon Does this ticket need the script so that Mava is connected to the existing Common Product+Growth Team Account with Mava? Or should I add the assigned Engineer to the Team Account?
