### ISSUE TITLE
Address removed tooltip should not show up on proposal pages

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5918]
## Describe the bug

The 'address removed' tooltip currently shows up on proposal pages which should not be the case since votes on a proposal are public and should have nothing to do with Commonwealth profiles. Displaying 'address removed' on proposal pages is misleading.

## To Reproduce

- Start the app locally
- View the votes on http://localhost:8080/dydx/proposal/16-bridging-the-community-and-rewards-treasuries

## Expected behavior

Addresses should be displayed as normal on proposal pages.

## Additional context

The 'address removed' tooltip was introduced in #5578 (@Miaplacidus for visibility) to allow users to remove their addresses from a community. @jnaviask We probably do not want to ship the tooltip until this is resolved.

**Comment by Miaplacidus** [comment]
@timolegros @jnaviask @CowMuon 
Thanks for the find, @timolegros! I also just noticed something similar on the search bar. 
As mentioned on the ticket #4486, the copy was added as a way to explicitly indicate that an address associated has been removed. Hence, in every case where the User component is being used and no address is present, "Address removed" is displayed. I think we need a conversation around how we want to handle removed addresses wherever they appear, i.e. what visual indicator(s) do we want to use and when? I would suggest reverting the commit that updated the tooltip and to come back to this once that conversation has been had.

**Comment by CowMuon** [comment]
Per Design, Please consider "Address removed" to be the default behaviour / displayed text for removed addresses anywhere in app, and not just the User component. @Miaplacidus 

So the scope here should be to make sure we are handling removed addresses in the same way wherever they appear, namely by displaying the text "Address removed". 

If there are edge case where this will not work for some reason, they should be surfaced here.

**Comment by timolegros** [comment]
> Per Design, Please consider "Address removed" to be the default behaviour / displayed text for removed addresses anywhere in app, and not just the User component. @Miaplacidus
> 
> So the scope here should be to make sure we are handling removed addresses in the same way wherever they appear, namely by displaying the text "Address removed".
> 
> If there are edge case where this will not work for some reason, they should be surfaced here.

@CowMuon Any address associated with _on-chain_ data must not be removed. Imagine loading up Keplr governance dashboard and seeing a bunch of 'Address Removed' tooltips - it doesn't make any sense. So far I have only thought of proposals as on-chain data we display addresses for but any on-chain data in the future needs to be considered as well e.g. community stakes transactions/history. What about groups @rbennettcw - does a member record get deleted (removed from groups) if they remove their address from their account?

**Comment by rbennettcw** [comment]
@timolegros – No, membership records are not mutated in any way if the address is removed. That's not a case that was even considered tbh.

**Comment by jnaviask** [comment]
No longer a problem.
