### ISSUE TITLE
Catalog cross-cutting concerns into existing/TODO

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#5927]
## Description
Cataloging existing and future cross-cutting concerns:
- So we can plan future refactoring work into utilities/middleware 
- While continue using them consistently 

### Project Owner
@Rotorsoft 

## Application Layers

Modern software architectures (e.g. hexagonal, clean, onion) place the cross-cutting concerns (mostly technical) in the outside layers, aiming at improving reusability, maintainability, testability, etc. This is called separation of concerns.

We can improve the codebase by applying this principle, but first we need to establish some basic layers, and map existing utilities that might need some refactoring.

### Authentication (Sign In)  & Authorization 
> *Signing in with a web30 address*
- Middleware
  When a user signs-in, we can inject a reusable `Actor` context to the execution pipeline. This context can be hydrated by middleware utilities, providing the following data points (some optional):
      - Profile: user name, avatar, etc
      - Wallet Address
      - Application Roles (admin or regular-user)
      - Community (or Communities) - including role within the community (admin, moderator, member)
   We can implement multiple *reusable* middleware utilities:
        - getFullUser (profile, addresses, communities, etc)
        - getUserProfile
        - getUser...
   We can chain multiple middleware handlers with dependencies to previously hydrated context, to compose complex validation operations like:
        - getUser -> getCommunity -> isOwner...(user owner of community)
        - Validating the user in context belongs to a role (in a community).. so we need to include the current community in context 
- Existing Utilities
   - We declare auth rules with `passport.authenticate('jwt', { session: false })` on each route requiring auth
   - The middleware parses the JWT injected by the login flows and returns a User object - Sequelize User model
   - If we need more details (see object schema above), those are loaded via `models.User...` functions in the ORM
- Project Structure
   - Defined in the routing layer
   - Defined at the `server.ts` level (passport middleware)
   - Each route in `router.ts` has its own passport.authenticate rule
   - Inside each handler function we load more user data according to the functionality implemented 
   - TODO: Encapsulate auth middleware in the routing layer, inject context in handlers.
 
### Message Schema Validation 
> *Validating incoming messages using zod schemas*
- Existing utilities
    - Starting to use zod, we will need strict mode
- Middleware
    - We could use the [Zod Express Middleware library](https://www.npmjs.com/package/zod-express-middleware)
    - We could use trpc
- Project Structure
    - zod schemas in `commonwealth/shared/schemas` organized by subdomains and model artifacts
    - Custom validation error with validation details (to be used by response builder)

### Routing 
> *Protocol related routes with versioning*
- Existing utilities
  - Inside `router.ts`  
- Tooling
  - Using express, but looking into trpc 
- Project Structure
  - We want to keep this in the top layer 

### Business Rules Helpers 
> *Encapsulating invariant rules to be reused by aggregates*
- Existing utilities
  - Business rules are not reusable across actions, the opportunity is to find reusability (per artifact)
- Generic Interface
  - Define a simple invariant interface that takes an aggregate, evaluates a condition on the state of the aggregate, and throws an invariant error if the condition is not met
- Custom errors
  - Invariant violation error will drive the type of response
- Project Structure
  - This rules belong to the core structure (model driven) 

### Repository 
> *Repository pattern to load and save aggregates*
- The ideal is to detach loading/saving state from the core functionality via repository interfaces that can implement multiple adapters (Sequelize, in-memory, any other persistence technology)
- Existing utilities 
  - Sequelize ORM, it has a model that can be loaded and saved
  - This one will require more work
  - Unit of work abstraction might be needed to support multiple operations inside a transaction
- Project Structure
  - This should reside in a repository folder that's tied to the artifacts in the model
  - Each specific adapter should have a place in the repositories folder

### Response Builder
> *Generic response builder utility*
- Existing utilities
  - We don't have any middleware, just custom errors 
- Based on custom errors and protocol adapters
  - Refine existing custom errors and conventions to map them to protocol responses
  - Error codes
  - Based on response schemas (happy path)
- Middleware
  - Inject response handling middleware according to rules above
  - Includes error formatting, details, etc
- Project Structure
  - Belongs to the upper layer (routing configuration)

### Miscellaneous 
> *Other cross-cutting concerns and tooling integrations*
- Existing utilities
  - logging
      - (Very old) logging.ts
      - TODO:
      - Support some kind of standard
      - Bootstrapped in the top layer using log levels and env 
      - Logs actions/errors by default
  - stats (and tracing)
      - Datadog, mixpanel: server_analytics_controller.ts
      - Explore OpenTelemetry, etc
      - Use conventions and defaults
  - rollbar - same as logging for errors
  - config - generic config utility with schema validation, defaults, can be inherited, consistent naming conventions

**Comment by jnaviask** [comment]
@Rotorsoft I notice that this ticket and #5981 are both on the bucket #5826 -- wondering what amount of work is required on either/both of these tickets that would be considered necessary or blocking for us to complete the MVP (and mark #5981 closed)?

**Comment by Rotorsoft** [comment]
This is just a catalog, practically done. The other one should be in the 5 to 7 point range, but not a blocking issue in case we get stuck. This is platform work, not part of value stream deliverables... more like tooling you put on a shelf to be adopted.

**Comment by dillchen** [comment]
Is this part of the Community Stake Milestone?

**Comment by Rotorsoft** [comment]
Yes, this is almost complete ...but always a WIP when we use it a reference to future work. This might eventually become a documentation ticket.

**Comment by Rotorsoft** [comment]
This is a documentation ticket. Marking completed.
