### ISSUE TITLE
Gating: Unable to vote on poll 

### ISSUE THREAD

**Issue by markiscommon** [hicommonwealth/commonwealth#5929]
## Describe the bug
can't vote on poll here in demo environement 
https://commonwealth-demo.herokuapp.com/beerman2/discussion/14349-question
<img width="1340" alt="Screenshot 2023-12-11 at 11 50 53 AM" src="https://github.com/hicommonwealth/commonwealth/assets/128752305/82b682a8-94d3-4876-99f4-6a0c0e590a7a">
-for-the-community

## To Reproduce
Create thread and add poll in gated topic with a group in demo environment - attempt to vote on poll and make sure you're in the group 
 
## Expected behavior
Should be able to vote on this poll despite being a member of the group

**Comment by rbennettcw** [comment]
LIkely will be resolved by #5928
