### ISSUE TITLE
Autogenerate Non Editable Stakeholder Group when Stake is Enabled

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5934]
## Description

Autogenerated group: do not allow metadata to be edited

Goal: users should be added to a stakeholder group automatically upon buying stake. 

User story: 
- As a community admin, at the time when I create a community with stake enabled, or at the time when I enable stake, an immutable group is created automatically called "Stakeholders" with a single requirement set to the deployed stake contract with a threshold of "more than 0" tokens.

<img width="497" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/7602bceb-1ab1-4f28-94ac-50053e12d7a3">

## Engineering Requirements
- When Stakes are enabled, either at community creation time or when enabled after creation, a stakeholder group is created within that community automatically.
- When a user mints or burns stake, their group membership status should be refreshed.
- [discuss callout copy / display for immutability]

## Acceptance Criteria
- All functionality for all other groups in terms of metadata, I.e edit name and more disabled

## Additional context
[DevLink](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1671-174760&mode=design&t=F13YaBX03PBO0pbH-4)

**Comment by HIM92** [comment]
@HIM92 AI: create user story for this

**Comment by dillchen** [comment]
@zakhap Additional acceptance criteria

- for stakeholder group, if enabled. show on members page, another column, and display their stake ownership. (grab using getter from chain)

----
I want to know the ranking of the stakeholders

----
**Out of scope**

- who bought and who sold

**Comment by HIM92** [comment]
rewritten as : https://github.com/hicommonwealth/commonwealth/issues/6843
