### ISSUE TITLE
Gracefully handle no results found in /getX routes.

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#594]
Currently errors are thrown for /getRewards when no records are found. This is not the proper way to handle that event. If there are no records found, then we should return an empty array and ensure the client can handle no results in a graceful way.

**Comment by nblogist** [comment]
@drewstone  would appreciate a feedback on the changes!

**Comment by drewstone** [comment]
Feel free to open PRs for these changes!
