### ISSUE TITLE
Pasting from HAckMD breaks formatting 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5940]
## Reproduced? (Include Loom or steps To reproduce)
(Copy/paste from HackMD.)

## Acceptance Criteria 
Copy/paste from HackMD works.

**Comment by Miaplacidus** [comment]
@lzach83 
I know you're working on a lot of pasting tickets. Do you feel like you'll solve this while working on one of your cards or maybe would you like to take this on?

**Comment by lzach83** [comment]
@Miaplacidus Per our conversation this has direct impacts on #5941, the regex that is being used to detect ASCII art gets triggered on paste for the tables pasted from HackMD thus forces it into a code block. We will have to pair on this to solve both tickets correctly. 

cc: @CowMuon @jnaviask

**Comment by lzach83** [comment]
Reassigning this ticket to myself since it has direct implications to my other Editor Cleanup milestone tickets.

**Comment by lzach83** [comment]
Since we are not supporting HTML in our markdown this ticket is closed for now, if we discover some other parts of HackMD that needs to be supported more than happy to reopen.
