### ISSUE TITLE
CopyPasta 2/3: Pasting from Notion 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5946]
## Describe the bug
Ticket 2/3 for pasting other formats into markdown editor → from Notion 

## Expected behavior
Pasting Notion formatted data into markdown editor works as expected, is tested and confirmed.

## Acceptance criteria 
Pasting rich text formatted data from any of above listed editors: (or similar)
- Renders text correctly formatted 
- Cursor is rendered at end of pasted content, not beginning. 
- Return and all other functions work as normal 

## Additional context
- We should heavily test this for multiple uses cases pasting from Notion, just for example pasting a single block vs pasting multipl blocks. 
- We should also pay attention to how unsupported formatters are handled; for example Notion has toggle based lists, how are these handled when pasted in? (Expectation: they paste in as normal untoggled lists, just as an example of an edge case we should include in test coverage.

**Comment by lzach83** [comment]
I've found a few issues when copying unsorted lists where instead of a bullet in Notion it's a checkbox, does not always happen but sometimes Quill completely ignores the checkbox then if you switch to markdown from rich it'll get rid of the list.
