### ISSUE TITLE
CopyPasta 1/3: Pasting from rich text editor 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5947]
## Describe the bug
Ticket 1/3 for pasting other formats into markdown editor → from other rich text editor

## Expected behavior
Pasting rich text formatted data into markdown editor works as expected, is tested and confirmed for the following: 
- Apple Notes
- Google Docs
- MS Word

## Acceptance criteria 
Pasting rich text formatted data from any of above listed editors: (or similar)
- Renders text correctly formatted 
- Cursor is rendered at end of pasted content, not beginning. 
- Return and all other functions work as normal

**Comment by lzach83** [comment]
I have copy and pasted from all the above editors plus a few more web based ones into ours and the results were great. 

I used every format available and cannot produce errors or unfavorable results.

**Comment by CowMuon** [comment]
Can we get this on Demo for Growth and Product to hammer on? 

I'm not sure they are going to find anything, but it would be good to have an environment where they may or may not be able to find any kinks in our long beleaguered copy pasta handling. 

As per other comments, there definitely was a bug in handling IDE blobs, and you *should* also be able to notice the bug that only affects the first paste operation (which fails) then subsequent pastes work. This behaviour is (was) definitely affected by whether the state of the text box was virgin, had content, or (3rd case) had content which was also highlighted. @lzach83 @zakhap @cowballzach

**Comment by lzach83** [comment]
I have not made it to #5945 quite yet, admittedly i don't have an traditional IDE installed but on first glance my editor to Quill does work without issues. So i have to install one to get the traditional IDE Blob, errrr maybe i could use something like codesandbox unsure. 

I will update #5945 With my findings after I figure out these unordered list pasting issues from Notion for #5946 

cc: @CowMuon @zakhap @cowballzach
