### ISSUE TITLE
Update Editor Component UI, emphasizes new Preview Button

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5949]
## Description
In comparison to some other web2 platforms where previewing content happens in real time (ie rendered markdown), Common users must first know there is a preview mode and locate which button to click to launch it. There is an implicit design question here of whether we want to support live preview. The explicit question is how the editing experience may be improved without that much larger change. Can UI be adjusted so that user has better awareness of this? 

## Engineering Requirements
* remove rich text mode
* update the editor so that there are 'Markdown' and 'Preview' tabs
* on editing rich text content, the editor should open the text in markdown so that the user can make any necessary changes. 

## Additional context
This updates the UI of the editor with an emphasis on placement of buttons and the overall arrangement of the editor has cleaned up. A few notes:
- We Are Including Preview as a "Tab" similar to Github.
- We are **removing RichTextMode**

**Markdown Editor Mode**

<img width="326" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/5b037786-fd2b-413a-aa9a-c8756a735350">

**Preview Mode**

<img width="462" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/def95bff-d77b-44c0-ade0-eb96226db53f">

**Markdown Button Behaviors**
1. Headers should add "#" on the line highlighted.
2. Bold and Italics should add relevant characters ** __ before and after the cursor. If text is highlighted in editor, the highlighted text should be wrapped.
3. Link should add link syntax into editor => highlighted text should become hyperlink text
4. Codebock should add codeblock syntax => highlighted text should be wrapped
5. Quote should add quote syntax => if highlighted text, add > to front of line highlighted.
6. List icons should insert correct type of list syntax

<img width="680" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/f3ec5e58-e52a-4b2c-a1b0-876eadf92e5b">

[DevLink](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&node-id=117-31280&mode=design&t=VPzo9jfcE3NuqG9q-4)

**Comment by Miaplacidus** [comment]
@CowMuon @jessmart1213 @zakhap @sachben91 @jabell88
Are there any other engineering requirements than entirely removing rich text mode and having a preview window?

**Comment by Miaplacidus** [comment]
@zakhap @CowMuon @jessmart1213 @jabell88
A few questions about this card. Just to make sure everything is clear:

1. Are we including all of the new icons in the scope of this work?
2. The image import button is missing. Are we doing away with this feature? It seems pretty useful. 
3. I assume the repeated list icon should actually be an icon for a task list (i.e. a checkbox list)?
4. I assume the last two icons are to add columns and rows to the table a user has just created.

**Comment by jabell88** [comment]
Let me clear some of these up:
1. I believe so but I'll defer to product
2. The image import button is in the bottom left. The section where it tells you to drag an image or click is clickable.
3. The 3rd list icon should be the checklist, I'll fix that in the design. 
4. Correct, the last section of icons is table formatting. 

Note: some of these screenshots are old so please use the text and icons from the [Figma file](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&node-id=187%3A8484&mode=design&t=jbzmNnJP7jFCLnC3-1)

**Comment by zakhap** [comment]
1. If there are any difficulties with adding the new icons + functionality, we can peel it out into a follow-up ticket, but the intention is to include the functionality.

**Comment by Miaplacidus** [comment]
Thanks, @jabell88 @zakhap!
Updated points to more accurately reflect scope.

**Comment by Miaplacidus** [comment]
@zakhap @jabell88 
We need some way to deal with posts that are rich text. I know that at some point there's been discussion around converting existing rich text content to markdown. @jnaviask suggested that, instead, we just make rich text read-only. If we do this, we should probably have some kind of visual indicator/message so that this experience is not too unpleasant for users.

Any thoughts? Suggestions?

**Comment by jnaviask** [comment]
The midway solution is to only convert when they edit. What I want to avoid is running a migration across all rich text blobs in the database that might mess up a bunch of the posts.

**Comment by zakhap** [comment]
Both are really good suggestions!

I would prefer @jnaviask's solution. Here it is as a User Story:  
- When the user presses "Edit", their Rich Text gets converted into Markdown so that they can update their thread/comment (and also fix any generated MD issues that arise). This will only impact a subset of users in the present, and over time, will wane as all new content will be created in MD

**Comment by Miaplacidus** [comment]
Update: currently working on handing rich text headers, bold, italic, and strikethrough text.

**Comment by CowMuon** [comment]
Setting this back to in progress given Marcin's comments. 

NB. this is now overdue and blocking other work, so we'll need to decide how to handle that to keep our release on track.
