### ISSUE TITLE
Small text editor window size on Desktop

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5950]
## Description
"Small text editor window size on Desktop"

## Additional context
Literally, this is the only description we have for this bug. 

Design to review and propose solution.

**Comment by CowMuon** [comment]
Does this user complaint precede auto-sizing? Presumption is yes, and that this ticket is closable. 

We should still look into height as it is definitely worth exploring to improve this area.

**Comment by zakhap** [comment]
This ticket is closable as we have this detailed in the editor revamp tickets.
