### ISSUE TITLE
Post formatting looks bad? 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5956]
## Description
- Post formatting looks “ugly” compared to other platforms

## Additional context
Design hand off → Need non-ugly requirements

**Comment by CowMuon** [comment]
This is about spacing inside of markdown eg. a HR tag doesn't have any padding (so everything just feels bad.)

**Comment by zakhap** [comment]
All style related issues for rendering markdown is handled is #6035 + #6036
