### ISSUE TITLE
Page blow up when saving community settings

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5963]
## Describe the bug

Saving the community settings on the manage community page throws an error which breaks the entire page.

## To Reproduce

- Create a new start Ethereum community
- Go to manage community page
- Click the save button

## Expected behavior

The page should not blow up when saving settings.

## Additional context

Introduced in #5821

**Comment by kurtisassad** [comment]
My bug, stealing from Tim
