### ISSUE TITLE
BUG: Create community enforces icon validation

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5966]
## Describe the bug

**BRANCH**: v0.8.3
**ENV**: QA

When user tries to create new community without icon, we have validation error. Previously that was not required param in api call.

## To Reproduce

1. Go to https://qa.commonwealth.im/
2. Sing up 
3. Create new community 
4. Type basic community name and click save

## Expected behavior

Since new community feature is not live yet, we should preserve old state of required fields. 

## Additional context

Video:
https://app.screencast.com/z2HB3QJzFdoKY

**Comment by jnaviask** [comment]
@ilijabojanovic my experience on production was that an icon is in fact required for the old create community flow -- can you confirm this?
