### ISSUE TITLE
Metamask Login button should only open metamask (and not coinbase or phantom wallet)

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5968]
## Describe the bug

Currently when you click "metamask" it may give you the option to open coinbase wallet or phantom wallet instead of metamask. We want to ensure the metamask button only opens metamask.

## To Reproduce

1. Ensure you have metamask AND phantom or coinbase wallet installed in your browser.
2. Click "metamask" and observe the selection screen.

## Expected behavior

Metamask immediately opens.

## Additional context

Supersedes #5629

**Comment by ianrowan** [comment]
Adding coinbase extension even breaks metamask SDK(sdk doesnt think metamask is installed b/c coinbase totally wipes the window.ethereum format) smh:
<img width="415" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/7e269699-2e5b-4649-969b-9c2d7a128287">

It appears coinbase isnt implementing: EIP-6963(https://docs.metamask.io/wallet/how-to/discover-multiple-wallets/) and metamask best solution to this is to disable non EIP-6963 wallets for metamask to work. https://support.metamask.io/hc/en-us/articles/11907107168923-I-can-t-connect-MetaMask-Extension-to-a-dapp-#:~:text=If%20nothing%20happens%2C%20the%20most,for%20MetaMask%20to%20work%20properly.&text=Once%20you%20have%20disabled%20other%20wallets%2C%20reload%20the%20page.

This isnt a blocker as there looks to be some non-sdk solutions, but it will require more research than expected now

CC: @jnaviask @ForestMars @egetekiner
