### ISSUE TITLE
Removing the community tag from the search bar should result in a global search

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#5972]
Currently, when you are on a community's page and you remove the community tag from the search bar, search functionality is limited to the community, i.e. the dropdown and search page only show results for the community.

We want to allow global search even when on a community page. The ask here is that when the community tag is removed from the search bar, searching happens across all communities. 

@ForestMars @jessmart1213 @jnaviask

**Comment by jnaviask** [comment]
Note that the "Search all communities?" link also has this issue, and should be resolved within this ticket.

**Comment by Miaplacidus** [comment]
@jnaviask 
Gotcha! Could you remind me of where the 'search all communities' link is?

**Comment by jnaviask** [comment]
Search within a community, hit enter, then it appears as a link:

![2023-12-13-163751_1565x895_scrot](https://github.com/hicommonwealth/commonwealth/assets/1860629/79ec67cd-3466-434e-8984-64ea7ed9f413)

**Comment by Miaplacidus** [comment]
Adjusted points due to post-vacation productivity being terrible. 😬
