### ISSUE TITLE
Resolve issue with injecting pinned posts into getRecentPostsSortedByWeek in discussions listing

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#598]
- Empty forums currently show up with a spinner at the bottom
- If a listing (e.g. a topic) has no non-pinned threads, the empty state will show up instead

**Comment by zakhap** [comment]
- [ ] Empty forums currently show up with a spinner at the bottom
- [x] If a listing (e.g. a topic) has no non-pinned threads, the empty state will show up instead
