### ISSUE TITLE
Adopt chain of responsibility pattern to hydrate/validate actor state before it gets injected in actions

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#5981]
## Description
This marks the initial steps in our platform refactoring journey towards a "cleaner" architecture. See #5927
We will plan for incremental adoption, but not mandatory.

Our objective is to start building a modular collection of reusable utilities for validating actions (commands), encompassing actor roles and state.

## Project Owner
@Rotorsoft 

## Engineering Requirements
- Define "Actor" schema with all properties needed to validate actor roles and state
- Define utilities to hydrate "actor state" ... replacing user.getAddresses, findAllRoles, etc
- Consider caching strategy for "actor states". Each user is an actor in a community, we can cache with key {address, community}
- Define utilities to validate "actor state" ... role validators, community validators, content validators, etc
- Define pattern to compose these utilities as a chain of responsibility - middleware using functional monadic patterns?
- Avoid leaking protocol features (like req, res, body, etc)
- Inject "actor state" in actions the same way we inject the db adapter
- Start adopting a more straightforward unit testing pattern, focusing on core functionality, initiating from the creation of the actor state.  

## Acceptance Criteria
- Deliver new actions that get validated by the new middleware
- Deliver unit tests, practicing proper TDD

**Comment by rbennettcw** [comment]
Notes from meeting:

- Improvements for `router.ts`
    - File is currently long since there are many routes. Make smaller.
        - Create subrouter for each router group (e.g. `/threads/XXX`, `threads/YYY`)
          - ```ts
            import threadsRouter from 'threads'
            router.use('/threads', threadsRouter)
            ```
        - With RESTful endpoints, this should map easily
    - Replace `methodNotAllowedMiddleware` with proper global middlewares
      - Use `app.use(errorHandler)` or `app.all(errorHandler)` after all route declarations
      - Create seperate middlewares for statsD, rollbar, etc.
    - `databaseValidationService.ts`
      - Remove dependency on Express types, use normalized Actor type instead
        - Decouples server framework from logic– easier to test
- DB model usage
  - It's not necessarily needed to pass the `models: DB` object around the app– it's already a singleton, just use the imported object
  - TODO: how to mock imports?
- Middleware
  - Old system == request middleware
  - New system == command middleware
    - Example branch `rotorsoft/5981.actor-state`
    - `ExpressCommand` adapter function maps Express request to command parameters and invokes the command
      - e.g. `commandFn(actor, req.body)`
      - Rather than `req.address`/`req.user`, instead use `actor: Actor`:
          - Normalized object that contains request context decoupled from Express framework, easier to test
          - Includes address, roles, communities, etc. as needed
    - Can be implemented in current code without jumping to TRPC immediately
