### ISSUE TITLE
Cursor focusing on top rather than bottom of content after pasting into quill editor

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5984]
## Description

Follow-up to #5942 regression.

**Comment by Israellund** [comment]
I have only been able to fix the scroll-top-top bug by installing `quill@2.0.0-dev.4` And after that there is a new bug wherein, when the editor has enough content to trigger a scroll bar, if anything is pasted or return is pressed, the focus doesn't follow the cursor yet it will refocus when any other character is pressed (see video).
That version [from what I've read doesn't seem at all production ready or even maintained](https://github.com/quilljs/quill/issues/3356).




![Image](https://github.com/hicommonwealth/commonwealth/assets/69872984/13f4786d-d01b-45dd-af5e-5dc9a79b556d)


![Image](https://github.com/hicommonwealth/commonwealth/assets/69872984/de690921-3ae5-4d52-88ab-944e6bc140f8)
