### ISSUE TITLE
Spike: Replace the dreaded Quill editor

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#5986]
Everyone hates Quill. Let's do something about that.

Investigate alternatives to the Quill editor, choose one you believe to be the best, and estimate the effort it would take to replace Quill with this new editor. 

Some options include React-md-editor and React-simplemde-editor. However, feel free to include anything you think would be a good fit in your investigation.

@ForestMars @jnaviask

**Comment by jnaviask** [comment]
Spike timebox: 3 hours.

Deliverable: comparison matrix of options

**Comment by CowMuon** [comment]
This will not happen in Cycle 9, for obvi reasons.

**Comment by jnaviask** [comment]
Superseded by several other tickets.
