### ISSUE TITLE
Move off cw-discourse-import script off airplane

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#5988]
## Description
This idea spawned from this discussion:
https://github.com/hicommonwealth/commonwealth/issues/5819#issuecomment-1852687495

The basic idea is to move and update the script to the commonwealth repo. We also need to make sure that the one-off heroku dyno can run it properly.

**Comment by jnaviask** [comment]
I also wonder if there's a way we can integrate it with the super admin panel, so that growth can do it without engineering intervention. However this seems like a stretch given the relatively complex database operations involved.

**Comment by CowMuon** [comment]
> [I also wonder if there's a way ](https://github.com/hicommonwealth/commonwealth/issues/5988#issuecomment-1852937680)

**Comment by rbennettcw** [comment]
This is obsolete in favor of #7124
