### ISSUE TITLE
Diva Staking Bug: Webhooks is double sending updates into discord channels 

### ISSUE THREAD

**Issue by markiscommon** [hicommonwealth/commonwealth#5994]
## Describe the bug
Webhooks is double sending updates into discord channels 
"he Discord integration is great indeed...
...but the bot usually sends each message twice :flushed:
Don't know if you have an easy fix for this." 
![image](https://github.com/hicommonwealth/commonwealth/assets/128752305/e5b6b1cd-55e9-4951-bd5a-c846ebdfe378)
![image](https://github.com/hicommonwealth/commonwealth/assets/128752305/20844f2e-590c-4e4d-a387-a7cfef67cf0d)

## To Reproduce
Setup webhooks, populate something into a topic on common, watch it double populate in the designated discord server 

can check diva staking or stargazes discords

## Expected behavior
webhooks should only send one notification

**Comment by mw2000** [comment]
While debugging this, it looks like some of the comments in the divastaking discord are being sent twice, while some aren't.

I also came across this post on zapier, which sends another message in 37 ms if the original API (in this case our discord bot) is unresponsive.

https://community.zapier.com/how-do-i-3/webhook-post-is-sent-several-times-causing-duplicates-at-the-other-service-3235

**Comment by mw2000** [comment]
after checking in the database, it looks like there are no duplicate notifications. Looks like a discord error.
