### ISSUE TITLE
Transaction Page where users can view all their stake

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5996]
## Description

This is a page where users can go to view their stake transaction history and current ownership across all their communities.

We want to add a page to the user's profile where they can view all the stake that they have and which communities that stake is connected to.  

I. Users are able to navigate to this by clicking on their profile on the top right corner of Commonwealth (see image 1).
II. Users then select "my Community Stake." (see image 2)
III. They are then taken to the "My Community Stake" page where there is a table that they can see all the stake that they have acquired broken down by community and the contract the stake was obtained from. Within this there are 5 data points on the table (see image 3): 
_a) Community 
b) The stake smart contract address (NOT THEIR OWN WALLET ADDRESS)
c) The amount of community Stake therein
d) Vote weight (please ignore the figure in the mock up, the vote weight is the amount of vote weight provided by the collective amount of stake established in **c** which increases their reaction and voting weight in the community established in **a**.
e) the average cost of minting the new stake by the user (what they paid) established in **b**._

IV) there are two tabs on the table. The default is the "My Stake" table, and the second option is displayed to the right of this and it is the address' transaction history. This provides all the transactions of the user's address dealing with community stake contracts. Within this table the following information is provided (see image 5):
a) Community
b) The stake smart contract address (NOT THEIR OWN WALLET ADDRESS)
c) Action = either Mint or Burn (formerly buy or sell)
c) The amount of community Stake therein
d) Vote weight (please ignore the figure in the mock up, the vote weight is the amount of vote weight provided by the collective amount of stake established in **c** which increases their reaction and voting weight in the community established in **a**.
e) the average cost of minting the new stake by the user (what they paid) established in **b**._
f) timestamp = the date mm/dd/yyyy and time in UTC of the transaction. 

V) The user can change the table to review all stake held by their connected addresses which will show all the holdings of that user address (see image 4)

Image Flow: 
1 - 
<img width="266" alt="Screenshot 2024-02-01 at 4 03 10 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/3830cf82-94e5-4e6b-8d9a-21930cdcba62">

2- 
<img width="218" alt="Screenshot 2024-02-01 at 4 02 10 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/e96b3e96-bb3f-48f2-adbf-1f5118a053c7">

3- <img width="789" alt="Screenshot 2024-02-01 at 4 02 42 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/aa58ebae-2e24-42f5-867c-c2e5201f74cb">

4- <img width="254" alt="Screenshot 2024-02-01 at 4 02 38 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/46e9b065-0c07-4aa0-8851-4e341ea113ce">

5 -<img width="670" alt="Screenshot 2024-02-01 at 4 39 09 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/ff24977c-fb04-47ff-bed4-00b8f45d290d">

## Project Owner
PM: @HIM92 
Designer: @jessmart1213 

## Acceptance Criteria
- Add a new navigation menu to page within user settings mgmt dropdown
- Create a new page, with route at `/transactions`, only accessible if is logged in
- Create Components and fetch transaction and stakes data in separate tabs using #5538 and display in component, with ability to search and filter by owned address
- Update the layout and include filter / search following specified behavior in design component

## Additional context
- [DevLink](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1812%3A63466&mode=design&t=3HeDnwczbSIdX4xm-1)
- [Notion Doc with Comprehensive Design Solution](https://www.notion.so/buildcommon/Design-solution-Community-Stake-V2-E2E-5035a6f44e6e4744974492ac64b72f8a?pvs=4#497ddef1327740f9bc2b86a4ac00378b)
- Needs empty stakes from Design

**Comment by HIM92** [comment]
AI: move devlink to the top, order the flow.

**Comment by CowMuon** [comment]
Closed #5998 (to be re-ticketed by @HIM92) which blocks this one.

**Comment by CowMuon** [comment]
@zakhap will rewrite ticket (surface user story)

**Comment by HIM92** [comment]
Closing and rewriting as multiple tickets
