### ISSUE TITLE
[SPIKE] Mixpanel Analytics

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#5997]
## Description
We will want to track the growth of communities with Community Stake feature enabled. My initial thought is to create:

1. A new **property** for Community Stake being enabled for tracking the community.
2. A new **event** in the Create Community funnel where Community Stake is activated.

## Project Owner
@HIM92 (Harris Innes-Miller)

## Engineering Requirements
- That the growth rate of communities using community stake is trackable in mixpanel. This is both the users joining communities with stake activated and the overall population of communities with stake activated. 

## Additional context
I want to be able to track the number of communities that are created with community stake activated. Additionally, I want to track the number of new users who sign up and join community a community that has stake activated on it.

**Comment by dillchen** [comment]
cc: @HIM92 can you take a look at #5886 I've updated the ticket, I feel like we should close this ticket as the other one is more comprehensive atm

**Comment by HIM92** [comment]
lets close it
