### ISSUE TITLE
DS: Update Table in Design System to include footer row

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5998]
## Description

We are adding a row within the Table that includes additional information, and summary statistics

See Image

<img width="963" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/e19885a0-56a3-4948-a5a9-64cb976b2026">

This blocks #5996 

## Project Owner
PM: @dillchen 
Designer: @jessmart1213 

## Additional context
- [DevLink](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=3309-18058&mode=design&t=zqHFBVaGA8NtqB1G-4)

**Comment by HIM92** [comment]
@HIM92 AI: Define what this is actually supposed to do

**Comment by CowMuon** [comment]
(2/1 - Refinement tag *not* added.)

**Comment by CowMuon** [comment]
Ackshully, we decided to close this story and Harris will re-ticket.
