### ISSUE TITLE
Governance styling

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#600]
- the metadata is center aligned now, on the discussions page (should be left aligned)
- date formatting on discussions page is different than on the proposals page (should change the proposals page to match discussions)
- UserGallery, ReactionButton, and last updated date aren’t perfectly aligned

**Comment by gdjohnson** [comment]
Didn't see this issue before I pushed up to construct, but should be taken care of!

Alignment issue was due to a missing ternary switch for logged-out users; I've added a ternary to make sure grid col spacing is correct. Timestamps have been regularized to use the formatLastUpdated function.
