### ISSUE TITLE
In New Create Community Flow social links are not displayed in the community page

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#6006]
## Describe the bug

Links provided in the new create community form are not displayed in the app.

## To Reproduce

add `FLAG_NEW_CREATE_COMMUNITY=true` to .env
1. go to branch `marcin.5896.create-community-backend` and page `/createCommunity`
2. be signed in
3. select EVM
4. fill out the form
5. add social links
6. launch community
7. go to created community page
8. in left sidebar there are no social icons
9. go to manage community page
10. inputs related to social links are empty

https://github.com/hicommonwealth/commonwealth/assets/14819225/883bc590-0303-4062-a1f3-2d780a3c656d

## Expected behavior

8. icons are visible and point to the links provided in the create community  form
10. inputs are filled out with the links provided in the create community form

## Additional context

payload with links to POST /api/communities

```
{"id":"testcomm","name":"testcomm","base":"ethereum","description":"community description","icon_url":"https://assets.commonwealth.im/03d2c322-fce3-49d4-99ed-3ff27335125c.png","social_links":["https://www.discord.com/","https://discord.com/","https://www.telegram.com/","https://telegram.com/","https://github.com/","https://www.github.com/"],"eth_chain_id":"1","node_url":"https://eth-mainnet.g.alchemy.com/v2/pZsX6R3wGdnwhUJHlVmKg4QqsiS32Qm4","alt_wallet_url":"https://eth-mainnet.g.alchemy.com/v2/pZsX6R3wGdnwhUJHlVmKg4QqsiS32Qm4","type":"offchain","network":"ethereum","default_symbol":"TEST","jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEwMjkyLCJlbWFpbCI6bnVsbCwiaWF0IjoxNzAyNDc5NDQ4fQ.w3bUdFgDPyV13sKwAxqHDW9dftVLYCjEjxCrhDLRLcs"}
```

DB dump
`select social_links from "Communities" where id = 'testeth3'`
<img width="403" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/abb42ae2-c419-4b69-9cab-d844d2b3bda6">

**Comment by mzparacha** [comment]
I tried https://github.com/hicommonwealth/commonwealth/pull/5999 (from @kurtisassad) locally and it fixes this issue.

cc: @masvelio @jnaviask
