### ISSUE TITLE
Update Community Namespace On-chain Validation

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#6007]
## Description

As part of the work in #5882 a on-chain validation of the attested namespace will be required. The objectives of this validation should only depend on on-chain data, while other validations are contained in the route. 

The main points of validation are:
1. transaction success
2. admin on namespace of attesting user

## Project Owner

@ianrowan 

## Engineering Requirements

- A self contained helper function that can receive the following data
    - namespace name
    - transaction hash
    - attesting user address
- And returns a success response or a detailed error response
- To preform the following validation approaches should be used
    - Check ERC1155 balance of namespace id=0 of address via TBC. Assert balance is 1
    - use a web3 framework to obtain details about the transaction hash. Confirm success and that tx hash involved deployment of contract address related to name

**Comment by jnaviask** [comment]
@Rotorsoft can you add this ticket to #5882 in the appropriate place, so it's tracked alongside the other platform-side tickets?
