### ISSUE TITLE
Bucket: Update Stake Enablement on Create Community and Admin Panel

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#6010]
## Description

Allows existing communities to enable stake by:

1. adding a new module on the integrations page
2. includes a flow to enable stake (borrowing from create community flow)
3. includes additional success page to show the current status and other information

This is blocked on the #6030 ticket

## Project Owner
PM: @dillchen 
Design: @jessmart1213 / Jared for broader admin onboarding

## Acceptance Criteria
- Add a new module on the Integrations page, this should be below the Directory Page

<img width="831" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/f3c28525-35ae-4457-a59f-d7a38e021c2b">

- Adds flow to enable stake [DevLink for End to End Flow](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1738-83886&mode=design&t=ml6ROKLyh2WD1SB1-4)

-  Include status of stake at the top of the page with specific [devlink](https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1805-35770&mode=design&t=ml6ROKLyh2WD1SB1-4)
<img width="592" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/13bddec1-9595-409e-b005-08f346ae7e51">

- Upon success show this
<img width="633" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/54676cfb-378f-4908-84aa-d2a8435dac43">

## Additional context
- May need to be broken into separate tickets depending on PEng discussion

**Comment by CowMuon** [comment]
Dropped into backlog, but could really stand to have a description here. (Also unclear how WIP tag is being used here (other that to imply it is being actively worked on).)

**Comment by dillchen** [comment]
WIP Tag in this case needs dev link, for clarity it's still blocked because we'd like to rollout the entire admin panel refresh which @sachben91 and Jared are working on ticketing

**Comment by CowMuon** [comment]
Blocked by Admin Flow & Community Stake v1's. Adding for Sprint #4, may roll over into Sprint #5.

**Comment by HIM92** [comment]
deprecated for: https://github.com/hicommonwealth/commonwealth/issues/6877
