### ISSUE TITLE
Set Community Stake on-chain validation

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#6019]
## Description

Upon setting up community stake a new id on the namespace must be saved for use with buy/sell/balances later on. 
Within the proposed set community stake route an on-chain validation will occur. The main objective of this validation is to ensure that the community stake id attested to is in fact configured for the proper namespace.

## Project Owner

@ianrowan 

## Engineering Requirements

- Write a standalone validation helper on the server with the following parameters: namespace name, community stake id
- Check against CommunityStake contract whitelist if name/id is in fact configured
- return success or detailed failure error 

## Acceptance Criteria

- name/id of configured community stake is checked on chain and proper result returned.

## Additional context

- required for #5826 
- This does not check for platform(#5826) side items such as
    - Is user admin of Community 
    - Is attested name associated with community 
These should in theory be checked prior to calling on-chain data. 
- Another proactive note - on-chain admin does not need to be checked as they are the only one who could have triggered the onchain action to whitelist the mentioned data. ie above check proves admin action by proxy.

**Comment by jnaviask** [comment]
Can we link to #5826?
