### ISSUE TITLE
Admin capabilities - Community Profile screen

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6024]
## User Story 
When I click on Community profile, I want to see information about my community that I added at the time of community creation, along with nice to have fields such as tags and stages.

## Product Specs 
Fields (view and edit permissions unless specified) :
- Community Name (view only)
- URL
- Community Namespace (view only)
- Community Symbol 
- Description
- Community profile image (both upload and generate new image) 
- Links 
- Tags
- Stages
- Banner 
- Option to choose default home page for the community 

Once the user has made any edits, they should be saved only when the user clicks on Save at the bottom of the page 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/815bb0e9-bb2f-4cc6-b01a-63baad103a53)

## Designs 
[Figma](https://www.figma.com/file/ibuywR0bBcy3ZZhPXbjEJw/Community-Admin?type=design&node-id=278-6440&mode=dev)

**Comment by CowMuon** [comment]
As discussed in kickoff, stories for this milestone assigned to Malik, @Miaplacidus & @Israellund.
