### ISSUE TITLE
Admin capabilities - Admins and Moderators screen

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6027]
## User Story
Admins should have a single page to manage upgrading/removing members as admins or moderators 

## Product Page
- Screen shows a searchable list of all members in the community, along with options to upgrade a member to admin or moderator
<img width="452" alt="Screenshot 2024-01-10 at 11 57 43 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/7aa92050-0bf6-4e5b-a681-b6088ee1518d">

- Two separate sections to manage existing admins and moderators 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/6542ab3f-6ad3-49b7-9e65-1490bf3fd5a7)
![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/132f4c32-ee92-422e-82e6-b6bdfd017d1f)

## Design
[Figma](https://www.figma.com/file/ibuywR0bBcy3ZZhPXbjEJw/Community-Admin?type=design&node-id=278-7226&mode=dev)

**Comment by CowMuon** [comment]
@sachben91 Can someone please add full design here? (Currently only has fragments)
