### ISSUE TITLE
🪣 Admin onboarding bucket

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6028]
## Description

A user who has created a community on Common is not directed on what the best next steps are after they have created a community. This creates a lot of communities that are inactive as soon as they have been created because we don't guide admins to set up their communities for success.  Prompting users to take action in setting up their community (such as nudging them towards integrations like Snapshot, and Discord) will increase the number of active communities, and engage community admins more. 

The admin capabilities panel is closely related to onboarding a new community.  A hierarchically organized admin capabilities panel will enable admins to discover the necessary tools for setting up a successful community

[PRD ](https://www.notion.so/buildcommon/Product-brief-admin-onboarding-admin-capabilities-ed39ceb2c8d0474797b9ac72e47f80d2)

## Tickets 
Admin onboarding - https://github.com/hicommonwealth/commonwealth/issues/6030 
Related bucket ticket for reorganizing admin capabilities - https://github.com/hicommonwealth/commonwealth/issues/6020

**Comment by CowMuon** [comment]
@sachben91 will convert both buckets into single milestone.
