### ISSUE TITLE
Action cards for onboarding

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6029]
## Description
The onboarding card component is part of the admin onboarding feature. Within the admin onboarding feature, it is used to prompt the admin of a new community towards actions that we see as critical for the success of a community, such as integrating Discord or setting up snapshot

## Behavior 
- The cards are arranged side by side to each other at the top of a new community, regardless of the page that the user is on within the community. 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/c996876a-822e-40df-b4eb-5390eb620c4c)

- All the cards have CTAs that take the admin towards different screens within admin capabilities. 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/aee085e7-bd7d-411e-9fab-9b49ef8cd11c)
- Once the user has clicked on the CTA and completed the specified action, such as creating a group, the card changes to a completed state 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/30b4ddae-472a-444e-af40-630c37756801)

## Design
[Figma ](https://www.figma.com/file/ibuywR0bBcy3ZZhPXbjEJw/Community-Admin?type=design&node-id=335-11677&mode=dev)

**Comment by dillchen** [comment]
May need to specify mobile behavior, otherwise this may get implemented responsively. I.e stacked vertically instead of horizontally

**Comment by sachben91** [comment]
mobile behavior is mentioned in the main ticket https://github.com/hicommonwealth/commonwealth/issues/6030 - can move it here if needed

**Comment by dillchen** [comment]
All good, as long as engineer is aware

Sent via Superhuman iOS ***@***.***>

**Comment by dillchen** [comment]
@mzparacha did u see the linked Mobile Behavior as well here?

**Comment by mzparacha** [comment]
Yes, [this draft PR](https://github.com/hicommonwealth/commonwealth/pull/6216) follows the mobile designs from https://github.com/hicommonwealth/commonwealth/issues/6030, but I noticed that https://github.com/hicommonwealth/commonwealth/issues/6030 mentions that 
> The cards should be there only within Discussions/All  . If the user navigates to a different page the cards should disappear

but this ticket mentions

> The cards are arranged side by side to each other at the top of a new community, regardless of the page that the user is on within the community.

not sure which one to follow here, tagging @sachben91 for confirmation.

**Comment by mzparacha** [comment]
I also noticed that #6030 mentions a dismiss-modal

> User has the option to dismiss cars by clicking "dismiss", which would show the following pop-up. It gives the option to "not show this again". If the user selects that option the cards should not be displayed to the user again
![image](https://github.com/hicommonwealth/commonwealth/assets/51641047/f052ad52-c983-418c-a654-e691bdd6d98f)


I will do that in this ticket.

cc: @sachben91
