### ISSUE TITLE
Admin onboarding

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6030]
## Description 

A user who has created a community on Common is not directed on what the best next steps are after they have created a community. This creates a lot of communities that are inactive as soon as they have been created because we don't guide admins to set up their communities for success. Prompting users to take action in setting up their community (such as nudging them towards integrations like Snapshot, and Discord) will increase the number of active communities, and engage community admins more.

The admin capabilities panel is closely related to onboarding a new community. A hierarchically organized admin capabilities panel will enable admins to discover the necessary tools for setting up a successful community

[PRD](https://www.notion.so/buildcommon/Product-brief-admin-onboarding-admin-capabilities-ed39ceb2c8d0474797b9ac72e47f80d2)

Related bucket ticket for reorganizing admin capabilities - https://github.com/hicommonwealth/commonwealth/issues/6020

## User Story
After a community has been created, Admins should be prompted to complete a set of actions that will enable them to have an active community 

## Product Specs 
-  User lands on` Discussions/all `once they have created a community. They should see a set of onboarding cards with CTAs at the top of the page under the title "Finish setting up your community" 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/ee036758-cd7f-43c4-a75b-8aeb0d29273a)
- The cards should be there only within `Discussions/All ` . If the user navigates to a different page the cards should disappear 
- The cards available to the user are: Create a topic, make a group, enable integrations, create a thread, purchase stake (only when community stakes is done) 
- On clicking the CTAs in the card the user should be taken to the appropriate screen within the admin capabilities page 
- Once the user has completed the action mentioned in the CTA, the status of the card should change to completed 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/29fb3a66-7b3c-4335-9f8c-e8c3dd9165cc)
- User has the option to dismiss cars by clicking "dismiss", which would show the following pop-up. It gives the option to "not show this again". If the user selects that option the cards should not be displayed to the user again

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/03c0c769-b168-493e-9cba-3f2a9a6f1c9a)

- If the user only dismisses the cards, it should be displayed again when user navigates back to `Discussions/all `
- Mobile behavior: The cards should be available as a side scroll within mobile and should not be stacked 

<img width="390" alt="Screenshot 2023-12-14 at 11 43 06 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/5453dacc-1740-42f0-a145-96fd8252517a">

## New Compoents 
Onboarding cards - https://github.com/hicommonwealth/commonwealth/issues/6029 

## Design 
[Figma ](https://www.figma.com/file/ibuywR0bBcy3ZZhPXbjEJw/Community-Admin?type=design&node-id=348-12978&mode=dev)

**Comment by jnaviask** [comment]
@mzparacha is this ticket relevant to your work on #6029? Can we close it now as not necessary, or should we close it alongside your changes?

**Comment by mzparacha** [comment]
Yes, this once can be closed as the changes were already done in https://github.com/hicommonwealth/commonwealth/issues/6029, @jnaviask.
