### ISSUE TITLE
Comprehensive Markdown Support (Part 1: Basic Features)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6035]
## Description

In our Text Editor's Preview and when Threads, Comments, and Proposals gets rendered from Markdown, we should support all of the basic functionality expected within Markdown. This Issue is part 1 of 2 and the list below is a comprehensive feature list of what Common _expects_ of basic markdown functionality. Part 2 will be to add a subset of the extended Markdown Feature-set that is most relevant to the kinds of conversations that happen on Common. 

Dev Mode for all Rendering Options: https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&node-id=301-4682&mode=dev

## Project Owner

@zakhap 

## Acceptance Criteria

When rendering Markdown formatted text, we should accept and properly render the standard syntax for the following features: 
- [x] Headers (all 6, with proper spacing below) `# ## ###...`
  - Headers 1-5 should reflect our design system
  - Headers 6 should simply maintain the styling for H5 as we don't have a detailed H6. 
- [x] Horizontal Rule / Divider line (with proper spacing above + below)
- Inline Typography: 
  - [x] Bold
  - [x] Italic
  - [x] Bold + Italic (together)
  - [x] Strike-through
  - [x] underline
- [x] Block Quotes (and nest-able) `>` `> >`
- Lists
  - [x] Ordered
  - [x] Unordered
  - [x] Lettered (consitutional style)
  - [ ] Todo lists
- Code
  - [x] Inline (single tick)
  - [x] Block (wrapping triple tick)
- [x] Tables
  - [x] Inline Typography properly applying to text in table cells
- Links
  - [x] Standard MD format for hyperlinks (with text)
  - [x] Auto-convert pasted URL into clickable link
- Images
  - [x] D&D into editor, upload and insert MD, allow update of alt-text
  - [x] Standard MD format, with alt text (image ref to external server)
  - [x] Image Link (clickable image)
- [x] Special Character Escaping (https://www.markdownguide.org/basic-syntax/#characters-you-can-escape)

## Additional context

<img width="568" alt="Screen Shot 2024-01-04 at 11 01 14 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/f52f3398-cbf2-4570-8e25-d377e124a808">

**Comment by dillchen** [comment]
**What it should look like**

<img width="371" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/0741a16d-6db8-4ded-b504-603640f1114b">

[DevLink](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&node-id=117-32858&mode=design&t=VPzo9jfcE3NuqG9q-4)

**The Markdown Blob that should map to this**

_Zak to Insert_

**Comment by Miaplacidus** [comment]
@zakhap @jessmart1213 
Hey, y'all! 
The checklist asks that the headers match the design system. However, the styles provided in the Forum Improvements Figma do not match the design system. Which header designs are correct? 
In addition, if the designs in the Figma are the ones I should follow, I'll also need the styling for headers 4 - 6.

**Comment by zakhap** [comment]
As @jessmart1213 said in DMs: 
> While we allow user in markdown to create headers 1-6, headers 3, 4, 5, 6 will all render as an editor H3.

**Comment by Miaplacidus** [comment]
Updated pointing to account for trickiness of table border rounding and todo checklist (this should be pulled into separate card; more on that later)

**Comment by Miaplacidus** [comment]
@jnaviask @ForestMars @zakhap @jessmart1213 
Styling a checkbox is tricky. I'm thinking we'll need to use JS to find the checkbox inputs and replace them with our checkboxes / modify them to get the styling we want. Any thoughts?

**Comment by zakhap** [comment]
> Styling a checkbox is tricky. I'm thinking we'll need to use JS to find the checkbox inputs and replace them with our checkboxes / modify them to get the styling we want. Any thoughts?

This kind of detail is much lower priority that the bulk of the tickets in the Editor Cleanup Milestone. I suggest we make sure that checkboxes render in a default style and make a WIP Follow ticket that documents this (and any other) difficulties to be handled subsequently.

**Comment by Miaplacidus** [comment]
@zakhap My thoughts exactly. New ticket incoming!

**Comment by Miaplacidus** [comment]
@zakhap @jessmart1213 @ForestMars @jnaviask 
Follow-up proto-ticket created here: #6309
