### ISSUE TITLE
Comprehensive Markdown Support (Part 2: Extended Functionality)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6036]
## Description

This is part 2, related to #6035. These are NTH features to our basic markdown support. 

## Project Owner

@zakhap 

## Acceptance Criteria

- Inline Typography:
  - [x] subscript
  - [x] superscript
- Tables
  - [x] [Custom set Alignment](https://www.markdownguide.org/extended-syntax/#alignment)
- [ ] Footnotes
- List
  - [x] Definition Lists

**Comment by Miaplacidus** [comment]
@CowMuon @jnaviask 
Was this intentionally prioritized before Part 1?

**Comment by Miaplacidus** [comment]
@jnaviask @ForestMars 
We're using the `marked` package to parse markdown. To parse footnotes, we can potentially extend `marked`'s functionality using the `marked-footnote` package, but that would require that we bump up the version of `marked` from 4 to 7. That's a significant jump, so I wanted to check in as to whether we want to do that now or leave footnote functionality (and the required bump) to a ticket further down the line.

**Comment by jnaviask** [comment]
@Miaplacidus can we do what we did with Part 1, and get a PR up for all changes except footnotes, then open another ticket for footnotes, which can include bumping Marked support? Then we can evaluate the point estimation for upgrading markdown separately from the rest of the changeset. cc @CowMuon

**Comment by jnaviask** [comment]
I will also note, I don't see a TON of breaking changes between the upstream current v11 and our v4 -- only some deprecated options (which we need to determine if we're even using) + node version bumps (we're already on node v18 so we should be OK).

**Comment by CowMuon** [comment]
@jnaviask @Miaplacidus Seems like this [ is not going to get into the v0.9.1 release for shipping on Monday. Can we put a branch up with updating marked from v4 to v11, and then tomorrow we can decide whether to roll it in or roll forward.

**Comment by Miaplacidus** [comment]
@jnaviask @ForestMars 
Created a ticket here #6338
