### ISSUE TITLE
New tag under suggested communities

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6037]
## Describe the bug
The '8 New' tag is not supposed to show

## To Reproduce
Log into commonwealth the tag is showing under the suggested communities on the right

## Expected behavior
The tag should not happen

## Additional context
![image](https://github.com/hicommonwealth/commonwealth/assets/144931524/6a2f1c1c-6e2a-4277-a668-73d4c5379a02)
<img width="298" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/144931524/3f5fc03d-3234-4c02-ac70-3f3bca7c8227">

**Comment by CowMuon** [comment]
Thanks for including screencaps of slack convo here @cowballzach! 🙌
