### ISSUE TITLE
Demo: Mixpanel error: Bad HTTP status: 0

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6041]
## Describe the bug

**Branch:** Master
**ENV:** Demo

When user land on dashboard we have console errors for mixpanel

```
5932.292fc22a.js:2 Mixpanel error: Bad HTTP status: 0 
error @ 5932.292fc22a.js:2
```

## To Reproduce

1. Go to: https://dydx.affinity.fun/
2. Sign up

## Expected behavior

We should not have console errors

## Additional context

Image:
https://app.screencast.com/oMcu9VpikVNwS

**Comment by Israellund** [comment]
@ilijabojanovic said to close this ticket as the bug is not present on qa and production. 


![Image](https://github.com/hicommonwealth/commonwealth/assets/69872984/0b92b2c8-ce5e-4420-abef-fe6a6314e803)
