### ISSUE TITLE
Gating: Community admin can publish empty comment on gated threat

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6044]
## Describe the bug

**Branch:** Master
**ENV:** Demo

When community admin who don't meet criteria for gated topic click on submit, we save empty comment. We should disable options of gated topic.

## To Reproduce

1. Go to: https://dydx.affinity.fun/
2. Sign up
3. Create EC20 community
4. Create groups 
5. Go to some gated topic
6. Click on submit for comment

## Expected behavior

User should not be able to submit comment

## Additional context

Video:
https://app.screencast.com/rpC4FX10GgbVP

**Comment by mzparacha** [comment]
not reproducible, discussing in slack.

**Comment by jnaviask** [comment]
We should NOT disable admin functionality if they don't meet the gating threshold -- we should allow them to post!
