### ISSUE TITLE
Bug: Members Table, Sorting by Groups is funky

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6071]
## Describe the bug

On Members Table, Sorting by Groups is not sorting by Groups!

## To Reproduce

- Go to /ethereum
- Click Up or Down on the Table column "Groups"
- See if it sorts

## Expected behavior

- The table sorts! Alphabetically by Group Name + in reverse order.

## Additional context

https://www.loom.com/share/ed78cf649c984af6b7086e82069ade6f

**Comment by mzparacha** [comment]
Looks like custom sorting is not implemented in the `CWTable`, will look into it.
