### ISSUE TITLE
Quill Delta pushed when creating a thread

### ISSUE THREAD

**Issue by RhysCommonwealth** [hicommonwealth/commonwealth#6074]
## Describe the bug
When pasting links in RichText on Chrome this happens: 
![Screenshot 2023-12-15 at 6 16 34 PM](https://github.com/hicommonwealth/commonwealth/assets/88511608/99215218-3084-484f-9428-70426aa3bcd3)
 thread link: https://commonwealth.im/cmn-protocol/discussion/14536-create-community-conversion

## To Reproduce
1. start drafting a thread in a community on Chrome (I wasn't able to replicate on Brave)
2. paste longer links in the text editor
3. post thread

## Expected behavior
Only the link should show up when pasting a link

**Comment by jnaviask** [comment]
Dupe
