### ISSUE TITLE
Community Live image fails to display

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6084]
## Describe the bug 
The graphic/image that is on the "Community is Live" screen within Create Community fails to display 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/4d4f3f55-eadd-46d6-9ee0-a87a84be4912)

## To Reproduce
- go to https://qa.commonwealth.im/createCommunity
- create a community
- Notice the third screen - Community is  Live 

## Expected behavior 
Image that is part of "Community is Live" screen gets displayed

**Comment by jnaviask** [comment]
PR did not fix broken image.
