### ISSUE TITLE
Create Community - Social Links Not Appearing

### ISSUE THREAD

**Issue by jabell88** [hicommonwealth/commonwealth#6086]
## Describe the bug
When creating a community, the social links section isn't appearing. The header section is displayed but the UI element is missing.
<img width="617" alt="Screen Shot 2023-12-18 at 1 05 05 PM" src="https://github.com/hicommonwealth/commonwealth/assets/148801576/b13d96ad-102c-4293-8db5-ad9143582b4a">

## To Reproduce
Chrome - Macbook Pro
Version 120.0.6099.109 (Official Build) (x86_64)

**Comment by sachben91** [comment]
not able to replicate this on my side but Jared replicated twice on his side

**Comment by mzparacha** [comment]
I am also not able to replicate it. Seems to be something system-specific.

https://github.com/hicommonwealth/commonwealth/assets/51641047/f2cb4619-5cc3-47f7-aeee-b2bdabbeaad2

**Comment by masvelio** [comment]
Not reproducible for me neither. We don’t have any specific code for social links inputs, no special styling, rules, breakpoints etc so I have no idea why this happens to Jared.

**Comment by jnaviask** [comment]
Can't reproduce.

**Comment by jabell88** [comment]
@masvelio Confirmed with Jake that the Ad Blocker was causing a conflict with the component in my chrome
