### ISSUE TITLE
[Spike] Determine common.xyz migration effort

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#6091]
## Description

As part of the rebrand initiative aiming at Common 1.0, we want to change the Commonwealth application's top level domain name from commonwealth.im to common.xyz.

If we were a static site, this would be as easy as updating the DNS entry. However, we have a relatively significant set of considerations when it comes to changing the site's URL. Consider the following:

- How to ensure extant links still work?
- What is the list of configurable services that need to have URLs/whitelists/domain-based configuration updated ([there's a first pass on notion](https://www.notion.so/buildcommon/Rebrand-43db1a64d94848118ac5e4a48c839620?pvs=4#82a172aa22a046c7b69822deaf60c723))? What about environment variables? Email senders? API users?
- Is the domain name hard-coded anywhere in the codebase and will need to be updated or made domain agnostic?
- Are there any considerations involving certificate issuance when we make the cutover?

There may be other questions I'm missing -- this is just a first pass of things to consider in planning the cutover.

## Deliverables

1. A list of specific sites in terms of areas of the codebase or infrastructure including external tools that will need to be modified to migrate the domain name.
2. A step-by-step plan for migrating the domain without significant (or ideally, any) downtime, preserving all incoming links.

## Timebox

4 hours.

**Comment by jnaviask** [comment]
@timolegros I've assigned you to this spike -- but feel free to loop in the rest of the engineering team as needed. @ianrowan may be able to help you with web3-specific service configurations. @kurtisassad may know about cloudflare or webpack or other pieces of external infra. @gdjohnson and I can also help provide old feature-related info as needed.

**Comment by dillchen** [comment]
Here is a draft list [link](https://www.notion.so/buildcommon/Rebrand-43db1a64d94848118ac5e4a48c839620?pvs=4#82a172aa22a046c7b69822deaf60c723)

**Comment by timolegros** [comment]
Will be starting this with @kurtisassad next week when most of the engineering team is out.

**Comment by HIM92** [comment]
The product team discussed adding an account/user mapping system to the URLs today. We would like to consider copying reddit's URL styling replacing "r" with "c" such that an example of our new rebranded URL system would be:

Community URL
"Common.xyz/c/aave" instead of "common.xyz/aave"

User URL
"common.xyz/u/dillonchen" instead of "common.xyz/profile/id/12345"

Could we add exploring the effort of this work to the current spike?

**Comment by timolegros** [comment]
> The product team discussed adding an account/user mapping system to the URLs today. We would like to consider copying reddit's URL styling replacing "r" with "c" such that an example of our new rebranded URL system would be:
> 
> Community URL "Common.xyz/c/aave" instead of "common.xyz/aave"
> 
> User URL "common.xyz/u/dillonchen" instead of "common.xyz/profile/id/12345"
> 
> Could we add exploring the effort of this work to the current spike?

I don't think that should be part of this spike as the change to such a URL scheme is separate from the domain changes - it requires much more extensive app/client level routing changes while the domain changes requires much more configuration env and of external services. That said, the spike for that scheme can build upon the findings and results of this spike. I think this will allow us to better streamline these sets of changes.

If anyone strongly disagrees I can include the research in this spike but those are my thoughts.

**Comment by timolegros** [comment]
Per conversation with @jnaviask @MuonShot this ticket is delayed until later next year (potentially till after Eth Denver). This is because we will not complete the domain migration before Eth Denver (due to associated risks) and the spike should be completed as close as possible to when we start the implementation (since external services can change and we need to cover all bases).

**Comment by ForestMars** [comment]
This closed. Updated assignment, Dillon will add new ticket
