### ISSUE TITLE
Community: Multiple social links are not saved in community admin page

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6119]
## Describe the bug

**ENV:** QA
**Branch:** Master
## To Reproduce

1. Go to https://qa.commonwealth.im/
2. Sign up
3. Create new community 
4. On create page add multiple social links
5. Lunch community 
6. Go to community management screen 
 
## Expected behavior

All links entered on create page should be visible on admin page

## Additional context

Video:
https://app.screencast.com/etzXImQBBC8n0

**Comment by kurtisassad** [comment]
This is more a design issue. Since we can add arbitrary amounts of social links, it doesn't make sense to display them on the old structured update community page.

I think we need a new design for the manage community page that involves managing arbitrary social links

**Comment by kurtisassad** [comment]
For more context. In this loom you have 3 random website links. On the manage community page, only the first one is displayed (http://test.com). We don't have enough fields to support displaying all of them.

**Comment by sachben91** [comment]
Talked with design about this. Let's disable and not display the social links section on Create Community flow for the time being. Its optional anyway and the user can add them from manage community page. 

The longer term fix is to change the manage community page to have same social link behavior as the user profile page. That is the component that design based this off. We will add that to the admin onboarding milestone and then we can re-add the social links on here.
