### ISSUE TITLE
Reorganize project dependencies

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#6123]
## Description
Organize project dependencies following these conventions:

### Project Structure

- All dev dependencies should be at the root level, including test packages and typescript related packages (typescript, ts-node, ts-node-dev, ts-mocha, etc)
- All @types are dev dependencies (root level)
- Packages are either /libs or /services (packages). Libs are reusable, Services are deployable.
- Dependencies should be added to packages (workspace), including dependencies to /libs
- Check using `yarn workspaces info`

### Testing (Let's debate)

- All testing scripts should be defined and started at the root level, including coverage options
- Each package should define a `build` script
- Packages can be individually built with `yarn workspace package build` or we can trigger a full build with `yarn workspaces build`

## Project Owner
@Rotorsoft

**Comment by jnaviask** [comment]
@Rotorsoft is this completed with #6096 ?

**Comment by Rotorsoft** [comment]
not yet, this one is about dependencies in all package.json files... a little messy right now

**Comment by Rotorsoft** [comment]
Resolved in #6149
