### ISSUE TITLE
Mobile Landing Page Nonresponsive to Button Press

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#6125]
## Describe the bug
Non responsive clicks on the landing page on mobile Safari

## To Reproduce
Go to Mobile Safari, on device. Without any cached version. Page should load but it won't respond to clicks.

Upon later click out it works???

## Expected behavior
Clicks should work

## Additional context

https://commonxyz.slack.com/archives/C051XFN57FT/p1703087586961349

Hard to reproduce, only reported on Mobile Safari

**Comment by lzach83** [comment]
I can't reproduce -- i've attempted on multiple devices with no cache. If this occurs and we happen to catch it on loom, will reopen.
