### ISSUE TITLE
Groups V1.5: Members Page Filter update

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6142]
## Description

Filter on Members Table currently only checks "in group" or "not in group". Growth and Users have wanted to filter by Group. See images in Additional Context for clarity.

## Project Owner

@zakhap + Jared

## Engineering Requirements

- Update API for table to filter by specific Groups
- TBD

## Acceptance Criteria

Dropdown Menu for Filter should be updated to have the following options: 

- [ ] "All Groups" => no filter applied, default option
- [ ] "Ungrouped" => users not in any group
- [ ] Enumerate the Groups within the community => if selected, only show members in that Group.

## Additional context

<img width="433" alt="Screen Shot 2023-12-21 at 7 59 09 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/270c3432-f422-4017-ac50-a670bda477f4">
<img width="295" alt="Screen Shot 2023-12-21 at 7 59 12 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/8f08c540-1d93-4dc0-ad82-ddd9846c62af">

**Comment by zakhap** [comment]
@zakhap To update with Groups Tab Filter as well

**Comment by mzparacha** [comment]
Added `2` points for frontend related changes.
