### ISSUE TITLE
CI cosmos chains show up on the new community creation form

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#6146]
## Describe the bug

The Evmos, Beta, and V1 Cosmos CI chains are selectable options on the cosmos community creation form. Additionally the sandbox chain nodes are available but this may be intentional.

## To Reproduce

- Create a cosmos community

## Expected behavior

CI cosmos chains used for testing should not show up in production.

**Comment by CowMuon** [comment]
@Rotorsoft visibility
