### ISSUE TITLE
Update the Layout and Selections on the Create Thread Page

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#6148]
## Description

We are addressing some concerns with the layout and visibility of certain few fields such as stage selection. And on unscoped pages, we introduce a field to choose the community a user wants to post in.

This is important because we will have a create button visible on desktop in Top Nav, and on mobile either with a **FAB** or some other method

## Project Owner
PM: @zakhap 
Designer: **Jared**

## Acceptance Criteria

**From Within A Community** [DevLink](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&node-id=187-8484&mode=design&t=k8kvqpD2YgVmMYBf-0)

- We should note visually that selecting a stage is optional by greying it out more
<img width="888" alt="Screen Shot 2024-01-04 at 10 58 14 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/f8a28042-2050-490f-94a9-1e3e2dd7367f">

- When Selecting a Community, the User should only be able to select from communities that they have actively joined

## Additional context
- The Sidebar Element should not yet be updated, that will be done in a separate ticket #5939 where more full behavior will be specified

**Comment by mzparacha** [comment]
> We should note visually that selecting a stage is optional by greying it out more

I am not sure what 'stage' refers to, is it the form field?

> When Selecting a Community, the User should only be able to select from communities that they have actively joined

We don't have a universal create option for threads right now, so I think this is out of the scope of this ticket?

cc: @zakhap plz confirm

**Comment by mzparacha** [comment]
Marking `5` since it includes quill editor updates.

**Comment by zakhap** [comment]
> > We should note visually that selecting a stage is optional by greying it out more
> 
> I am not sure what 'stage' refers to, is it the form field?
> 


Stages are a type of tag we support on Threads. As it exists in our Product now, you can only add a Stage to a Thread after the Thread is created. Stages are set by the community (see the admin panel Stages input and the Update Stage Modals). 


> > When Selecting a Community, the User should only be able to select from communities that they have actively joined
> 
> We don't have a universal create option for threads right now, so I think this is out of the scope of this ticket?
> 

That is correct. Let's not include that on this page right now.

**Comment by mzparacha** [comment]
I did some updates to the quill editor but noticed that the quill editor updates already have a dedicated ticket https://github.com/hicommonwealth/commonwealth/issues/5949. Leaving my diff here if it helps for ticket.

[quill-editor-updates.txt](https://github.com/hicommonwealth/commonwealth/files/13889022/quill-editor-updates.txt)


cc: @Miaplacidus since you are assigned there.
