### ISSUE TITLE
[SPIKE] Mutation Events →  MutationObserver API

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#6182]
## Description
Per #6171  we need to refactor client code to remove any mutation events, to be replaced by MutationObserver API. 

Please see that ticket for relevant details, OTN that Mutation Events were deprecated by W3C 12+ years ago, and have not been finally removed from most major browsers (chickens coming home to roost, as we say.) 

## Acceptance Criteria
Write up describing scope of impact (severity/surface area) of problem with recommendations for refactoring. 

## Additional context
We need to decide whether executing these changes will be in scope before or after Denver. Also for implementation, as always, Safari tends to have its own implementation of web standards, so not to assume it will "just work" like Chrome (or Firefox.) 

## Additional resources
https://developer.chrome.com/blog/mutation-events-deprecation

**Comment by CowMuon** [comment]
Cc. Marcin mainly for visibility.

**Comment by CowMuon** [comment]
See instigating story: #6171

**Comment by kurtisassad** [comment]
Spike not needed, see here: https://github.com/hicommonwealth/commonwealth/issues/6171#issuecomment-1875441517

Feel free to close this ticket if no other issues.
