### ISSUE TITLE
Update variable semantics for /server directory – child of #5290

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#6194]
## Files to update

Utils/scripts
- databaseValidationService.ts
- linkingValidationHelper.ts
- setupAppRoutes.ts
- imageUrlMigration.ts
- emailDigest.ts
- deleteEntities.ts
- addEntities.ts

Webhooks* (req updates)
- Webhook/utils.ts
- getWebhookData.ts
- dispatchWebhook.ts
- updateWebhook.ts
- getWebhooks.ts
- deleteWebhook.ts
- createWebhook.ts

Groups
- validateTopicGroupsMembership

Session Keys
- verifySessionSignature.ts

Roles
- roles.ts
- setDefaultRole.ts
- 

Topics
- update_topics_order_handler.ts
- update_topic_handler.ts
- update_topic_channel_handler.ts
- get_topics_handler.ts
- delete_topic_handler.ts
- create_topic_handler.ts
- get_bulk_threads.ts
- orderTopics.ts
- editTopic.ts (delete)

Threads
- update_thread_handler.ts
- update_thread.ts
- get_threads_handler.ts
- create_thread_poll_handler.ts
- create_thread_handler.ts
- viewCount.ts
- viewComments.ts
- threadUsersCountAndAvatars.ts
- bulkOffchain.ts
- get_bulk_threads.ts

Comments
- create_thread_comment_handler.ts
- update_comment_handler.ts
- search_comments_handler.ts
- delete_comment_handler.ts
- search_comments

Address
- createAddressHelper.ts
- createAddress.ts
- verifyAddress.ts
- updateAddress.ts
- setWalletAddress.ts
- linkExistingAddressToChain.ts
- getBannedAddresses.ts
- getAddressStatus.ts
- getAddressProfile.ts
- deleteAddress.ts
- banAddress.ts
- lookupAddressOwnedByUser.ts

Roles
- upgradeMember.ts

Status
- status.ts

Custom Domain
- updateChainCustomDomain.ts

Community
- updateChainCategory.ts
- update_community.ts
- selectChain.ts
- starCommunity.ts
- getSubscribedChains.ts
- domain.ts
- communityStats.ts
- validateCommunity.ts

Banner
- updateBanner.ts

Reactions
- create_comment_reaction_handler.ts
- create_thread_reaction_handler.ts

Subscription
- createSubscription.ts
- errors.ts (subscription)

Proposals
- getProposalVotesHandler.ts
- getProposalsHandler.ts
- proposalTemplate.ts
- templates.ts
- server_proposals_controller.ts

Profiles
- search_profiles_handler.ts
- search_profiles.ts

Votes
- update_poll_vote_handler.ts
- delete_poll_handler.ts

Groups
- update_group_handler.ts
- refresh_membership_handler.ts
- get_groups_handler.ts
- delete_group_handler.ts
- create_group_handler.ts

Discord
- discord.ts
- delete_comment_bot_handler.ts
- setDiscordBotConfig.ts
- getDiscordChannels.ts

Admin
- exportMembersList.ts

Misc
- editSubstrateSpec.ts

Wallets/Login
- magic.ts
- startEmailLogin.ts

**Comment by timolegros** [comment]
The remaining work after https://github.com/hicommonwealth/commonwealth/pull/6402 is merged:
- `server/util/`
- `server/workers/`
- `server/scripts/`
- `server/routing/`
- `server/passport/`
- `server/middleware/`
- `databaseValidationService.ts`
- `server/types.ts`
- `server/controllers/`
  - `server_admin_methods/`
  - `server_profiles_methods/`
  - `server_threads_methods/`
  - `server_proposals_controller.ts`
- `server/routes/`
  - `addEntities.ts`
  - `authCallback.ts`
  - `communityStats.ts`
  - `/contracts/`
  - `/subscription/`
  - `deleteEntities.ts`
  - `editSubstrateSpec.ts` (can potentially deprecate)
  - `editTopic.ts` (deprecate?)
  - ... a bunch more -> redo text search upon completion of other directories

Also included: Chain parameter in all notification emission https://github.com/hicommonwealth/commonwealth/issues/4372

**Comment by rbennettcw** [comment]
I've split these out into a new ticket:
```
server/util/
server/workers/
server/scripts/
server/routing/
server/passport/
server/middleware/
databaseValidationService.ts
server/types.ts
```
https://github.com/hicommonwealth/commonwealth/issues/6782

**Comment by rbennettcw** [comment]
Created new ticket for controllers dir:

```
server/controllers/
server_admin_methods/
server_profiles_methods/
server_threads_methods/
server_proposals_controller.ts
```

https://github.com/hicommonwealth/commonwealth/issues/6850

**Comment by timolegros** [comment]
This ticket is now complete.
