### ISSUE TITLE
Refactor project configuration

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#6200]
## Description
Refactor project configuration with new conventions

## Project Owner
@Rotorsoft 

## Engineering Requirements
- Completed in #6205
  - All workspaces should have a consistent set of scripts to `clean`, `build`, `check-types`, (etc) that can be executed all at once using `yarn workspaces run <script>` 
  - Workspaces should have a `src` folder standard (let's keep commonwealth the way it is though).  
  - Remove unnecessary exclude statements in `tsconfig` files 
  - Add rootDir and project references  
- Add `sanity` script at root level to `check types`,`lint`, and `unit test` before pushing code

## Acceptance Criteria
- Builds, tests, and deploys

**Comment by gdjohnson** [comment]
> All workspaces should have a consistent set of scripts to clean, build, check-types, (etc) that can be executed all at once using yarn workspaces run <script> - @gdjohnson do we have something like this in the docs?

Nothing quite like you're envisioning—we have some individual scripts along those lines for individual packages/workspaces, but nothing that ties them together, and not in any comprehensive way. See the Package-Scripts.md file for full documentation

**Comment by Rotorsoft** [comment]
Thanks @gdjohnson, adding documentation step to the list - this should simplify the workflows
