### ISSUE TITLE
Links are broken in pasted json file

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6225]
## Describe the bug

ENV: Production 
Branch/Release: All

Pasted link is broken in thread.

## To Reproduce

1. Go to: https://commonwealth.im/cmn-protocol/discussion/14536-create-community-conversion

## Expected behavior

Url should be properly embedded

**Comment by zakhap** [comment]
@ilijabojanovic this is not JSON => this is the Quill Delta format. What I see here is that our text body is rendering the Quill Delta format as plaintext/markdown. If this is happening site wide and is not a user error (toggling between Rich Text and Markdown), this would be P1 as content everywhere would be broken.

**Comment by CowMuon** [comment]
This doesn't appear to be a sitewide breakage. Apparently auto link detection is if you paste a json blob with a link inside it, it doesn't parse correctly. 

"Regex is hard." -Jake

**Comment by CowMuon** [comment]
@zakhap What's the severity/priority here?

**Comment by zakhap** [comment]
I don't think this should be prioritized at this time. I think this is downstream of a different kind of user error which we will resolve by deprecating Quill Delta Format. I do not believe the user intended to just paste JSON directly into the body of the thread like this.

**Comment by CowMuon** [comment]
Thanks @zakhap!

**Comment by lzach83** [comment]
> we will resolve by deprecating Quill Delta Format

Don't tease me! Thank you @zakhap

**Comment by jnaviask** [comment]
No longer needed.
