### ISSUE TITLE
Domain change for Terra Classic Community

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6256]
## Describe the bug
Community want their domain to change from: /terra-luna-classic-lunc To: /terra-classic-community

https://commonwealth.im/terra-luna-classic-lunc/discussions 

## Additional context
I know it's a weird request and they are not using the custom domain correctly but if we could make that low hanging fruit change that would be fantastic.

**Comment by CowMuon** [comment]
@kurtisassad Can you please show @Israellund how we do this, so we can reduce our lottery factor here by 1?

**Comment by CowMuon** [comment]
@kurtisassad Can you please show @Israellund how we do this, so we can reduce our lottery factor here by 1?

**Comment by mhagel** [comment]
Note `terra-classic-community` is already taken. This may not be a request we can do 

@kurtisassad @Israellund @ForestMars

**Comment by cowballzach** [comment]
Closing bug ticket, they understood that the domain change could not take place as that name is already taken. TY guys

**Comment by CowMuon** [comment]
When we say `/terra-classic-community` is "already taken", is that actually an active community? Or is it just a dead namespace? Because I am not seeing any discussions, proposals, or, indeed, any members. (members = 0?) @mhagel @cowballzach @zakhap
