### ISSUE TITLE
Delegate tab Unnecessary in Diva Staking Community

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6277]
## Describe the bug
The delegate tab should not be showing up in the Divastaking community

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reproduction steps
Go to https://commonwealth.im/divastaking/discussions & head to https://commonwealth.im/divastaking/delegate 

## Actual behavior
delegation tab should not appear

## Expected behavior
There should be no delegate tab

## Screenshots / Video
![image](https://github.com/hicommonwealth/commonwealth/assets/144931524/9dc1b1c3-5154-4575-9300-89f3e16c6ba5)
https://www.loom.com/share/15c3a0d5a8aa4c3c8cb36829cc3c7c94?sid=7c8d690b-5f20-4984-830f-01bb4813ca80

## Reporter
Growth team Mark

**Comment by cowballzach** [comment]
it's fixed ty!

**Comment by jnaviask** [comment]
Still open as of 0.9.4. Ensure you've joined the community in question.

**Comment by CowMuon** [comment]
Should be 1 point? @mw2000

**Comment by mw2000** [comment]
@CowMuon have pushed a simple fix for this that should stop any further communities like Divastaking (which use the GovernorCountingSimple contract for governance) from the ghost Delegate button. However, this fix still papers over what we actually need to do, which is refactoring the way we are classifying Governance contracts into separate networks - Aave and Compound, and make it more modular.
