### ISSUE TITLE
Stargate Finance Failed to Create Thread Error

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6301]
## Describe the bug
A stargate user is trying to post in a gated topic, they have the required token to post and an error message pops up when they try to post.  

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reproduction steps
Try to post a thread for the stargate finance community

## Expected behavior
The thread should be posted when they have the required token for a gated group

## Screenshots / Video
<img width="911" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/144931524/20293327-e30c-4c02-837d-dfc94f771a80">

## Reporter
External from Stargate Finance

## Additional context
https://commonwealth.im/profile/id/130937 that is the user profile
Their wallet address: 0xB453Cb3b96101e597eF0CF201a92777f721849ae
https://commonwealth.im/stargatetoken/discussions
https://commonxyz.slack.com/archives/C051XFN57FT/p1704897243941699

**Comment by jnaviask** [comment]
@RhysCommonwealth @cowballzach to confirm whether this is resolved following #6300

**Comment by RhysCommonwealth** [comment]
@cowballzach & I can't QA since we have god mode and are running into bugs trying to connect wallet addresses to non-god mode accounts. Is eng able to QA this? I'm not asking the effected user to try it until we are confident it is fixed

**Comment by RhysCommonwealth** [comment]
Sure. Mitchy sent me this loom showing the bug: https://www.loom.com/share/0555a42099b44fb0a1dcf6bef2b118ec it is not ticketed. The bug occurs when a user is creating another CW account & is connecting a MM address that is within the same MM account as an address that is already connected to a different CW account.

**Comment by jnaviask** [comment]
@RhysCommonwealth can you ticket the metamask issue with details please? Is there any reason we haven't reported this formally?

**Comment by cowballzach** [comment]
just ticketed the issue here, just happened an hour or so ago. https://github.com/hicommonwealth/commonwealth/issues/6320
@jnaviask
