### ISSUE TITLE
Sign in issues with Station, Keplr, & Leap Wallet

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6303]
## Describe the bug
Users are having issues issues signing into their account through station, keplr, & leap wallets. This sign in issue is also accompanied by the home page feed not loading. 

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reproduction steps
Sign into Common using either station, keplr, or leap

## Expected behavior
Sign in should work as normal

## Reporter
External Client - Cheqd

## Additional context
https://commonwealth.im/cheqd/discussions
https://commonxyz.slack.com/archives/C051XFN57FT/p1704903337340409
https://commonxyz.slack.com/archives/C01RC895479/p1704899526697459
https://github.com/hicommonwealth/commonwealth/pull/6300

**Comment by mhagel** [comment]
Keplr and Leap seem fine. 

Should we focus this ticket on Station? @cowballzach

**Comment by jnaviask** [comment]
Closing as this ticket was related to an RPC endpoint error with Cheqd, since resolved. We should open a separate ticket to bump station support for station v3. We can also reopen this ticket when we can reproduce reliably.

**Comment by cowballzach** [comment]
https://github.com/hicommonwealth/commonwealth/issues/6323
Ticketed just Station here, TY ENG!
