### ISSUE TITLE
Generalize Styling for Drawer Component

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6325]
Drawer component styling assumes that the drawer will only expand from the right. This tickets asks that the styling be generalized for the drawer expanding from the top, bottom, and left, as well.

Will require some design input from @jessmart1213 as to top and bottom expanding drawers.

@zakhap @ForestMars @jnaviask @dillchen

**Comment by dillchen** [comment]
Let’s keep scope to only from the right, please do spin up a separate
ticket WIP and we can follow up later

Sent via Superhuman iOS ***@***.***>

**Comment by Miaplacidus** [comment]
@dillchen 
This ticket is the new one. Feel free to add any details you'd like here.

**Comment by dillchen** [comment]
I see, apologies

Sent via Superhuman iOS ***@***.***>
