### ISSUE TITLE
Markdown Support: Footnotes

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6338]
Users should be able to create footnotes. 

This should be as simple as 
1. upgrading the `marked` package from 4 to 7 (the minimum required version to use `markdown-footnotes`
2. installing `markdown-footnotes`
3. extending `marked` with the above package

Reference ticket: #6036

**Comment by Miaplacidus** [comment]
Tagging for reference:
@jnaviask @ForestMars @zakhap @jessmart1213

**Comment by jnaviask** [comment]
@Miaplacidus what would the difference in effort be to bump marked to v11, if it would be useful to have a higher version than 7?

**Comment by Miaplacidus** [comment]
@jnaviask 
Fair question! How about I bump first to 7, implement the footnotes extension, and check that nothing breaks? Then I'll give the bump to 11 a shot. Thinking that should be pretty smooth, but will adjust points if there are Michael Bay style explosions.

**Comment by jnaviask** [comment]
Sounds good to me. @Miaplacidus

**Comment by Miaplacidus** [comment]
@jnaviask 
Bumped to 11. No cinematic explosions.
