### ISSUE TITLE
Groups api returns 400 error

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6351]
## Describe the bug

When  user lands on Members page we have 400 error for `api/groups` endpoint
### Initial conditions

**Environment:** 
QA

**Branch/Release version:** 
Master/v0.9.1 tag

**Browser:** 
All

**Wallet:** 
All

## Reproduction steps

1. Go to: https://qa.commonwealth.im/
2. Sign in
3. Create new community 
4. On left sidebar navigate to members page

## Actual behavior

We have 400 error in console

## Expected behavior

We should not have any console errors

## Screenshots / Video

https://app.screencast.com/iiiWA6RYH2tpm

**Comment by mzparacha** [comment]
Not reproducible in qa and local.


https://github.com/hicommonwealth/commonwealth/assets/51641047/275b64c8-19df-4725-be60-b9004daea133

cc: @ilijabojanovic @jnaviask

**Comment by mzparacha** [comment]
Reproduced, fixing...

**Comment by mzparacha** [comment]
Is a 1 pointer basically, but for some reason react-query is not disabling query when community data is still loading. Figuring it out.
