### ISSUE TITLE
Remove tsc-alias

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#6362]
## Description
Evaluate the use of tsc-alias after all the refactoring work is complete, and determine if it can be removed.

## Project Owner
@Rotorsoft 

## Engineering Requirements
- Evaluate the need of tsc-alias, pros and cons.

**Comment by ForestMars** [comment]
Is this still needed? @Rotorsoft please close if not.

**Comment by Rotorsoft** [comment]
@kurtisassad should we close this one? What's the other ticket #?

**Comment by Rotorsoft** [comment]
tsc-alias remains in packages/commonwealth for rewriting imports after builds
