### ISSUE TITLE
Synonym Finance Custom Domain

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#6365]
## Describe the bug
https://commonwealth.im/synonym-finance/overview to point to forum.synonym.finance can you ticket 

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reporter
External Client Synonym Finance

## Additional context

https://commonxyz.slack.com/archives/C051XFN57FT/p1705422885929069

**Comment by jnaviask** [comment]
DNS target relayed to client.
