### ISSUE TITLE
Sign-in w Google Option should use Google Modal instead of redirect

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6385]
## Description

Our current sign-in flow, when selecting the Google Account option, redirects you through the Google Auth Flow.

Desired update: use the Google Sign-in Modal instead of redirecting away from the App. 

Dev Link: https://www.figma.com/file/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?type=design&node-id=456-16914&mode=design&t=jJaTjedfeMYaw8QS-0

## Project Owner

PM: @zakhap 
Designer: Jared

## Acceptance Criteria

- Use Google Auth in Modal instead of redirecting away from App.

## Additional context

<img width="324" alt="Screen Shot 2024-01-17 at 5 27 28 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/ddb2d8be-cfab-47b3-b4e1-5785c5faf4e3">

**Comment by zakhap** [comment]
@jnaviask: not sure if this ticket is possible because we rely on the Magic API here. To be reviewed.

**Comment by CowMuon** [comment]
@jnaviask: Will it be possible to use modal instead of redirect here?

**Comment by CowMuon** [comment]
@jnaviask: Will it be possible to use modal instead of redirect here?
@zakhap: What are considerations/consequences if we bounce this past Denver?

**Comment by CowMuon** [comment]
Kicking this post-Denver @mzparacha @jnaviask

**Comment by jnaviask** [comment]
Unsupported by magic.link.
