### ISSUE TITLE
Sign-in: WalletConnect Option utilizes Web3Modal

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6387]
## Description

For EVM wallets (as deemed useful in #5979).

When the WalletConnect option is selected from the Sign-in Modal, trigger the usage of Web3Modal.

## Project Owner

PM: @zakhap 
Designer: Jared

## Acceptance Criteria

- [ ] Use Web3Modal for EVM Wallet Options.

## Additional context

<img width="529" alt="Screen Shot 2024-01-17 at 5 38 26 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/80d57e12-5fbb-41b9-b45f-3a97a48304be">

**Comment by dillchen** [comment]
We should Web3Modal be presented as the option (instead of WalletConnect) in the first place? 

Otherwise seems confusing to show Wallet Connect -> then Show A Bumch of other options where WalletConnect is one of the options @zakhap
