### ISSUE TITLE
Implement new mobile navigation

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6389]
## Description
Improvements to navigation components on mobile (screen size < 600px). Currently, navigation on mobile is hard and unintuitive and not optimized for mobile. The improvements affect the sidebar, profile options, search, create, and notifications page. 

## Project Owner
Designer: @jessmart1213 
PM: @sachben91 

## Designs 
[Figma ](https://www.figma.com/file/w6Tli9ApqBqgsZa7kB0Vk5/Mobile-ideation-Q4?type=design&node-id=512%3A32252&mode=design&t=sG5uewocOzFvrYPE-1)
[Prototype ](https://www.figma.com/proto/w6Tli9ApqBqgsZa7kB0Vk5/Mobile-ideation-Q4?type=design&node-id=512-32252&t=Yj1nEy4UGcKGhn9w-1&scaling=min-zoom&page-id=512%3A26400&starting-point-node-id=512%3A32252&show-proto-sidebar=1&mode=design)
[Loom Video ](https://www.loom.com/share/c1841ec0ada946b4853dbc115e652ea9?sid=e1ce836f-f976-4587-bf60-df79256f786d)

### top nav
The top nav will have the double caret that opens up the sidebar, search icon that opens to the search page, and profile picture which opens the profile options sidebar

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/0c7e285d-274b-4150-b7db-593d550399ab)

### bottom nav
The bottom nav is a new component and will have home, create, explore and notifications options. The bottom nav will stick to the bottom on all pages other than when the user clicks into search or into the profile dropdown

<img width="440" alt="Screenshot 2024-01-17 at 11 04 26 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/fc202ee2-5d88-418b-a0e3-acdcc07be1da">

### Sidebar
- unscoped and non-community pages: For these pages, clicking on the double caret reveals the quick switcher page 
- for scoped page: clicking on the double caret shows the community sidebar along with the quick switcher which will take up the full size of the page
- when the sidebar is active, there is an overlay in the background or the curtain as it is referred to in the design system

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/d10cd874-22c3-472c-bb9e-460e5b40cf34)
![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/6d04fb4b-77ef-4ac1-ad3a-12ae0be2c07d)

### Search
- The top nav now has a search component, clicking on this takes the user to a new page where the user can enter their search and see the search results
- clicking on cancel takes the user back to the page that they were on previously 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/82270578-2bcf-465f-9869-7e3dbbbcf4b5)
![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/288427b2-f443-473b-ac9e-0efd17d40639)

### Profile options
- The profile option on the right top nav is now just the profile picture of the user
- When the user clicks on the profile picture, he would be shown the same options that we currently have under profiles, along with links to help documentation (which don't have a place otherwise) 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/cfffebd3-b923-408d-ae60-1387e387266b)

### Scoped pages (user within a community)
- Clicking on Create in the bottom nav opens up the create drawer which shows the create options that are available to the user - create community and create thread 
- On clicking "X" the bottom drawer is closed 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/904b7c72-d37b-4b4d-bf46-4a2296fd380a)

### Unscoped pages (user not within the community)
- Clicking on Create in the bottom nav opens up the create drawer which shows the create community option and no option to create thread 
- On clicking "X" the bottom drawer closes 
<img width="242" alt="Screenshot 2024-02-14 at 5 05 49 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/4e572031-1653-44c1-b45e-1d00e796ccca">

### Notifications 
- When the user clicks on Notifications they are directly taken to the notifications page (no pop-ups as it is currently designed) 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/a63c4223-03a7-4b00-8036-3736c5c8fe89)

**Comment by CowMuon** [comment]
Estimating this at 8, which means this ticket really needs to be broken out, at the very least into subtasks, or into separate tickets.

**Comment by rbennettcw** [comment]
Looks feasible. It's a rearrangement of existing functionality.

**Comment by rbennettcw** [comment]
I think 8 is a good estimate, since refactoring a high-level navigation UI (especially with a responsive layout) can require a bit of effort to get right.

Regarding the ticket breakdown, I recommend that the first ticket be a skeleton layout, and any subsequent tickets can be non-blocking work that fills in the skeleton.

**Comment by zakhap** [comment]
Is this still "Blocked" or can we update the tags?
