### ISSUE TITLE
Admin Capabilities Topics Enhancements

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6397]
This is a follow-up ticket on #6026 for the purposes of ensuring the use of common components across the Admin Capabilities menu. 

- [x] use CWForm on CreateTopicsSection
- [x] 'Revert Changes' button should be disabled if no topics have been re-ordered

**Comment by Miaplacidus** [comment]
Removed use of Community Management Layout as that would a) break styles for the topics page from what is shown in the designs b) would require changing the layout to accommodate tabbing. 

Will focus on ways to bring Topics page more in line with Community Management when possible/necessary.

**Comment by mzparacha** [comment]
Synced with @Miaplacidus and @Miaplacidus plans to address PR comments soon. Unassinging myself.

**Comment by Miaplacidus** [comment]
Per conversation with @jessmart1213 and @zakhap, we'll be removing UI that indicates that a user can create a topic and a thread simultaneously. Note that this functionality never worked to begin with, despite the UI indicating as such.
