### ISSUE TITLE
Return reaction data when using fetch bulk threads query

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6459]
The view threads page now displays a upvote viewing drawer (see issue #5509). The table within the drawer requires timestamp data on reach reaction it distplays. Unfortunately, the `__getBulkThreads` controller method does not return a `reactions` field (see `__getThreadsById` for comparison) where timestamp data for a reaction can be found. This needs to be added.

@jnaviask @CowMuon <-- please assign to whomever you believe would be best for this task.

**Comment by jnaviask** [comment]
@rbennettcw to evaluate whether this solution is correct and to propose alternatives, and then implement the change to ensure we can properly display timestamps per @Miaplacidus's request.
