### ISSUE TITLE
Update mobile home page to add "trending community" and new community card design

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6465]
## Description
Currently, the "suggested communities" section shows up on desktop in the sidebar on desktop. We want to make this section available on mobile, and also change the name of this section to "Trending communities" on both mobile and desktop.

## Project Owner
PM: @sachben91 
Designer: @jessmart1213 

## Design
[Figma](https://www.figma.com/file/w6Tli9ApqBqgsZa7kB0Vk5/Mobile-ideation-Q4?type=design&node-id=744%3A51924&mode=design&t=urprUi8Y7QZR2ALN-1)

## Feature specs 
- Update “Suggested Communities” copy to “Trending communities” copy on mobile + desktop
- "Trending communities" is stacked on top of the tabbed For you page feed. It utilized the same card component that was used in admin onboarding. The community card contains the name of the community and number of threads in the community. 
<img width="366" alt="Screenshot 2024-01-24 at 3 14 12 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/fd5d1520-64b4-4066-92a4-92cfb2582929">

- The user can use side scroll to browse the cards up to three communities (just as it is now in desktop), the fourth option is a call to action to "explore communities" that takes them to the explore communities page

<img width="555" alt="Screenshot 2024-01-24 at 3 17 09 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/cdd41b44-5125-4bbe-99ab-a7bb51d4d061">

**Comment by CowMuon** [comment]
JTN this was missing from mobile, and we will update the copy when we add to mobile.

**Comment by HIM92** [comment]
Dovetails with user onboarding as well

**Comment by CowMuon** [comment]
@mzparacha Would you like to estimate this one?

**Comment by mzparacha** [comment]
Looks like a `3` to me.
