### ISSUE TITLE
Cleanup: Improper User Model Association

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#6478]
Per conversation today with Zak, I confirmed that there is a 1:1 relationship between Users and Profiles. (i.e. a User may only have one Profile)

Our User model does not reflect this relationship, and a `hasMany` association to Profiles has lingered on. This is misleading as to the underlying structure of relationships between objects.

**Comment by CowMuon** [comment]
Tagging @Rotorsoft (since Graham has already self-assigned(?)) 

(Also JTN this story could stand improvement.)

**Comment by gdjohnson** [comment]
Closing in light of #5564
