### ISSUE TITLE
Mixpanel: Create a metric for form abandonment

### ISSUE THREAD

**Issue by calebcowmoon** [hicommonwealth/commonwealth#6480]
## Description
We need to track when a user starts a form and then abandons it, so we can improve the form experience so they will complete it, and therefore generate more content on the platform and drive overall engagement

## Project Owner
@Miaplacidus 

## Acceptance Criteria
Metric is viewable in Mixpanel, address, community, user ID, form that was abandoned

**Comment by jnaviask** [comment]
FullStory will have this data.
