### ISSUE TITLE
Cleanup: "Template" table should be renamed "Templates"

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#6482]
Across our database, we uniformly use the plural form of the noun for a given table, e.g. "Attachments," "Addresses," "Bans." 

The "Template" table breaks this pattern and a migration should be written to conform it to standard.

**Comment by CowMuon** [comment]
I really appreciate and agree with the aim for consistency here, only to note something I've mentioned before about our database schema, mainly that our pluralized column names is actually **against** convention in Postgres, which is singular name for tables and columns. 

> The singular form for table names and also to stick with singular form for column names. The rationale behind this is that each table is considered a collection of entities, where each row represents a single instance of that entity. Therefore, the table name is singular because each record (row) is an instance of that entity. The same logic applies to column names, where each column holds a singular attribute of an entity.
