### ISSUE TITLE
🎯 Add iOS Magic

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#6509]
## Description:

Gets iOS Magic Login Working (across all devices)
This task involves several crucial updates to get the iOS magic login working as options for our mobile PWA

Note: We should discuss the security implications of these changes with the team.

## Acceptance Criteria:

As a user, I should be able to log in using Magic SSO options on mobile and see the app in the logged-in state.
On mobile, I should see the Apple iOS login option on apple browsers + pwa
Engineering Considerations:

## Product Considerations 

There are no product improvements on this ticket noted. Please use https://github.com/hicommonwealth/commonwealth/issues/4633 to log any (small or large) improvements to login flow on mobile should be. There are currently 5 - 7 small items, and several more not written down)

## Later:
 https://github.com/hicommonwealth/commonwealth/issues/5320
 
 ## Additional Context 
Re-ticketed from #4554 (design superseded)

**Comment by zakhap** [comment]
BLOCKED BY #6382.

**Comment by CowMuon** [comment]
> Also, moving the Milestone 

That's fine @zakhap as long as we understand that is scope creep. I'm fine with this, but the idea is that an epic, once delivered, should not have its scope increased, and ofc course that skews burn down metrics.

**Comment by CowMuon** [comment]
@mzparacha Please remove the `blocked` tag if you have everything you need here.

**Comment by CowMuon** [comment]
This should go into v0.9.6
