### ISSUE TITLE
Update Editor Component UI - Toolbar Text Indenting

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6513]
This code is a breakaway from #5949 and covers the portion of the toolbar that includes creating indented text: left align, center align, right align, and justified. 

Clicking the associated buttons should result in the following behavior:

1. The insertion of the relevant HTML to achieve the alignment or justification requested, with the cursor situated between the two HTML tags.

The relevant designs can be found in this [Figma](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&mode=design&t=Ax3UBAXSVyvTmBpL-0)

@jabell88 @zakhap  <-- feel free to add any details you'd like
@jnaviask  @CowMuon <-- tagged for visibility

<sub>[COM-16](https://linear.app/hicommon/issue/COM-16/update-editor-component-ui-toolbar-text-indenting)</sub>

**Comment by jnaviask** [comment]
No longer needed.
