### ISSUE TITLE
Update Editor UI - Footer w/ Expander Handle and Image Upload

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6515]
This code is a breakaway from #5949 and covers the footer portion of the editor.

1. The editor footer should have a handle that expands the height (not the width) of the editor.
2. The footer should contain an image icon that, when clicked, opens a dialog for image upload. 
3. User should be able to upload an image using drag-and-drop.

The relevant designs can be found in this [Figma](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?type=design&mode=design&t=Ax3UBAXSVyvTmBpL-0)

@jabell88 @zakhap  <-- add any details you'd like
@jnaviask @CowMuon  <-- tagged for visibility

**Comment by Miaplacidus** [comment]
Relevant designs [here](https://www.figma.com/file/5iXtMFaRJopRNAe6nDCnP6/Forum-Experience-Improvements?node-id=259%3A5152&mode=dev)

**Comment by Miaplacidus** [comment]
@jessmart1213 @jabell88 @zakhap 
Quick question: should the handle in the footer expand the editor both horizontally and vertically or just in one of those two directions?

Thanks!

**Comment by jabell88** [comment]
@Miaplacidus The handle should just expand vertically, not horizontally. Thanks!
