### ISSUE TITLE
Deprecate Marketing Splash Page for Rebrand Launch (Part 2 of 2)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6535]
## Description

Part 2 of 2. To be merged AFTER the rebrand is successfully launched + #6534's is executed. 

### Part 2: Clearing the Old
- Once we successfully launch the new Marketing Site (common.xyz) and remove the Old Marketing Site from our app domain root (commonwealth.im/), we can remove the old marketing site from the codebase + the feature flag that let us seamlessly flip the switch.

## Project Owner

PM: @zakhap 

## Acceptance Criteria

- We don't need the old marketing page anymore. Raze it 🔥 

## Additional context

This is Technically to Released in Cycle 2, but because it dovetails with #6534, it is in the Cycle 1 Project Board as well.

**Comment by jnaviask** [comment]
Closing for newer ticket: #6890
