### ISSUE TITLE
Kill The Cow

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6536]
## Description

Replace all instance of our existing spinner (Cow) with the new branded one  added to our kit in #6410

## Project Owner

PM: @zakhap 
Design: @jessmart1213 

## Acceptance Criteria

- Use new spinner everywhere the cow is used.

**Comment by rbennettcw** [comment]
Estimating as 1.

If there are no one-off changes required, then it’s just a drop-in replacement with possibly a bit of CSS.
