### ISSUE TITLE
Stake enabled tag for communities on explore page

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6542]
## Description
We want to surface that stake is enabled within communities for users who are exploring new groups on Common. On the explore page a user should be able to filter communities by having stake enabled or not. When this filter is selected ONLY communities with stake enabled are shown. When the filter is not selected, then communities with and wihout stake can be surfaced. 

A user should be able to determine whether a community has stake enabled or not upon glancing at the explore communities page. 

## Project Owner
@HIM92 

Image: <img width="134" alt="Screenshot 2024-02-08 at 11 22 36 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/70a6df29-4b26-4abe-b18b-c10bb2d9aa9c">

Design link: https://www.figma.com/file/omZZrndm6Phbk1rOU4IKhS/Stake-V1-Fast-Follows?type=design&node-id=1-16442&mode=design&t=l4mOmGlvXACem1XT-0

## Acceptance Criteria
This needs to be implemented in a way that we could filter for it in the future. It should not block any other filters from being activated. Please ignore other aspects in the design link such as the level of activity happening on the bonding curve (mild, wild, booming) for now as those are being retooled.

**Comment by dillchen** [comment]
@HIM92 isn't this already covered in #6873? we should close this
