### ISSUE TITLE
Favicon + Logo Updates

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6544]
## Description

Update the Common Favicon + Replace Logo everywhere it exists with new SVG.

## Project Owner

PM: @zakhap 
Design: @jessmart1213 

## Acceptance Criteria

- Favicon Updated
- Logo Updated everywhere

## Additional context

Logo Locations: 
- [ ] Upper Left Corner Home Button
- [ ] Common Community Logo => Rhys to update?
- [ ] ...

**Comment by dillchen** [comment]
Other locations, should ensure that shares to webhooks and other channels are correctly showing
