### ISSUE TITLE
[SPIKE] RTMP Feasibility

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#6550]
Growth has requested adding [RTMP](https://rtmp.veriskope.com/docs/spec/) support on Common in time for the event on 2/14, which will be using [Streamyard](https://streamyard.com/) for video sharing. 

To accept an RTMP feed in Common we’ll need to add a package on the platform side (such as **`node-media-server`**) and a library (such as **`react-player`** ) on the client to handle playback.

## General Configuration 
**Here are the general steps to set it up.** 

### **1. Add RTMP server to our back end via `node-media-server` pkg**

Stub code to Install the **`node-media-server`** package:

```bash
// (obvi) 
npm install --save node-media-server
```

Create file (e.g., **`rtmp-server.js`**) and set up RTMP server:

```tsx
const NodeMediaServer = require('node-media-server');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 60,
    ping_timeout: 30
  },
  http: {
    port: 8000,
    allow_origin: '*'
  }
};

const nms = new NodeMediaServer(config);

nms.run();

console.log('RTMP Server is running on port 1935');
```

### **2. Configure Express.js handle RTMP requests**

Configure Express to handle RTMP:

```tsx
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const { spawn } = require('child_process');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

// ... (Our existing Express.js server setup)

// WebSocket for communication between server and client
io.on('connection', (socket) => {
  console.log('A user connected');
});

// Run RTMP server
const rtmpServerProcess = spawn('node', ['rtmp-server.js']);

rtmpServerProcess.stdout.on('data', (data) => {
  console.log(`RTMP Server: ${data}`);
});

// ... other server routes and middlewarez

server.listen(3001, () => {
  console.log('Server is running on port 3001');
});
```

### **3. Use `react-player` on client**

Install the **`react-player`** package:

```bash

npm install --save react-player
```

Use **`react-player`** in component to play stream:

```tsx
import React from 'react';
import ReactPlayer from 'react-player';

const VideoPlayer = () => {
  const rtmpUrl = 'rtmp://<SERVER_IP>:1935/live/stream-name';

  return (
    <div>
      <ReactPlayer url={rtmpUrl} playing controls />
    </div>
  );
};

export default VideoPlayer;
```

### **4. CORS!**

We are serving our app from the same domain, but Streamyard and other RTMPs will be coming from a different origin, so we should use CORS. I believe we only have this on Chain Events, not the Commonwealth app (?) 

```tsx

const cors = require('cors');

app.use(cors());
```

### **5. The tricky part**

Do we want to support this as a feature for users? (adding embedded video links to any post.) Is this something we want be toggle-able per community? (Product question) 

In any case we need a way to inject the Streamyard url into the player. Even for this one-off I would prefer we didn’t literally hard code this. Rather, we should do it in a way that allows any users with appropriate permissions to add a video url to be embedded and played. 
In fact, that could be a gated feature in communities. (eg. you must have created at least x pieces of content to be able to add video, or have x upvotes, x points, etc.) [PRODUCT QUESTION @zak] 

Ideally, we can add this functionality cleanly for users to be able to include video (gated or no) and put behind a feature flag to be able to offer as a value add [GROWTH QUESTION? @ Mark]

## The Plan
1. Complete feasibility spike (remaining goals) 
2. If Streamyard not feasible, consider Youtube fallback  (apparently they will use both for 2/14)
3. If injection ruled out, Consider options to hard code (to make Growth happy.) Would there be any advantage in pointing to Youtube or Streamyard over the other? 
4. If not feasible, inform Growth so they can be disappointed. 

## Remaining goals for this spike are: 
1. Confirm above installation and point estimate. (2 pts for adding libs] NB suggested packages are recommendations not specification; if there are better libraries we should use those. 
2. Confirm and document url injection implementation 
3. Thoroughly look at edge cases ("compatibility issues on popular browsers and devices")
3. Look into edge case handling and what the sharp edges are. RTMP has a rep for lots of cross-browser compatibility issues, and we don't want to get most of the way on this and have to deal with death of 1000 cuts. 
4. Full estimation of total scope of work for completion 

### Links
- [RTMP Specification](https://rtmp.veriskope.com/docs/spec/)
- [Original Spec](https://rtmp.veriskope.com/pdf/rtmp_specification_1.0.pdf) 
- [Wowza RTMP Explained](https://www.wowza.com/blog/rtmp-streaming-real-time-messaging-protocol) _("RTMP streams run into compatibility issues when it comes to playback on popular browsers and devices.")_
- [React Player](https://github.com/cookpete/react-player?tab=readme-ov-file)
- [copycat.dev tips](https://www.copycat.dev/blog/react-player/) incl. [React Player Props](https://images.surferseo.art/64731390-cc0b-41bb-a26c-9f1c33cd5ecb.png)

**Comment by CowMuon** [comment]
Implementation assuming we get that far will likely be @lzach83. Zach is OOO until Tuesday, so would like @kurtisassad  to do a super quick spike here. In fact Kurtis, if you can find even just 30 minutes (on Fri 2/2) to take a look at this, it would be super helpful (or if you need a bigger time box, that's fine, would just like to see at least some attention here before EOW kudasai)

**Comment by kurtisassad** [comment]
@ForestMars Just from a pure numbers point of view, I don't think it would be wise to host the RTMP stream ourselves. Our infrastructure is not built to handle that much bandwidth. All of our assets are pulled from the CDN which are pulled from our object storage service.

A better alternative would be to use a hosted server like https://www.cloudflare.com/products/cloudflare-stream/. I think it would be far cheaper in terms of both engineering time and cost.

The front end looks good though.

**Comment by kurtisassad** [comment]
As for backend points, I am not 100% sure since I have never done it. But I suspect hooking up streamyard with cloudflare streams would be around 5 points.

**Comment by CowMuon** [comment]
Good call Kurtis, that was a concern of mine as well (whether current dyno could handle load) and would like to avoid running this on a vultr box if pos. However, 5 points is out of our budget for this one off (unless priorities change.) 

I'm going to say this is not going to happen for 2/14. We need to stay on track for Denver, and then after that we should circle back to assess value of adding RTMP, but moreover put the thought into how video embeds are handled as 'blocks.' 🧊

**Comment by CowMuon** [comment]
@lzach83 for visibility (once he's back in office.)

**Comment by CowMuon** [comment]
Memorializing that we have decided not to pursue this story for the 2/14 community call. Let's revisit how RTMP might be added as a `block` to threads (going forward.)

**Comment by dillchen** [comment]
I'd like to try to land this before NFT NYC or Far Con or smth
