### ISSUE TITLE
Minimum Viable Discourse Import Fix

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#6574]
## Description

Currently, Discourse import very likely does not work. We have another ticket for self-serve and refactoring at #6450 but we also want to onboard communities from Discourse this week. So, let's figure out how to get the script working again. Probably just need to clean up the database queries for chain <> community refactor, but may be other small things involved.

**Comment by timolegros** [comment]
For clarity:
@rbennettcw is working on fixing bugs by updating all files to use TS.
In the meantime, I am working on updating the CW side queries (semantics + outdated columns/tables).

Once both of these tasks are finalized we will merge them and update any Discourse side queries that need to be updated (if the Discourse data model has changed).
