### ISSUE TITLE
FE - Vote weight should increase upvote count on UX

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6579]
## Description
When someone owns Stake, and they upvote a post - the upvote count should go up by the vote weight of the user with stake. 

Example: If a post has 3 upvotes, and a user with 3 vote weight from 3 stake upvotes it, then hte post will have 6 upvotes now. This should be viewable at the forum level wihtout needing to click into the upvote drawer. 

There is an exisitng component on the backend for this. 

## Project Owner
@HIM92 

## Engineering Requirements
The upvote count accurately reflects the number of upvotes given to the post as well as the stake based vote weight owned by the users. 

## Acceptance Criteria
The upvote count is reflected on the frontend user expereince.

**Comment by Miaplacidus** [comment]
Per discussion in Slack, the UI will display the number of reactors on upvote buttons if no weighted vote sum exists. In addition, the view upvotes drawer will default to giving reactors a vote weight of 1 if no weight is associated with the reactor.
