### ISSUE TITLE
Membership must count towards vote weight. 

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6583]
## Description
Right now in the community stake flow having 1 stake = 1 vote weight. Joining a community gives you 1 vote as well. This means that your 1 community stake is currently overwriting the 1 vote you get from being in the community. 

If someone has 1 stake and is a member of a community, their vote weight should be 1 (community membership vote) + N stake based vote weight. 

## Project Owner
@HIM92 

## Acceptance Criteria
Vote weight should never be less than 1. Any stake is in addition to the default vote weight of a community member. Owning stake + being a member of a community will never = 1.

**Comment by rbennettcw** [comment]
Confirmed from Harris that "every member should be able to vote / upvote so long as they meet the criteria for being a member of the community. But if they own stake, they get more vote weight" and the calculation should be `1 + (userStakeBalance * communityVoteWeight)` for each vote.

If a user owns `1` stake and the community vote weight is `100`, then the total vote weight is `101`.
