### ISSUE TITLE
Automatically add user to community upon stake acquisition

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6594]
## Description
Goal: If a user mints stake they should be automatically added to the community that they are minting the stake from. This should happen for any user purchasing stake from a community within the UX. 

User story: I am looking at communities with Stake enabled, and I am acquiring a small batch of stake in every community. I dont take the time to join the communities -- i just go in and mint some on Commonwealth.im. Afterwards, I see that the community has shown up on the sidebar of the navigation system. 

## Project Owner
Pm: @HIM92 

## Engineering Requirements
As a consequence of signing a stake minting transaction the user should be autojoined to that community on the common website.

**Comment by jnaviask** [comment]
Blocked by #6594
