### ISSUE TITLE
Replace copy of buy sell with Mint/Burn. 

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6621]
## Description
We are replace Buy and Sell, along with some more of the language, on the Stake experience with "Mint" and "Burn." This needs be done on the side bar, on the banner ad, and within the modal.

## Project Owner
@HIM92 

## Engineering Requirements
Must match desgins: 

## Additional context
Design link -> https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1117%3A201363&mode=design&t=KwVMkr8hnt3GeJ90-1

**Comment by dillchen** [comment]
I am considering nixing this ticket, will discuss with team on Monday reasoning

**Comment by CowMuon** [comment]
Will follow up with @HIM92 and close/update ticket accordingly.

**Comment by HIM92** [comment]
closing this ticket per @dillchen req
