### ISSUE TITLE
Mobile push notifications screen

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6622]
## Description 
Community members and admins should be able to manage their push notifications for mobile from this screen. 

## Feature Specs
- User should be able to turn push notifications on/off from ~~this~~ the push notifs screen 
- When the user turns the push notification on, they should get the system prompt for turning notifications on/off 
- The user will still continue to get in-app notifications if they turn off push notifications 
- Discussion activity: If turned on, users should get notifications for replies to threads that they have posted, replies to comments, and mentions 
- Admin Alerts: The admin alerts option should be shown (only) if the user is an admin of a community. For V1 admins alerts should include: 
   - Update on stakes burned in the community every 8 hours
   - Update on stakes minted in admins community every 8 hours

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/f155ad6b-3c44-4bb3-bce3-693ea0c81b8d)

## Designs
[Figma](https://www.figma.com/file/WdlVQRpQKg4GMgCOzbQt34/Notifications?node-id=261%3A2078&mode=dev)

**Comment by burtonator** [comment]
For the following issues @timolegros says we need to fix:


> Discussion activity: If turned on, users should get notifications for replies to threads that they have posted, replies to comments, and mentions
> Admin Alerts: The admin alerts option should be shown (only) if the user is an admin of a community. For V1 admins alerts should include:
> Update on stakes burned in the community every 8 hours
> Update on stakes minted in admins community every 8 hours

Tims says we're not yet ready because we have to fix:

> Subscriptions related things -> syncing our model with Knock

**Comment by timolegros** [comment]
> For the following issues @timolegros says we need to fix:
> 
> > Discussion activity: If turned on, users should get notifications for replies to threads that they have posted, replies to comments, and mentions
> > Admin Alerts: The admin alerts option should be shown (only) if the user is an admin of a community. For V1 admins alerts should include:
> > Update on stakes burned in the community every 8 hours
> > Update on stakes minted in admins community every 8 hours
> 
> Tims says we're not yet ready because we have to fix:
> 
> > Subscriptions related things -> syncing our model with Knock

To be clear, there is no "bug" to fix. Push notifications are not supported on the backend yet and no tickets have been created for its support on the backend since we have not shipped in-app notifications. There are several in-app follow-ups to complete before  ticketing up the push notifications subscription backend changes.
