### ISSUE TITLE
Working email notifications

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6625]
## Description
Currently, we have three types of email notifications, which are not working or need updates:
    - Legacy digest emails: These are a weekly digest of emails that includes all the in-app notifications that the user has got in the last week
    - Legacy immediate emails: These are individual emails sent for every notification that the user is subscribed to
    - New weekly digest emails is sent using a script:
           - The script iterates through CW communities, querying them for top threads, activity counts, and "Community Activity Score" (a sort of aggregate of engagement metrics). This data is then used to seed a Sendgrid template. Described in https://github.com/hicommonwealth/commonwealth/pull/6564
- We are re-doing our notifications management system as part of Push Notifications V1. As part of this project, we want to ensure working email notifications that the user can read and manage. 

## Feature Specs
- Deprecate immediate emails
- Get legacy digest and new weekly digest emails working 
- Implement new email templates for legacy digest and new weekly digest emails (TBD) 
- User should be able to turn email notifications on or off on the email notifications management screen 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/2bd070a9-1e31-4416-9358-35d70158b060)

- Turning email notifications on will subscribe the user to Weekly Digest (the new weekly digest email) and Community updates (legacy digest) 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/790b55ea-0c30-47e1-a230-d986d0d525ad)

- User should be able to toggle on and off Weekly Digest and Community updates individually
- If email notifications are turned off, the user will not be able to see the options to turn on weekly digests or community updates 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/e870e056-cfdd-41b6-bbf0-fd846c676786)

**Comment by CowMuon** [comment]
(Platform WIP is soft blocker here, as is other work scope (Stake, Contests)

**Comment by dillchen** [comment]
superseding tickets
