### ISSUE TITLE
Community Forum RSS Feed 

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6633]
## Description

A user familiar with Discourse finds RSS feeds to forums very useful (See attached screenshot under _Additional Context_).

We should add community specific RSS feeds that mirror our Filter options for the Forum: 
- In the proposed standard format: /sort/timespan.rss
  - Sorts: `latest-activity`, `newest`, `oldest`, `upvotes`, `comments`
  - timespans: `all`, `month`, `week`. we don't currently have a `day` option in our ui at this time, but for Discourse feature parity, would be useful.

## Project Owner

PM: @zakhap 

## Acceptance Criteria

- Community-specific forum activity rss feed with different sorts+filters that reflect our forum experience

## Additional context

<img width="627" alt="Screen Shot 2024-02-07 at 7 12 16 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/5e6c0269-293f-4e51-b0d0-fd770900f9b2">

**Comment by CowMuon** [comment]
As mentioned on standup 03/04, @burtonator  ;-)

**Comment by burtonator** [comment]
Do we want to handle authenticated RSS and running it in the context of the user? In that regard it would be closer to a REST API.

**Comment by CowMuon** [comment]
Initial ask is just for community level feeds, and you're right, if we include the user context, that's basically the API + user auth. Long term we should ensure our model supports private communities, but for this scope, it's just adding RSS with basic sort filters and time window. 

If we need to do a Spike before implementing, that's fine.

**Comment by burtonator** [comment]
@CowMuon I'm looking into the backend of this now and investigating the server components.

**Comment by burtonator** [comment]
I assume it would be URLs like:

http://localhost:8080/terra-luna-classic-lunc/discussions

should probably support the same URL parameters.

**Comment by burtonator** [comment]
... and we'll need HTTP caching for these.

**Comment by burtonator** [comment]
I think it should probably be:

/<community-id>/discussions/feed

... and accept the same URL parameters as /discussions

**Comment by zakhap** [comment]
> I think it should probably be:
> 
> /{community-id}/discussions/feed
> 
> ... and accept the same URL parameters as /discussions

I think this is a great suggestion for the canonical feed

**Comment by burtonator** [comment]
OK. I have the RSS feed being generated now but I need to clean up a few things.  Here's a sneak preview:

<img width="1359" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/45447/312442e1-53e3-4750-ae0f-646b4d925c15">

**Comment by burtonator** [comment]
Here's one blocker.

I'm not being returned a URL from the backend in the 'thread'

![CleanShot 2024-03-06 at 13 33 15@2x](https://github.com/hicommonwealth/commonwealth/assets/45447/2caa887a-c54f-4557-b77d-16cd4f8dbcb7)

I suspect the frontend is computing the URL manually.  

I'll need a way to handle this.

**Comment by burtonator** [comment]
This is what the URL looks like:

http://localhost:8080/api/feed?bulk=true&page=1&limit=20&community_id=terra-luna-classic-lunc&includePinnedThreads=true&orderBy=createdAt:desc

Do we care that what the URL is ?  It's not really visible by the user.

I'll add a <link> in the HTML for auto-discovery so the browser can find it and feed readers can find it too.

**Comment by jnaviask** [comment]
@burtonator i thought we landed on a very different, simpler URL for RSS feeds? `/{community-id}/discussions/feed` -- what was the reason we didn't end up with this URL?

**Comment by burtonator** [comment]
@jnaviask The URL is only "visible" when you subscribe to the feed. It's not really in the URL bar. It looks like all the routes prefix with /api so I just kept the existing pattern.

Do you think it's worth implementing this URL? I agree it would be nicer but it also looks like it would be a one-off.

**Comment by zakhap** [comment]
What are the typical paths for RSS feeds? 

I think it is incredibly important that discoverability isn't dimished, which I fear behind an /api, it might be.
