### ISSUE TITLE
Gating Requirement Type: CW20

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6634]
## Description

Add CW20 token threshold requirement to Gating for Cosmos Chains that support CosmWasm. 

## Project Owner

PM: @zakhap 

## Acceptance Criteria

- A new threshold requirement type for CW20 tokens on CosmWasm-enabled Cosmos Chains.
- It should follow the pattern of all our existing Threshold requirements.

## Additional context

This was a specific as from Oraichain who wants to use their staked native token for gating which happens to be a CW20.

**Comment by mhagel** [comment]
> This was a specific as from Oraichain who wants to use their staked native token for gating which happens to be a CW20.

Which token is this specifically? @zakhap

**Comment by mhagel** [comment]
>This was a specific as from Oraichain who wants to use their staked native token for gating which happens to be a CW20.

Staked native tokens are different from CW20. They are queried differently, and should be a separate ticket from this one. 
@zakhap

**Comment by mhagel** [comment]
Ticket for Staked tokens: https://github.com/hicommonwealth/commonwealth/issues/6993

**Comment by zakhap** [comment]
That makes sense to me. Happy to refer to them as separate tickets + they're definitely both useful!

**Comment by mhagel** [comment]
Current PR #6975 covers happiest path: Standard CW20 contract on it's native chain.

In the interchain, there are some other implementations that would have to be queried differently. So some possible follow-ups might be:
- Factory tokens
- IBC-CW20

Note: Leap recently implemented factory token querying, so might be able to learn from that.

**Comment by mhagel** [comment]
>possible follow-ups

Follow-up ticket, to be prioritized: https://github.com/hicommonwealth/commonwealth/issues/7026
