### ISSUE TITLE
Growl for Valentine's Community Call 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#6636]
## Description
We have a fun request from Growth to add a Growl to the site for next Wednesday's Community Call on 2/14. (Valentine's Day) The really fun part is the ask is to remove the growl the following week, after the call has been held. 

## Engineering Requirements
- Title: Join the community call
- Subtitle: and receive a POAP
- Body: Get ready for an exclusive announcement from Common! Join us on February 14th at 11am EST for something special just for you!
- Button Copy: Add to calendar
- CTA Payload:  [common_community_call.ics](https://drive.google.com/file/d/1dQgcMwBcD7T9FneGcgD9sCwk8kcri4np/view?usp=drive_link)

## Acceptance Criteria
Growl appears as specified. 

## Additional context
- [Figma](https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro3nySutAgQPt34lNFAjvKx0OujY-2FQ2S2MoLblNLk0g4tRqw4BzdLCthd6W4ubXLbsdXOGaNf3cv5fQw7dsOy-2F4YEwopzHpxdxjwFlVPVjlhUX8qRAm1H-2BGlfeiMyJXeoDdM2kNF8CYUyUyKesZL2t8Y-3DxJ2B_IERtsL8IaKW4VcVEme7RTdlsSZfAJhcCSeag674VcicCdJOYpRi-2BpkRu5czYtz4W-2BHUxSLxzSunEBdNoLvYM0-2Fh-2F-2FOUYy3SO7DfI5X6bk8FBjN8FBbsjEFPv2USn9cbYs1thNi4l9GbnOPAiAOVq3QJTaxXTGNlnQQgpk5P7U6J070DuiwEDdQ6od0RBvwadSZmtmM8e290XVFg4rHtnvOkNx8-2B-2F923-2BLipKKnrbTfBdQ2gyUu5SxNdY2xQup0JM)
- Growth requested this for 0.9.5 release going out Monday 2/12. **HOWEVER** we really need this to go out as a patch to 0.9.3, as the community call is only 1 week away. 
- [ ] **We need to confirm we can do that (ship as patch 0.9.4-4)** 

_Going forward we do not intend to add temporary growls to the codebase only to be removed. This is a one off for the Valentine's Day community call_ 💘

**Comment by CowMuon** [comment]
Seems like @lzach83 would be the _fastest_ at knocking this out, given recent Growl work. What say you @Israellund & @mzparacha ?  Who can knock this out faster so we can get it live on the site for growth?

**Comment by mzparacha** [comment]
I am happy if @lzach83 wants to do it. I can also do it if you want.

**Comment by CowMuon** [comment]
Honestly, which of you can bang it out faster? 🤘🎸🙄

**Comment by lzach83** [comment]
It'll be a 2 for me

**Comment by mzparacha** [comment]
Removing `3` since we decided to not add individual calender invite options in favor of default OS calender.
