### ISSUE TITLE
🐞 Editor sometimes loses focus even when 'Yes' selected on Rich Text to Markdown confirmation

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6637]
@lzach83 
Would you mind adding details here?

**Comment by CowMuon** [comment]
"sometimes"?

**Comment by lzach83** [comment]
Loom: https://www.loom.com/share/49633437036a4dbc9b4677753c605544?sid=41af717f-1b8a-47a0-92fb-fb28b23fa70a

It seems there's a focus issue behind the prompt. I'm unsure it's "sometimes" since I couldn't get it to _not_ perform this way.

**Comment by lzach83** [comment]
This is closed as it's fixed in #6605
