### ISSUE TITLE
OG Social Share Meta Updates: Thread Page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6638]
## Description

Our current OG Social Share card is underwhelming.  A protocol on our platform messaged the growth team:
> "Here's one thought-- splashier twitter cards." 

While product+design stage out what each of our different meta links should contain, let's start with our most-frequented page: the thread page.

When Sharing a link to a specific Thread: 
- Image: The Community's Icon, fallback is Common Logo
- Title: Thread Title (60 character truncation)
- Description: First 155 characters of thread body (OG recommended limit)

Be sure to include all standard meta tags for Facebook + Twitter:
- Twitter: `twitter:`-prefixed tags
- Facebook: `og:`-prefixed tags

For Twitter's card type, we should use `summary_large_image`:
  `<meta name="twitter:card" content="summary_large_image">`

## Acceptance Criteria

- Update Meta for Thread Pages to be more contentful: 
  - Image is Community-specific
  - Title is Thread-specific
  - Description is Thread-specific

OG tags should work for

- [x] Twitter
- [x] Facebook
- [x] Slack
- [x] Discord

## Additional context

**What Common Links Currently Look Like:** 
<img width="324" alt="Screen Shot 2024-02-07 at 7 38 30 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/7b58ac3c-8f35-4c0e-91a6-e4e1f25a6e9d">

**What Discourse Preview Links look like:** 
Twitter: 
<img width="548" alt="Screen Shot 2024-02-07 at 7 45 21 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/077ac490-f634-4c58-b1d1-419802aa2cd4">

Slack:
<img width="403" alt="Screen Shot 2024-02-07 at 7 38 35 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/f0987597-834e-48b9-98c4-a2e7f95c4c24">

**Comment by jnaviask** [comment]
To follow #4239

**Comment by CowMuon** [comment]
Pretty cool that a protocol messaged the Growth team @zakhap

**Comment by CowMuon** [comment]
@zakhap I notice the other 2 examples are in in dark mode, but Common is not. Maybe include Common dark mode for better comparison? @zakhap

**Comment by lzach83** [comment]
Met with @timolegros on this, he pointed me towards our usage of Prerender and how i can use open graph to generate these. 

There is still a little bit of discovery to be done on my end of how to make these shared links / urls more dynamic to the specs above but a quick google search rendered a few packages i'll take a look at tomorrow AM. 

resources: [Prerender open-graph](https://prerender.io/blog/benefits-of-using-open-graph/)
[Social Media Sharing](https://prerender.io/benefits/social-media-sharing/)

**Comment by ForestMars** [comment]
Malik, are you able to walk this over the finish line, or are you too deep in user onboarding flow? Would like this to go into v1.3.3  (was supposed to be Allow Lists release, but that may slip.)

**Comment by mzparacha** [comment]
Sure @ForestMars, i can try after https://github.com/hicommonwealth/commonwealth/issues/6643
