### ISSUE TITLE
Track all users that have voted on a proposal for specific communities

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#6639]
## Description
Placeholder ticket for adding functionality totrack all users that have voted on a proposal for specific cowmoonities. 

## Engineering Requirements
Open question of whether to do this as a one-off database query, or add functionality to the code base so as to remove Growth team dependency on ENG for bespoke db queries. 

## Additional context
Intended use is to reward users who have voted on proposals for specific communities (eg. Stargaze)

**Comment by jnaviask** [comment]
Closed by #5490
