### ISSUE TITLE
Improve Authentication Flow to Prevent Duplicate Accounts

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6642]
## Description

Goal: Prevent accidental creation of multiple accounts by directing users to either sign in with a previously used wallet address on Commonwealth or start the new user onboarding flow. (This experience is conditional for users signing in with an unrecognized wallet address.)

- User story: As a user on Common, when I attempt to sign in using a wallet address that I haven't used before on the platform, it becomes unclear whether I intend to sign into an existing account or create a new one. I expect to be guided either to create a new account or to correct my input and sign in with the appropriate wallet address.
  - If I choose "sign in a different way," I should be redirected to an alternative sign-in method for Common.
  - If I choose "create an account," I should seamlessly transition into the user sign-up flow.
    - Upon selecting "create account," I should be directed to the account creation process, starting with the modal detailed in ticket #6641.

<img width="403" alt="Screenshot 2024-02-08 at 11 05 23 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/73ac838e-20b9-4b75-a1bd-841ba68ff21e">

## Project Owner
@HIM92 

## Additional context
Designs: https://www.figma.com/file/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?type=design&mode=design&t=VkGa4g61pMJjke6k-0

**Comment by ForestMars** [comment]
In scope for Cycle 4 Sprint 1
