### ISSUE TITLE
Join Communities Prompt

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6648]
## Description
Goal: Prompt users to join an additional community on the final modal. 

- User Story: In the final step labeled "Join A Community," users are presented with four of our top communities tailored to their previously indicated interests. If no interests were selected, communities are ranked based on user count and activity.
  - Upon selection of a community, the corresponding box turns blue. 
  - Users have the option to skip this step by clicking the "x" button. 
  - If users choose none of the communities, they can still click “Let’s Go,” completing the user onboarding modal flow.
  - if a user is signing up with a wallet on the EVM chain, they should only be given suggested communities that work with that wallet. 
      - this is also true if a user signs up with a cosmos wallet or any additional blockchain wallet. 
      - Suggestions should be exclusive to communities that the user can actually join

<img width="247" alt="Screenshot 2024-02-08 at 11 10 37 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/7b562edf-8fda-4232-bc8e-64affc2b5ae6">

## Project Owner
@HIM92 

## Additional context
Design link: https://www.figma.com/file/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?type=design&mode=design&t=VkGa4g61pMJjke6k-0

**Comment by HIM92** [comment]
Yes, that is correct. Will add to the ticket. If a user does not have a cosmos wallet, they should not be shown cosmos based communities.

**Comment by mzparacha** [comment]
gotcha, Thanks
