### ISSUE TITLE
Community Tags for User Interest Preferences - admin management

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6653]
## Description

Goal: Community admins are able to describe their communities with tag buttons, and these are surfaced to users who are interested in those subject tags. 

User story: I am an admin of a community on Common. Within the admin page, I can choose what to tag my community with. When I have tagged these they are shown to users who have stated that they are interested in these subjects. 

These options are: NFTs, Gaming, Social, Memes, AI, Defi, ReFi, Lending/Borrowing, Staking, Swaps, dApp, Technology, Security, Governance, Marketplace. 

<img width="294" alt="Screenshot 2024-02-22 at 11 12 14 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/ecfd40ae-9ae1-4d79-9ee3-74494865e7f3">

## Project Owner
@HIM92 

## Additional context
Figma link: https://www.figma.com/file/ibuywR0bBcy3ZZhPXbjEJw/Community-Admin?type=design&node-id=1094-11858&mode=design&t=v2IaX8uvOYhiDj2I-0

**Comment by mzparacha** [comment]
We will need to do some API changes to accommodate new tags, not leaving estimation for that.
