### ISSUE TITLE
Enable push notifications prompt

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6655]
## Description
When enabling push notifications for the first time, users should do so from mobile-only. Once the user has enabled push notifications, they can modify their preferences on mobile and desktop. 

Since its not possible for us to detect if the user has downloaded the pwa, we will prompt the user to download the pwa with a link on the push notification screen. 

## Feature specs
- When the user visits the notifications settings page -> mobile, they will be prompted to download the pwa to enable notifications 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/220fef2d-bb78-494f-b918-83f62cc16332)
- Once notifications are enabled from mobile, they will able to manage notifications from either desktop or mobile 
- **Mobile**: Since we cannot detect whether a user has downloaded the pwa, we will show the prompt for the user to download the pwa on mobile 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/6fc56ec7-b24d-4f11-83fc-43928c1a0d57)
- Clicking on download would show the pwa prompt for ios or Android that is described in the[ PWA enablement ticket ](https://github.com/hicommonwealth/commonwealth/issues/6407)
- Related ticket - [mobile push notifications screen ](https://github.com/hicommonwealth/commonwealth/issues/6622)

## Designs 
[Figma ](https://www.figma.com/file/WdlVQRpQKg4GMgCOzbQt34/Notifications?node-id=261%3A2484&mode=dev)

**Comment by burtonator** [comment]
Just FYI I don't know if we can implement this 'switch toggle' UI. The way notifications work is that we get a callback saying that we CAN enable notifications and then it has to be done via a button.  I will investigate though and verify. We're limited what we can due to the security model done with PWAs for notifications.

**Comment by burtonator** [comment]
Also, I don't think we need this until we implement PWA notifications.  This doesn't apply to in-app notifications I think.

**Comment by sachben91** [comment]
Yes, these are for PWA notifications and it will be used by the user once they have enabled the notifications. They will use these toggles to manage their notification settings.

**Comment by ForestMars** [comment]
This issue needs an associated development branch / PR, kudasai
