### ISSUE TITLE
🪣  FF1

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6661]
## Description
The scope of FF1 is to complete known required functionality for community stake v1, as well as fix any issues spotted in the user experience while in QA. 

There are a few different types of ticket here in this bucket and FF tranche, known features that were cut from scope of v1 release but are necessary for public launch, grammar issues in the frontend we should fix, functionality issues, and feedback from beta partners.  I will break them down accordingly

Known features to add, ranked in terms of priority:

Stake discoverability - already split out

- [x] https://github.com/hicommonwealth/commonwealth/issues/6873
- [x] https://github.com/hicommonwealth/commonwealth/issues/6692
- [x] https://github.com/hicommonwealth/commonwealth/issues/6870
- [x] https://github.com/hicommonwealth/commonwealth/issues/6869
- [ ] ~~https://github.com/hicommonwealth/commonwealth/issues/6872~~

My Community Stake Page
- [ ] https://github.com/hicommonwealth/commonwealth/issues/6679
        My Stake Tab
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6668
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6669
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6670
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6671
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6672
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6673
       Transaction History Tab
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6674
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6675
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6676
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6677
   - [x] https://github.com/hicommonwealth/commonwealth/issues/6678

Other functionality

- [ ] https://github.com/hicommonwealth/commonwealth/issues/6843 -- high pri, assigned to Ryan

Add Community Stake to existing communities -> Blocked 

- [ ] https://github.com/hicommonwealth/commonwealth/issues/6877
- [ ] https://github.com/hicommonwealth/commonwealth/issues/6680
- [ ] https://github.com/hicommonwealth/commonwealth/issues/6684
- [ ] https://github.com/hicommonwealth/commonwealth/issues/6688
- [ ] https://github.com/hicommonwealth/commonwealth/issues/6689
- [x] https://github.com/hicommonwealth/commonwealth/issues/6690

Grammar (Copy) issues: 
- [x] https://github.com/hicommonwealth/commonwealth/issues/6621
- [x] https://github.com/hicommonwealth/commonwealth/issues/6662

Feedback: 
- [x] https://github.com/hicommonwealth/commonwealth/issues/6581
- [x] https://github.com/hicommonwealth/commonwealth/issues/6580
- [ ] https://github.com/hicommonwealth/commonwealth/issues/6587
- [ ] https://github.com/hicommonwealth/commonwealth/issues/6594

## Project Owner
Pm @HIM92

**Comment by CowMuon** [comment]
Closed in S1 but merged in C2 o_O
