### ISSUE TITLE
Welcome to Common Modal!: Notification and Product update checkboxes

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6667]
## Description

Goal: Users need to check whether they want 1) email notifications turned on for their account and 2) product update notifications on the Welcome to Common! modal. 

User Story: As a user on the Welcome to Common! modal, I can consent to receiving notifications about my account - this will activate email notifications for my account. Secondly, I can consent to receiving product updates and news. Neither of these options are mandatory to continue.

If I do not check these boxes off then the notifications are turned off by default. 

## Acceptance Criteria

- [x] 1- User should be able to enable all in-app notifications via -> `Send me notifications about my account`
- [x] 2- User should be able to enable marketing notification via -> `Send me product updates and news`

**Comment by mzparacha** [comment]
Update: Item 1 from the OP checklist is already done in #7629.

**Comment by mzparacha** [comment]
Per further discussion with @HIM92, we will be updating the API to support 

> User should be able to enable marketing notification via -> Send me product updates and news
