### ISSUE TITLE
Implement "My Stakes" Page with Detailed Stake Holdings View

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6669]
## Description
Goal: Users can review their stake holdings

- I am a user on Common, and I have clicked My Community Stake on the profile dropdown. I am taken to the My Community Stake page. 
- The page has two tabs: 
   - Tab 1, My Stakes
    - The following are viewable on My Stakes:
    - Community - this is the symbol of the community stake, and the community name 
    - Address - Smart Contract address my Community Stake originated from.  
    - Stake - this is the amount of the stake that the user owns, per stake symbol.  should only ever be whole numbers. 
    - Vote Weight - this is the collective vote weight of the stake that the user owners. This should only ever be whole numbers
    - Average purchase price - the average cost of the stake that the user has acquired. Number of stake minted  / total cost of stake minted - (number of stake burned / total value generated from burning stake) 
    - Average purchase price is displayed in ETH

- Tab 2: Transaction History

Subtickets:
- [ ] #6673 
- [ ] #6670 
- [ ] #6671

## Additional context
Figma - https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1812-63466&mode=design&t=RicvrnYRgLN1pkFi-0

**Comment by mzparacha** [comment]
reassigning `1` as most of the ground work was already merged in another PR

**Comment by mzparacha** [comment]
API to be integrated in https://github.com/hicommonwealth/commonwealth/issues/7201
