### ISSUE TITLE
Implement Column Sorting Feature in "My Stakes" tab

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6670]
## Description
Goal: Users can reorder their My Stakes table by clicking any of column titles. 

- I am a user on Common and I am reviewing all of the Stake that I have acquired. I want to reorder it by clicking the column title. 
  - By default, the My Stake page is ordered by the Community Stake the user has the most of from highest to lowest amount. 
  - When any of the 5 column titles are clicked, they are reordered by value (higher to lower) or alphabetical order
       - Community is ordered alphabetically by Stake symbol, By default it is A-Z, on click it is Z-A
       - Address is ordered Alpha-numerically
       - Stake is ordered from highest to lowest, on click it becomes lowest to highest
       - Vote Weight is ordered from highest to lowest, on click it becomes lowest to highest
       - Average Purchase Price is ordered from highest to lowest, on click it becomes lowest to highest

       
<img width="789" alt="Screenshot 2024-02-01 at 4 02 42 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/d4e24574-4119-4437-95d7-3103bcdfd963">

## Additional context
Figma: https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1812-63466&mode=design&t=RicvrnYRgLN1pkFi-0

**Comment by jnaviask** [comment]
Blocked by #6669
