### ISSUE TITLE
Enable Community Name Search Functionality in "My Stakes" Page search bar

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6671]
## Description
Goal: Users can search for specific stake holdings by searching for the community name or community stake symbol.

- User Story:“As a user I am able to search for specific stake holdings by community name, or symbol.”

## Additional context
Figma: https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1812-63466&mode=design&t=RicvrnYRgLN1pkFi-0

**Comment by jnaviask** [comment]
Blocked by #6669
