### ISSUE TITLE
Implement Community Name Search Functionality in Transaction History

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6675]
## Description
Goal: Users can search for specific stake transactions by searching for the community name or stake symbol. 

- User Story: “As a user I can search for specific Stake transaction by community name. or stake symbol”

**Comment by mzparacha** [comment]
Blocked by https://github.com/hicommonwealth/commonwealth/issues/6674

**Comment by mzparacha** [comment]
Removing blocked label as https://github.com/hicommonwealth/commonwealth/issues/6674 has a pr ready, will built on top of that
