### ISSUE TITLE
Enable Column Sorting in Stake Historical Transactions Menu

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6676]
## Description
Goal: users can reorder their stake historical transactions menu by clicking the header of any of the column headers

“As a user I can reorder my stake historical transactions menu by clicking the header of any of the column headers to sort up or down.” 
- Community is ordered alphabetically by Stake symbol, By default it is A-Z, on click it is Z-A
- Address is ordered Alpha-numerically
- Stake is ordered from highest to lowest, on click it becomes lowest to highest
- Vote Weight is ordered from highest to lowest, on click it becomes lowest to highest
- Average Purchase Price is ordered from highest to lowest, on click it becomes lowest to highest
- Total price is sorted from highest to lowest
- Timestamp is ordered historically with the most recent at the top by default.

<img width="777" alt="Screenshot 2024-02-01 at 4 02 22 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/a8f47f52-ca6b-4d06-8d87-9c0b5ca96de2">

## Additional context
Figma: https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1812-63466&mode=design&t=RicvrnYRgLN1pkFi-0

**Comment by mzparacha** [comment]
Blocked by https://github.com/hicommonwealth/commonwealth/issues/6674

**Comment by mzparacha** [comment]
Removing blocked label as https://github.com/hicommonwealth/commonwealth/issues/6674 has a pr ready, will built on top of that.

**Comment by mzparacha** [comment]
Done in https://github.com/hicommonwealth/commonwealth/pull/7087
