### ISSUE TITLE
Enable Community Stake Integration for Existing Communities

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6680]
## Description
Goal: Admins for existing communities are able to enable Community Stake on their community.

User story: As an admin of a Community that either didn't activate Community Stake during creation or was established before its introduction, I need to enable Community Stake now. To do so, I navigate to the integrations "page" [screen?] and find the Community Stake integration as the first option. 
- My community MUST be on a stake enabled network otherwise it is grayed out with a hover over tooltip that says Stake is not supported on your network [until Chains-B-Gone goes in.]

<img width="409" alt="Screenshot 2024-02-08 at 9 24 42 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/94ee7300-e0b8-4bd8-bb11-6766414d860b">

**Comment by jnaviask** [comment]
Blocked on "Community Chains B'Gone" project.
