### ISSUE TITLE
Metadata creation and endpoint for CS tokens

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#6681]
## Description

In order for ERC1155s and other NFTs to display information in metamask, opensea and other explorers they store a uri that points to an endpoint that exposes a json file containing the meta data the format for 1155 is as follows 
```
{
	"name": "Asset Name",
	"description": "Lorem ipsum...",
	"image": "https:\/\/s3.amazonaws.com\/your-bucket\/images\/{id}.png",
}
```
and the endpoint must follow the pattern of `https://token-cdn-domain/{id}.json` where `id` is a 32 byte hex value

In our case we'll likely craft endpoints as such: `https://commonwealth.im/api/{namepace}/{id}.json` that return a simple json file/

## Engineering Requirements

- ~~creation of json schema when community stake is configured~~ On second thought we dont need a pre-built JSON when all the data is in the model already and construction can be cached 
- performant endpoint serving format of json above
    - maybe use caching but this could happen as a FF 

## Acceptance Criteria

- metadata shows up on wallets, etc 

## Additional context

- The communityStake model appears to be the best place for this atm, we can make it expandable there (JSONB array) assuming metadata is used for community stake

**Comment by CowMuon** [comment]
(Moved to Teed-up since the PR is still in Draft.)
