### ISSUE TITLE
Continue lists when pressing enter

### ISSUE THREAD

**Issue by lzach83** [hicommonwealth/commonwealth#6683]
## Description

Currently, pressing enter in lists causes the editor to break out of the list entirely. We want to modify this behavior so that pressing enter within a list will continue the list, with specific functionalities for ordered and unordered lists. Additionally, we want to implement a feature where rapid consecutive presses of enter will break out of the list, allowing users to resume typing freely. 

## Engineering Requirements
Modify the list button functionality to toggle and maintain the list structure.
Create an event listener for the 'Enter' key that will handle list continuation for both ordered and unordered lists.
Implement logic to detect rapid consecutive presses of enter and break out of the list accordingly.

## Acceptance Criteria
In ordered lists, pressing 'Enter' continues incrementing the list numbering.
In unordered lists, pressing 'Enter' continues the current list item.
Rapid consecutive presses of enter should break out of the list, allowing free typing.

If we hit enter in rapid succession it should:
In all lists, break out of the list and you should be able to continue typing freely

## Additional context

Marcin's comment: https://github.com/hicommonwealth/commonwealth/pull/6605#pullrequestreview-1867633095

**Comment by ForestMars** [comment]
Not sure how this one got missed for so long, but  just closed that PR which was really stale. What's the path forward here? @Israellund @burtonator

**Comment by Israellund** [comment]
@ForestMars I think the PR you just closed should have solved for this. But @burtonator what are your thoughts?

**Comment by ForestMars** [comment]
@Israellund @burtonator Happy to re-open and merge that PR if it does the thing. My reticence was mainly how stale it seemed, and also at that time I don't think editor work was as scoped as it is now (additional editor stories coming in tomorrow's refinement.) 

I will defer to @burtonator on this: is the [extant PR](https://github.com/hicommonwealth/commonwealth/pull/6711) how we wish to solve this?

**Comment by ForestMars** [comment]
Assigned Burtonator to assess whether PR is drifted or that we should pull it in.

**Comment by ForestMars** [comment]
@jnaviask @Israellund @burtonator - For Cycle 4 Sprint 2, to either complete or kill.

**Comment by jnaviask** [comment]
Wont fix pending editor revamp.
