### ISSUE TITLE
Initiate Stake Enablement Flow 

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6684]
## Description
Goal: An admin who enables Community Stake on the integrations page must be put into the stake enablement flow. 

- User story: As an admin, once I click "Enable Stake" I am taken to the page where I can name my Community Stake Symbol, and namespace. When I click yes, I am taken to the transaction signing flow from Create Community where I sign to obtain my namespace adn launch community stake.
 - Namespace and Symbol must be unique on Common
 - If I click “No” then I am taken back to the integrations page. 

## Additional context
<img width="689" alt="Screenshot 2024-02-08 at 9 29 51 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/ee83cea5-cf2a-4dba-a219-27f39e0dcb16">

figma: https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1738-83886&mode=design&t=gp5GgOXFOqjBx3p8-0

**Comment by ForestMars** [comment]
Per my comment on breadcrumbs cleanup, would like to leave that for Fixit Friday and get this last stake story into this week's release (v.1.3.1 stake FFs) cc. @ilijabojanovic

**Comment by lzach83** [comment]
Waiting to get access to figma before i can start this...

**Comment by dillchen** [comment]
Getting this and then getting in User Onboarding would be great yea
