### ISSUE TITLE
Confirmation Screen for Launched Community Stake

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6689]
## Description
Goal: After enabling stake on my community, I see this screen that confirms Community Stake has been launched, gives me information on the namespace, bonding curve, and vote weight of the Community Stake. 

- User story: As an admin who has just enabled Community Stake, I get a confirmation screen once I have launched my namespace and successfully enabled community stake. This page confirms that I have launched Community Stake, and gives me the following:
  - Smart contract address for the namespace onchain
  - Bonding curve smart contract address
  - Vote weight of the community stake contract I have just launched
     - At launch this will be 1 - 1 community stake = 1 vote weight. 

Goal 2: On the integrations page, Community Stake is confirmed as enabled with a green checkmark on the integration card once I have launched my community stake.

Goal 3: The admin can revisit the Community Stake information page shown in ticket 12 by clicking “View Stake Information” on the Integrations page.

- User Story: As an admin who has previously enabled stake, I want to check the information on My Community’s Community Stake. I navigate to the Integrations page, and under Community Stake there is a “View Stake Information” button. When I click on this button it takes me to the Stake confirmation page, where I can confirm Community Stake is enabled, and review:
 - Smart contract address for the namespace onchain
 - Bonding curve smart contract address
 - Vote weight of the community stake contract I have just launched
 - At launch this will be 1 - 1 community stake = 1 vote weight.

<img width="559" alt="Screenshot 2024-02-08 at 9 37 45 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/23d50857-96d3-452b-9e64-5ee49d538e13">

## Additional context
Figma: https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1738-83886&mode=design&t=gp5GgOXFOqjBx3p8-0

**Comment by mzparacha** [comment]
Where should the "Learn more about community stake" button redirect?

cc: @HIM92

**Comment by HIM92** [comment]
For 1,  users should be redirected to here
https://docs.common.xyz/commonwealth/community-overview/community-stake

**Comment by HIM92** [comment]
For 2, the bonding curve address is the smart contract address of the community stake contract that was launched. For clarity's sake with the user, I feel like we should change "Bonding curve" to "Smart contract address"

**Comment by ForestMars** [comment]
Hmm, this issue didn't close when the PR was merged. 

Merge Queues are not enabled for this branch or even the repo. 

Not sure what caused that hiccup @burtonator @jnaviask
