### ISSUE TITLE
Incorrect number of runners-up

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#670]
The council page for Edgeware shows 8/7 runners-up which seems incorrect. Need to investigate why this happens, and propose a fix.

**Comment by raykyri** [comment]
actually not sure about this...

**Comment by gdjohnson** [comment]
It's calculated by subtracting councillors.length from candidates.length.

Candidates comes from `app.chain.phragmenElections.activeElection.candidates`; councillors comes from `app.chain.phragmenElections.members`

**Comment by gdjohnson** [comment]
From the polkadot wiki:
> The election also chooses a set number of runners up (currently seven on Kusama and fifteen on Polkadot) that will remain in the queue with their votes intact.

Ostensibly the "7" here is the number of runners-up who remain in the queue. If this is just a UI display count, then maybe we should do a Math.min for `members - candidates` & the desiredRunnersUp property. In other words, if there are more unelected candidates than the desiredRunnersUp count, then the actual count will always be equal to the desired count, e.g. 7/7. If there are less than the desired number (e.g. 5 runner-ups, as are currently on Edgeware), then we'll show that number, e.g. 5/7.

**Comment by raykyri** [comment]
That makes sense to me!
