### ISSUE TITLE
Bug: Mobile Footer Cut Off

### ISSUE THREAD

**Issue by markiscommon** [hicommonwealth/commonwealth#6721]
## Describe the bug

This is a sitewide issue as we have a margin issue on mobile. On the mobile app, when a user is creating a community, they cannot actually click "launch community" because they cannot scroll to it. The image provided shows the closest the user can get. 

Goal: We want the user to be able to click "launch community" in order on the mobile app. 

![IMG_9019](https://github.com/hicommonwealth/commonwealth/assets/128752305/5f894cd5-516c-4cdd-85ac-1e5b91f39045)

### Initial conditions
demo environment mobile 

## Reproduction steps
try to create community 

## Actual behavior
should be able to click create community

**Comment by jnaviask** [comment]
Also present on threads pages -- may be site-wide.

**Comment by mzparacha** [comment]
Cant repro on mobile Safari with Address bar in both the top and bottom positions.

**Comment by jnaviask** [comment]
Growth team can no longer reproduce.
