### ISSUE TITLE
Mixpanel Request: Buy Stake from banner, Manage Stake 

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6734]
## Description
This ticket is split off from this one https://github.com/hicommonwealth/commonwealth/issues/5886

We will want to track the growth of communities with Community Stake feature enabled. Additionally the growth rate of communities using community stake is trackable in mixpanel. This is both the users joining communities with stake activated and the overall population of communities with stake activated.

We could like to log data in Mixpanel for when a user interacts with Community Stakes. Please create mixpanel events for the following: 
- [ ]  'Buy stake' button in the CWCommunityStakeBanner is clicked.
- [ ]  'Manage Stake in the sidebar StakeSidebarModule is clicked

## Project Owner
@HIM92 

## Engineering Requirements
- A new property for Community Stake being enabled for tracking the community.
- The log should include the community id and user id (and user active address).

**Comment by Israellund** [comment]
Spoke with @HIM92 and he said that Manage Stake is something that was part of an older version of this and that it isn't applicable to this ticket anymore.
I added a Mixpanel call for when someone buys or sells stake, with separate logs for each. "Stake Bought" and "Stake Sold"
