### ISSUE TITLE
Random name Generation

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6751]
## Description
Goal: Offer users the option to generate a random username while on the username modal.

- User Story: As a new user on Common, I select "Generate Random Username" on the username modal. Subsequently, I receive a randomly generated username comprising a noun, an adjective, and a 2 digit number.

## Acceptance Criteria

- [x] Random names must contain an adjective+noun+2 digit number, i.e. "Fastboat10"
- [x] Generated or user provided usernames must be unique

## Additional context

Here is one github repository, although we could use any others: https://github.com/weaver/moniker.

**Comment by mzparacha** [comment]
Will be using https://www.npmjs.com/package/unique-username-generator
