### ISSUE TITLE
Email address importing for email sso

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6752]
## Description

Goal: Automate registration for new users signing up with Google and Email Address, prefilled email and suggested username.

- User story: As a new user signing up with Google (Cowfan1991@gmail.com), upon selection, the "Welcome to Common!" page should display prefilled email and suggest a random username (https://github.com/hicommonwealth/commonwealth/issues/6751)

<img width="392" alt="Screenshot 2024-03-20 at 12 09 47 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/8e4dc5b3-3b7e-4987-acdd-f2aedd5aab2f">

## Additional context
Design: https://www.figma.com/file/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?type=design&node-id=802-1672&mode=design&t=Xaw4zCBQcOOwAjBP-0

**Comment by mzparacha** [comment]
There is currently a bug in the app, when a user sign's up with any SSO service, the email used on that service is not stored on the db. Will fix the bug in this ticket.

**Comment by jnaviask** [comment]
Blocked by #7864

**Comment by mzparacha** [comment]
Update: There is a new bug report https://github.com/hicommonwealth/commonwealth/issues/7943, resolution of this ticket will also resolve that bug.
