### ISSUE TITLE
Stake "Growl"

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6763]
## Description

Make a "Growl" Component that announces Stake that includes the following:

Section | Content
-- | --
"Growl" concept | Community Stake
Header text | Introducing Community Stake
Body text | Empower members with onchain ownership, gated access and enhanced voting power with Community Stake
Button text | Create Community Stake
Button destination |  
(Where is the button taking the user to?) | https://commonwealth.im/createCommunity
Caption Text | Currently only newly created communities can enable stake
Learn More | Learn More
Learn more Destination | Community Stake Blog
<hr>

## Project Owner

@HIM92 

## Engineering Requirements
- Use existing "Growl"
- Enable metadata (above example) to be injected into component 
- Support future work allowing superadmins to: 
    - Enable / disable current growl 
    - Update growl metadata (per above, "Growl concept" excepted) 
    - Maintain a library of re-usable growls 

## Acceptance Criteria

- All the content above is in the Growl 

## Additional context
![Image (1)](https://github.com/hicommonwealth/commonwealth/assets/153562904/2be82376-56bc-4026-b6ef-20a36dfcab99)
![Screen Shot 2024-02-15 at 2 48 37 PM](https://github.com/hicommonwealth/commonwealth/assets/153562904/3b9906f9-02f8-41fd-9c77-c2eed69ec056)

Figma: https://www.figma.com/file/hyUNgm5nBfFDAa0gmxDptE/Growls?type=design&node-id=13-3384&mode=design&t=O2Gqa86eIvpop4QR-0

## Open Questions
- Is the above metadata table complete WRT to future needs?

**Comment by Miaplacidus** [comment]
@zakhap @CowMuon 
For clarification, there is an existing, re-usable Growl component. So, effectively, the ask for "templatize" has been completed. 

There are no details on what is required to support the ability for super-admins to manipulate growls via the UI. I'm thinking that should be separate ticket, anyhow.

Just adding a growl with text seems like a 2-pointer at most (not seeing associated designs, so adding some padding here assuming something not terribly complex).

Pinging @lzach83 to see if he has any input.

**Comment by lzach83** [comment]
This ___should___ be super simple to implement. It seems we follow the same kind of template for all of these growls. 

See: https://github.com/hicommonwealth/commonwealth/pull/5841/files

for a simple launch point.

**Comment by masvelio** [comment]
> Support future work allowing superadmins to:
- Enable / disable current growl
- Update growl metadata (per above, "Growl concept" excepted)
- Maintain a library of re-usable growls

@ForestMars @zakhap I agree that this should be a separate ticket. I will be happy to work it out and create cms-ish tool for growth.
