### ISSUE TITLE
Reorder Network selection dropdown during create community flow

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6765]
## Description

Goal: Update Network selection (divide stake enabled from non stake networks) so that stake enabled networks are at the top of the list, and all others are ranked beneath them alphabetically.  Stake enabled networks should be annotated with "Community Stake"

Ordering requirements: Base is the top chain on the network selection and is annotated with "Community Stake" - see figma.

User story: I am a founder on common and I am setting up my community, when I choose the network from the dropdown I see Base is the top chain available and it is clear Community Stake is available on that network. All other chains are listed out afterwards in A-Z alphabetical order.

<img width="352" alt="Screenshot 2024-02-23 at 10 17 44 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/16414cc6-d29d-4055-90e5-f929d000537a">

## Acceptance Criteria
Any chain that stake is later launched on should automatically receive the "community stake" annotation when contracts are deployed there. 

## Additional context
Figma link: https://www.figma.com/file/omZZrndm6Phbk1rOU4IKhS/Stake-V1-Fast-Follows?type=design&node-id=78-7917&mode=design&t=IyCKWExJP0dVo3Vl-0

**Comment by jnaviask** [comment]
@HIM92 any copy to explain to users what "stake-able" means?

**Comment by CowMuon** [comment]
We would like this for `v1.2.0` but should not be a release blocker @ilijabojanovic

**Comment by zakhap** [comment]
With Blast launch on Thursday, we will want to include "Blast" with "Base" at the top of the dropdown.
