### ISSUE TITLE
Stake buy/sell modal - enter quantity directly

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6766]
## Description
Goal: Users should be able to input the number of Stake they want to buy/mint/sell/burn on the stake modal rather than needing to just use the “+” or “-”.

User story: I am a user buying stake in common, I want to buy 100. I am able to click on the “1”  on the buy or sell input and change it to 100, or any other figure up to 6 digits. 

Note: There are no fractional numbers or decimals allowed in the stake modal.

<img width="484" alt="Screenshot 2024-02-14 at 9 23 37 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/c26923bf-4652-4615-a9be-0b177f63d65a">

**Comment by HIM92** [comment]
I would like it to look as similar to the previous design as possible, including the gray background if the user clicks out of editing the figure.

**Comment by HIM92** [comment]
I also think the input box should be much narrower and only expand after 100 as the user inputs larger figured

**Comment by ianrowan** [comment]
with or without the border? 
<img width="502" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/cd14d186-4271-4260-be4f-91041fa252e5">

only reason I could see for border is to indicate its an input

**Comment by ianrowan** [comment]
End result. Basically same styling w/o the border https://www.loom.com/share/61e1cc9e926f44228becc4195b310bb2

**Comment by HIM92** [comment]
Love it
