### ISSUE TITLE
Cannot vote on chains using newest democracy module

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#679]
On Kulupu and Beresheet:

![image](https://user-images.githubusercontent.com/1273926/91507516-e21df880-e889-11ea-9d8a-7bdbdfd37c52.png)

cc @dillchen on this one too

**Comment by jnaviask** [comment]
Fixed in commit d6d112a8cccf439cb3339b11ce065b16ce385083 (still has #676 though on Beresheet)
