### ISSUE TITLE
[SPIKE-102] Self-managed "Growl" 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#6809]
## Description
Rather than asking Engineering to add interstitials to the app, Growth should be able to easily self-manage current active announcements to users. 

## Engineering Requirements
Per 6763](https://github.com/hicommonwealth/commonwealth/issues/6763
- Enable / disable current growl
- Update growl metadata (per above, "Growl concept" excepted)
- Maintain a library of re-usable growls

## Acceptance Criteria
- Report of findings with execution plan attached here (or added to [Engineering Spikes folder](https://drive.google.com/drive/u/0/folders/1U88uJVf_JorCCu1kJpG6gjzU1pn3sK8W) and linked here.) 
- Execution follows in #6810

## Additional context
- See #6763 Stake "Growl" for context 
- "Growl" is in quotes here since technically the interstitials we use are technically not growls.

**Comment by masvelio** [comment]
before we go into implementation #6810 we should then think about new designs for mobile growl. Until the logic for showing/hiding them will be the same for desktop & mobile, we should be able to manage growls from one place in super-admin-panel for both platforms (this should actually be the goal).

@jessmart1213 @jabell88

**Comment by masvelio** [comment]
according to the design team, there is no capacity for design work on growl right now. We can close this spike ticket and the implementation ticket https://github.com/hicommonwealth/commonwealth/issues/6810 will be moved to the backlog with "needs design"
