### ISSUE TITLE
🐞 Bug: User cannot create an associated post when creating or editing a topic

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6836]
The UI gives the user the option of creating a new post (under the soon-to-be created or currently edited topic). However, no such post is actually created. The ask here is to create a new post when a topic is edited or created.

* Admin Capabilities Topic creation page Figma [here](https://www.figma.com/file/ibuywR0bBcy3ZZhPXbjEJw/Community-Admin?node-id=278%3A7981&mode=dev)

* Edit Topic Modal:
![Image](https://github.com/hicommonwealth/commonwealth/assets/6057187/86d189eb-2075-4fe0-80db-b3dd3327b253)

**Comment by CowMuon** [comment]
Thanks Ifu. Unclear what the priority here is, will likely find out when P&D is back in office tomorrow. Also then we can hopefully better understand what happened here

**Comment by Miaplacidus** [comment]
Per conversation with product and design, we're removing the ability to simultaneously create a thread and a topic. As such, I am closing this ticket.
