### ISSUE TITLE
Running for councillor on Beresheet produces an event handling error

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#684]
This is also a post-TX event handling error, that does not affect the creation of the councillor candidacy.

![image](https://user-images.githubusercontent.com/1273926/91508592-cb2cd580-e88c-11ea-96e0-68eac2f1e441.png)

**Comment by jnaviask** [comment]
Fixed this particular crash in commit cc2ae5756256bce2c118501a2dd9a0ada8535caa.
