### ISSUE TITLE
Remove cruft for simultaneous creation of a thread and topic

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6847]
The decision has been made to remove logic around creating a thread and topic simultaneously. The front-end logic for this has been removed (see PR [#6495](https://github.com/hicommonwealth/commonwealth/pull/6495)). This ticket asks that the backend logic be removed as well. 

Follow-up: will require a migration to remove any related attributes.

@CowMuon @jnaviask <-- tagged for visibility

**Comment by jnaviask** [comment]
Does a record of the "decision that was made" exist anywhere? This ticket seems underscoped in relation to the PR provided as solution. Unclear what exactly was signed off on wrt product changes and by whom.

**Comment by Miaplacidus** [comment]
The decision was made during a [conversation](https://commonxyz.slack.com/archives/C052DMYFKDL/p1708557450858019) with @zakhap and @jessmart1213 in the #design-product channel to remove the functionality for creating a topic and thread simultaneously. 

It seems that @sachben91 has confirmed that this is the case, as well, in a later conversation. As such, are we moving forward with this ticket, @jnaviask?

**Comment by jnaviask** [comment]
I don't see how the linked conversation implies the removal of "Featured in New Post" and default templates...

**Comment by Miaplacidus** [comment]
Closing this ticket. Will be handled in [#6997](https://github.com/hicommonwealth/commonwealth/issues/6997)
