### ISSUE TITLE
Internal tool for community name changes

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#6849]
## Description

#6801 and #6794 are two examples of community name change requests. Historically we handle these requests by constructing a database query manually (like in #5758), but as the app scales, we expect to see more and more of these.

We should write a script or some sort of internal tool (perhaps in the super admin panel?) that executes name changes.
- To begin with, we should simply change the name of the community + modify all the relevant DB objects.
- Additionally, we should maintain the old name of the community via a redirect (may be worth ticketing separately).

**Comment by timolegros** [comment]
Two points includes setting up an API route + entry on super-admin panel for updating the community ID. It does _not_ include setting up community redirect.
