### ISSUE TITLE
Add buttons for running for councillor & setting councillor votes to NewProposalButton dropdown menu

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#685]
Otherwise it is impossible to take those actions from mobile.

They should be added to the bottom of the menu, separated from the items above by a divider. (So it's New Thread -> the various New Proposal buttons -> run or vote for councillor, each stage separated by a divider).

**Comment by gdjohnson** [comment]
Should we display the NewProposalButton on council pages then? Currently it's left out; there's a bit of a space issue we begin to run into

**Comment by gdjohnson** [comment]
Second related Q: do we only wanna show these options on council pages, or should they be displayed on any chain community page?

**Comment by raykyri** [comment]
Ah yes we should - they should probably be displayed on most chain community pages!
