### ISSUE TITLE
Update link on create community stake

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6854]
## Describe the bug

Learn more about the community stake should point navigate to:
https://blog.commonwealth.im/community-stake-100-owners-around-any-idea/
### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Screenshots / Video

https://app.screencast.com/Q1M46lQ7GiHif?conversation=05vbxbl9TKsj7loyf6I6XM

**Comment by CowMuon** [comment]
Grab-n-go, who wants it? 

@Israellund @Miaplacidus @mzparacha @lzach83 

This needs to get into today's release `v1.2.0`

**Comment by lzach83** [comment]
I believe this is already done @CowMuon
