### ISSUE TITLE
Update explore and directory pages with new card designs

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6869]
## Description

Goal: Cards on the explore page need to reflect the new designs

<img width="395" alt="Screenshot 2024-02-23 at 11 47 55 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/732aef05-9e24-4fb2-880c-99ed415e3d34">

## Additional context
https://www.figma.com/file/omZZrndm6Phbk1rOU4IKhS/Stake-V1-Fast-Follows?type=design&mode=design&t=DkQY7hY46jMASDad-0

**Comment by Miaplacidus** [comment]
Hey @HIM92!
I just want to spell out the requirements on this card. We have an existing community card component that does not have the stake information in the upper right corner as shown in the designs. I noticed there's a 'Stake' button in the community filter bar up top. Shall I assume that the stake info is to be added to the community card after that has been implemented?
