### ISSUE TITLE
 Implement Stake Icon and Price Display on Explore Page for Community Cards

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6870]
## Description
Goal: add stake button to community cards on explore page + provide community stake token price. 

User story: As a user on Common, I can go to my explore page and discern which communities have stake enabled and which do not because of the "buy stake" button, and the stake token price provided on the community card, as well as the change in the price over the previous 24 hours provided as a % change. When I click the buy stake button, I am shown the modal to acquire stake for that community specifically. If I am not using the network stake was launched on, I am prompted to change the network on my metamask, or other EVM, wallet.

The price of tokens is shown if stake has been enabled on that community. This price is the cost of the next stake to be minted. 

The % is the % change in the cost of those tokens. I.e. if they go from $1 to $2, that is a 100% increase over the 24 hour period. The 24 is a rolling 24 hour calculation. 
 
![Screen Shot 2024-02-28 at 10 51 30 AM](https://github.com/hicommonwealth/commonwealth/assets/153562904/e1e6b927-0535-442f-9ab0-613565e41911)

## Additional context
designs: https://www.figma.com/file/omZZrndm6Phbk1rOU4IKhS/Stake-V1-Fast-Follows?type=design&node-id=427-3588&mode=design&t=6qrGmjBED9ixJ6pj-0

**Comment by Miaplacidus** [comment]
Hey, @HIM92!
A few questions about the description above.
There's a reference to a stake icon being present on communities that have stake enabled. However, there is no such icon in the designs. There is a button that says 'Stake' however. What should the behavior of that button be (I'm guessing the same as 'Buy Stake', but I'd like to confirm). Under what circumstances should the stake data in the upper-right-hand corner of the community card appear? What exactly are the percentage values in the corner?

**Comment by HIM92** [comment]
Heyo, thank you for you patience while we're all travelling. 

Added more info and designs have been updated for added clarity! and put more info on the price behavior

**Comment by Miaplacidus** [comment]
The PR for #6869 contains the changes in this issue, as such, ignore the PR associated with this ticket (#6967)
