### ISSUE TITLE
Implement 'Join' Button on Community Cards for Direct Community Enrollment

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6872]
## Description
Goal: Add join button to community cards. Users can join directly from the explore page. 
- if the user does not have a connected wallet address for that network, the button should be grayed out. 

User story: As a user on Common, I am on the explore page and I can join a community directly from here by clicking the “join” button on the community card. I get confirmation that I have joined the community after click the “join” button. If i join the community, the button is grayed out. 

User story 2: As a user on common who only has an ETH address, I am on the explore page and communities built on EVM, and I am able to join all the communities that I meet the criteria for. For communities that I do not meet the joining criteria, such as having a cosmos wallet, the join button should be grayed out. If I hover over the grayed out join button, text shows up that says "See community requirements to join."

## Additional context
desgins: https://www.figma.com/file/omZZrndm6Phbk1rOU4IKhS/Stake-V1-Fast-Follows?type=design&mode=design&t=DkQY7hY46jMASDad-0

**Comment by mzparacha** [comment]
Blocked by https://github.com/hicommonwealth/commonwealth/issues/6872#issuecomment-1973386207

**Comment by mzparacha** [comment]
Thanks for updating @HIM92

**Comment by mzparacha** [comment]
Update: Currently we don't support community joining/linking in non-scoped pages, per requirements this ticket would involve updating the community joining logic to work in the context of non-scoped pages.

**Comment by HIM92** [comment]
Ack @mzparacha, we will descope this from the ticket. Will move this from the milestone

**Comment by mzparacha** [comment]
Per discussion (async) with @HIM92, we are not doing this RN, moving this to the backlog.

**Comment by ForestMars** [comment]
This can be removed from the backlog. Please regroup and bring to refinement again if needed. @HIM92 @jarbell88 @ Jessica (GH?)
