### ISSUE TITLE
🪣  Stake for existing communities

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6877]
## Description
Goal: enable stake for existing communities. The user should experience the same steps to launch stake once they have clicked enable stake on integrations page. They must then identify their namespace and provide a symbol, or ticket, for their community stake. After this, they sign the transactions to launch it for their community. 

- [x] https://github.com/hicommonwealth/commonwealth/issues/6684
- [x] https://github.com/hicommonwealth/commonwealth/issues/6688
- [x] https://github.com/hicommonwealth/commonwealth/issues/6689
- [x] https://github.com/hicommonwealth/commonwealth/issues/6680

Designs: https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1738-83886&mode=design&t=ml6ROKLyh2WD1SB1-4

**Comment by HIM92** [comment]
Blocked until we resolve whether we are launching on Ethereum or decoupling chain selection from community stake enablement.

**Comment by CowMuon** [comment]
@HIM92 Please remove `blocked` tag when story is unblocked? 🙏

**Comment by ForestMars** [comment]
Buckets should really be owned by the PM-- all material work is in child tickets.
