### ISSUE TITLE
New Account modal is missing when we have ROOT_DOMAIN_REBRAND=true flag

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6900]
## Describe the bug

When we enable `ROOT_DOMAIN_REBRAND=true`, new Account Modal is missing. User is automatically created on application. 
### Initial conditions

**Environment:** 
QA

**Branch/Release version:** 
Master/v1.2.0

**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Go to: https://qa.commonwealth.im/
2. Create new wallet account 
3. Click on sign in

## Actual behavior

On QA env, user will be automatically created

## Expected behavior

We should display new account modal
## Screenshots / Video

https://app.screencast.com/6sSSBKznFp7TE?conversation=FjWLPLGaRrkcULWgT0ROKi

**Comment by kurtisassad** [comment]
@ilijabojanovic I think this is not a bug but intended behaviour:

From https://github.com/hicommonwealth/commonwealth/pull/6520

> Now during a new wallet account signup, we no longer require the user to input their username/profile-pic, instead we directly create an account for them with the default Anonymous name

I can revert this specific behaviour if we want, but we should probably double check with product first
