### ISSUE TITLE
Create collection of unit testing utilities

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#6908]
## Description
Develop a set of reusable unit testing utilities capable of seeding the database with randomized and custom parameters before executing unit tests.

## Project Owner
@Rotorsoft 

## Engineering Requirements
- Create utilities under libs/model/test 
- Refactor existing db-seed method to use the new utilities 

## Acceptance Criteria
- Refactor existing tests (ddd) to use utils

**Comment by rbennettcw** [comment]
Implementing zod inference to generate mock data with `@anatine/zod-mock`. This requires creating a zod schema for each model that doesn't already have one.
