### ISSUE TITLE
Improved Notifications Subscription Data Model - Child of #6738

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#6916]
Child of #6738

## Description
![NotificationsImprovementERD-3 drawio](https://github.com/hicommonwealth/commonwealth/assets/62490329/6e166090-c2f9-4ada-85e2-f6d3c1203b21)

All data pertaining to _how_ a notification is sent is contained in the user object. That is, any device IDs/provider tokens should be stored on the user object and not on subscriptions. Subscriptions should only describe _when_ and _where_ a notification should be sent.

The new subscription data is split into 4 tables:

- `SubscriptionPreferences`
  - This table contains all subscription data that maps 1-1 with a user.
- `ThreadSubscriptions` and `CommentSubscriptions`
  - Maps users to a thread or comment respectively.
  - Users are automatically subscribed to threads or comments they create so table size will be at minimum the total number of threads/comments.
  - Subscriptions are only for the top-level replies. This means nested replies to a thread/comment don't generate a notification.
- `CommunityAlertsDisabled`
  - Records in this table indicate that a user has disabled chain-event and snapshot notifications for a specific community.
  - Since community alerts are enabled by default, we can reduce the number of rows by only storing communities that a user has disabled.

An alternative data model could mean loosening referential integrity and having a clean-up job to maintain eventual consistency. For example, this could mean converting the `CommunityAlertsDisabled` table to an array on the `Subscriptions` table.

## Engineering Requirements
- Create relevant tables
- Set up proper indexes according to planned query patterns
- Come up with a migration plan for moving from old to new subscriptions (TBD -- this is the main reason for 3 pointer)

## Edits
- Renamed `Subscriptions` table to `SubscriptionPreferences` for clarity.

**Comment by Rotorsoft** [comment]
LGTM 👍  - Just waiting to see the pseudo-logic of the notification policy? How do subscriptions have precedence over the others when overlapped, etc -> the rules to call the external service API.

**Comment by timolegros** [comment]
> LGTM 👍 - Just waiting to see the pseudo-logic of the notification policy? How do subscriptions have precedence over the others when overlapped, etc -> the rules to call the external service API.

This logic is available on [this figma](https://www.figma.com/file/VRD0Z72rRiQhcGnq8P21Vj/Notifications-diagram?type=whiteboard&node-id=0%3A1&t=vVz8Q9h3EdDQuCGY-1) that I linked to the bucket ticket today.

**Comment by timolegros** [comment]
Implementation is done and migration works as intended locally. Will be deploying to Frick in the morning to do some more extensive testing as it is quite a heavy migration.

**Comment by timolegros** [comment]
For clarification. While Community Alerts _may_ be enabled by default in the future, they currently are not so it is much better to store 'enabled' alerts rather than 'disabled' alerts. As such `DisabledCommunityAlerts` will be renamed to `CommunityAlerts`
