### ISSUE TITLE
Subscription Commands and Queries - Child of #6738

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#6946]
Child of #6738

## Description
The scope of this ticket is to create all of the commands and queries (routes) needed to interact with the new subscription models.
- Subscriptions (mobile, email, and admin preferences)
  - GET `/user/subscriptionPreference`
  - PATCH `/user/subscriptionPreference`
- Community Alerts Disabled (chain-event/snapshot subscriptions disabled by community)
  - GET `/user/communityAlertDisabled`
  - PUT `/user/communityAlertDisabled`
  - DELETE  `/user/communityAlertDisabled/{id}`
- Subscriptions on objects (create by manually subscribing or when creating an object)
  - PUT `/user/threadSubscription/{id}`
  - DELETE `/user/commentSubscription/{id}`
  - PUT `/user/commentSubscription/{id}`
  - DELETE `/user/commentSubscription/{id}`

## Engineering Requirements
- Create the above routes using the command/query framework (potentially use tRPC depending on implementation progress)
- Modify user creation logic to include sensible subscription defaults (TBD)
- Commands/Query logic should be fully tested and documented with Swagger docs

**Comment by CowMuon** [comment]
If this is not blocked / has not dependencies, we'd like to target this for release `v1.3.1` (cutting next Thur 4/18) so that it's ready when PENG gets started. @timolegros

**Comment by timolegros** [comment]
The PR is ready but #6916 must be merged first. Once it is merged I will take the PR out of draft.
