### ISSUE TITLE
Wallets are not recognized on discussion page

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#6964]
## Describe the bug

When un signed user visit some discussion and click sign up, wallets modal is empty. 
### Initial conditions

**Environment:** 

QA/Production
**Branch/Release version:** 

Master
**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Go to: https://qa.commonwealth.im/dashboard/global
2. On dashboard Click on some discussion 
3. On discussion page click on Sing in

## Actual behavior

Application does not recognize installed wallets
## Expected behavior

On every page we should detect installed wallets in browser

## Screenshots / Video

https://app.screencast.com/Rb5YSA1zfrPvG

**Comment by mzparacha** [comment]
From the video, it seems to be expected behavior since the `membrane` community (the one in the video) requires cosmos-based wallets and the user has only the Phantom wallet installed.

Plz confirm @ilijabojanovic
