### ISSUE TITLE
"No available metamask address" on buy stake modal

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#6965]
## Describe the bug

A user is signed in with a metamask address and has joined a stake community, but they're getting "No Available metamask address" when they go to purchase stake.

Signing in and out resolved the problem.

### Initial conditions

**Environment:** production

**Branch/Release version:** v1.2.0

**Browser:** chrome(?)

**Wallet:** Metamask

## Reproduction steps

I could not reproduce myself but was happening on https://commonwealth.im/poker/discussions

## Screenshots / Video

![image](https://github.com/hicommonwealth/commonwealth/assets/1860629/da3e7a0e-9a83-4929-8779-60671230f971)

## Reporter

@RhysCommonwealth

**Comment by ianrowan** [comment]
Unable to reproduce, but for context of where this value comes from.

It isnt(directly pulled from metamask) its is from the `app.user` model and then filtered for addresses in the community. So the issue would've been with the general initialization of the user in the community if the addresses dont show up there.  

As far as I understand the components here - Addresses that the user has joined community with will show up here regarless of metamask connection atm. After selected address is passed to helpers and requested in MM. So here the general issue was that for some reason the users/profiles addresses didnt populate the app state. connection issue? 

CC @jnaviask
