### ISSUE TITLE
Create new "broker" port in libs/core

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#6972]
## Description
Implement a new "broker" port in the `libs/core` module to provide a publish/subscribe abstraction, facilitating asynchronous event-driven integrations. This abstraction will enable decoupled communication between different components of the system.

## Project Owner
@Rotorsoft 

## Engineering Requirements
- Define the interface for the broker, outlining methods for publishing events and subscribing to event topics - This is basically porting the existing [RabbitMQ abstraction](https://github.com/hicommonwealth/commonwealth/blob/dd14060654b51024d2adab18fdfff9f120a6f9ce/libs/adapters/src/rabbitmq/types/index.ts#L67) without leaking specific RabbitMQ details
- Consider new single source of truth for integration events in [Event Schemas](https://github.com/hicommonwealth/commonwealth/blob/master/libs/core/src/schemas/events.schemas.ts)
- Create a new RabbitMQ broker adapter by refactoring the existing RabbitMQ controller
- Consider specific configuration details (e.g. exchanges, queues, topics, routing) at the adapter level - the port should only be concerned about producers publishing events to a topic, and consumers subscribing to topics
  - Should we consider other integration patterns other than pub/sub?
  - Define DLQ conventions (should app errors block the queues?)
  - Define conventions/configuration details for # of retries, exponential backoff, logging errors, delivery guarantees (at-least-once, fire-and-forget, etc)
- Migrate apps from existing controller implementation to new adapter
- Refactor existing unit tests

## Acceptance Criteria
- Integration tests demonstrate the functionality and reliability of the broker

## Proposed Interface

Port the existing abstract class:

```typescript
export abstract class AbstractRabbitMQController {
  protected _initialized = false;

  public abstract init(): Promise<void>;

  public abstract startSubscription(
    messageProcessor: (data: TRmqMessages, ...args: any) => Promise<void>,
    subscriptionName: RascalSubscriptions,
    msgProcessorContext?: { [key: string]: any },
  ): Promise<any>;

  public abstract publish(
    data: TRmqMessages,
    publisherName: RascalPublications,
  ): Promise<any>;

  public abstract safePublish(
    publishData: TRmqMessages,
    objectId: number | string,
    publication: RascalPublications,
    DB: { sequelize: Sequelize; model: SafeRmqPublishSupported },
  ): Promise<any>;

  public abstract shutdown(): Promise<any>;

  public get initialized(): boolean {
    return this._initialized;
  }
}
```

to the minimum necessary abstraction to manage pub/sub integrations - to review

```typescript
export interface Broker extends Disposable {
  publish(topic: Topics, event: events.Events): Promise<any>; // event metadata should identify the producer
  safePublish(  ): Promise<void>; // is this just a publish option?

  subscribe(topic: Topics, handler: EventHandlerMetadata): Promise<void>; // handler should identify the consumer

  isHealthy():boolean; // if necessary

  // to dispose resources
  // dispose, name
}
```

**Comment by timolegros** [comment]
Bumped to 5 points because every instance of the `RabbitMQController` had to be updated (3 points in itself). Additionally, I need to extensively test on Frick with both snapshot-service (for which I need to spin up a new Heroku app) and the discord-bot. I will also likely need to write some new integration/unit tests to ensure everything is up to par. Aiming to finish this by EOD March 8.

**Comment by timolegros** [comment]
Blocking #6942
