### ISSUE TITLE
Contest Worker/Sequencer

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#6989]
## Description

To fulfill the product requirements of a gas free UX for Contests, a Worker/Transaction sequencing system should be built to handle pushing content and votes on-chain.

The proposed architecture for this is a queue worker/consumer with the platform itself being the message producer. We can use our existing RabbitMQ queue to handle messaging, while only requiring the platform to pass simple messages for content and votes(ie createThread and reactions) that have an associated contest. The consumer itself will need the following capabilities 
1. A funded EVM private key & way to store this
2. Access to RPC nodes for the valid networks
3. ABIs for contest function calls 
4. Listening and consuming from the newly created RMQ Queue. 

## Project Owner

@ianrowan @zakhap 

## Engineering Requirements

- Creation of a new RMQ Exchange/publication - consult @timolegros for questions of ideal arch here
- Creation of the worker/sequencer in a new package, deployable as a dyno - see https://github.com/hicommonwealth/commonwealth/tree/master/packages/discord-bot for example
- Worker Eng requirements are 
    - Listens to the relevant queue
    - Has access to RPC resources
    - upon receiving message(include everything necessary in the message schema) - determine correct network/addresses to send transactions
    - parse message into transaction and use ABI to send transactions on chain
        - Use securely stored private key
    - confirm successful transactions and include retry logic/error notif for failed transactions
    - Worker should be extendable to new types of transactions we need to sequence in the future 
- Platform requirements 
    - Add logic to create a message and push to queue on createThread and reactions in the related route controllers
- Security requirements 
   - propose a private key storage plan for the worker key(consult @egetekiner )
   - Include suggestions for how to track gas funds/warn when sequencer is running low 
  
## Acceptance Criteria

- Upon deployment of contracts and other platform work -> Threads in topics that have an on-chain topic should be pushed to chain via `addContent` without the user paying gas or being aware they're creating a transaction. Same for votes.  
- All content is available to vote for on-chain in a timely manner
 
## Additional context

- see https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764573734387460&cot=14 for a visual representation of this piece of contest arch

**Comment by ianrowan** [comment]
@egetekiner  here's the ticket for the contest worker. It looks like Platform team might be working on this too just fyi: #6822

**Comment by CowMuon** [comment]
**NB. There can only be one project owner.** @zakhap @ianrowan

**Comment by CowMuon** [comment]
@Rotorsoft Anything else needed here for execution on platform side?

**Comment by Rotorsoft** [comment]
As @ianrowan mentioned above, this sounds pretty close to what @rbennettcw is doing in #6822. Looks like we can merge both tickets (on the platform side)

**Comment by Rotorsoft** [comment]
@ianrowan @timolegros @egetekiner @rbennettcw @ForestMars - do you see anything here that hasn't been implemented by the contest worker policy and related integrations? I think we can close this one.

**Comment by ForestMars** [comment]
Good catch Roger, this one should really be marked as completed previous cycle.
