### ISSUE TITLE
Return member, thread, and token information associated with a community

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6995]
In order to place the [newly-designed community cards](https://github.com/hicommonwealth/commonwealth/issues/6870) on the 'Explore Community' page and on the directory page, we'll need to have the following information:

1. number of members in the community
2. number of threads associated with the community
3. the current price of the associated token for communities with stake enabled
4. the change in the price of the token over the past 24 hours

I believe the relevant controller methods to be updated are `__getRelatedCommunities` and `__getCommunities` under the directory `/server_communities_methods`.

@jnaviask @ForestMars <-- tagged for visibility and suggestions as to whom this should be assigned

**Comment by rbennettcw** [comment]
1 and 2 should be trivial to implement. 3 and 4 are more on the protocol side, so I'm checking w/ proto team to see how to get that info.

**Comment by rbennettcw** [comment]
For the current token price, there's the client-side function `getBuyPrice` –– Solutions:
- Simplest approach is to have the client be responsible for fetching prices using the function– assuming batching is not required
- Alternatively, logic can be shared w/ backend, and update the getCommunities route to batch fetch prices. Can't use TBC, so would need to implement the batching.

Leaning towards the client-side approach unless there's a reason we need it handled by the backend.

---

Regarding the 24h price change, that info isn't currently captured in the system –– Solutions:
- Create a subgraph(s) – (I'm looking into the specifics of how it would work with our contract)
- Create cron job to persist price in DB every 24h

The subgraph approach would be more friendly for external consumption, but could get complicated if we need to generate/deploy one for each community programatically. Cron job approach would be simpler.

**Comment by jnaviask** [comment]
@rbennettcw can you cut a separate ticket containing the above information that we can dispatch to the protocol team? They should be responsible for that side of the work and should expose helpers for the UI.

**Comment by rbennettcw** [comment]
@Miaplacidus I believe you can use the `getBuyPrice` function which is available on the client side to fetch the current price for each community. If this doesn't work for some reason (e.g. rate limiting), we can find another solution.

The 24h price change feature has been split into a new ticket for the protocol team: https://github.com/hicommonwealth/commonwealth/issues/7002

The scope of this current ticket is now:
- Update `getCommunities` and `getRelatedCommunities` routes to return number of members and threads for each
