### ISSUE TITLE
Mobile FYP width is wrong

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#6996]
## Describe the bug

On FYP user is able to scroll horizontally, on mobile. should not happen, leads to empty whitespace

### Initial conditions

https://www.loom.com/share/a04d133a19e445f3bf94542ccc794ab1

**Environment:** 
- Production
**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by lzach83** [comment]
I'm having issues reproducing this locally, can reproduce in prod.

**Comment by jnaviask** [comment]
@Miaplacidus to reproduce

**Comment by jnaviask** [comment]
Context from @dillchen: "Width is not set to the scroll of the whole page"

Screenshot: https://drive.google.com/open?id=1RQCCZmiEew-Z4xepDiTo7ORB5_p88Qnq
