### ISSUE TITLE
🐞 Bug: Unable to simultaneously create topic and associated thread template

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6997]
Prior, when you would navigate to the Topics section under the Admin Capabilities submenu, if you clicked the "Featured in New Post" checkbox and created a new post in the editor that would appear, nothing would happen.

The checkbox has since been removed, but if you'd like to confirm the presence of the bug, see PR [#6495](https://github.com/hicommonwealth/commonwealth/pull/6495) for details as to the code to re-add. 

The ask here is that this feature be made to work.

@jessmart1213 @zakhap <-- tagged to add further details

**Comment by zakhap** [comment]
> created a new post in the editor that would appear, nothing would happen.

This editor created a template for new threads, not a new thread itself. Then, upon saving, should have shown "New X Thread" in the create thread dropdown. When clicking that option and getting redirected to the New Thread form, the user would be presented with the thread body filled in with the template provided by the admin + the topic preselected. 

This feature is not creating a thread in the new topic!

**Comment by jnaviask** [comment]
Does not involve intended functionality.
