### ISSUE TITLE
Command to populate counts in a community on threads/comments

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#6999]
## Description

Today we did a discourse import, and it imports Reactions but did not properly populate reaction counts / comment counts. We should have a command that does the population manually, so we can recover from this error. See: commonwealth.im/sushi

Will ticket the discourse import issue separately.

**Comment by rbennettcw** [comment]
Existing command is `yarn recompute-counts`

**Comment by jnaviask** [comment]
Reopening because command did not work on a one-off dyno.
