### ISSUE TITLE
Breadcrumbs bug (groups)

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7004]
When clicking a link in the breadcrumbs, the target URL is marlformed and results in the page not being found.

Steps to reproduce:
- Go to the Edit Group page
- In the breadcrumbs, click Members
- Observe that the URL is invalid, page not found

## Acceptance criteria
- Breadcrumb links should go to a valid URL

**Comment by rbennettcw** [comment]
Video of repro:

https://github.com/hicommonwealth/commonwealth/assets/126922418/bddee832-1e98-4649-8570-27f86eafe675

**Comment by lzach83** [comment]
We originally believed that #7315 caused a regression that would resurface this ticket, apparently that is not true. After it was merged into Master this bug is not reappearing. 

Closing with comment.
