### ISSUE TITLE
Copy: Change copy for Stake modal depending on the funding token chosen

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7015]
## Description
Goal: funding token symbol changes on the buy stake modal depending on which asset the user adds as the funding token. 

User story: As a user who enabled stake on common, I chose an ERC20 as my community stake funding token. The symbol for this token is "ABC". On my community stake buyign modal: 

- [ ] "ABC" now appears in my current balance of the asset
- [ ] You have X stake valued at XXX line
- [ ] In the you buy portion of the stake modal
- [ ] Fees line
- [ ] Total cost line
- [ ] Buy / sell prompt for community stake

Images for reference:
<img width="488" alt="Screenshot 2024-03-06 at 12 40 43 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/7e7d8e1d-5ea5-4d06-b389-463a2f9f3543">

<img width="233" alt="Screenshot 2024-03-06 at 12 44 08 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/c3c4462c-0045-4928-b6e1-b91f8535ab76">

**Comment by Israellund** [comment]
NOTE: I overthought this ticket, moved estimation back to 1
