### ISSUE TITLE
Loading animation for PWA prompt

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7023]
## Description
We want to improve the user experience of the pwa prompt on the mobile site. Currently, it appears without any transition/animation which makes it seem jarring. The user should see a loading animation for the pwa when they open the mobile site.

## Feature specs
- User should see a pop-up animation for the pwa prompt wherever the pwa prompt is applicable. [Here is a prototype of the animation](https://www.figma.com/proto/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?page-id=1064%3A240&type=design&node-id=1064-2521&viewport=66%2C241%2C0.4&t=X4kNaWtDr3MwBJFx-1&scaling=min-zoom)

## Designs
[Figma ](https://www.figma.com/file/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?type=design&node-id=1064%3A240&mode=dev)

## Acceptance Criteria
- The popup animation should be triggered for the pwa prompt on Android and iphone when the user loads/re-loads the mobile site.  
- The implementation should not affect the current loading speed of the mobile site

**Comment by lzach83** [comment]
Not sure this is possible from an engineering perspective since that popup is a browser / device feature and not our app. 

Looking further into it...

**Comment by sachben91** [comment]
> Not sure this is possible from an engineering perspective since that popup is a browser / device feature and not our app.
> 
> Looking further into it...

@lzach83 the pop-up referred to here is the one that we show from the Common side and not the browser one. Try checking out Reddit on mobile, the pop-up they show to prompt app downloads has a small animation.
