### ISSUE TITLE
PWA/Mobile: Sign in modal is broken

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7047]
## Describe the bug

On PWA and mobile sign in modal is visually broken

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

Master/v1.2.2
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Lunch QA PWA app or go to https://qa.commonwealth.im/

## Actual behavior

Modal is broken

## Expected behavior

Modal should have clear sign in types

## Screenshots / Video

![Common](https://github.com/hicommonwealth/commonwealth/assets/8557292/53901a0f-061a-4b94-aa20-e7e8d9186525)

**Comment by mzparacha** [comment]
Duplicate https://github.com/hicommonwealth/commonwealth/issues/7027

cc: @ilijabojanovic
