### ISSUE TITLE
Contests Policy Contract Helpers

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#7052]
## Description

To assist the development of the services/policies for contest sequencing, contest helpers to interact with the contest contracts themselves. 

The main areas the policy will be concerned with are adding new content to a contest(s) and voting on content in a contest(s) 

## Engineering Requirements

The helpers should:
- Assist in the lookup of contest addresses to make transactions with 
- provide view functions for contest state and parameters 
- provide helper interfaces that can use digested thread and reaction models and create transactions to `addContent` and `voteContent`
- provide helpers for determining state of a given contest for use in error predicting/handling  

## Acceptance Criteria

- Contest policy can call simple helper functions to push transactions to the chain and read contest information 

## Additional context

- We will still need to determine, jointly, how the private key of the sequencer should be stored - this is both a platform security and protocol consideration. This will be required for helpers to work as they will likely abstract the use of the private key for signing and sending transactions

**Comment by ianrowan** [comment]
Noting this will be lightly blocked by 2 items 
1) #6822 arch/file structure decisions 
2) Contest Interface freeze

I know (2) should be unblocked at some point this week and will stay in touch with updates on (1)

**Comment by ianrowan** [comment]
Stubs created on branch [7052-contests-policy-contract-helpers-stubs](https://github.com/hicommonwealth/commonwealth/tree/7052-contests-policy-contract-helpers-stubs)

To be implemented after contest contracts are complete, should unblock development of #6822

**Comment by jnaviask** [comment]
Removed "blocked" tag as contract interfaces have been frozen.

**Comment by ForestMars** [comment]
Somewhat complicated dependencies here, this work was blocked by Contest Worker Policy which in turn was blocked by Contract Freeze. 

@ianrowan Do we have a target day next week in mind for execution? (queued up for sprint 4)
