### ISSUE TITLE
Integrate API for stakes transaction history

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#7059]
### Description
https://github.com/hicommonwealth/commonwealth/issues/6674 adds the stake transaction history tab UI. ATM, we don't have a preferred way to fetch stake history data.

We would need to display this data 

![image](https://github.com/hicommonwealth/commonwealth/assets/51641047/0845636c-3ab6-43df-ae2c-6bd682cd2d1f)

- Community - Community Stake symbol -- Community name is written beneath the symbol
- Address -Community Stake smart contract address
- Action - (either Mint or Burn)
- Stake - Number of stake minted or burned in the transaction
- Avg. Price - the average price of minting or burning per token
- Total Price - the total sum paid or received by minting or burning
- Timestamp - When the transaction took place historically, dd/mm/yyyy format or time since the transaction (whichever is an easier lift)
- The rightmost column is linked to the transaction on etherscan.

**Comment by jnaviask** [comment]
Blocked by #7059

**Comment by mzparacha** [comment]
Completed in https://github.com/hicommonwealth/commonwealth/pull/7239
