### ISSUE TITLE
Can't submit onchain TX with MM in Cosmos-EVM community

### ISSUE THREAD

**Issue by mhagel** [hicommonwealth/commonwealth#7084]
## Describe the bug

Can't submit an onchain transaction in Cosmos-EVM communities, even after signing in successfully

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reproduction steps

- go to /evmos, sign in with MetaMask
- attempt to create a proposal or vote onchain
- error banner says Cosmos Wallet not found

## Expected behavior

I should be able to create a proposal or vote with metamask in Evmos, Injective, evmos-dev, etc.

## Screenshots / Video

<img width="894" alt="Screenshot 2024-03-13 at 10 01 58 AM" src="https://github.com/hicommonwealth/commonwealth/assets/9438198/6dacc309-2865-4bbb-8e1b-cbe288b26531">

**Comment by jnaviask** [comment]
Wont fix.
