### ISSUE TITLE
Common 2024 "create onchain together" blog link to clickable 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7111]
## Describe the bug
There is a banner that is displayed at the top of the Common community which is supposed to link to the "create onchain together" blog but instead the link is displayed as text and is not clickable 

### Initial conditions
logged in and within the Common community
**Environment:** 
production
**Browser:** 
Safari 
**Wallet:** 
logged in with metamask 

## Reproduction steps
- log in and go to the Common community on Commonwealth
- observe the banner at the top 

## Actual behavior
- The banner should link to "create onchain together"  blog but instead it displays the whole link as text and is not clickable 

## Expected behavior
- "Create onchain together" should be the text and it should link to - [this blog](https://blog.commonwealth.im/introducing-common-create-onchain-together/)

## Screenshots / Video
<img width="1159" alt="Screenshot 2024-03-14 at 10 24 10 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/9b79a176-8f5c-4811-aab3-ff55c39309b4">

## Reporter
@sachben91

**Comment by Israellund** [comment]
Figma design link
https://www.figma.com/design/ibuywR0bBcy3ZZhPXbjEJw/Community-Admin?node-id=1252-3686&t=rCDNsJAHymvSBy02-0

**Comment by Israellund** [comment]
@MuhammadKaleem171  Please work on this ticket, and if you have any questions or problems you can @ me here. -Israel

**Comment by MuhammadKaleem171** [comment]
@Israellund Thank You I'm Currently working on it.
Just need to confirm if it's the same flow every time like we need to redirect to the provided banner url?
and text should always be "**create onchain together**" ? I Just need to make the link clickable as of **Terms Banner** link in the common community?

**Comment by MuhammadKaleem171** [comment]
Sure @Israellund I had send you an email regarding the Figma file.
