### ISSUE TITLE
Store Stake Transactions 

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#7119]
### Description

In the Community Stake [FF's](https://github.com/hicommonwealth/commonwealth/milestone/45), we want to add a transactions view for stakes -> "My Community Stakes" page , see 
- https://github.com/hicommonwealth/commonwealth/issues/6669
- https://github.com/hicommonwealth/commonwealth/issues/6674

which would look like this

<details>
<summary>screenshots</summary>
<img width="622" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/6f70823b-95aa-40ad-a15e-85e26365ec85">

<img width="622" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/7fed9a53-0482-49a1-818f-b4ff01e575da">
</details>

The columns (see screenshots) represent these data value

For "Stakes" tab (per https://github.com/hicommonwealth/commonwealth/issues/6669)

- Community - Community Info (stake symbol, id, name)
- Address -Community Stake smart contract address
- Stake - this is the amount of the stake that the user owns, per stake symbol. should only ever be whole numbers.
- Vote Weight - this is the collective vote weight of the stake that the user owners. This should only ever be whole numbers
- Avg. Price - the average price of minting or burning per token

For "Transaction History" tab (per https://github.com/hicommonwealth/commonwealth/issues/6674)

- Community - Community Info (stake symbol, id, name)
- Address -Community Stake smart contract address
- Action - (either Mint or Burn)
- Stake - Number of stake minted or burned in the transaction
- Avg. Price - the average price of minting or burning per token
- Total Price - the total sum paid or received by minting or burning
- Timestamp - When the transaction took place historically, dd/mm/yyyy format or time since the transaction (whichever is an easier lift)

ATM we don't have a way to get this data on the front end as we currently don't store it. 

### Engineering requirements
We want to have a way to store these transactions on the backend and expose an API for the users to get that data.

### Acceptance Criteria
N/A

### Additional context
N/A

**Comment by Rotorsoft** [comment]
@kurtisassad  you already delivered this ticket, not sure if this is a duplicate or how we are going to track the refactoring to a new projection.

**Comment by kurtisassad** [comment]
Yep I am pretty sure this one is done. @mzparacha can you confirm and if so close this ticket?

**Comment by mzparacha** [comment]
Yes, this can be closed.
