### ISSUE TITLE
Create Contest - Form Page (1/2)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7120]
### Create Contest Form Page
This page is a form for creating the transaction for deploying a Contest within a Community.

Form Input Configurations for Contest: 
- Contest Name
- Splash/Display Image
- Winner Payouts + Payout Percentages
- Use Community Funds?
- Recurring?
  - If one-off/not recurring, Choice of token for funding?
- Topics that submit content to Contests

Mobile Designs: https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=220-12764&mode=design&t=jSWEbMsjeCOfz3od-0

Desktop: https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=187-7848&mode=design&t=jSWEbMsjeCOfz3od-0

## Project Owner

@zakhap @jaredbell

## Acceptance Criteria

- As a user I can configure each of the contest input requirements.
- Designs are implemented to specification in Figma

## Additional context

<img width="371" alt="Screen Shot 2024-03-14 at 1 14 35 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/b716ee05-81a3-4c6a-91c4-32b43be63c97">

**Comment by masvelio** [comment]
1. Is contest only available for communities with stake enabled or for any community on any chain? 
2. Can't see anywhere on the designs new menu item under `Admin Capabilities` (in left sidebar) that will take admin user to  `Launch a contest` form page. Additionally, what would breadcrumb say for this page?
3. Do we want warning modal appear when user clicks `Cancel` button? If yes, copy needed. This is modal we use in create community.
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/f2e53682-cc37-4b82-97d1-0e1088ec5b43)
4. Where user is redirected after clicking `Cancel` button?


### Winners & payouts section
5. What is the default configuration, meaning, how many rows (how many prizes) and what is the percentage distribution.
6. We have `remove` and `add` winner buttons. Is there minimum and maximum number of winners that can be set in this view?

### Included Topics section
7. Here we list all available topics inside the community? 
8. Side question: what if I create a thread in the topic that is part of the contest and then change the thread's topic to the one without the contest? This high level question just to think if we have any problems in those kind of situations.

**Comment by masvelio** [comment]
estimation for only components work + form validation without backend integration => 2 days / 5 points

**Comment by jabell88** [comment]
@masvelio I'll answer what I can here. There are a few comments you made that I will also address in the Figma:

1. Contests are available to non-staked communities because you can fund the contest directly. Non-staked communities would have the “use community funds” selection disabled. 
2. Contest should appear under the admin capabilities and as a topic under discussion. Sorry, I only had this in the view step not in the enablement step. 
3. This is a good call, I will add a cancel modal to the designs. 
4. Cancel should return to the contests overview page. 
5. I will add breadcrumbs. 

Winners/Payouts - I’ll leave this for product

8. Yes, show a list of all topics with the toggles
9. Great question, I will also leave this for product

**Comment by zakhap** [comment]
1. Currently, only stake-enabled communities can have contests as the vote-weight calculation onchain requires stake. This **will** be changeable toward the end of the quarter/Q3 when we allow different vote-weight strategies to be used by the community for upvotes (onchain + offchain).
2. Admins will be able to create a contest via the Contests page, visible only to admins until the community has at least 1 contest. The empty state of the Contests Page is only for admins. 
3. Modal ✅ 
4. Cancel should take the user back to the Contests page
5. Jared's addition: ✅ 
6. Dillon's response ✅  3 winners: 60/25/15
7. Minimum 1, Maximum 10
8. Correct, we list all the topics.
9. Submitting to a contest happens at the point of Thread creation. Once submitted to a contest, there is no "unsubmitting" from a contest. In this way, if a thread is moved to another topic _after already being submitted onchain_, it does not impact the contest onchain. Inversely, if a thread is made in a non-contest topic and then moved into a contest topic, it is **not** submitted onchain to the contest as submission only happens during thread creation.
