### ISSUE TITLE
WIP: Allowlist - Table Component on Create/Edit Group Form Page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7129]
## Description

[Detailed behaviors here]

Devlink: https://www.figma.com/file/u9xVULF2IzBU4riycghQil/Gating-v2?type=design&node-id=522-14405&mode=design&t=IWgV0xRwiVirZq0f-0

## Additional context

<img width="752" alt="Screen Shot 2024-03-14 at 1 54 25 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/06eb3558-ffaf-44c2-a195-aacad1d674ea">

**Comment by kurtisassad** [comment]
The pagination button component at the bottom is not clear. Lets say there are 20 pages and we are on the 10th page, what do we expect the pagination buttons to look like (Where would the ellipses be?)

<img width="500" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14794654/49e34c33-fbda-407d-885f-35f6a67b6932">

**Comment by kurtisassad** [comment]
I will split the Pagination Button part out into a separate ticket since it will take more work and should be assigned to someone who works closer to PENG side:
https://github.com/hicommonwealth/commonwealth/issues/7821
