### ISSUE TITLE
Allowlist Behavior within Groups

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7131]
## Description

As stated in the bucket #7126, Allowlist on each Group will function as a big "OR":
> n of m onchain requirements OR in allowlist.

This needs to be reflected in the backend to handle this.

## Project Owner

@zakhap @jaredbell

**Comment by ForestMars** [comment]
I see this still has `needs-spec` label? 
Is this ready to go? @lzach83 @zakhap
