### ISSUE TITLE
Create monitors for Heroku Scheduler jobs

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7142]
## Description

We currently have no way of knowing if a Heroku Scheduler script is failing before startup (e.g. no error logs since script never runs).
To alleviate this issue we need to create Datadog monitors in combination with health check pings. The monitors should be set to expect at least 1 ping during the interval in which the script is supposed to execute (e.g. at least 1 ping every 10 min for CosmosGovNotification generator).

**Comment by ForestMars** [comment]
Perhaps @kurtisassad can add this monitoring when he gets back. (so, Sprint 4)

**Comment by timolegros** [comment]
@kurtisassad this issue should technically remain open until the monitors are created on Datadog post-deployment. Fine to keep it closed just can't forget to add the monitors once we deploy.
