### ISSUE TITLE
Link RabbitMQ via attachments for Snapshot + Discobot

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7145]
## Describe the bug
Currently, we hardcode the RabbitMQ env var from `commonwealthapp` on `discobot-listener` and `snapshot-listener`. This is prone to error because Heroku or CloudAMQP can perform maintenance on our RabbitMQ instance and modify the URI. By properly attaching the RabbitMQ instance, the URI will automatically update on all attached apps. This does not require any downtime but the discobot and snapshot apps will be re-released.

The same applies for `CW_DB_URL` in `cw-discourse-import` and `DATABASE_URL` in `discobot-listener`.

**Comment by ForestMars** [comment]
`v1.3.2`

**Comment by timolegros** [comment]
Done
