### ISSUE TITLE
Broken types on frontend for trpc

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#7154]
## Describe the bug

I found a nasty bug where the typescript types with Zod and TPRC are not working properly.

This manifested itself in a problem where the client failed to execute a query:

![image](https://github.com/hicommonwealth/commonwealth/assets/45447/8bd9fb8e-e389-46b2-83f2-e2755550fd53)

The work around was convert the topicId from a number to a string:

```typecript
topicId: topicId ? `${topicId}` : undefined,
```

but this shouldn't have even been possible. It should have been caught.

**Comment by burtonator** [comment]
Changing the underlying type and rebuilding doesn't fix this problem.

**Comment by burtonator** [comment]
We might be able to move the types for these to a new types repository that's strict.

**Comment by ForestMars** [comment]
Looks like CICD automation is no longer closing tickets when the linked PR is merged @burtonator @jnaviask
