### ISSUE TITLE
Fix infinite loop on Members page

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7155]
When scrolling through the Members page of a community, too many requests are made in quick succession. 

Steps to repro:
- Go to http://localhost:8080/ethereum/members?tab=all-members
- Scroll through members– observe that many network calls are fired

Video:
https://github.com/hicommonwealth/commonwealth/assets/126922418/f5b42a1f-42a8-498a-aa3d-74eebe4f9cdc

## Acceptance Criteria
When scrolling through the Members page, it should not make rapid network calls.

**Comment by rbennettcw** [comment]
Although it appears to be FE, I'm checking to see if the BE is sending duplicate profiles to the FE– which could cause rendering issues as shown in the video (multiple items with same key rendered in list).

**Comment by rbennettcw** [comment]
No dupes found in the backend payload for the profiles route. Wrote a script to go through 100 pages and check.

**Comment by lzach83** [comment]
Moving this back to backlog until there's more clarity here.
