### ISSUE TITLE
🐞 Bug: Member counts differ on explore and related communities pages

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#7180]
The members counts in the Community Cards on the Explore Communities and Community Directory pages differ. 

Note that the former makes use of `useFetchActiveCommunitiesQuery` and the latter makes use of the `useFetchRelatedCommunitiesQuery`. 

Issue in https://github.com/hicommonwealth/commonwealth/pull/6974 -- not on production.

**Comment by Israellund** [comment]
Closing this issue as it is fixed in [Kurtis' PR](https://github.com/hicommonwealth/commonwealth/pull/8071)
