### ISSUE TITLE
Common Wallet: Create Wallet Platform

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#7190]
## Description

Using Station GroupOS the first step to enable smart wallets for users is to allow a route for creating and configuring their smart account. The goal of this feature is to build platform side routes with controller functionality to interact with the groupOs API to create smart accounts and save the details in a new Model. data relating to the users smart account should also be available for the app/product to consume

- User and a Common Key should be valid signers on the new wallet

## Engineering Requirements

- validate User who wants to create smart account via session
- ensure User does not have a smart account on common yet
- Make call to group OS API to create smart account, add user and Common Public key as valid signers
- store address and other groupOS addressable data in existing or new model
- Read routes for users account

## Acceptance Criteria

- A route that can be called to create a smart account for Users who dont have one
- A route to provide data on user smart account

**Comment by ianrowan** [comment]
Call to station will look like: 
```
/v1/smart-account/create

Body: {
  customRef: string
}

Return: {
  success: boolean,
  evmAddress: string
}
```

Assuming custom ref will include params we can use to select wallets with access.

From here I think we should create a new model for mapping 'wallet' objects to users that includes:
1. the users signing address
2. the common/admin signing address
3. the wallet address
This should have a foreign key to the User model and suggest it isnt tied to addresses

**Comment by ForestMars** [comment]
I'm going to drop this into the backlog giving Station's message to us today. Let's circle back on what our approach here is going to be.

**Comment by ianrowan** [comment]
Unblocked given plans to use Alchemy. Will refactor existing work to support alchemy
