### ISSUE TITLE
Common Wallet: Platform side Transaction -> UserOp service

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#7191]
## Description

When request a transaction via their smart wallet, the tx data should be sent to the backend(either signed or to be signed by common). Upon receiving it should submit the tx to the groupOS API with required parsing. 

## Engineering Requirements

- Proper security to check that a tx was submitted by user(ie using session key) 
- automatic transmitting of signed txs
- parsing of unsigned txs 
- potentially only allow certain transactions 
- Relay parsed data to groupOS

## Acceptance Criteria

- Transaction data can be passed to platform and ends up submitted to chain by groupOS smart wallet

**Comment by ianrowan** [comment]
Confirmed we will only need to include:

```
/v1/smart-account/transact

Body: {
  chainId: number
  address: string
  transaction: {
    to: string
    value: string
    data: string
  }
  signatures: string[]
}

Return: {
  success: boolean,
  transactionHash: string
}
```
meaning we encode the desired transaction and sign with our key(push into signature)

**Comment by ForestMars** [comment]
Looks like this will roll over to S4 (sprint 4)

**Comment by ianrowan** [comment]
PR is ready but should be reviewed after #8044
