### ISSUE TITLE
Training cards

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7194]
## Description

Goal: Users are taught how to engage on common in four steps. When they complete each training card

User story: After creating my account on common, I see that there are four training cards on how I can interact with Common. Whenever I accomplish the task laid out in the training card I am told this because it receives a blue checkmark. I can dismiss a single training card by clicking the "x" on the card's top right corner, or I can dismiss all training cards by clicking dismiss at the top right hand corner above the training cards. 

In left to right order, the cards are:

- [x] Give an upvote: User completes this task when they upvote any comment, post, or content within any community.
- [x] Comment or post: User completes this task when they comment or post a new thread, or topic within any community
- [x] Edit my profile: Users are prompted to add an email or discord to their account. 
      - if a user has already provided an email as part of onboarding, then this card does not appear for them. 
- [x] Explore communities: User completes this by going to the explore community page once. 
- [x] When a user has accomplished any of the tasks, they receive a blue checkmark as provided in the designs. The next time the user refreshes the page, the completed card is removed. 

Dismissing training cards.
- [x] IF the user clicks "dismiss" all training cards are removed from the screen.
- [x] If the user hits the "x" in the top right corner of any of the cards, that specific card is dismissed. 

## Project Owner
- @HIM92 

## Additional context
Training cards:
<img width="560" alt="Screenshot 2024-03-20 at 11 33 17 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/67633f15-e6ea-476c-9ac9-7c5a9e2481e9">

Training card completion: 
<img width="560" alt="Screenshot 2024-03-20 at 11 33 13 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/fba60ed4-6edd-47e9-8c81-399d46170401">

Design: https://www.figma.com/file/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?type=design&node-id=802-1672&mode=design&t=dWeeEQc4xhu19qW9-0

**Comment by mzparacha** [comment]
Some questions
1. Where does the `Like a thread` or `Say hello` button take the user, if the user has joined multiple communities? Do we randomly redirect them to the most active community they joined?
2. Can the user "Dismiss" these cards permanently (like in the case of admin onboarding cards)?

cc: @HIM92

**Comment by HIM92** [comment]
@mzparacha it should take them to their "for you" feed. This shows them all the threads on the communities they've joined as well as some outside of those communities. They can like or comment on any of them if they choose to engage. 

2. User can dismiss the cards permanently - the x or dismiss all button is a permanent dismissal.

**Comment by mzparacha** [comment]
The Figma link is pointing to some other doc, please take a look. Thanks!

cc: @HIM92

**Comment by HIM92** [comment]
@mzparacha, please review the figma link attached. If you look at the figma link attached on the right hand side there is a screen called "user dashboard" and there are three screens provided. These have the training cards. Attached an image with them highlighted here: 
<img width="736" alt="Screenshot 2024-05-08 at 5 44 01 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/31fc3768-d908-4537-9da7-ea783170d2a6">

**Comment by mzparacha** [comment]
I am not sure if the description copy of the user training cards is outdated or incorrect. Example: the "Make a thread or comment" card has the description `Add custom topics to keep your discussions organized`, the other cards have similar inconsistencies. Can you plz confirm when you get a chance.

<img width="258" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/b2dba032-912d-49a2-8081-ae0ab225eb90">

cc: @HIM92

**Comment by HIM92** [comment]
I see that. 

1. Give an upvote -> "Show your support for a comment or thread by upvoting it!"
2. Make a post or comment -> Share your thoughts to contribute to a community.
3. Finish your profile -> Check out your profile page to add any socials or additional information. 
4. Explore Communities -> Check out other Communities on Common.
