### ISSUE TITLE
Join communities during onboarding

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7198]
## Description
Goal: Join a Community stage. Users are invited to join a community tagged with their interests, and high levels of engagement. 

User story: As a new user on common, I am nearly finished creating my account. I am prompted to join a community with four options based on engagement, popularity, the wallet address I signed up with (optional if signed up with EOA) and the preferences I selected in the previous step. If I select any of the communities I join them. 
I can click "x" to skip this step, or just click "lets go" without selecting any new communities. 

<img width="194" alt="Screenshot 2024-02-08 at 11 13 08 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/ef9510d2-b1b6-42ac-8392-55a438a1bc55">

## Additional context
designs: https://www.figma.com/file/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?type=design&node-id=802-1672&mode=design&t=Xaw4zCBQcOOwAjBP-0

**Comment by ForestMars** [comment]
What is the algorithm for picking which communities? @zakhap
