### ISSUE TITLE
Isolate chain events into separate processes (possibly using Celery)

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#720]
- Separate worker process on Heroku & locally
- Each process should initialize its own API / there could be one process per chain
- Do we need to use a message queue? Can we get away with chain events running as its own process?

Additional considerations:
- We should consider what the testing strategy for this is
- We should move sending emails into the queue as well

**Comment by raykyri** [comment]
This is higher priority now that chain events prevents the web server from booting.

**Comment by jnaviask** [comment]
> Do we need to use a message queue? Can we get away with chain events running as its own process?

We will need some sort of queue, or at least some sort of IPC setup if we're moving chain events into its own process, as the two will no longer share memory spaces.
