### ISSUE TITLE
🪣 Convert forum actions to framework commands

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7203]
Child of #6802 

Currently, most core functionality is implemented in controllers. We need to start refactoring the logic to conform to the DDD framework.

Create commands for the following actions:

## Commands

- Thread: #7240 
- Poll: #7241 
- Comment: #7246 
- Community: #7247  
- Chain Node: #7248 
- Group: #7250 
- Topic: #7251 
- Reaction: #7252 
- Webhook: #7255 
- Address: #7257 
- Role: #7259 
- Template: #7258 
- User: #7260 
- Profile: #7261 
- Discord: #7262 
- Image: #7263 
- Linking: #7264 
- Auth: #7265 

NOTE: Event emission should not be coupled to the model. Create a nice framework convention for it.

**Comment by rbennettcw** [comment]
@Rotorsoft I've created this ticket to track the creation of the commands. I've prioritized the forum commands since they represent core functionality. However I recall you mentioned Mixpanel in #6802?

**Comment by Rotorsoft** [comment]
yes, probably most of them are already on this list, but make sure to tag them.... and don't miss any other event emitters getting tracked in mixpanel - searching the enum should help

**Comment by rbennettcw** [comment]
This child tickets now represent all commands that are exposed via the API. Might be others that I missed if there are cronjobs or event-driven actions.

Will flesh out the child tickets incrementally as needed.

**Comment by rbennettcw** [comment]
@Rotorsoft – Per previous discussion, we should identify which commands/entities should be prioritized for the Contest work.

**Comment by Rotorsoft** [comment]
@rbennettcw you can find the model linked to #6824. The contest worker policy will react to thread creation and voting events (initially), so you should focus on the refactoring of these two commands and publishing the events (using a reusable pattern for future commands - we discussed a sequelize hook, but maybe we can create some reusable utilities here).

In summary:

[Create Thread](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764572226150780&cot=10)
[React on Thread](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764573738284336&cot=10)

You can confirm the names with the product team... I think we are using "react on thread" to represent future reactions, not just upvoting.

**Comment by rbennettcw** [comment]
Since we're building the new API gradually and releasing in phases + tracked by other tickets, it no longer makes sense to keep this ticket around.
