### ISSUE TITLE
Clean up Add social link in Edit Profile

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#7204]
Currently the `Add social link` input in Edit Profile is different than the newer version in Admin Capabilities -> Community Profile. They should look the same, have the same functionality, and use the updated methods/components.
-Work with Jess and Jared to update any design needs, possibly combining designs between the two inputs
-stop using `cw_socials.tsx`, update everything to be using `LinksArray`
-refactor any code as needed. 

![screenshot_2024-03-20_at_2 29 20___pm_720](https://github.com/hicommonwealth/commonwealth/assets/69872984/57b02da7-ee71-4bba-a37a-dc250707c2a5)
![screenshot_2024-03-20_at_2 30 49___pm_720](https://github.com/hicommonwealth/commonwealth/assets/69872984/bace6f2e-5a71-47de-a1ab-e12e3f20bbd1)

**Comment by dillchen** [comment]
I think this got addressed on the revised page, closing
