### ISSUE TITLE
"Set [on-chain] identity" on offchain community profiles should prompt you with a confirmationModal to go to the chain's profile

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#723]
Log into any account on an offchain community, and go to your own profile: http://localhost:8080/meta/account/npQ9qxmS6XafNyXoxcgB54ncR5hoQaPoYKbgg2gehd9wBiq?base=edgeware

The set on-chain identity modal doesn't work because you are not connected to a chain.

Should pop up a confirmation modal that says "Must switch to [Edgeware] to set on-chain identity. Continue?" -> Yes / Cancel (Not exact on the copy, feel free to improve if something easily comes to mind)

**Comment by gdjohnson** [comment]
By "the modal doesn't work," I'm guessing you're referring to the "Set identity" button within the modal being disabled (due to `!app.chain?.loaded`)?

**Comment by raykyri** [comment]
Yeah, but it doesn't seem to be disabled for me...we only disable it when `vnode.state.chainLoading` is true right now, right?on profile_header.ts line 32.

**Comment by gdjohnson** [comment]
So I assume we want to redirect them not just to the chain page, but to their address's profile _on_ the chain. The only issue is that it seems like, in many cases, the user won't have added "joined" the chain. E.g., let's say my Edgeware address oD7P is a member in Internal. However, only my address iqQi is a member of Edgeware. So if I want to continue on iqQi, and get switched over to oD7P, I no longer have permissions to set the identity for iqQi. I have to add the address, then switch to it, and only then can I set my identity. Are we ok leaving all that to manual, or do we wanna try to automate, or..?

Or am I misinterpreting what "switching" to Edgeware means? We already have chainLoading/initing logic set up, so I figured you're gesturing at switching pages.

**Comment by raykyri** [comment]
Oh yikes. Yeah, this requires more thought. I'll think about it for a bit...

**Comment by gdjohnson** [comment]
@raykyri I've spent a bit of time peeking through the codebase trying to figure out what we can do about this. My thought is, if there's (eg) an Edgeware address that has a membership role on Internal, and the user is visiting their Internal profile for that address, hoping to set the address's on-chain identity, well then there are three situations: either that address is also their active and default ("current active") account on Edgeware, or it's added but not the default, or it hasn't "joined" the community at all.

What if we have a simple switch: first, we check if the current profile address (the one they're setting an identity for) has a role on the (e.g.) Edgeware community. If they have a role, we just switch their activeAccount to that address when we re-direct them to their Edgeware profile. If they don't have a role—if they haven't joined Edgeware with the address—then we can trigger the Address selector modal, and let them join if they wish to.

**Comment by raykyri** [comment]
It seems sudden and unexpected to trigger the Address selector modal. Also I am worried that after closing out the modal, the user will have no way to get it to reappear.

I considered this:

![image](https://user-images.githubusercontent.com/1273926/94214317-1cc97f80-fe8e-11ea-9042-4ab43d7f1a4f.png)

But really it seems like addresses should implicitly always be members of the *chain* they are associated with. This would solve a lot of problems around having to go through the Manage Addresses modal after logging in with an address for the first time, etc.

Chains would have to be broken out as distinct from other communities but I think this makes sense:

![image](https://user-images.githubusercontent.com/1273926/94214532-af6a1e80-fe8e-11ea-87d2-94990fe1510d.png)

This seems like a larger project - what if for this ticket we just made the button direct you to the chain, and modified the chain profile page so this shows up if you have the address?

![image](https://user-images.githubusercontent.com/1273926/94214648-f3f5ba00-fe8e-11ea-9c0b-85b2d1984ae0.png)

**Comment by gdjohnson** [comment]
That seems much better! Will do

**Comment by gdjohnson** [comment]
@raykyri The one case this doesn't cover is if they have already joined a community with an address, but it is not their default address, i.e. when you switch over, the Role already exists but they do not have edit permissions for the Profile.

Would you rather I automatically switch the user to the address of the profile they're navigating to, or have an alternate button in the place of Join Community which reads (e.g.) "Switch to this profile/addr"?

**Comment by raykyri** [comment]
Both make sense; I think the "Switch to this address" button makes a little more sense right now as it's more straightforward and modular even though it is slighly slower UX.
