### ISSUE TITLE
Forum Commands: Subscriptions

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7254]
Child of #7203

## Acceptance Criteria
- There should be commands for the following actions
  - Subscriptions
    - CreateSubscription
    - DeleteSubscription
    - UpdateSubscription (enable/disable)
- There should be new tRPC and Express handlers
- The UI should be updated to use the new routes
- There should be async handling (notifications, analytics)
- There should be lifecycle tests (minimum 90% coverage)
- BDD Cases
  - TODO

**Comment by rbennettcw** [comment]
@timolegros This is the ticket for moving the subscription-related logic into the framework as commands. Please confirm if these routes are still relevant considering the recent changes to the notifications system.

**Comment by timolegros** [comment]
> @timolegros This is the ticket for moving the subscription-related logic into the framework as commands. Please confirm if these routes are still relevant considering the recent changes to the notifications system.

All of these routes will probably be deprecated. We can probably close this ticket in favor of #6946.
