### ISSUE TITLE
Update: Communities can have multiple contests + One-off Contests

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7292]
## Description

In the original event storming of the project, we only considered a single recurring contest for each community. 

Two Updates: 
1. With further validation with customers and growth team, we will now be supporting multiple contests within a community. 
2. One-off, not recurring, contests will also be supported. 

## Project Owner

@zakhap

## Acceptance Criteria

- We should be able to support a community having multiple contests running, some recurring and some one-offs.

**Comment by Rotorsoft** [comment]
@rbennettcw this should have minimal impact on the contest worker policy. Please to coordinate with the protocol team on how to interface with the "protocol domain service" to initiate new contests.

**Comment by rbennettcw** [comment]
Looks like this is taken into account by the projection in #6820.

**Comment by Rotorsoft** [comment]
@CowMuon I think we can close this issue

**Comment by Rotorsoft** [comment]
@jnaviask should we close this?
