### ISSUE TITLE
Admin Onboarding Card for Contests

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7295]
## Description

In our Admin Onboarding Carousel, we have multiple cards prompting the admins to finish setting up their community.

If an admin has not setup a contest in their community, we want to show them this new card prompting them to Create a Contest. Clicking the card should take the admin to the Contests page, which will be in its Null/Empty State. 

DevLink: https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=293-12334&mode=design&t=S18XZ7gukEEIYMtn-0

## Project Owner

@zakhap 

## Acceptance Criteria

- In EVM communities with and without Stake, we want to enable this new Create Contest Card in the admin onboarding carousel. Clicking this card will take them to the Contests Page. 

## Additional context

<img width="430" alt="Screen Shot 2024-03-28 at 3 07 53 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/fa64f06b-f976-4fdd-81fe-031fc6881d90">

**Comment by masvelio** [comment]
it looks like its a matter of adding one card to existing slider and changing old icons to new images. Estimation is 1 point then.
