### ISSUE TITLE
Contests Page, with Contests populated (2/2)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7297]
## Description

The Contests Page will not show the empty state after Contests exists within the community. 

Active Contests (recurring + one-offs) + Past Contests (one-offs, ended) will be shown on this page.

For each contest: 
- Show the Contest's Image
- The Contest Contract Address 

Leaderboard Button takes user to the Thread Listing Page, filtered by Contest + sorted by Upvote.
Previous Winners button takes user to the Thread Listing Page, filtered by Contest.
Share button opens dropdown to copy link.
Fund button opens the Fund Contest Drawer #7373 

Admin Buttons:
- Only Community Admins see these buttons
- Edit => Takes Admin to Edit Contest Form Page (#7298)
- Cancel => does not need to be implemented at this time.
- "Create Contest" Button => directs Admins to Create Contest Form Page (#7120)

DevLink: https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=297-19691&mode=design&t=S18XZ7gukEEIYMtn-0

## Project Owner

@zakhap 

## Engineering Requirements

- New Contests Card Component for displaying Contest Information

## Acceptance Criteria

- Display all active/past contests on the Contests Page using the Contest Card design
  - For admins, display the Edit + Cancel Contest Buttons. Do not show these to non-admins.
- Contest Card is implemented to design specification

## Additional context

ALL DESIGNS BELOW HERE ARE LINKED DIRECTLY ABOVE IN THE FIGMA LINK

![Image](https://github.com/hicommonwealth/commonwealth/assets/16248081/4483886a-b2a4-4184-95bf-79938a2ae1b3)
![Image](https://github.com/hicommonwealth/commonwealth/assets/16248081/72924d36-e590-4f84-a276-6b04e3bb9007)

**Comment by masvelio** [comment]
@zakhap @jabell88

1. Should we hide `Contests` menu item from left sidebar (this one from discussion section) if the contest feature is not enabled
2. From description: 
> Active Contests (recurring + one-offs) + Past Contests (one-offs, ended) will be shown on this page.

The design though shows `Active contents` as a header. Do we show ended contests for the user, or those are only visible in admin's contest page? Or maybe we should have more meaningful header?

3. From description: 
>The Contest Contract Address

Can't see the address anywhere on the contest card? 

4. How the card should be sorted? 
5. Did we think about any filter/sort/search for contests listing page?

**Comment by masvelio** [comment]
estimation for components with mocked data + listing page (without backend integration) => 3 points

**Comment by masvelio** [comment]
blocked by #7120

**Comment by zakhap** [comment]
1. Yes! Normal users should never end up on an empty Contests Page.
2. We will show ended contests to everyone. Past contests are still "important" insofar as users who participate will care about them, who/what won, and seeing the leaderboard.
3. The Address is currently just shown in the Fund Drawer. 
4. They should be sorted alphabetically, grouped by Active/Inactive.
5. No filter or search at this time, we don't expect n-many contests per community, though we are not currently putting a cap on the number of contests.
6. Contests in sidebar should be visible to everyone, if there is at least 1 contest in the community. Otherwise, only the admins can see it.
