### ISSUE TITLE
Contest Winner Tag on Thread 

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7300]
## Description

On Threads that have Won a Contest, we want to display a tag (similar to Stages) denoting such. 
This will be displayed on the Thread Listing Pages + on the Thread Page. 

DevLink: https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=304-12127&mode=design&t=S18XZ7gukEEIYMtn-0

## Project Owner

@zakhap 

## Acceptance Criteria

- New Thread Tag
- On hover popover with Contest Metadata
  - Contest Name, Date Contest Won, Round of Contest (if recurring Contest).

## Additional context

<img width="526" alt="Screen Shot 2024-03-28 at 3 49 20 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/692662d3-2541-4e56-bd59-a934b25f1475">
<img width="627" alt="Screen Shot 2024-03-28 at 3 52 48 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/cd7535c3-b0fc-4dc4-99fa-611231dbb54f">

**Comment by masvelio** [comment]
@zakhap @jabell88 
1. Is there a chance that one thread will be a winner (1st, 2nd, 3rd etc place) in multiple contests? So that the thread might have multiple badges? 
2. Will the badge go away after some time or it will visible on thread forever?

**Comment by zakhap** [comment]
1. There is that possibility.
2. It will stay forever, for the time being.
