### ISSUE TITLE
Filter Threads by Contest

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7302]
## Description

For Communities with Contests enabled, we want to allow users to filter threads by Contest on the Thread Listing Page. 

Filter by Contest will be in the same Dropdown as Topics. Users will not be able to Filter by both a Topic and a Contest, only one or the other. There are now labels in the dropdown menu to show the distinction between the two.

In the case in which a Contest is selected from the primary filter dropdown, the "Stages" dropdown will be switched for a "Status" dropdown that displays 3 options: Active (default), Past Winners, All.

DevLink: https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=304-12127&mode=design&t=S18XZ7gukEEIYMtn-0

## Project Owner

@zakhap 

## Acceptance Criteria

- As a user, I want to be able to filter by Contest.

## Additional context

<img width="843" alt="Screen Shot 2024-03-28 at 3 57 43 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/1f423c61-6bce-4eb4-a867-b5b9bfe8b1df">

![Image](https://github.com/hicommonwealth/commonwealth/assets/16248081/935f134b-0e99-41c2-a39e-0b33ea4fec57)

**Comment by jnaviask** [comment]
@zakhap what will the dropdown list look like? Will there be e.g. dividers? What order will we see them in? If there's a lot of contests how will we deal with it? etc

**Comment by zakhap** [comment]
The designs for the dropdown have been added to the figma and attached to the ticket.
