### ISSUE TITLE
Allow creating posts without topics iff the community/chain has no topics

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#732]
- Right now, we show a callout that says "The admin has not configured this community with topics" if the community has no topics. This is obtrusive and annoying for new community creators, and we should remove it
- If a community has no topics, the backend should allow a thread to be created without any topic. This should only be allowed if the community has no topics (in theory this should not matter since the topic dropdown should auto-populate with the first topic, but we should enforce the invariant just for consistency's sake)
- We should update the tests to reflect this
- If there is at least one topic in a community, the topic selector (in e.g. the new thread modal) should automatically populate with the first topic

**Comment by gdjohnson** [comment]
Think we'd be best removing the topic selector entirely in case of no tags?

![image](https://user-images.githubusercontent.com/22281010/92614717-5db87600-f28a-11ea-8eb4-c853429a0fc8.png)
![image](https://user-images.githubusercontent.com/22281010/92614800-732da000-f28a-11ea-8479-deaf4099b91b.png)

**Comment by raykyri** [comment]
yep that makes sense!
