### ISSUE TITLE
🪣 `/libs` Exporting/Importing DevX

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7361]
## Describe the bug

- Auto-complete for namespaces does not function properly.
- We export conflicting namespaces i.e. `commonProtocol` from both `/model` and `/core`
- We include arbitrary objects in namespaces. For example, the `schemas` namespace contains both EventName enums + types on top of all of the event and entity schemas.
  - We should simplify namespaces so that the name of the namespace properly reflects what is contained within.
- In several cases, namespaces are simply not necessary. For example, the `commonProtocol` namespace includes a very specific set of utils, many of which can already be traced back to the commonProtocol just by the way they are named.

- [x] #7501
- [x] #7575
- [x] #7576
- [x] #7843
- [x] #7897
- [x] #7929

**Comment by Rotorsoft** [comment]
We discussed this issue today with @burtonator and @rbennettcw in our weekly retro, and decided to start using a flatter lib structure to replace these internal "modules". @timolegros will start prioritizing the first modules, and provide more details in the sub tickets.

**Comment by timolegros** [comment]
Turns out that the first new package will be `/shared` as described here: https://github.com/hicommonwealth/commonwealth/issues/7396
