### ISSUE TITLE
Fund Contest Drawer Component

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7373]
## Description

All users will have the ability to fund any contest running in the community. To be able to do so easily, users will press a "Fund" button on the Contests Page (see: #7297) to trigger the drawer opening.

The Drawer will have three inputs, one of which is disabled: 
1. Dropdown selector showing the user's evm addresses, defaulting to the user's community member address (if there is one). Beneath, it will show the current balance of the token being used by the Contest for its pool.
2. Disabled: The Address of the Contract being funded, for transparency.
3. Standard number Input field, to allow the user to input how much of the token they want to deposit into the contract. If the user puts in a number higher than their balance, the input should show error state.

DevLink:  https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=368-20799&mode=design&t=UWyQAPeEUs5zuDsh-0

## Project Owner

@sachben91 @zakhap 
+Design: Jared

## Acceptance Criteria

- A Drawer Component that enables the user to deposit token to a specific Contest.
  - Should let the user select the address.
  - Should show the user the contract address.
  - Should let the user input the amount of token they want to deposit
  - Should dynamically render the token symbol + $TICKER as contests may use different tokens.
  - Should be accessible by any member of the community by pressed "Fund" on the Contest Card on the Contests Page. 
 
## Additional context

<img width="732" alt="Screen Shot 2024-04-04 at 1 08 33 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/431e4ea1-a951-4ab5-9400-aa9418e97fc3">

**Comment by masvelio** [comment]
Components should be done before in #7121 so it will be matter of creating a drawer, reuse the components, and make sure everything works correctly. Estimation => 2 points

**Comment by masvelio** [comment]
blocked by #7121

**Comment by masvelio** [comment]
bumping to 3 because the scope was bigger (it was smaller in #7121 though)
