### ISSUE TITLE
Enable a third party for github admin

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#7379]
@jnaviask is going to be on PTO which (I think) this means that @ForestMars is the only github admin.

We need to not bottleneck so I'd like to propose @timolegros also get Github admin.

I think the protocol should be that we post every change somewhere so that everyone is aware of the changes.

Also, I think both @ForestMars and @jnaviask will be on PTO at the same time coming up so we'd have no one with Github admin permissions during tha ttime.

**Comment by dillchen** [comment]
Not necessary, you can ping me
