### ISSUE TITLE
Update My Stakes page for multi-chain

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7414]
## Description

Please add the following changes to information provided on the My Stakes page.

- [x] MY STAKE tab: Change the denomination of average price on the my stake page from BASE to mainnet Ethereum. 
- [x] MY Stake tab: Add a column to the My Stakes Page and the Transaction history page that displays the chain community stake has been launched on
- Chain column should come before the Address column and after the Community column
- [x] Transaction history tab: Add a column to the My Stakes Page and the Transaction history page that displays the chain community stake has been launched on.
- Chain column should come BEFORE the Address column and after Community column

## Project Owner
@HIM92 

## Additional context
If the Transaction history begins to overflow outside of the margins of the page, allow it and allow the users

**Comment by CowMuon** [comment]
May as well catch this one too pls (with Stake Enablement 3 pointer, please FF2 update estimate) @lzach83

**Comment by ForestMars** [comment]
Estimate would be greatly appreciated.

**Comment by lzach83** [comment]
Is there a figma for this? Gut reaction is it's a 2 but without knowing what the UI will be it's hard to give a firm estimate. 

cc: @ForestMars @HIM92

**Comment by ForestMars** [comment]
@Israellund Can you pick this up from Zachary to top of your stack? Then in EOW we'll sync w @ilijabojanovic if it can still make it into v1.3.1, depending how strict that cutoff is

**Comment by Israellund** [comment]
@HIM92 @ForestMars @jessmart1213 Is there a Figma file for this?

**Comment by jabell88** [comment]
@Israellund Figma file is updated with the additional column for community chain. LMK if you have any questions/concerns. Thanks! 

https://www.figma.com/file/2IDrY6BAwADptR4AWB0Wjh/Portfolio-%26-Transactions?type=design&node-id=0%3A1&mode=design&t=W0ejucOBMZkS1Rzs-1

**Comment by HIM92** [comment]
<3
