### ISSUE TITLE
Register sitemaps in Google Search Console

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#7419]
## Describe the bug
Once the sitemaps have been implemented via #6173 we need to verify that they have been written properly and that Google can properly read the output.

https://search.google.com/search-console/

We need to complete this step with someone that has access to our DNS (@jnaviask @ForestMars)

Please invite @burtonator when done.

<img width="1357" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/45447/60d4e42c-64cd-4fba-b04a-44fa76abe450">

**Comment by jnaviask** [comment]
Search console has been configured (DNS target added via cloudflare) and PENG + Platform teams have been invited to the console.
