### ISSUE TITLE
Community stake: Is not possible to buy stake from explore communities page

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7430]
## Describe the bug

When user try to buy stake from explore communities page, we have console error and tx fail

### Initial conditions

**Environment:** 

Production
**Branch/Release version:** 

v1.3.0
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://commonwealth.im/communities
2. Sing in 
3. On Explore page click on stake
4. On communities with stake click to buy some stake

## Actual behavior

We are asking user to switch on main net where we don't have stake deployed

## Expected behavior

We should point to buy stake on proper chain 

## Screenshots / Video

https://app.screencast.com/XRRMsZhmTlogc

## Additional context

```
Error buying:  Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
```

**Comment by mzparacha** [comment]
This issue should not happen after https://github.com/hicommonwealth/commonwealth/pull/7181 is deployed.

cc: @ilijabojanovic
