### ISSUE TITLE
Implement Mava on Production

### ISSUE THREAD

**Issue by RhysCommonwealth** [hicommonwealth/commonwealth#7433]
## Description
After testing from the growth team, we would like to add the Mava chat service to production.
## Project Owner
Rhys
## Engineering Requirements
turn it on pls :)

## Acceptance Criteria

**Comment by ForestMars** [comment]
This is needed for `v1.3.2` 
- Would like to cut release for QA today (including this ticket #[7433](https://github.com/hicommonwealth/commonwealth/issues/7433)) 
- We aim to ship Monday morning, however it will likely go out Tuesday or Wednesday next week (I will be OOO all week and Jake is just getting back on Tuesday)

**Comment by burtonator** [comment]
@RhysCommonwealth who else needs access to this?

**Comment by RhysCommonwealth** [comment]
Mark & Zach

**Comment by burtonator** [comment]
This PR is done but I don't know what's up with master being ready to merge.

**Comment by burtonator** [comment]
OK. Invited.
