### ISSUE TITLE
Launchpad: Audit and Tests for launchpad contracts 

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#7436]
## Description 

Upon completion of the implementations of the Launchpad contracts they will need a general Audit and set of tests to be created. Items to consider will be very similar to CommunityStake work in the past. 

A major part of this task will be to set up test access to UniswapV3 contracts which @ianrowan and @egetekiner can collaborate on. this will likely be done via a fork on a local net within foundry. 

The files expected to be included in this audit/testing stage are
1. `CommonERC20.sol`
2. `LPBondingCurve.sol`
3. `Launchpad.sol`
4. `UniswapV3LPHook.sol`

## Deliverable 

PR of Launchpad code that is ready for an external Audit and deployment upon passing

**Comment by egetekiner** [comment]
CommonERC20 tests, internal static and dynamic audit and documentation completed with 96ffe6a commit. The internal documentation can be found under the following link:

https://docs.google.com/document/d/1ZlH3IyNvJNdldYiC1p61JrllfzJ5TAHUh7iRoP5YEEI/edit?usp=sharing

**Comment by jnaviask** [comment]
Tests are written, audit will be tracked separately.
