### ISSUE TITLE
Launchpad KOH: Build contract infrastructure for KOH contest

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#7437]
## Description 

This ticket will involve the ideation, prototyping, refining and creation of the KOH contest contract. KOH represents 'King of the Hill' which in the context of the launchpad is the token who sells the most units in a given period of time during a given period. 

The goals of this contract are:
1. Allow for tracking of # of each token bought on `LPBondingCurve.sol` during a given interval
2. A routing mechanism for protocol fees that should be used for KOH buys
3. accounting of fees and winner of a period
4. publicly callable function to roll the contest and make the buy
    - KOH contract should use accrued fees during the period to call the buyToken function on `LPBondingCurve.sol` for the winning token
    
## Considerations 
There was discussion about a more centralized version of this where indexing of txs/buy logic occurs on the Common platform. I think this could still be an architectural consideration as an event driven contest rollover service will need to be built regardless. 

## Deliverables

Architectural decisions and PR With the KOH Contract

**Comment by ForestMars** [comment]
Teeing this for Sprint 3, expectation is that everything should be work complete to go to QA next week.
