### ISSUE TITLE
Make Proposals generate OffchainThreads

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#745]
~~See server/routes/createReaction.ts on lines 77, 93, 94, 109, 118~~

~~This breaks notifications when someone else likes your comment on an on-chain proposal.~~ (fixed)

We should discuss the way OffchainComments are bound to proposals. The system would be more stable if we generated an OffchainThread for every Proposal, linked the two, and made OffchainComments linked only to OffchainThreads. At the very least we should inform the user if a Proposal has not received a ChainEntity yet on the frontend instead of letting that failure happen silently (since it breaks reactions/comments).

**Comment by jnaviask** [comment]
> The system would be more stable if we generated an OffchainThread for every Proposal, linked the two, and made OffchainComments linked only to OffchainThreads

I agree, and the db schema for ChainEntities (proposals) is built to support this -- there's an unused `thread_id` field which has an association already to OffchainThreads, so it should be easy to fixup the logic and support this as a 1-to-1 association. Then we can check if the association resolves and list a warning re: commenting if it doesn't.

**Comment by raykyri** [comment]
How this would be done:

- In entityArchival.ts: `const proposalThread = createNewThread()`, and then set thread_id to proposalThread.id on the ChainEntity
- Remove special casing for Proposals in createComment, createReaction, etc.
- Remove every use of proposalIdToEntity
- The only thing we use `Proposal` for right now is associations to comments...so that can be removed too
- The view_proposal page can now be converted into view_thread (for OffchainThreads only), and we should make a separate on-chain proposal voting page that just links back to the thread for discussion

**Comment by raykyri** [comment]
duplicate of #212
