### ISSUE TITLE
Canceling a Contest

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7463]
## Description

While we cannot stop the onchain contest contract, we can stop pushing new content to the chain.

The Cancel Button is only visible to admins. Clicking Cancel + confirming updates the Contests Metadata so that our backend stops submitting new threads to the contest.

DevLink: https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=297-19691&mode=design&t=AbzLkoeLsZG4oYMe-0

## Project Owner

@zakhap @sachben91 Jared

## Acceptance Criteria

- As an admin, I can cancel a contest, preventing new threads to be submitted to the contest contract.

## Additional context

<img width="472" alt="Screen Shot 2024-04-16 at 12 16 46 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/38528ee4-6a2b-4c6f-9b18-a6f0fa1ef9ba">

**Comment by masvelio** [comment]
bumping down to 1 as this is only UI. After backend will be done, then I will handle the integration
