### ISSUE TITLE
Use `AutoIdle` to reduce Heroku staging app costs

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7473]
## Description
Frick costs 209$ per month but is only used a fraction of the time. With [AutoIdle](https://elements.heroku.com/addons/autoidle) we can automatically turn off dynos we aren't using and wake them up automatically in seconds when we do need them.

With this add-on we can potentially save several hundred dollars on our cloud bill since we have many different Heroku apps that are rarely utilized.

**Comment by ForestMars** [comment]
If this is really a 1 pointer, let's jump this to top of queue please and save some money.

**Comment by timolegros** [comment]
I added the AutoIdle add-on to Frick. It seems to have trouble handling traffic from custom domains (such as `frick.commonwealth.im` -> to prevent request errors on dyno wake-up) when the `ssl.autoidleapp.com` CNAME is added. I contacted support to hopefully find a solution to get the `frick.commonwealth.im` domain working.

**Comment by timolegros** [comment]
Alright, support responded - we needed to set the 'proxy status' on Cloudflare for the `frick` CNAME to `DNS Only` rather than `Proxied`. AutoIdle will be adding this to their documentation as well.

If the Frick app is on idle, and you request `frick.commonwealth.im` AutoIdle will start the dynos and return a response when the dynos are ready. If you try to access via the Heroku URL: `https://commonwealth-frick.herokuapp.com/`, the request may fail until the dynos are back up.

This service costs 16$ a month so we should leave it running on Frick for 7 days and then review the cost savings. If at the end of the 7 days we are saving significant amounts (greater than 16$) we should add the AutoIdle add-on to frack, demo, QA and any other staging apps.

**Comment by timolegros** [comment]
This is not saving us nearly as much money as I had hoped. Any request coming in wakes the servers back up and in most cases these requests are from bots/crawlers and not from internal team members. I will leave it up for the full 7 days to make sure.

**Comment by timolegros** [comment]
We have saved ~13$ over the past 4 days with savings estimated to be ~50$ per month for Frick. This would lead to approximately 200$ in savings if applied across all of our apps.

I am in contact with the creator of AutoIdle who will hopefully introduce some user-agent-based filtering (remove crawlers) or IP allowlists so that we can eliminate app starts due to internet traffic that is out of our control.

**Comment by timolegros** [comment]
The developer clarified that he cannot implement crawler blocking because he does not have access to request headers. The savings from this add-on without crawler blocking are insignificant and it's not worth spending time configuring the add-on/Cloudflare CNAME. The CNAME change on Cloudflare has been reverted and I removed AutoIdle from Frick.
