### ISSUE TITLE
Add Tangle Chain as Substrate Community (Webb support)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7492]
## Description

Our good friends at Webb want to have a Common community for their Substrate Chain "Tangle". Currently, adding Substrate communities are a white-glove endeavors. 

RPCs are here: https://docs.tangle.tools/ https://docs.tangle.tools/docs/

Community Name: Tangle
Chain: Tangle
Description: An MPC-as-a-service restaking infrastructure.
Admin: 0x89db5277A310C473d515891cafCD4E66b8A7F06F

## Project Owner

@zakhap @dillchen 

## Acceptance Criteria

- Tangle community is created as substrate community, using the RPC referenced above for formatting the address properly in their community.

**Comment by ForestMars** [comment]
Jake has the knowledge here, as this is Substrate.

**Comment by jnaviask** [comment]
Chain has been created at https://commonwealth.im/tangle
