### ISSUE TITLE
[Bug] Community stake: User can't buy stake from side bar

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7493]
## Describe the bug

When user sign in on app and join some community, he can't buy stake from sidebar or on discussion page
### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

release/v1.3.1-x/Master
**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Sign in
3. Create community with stake
4. On side bar click to buy stake

## Actual behavior

User can't buy stake over sidebar
## Expected behavior

User should be able to buy stake over sidebar

## Screenshots / Video

https://app.screencast.com/7U9TlAAnYlEvL

**Comment by ForestMars** [comment]
WTG @mzparacha! Really appreciate the response time here!
