### ISSUE TITLE
🪣  Relocate shared types, utils, and schemas from libs/core to libs/shared

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#7501]
## Description
As part of the DevX bucket #7361, let's move all shared types, utils, and schemas to /libs/shared, used by core, models (server) and available to the client (schemas)

One issue with current implementation is that schemas are nested in "namespaces" using `import * as namespace from ...` style. We can flatten this structure and have just one level of files including:
- event.schemas or events under event producer name (aggregate folder)
- command.schemas or commands under command receiver name (aggregate folder)
- entities.schemas or under entity name (folder)
- index.ts exporting all

## Requirements
Creating bucket - since this will impact a large number of files 

- [x] #7692
- [x] #7693
- [x] #7694 

![Image](https://github.com/hicommonwealth/commonwealth/assets/41707007/0cd95e6c-2900-4b70-964f-c3026c99447c)
<img width="943" alt="Screenshot 2024-05-06 at 9 34 16 AM" src="https://github.com/hicommonwealth/commonwealth/assets/41707007/a3bb3194-21e6-4571-9a23-421774d538c0">

**Comment by burtonator** [comment]
This would be GREAT!!!  Really excited for this.  I think it would make things much easier!

**Comment by Rotorsoft** [comment]
All tasks completed!
