### ISSUE TITLE
BUG: Keplr wallet is not recognized on dashboard

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7545]
## Describe the bug

On current QA env, when user tries to sign in over dashboard page, Keplr wallet is not recognized and displayed on list.
### Initial conditions

**Environment:** 

QA/Local
**Branch/Release version:** 

Master/v1.3.2-x
**Browser:** 

All
**Wallet:** 

Keplr
## Reproduction steps

1. Install Keplr wallet 
2. Go to https://qa.commonwealth.im/
3. Click on sign in

## Actual behavior

Keplr wallet is not recognized and visible on list. Wallet will be only visible if we go on some cosmos community 

## Expected behavior

We should have same behavior on current version as we have on production. 
## Screenshots / Video

https://app.screencast.com/7nGeWFF9qfhGO

**Comment by jnaviask** [comment]
Caused by #6930 using `specificChains` for Keplr, which means it's not part of the `availableWallets()` list except on Cosmos communities.
