### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7547]
## Describe the bug

Page breaks with reading error

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

Master/v1.3.2-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://qa.commonwealth.im/element-finance/discussion/4146-introducing-the-call-for-delegates-members-of-the-governance-steering-council
2. Observe

## Actual behavior

```
Cannot read properties of undefined (reading 'indexOf')
```
## Expected behavior

Page should load
## Screenshots / Video

![Screen Shot 2024-04-24 at 16 14 08 PM](https://github.com/hicommonwealth/commonwealth/assets/8557292/c51f4fab-b499-4a0b-99f6-efdec35c466a)

**Comment by jnaviask** [comment]
Looks like `fromAddress` (aka `app.chain.accounts.get()`) is being passed `undefined` on the threads page. Should be an easy fix.

**Comment by Israellund** [comment]
"The route has a required join with profiles but the author address somehow doesn't have a profile" -Tim
Assigning this ticket to @timolegros

**Comment by timolegros** [comment]
Bumping to 3 points because this ticket has several potential implications as described on Slack: https://commonxyz.slack.com/archives/C06F9256BTQ/p1714093921292289

**Comment by jnaviask** [comment]
Superseded by #7590.
