### ISSUE TITLE
Navigation between different versions of threads

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7557]
## Description
Context: When a user is within a community viewing a thread, there is the edit annotation next to the authors name. This annotation  provides the time of the most recent edits to the post. If a user clicks this carrot, a list of all edits saved over time. If I click one of these versions within the dropdown, the post changes to the post saved at the time of that edit.

User story: As a user on Common, I am weighing a proposal in one of the communities I'm a member of. I can see that the proposal has been edited multiple times since it was first released to the community and when I am now looking at it. I click on the carrot icon and a dropdown menu opens where I can look at how many versions of the proposal there have been. If I click one, i can explore the version from that date and time.

Edgecase: 
- [ ] if a user closes the application while viewing a past version of the proposal, and they reopen it, it should reset to the most current version

 

<img width="474" alt="Screenshot 2024-04-25 at 9 28 41 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/d6c9073a-f0ff-4513-b806-3de589ebb4cd">

## Project Owner
@HIM92 

## Additional context
Figma: https://www.figma.com/file/EBVBVwpX3ws3i7e0YaxaxB/Post-Version-History?type=design&node-id=67-384&mode=design&t=bevRndFF2nX9DNpE-0

**Comment by jnaviask** [comment]
Need to spec out platform-side considerations (make separate ticket).
