### ISSUE TITLE
Edit history of comments

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7563]
## Description
Context: We are going to provide the edit history of comments as well as threads / proposals. 

User story: As a user on common, when I am reviewing a hotly contested thread and there are many comments, I can see that comments have been edited. When I click on the edited icon, it opens a dropdown where I can navigate the different versions of the comment. When I click on one, the comment updates to show the previous version of the comment. 

## Additional context
Designs: https://www.figma.com/file/EBVBVwpX3ws3i7e0YaxaxB/Post-Version-History?type=design&node-id=67-384&mode=design&t=tkLtgQiz0FXfJqjh-0

**Comment by jnaviask** [comment]
Blocked on designs. Should still plan platform-side work.

**Comment by dillchen** [comment]
should the needs design tag be removed? -- looks like Figma's been attached

**Comment by HIM92** [comment]
We need it for comment edits, the figma attached only shows thread post edit history

**Comment by kurtisassad** [comment]
Also a little curious here, the mobile dropdown shows the addresses/profiles associated with the edits. Do we:
1. Want it as specified in the figma
2. Have it appear in both mobile and desktop
3. Have it appear in neither mobile or desktop

Also good to note all 3 options require the same amount of work (not much).

**Comment by HIM92** [comment]
Great question - it should be specified in both mobile and desktop, option 2.
