### ISSUE TITLE
commonwealth.im/search creates infinite loading screen and receives multiple 400 errors

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#7569]
## Describe the bug

If a user inputs `commonwealth.im/search` into the url bar the they are shown an infinite loading screen and many requests are sent/many 400 errors are returned. 

## Reproduction steps

-go to commonwealth.im/search
-notice the infinite loading screen
-open dev tools and notice all the calls being made

## Actual behavior

-infinite loading and many db calls
## Expected behavior

-this should redirect to a 404 page or to dashboard

## Screenshots / Video

https://github.com/hicommonwealth/commonwealth/assets/69872984/98b4dec7-d734-4768-ad91-d41223f6897e

**Comment by jnaviask** [comment]
Related to #7549
