### ISSUE TITLE
Create `libs/protocol` to encapsulate protocol domain services API

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#7576]
## Description
Relocate protocol "helpers" currently under `/model/src/services.../contractHelpers` into its own library, encapsulating all protocol related services behind a clear API - to be used by our app and potentially other integrations (Farcaster). 

- References to web3 stuff and logging

**Comment by timolegros** [comment]
We can't do this because it creates a circular dependency between `libs/protocol` and `libs/protocol`. The protocol lib needs `CommunityAttributes` from the model lib. @Rotorsoft
