### ISSUE TITLE
Fix links on profile page

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#759]
On http://localhost:8080/edgeware/account/hwR8hAatmmdupBLXQSxLUPBa8GhRomLD9hf6iRtFeXs8fcY?base=edgeware with a fresh database (or http://commonwealth.im/edgeware/account/hwR8hAatmmdupBLXQSxLUPBa8GhRomLD9hf6iRtFeXs8fcY?base=edgeware in production):

- [ ] In "__ commented on thread", "thread" should be linked to the origin thread. See `raymond.profile-links` for code for this
- [ ] ProfileCommentGroup is incorrectly passed `discussion` as a type for on-chain proposals. This needs to be fixed for the link to work
- [ ] Links to link threads do not work (see the thread titled "Release Naples · hicommonwealth/edgeware-node · GitHub")

**Comment by gdjohnson** [comment]
Did these get fixed? I can't replicate the issues.

Re: the first bullet, I think it already is linked to the origin thread? See screenshot 
![image](https://user-images.githubusercontent.com/22281010/93912502-d8918000-fcd1-11ea-9ac8-ca29c6405f15.png)

Re: links to threads, the "Release Naples" link properly directs for me.

**Comment by raykyri** [comment]
I think this is fixed!
