### ISSUE TITLE
Implement version history support on comment/thread models

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#7591]
## Description

#7558 defines the product goals + UI items for version history support, but we need to support version history on the model as well. We should determine what changes to the model and routes (if any) will be needed to support version history on the client side. We should aim for a simple implementation which we can add complexity to as needed, if we see degraded database performance. Please discuss with @Rotorsoft (and the rest of platform team) and feel free to produce a formal specification of the changes involved.

**Comment by kurtisassad** [comment]
Bumping down to 1 because of misunderstanding. This ticket was only the backend changes not front end
