### ISSUE TITLE
get sitemaps running  in cron in production

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#7599]
Should just be a matter of putting this script in prod.

**Comment by timolegros** [comment]
This should have been part of the deployment instructions of #6173. Need to define:
- When to run
- How to run (e.g. `yarn generate-sitemap` or `node ./build/...`

Once we have both those set all we need to do is apply them to Heroku Scheduler.

**Comment by burtonator** [comment]
@jnaviask @timolegros 

We just have to run this command in production

```
cd packages/scripts
SITEMAP_ENV=production NODE_ENV=production node ./build/sitemaps/runner.js 
```

The reason the SITEMAP_ENV environment var is required is to prevent people from accidentally running it. This way they have to be explicit about it.

It should complete almost immediately. 

The interval should probably be 1 hour.  It only takes a few minutes to run but we could also do a 6 hour interval.  It does a full scan of the database each time but the scan indexes by primary key so it shouldn't have unnecessary load on the DB.

**Comment by timolegros** [comment]
The command is on Heroku now. @burtonator can you follow-up on this and make sure this stuff is working via the console at some point?
