### ISSUE TITLE
Show active community members & active threads in sidebar

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#760]
On the discussions page listing:

![image](https://user-images.githubusercontent.com/1273926/92785126-0387e580-f35c-11ea-9456-3195ddc6dff2.png)

Would also be nice to show the equivalent on topic listing pages, but for that specific topic.

Currently we also have a problem with the right sidebar not scrolling, but we can ignore that for now (eventually will convert the absolutely positioned infobox into one like Discord, that allows the content above to scroll)

**Comment by gdjohnson** [comment]
is that "6/mo" a tally of all forum content (reactions, comments, threads) created (or updated?) in the last month? I guess part of me worries that's invasive, but just a feeling

Do we also want a "Newest members" section? It's in them mockup but not mentioned elsewhere in the ticket

**Comment by gdjohnson** [comment]
Are those red and green dots... login status?
