### ISSUE TITLE
Update nav bar look/clean up tooltip bug

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#7607]
## Describe the bug

Currently the tooltips are off/don't line up with the icons on the nav bar. Instead of fixing this small issue, this ticket is to overhaul the look of the nav bar, which will also fix the tooltip bug. 
[Here is the Figma file](https://www.figma.com/file/Y0LepZ1s905rOfbJKUefNU/Navigation?type=design&node-id=244%3A4248&mode=design&t=mmbIoHtP9aoxtdwM-1) for the updated nav bar look. 

## Screenshots / Video

How the tooltips currently look 🤮: 
<img width="1110" alt="Screenshot 2024-04-29 at 1 48 46 PM" src="https://github.com/hicommonwealth/commonwealth/assets/69872984/f363de08-a533-4073-8c6c-e225f483489b">
<img width="994" alt="Screenshot 2024-04-29 at 1 48 55 PM" src="https://github.com/hicommonwealth/commonwealth/assets/69872984/b713acfe-34b3-4b8f-bce1-3ea9882ef1ee">

**Comment by dillchen** [comment]
looks fine now
