### ISSUE TITLE
Implement event error handling in consumer

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7638]
Once #7637 has been implemented, policy functions and projection functions will throw special errors that indicate how the consumer should proceed (e.g. retry). The consumer logic needs to detect those special errors and handle them appropriately.

## Acceptance Criteria
- The RabbitMQ consumer (or whatever invokes the policies and projections) should detect the special errors thrown by the util. The error should contain context such as description and max retries.

**Comment by timolegros** [comment]
@rbennettcw just noting that this work should probably be implemented in the `DefaultRetryStrategy` of the consumer.

**Comment by timolegros** [comment]
@rbennettcw we need to get this out before notifications (Knock) _and_ contests go out. For notifications right now I think the policy should be to drop messages that cause errors since notifications aren't required i.e. we shouldn't block the notifications queue. Happy to pair up on this and knock (no pun intended) it out if needed.

**Comment by rbennettcw** [comment]
@timolegros Okay, then I think you'd be the best person suited for this, since it's an infra detail and you've been building infra.

The utility is already merged in– it's nothing special, it just maps errors. Code examples are included in the original PR.

Assigning to you.

**Comment by timolegros** [comment]
After a conversation with @rbennettcw we agreed that the event error mapper utility is redundant given that we can implement default retries for any error types directly in the RetryStrategy component and then provide an error class that allows specific edge cases to define a custom retry strategy when thrown.
