### ISSUE TITLE
Undefined stream error when loading Edgeware proposals page

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#765]
When loading the proposals page I get this error (doesn't seem to have an effect on the page loading, but maybe there is now a data pipeline that is not being filled?)

![image](https://user-images.githubusercontent.com/1273926/92810909-d1ce4900-f372-11ea-8e4a-69a3b5e9a513.png)

**Comment by jnaviask** [comment]
Does this still happen on https://github.com/hicommonwealth/commonwealth/pull/758 ?

**Comment by raykyri** [comment]
Seems to be resolved!
