### ISSUE TITLE
Deploy stake to Ethereum Mainnet

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7658]
## Description
Goal: We want to deploy community stake to the Ethereum mainnet since it will unlock contests on a majority of our existing communities. 

User story: As a user on Common, I have a community launched on the ethereum mainnet. I can go to my integrations page as an admin for my community and enable community stake. 

User story: As a user on Common, I am creating a community on Common. I select my network as Ethereum (EVM), and then on the Basic Information page I can select "Ethereum (Mainnet)" and it is annotated with community stake. 

- [ ] deploy contract to ethereum mainnet
- [ ] signing for namespace places namespace on mainnet
- [ ] signing to deploy community smart contract on mainnet

UX

- [ ] users should see enable stake on integration page _if mainnet community_
- [ ] users should see mainnet as an option annotated with community stake on network selection on basic information step of community creation

## Project Owner
@HIM92

**Comment by jnaviask** [comment]
Not planned
