### ISSUE TITLE
🪣 Contests on Farcaster

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7659]
### Description

Communities such as Mochi want to take advantage of Farcaster as a distribution channel for contests (more discovery provided in the PRD). This feature will allow the admin of a community to create contests that will run completely within Farcaster. The Farcaster contest would utilize Common's contest infrastructure to figure out the winner of the contest and distribute the prize amount 

### Project Owner

@sachben91

### PRD

 [PRD](https://www.notion.so/buildcommon/Farcaster-Channel-Incentivization-64230fa0d0ab405db849ef09e223c230)  

### Tasks

- [x] #7663 
- [x] #9674 
- [x] #7662 
- [x] https://github.com/hicommonwealth/commonwealth/issues/9865
- [x] #8898 
- [x] #7661 
- [x] #8836
- [x] #8798 
- [x] #8897 
- [x] https://github.com/hicommonwealth/commonwealth/issues/8981

### Design Links

[Farcaster Frame Wireframes](https://www.figma.com/file/bw6QUNeBFd7F1c3uCE9xIC/Contest-Frames?type=design&node-id=0-1&mode=design&t=XR6weq7AzYdhSdBm-0)
More designs TBA

**Comment by ForestMars** [comment]
Ideally the Farcaster integration for contests will start cycle 4 sprint 1 (wk of 5/13.)

**Comment by ForestMars** [comment]
Slated for Cycle 4
