### ISSUE TITLE
Upvote Contest on Farcaster

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7662]
### Description

Users who want to participate in a contest should be able to use Farcaster Actions to upvote a contest on Common 

### Project Owner

@sachben91 

### Bucket ID

#7659 

### User Stories / Acceptance Criteria

- Users should be able to add "Upvote" from the [discover actions](https://warpcast.com/~/discover-actions) module on Farcaster 
- When a user utilizes "upvote" action on a cast that is a reply to a contest frame, the upvote should get counted as a vote for that cast. A cast here maps to a thread on Common. 

### Design Devlink

NA

### Design Screenshot

Example of what the actions module in Farcaster looks like:

<img width="657" alt="Screenshot 2024-05-01 at 6 13 16 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/b3a3481c-23d9-4853-a1b5-da20217f2a82">
<img width="689" alt="Screenshot 2024-05-01 at 6 12 49 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/1e6b4da2-3a0a-4283-a95c-d8f25cc00db7">

### Additional Context

- This may need a spike since we have not spiked on Farcaster Actions before

**Comment by rbennettcw** [comment]
Found a way to install the action directly from the frame rather than having the user go through the global registry. This is best UX for the user we can do. If we still want to add to global registry, we'll need to do it *after* officially launching FC contests to prod.
