### ISSUE TITLE
Move integration schemas from /libs/core to /libs/shared

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#7694]
Third step of #7501

**Comment by ForestMars** [comment]
TBDiscussed today on Slack (soft-blocked pending discussion.) Please update here with results of discussion when you close ticket.

**Comment by Rotorsoft** [comment]
Since these are backend-only schemas, we decided to keep them in `/libs/core/src/integration/` and close this ticket.
