### ISSUE TITLE
PWA notifications delivery for ios and Android(stub) 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7705]
### Description

Notifications created as part of #6617 should be delivered to the user on both ios and Android OS devices. 

### Bucket ID

#6617

### User Stories / Acceptance Criteria

- User receives notifications in the format that has been designed in Knock 
- On clicking the notification, the user is taken to the right place in the PWA, which is specified on the notification 
- User is able to receive notifications on both IoS and Android 

### Design Devlink

[Prototypes ](https://www.figma.com/file/WdlVQRpQKg4GMgCOzbQt34/Notifications?type=design&node-id=431%3A5812&mode=design&t=s06xXnXmBnTRKZRJ-1)

### Design Screenshot

<img width="308" alt="Screenshot 2024-05-06 at 11 37 48 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/d5c0bd6d-cdd9-451f-8afb-67643489275e">

**Comment by ForestMars** [comment]
Tee'd for Cycle 4.

**Comment by burtonator** [comment]
Starting to work on this now... but here are the initial notes:

https://docs.knock.app/integrations/push/firebase
https://firebase.google.com/docs/cloud-messaging/js/client

- we need to import the firebase/messaging lib on the client
- when the user grants permissions we can THEN get their key but I need to use our vapidKey with it.
- That token then needs to be sent to the backend and the knock SDK can be used to send the notifications

... I think this is the general overview and I'm still tracking this down.

Oh! Also, the Knock team will give us access to a 'combined channel group' so that we can use Apple and FCM as one object in their workflow.  We have to ask and I already requested it.

**Comment by burtonator** [comment]
Here's another resource... I'm unclear what's up with the vapid certificate now though:

https://developer.chrome.com/blog/web-push-interop-wins#introducing_vapid_for_server_identification

**Comment by burtonator** [comment]
Update. I have the vapid keys and I know the general flow. There are a number of moving parts here. I should have something working by next week.  I have all the credentials I need too including the keys needed in the frontend and backend.

One downside is that our service worker has to be in .js. It can't be in typescript.  I went down a rabbit hole and the ServiceWorker types are incorrect for TS plus it means DOM types will be available in TS. To do it with correct types means we need our own repository which isn't really what we want.

**Comment by burtonator** [comment]
The general flow looks like this:

1. [ ] on the frontend, the user clicks a button which calls Notification.requestPermission() which then brings up a dialog in the bowser in the top left (on the desktop).  If the user clicks "yes" then they are "granted" that permission.
2. On the frontend, once we are 'granted', we have to call the FCM function to get the user device ID.
3. We send that device ID to the server

**Comment by dillchen** [comment]
wanted to confirm that this is part of the flow that's on demo?

**Comment by ForestMars** [comment]
@burtonator Looks like you have multiple tickets that may have PR, but the PR is not linked on the issue. (Please update all kudasai)

**Comment by ForestMars** [comment]
Seems like this issue also is an orphan with no branch?

**Comment by burtonator** [comment]
This is related directly to this ticket:

https://github.com/hicommonwealth/commonwealth/issues/6622#issuecomment-2266243915

And we're first waiting for in-app notifications on the client to be shipped.
