### ISSUE TITLE
`deleted_at` is automatically mocked in seed utilities

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7722]
## Describe the bug
The tester `seed` utility automatically mocks the `deleted_at` property of any table that supports it. This is counterintuitive because it means you need to explicitly declare `deleted_at: null` in the seed. The default behaviour should be to _not_ mock `deleted_at` unless explicitly set.

**Comment by Rotorsoft** [comment]
Fixed by #7601
