### ISSUE TITLE
Add subscriptions for policies

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7728]
Contest policies need to be subscribed to their corresponding events.
- RabbitMQ config needs to be updated at `rascalConfig.ts` to include additional configuration for queues and bindings.
- The commonwealth consumer at `commonwealthConsumer.ts` needs to be updated to add the additional subscriptions.

## Acceptance Criteria
- Contest policies should be subscribed to their relevant events

**Comment by rbennettcw** [comment]
@timolegros Just to confirm– both policies *and projections* should be configured this way?

**Comment by timolegros** [comment]
> @timolegros Just to confirm– both policies _and projections_ should be configured this way?

I haven't written any projections but I think so yes - @Rotorsoft to confirm. No matter what the processing type is, messages will need to be consumed on the CommonwealthConsumer.

**Comment by Rotorsoft** [comment]
Right. I don't think we'll need more than one consumer process at the moment

**Comment by rbennettcw** [comment]
Going to tackle the projections in the next ticket (#7731) since they won't work until the mapper is implemented.
