### ISSUE TITLE
Create chain event mapper util for projection schemas

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7731]
Currently, chain events are stored in the outbox in the original EVM array format. But projection event handlers expect for the events to be formatted according to input Zod (struct) schema.

In order to subscribe contest projection handlers to chain events, the events must be converted from EVM to schema.

## Acceptance Criteria
- There should be a mapper util from `EvmEvent` to the appropriate data structure
- The `getEvents` function in `logProcessing.ts` should be updated to map events before they are persisted to the outbox
- The RMQ configs should be updated to wire up the projection events
- Ultimately, the relevant chain events should trigger projections to be created in the DB

**Comment by rbennettcw** [comment]
@timolegros Please check this and confirm that it's correct

**Comment by timolegros** [comment]
Yea looks right

**Comment by rbennettcw** [comment]
I've noticed some inconsistencies when trying to map contest chain events to the current zod event schemas. Working on resolving them:

| Chain Event | Zod Event Schema | Note
-- | -- | --
`NewContest` | `RecurringContestManagerDeployed` |
address contest, address namespace, uint256 interval, bool oneOff | namespace string, contest_address string, interval number | OK
`NewContest` | `OneOffContestManagerDeployed` |
address contest, address namespace, uint256 interval, bool oneOff | namespace string, contest_address string, length number | Chain event has `interval` but schema has `length`
`NewRecurringContestStarted` + `NewSingleContestStartedSig` | `ContestStarted` |
uint256 indexed contestId, uint256 startTime, uint256 endTime | contest_address string, contest_id number, start_time date, end_time date | Chain event missing `contest_address`
uint256 startTime, uint256 endTime | contest_address string, contest_id number, start_time date, end_time date | Chain event missing `contest_address` and `contest_id`
`ContentAdded` | `ContestContentAdded` |
uint256 indexed contentId, address indexed creator, string url |  contest_address string, contest_id number, content_id number, creator_address string, content_url string | Chain event missing `contest_address` and `contest_id`
`VoterVoted` | `ContestContentUpvoted` |
address indexed voter, uint256 indexed contentId, uint256 votingPower | contest_address string, contest_id number, content_id number, voter_address string, voting_power number | Chain event missing `contest_address`, `contest_id`
`PrizeShareUpdated` | ??? |  Missing Zod event schema
uint256 newPrizeShare | ??? | ^^^
??? | `ContestWinnersRecorded` | Missing chain event
??? | winners { creator_address, prize }[] | ^^^

I suppose the contract address can be derived from some chain event metadata

**Comment by rbennettcw** [comment]
Latest status:
- The `created_at` timestamp and `contest_address` can likely be found in the protocol code that listens for events, then passed to the util.
- When it comes to recording winners of a contest, there are some changes required:
    - The onchain `ContestStarted` event represents a new contest starting and/or a previous contest ending. It should emit 2 offchain events: `ContestStarted` (new contest) + `ContestEnded` (old contest). The old contest ID would be the current contest ID minus one. I'm working on this.
    - Winners will change throughout a contest, so a protocol helper util will be needed to query the score/winners. @ianrowan will work on this.
    - Some projections need to be updated accordingly – @Rotorsoft will work on this.
- The onchain `VoterVoted` event needs to include `contest_id` – which requires a change to the contract. @ianrowan  will work on this.
- The `PrizeShareUpdated` onchain event does not need to be captured in a projection.

@Rotorsoft @ianrowan – Let me know if this accurately summarizes what was discussed.

**Comment by Rotorsoft** [comment]
> The onchain ContestStarted event represents a new contest starting and/or a previous contest ending. It should emit 2 offchain events: ContestStarted (new contest) + ContestEnded (old contest). The old contest ID would be the current contest ID minus one. I'm working on this.

@rbennettcw We don't need to embed the contest_id computation logic in the mapping layer. The projection can start projecting a new recurring contest on `ContestStarted` and also check for previous "running" recurring instances of that contest/address, calling GetScore/Winners with the proper contest ids and closing them on success --- we can also think about a worker for closing running contests in case this operation fails consistently.

**Comment by rbennettcw** [comment]
@Rotorsoft Ok great. So there's no need to emit a `ContestEnded` event since the `ContestStarted` projection will detect and handle all that 👍
