### ISSUE TITLE
Delete legacy notifications

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7738]
## Description

- [x] https://github.com/hicommonwealth/commonwealth/issues/8902
- [x] https://github.com/hicommonwealth/commonwealth/issues/8903
- [x] https://github.com/hicommonwealth/commonwealth/issues/8904 (related: https://github.com/hicommonwealth/commonwealth/issues/8204)
- [x] https://github.com/hicommonwealth/commonwealth/issues/8955
- [x] https://github.com/hicommonwealth/commonwealth/issues/8998
- [x] https://github.com/hicommonwealth/commonwealth/issues/8997
- [x] #8852
- [x] https://github.com/hicommonwealth/commonwealth/issues/9058

**Comment by timolegros** [comment]
Blocked until #7910 is merged.

**Comment by ForestMars** [comment]
Setting back to `In Progress` since the PR is a draft.

**Comment by timolegros** [comment]
Bumping to 5 because this ticket originally did not account for moving Webhooks to Knock.
