### ISSUE TITLE
Thread and comment content parsing

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7739]
## Description
What does product expect to happen when the body of a thread or comment contains an image or a user mention? For example, in email templates where we show a thread/comment body, should we display the image or parse it out?

**Comment by timolegros** [comment]
@sachben91

**Comment by sachben91** [comment]
In email templates, **the images should be displayed as it is**. I'll test out the templates and see if it affects email performance in anyway, we can revisit after that. @timolegros
