### ISSUE TITLE
Profiles should link to threads that the user created

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#774]
See https://github.com/hicommonwealth/commonwealth/tree/raymond.profile-links

However, this is broken in many cases - comments on proposals seem to be mis-linked - why is this? Probably something to do with higher level profiles code that is passing the wrong data down?

**Comment by zakhap** [comment]
The case that seem to be broken for "user create new thread" is specifically when the thread is of `OffchainThreadKind.Link`.

TBD on why comments on proposals are mislinked.

**Comment by zakhap** [comment]
Seems as though we are initializing an OffchainComment's Proposal as an OffchainThread somewhere prior to passing down, still hunting. 🔭

**Comment by zakhap** [comment]
Found it 💪  line 29 in `profile/index.ts`
