### ISSUE TITLE
Handling Snapshot notifications when space is linked to multiple communities

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7740]
## Description
A Snapshot space can be linked to multiple different communities. If this happens, how should we want the Snapshot proposal created notification. Some options:
- Throttle notifications based on a key like `[community_id]-[proposal-id]`.
  - This means only the first notification for a snapshot proposal will be emitted i.e. if the user is in the ethereum and dydx community (both linked to the same Snapshot space), only a notification indicating there is a new proposal in one of the two communities would be emitted (race condition to which one emits first)
- Emit a generic notification that doesn't mention or link to a community - alternatively we could also list the communities in the notification but still not link to any specific community snapshot proposal
- Emit both as notifications since spaces linked to multiple communities is pretty rare

**Comment by timolegros** [comment]
@sachben91

**Comment by sachben91** [comment]
We should go with emitting both notifications since it seems like a rare situation @timolegros
