### ISSUE TITLE
User can not link a thread to another thread through Linked Discussions

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#7755]
## Describe the bug

-Search function in Linked Discussions/Search thread titles... returns no results.
-on prod box reads "No threads found"
-on local whole page reads "Failed to locate chain: undefined"

## Reproduction steps

-go to a community that you know is legit and that has a valid thread
-copy that thread title
-go to a community that you are an admin of
-either create a thread or find one that is already made that you can see Linked Discussions on
-try to search for that saved title
-notice one of the 2 messages above, depending on where you're testing this

## Actual behavior

-No titles are being found/can't read undefined
## Expected behavior

-users should be able to search for threads and successfully link that thread.
## Screenshots / Video

https://github.com/hicommonwealth/commonwealth/assets/69872984/29ce62fb-4669-4571-aab3-d4e1bf9f3b06

**Comment by ForestMars** [comment]
@mzparacha for visibility

**Comment by mzparacha** [comment]
> @mzparacha for visibility

I am also able to reproduce this, @Israellund plz lmk if I could help.
