### ISSUE TITLE
Test stack traces are not correct

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7758]
## Describe the bug
Stack traces reported at the end of a failing test suite don't map to the correct line in a Typescript test file.

**Comment by timolegros** [comment]
@raykyri Can you look into this - I'm stumped? Ever since our switch to `tsx` and ESM stack traces in tests have been incorrect. The dev experience for tests is really bad without line numbers.

**Comment by Rotorsoft** [comment]
This sounds very promising, looking forward to the demo 👍

**Comment by timolegros** [comment]
Was able to get ~90% of commonwealth tests over to Vitest.

`pgListener` tests are broken (they haven't been running) and the solution is non-obvious at the moment (may be related to #8083) so I am skipping the tests for now.

All that remains is to make the devnet tests use Vitest. I have saved this one for last because I anticipate some issues with how Vitest uses separate threads for different tests and how Anvil uses threads to spin up local chains.

**Comment by raykyri** [comment]
This is super cool. Thanks for looking into it @timolegros!! (Vite is also great, we've had a really good experience with it.)
