### ISSUE TITLE
Show associated addresses in community switcher

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#776]
It will feel more familiar if, while switching communities, the user can see what other addresses they have linked to each community:

![image](https://user-images.githubusercontent.com/1273926/93142390-c47acc80-f69a-11ea-9355-eb1d6dd5bc30.png)

Not a pixel perfect design, the task is just to add the column that shows associated address(es). Probably simpler if we don't change the background color in this PR either.

There are a couple other things to note here:

- "Your communities" should change to "You're a member of"
- We should set a width for the community names column, and make sure that if it overflows, it does so elegantly (e.g. with text-overflow: ellipse)
- getAllRolesInCommunity has a bug where it starts to return multiple copies of the same role after a few community switches/refreshes

**Comment by zakhap** [comment]
> * getAllRolesInCommunity has a bug where it starts to return multiple copies of the same role after a few community switches/refreshes

At first pass at trying to fix this, it seems as though it's an upstream issue of how `app.user.roles` is either refreshing/replenishing itself on chain/comm initialization or something weird in how the roles controller is accessing `app.user.roles` (or mutating its copy?).
