### ISSUE TITLE
Referrals: Refer directly to Common

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7771]
### Description

Users can refer friends directly to common by generating a link on their profile page. 

### Project Owner

@Him9289

### Bucket ID

#7766

### User Stories / Acceptance Criteria

Referrer:
As a user on Common, I can refer my friends to common the platform directly. I can click the profile dropdown on the top right of the screen where it says "Get referral link." From here I am taken to my profile page and the referral link modal is shown. I can copy this link and immediatelyby hitting the copy button, highlighting and copying the referral link from the text box, or by hitting any of the “share to” buttons. 

- These buttons share common directly to: Twitter, Telegram, Discord, Messages, Warpcast, or Email. (in this order)
- If the user hits the “x” then the modal closes. 
- When a user clicks the referral, they are taken to the community the referral link was generated in. 

Referral:
As a new user referred here by a friend, when I clicked their referral link I was given I am taken to Common and funneled into the user onboarding flow where I create my account. I am not auto-joined to any communities.

### Design Devlink

https://www.figma.com/file/Vr3dv2IjUFSonyxZdwzfVU/Referral-Program?type=design&node-id=234-4556&mode=design&t=Z5OYcCvlgm7bEOCM-0

### Design Screenshot

<img width="346" alt="Screenshot 2024-05-09 at 11 25 24 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/3e0e7ea5-4011-4833-90a6-b67027eeccd2">

<img width="152" alt="Screenshot 2024-05-09 at 11 25 52 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/49738a06-80be-45e0-b865-cbbd4963009e">

Common invite referral modal
<img width="310" alt="Screenshot 2024-05-09 at 11 27 01 AM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/df0018fb-cb8d-4ecd-8768-327e2095858d">

**Comment by masvelio** [comment]
@Rotorsoft we have flag `is_welcome_onboard_flow_complete` and based on this we update the state on the FE (user.isWelcomeOnboardFlowComplete). Whenever this flag is turned to true, you can emit an event

**Comment by sssssabinaaa** [comment]
> 1. Shouldn't we put this into the `edit profile` page instead of the public profile page? It it's kind of account/profile management thing so it fits better to `edit profile` IMO.
> 2. User dropdown menu has always `get referral link` option available? It should generate invitation to Common or Community? Related to question from [other ticket](https://github.com/hicommonwealth/commonwealth/issues/7770#issuecomment-2493957854). I think we should be more explicit about it.

Added some screens that hopefully address these Qs @masvelio https://www.figma.com/design/Vr3dv2IjUFSonyxZdwzfVU/Referral-Program?node-id=452-4802&t=kJdzkCYZteNB8uhv-1

**Comment by dillchen** [comment]
I believe @sssssabinaaa answers are sufficient here
