### ISSUE TITLE
We should use Object.keys(process.env) to define feature flags in webpack.base.config.mjs

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#7776]
### Description

Right now if we come up with a new feature flag we have to remember to map it into webpack.base.config.mjs so that the DefinePlugin can pick it up.

We can do this automatically by looking at Object.keys(process.env) and if the key has a FLAG_ prefix *and* if it is either true or false we automatically use the Define plugin.  Otherwise it will just be off.  

Might not work with webpack hot reloading though.

### Project Owner

@burtonator

### User Stories / Acceptance Criteria

Verify that it can work when we reload the app and turn the key on or off. 

Also when it is not set and then we turn it on.

**Comment by ForestMars** [comment]
TBD, Platform office hours, 5/21/24

**Comment by burtonator** [comment]
Tried this and for some reason webpack is choking on this... I don't think we should do it for now.
