### ISSUE TITLE
SPL Token Gating

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#7810]
#### Description

Add Solana SPL token balance fetching functionality to TokenBalanceCache and ensure solana tokens become an option in the groups Frontend using a the same UI as ERC20

**Comment by ianrowan** [comment]
Realizing there might be some expanded scope here if the goal of this ticket it to generally enable SPL gating(ie vs create platform/TBC routes) 

Main addition to scope here will be to enable creating communities for Solana in general as only Solana balance type communities/addresses will work with SPL tokens. Just wanted to check if that should be part of this ticket or split out? I can easily(I think) include the client side additions for creating and using Solana communities but it will expand the scope here quite a relative bit as this ticket will already include client side updates to the groups module. I would estimate bumping this to a 5 if we include all of this here.

CC @jnaviask @ForestMars

**Comment by dillchen** [comment]
@ianrowan imo worth splitting out as a separate ticket, but ideally knocking out as well, because yea, doesn't make sense to have one without the other.

wdyt Jake + Forest?

**Comment by ianrowan** [comment]
@dillchen I ended up knocking it all out in the current branch. Just a point or two worth of cleanup left. We can just include it in this ticket

**Comment by dillchen** [comment]
Noiceeee 💓

Sent via Superhuman iOS ***@***.***>
