### ISSUE TITLE
Mava implementation block mobile/pwa bottom navigation

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7828]
## Describe the bug

When user use PWA or mobile app, mava implementation blocks access to notifications button
### Initial conditions

**Environment:** 

QA/Master
**Branch/Release version:** 

All
**Browser:** 

PWA/Mobile (all)
**Wallet:** 

All

## Reproduction steps

1. On Mobile device visit: https://qa.commonwealth.im/
2. Install PWA app (or use existing one)

## Actual behavior

Mava CTA goes over notification button 

## Expected behavior

Mava should be positioned on different place
## Screenshots / Video

![IMG_AE223C84FD26-1](https://github.com/hicommonwealth/commonwealth/assets/8557292/c79c184a-a66c-4ecf-92c7-a8c38fdc88cf)

**Comment by ForestMars** [comment]
Israel is OOO, re-assigning to @burtonator (unless @mzparacha is already working on a fix?)

**Comment by mzparacha** [comment]
I am currently on https://github.com/hicommonwealth/commonwealth/issues/8109 -- needed for v1.4.0-8 hotfix

cc: @ForestMars
