### ISSUE TITLE
Skip e2e tests for now

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#7849]
## Describe the bug
Just going to skip the e2e tests for now so we can get back to green builds.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by ForestMars** [comment]
Can we surface what exactly we're looking to do here? Currently E2E tests are failing, but they are not blocking the build. So not sure offhand what we get by disabling them. 

Ofc the main thing needed is a rough estimation of LOE to get E2E tests working again. Perhaps we can touch base on this during tomorrow's Lunch & Learn.
