### ISSUE TITLE
One Off Contests without Community Stake enabled

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7855]
### Description

Communities that are interested in contests on Common may not be interested in enabling Community Stake. Communities that do not have stakes enabled should be able to enable one-off contests from within Admin capabilities. 

### Project Owner

@sachben91 

### User Stories / Acceptance Criteria

- When a community is created, users should have the ability to enable contests from Admin Capabilities
- If the Community does not have Community Stake enabled, they should be able to only create on-off contests 
- When the community enables contests, they should be able to register the namespace for the community so as to fund the contests onchain

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/800966b1-0c15-4014-b719-1df5f8bd6774)

- If Community Stake is not enabled then there should be no "use community stakes fees for contest?" or "make contest recurring" steps. All contests should be one-off contest by default 

<img width="891" alt="Screenshot 2024-05-16 at 1 09 59 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/a05f73b8-2781-4bdb-b478-5a3736b7211d">

- In the create community step, users should be able to select the token address that they would like to use to fund the contest

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/3b3c0473-18e1-4bf0-b69e-f8a191eb1129)

- Users should be able to adjust the duration of the community to be anywhere between one and seven days 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/9cdb9cef-e96c-40c7-921a-40c98e2a9d49)

### Design Devlink

[Designs ](https://www.figma.com/design/NNqlhNPHvn0O96TCBIi6WU/Contests?node-id=1095-10462&t=iNiO8UYdrX13I0rN-0)(with the aforementioned sections removed) 

### Additional Context

If we have traction for contests, then we can think about adding in a recurring contests step that distributes the direct funds across multiple weeks 

Other option that was considered here was to show the fields but make it not selectable and ask them to explain stakes. This was decided against for two reasons - Stake has few users and the middle of the create contest flow is not the appropriate place to upsell Stake since it takes the user out of the flow

**Comment by jnaviask** [comment]
Might make sense instead to disable the fields with an explanation of the "locked in" settings as a result of not having stake enabled.

**Comment by masvelio** [comment]
Design questions:
1. it has contest duration section with dropdown - this is not in the ticket scope (is this mistaken with farcaster design?)
2. why `make contest recurring?` section is visible - it is against the ticket description
3. we need `Use Community Stake fees for contest?` section. To be able to create a one-off contest we need to provide funding token address => this input is visible if `direct deposit` only option is selected

Technical issues:
1. current implementation of deploying one-off contest requires namespace parameter, which means, that enablement stake step has to be done. To unblock this, we need @ianrowan input to check the feasibility and change implementation of the contract helper

**Comment by sachben91** [comment]
@masvelio Jared is making the design changes now. Adding the token address field and removing the "make contests recurring" section.

**Comment by ianrowan** [comment]
To Marcin point above, while one-off contests do not require community stake to be enabled they do require a namespace to be deployed due to access control(ie admins of namespace) and excess fund sweeping functionalities.

That being said a community will have to at least symbolically deploy a namespace to use contests. This can just be a one-time transaction before deploying their first one-off contest but it needs to happen somewhere. We can still probably work around the chain the community is on(ie non-base community deploys base namespace).

That being said this will need to be considered in designs as well + the scope of the ticket above. We have existing code to deploy namespaces that can be repurposed 

CC @sachben91 @masvelio

**Comment by sachben91** [comment]
based on @ianrowan comments and talking to Jared, we have to go back to the drawing board on this one and explore if we can rework the flow. I have spoken to Jared about it. For the time being, lets push this back to backlog or archive this @ForestMars @jnaviask

**Comment by ianrowan** [comment]
There is currently nothing scoped on-chain to support contests that do not have stake. The reason being that contests use on-chain stake balances as voting power. So a namespace and stake is technically required.

Voting strategies in contests are hook based so in the future we have the availability to create erc20 voting strategies but this has neither been scoped or ticketed, though I suspect it will for Farcaster contests. That being said on the Common app itself/protocol as it stands this would be a fairly large lift. 

There would also be a fair amount of design(and then PENG) considerations given that our voting logic within the app currently upvotes based on number of stake. With the changes proposed in this tickets we would need to wire up the token balance cache to the client to use on-chain balances to reflect upvotes on the UI.
CC: @ForestMars @masvelio

**Comment by sachben91** [comment]
closing this since we have a different plan and designs for this now cc @jnaviask @ForestMars
