### ISSUE TITLE
Mixpanel Request: PWA tracking

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7859]
### Description

Ask: We need a mixpanel property that identifies whether a user performing any of the events currently tracked on Mixpanel is using either the PWA or the Web application. 

The distinction should be between these two:
- "Standalone (PWA)"
- "Non Standalone (non PWA)"

We need to be able to track individual actions, as well as the entire session that a user is on common for. We already track whether users are on a mobile device or desktop, but this is insufficient because it does not differentiate mobile browser from PWA. 

### Project Owner

HIM92

### User Stories / Acceptance Criteria

On Mixpanel

**Comment by burtonator** [comment]
```typescript
function isPWA() {
    return window.matchMedia('(display-mode: standalone)').matches || 
           (window.navigator.standalone === true) || 
           (navigator.serviceWorker && navigator.serviceWorker.controller);
}

if (isPWA()) {
    console.log('The app is running as a PWA.');
} else {
    console.log('The app is running as a normal web app.');
}

```

Apparently this uses two methods:

```typescript
if (window.matchMedia('(display-mode: standalone)').matches) {
    console.log('The app is running as a PWA.');
} else {
    console.log('The app is running as a normal web app.');
}
```

... and this one for iOS:

```typescript
if (window.navigator.standalone) {
    console.log('The app is running as a PWA.');
} else {
    console.log('The app is running as a normal web app.');
}
```
