### ISSUE TITLE
Preview post and coments on For you page and Community Discussion 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7865]
### Description

The changes outlined here are intended to improve the user experience of browsing through the For You page and the Dicussions within the community. 

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

**Thread display within For You page and Discussions:**
- For all threads on Common within Discussions and For You page, User profile image should be removed and the username should be displayed next to the name of the Community 
<img width="264" alt="Screenshot 2024-05-16 at 2 52 05 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/358f26e1-aaa1-4023-8871-5e2a17d2b959">
- Titles for actions  "user commented on thread" and "user created thread" should be removed
- Each thread should be truncated to the first four lines of the body of the thread
- When the user clicks "show more" on the truncated thread, they should be taken to thread 
<img width="543" alt="Screenshot 2024-05-16 at 2 56 56 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/a88e2e20-2942-46b0-93ae-d7918b17de7e">

**Comment display in Thread previews:** 
- New comments on a thread should be shown directly under a preview of the thread. This enables the user to have context on the comment 
- Clicking a comment should take the user to that comment within the thread
- Comments should have a maximum height of four lines 
<img width="473" alt="Screenshot 2024-05-16 at 2 59 58 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/64631a7a-3f6f-4b75-a212-a036b81da731">

- The comments display should be added to pages where we show thread preview
   - community overview page 
   - community discussion page
   - dashboard page "for you" feed 
   - dashboard page "global" feed 
   

### Design Devlink

[Figma dev mode link](https://www.figma.com/design/YtAQsnrZU5QlF3KIObZXI6/Feed-Revamp?node-id=186-9118&m=dev)

### Design Screenshot

added within user stories 

### Additional Context

design: @jessmart1213

**Comment by mzparacha** [comment]
> Comment display in For You page and Discussions:
> New comments on a thread should be shown directly under a preview of the thread. This enables the user to have context on the comment

How many comments should we be showing in the thread preview in for-you/discussion pages?

cc: @sachben91 / @jessmart1213

**Comment by mzparacha** [comment]
Update: the recent comments with threads change per PR description touches a lot of areas in the frontend. Plus I will be making some changes to address get recent comments per thread per presentation area (global, community overview, discussions page). Updating estimations accordingly.

**Comment by jnaviask** [comment]
We should ensure truncation is happening at the database level as well as on the client, so that we can reduce server load for forums with long posts (e.g. layerzero's bounty program). Tagging @rbennettcw @kurtisassad @Rotorsoft @timolegros re modifications for db queries to ensure we can achieve this goal.

**Comment by mzparacha** [comment]
Draft PR -> https://github.com/hicommonwealth/commonwealth/pull/7958

**Comment by jessmart1213** [comment]
Responding to point 4 or 

> Thread comments/actions stacking on mobile
> Jared to answer

The upvote buttons on mobile should look like[ this](https://www.figma.com/design/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?node-id=1667-114253&t=dLE4XTU20vShqMV7-1) -> And is only applicable to when stake is enabled.

<img width="467" alt="Screen Shot 2024-05-28 at 10 28 15 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/299a9501-a8cd-4c09-91cd-b12311852427">

**Comment by jessmart1213** [comment]
Some design to implementation inconsistencies:

- When a user clicks on the Comment button on the FYP thread, they should be taken to the thread page and autoscrolled to the first comment, not the Editor.

- The 4th line of text is what should be grayed out. There are instances where all the body copy is grayed out. The original idea was for there to be a capped line height of 96px or 100px (Eng would know best) that ensures the first 3 lines of text are the Orignal color and the 4th is a lighter.
- See current implementation -> 
<img width="623" alt="Screen Shot 2024-06-04 at 4 22 01 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/233de550-31b8-4978-95b3-46c55172a56d">


- The discussion pages should not have comments visible. In the designs the update was to have a "Show more" CTA that takes users to the thread page.

**Comment by mzparacha** [comment]
> When a user clicks on the Comment button on the FYP thread, they should be taken to the thread page and autoscrolled to the first comment, not the Editor.

<img width="626" alt="Screenshot 2024-06-05 at 6 20 06 PM" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/b4691a7b-a16d-47eb-914b-9c749067477e">

I believe we are referring to this. If yes, the behavior wasn't mentioned in the ticket so I used the existing behaviour which is "click on comment button takes user to thread with comment editor focused". If we are to change the behavior,  are we going to change it every where (threads list, details, FYP page)? 


> The 4th line of text is what should be grayed out. There are instances where all the body copy is grayed out. The original idea was for there to be a capped line height of 96px or 100px (Eng would know best) that ensures the first 3 lines of text are the Orignal color and the 4th is a lighter.

This is actually not that easy to implement, because the content rendered is from quill/markdown and frontend has to guess the formatting/quill doc structure to be able to correctly apply the gray shade. Can be done but this will be time taking.

> The discussion pages should not have comments visible. In the designs the update was to have a "Show more" CTA that takes users to the thread page.

Actually the ticket mentioned to add it to discussions page as well, so I did that. Not sure if we want to remove it now?

> Comment display in For You page and Discussions:
New comments on a thread should be shown directly under a preview of the thread. This enables the user to have context on the comment


cc: @jessmart1213

**Comment by jessmart1213** [comment]
> I believe we are referring to this. If yes, the behavior wasn't mentioned in the ticket so I used the existing behaviour which is "click on comment button takes user to thread with comment editor focused". If we are to change the behavior, are we going to change it every where (threads list, details, FYP page)?

Apologies for this behavior not being in the ticket. This behavior should have been reflected in the ticket as it a critical change. And yes, let's change it everywhere, unless Product, @sachben91, has reasons not to.

> This is actually not that easy to implement, because the content rendered is from quill/markdown and frontend has to guess the formatting/quill doc structure to be able to correctly apply the gray shade. Can be done but this will take time. Lmk if we want to implement.

So the grey, as I believe Jared mentioned before (in slack) is a gradient of white that sits above the text and is applied to the bottom of the thread. I mocked an example how the gradient could look with different text sizes and pulled out the gradient block itself in the [figma.](https://www.figma.com/design/YtAQsnrZU5QlF3KIObZXI6/Feed-Revamp?node-id=383-2868&t=6nQ3DIMMeUBubpl7-1) If this proves too difficult, then let's replace the gradient with 3 dots (ellipsis) at the end of the final text line.

Here is another example of how the gradient should behave. 
<img width="685" alt="Screen Shot 2024-06-05 at 10 26 10 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/a9f3c1b7-200d-4490-b95b-f389faf246f7">

> Actually the ticket mentioned to add it to discussions page as well, so I did that. Not sure if we want to remove it now?

Apologies here again for this being added to the ticket. This is a miscommunication as there are no designs for this. My stance is to remove it. cc @sachben91. 

See [designs](https://www.figma.com/design/YtAQsnrZU5QlF3KIObZXI6/Feed-Revamp?node-id=170-7882&t=6nQ3DIMMeUBubpl7-1) for the Discussion pages
<img width="838" alt="Screen Shot 2024-06-05 at 10 35 11 AM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/adbb990b-8c3a-4567-8975-9f195693aaf2">

**Comment by sachben91** [comment]
@mzparacha 

> The "comment" button on thread card redirects to thread details page and focuses the comment editor (for creating comment). Do we want to keep this behaviour or change it to "clicking on comment button redirects to thread details and scrolled to the first comment" 

We should change the behavior to clicking on comment button redirects to thread details and scrolled to first comment. This should apply everywhere. 

> ATM, we are showing recent comments on thread cards, displayed on the community discussions page /:communityId/discussions, as per ticket spec. Do we want to remove recent comments display from this community discussions page or keep it?

Yes we should remove recent comments on /communityID/discussions as per the design

**Comment by mzparacha** [comment]
Thanks for the feedback, created a ticket https://github.com/hicommonwealth/commonwealth/issues/8069
