### ISSUE TITLE
BUG: Page scroll does not work 

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7888]
## Describe the bug

When user tries to scroll on page, scroll working only when we hover over discussions.

### Initial conditions

**Environment:** 

QA/Master
**Branch/Release version:** 

Master/v1.4.0
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. GO to: https://qa.commonwealth.im/stargatetoken/discussions
2. Sign in with wallet 
3. Try to scroll on page

## Actual behavior

Scroll does not work if move is outside discussions

## Expected behavior

Scroll should work over threads and on page

## Screenshots / Video

https://app.screencast.com/tpcSCLOf5Hb2m

**Comment by jnaviask** [comment]
Main problem is that the scroll is not the entire page anymore but a box of notifications. Going to assign this to @mzparacha because it seems related to the user onboarding cards.
