### ISSUE TITLE
Get CW linked from PolkadotJS for Kulupu

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#789]
Not sure who is best person to talk to Jaco on this (or if we can directly get a PR up so this can happen)

**Comment by jnaviask** [comment]
Asked Jaco: he says a PR that adds CW links for Kulupu is welcome.

**Comment by dillchen** [comment]
Awesome, not an immediate thing to tackle, but if you have some downtime, would be much appreciated.

**Comment by jnaviask** [comment]
Looks like someone did it for us: https://github.com/polkadot-js/apps/pull/3697
