### ISSUE TITLE
Break down chain events into separate events

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#7895]
Currently, different chain events are consolidated as a single `ChainEventCreated` event. For consistency, we should break down the existing chain events into their own distinct event types + use zod event schemas for the outbox payload, similar to what has been done for Contests.

## Acceptance Criteria
- Use mappers for various chain events to map from EVM event to zod schema

**Comment by timolegros** [comment]
As discussed we are reverting this approach and using AbiType Zod schema parsing along with `ChainEventCreated`
