### ISSUE TITLE
Optimize bulkEntities request, add index to ChainEvent objects

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#790]
I might handle these, but cc'ing you to review if this makes sense:

- Calling server/routes/bulkEntities.ts currently returns 7 MB of data, is there any way to reduce that? Do we need to return all chain event types? Is it enough if we just delete all the edgeware-reward, kusama-reward, and polkadot-reward events?

- We should add an index on entity_id for ChainEvents (in the model + in a migration)
- We should add an index on chain for ChainEntities - since that is the default query implied by the route `server/routes/bulkEntities.ts`
- We should add an index on [chain, completed] for ChainEntities - since that is the query we actually make

**Comment by jnaviask** [comment]
> Calling server/routes/bulkEntities.ts currently returns 7 MB of data, is there any way to reduce that? Do we need to return all chain event types? Is it enough if we just delete all the edgeware-reward, kusama-reward, and polkadot-reward events?

Doing some quick math here using postgres. First recall this table, generated with `SELECT chain_event_type_id, COUNT(*) FROM "ChainEvents" GROUP BY chain_event_type_id ORDER BY count DESC;`:
```
          chain_event_type_id          | count  
---------------------------------------+--------
 kusama-reward                         | 113770
 polkadot-reward                       |  19054
 polkadot-bonded                       |   3583
 kusama-bonded                         |   2996
 edgeware-reward                       |   2605
 kusama-unbonded                       |   1053
 polkadot-unbonded                     |    583
 kusama-collective-voted               |    251
 kusama-election-new-term              |     69
 edgeware-collective-voted             |     55
 polkadot-collective-voted             |     33
 kusama-collective-executed            |     25
 kusama-collective-approved            |     23
....
```

So how much data are Kusama rewards alone using?

```
commonwealth=> SELECT pg_size_pretty(sum(pg_column_size("ChainEvents"))) FROM "ChainEvents" WHERE chain_event_type_id = 'kusama-reward';
 pg_size_pretty 
----------------
 19 MB
(1 row)
```

However the size of all Edgeware events is only 2.5 MB:

```
commonwealth=> SELECT pg_size_pretty(sum(pg_column_size("ChainEvents"))) FROM "ChainEvents" WHERE chain_event_type_id LIKE 'edgeware%';
 pg_size_pretty 
----------------
 2487 kB
(1 row)
```

And most of it is in the preimage data (i.e. it's the bytecode for runtime upgrades):

```
commonwealth=> SELECT pg_size_pretty(sum(pg_column_size("ChainEvents"))) FROM "ChainEvents" WHERE chain_event_type_id LIKE 'edgeware-preimage%';
 pg_size_pretty 
----------------
 2107 kB
(1 row)
```

Hopefully this can guide our intuition a bit in terms of what we should do with the db.

> We should add an index on entity_id for ChainEvents (in the model + in a migration)

> We should add an index on chain for ChainEntities - since that is the default query implied by the route server/routes/bulkEntities.ts

> We should add an index on [chain, completed] for ChainEntities - since that is the query we actually make

These all make perfect sense, I recommend them.

**Comment by raykyri** [comment]
Okay - this was super helpful to guide what we can do. I've filed #792 and #793 for actual steps to take, and also added the indices to the database!
