### ISSUE TITLE
BUG: Is not possible to upload image in thread 

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7920]
## Describe the bug

When user tries to upload image to thread over drag and drop or simple upload we have 403 error

### Initial conditions

**Environment:** 

QA/Local
**Branch/Release version:** 

Master/v1.4.0-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Sign in on app
2. Create some thread 
3. Try to upload image

## Actual behavior

403 error in console
## Expected behavior

User should be able to upload image

## Screenshots / Video

https://app.screencast.com/KP1mv8xSqpmwm

**Comment by timolegros** [comment]
@ilijabojanovic seems this is affecting all images including in community creation. No need to create a separate ticket I will handle all of them as part of this PR.
