### ISSUE TITLE
Optimize bulkEntities request

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#793]
Currenty we make a bulkEntities HTTP request whenever we initialize a chain community. This request can be quite slow (many seconds) and it makes our forum loading experience worse than comparables like Polkassembly.

- Is this request necessary?
- Can we reduce the amount of data passed over the request? I added an index to make the request faster but we are still sending about ~7MB of data down the wire for Edgeware
- One way might be to change the backend to only pass down certain types of chain events, e.g. exclude reward events. I'm not entirely sure if those are being passed down but they seem like the most likely reason we are passing so much data.

Would be nice to diagnose and come up with an approach to begin with on this.

**Comment by zakhap** [comment]
`/bulkEntities` is requested in the `refresh` method on the ChainEntities Controller, which is solely invoked by the `IChainAdapter` when initializing the server. 

> Is this request necessary?

Not to load the offchain discussions, it doesn't seem depended on unless you're on a governance-related page. We could wait to make the `/bulkEntities` call until a governance page is requested (also with the chain loading simultaneous, it would be a good time to mask the long request time). 

> One way might be to change the backend to only pass down certain types of chain events, e.g. exclude reward events. I'm not entirely sure if those are being passed down but they seem like the most likely reason we are passing so much data.

~Doing an analysis of this now.~ We could just request what's necessary to render each on-chain governance page. For example, without initializing the ChainEntities controller, the Treasury proposal page renders empty. However we don't need to render the referenda or proposals. This is the most piecemeal of the solutions, but I'm not sure if it's necessary to break up the request if it is less time than connecting to the chain.

**Comment by raykyri** [comment]
For our current governance pages, is there a way to reduce the size of the request by pulling down fewer entity types?

**Comment by jnaviask** [comment]
My sense is that the vast majority of the data coming down the wire in these requests comes from a small number of `setCode` requests, which save the entire runtime string in the `data` field of the corresponding preimage `ChainEvent`. We may want to do a special case for these somewhere in the code, perhaps even as far back as the storage eventHandler, to avoid this issue.

**Comment by zakhap** [comment]
> For our current governance pages, is there a way to reduce the size of the request by pulling down fewer entity types?

Yeah, I guess I was coming around to some sort of solution like that where we fetch piecemeal what we need to load each page. We could even fetch the data after loading the page+chain because the active proposals/referenda/treasury are coming from the chain and everything from the server is past/archival data. Just have a little spinner going for past-proposals section at the bottom, maybe.

**Comment by zakhap** [comment]
@jnaviask What do you mean by `setCode` requests?

**Comment by jnaviask** [comment]
Some proposals are for upgrading the chain, which uses the `setCode` call, with the chain's new runtime provided as an argument. This is often several MB in size.
