### ISSUE TITLE
On-boarding: Email sign up does not trigger new profile modal

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7941]
## Describe the bug

When we enable new onboarding modal, when new user create profile with email we are not triggering new modal on app.

### Initial conditions

Enable onboarding flag

**Environment:** 

All
**Branch/Release version:** 

Master
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Open app (local or qa env)
2. Sign in with email flow
3. Observe

## Actual behavior

User is signed but we are not showing modal to finish profile setup
## Expected behavior

Profile setup modal should be displayed
## Screenshots / Video

https://app.screencast.com/Q6KsZAGiQol95

**Comment by mzparacha** [comment]
Getting this strange error when trying to login via any SSO locally. 

![image](https://github.com/hicommonwealth/commonwealth/assets/51641047/2998f9db-eae6-4f79-9466-1d0d18e91a1a)
![image](https://github.com/hicommonwealth/commonwealth/assets/51641047/41371e83-5090-44fc-be37-9ee2b8c3e6b3)


It was working before, not sure whats happening now.

cc: @ilijabojanovic
