### ISSUE TITLE
On-boarding: Profile edit throws 400 error if user is signed over email flow

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7943]
## Describe the bug

When new user sign up with email flow, on profile edit page we have 400 error for api call

### Initial conditions

Enable onboarding flag

**Environment:** 

All
**Branch/Release version:** 

All
**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Open app
2. Sign up with email flow
3. Refresh page to get modal
4. Navigate to profile/edit page

## Actual behavior

400 and 401 errors in console

## Expected behavior

We should not have any errors
## Screenshots / Video

https://app.screencast.com/Wwmuu6Uf9I5JZ

**Comment by mzparacha** [comment]
The root cause for this bug is the same as the issue we are trying to fix in https://github.com/hicommonwealth/commonwealth/issues/6752. Basically for users with magic SSO's, the `/updateEmail` route doesn't let them to update email.

Adding blocked label

cc: @ilijabojanovic @jnaviask
