### ISSUE TITLE
On-boarding: Save on edit profile page throws error message

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7945]
## Describe the bug

When we have onboarding modal enabled, save action on profile edit page throws error
### Initial conditions

Enable onboarding flag
**Environment:** 

All
**Branch/Release version:** 

Master
**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Open app
2. Sign in (wallet or email)
3. Go to profile edit page
4. Click save

## Actual behavior

Error message
## Expected behavior

We should not have error massage 
## Screenshots / Video

https://app.screencast.com/cWoV8HBgj4mYe

**Comment by mzparacha** [comment]
Not able to reproduce @ilijabojanovic.

https://github.com/hicommonwealth/commonwealth/assets/51641047/a7ff9f7b-1b5d-4ece-8c77-d5aed2faab6b

If you are getting an error from the `updateProfile/v2` response, can you share that please (plz see screenshot for reference)

<img width="750" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/51641047/858ac0b9-ef16-4116-8bed-2665673e7eaa">
