### ISSUE TITLE
On-boarding: Training cards are not connected with actions

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7946]
## Describe the bug

When user finish onboarding process, two training cards are not connected with real actions. 
### Initial conditions

Enable onboarding flag
**Environment:** 

All
**Branch/Release version:** 

All
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Open app
2. Sing up with new wallet address or email
3. Finish onboarding flow
4. On dashboard click on Give an update card od Make a post
5. Observe

## Actual behavior

Since user is on global dashboard, we just reload page
## Expected behavior

We should improve UX
## Screenshots / Video

https://app.screencast.com/lW8MY3RJAaond

**Comment by mzparacha** [comment]
@ilijabojanovic  This doesn't seem to be a bug, as this is per specs defined in https://github.com/hicommonwealth/commonwealth/issues/7194. Please see [this](https://github.com/hicommonwealth/commonwealth/issues/7194#issuecomment-2057606132) and [this](https://github.com/hicommonwealth/commonwealth/issues/7194#issuecomment-2057718701)

I think we can close this.
