### ISSUE TITLE
Set contest duration 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7990]
### Description

Users should be able to set contest duration to be anywhere between one and seven days. This change should apply to all types of contests: contests with stake, contests without stake and contests on Farcaster 

### User Stories / Acceptance Criteria

- In the contest information page, user should be able to use the contest duration drop down to select the duration of the contest. The selections on the drop down should be between one and seven days - one day being the minimum duration for a contest and seven days being the maximum
### Design Devlink

[Figma ](https://www.figma.com/design/NNqlhNPHvn0O96TCBIi6WU/Contests?node-id=293-13514&m=dev)

### Design Screenshot

<img width="530" alt="Screenshot 2024-05-30 at 11 49 51 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/b41a7162-4e01-4a34-ac9c-2fc14fe618c3">

**Comment by jnaviask** [comment]
@sachben91 to add specific choices for dropdown + default option
