### ISSUE TITLE
Feature Flag Requests Blocked by CORS

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#7993]
## Describe the bug
Feature flag requests to `flag.commonwealth.im` are being blocked by CORS. This means all feature flags in production are currently defaulting to false.
![image](https://github.com/hicommonwealth/commonwealth/assets/62490329/472b207c-c924-45f4-9bf1-b86d525113b6)

### Initial conditions

**Environment:** production

**Comment by kurtisassad** [comment]
Seems to be an issue with cloudflare. The cloudflare firewall was preventing this request from going through. By disabling the check for this subdomain, we can bypass this error
