### ISSUE TITLE
Monitoring Top 10 High Impact DB Queries

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8000]
## Description
- [ ] Create a pnpm script that resets the `pg_stat_statements` table
- [ ] Run the script as part of Heroku release phase
- [ ] Setup daily message to a Slack channel with Top 10 High Impact Query data (i.e. Outliers).
  - This involves writing a script which runs a query against the `pg_stat_statements` table and posts the message to a Slack webhook.

**Comment by Rotorsoft** [comment]
just as ref:

```
#!/usr/bin/env bash

heroku pg:psql -a commonwealthapp --command "\
SELECT \
  calls, \
  rows, \
  ROUND(total_exec_time / 1000.0) AS total_secs, \
  ROUND(max_exec_time / 1000.0) AS max_secs, \
  ROUND((mean_exec_time / 1000.0)::numeric, 3) AS mean_secs, \
  ROUND((total_exec_time / calls / 1000.0)::numeric, 3) AS avg_secs, \
  SUBSTRING(REGEXP_REPLACE(query, E'[\t\n ]+', ' ', 'g') FROM 1 FOR 250) AS query \
FROM \
  pg_stat_statements \
WHERE \
  calls > 500 \
ORDER BY \
  mean_exec_time DESC \
LIMIT 10; \
" > ./top10mean.txt
```

**Comment by timolegros** [comment]
No longer necessary since https://github.com/hicommonwealth/commonwealth/issues/8004.
