### ISSUE TITLE
Datadog High Impact Queries View

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8004]
## Description
Research whether it would be possible to view high-impact queries on Datadog and set up monitors/alerts for them. If it is possible, the result of this ticket should include the required steps to set up the query metrics view in Datadog.

**Comment by timolegros** [comment]
There are two methods of monitoring Postgres with Datadog. 

1. The first is to monitor simple parameters such as open connections, number of rows inserted/deleted/etc. This mode of monitoring is enabled with the `DD_ENABLE_HEROKU_POSTGRES=true` env var. 
2. The second is to monitor queries and activities and can be enabled with `DD_ENABLE_DBM=true`

The [docs](https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#enabling-the-datadog-postgres-integration) are not clear on whether a separate `datadog` Postgres user is required to enable database monitoring. We should try setting `DD_ENABLE_DBM=true` and if query metrics/plans don't populate we should merge the `tim/database-monitoring` branch. The branch contains a migration which sets up the datadog schema + required functions as well as the Datadog configuration.

**Comment by timolegros** [comment]
`DD_ENABLED_DBM=true` was sufficient for enabling the Datadog Database Monitoring so no further action is required. I created a monitor which will alert us if 3 or more queries take longer than 2 seconds to execute in a 5-minute sliding window.

**Comment by ForestMars** [comment]
tagging Jake for visibility
