### ISSUE TITLE
Improve scroll behavior on threads list page

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#8039]
### Description
On `/:communityId/discussions` the scroll only works when the user is hovering over the threads list, it doesn't work if the user hovers over the padding outside the threads list.

Improve the list scroll behavior by updating the thread list component to use the whole `Body` (excluding sidebar and header) as the scroll parent.

**Comment by ForestMars** [comment]
@mzparacha How do you hover on mobile? 

By way of asking, is this a desktop only bug?

**Comment by mzparacha** [comment]
its also reproducible in mobile, but hard to reproduce there. It mostly effects users with >=1600px screen size.

cc: @ForestMars
