### ISSUE TITLE
When automatically subscribed to new threads, and a new thread is created, automatically subscribe to the new thread's comments/reactions

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#805]
When creating a new thread, any users that are subscribed to new threads in that community should also be subscribed to the created thread's comments and reactions.

This should be unit tested.

(This is not scalable. We will have to move these changes to a background process in queue later.)

**Comment by zakhap** [comment]
To clarify: 
If an address is subscribed to a thread, create both `New Comment` and `New Reaction` subscriptions for every comment on the previously subscribed to thread?

**Comment by zakhap** [comment]
Or is it a better behavior to emit a notification for a `New comment/reaction` on a comment who's root is the thread itself, while not creating new subscriptions for each comment.

**Comment by raykyri** [comment]
I changed the title to be more clear - this is just in reference to new threads being created and what happens then (i.e. everyone who is subscribed to new threads should be subscribed to those newly created threads' comments and reactions).
