### ISSUE TITLE
Setup Local K6 Load Testing Infrastructure

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8063]
## Description
In order to begin creating API and Browser based load tests we first need a local environment in which we can create and run load tests. Tasks include:
- [x] Create a Docker compose file with all the required components
- [ ] Link all existing infra to the Docker compose file (use test DB and server)
- [x] Create load test directories where appropriate (maybe `/test/load-tests/`?) @Rotorsoft

**Comment by Rotorsoft** [comment]
We should have a dedicated package for load testing (top level) or near the apps. Not sure if you are asking about load testing libraries though... doable but probably not necessary... at least right now.

**Comment by timolegros** [comment]
> We should have a dedicated package for load testing (top level) or near the apps. Not sure if you are asking about load testing libraries though... doable but probably not necessary... at least right now.

No I just meant where to place the tests but a top level package for load testing sounds good to me.

**Comment by timolegros** [comment]
Bumping to correctly represent the total amount of work done by @ilijabojanovic @kurtisassad and myself.
- @ilijabojanovic setup k6 docker files and created the example API + browser load tests
- @timolegros setup up the `load-testing` package (scripts, config, JS ->Typescript) and added xK6/sql (WIP)
- @kurtisassad setup and then tore down Webpack since it doesn't work as well as expected (rip)
