### ISSUE TITLE
GetAllContests query is not available for non signed-in users

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#8098]
## Describe the bug

GetAllContests is called to determine few UI things in the app, for example, if we should show `contests` menu item in left sidebar. Contests should be visible to not signed-in users, similarly to threads. Currently, it is available only for authenticated users.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

master
**Browser:** 

**Wallet:** 

## Reproduction steps

- open app without being signed-in
- open network tab / dev console

## Actual behavior

- Error in the console: Failed to load resource: the server responded with a status of 401 (Unauthorized)
```
[
    {
        "error": {
            "message": "Not authenticated",
            "code": -32001,
            "data": {
                "code": "UNAUTHORIZED",
                "httpStatus": 401,
                "stack": "TRPCError: Not authenticated\n    at authenticate (/Users/marcin/Desktop/Projects/commonwealth/libs/adapters/src/trpc/index.ts:67:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/Users/marcin/Desktop/Projects/commonwealth/libs/adapters/src/trpc/index.ts:211:32)\n    at async resolveMiddleware (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:421:30)\n    at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)\n    at async outputMiddleware (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:302:24)\n    at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)",
                "path": "contest.getAllContests"
            }
        }
    }
]
```

## Expected behavior

- getAllContests should return response 200 
 
## Reporter

@masvelio

**Comment by Rotorsoft** [comment]
@masvelio I think we need to discuss the need for multiple queries to support contests, here are my concerns:
- Authorization: This ticket describes the need for a public query to support unauthenticated users, and we'll probably need secure queries with more details
- Scalability: getAllContests returns all contests of a given community, including all actions... this can grow very quickly. We need to define more filters and limit the amount of contests and actions - For example, the main query can aggregate action totals (total votes, number of threads, etc) and include the score of the last N contests... we can define a second getContestActions query with pagination to list all actions of a given contest (we can potentially have dozens to hundreds of threads and thousands of actions)
- The existing views are not consistent, we have platform votes and contest actions that need to be joined in the resultset, to present a single version of the combined state in audit views and thread views

I suggest we make a list of all views where we are presenting contest data and define the query requirements for each view in terms of the three points above (auth, scalability, consistency)

**Comment by masvelio** [comment]
There are three cases where we need contests data:

1. All contests for given community:
    - list of contests for admin, signed-in user and not signed-in user

<img width="1677" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/4d8bd3cc-cb54-40e0-b1f4-e7bcd4515124">

2. Single contest for given community
    - for editing contest

<img width="1668" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/a48452f5-d313-464d-8bfa-14590337f2aa">

3. Information (boolean) if there is at least one contest launched within given community. So far we call `getAllContests` and check if `contests > 0` so this indeed can be optimised, especially that this query now is called even though we are not in the contests list view. There are couple places where we display conditional UI based on this flag eg:
    - `contests` section in topic filter
<img width="313" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/f1b591bc-b1c8-498a-a83a-96807f3cbfd9">

    - Contests menu item in left sidebar, under Discussions 
<img width="297" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/a15e37cc-b510-4e8b-aaf0-4eb82263ab8b">

    - Empty contest list view for admin
<img width="1676" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/e884b893-3da5-42cf-8739-9166c5684969">


and maybe two more that uses the same logic

**Comment by Rotorsoft** [comment]
Let's try to refine this list:

## getAllContests - `public`
- All contests for given community
- Returns all or top N contests? Should we add a limit filter for N contest sorted by date?
- Let's refine the schema, right now we are returning all actions but we don't show that... maybe totals?
- We can cover the second scenario by passing a single contest_id filter (available today)

## getCommunityContestInfo - `public`
- Returns contest information for given community
- Optimized to return totals, active, any other metadata?
- Is this pattern better than joining existing queries to contest projection?

We might also need:

## getCommunityContestActions - `auth`?
- Returns paginated contest actions (adding and voting on threads)
- Joined to platform votes? This is one of the main consistency points... we can actually vote/unvote multiple times by contest actions are idempotent

## getThreadContestInfo - `public`
- Returns details about thread to contests and voting totals, position in running contest, etc?
- Separate query or joined to existing queries? 
- Lets also review consistency here - platform votes/unvotes with different voting weights across time vs when the actual contest action was recorded on-chain

**Comment by masvelio** [comment]
After chat with @Rotorsoft we agreed that immediate action for this ticket will be: 
- getAllContests should be public query available for non-auth users
- actions will be removed from the contests as they are not used right now but only blow up the payload

As an optimisation in the future we can:
- create new query that will return boolean, to check if the community has at least one contest launched
- create additional queries that will serve us more data related to contest/actions so that we will split it up to few smaller for optimisation sake
