### ISSUE TITLE
Disable undo vote and editing on contest threads

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#8106]
Parent ticket: #7724 

The contest contract doesn't support undoing votes, so UI should not allow undoing votes either. If a user attempts to click upvote for a second time after they have already cast an upvote, they should be shown an error toast. 

The contest contract also does not support edits to the threads that are within the contest. Users should be made aware of this during the thread creation process 

## Design 
[Design](https://www.figma.com/design/NNqlhNPHvn0O96TCBIi6WU/Contests?node-id=1313-3642&t=V8R6Y2LIpCFlbwSI-0)

## Acceptance Criteria
- If the user clicks the upvote button once more after making their first vote, they be shown an error toast "upvotes on contest entries cannot be removed" 
<img width="557" alt="Screenshot 2024-06-13 at 10 30 09 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/aa8d5c3c-0533-40e8-b0ae-e8e3504b50ac">
- When the user is creating a new thread within a contest topic, they should be shown an opt-in option that tells the user that the thread being created will be entered into the contest and cannot be edited. 
<img width="751" alt="Screenshot 2024-06-13 at 10 29 24 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/f4ee74f6-a5b3-4968-9aa9-b826321c9ed4">

- The user has to select the "submit entry" opt-in to proceed with creating the thread 
- The "edit" option for the thread should be disabled for all threads within contests

**Comment by masvelio** [comment]
first estimation is 1 but need to get know more details and how this will affect the flow

**Comment by masvelio** [comment]
this one needs designs that are still being discussed
