### ISSUE TITLE
Contests banner within topics

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8110]
### Description

Topics that have contests active should have a banner at the top that gives the user information about the contests and provides affordance that the topic has a contest active 

### User Stories / Acceptance Criteria

- Topics that have an active contest should have a banner at the top that shows the details of the contest
- The information in the banner is derived from the contest information entered by the admin. The banner contains: title of the contest, topics that it is active in, prizes for the contest, contest image and CTAs view leaderboard and view previous winners (only if contest is recurring) 

### Design Devlink

[Figma Dev Link](https://www.figma.com/design/bKCi7foVaPWrIN0mJZ8KXi/Contests-(Copy)?node-id=541-12021&t=FdRcevOHnHbC3Ftd-0)
[Updated design for contest banner with no image in horizontal mode](https://www.figma.com/design/NNqlhNPHvn0O96TCBIi6WU/Contests?node-id=1840-13400&t=ozFcsB0K5JpObIVE-0)

### Design Screenshot

<img width="808" alt="Screenshot 2024-06-10 at 9 47 41 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/b59d68cb-b58d-49af-b219-a5c03a3bc53e">

**Comment by ForestMars** [comment]
Appreciate the "follow on" milestone here, although with 23 open stories on the main Contests milestone, and just the one here, we could roll this in. (Low key expectation more are coming, so then it makes sense to have a separate milestone for follows that is not launch blocking.) @sachben91

**Comment by ForestMars** [comment]
Also, I closed the [`contes` milestone](https://github.com/hicommonwealth/commonwealth/milestone/76) whatever was going on with that.

**Comment by ForestMars** [comment]
(Fast follow, not launch blocker)

**Comment by masvelio** [comment]
@sachben91 
1. what if the topic has more that 1 contest? We show multiple banners?
2. how topic list view looks like for mobile with contest banner?
3. there is no design when the contest does not have image uploaded

**Comment by sachben91** [comment]
@masvelio 
- it should show multiple banners, which gets tricky after a certain number of contests - I dont think that is a condition we should handle now, we will message to users that ideally there should only be 1-2 contests per topic and see how people use it. If there are more than two contests running regularly and there is demand for it then we can address it then. 
- Talking to Jared about the other two

**Comment by sachben91** [comment]
@masvelio 
- on mobile, as per our discussion, we would reuse the portrait mode view of the contests banner
- For the desktop view of the banner when no image is uploaded - I've linked to the design that Jared shared
