### ISSUE TITLE
Remove Community Stake banner within topics 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8111]
### Description

Remove the community stake banner since it has very little click throughs. The top part of threads will become overcrowded once the contests banner is added 

### User Stories / Acceptance Criteria

- Banner with the title "increase your vote weight by buying community stake" should be removed 
<img width="1098" alt="Screenshot 2024-06-10 at 9 53 43 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/f6846dcb-1063-4d19-99d6-3c1cf24f1964">

**Comment by ForestMars** [comment]
Too much banner real estate! (follows launch, not blocking)
