### ISSUE TITLE
Fix treasury bond calculation

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#812]
Currently multiplying instead of dividing to calculate Substrate treasury proposal bonds

**Comment by gdjohnson** [comment]
Spent about a half hour combing through the codebase for instances of "bond" and multiplication symbols (*, mult, muln), but I really have no idea what this is referencing unfortunately. The treasury page has a `computeBond` function, but that's never called in the codebase, and besides, it's multiplying by a percentage, which would seem to be the correct behavior (dividing by a percentage seems very odd).

**Comment by gdjohnson** [comment]
@raykyri Any word?
@dillchen You alerted us to this bug initially, or am I misremembering from meeting?

**Comment by dillchen** [comment]
I did originally report this. See image for example

![image](https://user-images.githubusercontent.com/5334557/94171610-75355880-fe5f-11ea-92d0-74169df0012b.png)

**Comment by raykyri** [comment]
If you start punching in numbers into the treasury bond field it should start glitching after a while. I don’t know that it’s related to the multiplication/division logic...I think it’s something else. Tried to trace it earlier for a few minutes but the bug seems more involved than that.

**Comment by gdjohnson** [comment]
Yeah, I'm experimenting with it now. The desired behavior is that the bond will display 5% of the amount of EDG that's inputted in the field?

**Comment by raykyri** [comment]
The bond minimum is 5% OR X where X should be fetched from the chain. The parameters should be somewhere in https://github.com/hicommonwealth/edgeware-node (or if not, that means we're inheriting the default value from Substrate).
