### ISSUE TITLE
Edit group needs padding at the top

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#8139]
## Describe the bug

-When a user edits a group they are shown an edit form with a header of "Edit group", which is cut off at the top by the breadcrumbs
-could possibly be refactored to use `CWPageLayout.tsx`

## Reproduction steps

-go to a community that has a group, or make one
-edit that group
-notice that 'Edit group' is cut off at the top by the breadcrumbs

## Actual behavior

-text is cut off
## Expected behavior

-text should have the same space around it as all other pages
## Screenshots / Video

<img width="1150" alt="Screenshot 2024-06-13 at 12 16 00 AM" src="https://github.com/hicommonwealth/commonwealth/assets/69872984/b7c5f314-84e5-49e0-b30d-c1ca2c685c1e">
Below is an example of the proper spacing
<img width="1137" alt="Screenshot 2024-06-13 at 12 15 43 AM" src="https://github.com/hicommonwealth/commonwealth/assets/69872984/42500bcb-01b5-4357-8e62-e94005b81c0d">

**Comment by SandipGyawali** [comment]
@Israellund  can i give it a try.

**Comment by Israellund** [comment]
@SandipGyawali Yeah, go for it!

**Comment by Israellund** [comment]
Closing this as it is no longer an issue on both local and production
Local:
![Screenshot 2024-10-17 at 10 34 21 AM](https://github.com/user-attachments/assets/2673ff1d-505d-45d9-b418-518a8ede4db8)
Production:
<img width="1429" alt="Screenshot 2024-10-17 at 10 35 36 AM" src="https://github.com/user-attachments/assets/c69afe09-f72b-4888-98c5-77cecc29788e">
