### ISSUE TITLE
Searching for discussion topic to link is broken

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#8168]
## Describe the bug

-When a user attempts to link a discussion to another thread, the search 

## Reproduction steps

-find a thread you're an author of or create a thread
-click 'Link discussion' button to link a previous thread to this one
-try to search for a thread in the modal
-confirm that the search function throws an undefined error

## Actual behavior

-search function for looking up threads is broken
## Expected behavior

-users should be able search for threads without getting an error
## Screenshots / Video

<img width="1431" alt="Screenshot 2024-06-18 at 9 25 43 AM" src="https://github.com/hicommonwealth/commonwealth/assets/69872984/04a9d070-a851-40ab-8f84-3ef0d4e8ab3d">

**Comment by nesldeployment** [comment]
I attempted to reproduce the issue by following the steps, but everything worked as expected in production. I wasn't able to replicate the problem, even after testing with multiple communities.

Steps to reproduce:

Create a thread
Click the 'Link Discussion' button to link a previous thread
Search for a thread in the modal
Actual behavior: Users can successfully search for threads without any errors.

**Comment by MuhammadKaleem171** [comment]
I attempted to reproduce the issue by following the steps, but everything worked as expected in production. I wasn't able to replicate the problem, even after testing with multiple communities.

Steps to reproduce:

Create a thread
Click the 'Link Discussion' button to link a previous thread
Search for a thread in the modal
Actual behavior: Users can successfully search for threads without any errors.

**Comment by Israellund** [comment]
@MuhammadKaleem171 was not able to replicate this bug and neither was I. Closing this ticket
