### ISSUE TITLE
Notifications Improvements v1 Test Plan

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8175]
# Test Plan

## In-App Notifications

**Thread Subscriptions**

1. Sign in as user A
2. Create a thread and subscribe to it
3. Sign in as user B
4. Comment on the same thread
- [x] User A should receive a notification

**Mention Subscriptions**

5. As user B create another comment that mentions user A
6. As user B create a thread that mentions user A
- [x] User A should receive a mention notification and a comment notification
- [x] User A should receive a mention notification

**Comment Subscriptions**

7. As user B create a thread.
8. As user A comment on the thread.
9. As user B reply to the comment.
- [x] User A should receive a reply notification

**Snapshot Notifications**

9. As user A join the dydx community
10. Subscribe to CommunityAlerts from the subscriptions settings page
11. Execute `pnpm emit-event snapshot`
- [x] User A should receive a snapshot notification

**Chain Event Notifications**

12. Execute the following query on the relevant database:
```
UPDATE "Communities"
SET namespace_address = '0xD7f82204b1F47BFdE583a8d360986b31F22D3DAe'
WHERE id = 'dydx';
```
13. Run `pnpm set-super-admin` (requires having `SUPER_ADMIN_EMAIL` or `SUPER_ADMIN_WALLET_ADDRESS` set in `.env`). If executing against a remote app just append `frick`, `frack` or `beta` to the end of the command.
14. Run `pnpm emit-event chain-event` a couple of times in quick succession. Wait 1 minute for the batch to complete in Knock (batch time is currently 1 minute in Knock development workspace but 1 day in Knock Frack workspace so temporarily modify it for testing if needed).
- [x] User A should receive a community stake mint notification

# Issues
- Snapshot subscription button still available on the `/snapshot` page when Knock notifications are enabled
  - https://github.com/hicommonwealth/commonwealth/issues/8536

**Comment by timolegros** [comment]
Main goal for tomorrow (July 18) is to fill out this ticket and test in-app notifications end to end + resolve any remaining issues.

**Comment by burtonator** [comment]
The preview doesn't exactly look good:

![CleanShot 2024-07-25 at 14 36 38@2x](https://github.com/user-attachments/assets/936178a1-0d23-4349-96c2-13578ed37184)

**Comment by timolegros** [comment]
> The preview doesn't exactly look good:
> 
> ![CleanShot 2024-07-25 at 14 36 38@2x](https://private-user-images.githubusercontent.com/45447/352296300-936178a1-0d23-4349-96c2-13578ed37184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NDM3NTMsIm5iZiI6MTcyMTk0MzQ1MywicGF0aCI6Ii80NTQ0Ny8zNTIyOTYzMDAtOTM2MTc4YTEtMGQyMy00MzQ5LTk2YzItMTM1NzhlZDM3MTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDIxMzczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNDA3MzI4MDFlMjU3ZDY5MjAzNTdlMWM4YTI3NmY2MmI2ZmFmOGVhNzgzZjMyM2Y4OWI1MDUzZDE2Y2M0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_LHI9y_8KJ1MftG1uPI3gLosihALhIW_hZYT86uDKc)

Did you make changes to how we truncate or decode bodies? This wasn't like this before.

**Comment by timolegros** [comment]
All notifications work for me - I think this is ready for QA if #8636 is merged.

**Comment by timolegros** [comment]
Making a note that I need to update the test plan to include subscriptions testing.
