### ISSUE TITLE
Author and/or admin should be able to removed linked discussions

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#8177]
## Describe the bug

-The author of a thread and/or an admin should be able to remove a linked discussion, similar to how the same type of user can remove a snapshot proposal from a thread
**NOTE: This ticket can't be done until #8168** 

## Actual behavior

-user can not remove a linked discussion that has been linked to a thread
## Expected behavior

-User should be able to remove a linked discussion to a thread if they are the author of the thread or they are an admin

**Comment by MuhammadKaleem171** [comment]
I attempted to reproduce the issue by following the steps, but everything worked as expected in production. I wasn't able to replicate the problem, even after testing with multiple communities.

**Comment by Israellund** [comment]
@MuhammadKaleem171 was not able to replicate this bug and neither can I. Closing this ticket
