### ISSUE TITLE
Fix inconsistent state on all-communities subscriptions

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#820]
This ticket covers two issues which may be related:

1) If subscriptions have varying notification settings, right now we should one of "On (immediate)", "On", or "Off" on the all communities page. We should show "--" if it's the case that different child communities have different settings.

2) a bug:
- Log in with an Edgeware address that does not yet have an account
- Connect the address to a community, e.g. to Edgeware
- Go to the notification configurations page
- Change the subscription setting for "When a thread is created" to On (immediate emails) - this fails
- Change the subscription setting for "When a thread is created" to Off - this fails

Seems like the cause is a 500 error caused by subscription_ids not being passed correctly to the backend.

**Comment by zakhap** [comment]
TODOs: 
- [ ] Indeterminate setting fix
- [x] New threads notification row bug.
