### ISSUE TITLE
Back out all uses of old notification system API calls.

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8204]
## Describe the bug

Right now if someone goes through onboarding they will use the *old* API calls for notifications.

Specifically:

```typescript
      await app.user.notifications.disableSubscriptions(subs);
      await app.user.notifications.enableSubscriptions(subs);
```

we should track all uses of these down and make sure they are behind the same feature toggles as the rest of the application so that none of these are actually used once we push this out into production.

@mzparacha @sachben91 

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by mzparacha** [comment]
Thanks @burtonator. 

Self-note: newer notifications will only be used once knock is enabled.
