### ISSUE TITLE
Evm Proposal Loading Broken

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8213]
## Describe the bug
See title.

### Initial conditions

**Environment:** production
**Branch/Release version:** master

### Reproduction
https://commonwealth.im/dydx/proposals

**Comment by ForestMars** [comment]
What happened? @timolegros

**Comment by timolegros** [comment]
I'm not sure but likely broke when we upgraded to Web3 v4 - there was a type assertion that likely hid the error. Fixing now.
