### ISSUE TITLE
Deprecate: Near login

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8218]
### Description

Context: According to @jnaviask the NEAR login flow is completely broken and creating issues in login paths for weekly releases. We have not had a NEAR login by a non-common employee in more than 14 months. At the request of engineering, we should deprecate the NEAR login flow for the time being and re-evaluate if it is a need considering those users can use Metamask if they want to access Common and their NEAR assets. 

### Project Owner

@HIM9289

### User Stories / Acceptance Criteria

ASK: deprecate the NEAR login flow.

**Comment by jnaviask** [comment]
Scope includes sputnik governance.
