### ISSUE TITLE
Remove thread privacy

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#822]
We should remove the thread privacy feature, it's unused and introduces a ton of edge cases in the codebase many of which we aren't handling.

- Remove from frontend controllers, backend routes, helpers like test/util/modelUtils.ts, and tests such as test/unit/api/threads.spec.ts.
- Remove from UI
- grep through codebase and identify any remaining places that might not be listed here

**Comment by zakhap** [comment]
Do we want a model change and migration as well? Like it never even existed?
