### ISSUE TITLE
robots.txt, build, assets and other static resources now seem broken. 

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8244]
## Describe the bug

I noticed while debugging the service worker for push notifications.

We're not serving 'build' as a static resource anymore.

We also have the same problem with /robots.txt, manifest.json, and 'assets'.

I have to fix this to get push notifications working but this is a general issue that we should resolve.

The server probably shouldn't even startup if these files/directories are missing.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by kurtisassad** [comment]
BTW, assets won't work because they are bundled at build time and the name of the file is changed. You must import them from inside the app using esm type imports, you can't reference them to get them from the server.
