### ISSUE TITLE
Optimizations for /bulkOffchain retrieval

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#825]
To discuss on Monday...

- Currently, we retrieve ALL thread history when loading a community.
- When loading the most recent threads for a community, we should just retrieve the first page of threads, using SQL to join the threads table to the comments table and sort by most recent activity. (/api/bulkOffchain is used for this now so that route will have to be modified)
- When scrolling to the bottom of the page on the discussions index, instead of just increasing `lookback`, we should fetch additional threads. We may want to customize the /bulkThreads endpoint to support this, by making it accept pagination parameters, etc.
- We should figure out if it's possible to get rid of the /bulkComments endpoint if comments can always be loaded alongside the thread they exist within.

**Comment by raykyri** [comment]
Another possible addition: instead of making queries sequentially, we can make them in parallel following the pattern `Promise.all([q1, q2, q3])`.

**Comment by gdjohnson** [comment]
NOTES FROM CALL
- fetch all comments from the last thirty days, do a uniqueness check, grab threads with only their root_ids
--> subquery?
- staying one step ahead (prefetch): let's hold off on this until a normal pagination system is working
- bulkThreads: pagination parameters vs date ranges
- get rid of bulkComments endpoint, include it in bulkThreads
