### ISSUE TITLE
Migrate Contract to TRPC

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#8274]
## Describe the bug

Requires migrating the following APIs:

- POST /etherscanAPI/fetchEtherscanContract
- POST /etherscanAPI/fetchEtherscanContractAbi
- POST /contract
- POST /contract/template
- DELETE /contract/template
- GET /contract/template
- POST /contract/community_template_and_metadata
- PUT /contract/community_template
- DELETE /contract/community_template

**Comment by timolegros** [comment]
#8314 removes CAT so these routes will be removed.
