### ISSUE TITLE
Migrate RolesController into react-query

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#8285]
- ask around what is the state of role in the app
- move RolesController info state/api/roles 
- cover all `app.roles` occurrences in the app
- make sure everything works

**Comment by masvelio** [comment]
per yesterday’s discussion, assigning to @jnaviask

**Comment by jnaviask** [comment]
Branching off @mzparacha's work in #8312 as it has a lot of overlap.

**Comment by jnaviask** [comment]
As discussed with @masvelio:

> next step as I would like to do it is:
> - Add roles as a member on Account or AddressInfo, replicating the roles information
> - Replace role functions to pull from Account/AddressInfo rather than as a separate object and ensure the population matches the derived Roles objects we currently create)
> - Migrate the required functions to a different controller/store, simplifying or eliminating them when possible (e.g. if we can determine a role simply by checking address.role, then we should, with a very simple global helper, as opposed to something convoluted), then eliminate the Roles controller
> 
> Can also in parallel investigate the removal of any lingering Roles code from the platform, but that would be a diff ticket

**Comment by jnaviask** [comment]
Update: after investigation, the main usage of roles is to distinguish admins/mods from members. Intuitively, admin/mod lists should live on the community instead of on the address object. I will investigate and implement community-owned roles vs address-owned roles moving forward.
