### ISSUE TITLE
Update "proposal" links on threads to point to block explorer as web link (if possible) rather than to an internal "proposal" id.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#8323]

**Comment by timolegros** [comment]
I don't think this is worth the work that it would entail. The official `dydx` governance platform does not link to any on-chain transaction. The official `aave` governance platform links to events on Etherscan but these are useless beyond serving as a testament that an event is on-chain e.g. https://etherscan.io/tx/0xaa9b52afa821bd948aae29a5379c4720e162f9728c6a81bcd488f877bd213615. All of the proposals we display are extremely old. All of these communities have migrated to newer contracts or even entirely different chains a long time ago.
