### ISSUE TITLE
BUG: Images are missing on CreateCommunity Page

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8339]
## Describe the bug

Images are missing

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

release/v1.5.0-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://qa.commonwealth.im/createCommunity
2. Observe

## Actual behavior

Images are missing for chains 

## Screenshots / Video

<img width="1843" alt="Screenshot 2024-07-02 at 18 51 28" src="https://github.com/hicommonwealth/commonwealth/assets/8557292/126af14b-f551-432b-bca9-2308edc079c8">

**Comment by Israellund** [comment]
From branch `release/v1.5.0-x` I am unable to replicate this bug. After looking at the code it does not seem to be incorrect; the <img> src is correct, the path to the assets is correct, and all of the correct svg files are present. I'm waiting to hear back from Kurtis as I think this is a bug having to do with the switch over from webpack to vite. 

![Image](https://github.com/hicommonwealth/commonwealth/assets/69872984/c9ac97e7-8140-42d8-94f5-d736af1743f0)
