### ISSUE TITLE
BUG: Cert errors for unleash

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8340]
## Describe the bug

We have SSL errors for unleash domain
### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Observe

## Screenshots / Video

<img width="1584" alt="Screenshot 2024-07-02 at 18 53 20" src="https://github.com/hicommonwealth/commonwealth/assets/8557292/a5d30c0a-b0fc-44ae-9233-58b1efb9e324">

**Comment by kurtisassad** [comment]
Yeah so I can no longer reproduce this bug. But basically it was also appearing on the production domain commonwealth.im. For whatever reason chrome was saying "not secure". What is strange is that our SSL cert hasn't changed over the past day, but for whatever reason chrome no longer complains about the cert date.

@ilijabojanovic can we close this ticket?
