### ISSUE TITLE
BUG: Api returning data only for authenticated users

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8344]
## Describe the bug

When we originally fixed this issue https://github.com/hicommonwealth/commonwealth/issues/8338 we introduced regression issue. Members page now returning members only for authenticated users
 
### Initial conditions

**Environment:** 

qa
**Branch/Release version:** 

master/release/v1.5.0-x

**Browser:** 

all
**Wallet:** 

all

## Reproduction steps

1. Go to https://qa.commonwealth.im/finalqa/members?tab=all-members
2. Observe console
## Actual behavior

If user is not authenticated api call will return 401 error
## Screenshots / Video

<img width="1485" alt="Screenshot 2024-07-03 at 15 02 58" src="https://github.com/hicommonwealth/commonwealth/assets/8557292/7dd2b193-8b6b-444c-abc4-7d5a525b79e2">

**Comment by kurtisassad** [comment]
strange, as it works fine locally. I even tested with the same feature flags
