### ISSUE TITLE
Switch Select-based pickers to chiclet-based pickers (on notification settings page, on new thread modal)

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#835]

**Comment by zakhap** [comment]
@raykyri I'm not sure I understand what the intended experience is of using the chiclets for the notification settings page and new thread modal. Is this correct?
For Notification Settings Page: a chiclet for each the email notification and normal notification
For the new thread modal: chiclets for selecting multiple tags for the thread
