### ISSUE TITLE
New snapshot page inaccessible on multiple snapshot communities

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#8360]
## Describe the bug

New snapshot button in action dropdown on header takes you to /multiple-snapshots page if multiple snapshots are present on a community with multiple snapshots, such as 1inch. The page to actually create a new snapshot cannot be accessed.

**Comment by Israellund** [comment]
Estimating this at 2 because this involves more than refactoring the redirect. Snapshot init needs to be refactored and updated, and `NewSnapshotProposalPage.tsx` needs refactoring to account for communities with multiple Snapshot spaces integrated.
