### ISSUE TITLE
BUG: Featured topic breaks page

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8373]
## Describe the bug

When user change topic to be feature and click save we have error page

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

Master/release/v1.5.0-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Sign in
3. Create new community or edit existing one
4. On admin area go to topics
5. Add new topic and click save
6. Edit new topic and check featured in sidebar 
7. Click save

## Actual behavior

We have error page

## Expected behavior

We should display saved notification

## Screenshots / Video

https://app.screencast.com/yvUckjjBmjWE3

**Comment by burtonator** [comment]
I can't duplicate this either :-/

**Comment by Israellund** [comment]
@jnaviask @ilijabojanovic Myself, Kurtis, Malik, and Kevin are unable to replicate this bug on either QA or local.

**Comment by jnaviask** [comment]
Cannot reproduce.
