### ISSUE TITLE
SEO: Setup out sitemaps on subdomain -> sitemap.commonwealth.im

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8386]
## Describe the bug

Our sitemaps are not being indexed because they're under the default AWS domain.

Our TLD (commonwealth.im) must match the domain for our sitemap.  

Once this is done, all the URLs and the URLs for the individual sitemaps need to be changed to map to the sitemap.commonwealth.im domain.  We should also add sitemap.common.xyz as @ForestMars mentioned we might need to change the domain name in the near future.

The bucket name is common-sitemap

Will probably need help from @kurtisassad and @timolegros 

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by timolegros** [comment]
Sitemap is also extremely out of date since the Cron job isn't working. S3 bucket still shows files from April. Still waiting on https://github.com/hicommonwealth/commonwealth/pull/8054 to be deployed so we can see what is wrong with it.

**Comment by burtonator** [comment]
This has to be changed with common-sitemap ...

**Comment by kurtisassad** [comment]
New s3 bucket named sitemap.commonwealth.im created
CNAME in cloudflare pointing sitemap -> sitemap.commonwelath.im added

**Comment by burtonator** [comment]
OK.  I changed the sitemap config to work for this but I don't think we can write to it with our credentials yet. I think those need to be changed.

Once those are changed I'll run this again.
