### ISSUE TITLE
User-set title on chain entities

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#840]
### Summary

It should become possible to set a title on Chain Entities, in which case the current title (e.g. for a treasury proposal “Proposed spend: 50,000 EDG to kour8…”) would change to a manually set title. If no title has been set, on the on-chain governance pages, “No title set” should be displayed in a lighter color instead.

The title column would be used for:
* Referenda
* Democracy Proposals
* Treasury Proposals

The title column would not be used for:
* Signaling Proposals
* Council Motions
* Non-Substrate proposals.

### Expected Behavior

- [ ] Add a carat menu (similar to discussion rows) to referenda, democracy proposals, and treasury proposals. If it is straightforward, this should be placed both on each row in the proposal listing page, and on the view_proposal page. It should be hidden for other unsupported proposal types.
- [ ] The carat menu should offer one option, Set title, which is only visible to Admins, Moderators, and the `proposer` of the proposal. That menu option should pop open a modal, with the title “Set title” and an input box for the title. If a title is submitted by a valid user, it should be saved to the database. The modal should handle errors correctly (e.g. by showing a notifyError popup with the error message). This will require adding a route for setting the title on a chain event.
- [ ] The title should be limited to 140 characters, and a notifyError should be shown if any longer title is provided.
- [ ] Add a title column on the Chain Entity db table.

If the treasury proposal’s title has not been set, it should be in a lighter color, and have the title
* “No title set”

Otherwise it should have whatever title has been set.

The individual columns for treasury proposals should change to accommodate the title:
* “Value” should become “Proposed Spend”
* “Recipient” should be added after “Value”
* “Bond” should remain as is
* “Author” should remain as is
* Width of the four columns should be proportionally 1:2:1:2

**Comment by gdjohnson** [comment]
Since I'm nearing the end of my tickets stack, I wanna revisit this—

There are several obstacles to this ticket:
1. Many chain entities at this point lack authors, leading to permissions issues for title setting.
2. In the long-run, we wanted to set up an association between ChainEntities and OffchainThreads, with the corresponding thread row holding information like title, body text, metadata, etc. 

> democracy referenda do not [have proposers] because they can be “injected” as a reuslt of council motions e.g. so they may not have a proposal involved. there will always be either a council motion or a democracy proposal before the referenda starts (which prepares the referenda). both of those have known proposers. so theoretically the name could be propagated. but the chain does not do this, we would have to build it

A couple questions: Is this still high priority? Does @jnaviask have the bandwidth and/or interest to work on the blocking issues? If not, would this be an appropriate project for me to work on? The offchain thread side of things I'm obviously very comfortable with, but my knowledge on the chain entity side of things is hazier.

**Comment by jnaviask** [comment]
I probably wont have the bandwidth to look at this in any detail until after Christmas, although I can handle questions etc. We're in the middle of a pretty serious push to prepare the next Edgeware node upgrade.

**Comment by raykyri** [comment]
I think we can implement a first version of this ticket without too many changes to the current system:

- We have community admins and mods, so the responsibility of setting titles can fall to them right now. (However we should still store who set the title when that action is taken.)
- We can keep data stored on ChainEntities right now, or create a new type of OffchainThread if it's easier to use that to just store the title. As long as we're thorough in making sure those threads don't appear anywhere unexpected, any solution should be okay here. If we store user-set titles on ChainEntities, in the future we'll need to do a migration to move the data, but that's pretty straightforward (see 20201215091459-populate-plaintext-columns-for-indexer.js for a data transfer migration).
- Since admins/mods are setting titles, no need to associate referenda with democracy proposals for now.

@gdjohnson I did add your name to some other small tickets. This would still be a really nice feature to get in though, since it will immediately make the governance page much friendlier (so really, this is still worth prioritizing).

**Comment by gdjohnson** [comment]
This seems pretty easy to implement in its down-scaled scope. Throwing an admin-settable `title` column on ChainEntities seems pretty straightforward; if it's missing, we default to the automatic titles. Gonna prioritize this ticket since the bug-stack has been cleared. (Unless I hear otherwise, open to shift priority.)

**Comment by raykyri** [comment]
I would add an `author` field to chain entities as well, and update the chain event handlers to write the proposer of treasury proposals, proposer of democracy proposals, and initiator of council motions to the author field as well. Referenda might require a little more handling so we could leave those out.

**Comment by gdjohnson** [comment]
So, talked through with Jake the approach for titles. My plan was to just ensure Proposals, on construction, were instantiated with a title stored in the db on ChainEntities. It seems like that path forward won’t work; instead, we’ll need a controller method that makes a fetch (/bulkEntities maybe the best endpoint) for the complete proposal row entry, including the title, and serve it up then. 

What remains to be worked out, and what I’m researching, is when & where this call ought to be made. The very latest point would be upon navigation to a Proposals or Referendum page—but obviously, if one is directly linked to a proposal, bypassing the index, the title needs to be available then as well. On community initiation is an option, or there could be a backend fetch made upon visiting a proposal page that will grab its title if it isn’t already stored.

It seems like authors can be fetched this way too, but I'm less sure about how to update chain event handlers to write to the author field in the first place.

**Comment by dillchen** [comment]
Related to #855

**Comment by dillchen** [comment]
Related to #843

**Comment by dillchen** [comment]
Related to #1026

**Comment by dillchen** [comment]
Related to CW-protocol task of turning a thread into some onchain action (I.e a Treasury Proposal or CW Project)
