### ISSUE TITLE
Blast Support

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8404]
## Description
In an effort to simplify the codebase, I created https://github.com/hicommonwealth/commonwealth/issues/8343 with the idea that since we no longer needed to support governance chain-events on chains like Fantom, we could hugely simplify chain event ingestion by using Alchemy Webhooks. The one problem is that Alchemy GraphQL webhooks do not support Blast. They only support the following chains: Ethereum, Polygon PoS, Arbitrum, Optimism, Base, and ZKsync. This means that if we want to transition to a much simpler Webhook-based chain event ingestion system we need to deprecate the Community Stake transaction UI (list of trade events) and stake transaction notifications for Blast communities. Communities on Blast would still be able to trade stake though we may want to disable future stake deployments since those communities will not be feature-full.

Note that this ticket does not mark the removal of Blast support but raises it as a possibility for review.

Here are some stats on existing Blast communities that have stake enabled:

| Community ID | Member Count | Stake Purchases | Thread Count |
| ------------------- | -------------------- | ----------------------- | ------------------ |
| hieroglyphs | 1 | 1 | 2 |
| blast-off | 1 | 0 |  0 |
| blast | 5 | 1 | 1 |
| jackomo-ninja-round-table | 1 | 0 | 1 |

Note that the `blast` community was created by `common` and not by an external user.

**Comment by ForestMars** [comment]
This is the way. 

Let's get the execution ticket up so we can get this in. (Or rather, out.) @timolegros
