### ISSUE TITLE
Move app.config.chains out of app object

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#8405]
- cover all app.config.chains occurrences in the code
- remove ChainStore
- make sure everything works

Also we should rename `chain` into `community`. We have separate [ticket](https://github.com/hicommonwealth/commonwealth/issues/5753) for this, but it will be up to the engineer if we should do it in one PR or as a separate

**Comment by jnaviask** [comment]
Related: #4976

**Comment by mzparacha** [comment]
Duplicated of #2617
