### ISSUE TITLE
Disable upvoting after contest ends

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8411]
### Description

Once a contest has ended (direct or recurring), users should not be able to upvote entries submitted to the contest. Upvoting entries for contests that have already ended causes confusion wrt to the leaderboard and number of upvotes garnered by winning posts. 

### User Stories / Acceptance Criteria

- Upvote button on posts that were entries to a contest should be disabled once the contest has ended
- When the user attempts to upvote, they should be shown an error toast with the copy "Contest has ended. Upvotes on this entry are now inactive"

**Comment by masvelio** [comment]
I just realised one case that makes things bit complicated. Basically we can create two contests and both of them will include lets say contest-1  topic. We can create then the thread within contest-1 topic so the thread would belong to both contests. There might be a situation where first contest ends but second still runs so disabling voting won’t be a solution in this situation.

Per our Slack convo and @sachben91 `we need a more elegant solution for this, you can close this ticket`
