### ISSUE TITLE
Show Contest rate limit UI

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#8467]
Blocked by: #8466 

Once Contests rate limiting is applied to the backend, some UX affordances need to be applied to the frontend.

## Acceptance Criteria
- Apply UX changes outlined in the comment: https://github.com/hicommonwealth/commonwealth/issues/8268#issuecomment-2226190287

**Comment by masvelio** [comment]
duplicated https://github.com/hicommonwealth/commonwealth/issues/8474 and https://github.com/hicommonwealth/commonwealth/issues/8473
