### ISSUE TITLE
Affordance for community admin on rate limit 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8474]
### Description

Based on the decision made in #8268, admins of communities should be given affordances on the number of posts that each user would be limited to within topics that have active contests 

### User Stories / Acceptance Criteria

- The Included topics section should have the following copy that communicates the rate limit
- The "general" and "all" topics should be disabled so that the admin does not accidentally rate limit the entire forum for the community 
<img width="725" alt="Screenshot 2024-07-15 at 5 03 02 PM" src="https://github.com/user-attachments/assets/7d751181-112a-4693-83f0-9316bfb1b98a">

### Design Devlink

[design](https://www.figma.com/design/NNqlhNPHvn0O96TCBIi6WU/Contests?node-id=389-13627&t=rh19Cun2HtOH1IZV-0)

**Comment by masvelio** [comment]
@sachben91 
1. Do we need `All` toggle at all if it will be always disabled?
2. Don't we want to add some description why General and All is disabled?

**Comment by sachben91** [comment]
@masvelio I used the wrong terminology here, not disabled, but toggled off - so the user has the option to toggle them on but it is not toggled on by default. Apologies, wrote it late last evening
