### ISSUE TITLE
Automate clearing cloudflare cache for commonwealth.im on production deploy

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#8487]
## Description

Currently we must manually clear the cloudflare cache on deploys to production. We should be able to automate this somehow. A buildpack like https://elements.heroku.com/buildpacks/fuelviews/cloudflare-cache-purge-buildpack may suffice. Please investigate solution + suggest a plan of action.

**Comment by kurtisassad** [comment]
Should be simple to set up. Basically we have the required config already (CF_EMAIL/CF_ZONE_ID CF_AUTH_KEY). All we will need to do is set those in the environment and then add the corresponding buildpack to heroku. I will test out first with a staging environment and write up my findings.
