### ISSUE TITLE
Get unsubscribe and apple notification subscription to work.

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8490]
## Describe the bug

We have to modify our knock subscriptions to support a different registration path.

I did an initial implementation of knock just for Android but I have to add support for Apple now.

This involves:

- sending the device type in the registration request (android | ios)... but we should support desktop browsers too so I guess we should send the channel type (fcm, apns)

- appending to the tokens, not overwriting the tokens

- implementing an unsubscribe with the device token (filter the device token, then unsubscribe from it)

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by ForestMars** [comment]
@burtonator This needs a linked PR kudasai. 

If you have any suggestions for automating that pls lmk, currently everyone is updating their own tickets on this.

**Comment by ForestMars** [comment]
3rd issue with no linked PR. Setting back to progress for that.
