### ISSUE TITLE
Social sign in broken for new users

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8495]
## Describe the bug
If you attempt to sign-in (instead of create account) with a social account (Magic) that you have never used before it goes through the full magic sign-in flow and then silently fails leaving you in a signed-out state with no account.

### Initial conditions

**Environment:** production
**Branch/Release version:** v1.5.1-2
**Browser:** chrome - Discord sign in

## Reproduction steps

1. Get or create a social account e.g. Discord that you have never used to sign in on common before
2. Attempt to create a new account

## Expected behavior

1. You should be signed in with an account after going through the full-flow

## Additional context

Seems related to https://github.com/hicommonwealth/commonwealth/pull/8469 specifically this line: https://github.com/hicommonwealth/commonwealth/blob/master/packages/commonwealth/client/scripts/controllers/app/login.ts#L535
 - Edit: #8469 is not the root cause rather user onboarding added in #7856 is the root cause

**Comment by mzparacha** [comment]
> Edit: https://github.com/hicommonwealth/commonwealth/pull/8469 is not the root cause rather user onboarding added in https://github.com/hicommonwealth/commonwealth/pull/7856 is the root cause

If we are referring to [this](https://github.com/hicommonwealth/commonwealth/blob/fa4cf092e80bfd0d603739991096440539f2ceeb/packages/commonwealth/client/scripts/controllers/app/login.ts#L527-L536) code block, then it's intentional. It was added to divert the user signup flow (to choose account/auth type) in case of new address authentication. This is probably not the cause of the bug you are facing (as it also works correctly with wallets) 

cc: @timolegros

**Comment by timolegros** [comment]
Ok so I finally narrowed down the bug so let me clarify. The bug only occurs if you use the `sign-in` option with a social account that is not associated with an existing user in the database. In other words, if a new user attempts to sign in rather than create a new account, they will be left in a signed-out state with no redirection to account creation. 

To test/replicate:
1. Execute `pnpm delete-user [user id or email] frack` to delete the user you want to test with.
2. Click the `sign in` option (_not_ `create account`)
3. Select the social sign-in method whose user email/id you just deleted.
4. When you complete the flow you will be left in a signed-out state with no account and no prompt to create an account.
