### ISSUE TITLE
Use RabbitMQ to handle creating notifications & sending immediate emails

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#856]

**Comment by dillchen** [comment]
still needed?

**Comment by raykyri** [comment]
imo we can keep this around in icebox

**Comment by gdjohnson** [comment]
Has this been implemented?

**Comment by jnaviask** [comment]
Any update on this?

**Comment by raykyri** [comment]
Big project. Would make creating threads much smoother.

**Comment by jnaviask** [comment]
Stale pending notifications redesign (likely going with queuing architecture though).
