### ISSUE TITLE
Need correct wording for Community Alerts section.  

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8566]
## Describe the bug

@timolegros was saying that this isn't the correct wording.  

![CleanShot 2024-07-23 at 08 32 23@2x](https://github.com/user-attachments/assets/fe2749c2-c819-4fbe-bea9-45920b812607)

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by sachben91** [comment]
Copy should be "get updates on Onchain activity and proposals in these communities" @burtonator
