### ISSUE TITLE
Get the in-app notifications branch merged and assess why custom changes were required in my branch.

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8569]
## Describe the bug

My branch grew rather large but I'm not sure why it needs changes to the profile account for 'member' when I didn't update that code.  Try to remove it again an try the build by merging into a new branch.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by ForestMars** [comment]
Looking forward to the answer!
