### ISSUE TITLE
BUG: CRUD operations for topics are broken

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8571]
## Describe the bug

When admin tries to update topic (change status, pin or change topic) we have console errors

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

release/v1.5.2-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Sign up
3. Create some topic
4. From actions menu try to execute any action
5. Observe

## Actual behavior

When we try to update topic we have 400 errors in console

## Expected behavior

All actions should work
## Screenshots / Video

https://app.screencast.com/pHDOSiVcNGJaE
## Additional context

All actions causing 400 error
```
{"status":400,"error":"Must provide body"}
```

**Comment by kurtisassad** [comment]
The fix for this is this commit:
https://github.com/hicommonwealth/commonwealth/pull/8480/commits/def53200ea23daf0658219d518f0e3c1ff093f1a

Right now it is on master, but if we need it for a hot fix then we should cherry pick it.
