### ISSUE TITLE
Join community bug

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#8572]
When attempting to join a community, an error is thrown in the console and the UI fails to update. After refreshing the page, the UI reflects that the community was joined.

Reproduced on: QA

![Image](https://github.com/user-attachments/assets/39444d2a-31bb-4235-8080-4222964c1f08)

## Acceptance Criteria
- Joining a community should update the UI without errors

**Comment by ForestMars** [comment]
Nice catch Ryan. I actually joined a Community earlier today and didn't notice this behavior. Imma slap a low pri on it tho, we def have bigger 🐠 to fry

**Comment by Rotorsoft** [comment]
@rbennettcw this has been fixed here - https://github.com/hicommonwealth/commonwealth/pull/8613

Can you confirm?

**Comment by mzparacha** [comment]
closing https://github.com/hicommonwealth/commonwealth/issues/8587 as that seems like a duplicate of this one.

**Comment by rbennettcw** [comment]
@Rotorsoft yep, it's fixed now
