### ISSUE TITLE
BUG: Upvote actions triggers error on server

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8584]
## Describe the bug

When user upvote thread on community which does not have contest enabled we have error on server

### Initial conditions

**Environment:** 

Production
**Branch/Release version:** 

master/v1.5.2
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to app
2. Sign in
3. Join community
4. Click upvote on some thread

## Actual behavior

Server errors

## Expected behavior

We should now have errors 

## Screenshots / Video

<img width="1510" alt="Screenshot 2024-07-24 at 17 09 29" src="https://github.com/user-attachments/assets/388650fb-f4bf-4462-870e-ab5a95887522">

**Comment by rbennettcw** [comment]
Will be resolved by #8369
