### ISSUE TITLE
Fix Substrate democracy voting

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#860]
- Setting a locktime in democracy voting is broken because the CustomSelect component in construct-ui isn’t calling onSelect; I have filed an issue
- An incorrect amount is being voted when democracy voting is called. After voting with this configuration:

![image](https://user-images.githubusercontent.com/1273926/94978579-da79f100-04d2-11eb-87c5-c2af8bb00fb1.png)

This is the result:

![image](https://user-images.githubusercontent.com/1273926/94978571-cc2bd500-04d2-11eb-8152-7c7d26af24e3.png)

**Comment by jnaviask** [comment]
While we're at it -- one other thing is that voting now requires a manual unlock call. We should consider an interface for this.
