### ISSUE TITLE
Optimize gasPrice estimation in Contest sequencer

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#8627]
#### Description

I've noted that the sequencer is overpaying for gas. This is just given that the web3.js/RPC gas estimation for L2 gas prices is less than ideal. 

This can be solved by using recent block gas estimation methods and extracting proper L2 estimates. This could reduce cost by 50% or more in theory.

**Comment by ForestMars** [comment]
This will need to be hotfixed onto `v1.5.3` as `v1.5.3-01` please. @ilijabojanovic 

Crucial to get this in so we are not overpaying on gas.
