### ISSUE TITLE
refine super-admin form

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#8630]
## Describe the bug

The super admin form needs to be updated to make it less confusing. 

-Make community_id optional - right now it's not clear that you can just omit it
-Only show a text field for eth_chain_id if the selected balance type is 'ethereum'
-Update balance type copy to something more descriptive like chain base/type.
-Update the route associated with the form to also set the alt_wallet_url in the DB to the same url

**Comment by ForestMars** [comment]
Adding this to `s5` (sprint 5) unless @Israellund thinks we could get to it before that.

**Comment by timolegros** [comment]
## Plan
Separate the existing form into 2 new forms

### Add Chain
**Fields**:
- Network Family (REQUIRED) aka 'balance_type'
  - One of: EVM, Cosmos, NEAR, or Other?
  - If anything other than EVM -> refuse
- RPC Endpoint (REQUIRED)
  - Add helper/doc that points to https://chainlist.org/ for EVM chains
- Chain Name (REQUIRED)
  - Should match the endpoint from Chainlist
- eth chain id (REQUIRED)
  - Should only be required when network family is EVM
  - Should match the endpoint + name

### Connect Chain To Community
**Fields**
- Community id input (REQUIRED)
- Chain select dropdown (REQUIRED)

### Additional Tasks
- [ ] Update the route associated with the form to also set the alt_wallet_url in the DB to the same url
- [ ] Update docs to point to Chainlist
