### ISSUE TITLE
Notifications UI Unclear on Mobile

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8644]
## Description
On the mobile UI, we have a 'Notifications' tab on the bottom menu which opens the Knock notifications modal. This is confusing to me since we also have a 'Notifications' option in the sidebar which leads to the 'Notification Settings' page. We should consider updating this copy to more accurately reflect what button/option does. If this does not seem like an issue to you @sachben91 or @burtonator feel free to close this ticket.
![Screenshot from 2024-07-29 16-05-46](https://github.com/user-attachments/assets/439da0d6-f850-4bfc-ba27-ad3370b15c9b)
![Screenshot from 2024-07-29 16-05-40](https://github.com/user-attachments/assets/2432689f-b9ea-443a-be79-9508632189b1)

**Comment by dillchen** [comment]
We should update the copy:

- **Notification Settings:** in side bar menu
- Bottom bar, as is

**Comment by ForestMars** [comment]
Definitely a step in the right direction. Not the ideal (having separate `Notifications` and `Notification Settings` tabs/bars) but will do for now.
