### ISSUE TITLE
BUG: Admin user can't edit user comment

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8652]
## Describe the bug

When community admin user tries to edit some community member comment we have 400 error

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

master/release/v1.5.3-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Sign up
3. As admin of yours community try to edit some member comment

## Actual behavior

400 Error in console

## Expected behavior

Admin user should be able to edit all members comments
## Reporter

https://app.screencast.com/840nVHSXfv3pv
## Additional context

```

{status: 400, error: "User is not author of comment"}
error
: 
"User is not author of comment"
status
: 
400
```

**Comment by timolegros** [comment]
Per https://commonxyz.slack.com/archives/C052DMYFKDL/p1722447481899199, this is not a bug. Rather there are 2 existing bugs:
1. Admins should not have an 'edit' option on threads and comments they are not the author of or are not a collaborator off
2. Admins should not be able to edit thread content (API currently allows this but blocks comment edits).
