### ISSUE TITLE
:bucket: Search Indexing Improvements in Postgres

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8657]
## Note
Will break this out into separate tickets.

### Required for S3 Migration
- https://github.com/hicommonwealth/commonwealth/issues/9157: Rather than have a Postgres `GENERATED` `_search` column based on the `plaintext` column, we should manually set the `_search` column to the `to_tsvector(body)` value on thread creation/update.
  - This eliminates the need to store full thread bodies in Postgres for search indexing i.e. thread bodies can be stored in S3.
  - https://www.postgresql.org/docs/current/textsearch-tables.html

### Optional (before or after migration)
- Remove stop-words (words that are so common that they are useless for searching) by creating a new dictionary. 
  - https://www.postgresql.org/docs/current/textsearch-dictionaries.html#TEXTSEARCH-DICTIONARIES
  - This reduces vector/index size
  - The following query returns the top 10 stop-words:
     ```
     SELECT * FROM ts_stat('SELECT _search FROM "Threads"')
     ORDER BY nentry DESC, ndoc DESC, word
     LIMIT 10;
     ```
- Create/use a crypto-specific dictionary to narrow search results as quickly as possibly leading to better search performance
- Move search queries to a read-only replica since a few seconds of stale search is tolerable and searching on a read replica would relieve the primary database of significant load.
  - This may require revisiting multi-database support in Sequelize. If Sequelize is ill-suited for the task it may be best to set up a lightweight repo pattern with PG.

## Additional context
- This ticket is a prerequisite for moving thread/comment bodies to external storage.
- The 8-point estimation includes the optional tasks.
- If we complete the optional tasks we may be able to significantly delay transitioning to Elasticsearch or some other search provider that would be more difficult/expensive to maintain.

**Comment by burtonator** [comment]
How much work is this ? Would it just be better to cut over to Elasticsearch?

**Comment by timolegros** [comment]
> How much work is this ? Would it just be better to cut over to Elasticsearch?

Part of the work is required anyway. The optional work depends. The read-replica switch would probably give us big performance gains and eliminate the need for Elasticsearch for at least the next 6 months. The other optional tasks, when completed, would also mean less maintenance and error prone surface area when compared to Elasticsearch. I have not interacted directly with Postgres FTS dictionaries before but I would wager it is much easier than setting up an entirely new service and all of the infrastructure/monitor/logging that that requires.

**Comment by timolegros** [comment]
Won't move ahead with optional tasks at this time. Dictionary/stop-word modification requires more control over Postgres than we have with Heroku. Using search from a read replica is still possible but seems unnecessary at this time given the current performance of search queries. We can revisit using a read replica in the future.
