### ISSUE TITLE
Issue with caching scroll position when page isn't scrolled down

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#867]
- Go to a community homepage
- Scroll down a few screens and click on a listing row
- Click "All Discussions"
- Click on a listing row that's already on the page, e.g. the first non-pinned thread
- Go back using the browser's back button
- The scroll position preserved is the first listing row that was clicked, not the one that was just clicked

**Comment by gdjohnson** [comment]
The desired behavior seems to already be in place, at least on my end! 

https://streamable.com/jvmckp

**Comment by gdjohnson** [comment]
@raykyri Wanna touch base on this + bulkOffchain today?
