### ISSUE TITLE
Incorrect Contest Thread Vote Weight in UI

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8681]
## Describe the bug
The UI shows that each user gets 1 free upvote in contest topics but in reality, on-chain contest upvotes are 1 to 1 with stake holdings. Consider the following scenario:
- Thread A has 1 upvote from a user with 100 stake -> 100 total upvote on-chain -> shows up in UI as 101 total upvote
- Thread B has 34 upvotes each with 2 stake -> 68 total upvote on-chain -> shows up in UI as 102 (since 3 * 34)

In this situation thread B looks like it wins in the UI but on-chain it lost by a wide margin.

The problem is complicated by the fact that users _do_ get 1 free vote weight in non-contest topics.

### Tasks
- Let users know that:
    -  **Contest topics:** vote weight = stake owned
    - **Non-contest topics:** vote weight = stake owned + 1
- Ensure that thread upvote counts in contest enabled topics correctly display on-chain vote counts and exclude the 1 free vote weight users get in non-contest topics.

## Additional context

https://commonxyz.slack.com/archives/C06TAS2SQUS/p1722374877797279

**Comment by sachben91** [comment]
It seems like default solution is that you need to own stake to vote or participate in contest (both stake funded and direct contests)  - which is not my favorite solution but seems like the only one that will work across the board here. The sidebar should only have stake available displayed and stake available should be equal to vote weight available. 

If we are implementing that then the min eth requirement and only two posts per contest requirement

Will also need follow up with vote weight/stake being topic specific i.e some topics have vote weight/stake enabled and the others work like a normal forum topic

**Comment by sachben91** [comment]
**Solution agreed on**: remove free upvotes for communities that have stake enabled. Upvotes available will be equal to number of stakes owned by the user. If the user does not have stakes in a stake enabled community then they will not be able to upvote. 

@ryanbennettvoid
