### ISSUE TITLE
🪣  Upvote Weight - Made Modular (Phase 2, Part 1)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#8696]
### Description

**Overview**: Introducing a modular Upvote-Weight strategy allows communities to customize how influence and engagement are measured within their ecosystem. This flexibility empowers communities to align their voting mechanisms with their unique values, goals, and member dynamics. By allowing a single upvote-weight strategy that can be tailored or replaced, communities can explore these dynamics between the onchain and offchain.

**Goals:**
- Our platform default should stay as 1 Address 1 Vote (1A1V), unless a VoteWeightStrategy contract is provided.
- If a VoteWeightStrategy contract is provided, UpvoteWeight should be calculated onchain.
    - Snapshot VoteWeightStrategy contracts must be acceptable.
    - VoteWeightStrategy contracts exist on EVM chains, so knowing which chain to query will be necessary. This chain will not necessarily be the community's default chain.

**MVP NonGoals:**
- Launching new VoteWeightStrategy contract types, simple or complex.

### Project Owner

Sachin Benny, Zak Hap @zakhap

### PRD

https://www.notion.so/buildcommon/Upvote-Weight-Made-Modular-Bucket-Ticket-42636fcda43d47f785a7f52a0c323abe

### Tasks

1. Generic: **As a community admin, I want to implement a modular upvote-weight strategy so that users who invest more in the community have a greater influence on "decisions" + increase Sybil Resistance**
    - MVP, use external
        1. MVP: As a community admin, if I enable Stake, I want to be able to select the basic StakeVoteWeightStrategy. (current user story)
        2. MVP: As a Community Admin, I should be able to use any existing Snapshot VoteWeightStrategy contract for my Community's UpvoteWeight.
        3. MVP: As an Admin changing the Community's VoteWeightStrategy, I do not cause an update to the previous upvote values + upvote ranking of content within my community; only new upvotes are calculated there-forward with the newly chosen strategy.
            - Clearing all the previous values and recalculating every upvote for the entire community is unnecessary until requested. Could be a premium feature, but too costly and unnecessary at this time.

### Benefits to Communities

- **Customization:** Communities can tailor voting mechanisms to align with their unique needs and values.
- **Fairness:** Ensures that voting power is distributed in a manner that reflects genuine investment and contributions.
- **Flexibility:** Allows for seamless transitions to new strategies as community dynamics evolve.
- **Security:** Mitigates the risk of Sybil attacks and vote manipulation, maintaining the integrity of the community's decision-making + content ranking.

**Comment by sachben91** [comment]
closing this since its not relevant anymore
