### ISSUE TITLE
🪣  Upvote Weight - (Phase 2, Part 2)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#8697]
### Description

Improvements to #8696! 

1. Extending Topics to have their own VoteWeight Strategies. Based on onchain communities like Aave having 4 or 5 onchain vote weight strategies for different types of proposals in their DAO + specifically requested by 1inch + LayerZero

2. Helping Admins Deploy new Voteweight Strategies

### Project Owner

Sachin Benny, Zak Hap @zakhap

### PRD

https://www.notion.so/buildcommon/Upvote-Weight-Made-Modular-Bucket-Ticket-42636fcda43d47f785a7f52a0c323abe

### Tasks

2. Improvements for contests:
    - Vote-weight by Topic! As an Admin, I want to select a specific VoteWeightStrategy for specific topics, as different Contests + Topics can have different weighting strategies. Update: 1 Contests Per Topic
    - Launching Strategies on Common:
        - As a Community Admin, I should be able to easily deploy a simple VoteWeightStrategy contract with just an ERC20 contract address + chain (1T1V). => Simple Strategy Factory contract (on different chains?) that simply takes a contract address as input.
        - As a Community Admin, I should be to create a more complex VoteWeightStrategy taking in multiple tokens of different types with different multipliers for each balance, returning the Sum. e.g. `[(Token1, ERC20, 1), (Token2, ERC1155, .75)]` returns `(Token1Balance x 1) + (Token2Balance x .75)`
            - Limitation: this is for assets on a single chain.

**Comment by sachben91** [comment]
closing this since its not relevant anymore
