### ISSUE TITLE
Allow Growth and Product to use Knock to send Direct Push Notifications

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#8699]
### Description

Knock allows users to use a UI to send notifications. We would like to set up a workflow that allows the growth team to send new notifications around new product launches.

### Project Owner

@dillchen

### User Stories / Acceptance Criteria

- Growth team should be able to login to Knock and use the configured workflow to send push notification to all users immediately

### Additional Context

- Requested by growth team [see slack convo](https://commonxyz.slack.com/archives/C050JCE0S94/p1721931331672629)

**Comment by ForestMars** [comment]
Thanks for putting ticket up @dillchen. This is something we've discussed, and while it would be incredible to get out this cycle, more realistically this will land beginning of cycle 6.

**Comment by timolegros** [comment]
We don't have a subscription under which this type of notification would fall under. We likely need to add a 'product updates' toggle to the push notification settings @burtonator.

Tasks for this ticket:
- Create generic Knock workflow for sending push notifications
- Create internal API route with tRPC to trigger the generic workflow for all users with mobile push notifications enabled
- Create a form in the admin panel which calls the new API route
  - Input field is JSON data used in the Knock workflow
- Add growth facing documentation on the entire flow
