### ISSUE TITLE
Token Launch CTA elements

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8704]
### Description

Context: This is an entirely new token launch functionality within common, so we would like to highlight it across the functionality of the website. 

There are two locations where the button exists:

1. the first is on the sidebar, and this is conditional to when the user is on an unscoped page. If the user is within a community, and is not an admin, and there is no token token connected to the community at that time, then there is no change to the user’s sidebar experience. 
2. The second location is across the page header on the top right side of the navigation page. No matter where the user is on the website this is visible.

By clicking this page, the user is taken into the launch token + community flow spelled out in these tickets. 

### Project Owner

@HIM92

### Bucket ID

#8703

### User Stories / Acceptance Criteria

User story: I am a user on Common, I am on the for you page or another unscoped page – and I see the launch token button either on the header or the sidebar. I click the button and I am taken to the create asset + community flow. 
 
User story: I am a user on Common, I am within a community page, and I see the launch token button on the header of the website. I click it and I am taken into a new token and new community flow. This community will be distinct from the community I was previously in. 

### Design Devlink

https://www.figma.com/design/1b9wbqv9YV2FlU2svFyf0I/IdeaCoin?node-id=815-39215&t=CPzA8TQX48r6yzZy-0

### Additional Context

<img width="269" alt="Screenshot 2024-08-01 at 12 18 27 PM" src="https://github.com/user-attachments/assets/14e399ae-3e6c-45ad-bdd0-e0963a32ce7a">
<img width="662" alt="Screenshot 2024-08-01 at 12 18 33 PM" src="https://github.com/user-attachments/assets/82c0de41-b458-4ebd-bf18-61b5b896b5d3">

**Comment by mzparacha** [comment]
Is the new sidebar part with the new addresses/profile sections part of this feature?

cc: @dillchen @jnaviask
