### ISSUE TITLE
Sign to launch token and create community. 

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8707]
### Description

Context: the user is at the final step of the launch token and creates community flow. The user has provided all necessary information to launch their token. They are presented with the opportunity to sign and launch their token. 

The user can sign to generate the erc20 token and community. When they click this they are prompted to sign with their wallet, and pay the generation and gas fees for the smart contract. 

If they can pay those fees, and they confirm the payment then they are taken to the community launch page, where their project is confirmed as launched. 

If they cannot pay those fees, we will rely on the metamask / wallet error that will block them by saying they cannot afford the fees based on their holdings. 

If they are only connected to communities with a magic wallet address that we have generated for them, then they will be prompted to use a funded wallet address. 

There is the option to cancel launching the asset, if the user cancels this they are prompted with the cancellation modal where they can confirm cancel or “go back”. If they cancel then they are returned to the there for you page. 

### Project Owner

@HIM92

### Bucket ID

#8703

### User Stories / Acceptance Criteria

I am a user on the third step of the launch asset and community flow. I have provided all the necessary information to launch my token. When I click “sign” my wallet is prompted for me to pay the fees and confirm the transaction. 

Edge cases:

- If i dont have the funds to confirm the transaction I cannot move forward with it. 
- If i don't have a wallet address that is funded (i.e. magic user) I am prompted to connect with a funded wallet address

(Cancel) 

I am a user on the third step of the launch asset and community flow. I decide to cancel my progress and not move forward. When I hit cancel, I am prompted WITH A POPUP MODAL to either cancel or “go back.” 

- If i hit cancel I go back to my for you page
- If i hit “go back” the modal disappears and I am still on the third page of the token launch + create community flow, where I can sign to launch my asset. 

### Design Devlink

https://www.figma.com/design/1b9wbqv9YV2FlU2svFyf0I/IdeaCoin?node-id=815-39215&t=CPzA8TQX48r6yzZy-0

### Design Screenshot

<img width="585" alt="Screenshot 2024-08-01 at 1 38 45 PM" src="https://github.com/user-attachments/assets/b0c36b44-521a-42c6-a587-14364be4a410">

**Comment by jnaviask** [comment]
Adding @ianrowan to assignees to consult on transaction flow.

**Comment by ianrowan** [comment]
Main question/comment here is: 

Aren't we going to need to collect input from the user for token/bonding curve settings? ie(recipient addresses, supply, etc)

Or do we plan to autofill this(from a tx perspective) with strict values that all common created tokens will follow?
