### ISSUE TITLE
🪣  Address Management revamp

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8708]
### Description

The goal of this project is to improve the user experience for adding and removing wallet addresses. At this time, there is no way to clearly leave a community for a user.The most pressing need here is better organization of the communities that a user is a part of, and an easier workflow to leave the communities that a member is part of. 

This improvement is within the user profile page, where the page displays linked addresses. The current functionality is not serving the user. Firstly, you cannot link a new address from this page. Addresses are not fully visible, and communities are not clearly organized, forcing the user to identify communities by matching the images associated with them. Moreover, the text is small and hard to read. With regard to some limitations, like Magic addresses being unable to disconnect from a community. 

Key functions for this work:

- Users can review all addresses connected to their account from their profile page
- Format should be Address, and then the communities they are part of
- List should expand to fit all addresses
- Users can disconnect from communities
- Users are made aware of what addresses cannot be removed
- Users are aware of what addresses are admins in a community
- Users are able to add an address directly to their account within the profile page
- Users can add an address from the sidebar
- If a user hits the sidebar settings widget they can see all of their addresses
- Users can disconnect their address from all communities it is connected to
- Unless the address is a magic wallet
- Unless the user is an admin, and the only admin of the community
- Unless the user is the last member of a given community. 

### Project Owner

@HIM92

### PRD

/// to be added by @him

### Tasks

- [x] #8709 
- [x] #8710 
- [x] #8711 

### Design Links

https://www.figma.com/design/N7vGFBW0XNQG5lgUIflObX/Address-Mgmt?node-id=223-12578&t=TO2EMFwyebMRpS74-0

**Comment by ForestMars** [comment]
@mzparacha Can you please estimate how long it would take to bang out the whole bucket? This is not critical path, but is a real quality-of-life issue for user experience
