### ISSUE TITLE
Migrate back to default merge strategy (away from squash merges)

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8716]
## Describe the bug

This is a tracking ticket so that we can keep track of the progress or raise any issues regarding disabling squash merges and migrating back to the default merge strategy.

### Motivation

The major motivation is to: 

- reduce PR merge latency
- allow the ability to stack branches with much less risk of merge conflicts so you can send in smaller PRs
- pave the way for CI/CD releases so that we can have every master commit automatically pushed.

### Background

For some background, the squash merge is a github specific feature that takes an entire PR, builds it up as a diff/patch, then commits it to master on behalf of the user.

The problem with squash merges is that it creates a much higher risk of merge conflicts.

### Solution

We're going to disable squash merges and migrate BACK to the default merge strategy in git.  

This includes the recursive, fast forward, and octopus merges that are the default way git does merges.

The octopus merge should never happen during a PR because it's an N-way merge across multiple branches. This should only happen if we had merge queues on which aren't currently enabled.

### New Branch Changes

I'd like to propose the following developer workflow changes:

- Please send in smaller branches. They should contain just 1-2 features and be very small.  A PR review should just take a few minutes so if you're placing more than say 1-2 minutes of PR review work on someone please try to split that up into a new branch.

- Make your commits to your feature branches small.  This will help make merge conflicts a thing of the past.

- You might consider merging master into your branch often but not required.

- DO NOT use rebase.  Git rebase is really only beneficial for rewriting the merge history to keep things linear but it can increase the risk of merge conflicts and problems when sharing branches with other developers.

- If you have to work on multiple PRs in one large PR, break the large PR into smaller PRs, send those in individually, then merge the smaller PRs into your bigger PR.  You no longer need to wait for them to be merge into master as you will no longer have merge conflicts. Note that you can decompose a larger PR into smaller PRs by cherrypicking it into a smaller PR, sending that in, and also reducing the chance of a merge conflict this way.

### Usage 

If you need to see PR merges you can see them just by doing a:

```git log --merges```

#### Conventional Commits

 @ilijabojanovic wants to require conventional commits.  
 
https://www.conventionalcommits.org/en/v1.0.0/

I agree with and support this 100%.  We can require this in the PR commit message.

It's basically just adding a string prefix in the commit message like "feat: " for a new feature.

We'll add a github action to verify these.

### Potential Problems

- We've been sending in large PRs which contain all the changes in one branch. To do a cherrypick release we might require more than one cherrypick.  However, that's ALREADY the case but I think the probability will increase that if we do a cherrypick release that we might need more than one PR merged.  I think this is a risk we should take though and will be mitigated once we move to a CI/CD release process.

**Comment by burtonator** [comment]
@ilijabojanovic @ForestMars @jnaviask @timolegros thoughts?

**Comment by timolegros** [comment]
> pave the way for CI/CD releases so that we can have every master commit automatically pushed.

One concern I have for frequent deployments is that Heroku deployments are not seamless. When we deploy Heroku dynos restart leading to 10-30 seconds of downtime. If we release on every master merge this could lead to several minutes of downtime per day which may be undesirable. Not sure what we can do about this other than maybe deploy to master on a set schedule during low-traffic hours e.g. every day at X time.

> The octopus merge should never happen during a PR because it's an N-way merge across multiple branches. This should only happen if we had merge queues on which aren't currently enabled.

I remember us having issues with merge queues but I don't specifically remember what those issues were. Would reverting back to the default merge strategy resolve those issues?

> Usage
> Conventional Commits

Maybe we should add couple utility commands in the Common Knowledge? Also, we should add links to relevant documentation of conventional commits standards in the docs.

LGTM

**Comment by burtonator** [comment]
@timolegros 

> I remember us having issues with merge queues but I don't specifically remember what those issues were. Would reverting back to the default merge strategy resolve those issues?

The main problem was when a merge failed in a merge queue there was no way to debug CI like there is with a regular CI.  I don't think we should migrate back until they fix that.

I don't think there's anything blocking us from switching back now.

**Comment by burtonator** [comment]
@timolegros and I discussed and one strategy would be to do a 9AM PST *schedule* deploy every day so all pushes from the previous day would be batched up and submitted to deploy. We'd just overwrite ever deploy so there's always one (the most recent).  Then if something breaks the whole team is awake to fix something.

I'd be happy with this as a workaround rather than pushing 5-10x per day.
