### ISSUE TITLE
Clean production env var

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8722]
## Description
Following the deployment of #8581, we need to remove all unnecessary env var from the production (and demo) environment as a single command to avoid multiple successive re-releases. Creating this ticket to document the command that needs to be reviewed and executed.

**Comment by timolegros** [comment]
Execute the following command:
```
heroku config:unset -a commonwealthapp AIRPLANE_DELETE_COMMUNITY_SECRET AIRPLANE_DELETE_COMMUNITY_MANUAL_SECRET AXIE_SHARED_SECRET COSMOS_GOV_V1 COVALENT_API_KEY CUSTOM_DOMAIN_UPDATE_SECRET DISABLE_REDIRECT_URL ETHERSCAN_JS_API_KEY FEATURE_FLAG_GROUP_CHECK_ENABLED FLAG_NEW_ADMIN_ONBOARDING FLAG_NEW_CREATE_COMMUNITY FLAG_PROPOSAL_TEMPLATES GATING_API_ENABLED GITHUB_CLIENT_ID HG_API_KEY GITHUB_CLIENT_SECRET INFURA_API_KEY MIXPANEL_DEV_TOKEN MIXPANEL_TOKEN NEW_ALCHEMY_PRIVATE_KEY NEW_ALCHEMY_PUBLIC_KEY NEXT_PUBLIC_RSA_PRIVATE_KEY NEXT_PUBLIC_RSA_PUBLIC_KEY NODE_URL NUM_WORKERS RECOVERY_DATABASE_URI REPEAT_TIME SLACK_FEEDBACK_WEBHOOK STATSD_URL TERRA_SETTEN_PHOENIX_API_KEY WEBSOCKET_ADMIN_PASSWORD WEBSOCKET_ADMIN_USERNAME
```
To ensure we can quickly rollback I will also create a command which immediately recreates all of the above env var with the exact same values. For obvious reasons, I am not posting this command here.

**Comment by jnaviask** [comment]
Approved to execute.
