### ISSUE TITLE
Add filter params and pagination to GET `/communities` endpoint

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#8756]
### Description

Context: https://github.com/hicommonwealth/commonwealth/issues/4976

### Engineering Requirements
Update  GET `/communities` endpoint

*API*: 
- Add an optional param (ex: `include_node_info: true/false`) to include `ChainNode` with the community response ex: `community:{ ChainNode: {...}, ...other info }`
- Add params for filtering communities based on `CommunityTags`, `community.base`, `stakeEnabled`

*Frontend*:
- Remove calls to `/communities` and `/nodes` from packages/commonwealth/client/scripts/state/index.ts
- In the communities list page, implement the new filter params and pagination, and remove the old communities filter logic.
---

Side Note: If we add `ChainNode` param, then the `/nodes` API can be deprecated. Also see https://github.com/hicommonwealth/commonwealth/issues/8755

**Comment by jnaviask** [comment]
Bumped to 3; need to rewrite query in SQL as sequelize makes it challenging to write the Tag intersection query requested.

**Comment by jnaviask** [comment]
Note that the new TRPC route will now ALWAYS return Stake and Tag data.

**Comment by jnaviask** [comment]
Further request:
> can we merge /bulkOffchain into get community by id and delete that route? It basically returns this data
```
{
    adminsAndMods: [ .. a list of addresses ],
    numVotingThreads: count of threads in 'voting' stage,
    numTotalThreads: count of total threads,
    communityBanner: string // banner text of the community
}
```

**Comment by jnaviask** [comment]
Bumped points to 5 due to many schema issues + changes required to data fetching.
