### ISSUE TITLE
Turn off squash merges

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8759]
## Describe the bug

Tracking bug to turn off squash merges.

I've talked to everyone on the team and we have agreement that this is the best way forward.  

I think now it's just that @jnaviask or @ForestMars need to turn off squash merges

@ilijabojanovic has agreed that we do not need force 'conventional commits' to turn this on.  

This is what the settings should look like:

https://github.com/hicommonwealth/commonwealth/settings

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/1b9d63b1-6094-4074-a059-cd52cba63a14">

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by ForestMars** [comment]
Aiming to have turned off by tomorrow 8/6.

**Comment by ForestMars** [comment]
As discussed, re-enabling merge commits. 

@ilijabojanovic please LMK if there are ANY issues or concerns that may come up as result of the change.
