### ISSUE TITLE
Implement pre-profile banner

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#876]
![image](https://user-images.githubusercontent.com/1273926/95181403-18e40a00-0778-11eb-97fe-89745030de68.png)

**Comment by gdjohnson** [comment]
Trying to envision which circumstances we're trying to hit here. Is it just for addresses that haven't joined the community, but that are on the chain? In that case I'd imagine this banner would:
* be disabled on offchain communities
* only appear for addresses that are *on* the active chain, but *not* yet registered with a Role in the on-chain community

**Comment by raykyri** [comment]
I think the case is that:

- addressees that haven't joined the community or chain (do not have a Role in app.activeId())
- but are in your *keychain* (not active chain, as if you're in a community, you will not have an active chain)

Basically, if you're on your the profile of one of the addresses in your keychain, and it does not have a Role in app.activeId(), this would show up.
