### ISSUE TITLE
Update Contest Worker Policy to be source agnostic

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#8774]
# Description
Since the Farcaster integration will reuse the existing Contest Worker Policy, then the CWP (ThreadCreated + ThreadUpdated handlers) need to be agnostic to the source of content and upvotes.

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @sachben91      | @rbennettcw        |

## Model
[Integration middle flow](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764587539511777&cot=14)

## Engineering Requirements
- Update Contest Worker Policy so that it doesn't make DB calls for Addresses/Threads/etc.
  - This requires baking the metadata into the payload when the event is emitted

## Sequence Diagram
![Image](https://github.com/user-attachments/assets/058c1f84-3172-4421-8fbf-9438cfdb5061)

**Comment by rbennettcw** [comment]
Bumping to 3 since it requires a bit more work to fit the integration policy convention for webhook commands.
