### ISSUE TITLE
Project farcaster actions

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#8776]
# Description
TBD- One of the nice to have we discussed in the Event Storming Session was the ability to project farcaster actions inside the platform

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @sachben91      | @rbennettcw        |

## Engineering Requirements
TBD
1. **Authorization**
   - Who's authorized to query this projection? Roles, Groups?
2. **Projection Schema** - Use [zod](http://zod.dev)
   - Projection schema (Mainly for the UI, but required for CQRS)
3. **Routing**
   - Define REST query paths (GET) - params, query string
   - Include validation schemas (params, query)
   - Include pagination requirements
4. **Query**
   - Define repository interface used to query this projection
   - New interface might be required
5. **Business Rules**
   - Define projection rules for the events we are projecting (reference to event schemas can be found in command features)
6. **Persistence**
   - Define repository interfaces used to persist projections, including data schemas
7. **Response**
   - Define success, including response schema (zod)
   - Define errors (HTTP codes)

**Comment by rbennettcw** [comment]
This doesn't apply anymore since we're mapping Farcaster events to existing CW events, and the existing policy/projections will be used.
