### ISSUE TITLE
Configure existing infrastructure to rate-limit API users

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#8783]
### Description

Make sure our existing infrastructure provides proper rate limiting functionality at the user level. Consider rate limiting users by: ip, address_id as credentials (might need to decode JWT)

- See master ticket

### Bucket ID

#8694

### User Stories / Acceptance Criteria

- Validate rate limits are working

**Comment by Rotorsoft** [comment]
@kurtisassad I think this is already covered in https://github.com/hicommonwealth/commonwealth/pull/9358

I was commenting with @timolegros about optimizing the middleware a little, maybe we can repurpose this ticket for it:

> I think we can optimize the apiKey auth middleware a bit by (redis) caching the apikey for a few mins to avoid to constantly loading/validating from the DB... and also use a single query to load address+user+apikey in a single select too. We can also invalidate the cache on ApiKey delete commands.

**Comment by timolegros** [comment]
> @kurtisassad I think this is already covered in #9358
> 
> I was commenting with @timolegros about optimizing the middleware a little, maybe we can repurpose this ticket for it:
> 
> > I think we can optimize the apiKey auth middleware a bit by (redis) caching the apikey for a few mins to avoid to constantly loading/validating from the DB... and also use a single query to load address+user+apikey in a single select too. We can also invalidate the cache on ApiKey delete commands.

There is already a ticket for the improvements: https://github.com/hicommonwealth/commonwealth/issues/9403

**Comment by Rotorsoft** [comment]
completed in https://github.com/hicommonwealth/commonwealth/pull/9358.
