### ISSUE TITLE
🐞 Gating Requirements: /node returning 2 keys with same name 

### ISSUE THREAD

**Issue by ForestMars** [hicommonwealth/commonwealth#8786]
## Describe the bug
the gating requirements dropdown is displaying 2 entries for Solana Mainnet. This does not appear to be a client side issue, rather the /nodes response is returning 2x nodes records/objects with same name keys = Solana (Mainnet Beta) but the other info/keys are different: 

{
    "id": 1404,
    "url": "https://solana-mainnet.g.alchemy.com/v2/1Qc8e4jZSqe_RB2O4Tb1Wd0TQCEeUoXH",
    "eth_chain_id": null,
    "cosmos_chain_id": null,
    "alt_wallet_url": "https://solana-mainnet.g.alchemy.com/v2/1Qc8e4jZSqe_RB2O4Tb1Wd0TQCEeUoXH",
    "balance_type": "solana",
    "name": "Solana (Mainnet Beta)",
    "description": null,
    "health": null,
    "ss58": null,
    "bech32": null,
    "cosmos_gov_version": null,
    "block_explorer": null,
    "slip44": null,
    "created_at": "2022-10-27T18:45:08.315Z",
    "updated_at": "2022-10-27T18:45:08.322Z"
},
{
    "id": 29,
    "url": "mainnet-beta",
    "eth_chain_id": null,
    "cosmos_chain_id": null,
    "alt_wallet_url": null,
    "balance_type": "solana",
    "name": "Solana (Mainnet beta)",
    "description": null,
    "health": null,
    "ss58": null,
    "bech32": null,
    "cosmos_gov_version": null,
    "block_explorer": null,
    "slip44": null,
    "created_at": "2022-10-27T18:45:08.315Z",
    "updated_at": "2022-10-27T18:45:08.322Z"
},

![image](https://github.com/user-attachments/assets/e26c6c9c-6bd7-4697-ad76-1ff775f9db9a)

Supposedly fixed in #8237, looks like we just need to remove the spurious entry. Currently there is no way from the app gui to determine which of the 2 to select.

**Comment by cowballzach** [comment]
p3 from growth. we are planning outreach in 2 weeks so before then is great.

**Comment by timolegros** [comment]
```
DO
$$
    DECLARE
        sol_mainnet      INT := 1404;
        sol_devnet       INT := 1;
        fake_sol_mainnet INT := 29;
        fake_sol_devnet  INT := 30;
    BEGIN
        UPDATE "Communities"
        SET chain_node_id = CASE
                                WHEN chain_node_id = fake_sol_mainnet THEN sol_mainnet
                                ELSE sol_devnet
            END
        WHERE chain_node_id IN (fake_sol_mainnet, fake_sol_devnet);

        UPDATE "Contracts"
        SET chain_node_id = CASE
                                WHEN chain_node_id = fake_sol_mainnet THEN sol_mainnet
                                ELSE sol_devnet
            END
        WHERE chain_node_id IN (fake_sol_mainnet, fake_sol_devnet);

        DELETE
        FROM "ChainNodes"
        WHERE id IN (fake_sol_devnet, fake_sol_mainnet);
    END
$$;
```

**Comment by jnaviask** [comment]
Good to run on production.

**Comment by timolegros** [comment]
Query executed successfully in production.
