### ISSUE TITLE
Implement Asset-Focused Cards on the Explore Page

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8803]
### Description

Context:
As part of the launchpad, we are introducing new asset-focused cards on the explore page. These cards will prominently feature memecoins, ERC-20 tokens, and other assets. Each card will display key information about the token, making it easier for users to quickly assess and interact with the available assets.

Displayed Information on Asset Cards:

- Token Name
- Token Symbol
- Price
- Percentage Change Over 24 Hours
- Current Market Cap
- Market Cap Progress Bar:
- The progress bar visually represents the current market cap.
- If the market cap reaches the “escape value,” the progress bar will turn green.

User Actions:

- Go to Community:
  - If a user clicks anywhere on the asset card (except the “Buy” button), they will be redirected to the asset’s community page.
- Buy Token: 
  - A “Buy” button will be available on each asset card. Clicking this button will open a purchase modal, allowing the user to buy the token directly from the explore page.
- Load More Assets:
  - Users can load additional asset cards by clicking the “See More” button after every five rows of asset cards.

Behavioral Consideration:

- Market Cap Progress Bar Update:
  - The market cap progress bar should dynamically update in real-time, allowing users to see the progress without needing to refresh the page. (Please confirm if this behavior is feasible.)

### User Stories / Acceptance Criteria

As a user on the explore page, I want to review all the tokens available on Common. I can see each asset laid out in a card format, displaying the token image, market cap, symbol, token name, and market cap progress bar. When I click on an asset card, I am taken to the asset’s community page.

### Design Devlink

https://www.figma.com/design/1b9wbqv9YV2FlU2svFyf0I/IdeaCoin?node-id=815-39215&t=Bs73ODTMr1Of6lIs-0

### Design Screenshot

<img width="378" alt="Screenshot 2024-08-08 at 1 14 12 PM" src="https://github.com/user-attachments/assets/8fcf1d99-ccec-4b9a-949a-3d76a5eeaf07">

### Additional Context

Design layout notes: Each row on the explore page will feature four asset cards.

**Comment by mzparacha** [comment]
1. "The market cap progress bar should dynamically update in real-time" not sure if this is possible, I will take a look when I start on this and then update.
2. In one of the designs, we allow users to buy tokens from token community pages, is this part of a different milestone?
<img width="873" alt="image" src="https://github.com/user-attachments/assets/c49f8d17-3c32-45dc-8976-983235fb1f4d">


cc: @dillchen / @sssssabinaaa

**Comment by dillchen** [comment]
1. It's fine if it's not in real-time - as long as it updates on user reloads (or similar to what we see on Stake Price Updates)
2. Within the community, it is a separate ticket

**Comment by mzparacha** [comment]
Thanks, will take a look on #9489.
