### ISSUE TITLE
Enable Token Purchase from Explore Page

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8804]
### Description

Context:
We need to allow users to purchase tokens directly from the explore page, similar to the functionality described in [Ticket #6870](https://github.com/hicommonwealth/commonwealth/issues/6870). When a user clicks the “Buy” button on an asset card, a transaction modal should appear, enabling them to complete the purchase without navigating away from the explore page.

Task:
Implement a “Buy” button on each asset card on the explore page. When clicked, the following should occur:

Transaction Modal Details:

Fields Displayed:
- Amount to Buy: User inputs the number of tokens they wish to purchase.
- Acquisition Cost: Display the total cost of the tokens.
- Common Fees: Show any fees associated with the acquisition that Common charges.
- Transacting Wallet: Confirm the wallet to be used for the transaction. This should default to the most recently active, funded wallet that is compatible with the BASE chain.
User Actions:

- After reviewing the details, the user can proceed by clicking the “Buy” button to confirm the transaction.
- Upon clicking “Buy,” prompt MetaMask or the connected wallet to confirm the transaction.
- The user should have the option to cancel the transaction before finalizing the purchase.

Post-Purchase Behavior:

- After the transaction is completed, the user remains on the explore page rather than being redirected to the token’s community page.
- If the user successfully purchases a token, they are automatically joined to the corresponding community.

### Project Owner

@HIM92

### Bucket ID

#8800

### User Stories / Acceptance Criteria

As a user on the explore page, I want to buy tokens directly from the asset cards. When I click “Buy,” I can enter the amount I wish to purchase, see the total cost, and confirm the transaction using my wallet. I should remain on the explore page after completing the purchase, and I will automatically join the token’s community.

### Design Devlink

https://www.figma.com/design/1b9wbqv9YV2FlU2svFyf0I/IdeaCoin?node-id=815-39215&t=Bs73ODTMr1Of6lIs-0

### Design Screenshot

<img width="246" alt="Screenshot 2024-08-08 at 1 21 45 PM" src="https://github.com/user-attachments/assets/a7fbfdde-5fec-4c63-ac17-033988d44597">
<img width="460" alt="Screenshot 2024-08-08 at 1 27 33 PM" src="https://github.com/user-attachments/assets/330f3628-3f5f-464a-ba89-a31332f1ec27">

**Comment by dillchen** [comment]
Not blocked, but should be wired up to the helpers. 

Will need the Uniswap Helpers

**Comment by timolegros** [comment]
@mzparacha the `CreateLaunchpadTrade` command will be merged as part of https://github.com/hicommonwealth/commonwealth/pull/9820. If your PR for this ticket is merged first, I will create a ticket to follow up - otherwise, we can include it in your PR.
