### ISSUE TITLE
Notifications page: All links for communities pointing on local env 

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#8809]
## Describe the bug

On notifications page, when user click on community icon, he will be redirected to the localhost

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

master/release/v1.5.4-x

**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Sing in 
3. Go to notifications settings
4. Navigate on subscriptions tab
5. Click on some community 

## Actual behavior

Redirection on `http://localhost:8080/`

## Expected behavior

Open proper domain

## Screenshots / Video

https://app.screencast.com/odzfjezZfd1WI

**Comment by burtonator** [comment]
Thanks for the video... I didn't see that!

![CleanShot 2024-08-12 at 16 23 33@2x](https://github.com/user-attachments/assets/5bdd3da2-4260-44f7-be85-ed0734af3e60)

This is the problem.  Does the NODE_ENV not equal 'production' ?
