### ISSUE TITLE
Un-starring a community causes all stars to disappear

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#881]
Then stars are restored when refreshing the page

Could be an issue with `key`s or with the starred state code

**Comment by zakhap** [comment]
part of the bug seems to be an issue with un-starring a community/chain you are currently within (active comm), might be a general un-starring issue of other sorts too

**Comment by zakhap** [comment]
oh this is 100% an issue with what the route `/starCommunity` returns and what the controller method `setStarred` expects it to return. 

controller: 
`const json = response.result;`
 `app.user.addStarredCommunity(new StarredCommunity(json.chain, json.community, json.user_id));`

route: 
`    return res.json({ status: 'Success' });
  } else {
    return next(new Error(Errors.NoStarValue));
  }
`

**Comment by zakhap** [comment]
compound problem i think i figured out, not yet squashed: 
- something is up with the `removeStarredCommunity` method, sometimes it removes more than 1 community. 
- after removing more than one community, if you click again to star an wrongly removed community, it creates a second star in the db, which causes further issues with the starring/unstarring flow.
