### ISSUE TITLE
Launchpad: Randomize image generation

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8864]
### Description

Context: After the user has 1) hit the generate idea or “genius” button, this opens the token launch drawer on discovery and exploration. When this opens the Token Name, Token Symbol, and Token description begin generating. When they are complete, the image begins generating automatically

If the user wants to create a new image, they can hit the generate image button. If they do so, they can cycle through each image generated before they refresh the page by navigating using carrots “<” or “>”.. 

Right now we are hooked into DallE-1 or 2. We will need to update this information to DallE-3.
We will need to pass the token description and token name into Dalle-3 as the prompt for an image.  

### Project Owner

@HIM92

### Bucket ID

#8800

### User Stories / Acceptance Criteria

User story: As a user on Common, I began the process of generating a memecoin with the “Randomize button” after the Token name, Token symbol, and Token description are generated, an image based on those three begins generating. If I like the image, I can immediately launch the token laid out in this bucket ticket: https://github.com/hicommonwealth/commonwealth/issues/8800 . If i do not like the image generated I can generate a new image by hitting the retry button. 

If I have generated multiple images, I can cycle through them by clicking the arrow symbols. 

### Design Devlink

https://www.figma.com/design/1b9wbqv9YV2FlU2svFyf0I/IdeaCoin?node-id=815-39215&t=ffRdv1XrpTBe32aq-0

### Design Screenshot

<img width="158" alt="Screenshot 2024-08-15 at 1 20 49 PM" src="https://github.com/user-attachments/assets/6e911b9b-bac0-415f-b62b-2647ac4cb760">
<img width="54" alt="Screenshot 2024-08-15 at 1 20 50 PM" src="https://github.com/user-attachments/assets/60e1e148-7ba5-4f7b-a3d4-47eeae96e1cb">
<img width="273" alt="Screenshot 2024-08-15 at 1 24 57 PM" src="https://github.com/user-attachments/assets/ea07bd9f-a2c8-419e-b454-8c4e11de110a">
<img width="250" alt="Screenshot 2024-08-15 at 1 25 01 PM" src="https://github.com/user-attachments/assets/632bdd60-3a80-40dc-be0d-9a5fd4c81adc">

**Comment by mzparacha** [comment]
Update: The `CWCoverImageUploader` component responsible for image generation/upload is too messy atm and has many validation/state issues. With this ticket I'd have to add more logic to it (more cluttering) which might break some state. 

Will be working on https://github.com/hicommonwealth/commonwealth/issues/9606 first to cleanup the component and then will continue with this.
