### ISSUE TITLE
Event Storm: Stake/Contests Decoupling, Arbitrary ERC20 Vote Weight

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#8872]
## Description

Placeholder ticket for outputs of event storm re: stake decoupling and ERC20 vote weight. Will determine the architectural decisions for implementing https://github.com/hicommonwealth/commonwealth/issues/8805.

**Comment by Rotorsoft** [comment]
@sachben91 - here is the first draft of the ES board showing the new topic creation flows:
https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764597700673037&cot=14
