### ISSUE TITLE
Create Utility to Generate JWT for Secure Endpoints

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#8874]
### Description

Develop a utility function inside `/libs/api-client` to generate JSON Web Tokens (JWT) for secure access to API endpoints. This utility should reproduce the authentication flows we are currently using (magic, wallet, canvas, privy?)

### Bucket ID

#8694

### User Stories / Acceptance Criteria

- A utility function is created that generates JWTs.
- Initially supports wallet auth and maybe canvas. Privy/Magic SSO options will be considered in future phases.
- JWT utility allows setting expiration times, etc - consider token refresh flow
- Unit tests cover JWT generation and validation.

**Comment by Rotorsoft** [comment]
@jnaviask who can take this one? @raykyri?

**Comment by jnaviask** [comment]
This may actually be something for @ianrowan to look at ... but it depends on the context about how these JWTs will be used/consumed.

**Comment by timolegros** [comment]
For clarity, this ticket involves creating an 'authentication' function for the SDK
- Use a `PRIVATE_KEY` environment variable to sign a message attesting ownership
  - This should replicate the message signing with wallet behaviour from the client
- POST the signature to `/verifyAddress` (or new route)

The scope may include modifying `/verifyAddress` or creating a new authentication route which directly returns the JWT since in the current implementation, `/verifyAddress` returns a session cookie (`/status` returns the JWT based on session cookie).

**Comment by timolegros** [comment]
Been researching the tasks for this ticket. To make authentication as absolutely simple and secure as possible I recommend the following:
1. Create a new command which generates a nonce for a specific wallet address. This should follow approximately the same pattern/implementation as SIWE: https://github.com/spruceid/siwe-quickstart/blob/main/02_backend/src/index.js#L9.
    - The address -> nonce map should be stored in Redis
2. Create a new command which verifies the signature/address/nonce and returns a JWT with a short lifespan (e.g. 1 hr)
    - If the address does not exist in the database upon successful verification, create it (with default community e.g. Ethereum).
3. Modify external API authentication flow to indicate when a JWT has expired (custom error message?)
4. Add an Axios interceptor to the Typescript SDK axios instance which refreshes the JWT upon JWT expiration error
    - This means either adding refresh tokens to the JWT or signing a new message. For simplicity and since this requires no user interaction, signing a new message is likely easier to implement than adding refresh tokens to the JWT.

**Comment by Rotorsoft** [comment]
Sounds good to me... btw, there is probably some cleanup to do after implementing step 2 (join default community after auth).
Makes sense to add logic in `authorization.ts` to make sure address is verified and not expired, returning special error code to axios
