### ISSUE TITLE
Verify prerender.io costs go down when we disable profiles

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8892]
## Describe the bug

We have plans to disable profiles:

https://github.com/hicommonwealth/commonwealth/issues/8766

but part of the upside here is to disable profiles on prerender.io to save costs.

This is a tracking ticket to make sure that works.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by jnaviask** [comment]
Confirmed decrease from ~120k renders/day to ~40k renders/day, which is still above the allotted 1mm renders/mo without overage costs, but considerably better.
