### ISSUE TITLE
Spike: Farcaster actions and weighted votes 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8897]
### Description

- Users who want to upvote contests should be able to do it using Farcaster actions
- Users can upvote contest entries (replies to casts) using Common's Farcaster upvote action. 
- When a user upvotes a contest entry, they should be shown a message that communicates the vote weight of the upvote.
- The vote weight available to each user is calculated by using the total number of tokens held by the user divided by the weight set by the admin when the contest is created. 
- The token that is used to determine the vote weight is set by the admin when the contest is created 
- Action specifications are detailed [here ](https://docs.farcaster.xyz/reference/actions/spec)

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

open questions:
- can we return dynamic information to the user when they use the upvote action. For example, if the user has a vote weight of 10, are we able to send a success toast to the user that reads "you have given 10 upvotes to this entry" 
- are we able to calculate the vote weight of the user using the information that we receive from Farcaster? For example if a user has an ethereum account connected, are we able to know how many degen or ham or mochi tokens they own?

**Comment by jnaviask** [comment]
Timebox: 1.5 hours.

**Comment by rbennettcw** [comment]
- The Action payload we will receive includes the cast ID so we know which content was voted on + the user address so we know who performed the action. Through cast -> farcaster contest -> topic, we can then see which topics the cast is associated with.
  - As long as farcaster contests can only be bound to a single topic, then yes, we should be able to send the user a toast message showing the stake weight of the user's vote on a cast.

- Yes, we can associate the farcaster cast/user info with the contest topic, and calculate the user's vote weight based on user topic token balance * topic multiplier.

cc @sachben91

**Comment by jnaviask** [comment]
Reviewed.
