### ISSUE TITLE
Weighted Voting for Farcaster Contests 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8898]
### Description

Farcaster contests need weighted voting as a contest voting mechanism. This was missed in the early iterations of Farcaster Contests. Weighted voting would enable admins of communities to set a token and corresponding vote weight for the token. Users on Farcaster who hold the token would be able to participate in the contest and add weighted upvotes to entries using Farcaster actions 

### User Stories / Acceptance Criteria

- When creating a Farcaster contest, the admin of the community should be able to enable weighted voting for the contest
- On the weighted voting screen, the admin should be able to copy paste the token address of an ERC20
- The ERC20 should be on a chain that is supported (only Base at the moment) 
- The admin should be able to set the vote weight for the ERC20 token that has been added
- In the next screen, the user should know if the ERC20 they added has been recognized
- The user should see a message for the vote weight that they have set. For example, if the weighted voting is using Mochi and the weight of one token is 10 vote weight, the message should be "1 Mochi equal to 10 votes"

### Design Devlink

[Figma designs](https://www.figma.com/design/DZ5IN1p0QUxpwd0csJRuvv/Contest-V2?node-id=313-48382&t=cHQGApc2uVa4XeS3-0)
### Design Screenshot

<img width="617" alt="Screenshot 2024-08-19 at 1 46 09 PM" src="https://github.com/user-attachments/assets/1efcd4d7-d006-40f4-9a49-510a4d29f71c">

**Comment by masvelio** [comment]
@sachben91 currently we have farcaster contest behind the feature flag. I am wondering if weighted voting will go on prod before, after or in the same time as farcaster. Introducing another feature flag would be problematic and make all those flows complicated. Can we assume that farcaster contest and weighted voting needs to go out together or they are independent?

**Comment by sachben91** [comment]
@masvelio yes weighted voting using ERC20 and farcaster contests should go out at the same time

**Comment by masvelio** [comment]
1. Create topic page looks a lot different than currently. Just want to confirm if we want to change this view exactly how it is on the designs? Including parent topic dropdown and group permissions section? If yes, definitely to discuss with backend team as I think this might be a lift. I think we are missing details how this should work. 
![image](https://github.com/user-attachments/assets/4e66118a-879b-4e4c-b2d8-5949311ff28e)

2. Is there a situation where weighted voting view is not available when creating a topic? Eg, this is only for communities that have stake enabled?
![image](https://github.com/user-attachments/assets/f484a9a2-1529-449c-a392-8b6ef0c3a452)

3. When the token banner should be displayed? I assume only for created topic that have weighted topic turned on?  
![image](https://github.com/user-attachments/assets/acfd7d95-74cb-432e-acf0-d1a969ff2086)

**Comment by sachben91** [comment]
> 1. Create topic page looks a lot different than currently. Just want to confirm if we want to change this view exactly how it is on the designs? Including parent topic dropdown and group permissions section? If yes, definitely to discuss with backend team as I think this might be a lift. I think we are missing details how this should work.
- The only change here should be adding the tabbing at the top, the other changes are not part of this workflow and we should retain the page as is
> 2. Is there a situation where weighted voting view is not available when creating a topic? Eg, this is only for communities that have stake enabled?
TBD but as per our discussion weighted voting should be available for everyone when creating a topic 
> 3. When the token banner should be displayed? I assume only for created topic that have weighted topic turned on?
- token banner should be only for topics that have weighted voting enabled 
> 4. Do we need any changes to "edit topic modal"? I mean, can we still edit/remove topics that will be using weighted voting? What happens with the content that belongs to the topic that is edited/deleted?
do we allow users to delete topics that have contests at the moment @masvelio ? That is the only case in which deleting a topic presents a risk I think.

**Comment by masvelio** [comment]
@sachben91 yeah, we do allow removing topic. We disabled removing thread contest but topic is still deletable

**Comment by masvelio** [comment]
@sachben91 most of the UI has been done in this ticket https://github.com/hicommonwealth/commonwealth/issues/8981
Moreover, some of the requirements are not up-to-date. Imo we should close this ticket and keep working on [this one](https://github.com/hicommonwealth/commonwealth/issues/8958) as it has mostly the same scope + more up to date info. If you agree @sachben91, please close it

**Comment by sachben91** [comment]
closed as per above comment
