### ISSUE TITLE
Support Substrate on-chain bounties

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#891]
- [ ] Create a new page, that comes after the Treasury page for Substrate chains, to show on-chain bounties. Each bounty should show:
    - Description (as title)
    - Value
    - Curator
    - Deposit (curator_deposit)
    - Bond
    - Status: Proposed/CuratorProposed (which are effectively the same in the user interface), Approved, Funded, Active, PendingPayout.
    - Expiry
- [ ] Create a new proposal creation flow, after "New council motion", for "New treasury bounty". It should ask for these parameters:
  - curator (an address to manage the bounty)
  - amount to curator ("fee")
  - amount to be awarded to recipient (amount to curator + amount to recipient === "value")
  - description (title)
- Add all the bounty-related actions to the Create Council Motion flow.

See https://github.com/paritytech/substrate/issues/5713 and in particular frame/treasury/src/lib.rs in https://github.com/paritytech/substrate/pull/5715/files 

approximate design:

![image](https://user-images.githubusercontent.com/1273926/95976193-05661e00-0dcc-11eb-8128-162bb1057622.png)

(this is messy and needs more work, but the UI can be sorted out once everything else is roughly working)

**Comment by zakhap** [comment]
@jnaviask 
Upon reading through `frame/treasury/src/lib.rs`, it seems as though the bounties/bounty proposals/etc are an extension of the treasury. Currently, we don't include bounty-related events in our chain-events or in our treasury controller (same can be said of `EntityKinds`). Can you confirm these are necessary steps for getting and creating bounties?

**Comment by jnaviask** [comment]
> Currently, we don't include bounty-related events in our chain-events or in our treasury controller (same can be said of EntityKinds). Can you confirm these are necessary steps for getting and creating bounties?

Yep, you should add the Chain Events and Chain Entities to the chain-events project, and then you can add them to the treasury controller!

**Comment by zakhap** [comment]
https://github.com/paritytech/substrate/pull/7536

This PR from yesterday refactors the Treasury Pallet into 3 distinct pallets: Proposals, Bounties, Tips.
