### ISSUE TITLE
Show Substrate validator & councillor status on User component

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#892]
- Ensure whether a user is a validator or councillor is saved on the Profile model by the chain event listener, in a column alongside identity and judgements
    - This is pretty involved...need to listen to a few different event types, and then provide a way to manually reinitialize all users' validators and councillor status the same way we have `yarn migrate-identities`
- Ensure this data is passed to the frontend whenever Profile objects are requested
- If hideOnchainRole is not set to true, display it by default, the same way showRole is displayed in a tag component. If a user is both a validator and councillor, then only show them as a councillor.
- Since this affects lots of places in the UI, I will take a look at a more compact way to display this using icons before merging

**Comment by jnaviask** [comment]
Is there any reason we want this data stored on the Profile rather than the Address model?
