### ISSUE TITLE
Weighted Voting using ERC20

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8960]
### Description

These are the screens for setting up weighted voting using ERC20s at the topic level. 

### Project Owner

@sachben91 

### Bucket ID

#8805 

### User Stories / Acceptance Criteria

- in the enable weighted voting using ERC20 page the user should be able to select the chain (currently only Base) and input a token address for an ERC20 that they wish to use
- The user should be able to enter a vote weight multiplier for the token that they have inputted. The vote weight multiplier will be the weight of the token that the user has selected 
- The vote weight per user = vote weight set by admin X number of tokens held by user
<img width="561" alt="Screenshot 2024-08-29 at 11 34 28 AM" src="https://github.com/user-attachments/assets/5998c13f-ad78-4b7b-bafc-0eeeee152599">

- When  the user clicks on enable weighted voting, the topic should be created with weighted voting enabled for the topic using the ERC20 that the user has selected 

### Design Devlink

[Figma ](https://www.figma.com/design/DZ5IN1p0QUxpwd0csJRuvv/Contest-V2?node-id=210-25795&t=Nxag8u4qFiYLonKa-0)

**Comment by jnaviask** [comment]
Note that the component displaying token price is considered OUT OF SCOPE for this ticket and will be ticketed separately.

**Comment by masvelio** [comment]
This ticket is done from the UI perspective. To make it completed, we need to wire it up with the backend

**Comment by masvelio** [comment]
Bumping to 2 because of additional scope: fetching and displaying token data
