### ISSUE TITLE
Weighted Voting display within topic

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#8961]
### Description

- Once weighted voting is moved to the topic level, the weighted votes available using ERC20 should be displayed at the topic level instead of the community level. The community stake should still be displayed at the community level. 

### Project Owner

@sachben91 

### Bucket ID
#8805 

### User Stories / Acceptance Criteria

- If the topic has weighted voting using ERC20s, the user should see the token that is used for weighted votes, the price of the token and the vote weight that the user has in the topic 
<img width="831" alt="Screenshot 2024-08-29 at 11 36 45 AM" src="https://github.com/user-attachments/assets/e03cc31e-4168-4a49-aebb-419b70267a9f">

### Design Devlink

[Figma] (https://www.figma.com/design/DZ5IN1p0QUxpwd0csJRuvv/Contest-V2?node-id=313-48382&node-type=CANVAS&t=ATGawOrkkNVuKhRs-0)

**Comment by jnaviask** [comment]
Note that price display is out of scope for this ticket.
