### ISSUE TITLE
Cannot remove own addresses as admin

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#899]
- If I have two admin addresses, I cannot remove either one from being an admin using the Manage Community modal. As long as I'm not the only admin in a community, I should be able to remove any of my addresses from being admin.
- If I'm removing myself as admin or mod, I should see a confirmationModal that asks me if I really want to give up my admin role, so I have an opportunity to confirm that I really want to resign my own admin/mod role.

**Comment by gdjohnson** [comment]
@raykyri To be clear—if I have just one admin address, I should be able to remove it (and immediately lose all permissions to add/remove further addresses?)

**Comment by raykyri** [comment]
Yeah, but you should be shown a confirmation dialog that emphatically tells you that will happen.

Also, you *shouldn't* be able to remove it if nobody else is an admin.

**Comment by gdjohnson** [comment]
Realized at some point yesterday confirmation modal isn't gonna work because community mgmt is already a modal. We could either convert it into a page or I'll figure out an alternate solution to checking for confirmation

**Comment by gdjohnson** [comment]
> Save/Cancel state for the page instead of save-as-you-change. When making changes on the page, the changes aren't saved but a "Save" button appears along with a "Cancel" button. This supports batch operations but it means the changes, even the completely riskless ones such as ticking a checkbox (which is just as easily unticked), aren't applied until the user hits "Save" on the page. It also requires the "Save" button to be very visible or the user might lose data another way, by forgetting to save their changes.

This is an interesting alternate approach.

**Comment by gdjohnson** [comment]
I'd also like to add support to the CommunityInfo and ChainInfo controllers to add, delete, and edit roles live. Right now, these stores only get updated on chain or community initialization. Thus, a request to the backend is required any time you want to ensure that this data is up-to-date.

**Comment by raykyri** [comment]
Shouldn't modals be able to pop up over existing modals? We used to do this during Web Wallet logins.

**Comment by gdjohnson** [comment]
@raykyri At least having stepped through with a debugger, the confirmationModalWithText doesn't seem to fire from inside a modal. I can scope out other uses
