### ISSUE TITLE
Stake + ERC20 Dual Model Assessment Spike

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#9042]
In making a final decision about whether or not to adopt a dual model of supporting staked voting and ERC20 voting, some a preliminary assessment needs to be made regarding what the scope of effort is required.

Timebox: 3H

## Acceptance Criteria
- There should be a writeup explaining the scope of changes for supporting the dual model vs only the new model

**Comment by rbennettcw** [comment]
Here's the written assessment comparing the models: https://gist.github.com/rbennettcw/6cfc16731686d439d85a55d213a80e58

**Comment by jnaviask** [comment]
Reviewed and suggestions implemented by product.
