### ISSUE TITLE
Figure out how to import frames.js without increasing slug size by ~100MB

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#9070]
## Description

#9069 removes frames.js code because it increased slug size so dramatically that it blocked production deployment. We still want to ship our farcaster integration, but we need to figure out how to do it without blocking the production application.

One possible solution is a separate heroku deployment including frames, so we don't need to import the lib on the main app environment. Open to other solutions as well. Please discuss plan on this ticket.

**Comment by dillchen** [comment]
should close? if @kurtisassad this should be reopened lmk, as we emailed Heroku abt the bundle size
