### ISSUE TITLE
Use Docker for Heroku deployments

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#9085]
## Description
- [ ] Create `Heroku.yml`
- [x] #9099
- [ ] #9158
- [ ] Add documentation for new deployment/Heroku practices
- [ ] Test on Frick (how does Docker) compare with native performance-wise? (Do we need to scale?)

## Additional context

Tagging @rbennettcw @Rotorsoft @kurtisassad for visibility.

**Comment by jnaviask** [comment]
@timolegros @kurtisassad This unblocks us on moving from a build-based deployment model to a promotion-based deployment model. Let's discuss on platform hours.

**Comment by dillchen** [comment]
Should this get moved to needs 2nd review?
