### ISSUE TITLE
Spike: effort required and tradeoffs in replacing our wallet selection flow with AppKit

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#9115]
## Description

Per @ianrowan's research in https://github.com/hicommonwealth/commonwealth/issues/8989 we may be able to replace our hand-rolled Wallet selection with AppKit. However, we need to understand a few things:

1. How does Magic support work on Appkit?
2. How does Cosmos and Solana support work on AppKit?
3. How does Custom Domain support work on AppKit? (cf. #9028)

Ideally the outcome of this spike is an understanding of the tradeoffs involved in migrating to AppKit, the exact tasks necessary to migrate to AppKit, and an estimation of the effort involved in executing on it.

Timebox: 3 hours.

**Comment by ianrowan** [comment]
Will drop some additional research for (1) 
https://commonxyz.slack.com/archives/C060UC6UCCC/p1724853821965319

Magic confirmed that the built in Magic component of AppKit would not use our API key, but a single API key that is owned by WalletConnect(ie users managed by walletConnect which are technically managed by magic) 

They mentioned they could help us dig in more how to use our own API key with some sort of work around. That is pending but would probably be the only way we'd be able/willing to use AppKit for magic

**Comment by mzparacha** [comment]
For Q's in OP.

1. It's unclear how SSO users will be migrated or if its possible. I couldn't find any WalletConnect docs on how to use our existing magic key with AppKit. As @ianrowan mentioned [here](https://github.com/hicommonwealth/commonwealth/issues/9115#issuecomment-2329924943), It'd help if there is a workaround to use our magic API key with AppKit. The other option is to migrate existing SSO user accounts to AppKit but it doesn't seem like an easy integration - also I couldn't find any docs regarding this kind of migration in WalletConnect. 
2. Wallet connect **"protocol"** seems to support all the chains (Ethereum/Cosmos/Solana/Substrate(Relay)) that we support (see [here](https://docs.walletconnect.com/advanced/faq#what-chains-does-walletconnect-support) and  [here](https://docs.walletconnect.com/cloud/chains/chain-list)) but their **"SDK"** atm only seems to support Ethereum/EVM and Solana (more [context](https://docs.walletconnect.com/appkit/react/core/installation#implementation)). I found some references that suggest we could add custom integrations for multi chains possibly supporting [Cosmos](https://docs.walletconnect.com/advanced/multichain/rpc-reference/cosmos-rpc) and [Substrate/Relay](https://docs.walletconnect.com/advanced/multichain/polkadot/dapp-integration-guide). I also tried a test AppKit integration with Solana/Ethereum (which their SDK supports out of the box) and it seemed to work - other than the default Ethereum/Solana wallets implementation, everything else would be/involve some kind of custom implementation.
3. We'd have to whitelist our domains and domains of "white-label/custom-domain" instances in the "app/project" we'd be creating in https://cloud.walletconnect.com/.

--

Based on the data we have ATM, the migration tasks with estimates would be
1. We could use our magic key with AppKit which would be simpler and less time-consuming (if possible at all). The other option of Migrating existing SSO accounts would be harder, might take multiple sprints (if possible at all). With both options, we'd have to update current/legacy logic around client/server authentication to accommodate AppKit.
2. For EVM/Solana, the built-in SDK support would make it easier to just update current/legacy logic around client/server authentication to accommodate AppKit (a sprint worth of work). For other chains tho, we'd have to dig into custom logic for each chain + client/server authentication accommodation around that chain auth with AppKit, which would be harder and might take multiple sprints.
3. For custom domains, the changes seem minimal (< sprint) - considering we find some solution for 1.

cc: @jnaviask

**Comment by jnaviask** [comment]
Closing this spike to revisit after #9028.
