### ISSUE TITLE
Too many requests to `/getAddressProfile` when visiting any page

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#9125]
### Description
A lot of requests to `/getAddressProfile` happen when the app is loaded or a community is visited. Some of these calls return similar responses and some calls seem redundant.

These calls should/can be batched to optimize network load.

Reported by: @timolegros

**Comment by timolegros** [comment]
Duplicate of https://github.com/hicommonwealth/commonwealth/issues/9053

**Comment by mzparacha** [comment]
Ops, didn't knew it was a duplicate. Closing this in favor of https://github.com/hicommonwealth/commonwealth/issues/9053. Thanks @timolegros.
