### ISSUE TITLE
Comment attaches to wrong thread

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#921]
## Description

When flipping between threads through the notification dropdown, if you comment on thread, it gets attached to the wrong thread!

> it was an issue with the comments store, `oninit` vs `onupdate`, guess we fixed it for comments but not for `createcomment`,

- Above from internal slack.

## *Who* is the bug affecting?

Everyone!

**Comment by gdjohnson** [comment]
Hmmm lemme peek.

**Comment by gdjohnson** [comment]
Couldn't replicate this last time I gave it a run-through, but I'll load it up again today, give it a spin see what's up

**Comment by gdjohnson** [comment]
I'm getting very broken behavior from notifications—80% of the time, while on an existing thread, it will fail to redirect to the notified thread. But I'm not able to replicate this specific misfortune.

**Comment by raykyri** [comment]
@gdjohnson Want to create a new issue for that?

**Comment by gdjohnson** [comment]
See [947](https://github.com/hicommonwealth/commonwealth/pull/947).
