### ISSUE TITLE
Editor design questions v2..

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#9222]
## Describe the bug

OK. Another batch of UI questions for the editor.

- should the desktop editor have a limited height or full height of the underlying document?  Right now the default hight is 200px and it can grow to 500px.  
- should the editor have a blue outline when it's active? This is how the current editor works and without an outline it seems headless.  
- Do the header and footer need to have a different color?

### Button in Footer

I need some guidance of how to handle the button in the footer.  Our design TRD had the button in the footer.

Here's what it looks like per the TRD.

https://github.com/hicommonwealth/commonwealth/issues/8593#issuecomment-2307641913

However we have an issue because our buttons differ from desktop and mobile in the designs.

Here is what the footer looks like for desktop and mobile:

**desktop**

![CleanShot 2024-09-17 at 13 53 59@2x](https://github.com/user-attachments/assets/a0af46aa-86e3-4211-a21a-7a6d77655d82)

**mobile**

![CleanShot 2024-09-17 at 13 54 14@2x](https://github.com/user-attachments/assets/47950568-ebc4-4bf3-9c4e-1625117758f6)

If we want the button in the footer, I can do that but I have to wrap it in another component to adapt its UI for desktop or mobile and add the functionality we need on mobile (different button) and support the ability to disable it in certain situations as needed by the 'new thread' page.

I don't really feel strongly on any of these issues so whatever you guys decide is fine with me.

### Current UI

This is what it currently looks like:

![CleanShot 2024-09-17 at 13 51 06@2x](https://github.com/user-attachments/assets/b0065b6a-284a-4216-ae8c-9ac16b9af3b8)

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by sssssabinaaa** [comment]
-let's do full height for the desktop editor
-let's also do a blue outline
-if possible, adapt consistent style from the desktop footer to the mobile footer
