### ISSUE TITLE
Add ability to copy wallet address to clipboard

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9244]
## Describe the bug

Add the ability to copy a wallet address to clipboard and add copy icon in Stake sidebar

Add copy icon with a popup after address has been successfully copied (phosphor icon family)

Phosphor copy icon 
https://phosphoricons.com/?q=%22copy%22

![Screenshot 2024-09-16 at 4 32 57 PM](https://github.com/user-attachments/assets/ca0912bc-713c-4e9e-b8a9-b83968df68d6)

**Comment by KaleemNeslit** [comment]
@Israellund  i have question related to this ticket  where i need to add icon?  In the list of select ?  
where can  i find " Stake sidebar " ? . I need to add icon in two different places  ?  i am little confused

**Comment by Israellund** [comment]
@KaleemNeslit I'm sorry, this is a very confusing ticket. The icon only needs to be added in one place, in the Select address dropdown inside the modal you see after clicking Buy Stake. By "Stake sidebar" I mean the Stake section above the user sidebar (with Admin Capabilities, Discussion, Governance, etc). The Stake information will only be visible in the sidebar when Stake is enabled in a community. 
The icon should be to the right of the selected wallet address. In the image below, where the highlighted square is. 
Let me know if you need any other information or if my second description was just  as confusing as the first. 
![Screenshot 2024-10-03 at 1 04 07 PM](https://github.com/user-attachments/assets/8a34f0a3-e607-4d3c-b200-7461fae05dd7)
![Screenshot 2024-10-03 at 12 53 12 PM](https://github.com/user-attachments/assets/401dd716-0338-434e-8aad-122703f7bfc8)
