### ISSUE TITLE
"Selecting your chain" text should be more responsive

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9266]
## Describe the bug

"Selecting your chain" text should be more responsive.
Refer to how other similar text is handled on the site.

![Screenshot 2024-09-18 at 11 54 22 AM](https://github.com/user-attachments/assets/d3a4490d-1634-4bda-9c68-106a0878d5e0)

**Comment by KaleemNeslit** [comment]
@Israellund  
<img width="194" alt="image" src="https://github.com/user-attachments/assets/4f571f1e-1d92-4529-b466-9ed436ab65dc">
is this good ? , i am not able to see other related text if we add more width it will make page scrollable  . Also i am facing issue when i checkout to master and pull latest code i am not able to run code . need Key related to ALCHEMY and cloudfare .

**Comment by Israellund** [comment]
@KaleemNeslit This looks good in this picture. I will email you the env vars needed for you to run it locally. When you're able to, will you record a loom or a screencast of how the above text looks when you adjust the screen widths?

**Comment by Israellund** [comment]
@KaleemNeslit Also when tickets are ready to review, please assign myself, @masvelio, @mzparacha and @burtonator for reviews. We are the Product Engineering team and handle reviewing most frontend tickets.

**Comment by KaleemNeslit** [comment]
Uploading Screen Recording 2024-10-03 at 10.45.35 AM.mov…

@Israellund here is the video
