### ISSUE TITLE
User should be able to switch address from sidebar

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9271]
## Describe the bug

A user should be able to change their wallet address from the sidebar when in a community. 

<img width="647" alt="Screenshot 2024-09-18 at 1 35 00 PM" src="https://github.com/user-attachments/assets/cd6b7939-1842-4ebf-a3e2-99102080b0f6">

**Comment by dillchen** [comment]
https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=177-38105&t=rBuAzKztyRxLQEZf-4
