### ISSUE TITLE
Pagination should be added to Home screen

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9272]
## Describe the bug

Pagination should be added to the Home page, get rid of infinite scroll. Pages can be limited to a certain amount, but should be paginated. 
![screenshot_2024-09-17_at_8 52 03___am_720](https://github.com/user-attachments/assets/5ac76164-c46f-4dac-974d-45020066e170)

**Comment by Israellund** [comment]
@KaleemNeslit Try looking into this ticket and let me know if you need anymore information or guidance.

**Comment by KaleemNeslit** [comment]
@Israellund pagination  for "Global activity" or " for you " or for both api's ?

**Comment by Israellund** [comment]
@KaleemNeslit This is for adding pagination to both the For You and Global pages. Sorry for the confusion.
