### ISSUE TITLE
Show more cut off on mobile

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9278]
## Describe the bug

The `Show more` button/functionality is not shown when on mobile, rendering the threads unreadable

Replication steps:
-create a thread and paste a large text into the editor
-if not already in mobile mode, convert to mobile
-notice that you can not see `Show more` button/functionality

![screenshot_20240917_151743_chrome_720](https://github.com/user-attachments/assets/c339bf5e-523c-4583-bc1e-b2cb3235a892)

**Comment by KaleemNeslit** [comment]
@Israellund  @salman-neslit  open the PR for same issue once it merge it will be solve.
https://github.com/hicommonwealth/commonwealth/pull/9698

**Comment by Israellund** [comment]
@KaleemNeslit Thank you. 
Closing this ticket as it will be fixed once #9698 is merged.
