### ISSUE TITLE
edits to threads do now always show without refresh

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9282]
## Describe the bug

-This ticket is part investigation into replicating this issue, and if able to replicate and determine the cause, fix it. 

-After editing a thread the UI doesn't show the update until I refresh. Happens both in production and locally. It doesn't happen for every edit but for roughly 50% of edits (maybe race condition?)

## Reproduction steps

-create a thread or go to an existing thread
-edit the thread
-track its behavior, does it show the new edits immediately or do you have to refresh the page?

## Actual behavior

-new edits not being shown immediately after editing, but only some of the time
## Expected behavior

-edits should update immediately without having to refresh the page.

**Comment by KaleemNeslit** [comment]
@Israellund Hi can you please mark this as fixed, It's being resolved in PR #9804.

**Comment by Israellund** [comment]
Closing this ticket as it is fixed in #9804 as mentioned above by @KaleemNeslit
