### ISSUE TITLE
Any user can view the Manage Topics page

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9284]
## Describe the bug

Literally any user can view the manage topics page though they won't be able to make changes due to API authentication layer.

## Reproduction steps

go to any community and add `/manage/topics?tab=create-topic`

e.g. https://commonwealth.im/dydx/manage/topics?tab=create-topic

**Comment by KaleemNeslit** [comment]
@Israellund  so no one other then admin can see this tab ?

**Comment by Israellund** [comment]
@KaleemNeslit Yes, only admins should be able to see this page
