### ISSUE TITLE
🟪 LinkTokenToCommunity

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#9394]
# Description
This policy will link a launched token to the corresponding community after receiving TokenLaunched events. The association will be found by linking communities via new token address with token event.

- Need to discuss Abi creation with protocol team
- Need to wire RabbitMQ routes to policy
- Need to declare new event TokenLaunched

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @sachben91      | @rbennettcw        |

## Model
[Event Storming Model](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764597627576884&cot=14)

## Engineering Requirements

1. **Integration**
   - Outbox - TokenLaunched
2. **Routing**
   - Standard EVM routing
   - Defined TokenLaunched schema (see bucket, command)
3. **References**
   - N/A
4. **Business Rules**
   - N/A passthrough command
5. **Response**
   - Command OK -> ack

## Unit Testing
- confirm outbox event triggers policy

**Comment by dillchen** [comment]
Discussion points:

We add the Token to the DB in #9371, we do not launch it on-chain.

In the LinkTokenToCommunity route: we need to 1) link to community and 2) attach the token address to the Token in DB

**Comment by kurtisassad** [comment]
New Token will be:
tokenAddress (primary key)
namespace (maps to community.namespace)
supply
