### ISSUE TITLE
🟦 Helpers for Uniswap Swaps

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#9396]
# Description
Sells launchpad tokens in communities with tokens (not deployed)

These are UI commands that invoke on-chain systems, no platform work required here, but tagging @ianrowan and @masvelio  for grooming

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @sachben91      | @ianrowan         |

## Model
[Buy Command](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764597629079712&cot=10)

## Engineering Requirements
- @ianrowan to review and see if we can directly leverage the Uniswap API for Swaps
- @ianrowan would be great to add'l note if their API helps retrieve tx'es or make recommendations on how we should update the `Transactions (sic) Model` so that we can display these swaps on the user's profile

## Additional Context
- Will be wired up to the Buy / Sell Modal

**Comment by ianrowan** [comment]
closing as we're using swap widget
