### ISSUE TITLE
🟦  LinkToken

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#9398]
# Description
Links a launchpad token to the associated community

Tokens have:
- short name (ticker)
- launchpad address (not optional)
- UniV3 pool address (optional) - this is after uniswap deployment
- associated to a community (we will keep the launchpad address in the community schema so we can find the associated community when the token is received)

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @sachben91      | @rbennettcw        |

## Model
https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764597629079712&cot=10

## Engineering Requirements

1. **Authorization**
   - only the policy `LinkTokenToCommunity` will execute this command (we don't expose this endpoint)
2. **Schemas** - Use [zod](http://zod.dev)
   - Input
     - Token properties
   - Output
     - New token with community attributes
3. **Routing**
   - No routing
4. **Loading Aggregate**
   - Token with same address don't exist, b/c we are creating a new entity (projection of on-chain token)
5. **Business Rules**
   - must not exist
6. **Mutations**
   - Create token
7. **Persistence**
   - Token schema (new table Tokens), could be CommonTokens, LaunchPadTokens
   - FK to Communities (community_id)
8. **Events**
   - N/A
9. **Response**
   - Standard output

## Unit Testing

- In community lifecycle, add section to test token creation, buying a and selling projection, and triggering deployment

**Comment by rbennettcw** [comment]
@mzparacha is working on the `CreateToken` command which is effectively the same as this `LinkToken` command.

`CreateToken` will be invoked after the txn is signed. The `Token` schema will contain all token metadata and a Community ID reference.

Closed by #9408

**Comment by rbennettcw** [comment]
The dupe ticket has been closed.
