### ISSUE TITLE
🟩 TokenTrades

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#9413]
# Description
Projects on-chain token buys and sales to off-chain Tokens projection

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @sachben91      | @timolegros         |

## Model
See bucket #9393

## Engineering Requirements

1. **Events**
   - TokenBought, TokenSold ---- or TokenTraded -> consult with @ianrowan 
2. **Schemas**
   - See token model in Link command
3. **Business Rules** Tagging @dillchen to answer caching off-chain 
   - Do we keep track of token balance in projection? Our pattern is to fetch balances directly from the UI.
   - Do we keep track of off-chain audit trail or always query the contract?
4. **Persistence**
   - See Link command
5. **Response**
   - N/A

## Unit Testing
- Make sure projected state reflects the decisions we made in 3

**Comment by timolegros** [comment]
If `supply` (floating supply) in the launchpad Trade event is equal to the total supply then trigger transferring liquidity to Uniswap.
