### ISSUE TITLE
Connect routes for email notifications 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9415]
### Description

On Knock, we have two types of emails we want to send:
- email digest: The email digest is a compilation of updates (most active threads) from communities that the user is part of
- email recap: This is a batched recap of all the notifications that the user has got over the last week 

Here are the workflows on Knock:
- [Email Digest](https://dashboard.knock.app/common-dev/development/workflows/email-digest)
- [Email Recap](https://dashboard.knock.app/common-dev/development/workflows/email-recap)

we have routes set up for these emails already but they need to be connected to the email templates 

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- Email digest and email recap templates should have the dynamic data fetched from the routes that have already been set up for those

**Comment by dillchen** [comment]
tagged @timolegros per parking lot

**Comment by timolegros** [comment]
Issues:
1. What is the default avatar URL for users who don't have one set?
2. The Recap email template (and therefore likely also the digest email template) does not render correctly at all in email clients (just tested Gmail):
![Image](https://github.com/user-attachments/assets/771af2ca-6faf-447b-b2a8-b387fcbb8ec0)
![Image](https://github.com/user-attachments/assets/1c9a7b2c-12ca-4d19-bf2f-75bd8f76d8c5)
![Image](https://github.com/user-attachments/assets/97c02752-d2ad-4426-be38-05e1c7ac2ff5)

**Comment by timolegros** [comment]
@dillchen why did you move this into review? Have the emails been made fully responsive using both routes? Unless I am mistaken we still need someone internal (e.g. Kevin) to link the routes to the templates to properly load the dynamic data.

**Comment by timolegros** [comment]
All further issues are detailed in:
https://github.com/hicommonwealth/commonwealth/issues/10139
https://github.com/hicommonwealth/commonwealth/issues/10140

**Comment by timolegros** [comment]
All further issues are detailed in:
https://github.com/hicommonwealth/commonwealth/issues/10139
https://github.com/hicommonwealth/commonwealth/issues/10140
