### ISSUE TITLE
Add more functionality to username hover pop-up 

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9426]
## Describe the bug

-This is to update the functionality of the username hover pop up. 
**The pop up should now show:**
-The profile name
-the profile name should be clickable and redirect to that user's profile. 
-The wallet address should show the first 4 characters and the last 2 characters. Ex: "0x2C...42"
-to the right of the wallet there should be a copy icon that copies the user's address to your clipboard

**NOTE: No design is needed, knock yourself out.** 

## Reproduction steps

-go to a thread that has at least 1 comment
-hover over the user's name that made the comment
-notice that it looks like the screenshot below

## Screenshots / Video

![Screenshot 2024-10-03 at 3 47 57 PM](https://github.com/user-attachments/assets/1da21749-ef3b-4227-8259-482123c56055)

**Comment by dillchen** [comment]
Might need on on this one @Israellund
