### ISSUE TITLE
Remove thread from upvotes drawer

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9447]
## Describe the bug

-Remove the thread preview - the drawer becomes particularly large when threads contain photos. Reducing the width of this drawer allows the user to view the thread while also looking at upvotes

![Screenshot 2024-10-04 at 8 40 51 AM](https://github.com/user-attachments/assets/eb469661-0fa5-4c76-b428-6452f7863f08)

**Comment by KaleemNeslit** [comment]
@Israellund  we also have comment  preview on upvotes drawer should i remove that as well ?

**Comment by Israellund** [comment]
@sachben91 See question above. Thank you
