### ISSUE TITLE
Thread previews should show truncated image if thread contains image

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9455]
## Describe the bug

-Thread preview should show truncated image if thread has an image
-click the text should bring you to the thread (as it already si)
-click the image should open the image/s to it's own view, with the thread on the right side. Similar to Twitter 

Designs:
https://www.figma.com/design/bP5OITAQuDGgC9wkvXwX6h/Community-Wallet?node-id=60-2814&t=tVR2Y7KzTzfsGG7N-1

https://github.com/user-attachments/assets/a26ee618-6591-4e54-8ffb-d7c3093dbb57

![screenshot_2024-10-04_at_12 16 36___pm_720](https://github.com/user-attachments/assets/e29d0bc4-fb0e-42c8-b677-d930c67c25d8)

**Comment by sssssabinaaa** [comment]
https://www.figma.com/design/bP5OITAQuDGgC9wkvXwX6h/Community-Wallet?node-id=60-2814&t=tVR2Y7KzTzfsGG7N-1

**Comment by salman-neslit** [comment]
@Israellund i need access to the figma design.
