### ISSUE TITLE
Abnormally large spacing in the user dashboard

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#9485]
## Describe the bug
Spacing in the global dashboard appears to be much larger than the 'normal spacing' between threads in the feed. 

### Initial conditions
Mark and Rhys both have this spacing issue. Both using chrome and rhys is experiencing the spacing issue after you scroll down past the explore communities button. 

**Environment:** 

**Branch/Release version:** 

**Browser:** 
Chrome
**Wallet:** 

## Reproduction steps
go to commonwealth.im and see the spacing in the user dashboard. 

## Actual behavior
Spacing seems to be larger between the feed in the user dashboard. Spacing originally was not this large. 

## Expected behavior
Spacing to be Normal. See example below: 
<img width="391" alt="image" src="https://github.com/user-attachments/assets/932c5021-41c3-434f-8809-a421003074cf">

## Screenshots / Video
https://www.loom.com/share/2c7256191e4349448ac6ad4caa235111?sid=def43c01-f0aa-4875-adee-802ed6f35c58
![Screenshot 2024-10-08 at 11 58 01 AM](https://github.com/user-attachments/assets/0202c6a2-ab93-4178-8669-c762e529fa1b)

## Reporter
Mark and Rhys. I tried to reproduce but was unsuccessful

**Comment by Israellund** [comment]
Closing this as both @mzparacha and I can not replicate it locally, and so it will be fixed on prod with the next release.
