### ISSUE TITLE
useUpdateSubscription only called during account creation / onboarding.

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#9492]
## Describe the bug

It looks it we're gating knock notification preferences during onboarding only and these aren't set anywhere in the notifications settings page:

useUpdateSubscriptionPreferencesMutation isn't called anywhere but onboarding.

We're going to need to duplicate this setting in the preferences page and not sure how this slipped through.

I think maybe there was a miscommunication.  

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by timolegros** [comment]
#6622 all the toggles on this page should use the mutation.
