### ISSUE TITLE
Merge `All` and `Overview` Page in sidebar, convert to tabs on one page

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#9501]
### Description

`All` and `Overview` present the same information using different views.

We should present them as toggles of the same page.

### Project Owner

@dillchen

### User Stories / Acceptance Criteria

- get rid overview as a page in the sidebar
- add a toggle in the filter / navigation row that allows people to toggle between views (getting rid of the "latest thread" button)
- allow admins still to set the default view of the community
- create a small explainer / toast that notifies users of the change (to be shown for a week)

### Design Devlink

https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=789-4056&t=Gd4C2Clf0RaiggYC-1

### Design Screenshot

(https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=648-2394&t=lorycENhShi4Km5i-1)

**Comment by sachben91** [comment]
icons pending from @sssssabinaaa

**Comment by dillchen** [comment]
@Israellund when @KaleemNeslit gets to this can u walk him thru da ticket

**Comment by Israellund** [comment]
I am making a growl for this, the new separate ticket is [here](https://github.com/hicommonwealth/commonwealth/issues/9852) @masvelio @mzparacha Please review corresponding PR without the line  "create a small explainer / toast that notifies users of the change (to be shown for a week)"
