### ISSUE TITLE
Create Card Style View for Threads

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#9502]
### Description

- create another view for the threads page that is more like an "image/ card view"

### Project Owner

@dillchen

### User Stories / Acceptance Criteria

- is another toggle that users are able to click on All / Overview and within topics (first screenshot)
- allows for 3 by 3 view of images and thread (second screenshot)

### Design Devlink

[Figma](https://www.figma.com/design/dGPiswtnIfQIzSNOlB4MNC/Sticky-editor-%2B-Sidebar-%2B-Thread-UI?node-id=729-904&node-type=frame&t=rJYC8oTIb2bgLOtH-0)

### Design Screenshot

![Image](https://github.com/user-attachments/assets/545d2d36-79ef-470f-8d16-f10e0d197f66)

![Image](https://github.com/user-attachments/assets/8ff85235-1f5b-4d46-973a-4a3e802937b5)

### Additional Context

Should leverage our existing card components

**Comment by dillchen** [comment]
cc: @Israellund assigning @KaleemNeslit on this

**Comment by KaleemNeslit** [comment]
@Israellund  in cardView which data he show ? same data as All or OverView page ?

**Comment by Israellund** [comment]
@dillchen can you clarify @KaleemNeslit question above? Thank you

**Comment by KaleemNeslit** [comment]
@sssssabinaaa  where can i find this icon for card view ?

**Comment by sssssabinaaa** [comment]
@KaleemNeslit here you go! It's called kanban https://phosphoricons.com/?q=%22kanban%22
