### ISSUE TITLE
Update knock so the templates are as specified in the design. 

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#9557]
## Describe the bug

Make sure that knock is configured so that the templates line up with the design.  

We have to send the avatar URL though and I'm still working on figuring out how to send that.  

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by burtonator** [comment]
It looks like we're fetching the profile information via:

```

  const { data, error, isLoading } = useFetchProfileByIdQuery({
    userId,
    apiCallEnabled: !!userId,
  });

```

**Comment by dillchen** [comment]
Completed by #10175
