### ISSUE TITLE
Remove ViewCountCache + increment view count in GetThreadsByIds output middleware

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#9593]
## Prerequisite
#9646 

## Description
Title

**Comment by timolegros** [comment]
We have a viewCountCache which prevents the view count from being incremented by a single user more than once every two minutes (per thread). @sachben91 is this still something we need? 2 minutes seems like an arbitrarily chosen value and I think every page refresh/load regardless of the number of times in any period should count as a view.

Also @Rotorsoft it seems to me that we could simplify view count handling such that view count incrementing is a by-product of thread fetching rather than a separate route that we need to remember to call. This would mean that fetching a thread using the external API would also count as viewing a thread @sachben91.

**Comment by Rotorsoft** [comment]
> We have a viewCountCache which prevents the view count from being incremented by a single user more than once every two minutes (per thread). @sachben91 is this still something we need? 2 minutes seems like an arbitrarily chosen value and I think every page refresh/load regardless of the number of times in any period should count as a view.
> 
> Also @Rotorsoft it seems to me that we could simplify view count handling such that view count incrementing is a by-product of thread fetching rather than a separate route that we need to remember to call. This would mean that fetching a thread using the external API would also count as viewing a thread @sachben91.

💯 - view count and other usability metrics are usually considered part of an observability layer that's way outside the domain... and we should avoid leaking this extra complexity into the APIs and models like we do with other domain metrics like reaction count for example, unless we need them for some core business flow

**Comment by sachben91** [comment]
anyone know the reason why the viewcountcache was implemented in the first place? @Rotorsoft @timolegros
