### ISSUE TITLE
Knock should require auth and handle the feature flag being disabled. 

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#9643]
## Describe the bug

**UPDATE**: In retrospect, I *think* we have backed out the feature flag, but for some reason knock still doesn't have a userJWT? 

It looks like we "half removed" the feature flag for Knock.

Meaning we removed it in the webapp but the properties in the config are still optional.

When we remove a feature flag we need to make those config properties required.

This put the Knock env in the webapp a situation where it was running without a knock config.

I also think we accidentally removed the user.isLoggedIn check... Knock notifications don't make sense if the user isn't authenticated.

![CleanShot 2024-10-22 at 12 13 32@2x](https://github.com/user-attachments/assets/062bd2c0-a000-4378-9d73-b8350d5bbcbc)

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by timolegros** [comment]
I think this assumption that the configuration variables should be required is incorrect.

Knock env var should not be required to run the app given that Knock is a service we pay for and Knock notifications don't actually work locally or in other apps (e.g. commonwealth-pentest) without the message relayer + Knock worker anyways. As such Knock configuration _is_ (or at least should be) optional.
