### ISSUE TITLE
User should be able to view and copy ERC20 token 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9679]
### Description

Currently when a user hovers over the info icon for a weighted topic you are able to see only the partial address of the token that is funding the contest. User should be able to see the full address and if possible also be able to copy it - This will enable users to participate in contests easily by adding the given token their wallet if necessary 
<img width="400" alt="Screenshot 2024-10-24 at 2 58 51 PM" src="https://github.com/user-attachments/assets/5a8be3dc-2e04-4c1e-90d5-a060c6c64225">

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- On hovering over info icon users are able to the see the full token address of the ERC20 token used to weight the topic
- Users are able to copy the address (nice to have)

**Comment by sachben91** [comment]
@masvelio if this issue is high effort lets not do it now, but this would be really useful to have since it makes it easy for a user to add a token address to their wallet and also swap it etc

**Comment by masvelio** [comment]
@sachben91 this won't be high lift, PR up in a minute
