### ISSUE TITLE
PWA offline login persistance

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#9697]
### Description

We get logged out of the PWA more quickly than expected. This is a common issue among PWAs.

### User Stories / Acceptance Criteria

- user sessions are as long as expected.

**Task**
- We'll need to extend the offchain worker

### Additional Context

Theard on Common Solutions: https://www.perplexity.ai/search/pwa-logging-people-out-from-ap-v6C7tGWhRw6Tt7vGxWT9Tg

**Comment by burtonator** [comment]
Talked to @dillchen about this and he confirmed that it's logging him out in hours.

The way it worked last time is that it was a 2 week session that was persisted in a cookie

I verified that it worked last time but we must have had a regression.

I'm going to double check that this is the case.
