### ISSUE TITLE
Fund contest "Not Enough funds in wallet" when there are

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#9749]
## Describe the bug

![image](https://github.com/user-attachments/assets/966144ec-9252-4a86-851c-396a62e0364d)

Using USDC a 6 decimal token not enough funds is shown when the user has enough funds in wallet
### Initial conditions

**Environment:** 
production

## Reproduction steps

Use a token on base like USDC that has 6 decimals and try to fund a contest(@dillchen  to send to your address)

## Actual behavior

cant fund with a valid balance

## Expected behavior

should be able to fund with a valid balance

**Comment by dillchen** [comment]
duped
