### ISSUE TITLE
Fund Contest Page does not show user balance

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#9750]
## Describe the bug

User holds a certain token USDC, it is not being shown within our UI

![image](https://github.com/user-attachments/assets/35b2f419-d2aa-4ba2-b04e-7bdd434c5bd7)

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reproduction steps

1. Go to Fund a contest where community chainID is different than contest chainID
2. You can use Common Community (mainnet), and start a contest on base (using USDC Base)

We can use USDC Base Here: https://basescan.org/token/0x833589fcd6edb6e08f4c7c32d4f71b54bda02913

## Actual behavior

1. We do not see the correct token balance being shown

## Expected behavior

1. We see the correct token balance being shown

## Suggested Fix

It looks like the fund contest page is pulling the user’s tokenBalances from the wrong chain.
[https://github.com/hicommonwealth/commonwealth/blob/e7a960853fdda820e8c71ea24bf9f8[…]nityManagement/Contests/FundContestDrawer/useFundContestForm.ts](https://github.com/hicommonwealth/commonwealth/blob/e7a960853fdda820e8c71ea24bf9f8b54a46ed0e/packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/useFundContestForm.ts)

```
It looks like the fund contest page is pulling the user’s tokenBalances from the wrong chain.
[https://github.com/hicommonwealth/commonwealth/blob/e7a960853fdda820e8c71ea24bf9f8[…]nityManagement/Contests/FundContestDrawer/useFundContestForm.ts](https://github.com/hicommonwealth/commonwealth/blob/e7a960853fdda820e8c71ea24bf9f8b54a46ed0e/packages/commonwealth/client/scripts/views/pages/CommunityManagement/Contests/FundContestDrawer/useFundContestForm.ts)
```

It should be from ethChainId (or whichever chainID / chain Node) rather than the community’s chainID

**Comment by ianrowan** [comment]
Disregard - covered by #9747
