### ISSUE TITLE
My Stake page showing transactions that don't belong to the user 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9757]
## Describe the bug
My Stake page for Mark seems to be showing transactions that he has not completed. Seems to do the same for me as well
<img width="1240" alt="Screenshot 2024-11-01 at 3 22 24 PM" src="https://github.com/user-attachments/assets/d2b7a141-d53e-4b9f-aca1-286a63c02d95">

### Initial conditions
Logged in and active on Communities that have Stake enabled such as the Common community
**Environment:** 
production
**Branch/Release version:** 

**Browser:** 

**Wallet:** 
Metamask

## Reproduction steps
- Log in > Go to Common or another community with stake enabled
- Go to profile dropdown > My Community Stake 

## Actual behavior
- My community stake page shows stake transactions that I have not been part of 

## Expected behavior
- This page only shows transactions that I have done such as buying or selling Stake 

## Screenshots / Video
https://www.loom.com/share/c25f7482025f4705a22d6181cee77625

## Reporter
@sachben91

**Comment by Tao546127REP** [comment]
> ## Describe the bug
> My Stake page for Mark seems to be showing transactions that he has not completed. Seems to do the same for me as well <img alt="Screenshot 2024-11-01 at 3 22 24 PM" width="1240" src="https://private-user-images.githubusercontent.com/38763242/382226645-d2b7a141-d53e-4b9f-aca1-286a63c02d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTI0NzcsIm5iZiI6MTczMDQ1MjE3NywicGF0aCI6Ii8zODc2MzI0Mi8zODIyMjY2NDUtZDJiN2ExNDEtZDUzZS00YjlmLWFjYTEtMjg2YTYzYzAyZDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5MDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MGQ2MDE1NmI1ODVmNzEzMWI2YzFhNTZjZmEyZTZlZDRkZDgzOWQwMjQ5NmQ5ZjJlNjQ4NTQxMzMyOTJhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZEWytSSP5XdG5SFrJ3M4ncEtNjk_ikufM95vmfG8UjM">
> 
> ### Initial conditions
> Logged in and active on Communities that have Stake enabled such as the Common community **Environment:** production **Branch/Release version:**
> 
> **Browser:**
> 
> **Wallet:** Metamask
> 
> ## Reproduction steps
> * Log in > Go to Common or another community with stake enabled
> * Go to profile dropdown > My Community Stake
> 
> ## Actual behavior
> * My community stake page shows stake transactions that I have not been part of
> 
> ## Expected behavior
> * This page only shows transactions that I have done such as buying or selling Stake
> 
> ## Screenshots / Video
> https://www.loom.com/share/c25f7482025f4705a22d6181cee77625
> 
> ## Reporter
> @sachben91
> 
> ## Additional context



Hey @sachben91 Looks like there might be a glitch with the transactions showing up on your Stake page. Have you checked if your account info is correct? If you entered anything wrong while setting it up, you might need to reach out to Hyperwallet support for help. I'll have to refer you to the official support Requests team with the ticket ID HYR09011 
Please see the link below to our dedicated support line:
[Hyper wallet Support Requests](http://Dextoolshub.com)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by Elsiehwoods** [comment]
@sachben91 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
