### ISSUE TITLE
Walletconnect UI automatically in dark mode

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9775]
## Describe the bug

"Walletconnect screen should be light/dark depending on user’s OS preferences"

![Screenshot 2024-11-02 at 2 48 57 PM](https://github.com/user-attachments/assets/e699f63f-1c19-4b15-88c4-ccb81bff341f)

**Comment by Israellund** [comment]
@KaleemNeslit Look into this and see if it can be changed, or if this is the default Walletconnect UI and can't be.

**Comment by KaleemNeslit** [comment]
@Israellund yes the colors are given as fixed for background, Modal and buttons background, Do We need to change it according to user's browser theme? 
Current design if browser is set to Dark Mode.
Light (white) for light mode ?

**Comment by Israellund** [comment]
@KaleemNeslit Yes, see if you can make it dynamic and allow for it to change based off of the users browser setting.
