### ISSUE TITLE
Null error upon login

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9778]
## Describe the bug

"Dont have a screenshot for it but once in a blue moon when I log in, I’ll get a null error page - goes away when i log in"

-click around and try logging in multiple different ways with different wallets/sso, try to replicate null error.

**Comment by Elsiehwoods** [comment]
@Israellund It might be a good idea to document exactly what steps you took when the null error page appeared. Sometimes these intermittent issues can be tricky to replicate, but having detailed notes can help you or the support team pinpoint the problem. Have you tried clearing your cache or using a different browser to see if the issue persists?

**Comment by Israellund** [comment]
@Elsiehwoods feel free to submit a PR for this fix if you believe you can fix it.

**Comment by Israellund** [comment]
I am closing this issue as I was not able to replicate it and there is no further information to investigate.
