### ISSUE TITLE
Common member post history UI redesign

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9782]
## Describe the bug

![Screenshot 2024-11-02 at 3 12 12 PM](https://github.com/user-attachments/assets/dc480c20-e8c4-48ae-b8ec-647c0c7c5752)

**Comment by Israellund** [comment]
@KaleemNeslit assigning this to you, @sssssabinaaa will have designs to you by the end of the day Nov. 18th.

**Comment by sssssabinaaa** [comment]
Hi, that all sounds about right! I modified the "commented on/replied on" text color in the Figma file so that there's more separation of content.
