### ISSUE TITLE
Contest: 500 error we user do upvote

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#9799]
## Describe the bug

When user click on upvote on thread which has enabled contest we have 500 error

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

Master/release/v1.7.2-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to: https://qa.commonwealth.im/
2. Lunch contest
3. Create a thread 
4. As admin of that community click on upvote 
5. Check console

## Actual behavior

```
[
    {
        "error": {
            "message": "[ResponseError] Returned error: Unspecified origin not on whitelist.",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "path": "thread.createThreadReaction"
            }
        }
    }
]
```

**Comment by rbennettcw** [comment]
It's using the public key even when it should use the private. Normally I don't see the issue locally because I use the same key for both private/public, but I was able to repro by using different values and logging the resulting chain node url:
```
ALCHEMY_PRIVATE_APP_KEY=priv
ALCHEMY_PUBLIC_APP_KEY=pub
```
