### ISSUE TITLE
Contest: Upvote action is not visible 

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#9807]
## Describe the bug

When user upvote thread, action is not reflected on UI. Change is visible after refresh

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

master/release/v1.7.2-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to
2. Create contest 
3. Create threat in that contest
4. Click upvote 

## Actual behavior

Upvote action is executed but not visible on UI
## Expected behavior

When we click upvote we should refresh UI instantly and display proper status.

## Screenshots / Video

https://app.screencast.com/AgfIaSC7tmGvK

**Comment by mzparacha** [comment]
Already fixed by https://github.com/hicommonwealth/commonwealth/pull/9660 indirectly
