### ISSUE TITLE
Add launchpad_liquidity and market cap goal to the Tokens model and update Command

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#9813]
## Describe the bug
We will move away from a hardcoded launchpadLiquidity into a dynamic one, which means we will need to store this and the market cap goal in the Tokens model. These will come from the LPBondingCurve TokenRegistered event which "should" (correct me if I am wrong here) be in the same transaction as the TokenLaunched event.

**Comment by timolegros** [comment]
Yep and just for visibility, tagging @ianrowan who will add the `launchpadLiquidity` value to the `TokenRegistered` event and the `getMarketGoal` utility function.

**Comment by ianrowan** [comment]
Just noting this here for when I implement get Mkt Cap b/c I need somewhere to save it 

Formula:
R₀ = initial Reserve
S₀ = initial supply = 1e18
S = current supply = launchpad liquidity
F = connector Weight

P = (R₀/(S₀ * F)) * (S/S₀)^((1/F) - 1)

TS = total supply
MC = P * TS

That said I've made sure all of the above variables are emitted from the `TokenRegistered` event. We will likely want to store those on some model

**Comment by ianrowan** [comment]
@timolegros tagged you on https://github.com/hicommonwealth/commonwealth/pull/9857 for the mkt cap formula

**Comment by timolegros** [comment]
> event TokenRegistered(
>         address indexed token, 
>         uint256 curveId,
>         uint256 totalSupply,
>         uint256 launchpadLiquidity,
>         uint256 reserveRatio,
>         uint256 initialPurchaseEthAmount    
>     );
> ```

@ianrowan can we get this deployed so we can unblock this ticket?

**Comment by ianrowan** [comment]
@timolegros will have them deployed first thing next week. Some additional other related changes we'll want to pile into the deployment
