### ISSUE TITLE
Replace "Someone" with the address of the poster when generating emails

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#982]
we generate emails with "Someone" as the copy right now

**Comment by gdjohnson** [comment]
Just to confirm—we want to include the full address in the email message body, e.g. 
> 5G1rkajFGeZJYGACPz4X8mkpvQfwCQzrQjrhnywPAmo2u351 left a new comment on your post.

?

**Comment by raykyri** [comment]
can we truncate it using formatAddressShort?
