### ISSUE TITLE
🟦 CreateReferralLink

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#9833]
# Description
Creates a new referral link associated to the acting user

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
|   @dillchen    | @Rotorsoft     |

## Model
[Referrals](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764605012942618&cot=14)

## Engineering Requirements

1. **Authorization**
   - Any user
2. **Schemas** - Use [zod](http://zod.dev)
   - No inputs
   -  Output is a referral link string
3. **Routing**
   - tRPC user aggregate
4. **Loading Aggregate**
   - User
5. **Business Rules**
   - No link expirations or any other rules
6. **Mutations**
   - Create link in User aggregate (one link per user)
7. **Persistence**
   - Add new column to Users table
8. **Events**
   - N/A
9. **Response**
   - New link

## Unit Testing
- Create link

**Comment by Rotorsoft** [comment]
@dillchen @sachben91 a couple of questions regarding links:

- How many referral links per user? Many will require a new table ReferralLinks
- Format for referral links:
  - Something like `ref_userId_UUID` or do we have a desired format?
  - DB Indexed or we find it by extracting the userid from the link?
- Link associated to Users or Addresses?

**Comment by dillchen** [comment]
1. One referral link per user
2. No opinion on format that seems fine
3. Link to users

Sent via Superhuman iOS ***@***.***>

**Comment by dillchen** [comment]
No link expiration or other rules

Sent via Superhuman iOS ***@***.***>
