### ISSUE TITLE
Show image previews for threads in topics 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9845]
### Description

- Currently if there is an image in the thread, it is not previewed at the topic view. The community member has to click into the thread to view the image. 
- Community members should be able to preview the images added to a thread without having to click into the thread 
- This is a UX issue for contests that are based around images such as meme contests 

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- Community members are able to see previews of the images that are part of the thread. 
- If there are multiple images, community members should only see the first image that is added to the thread

**Comment by sachben91** [comment]
If the image is too big then we should reduce it to a fixed aspect ratio

**Comment by KaleemNeslit** [comment]
@Israellund  this ticket is done by @salman-neslit  in this [Pr](https://github.com/hicommonwealth/commonwealth/pull/9810)
