### ISSUE TITLE
Add weighted voting for other chains 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9849]
### Description

Weighted voting should also be available for communities on: Arbitrum, Ethereum, Linea and Optimism. All chains that support contests should also support weighted voting

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- Communities that are on ethereum, arbitrum, linea and optimism should be able to create weighted topics using Community Stake or using Tokens 
- All mentions of ERC20 in weighted voting creation should be replaced with "Token"

**Comment by ianrowan** [comment]
Contracts are deployed with ERC20 strategy on all these chains, so no protocol changes should be required
