### ISSUE TITLE
Use Uniswap trade widget for post-launchpad phase

### ISSUE THREAD

**Issue by ianrowan** [hicommonwealth/commonwealth#9887]
#### Description

After a token has been deployed to uniswap(post market cap goal) The token will no longer be tradable on the launchpad but rather on Uniswap. To enable users to trade we will use the Uniswap trade widget: https://docs.uniswap.org/sdk/swap-widget/guides/getting-started

In short, this widget looks similar to our trading experience and should live in the same part of the app.

To implement this widget the package must be installed and then its almost as simple as adding a react component in-line. 

On top of the default configuration we will include the following optional parameters to enable token trading: 

```
provider = fetch from active metaMask/otherWalletController
defaultChainId = the chain id of the community(ie 8453 for base)
defaultInputTokenAddress = 'NATIVE'
defaultOutputTokenAddress = the tokenAddress for the community from launchpad
hideConnectionUI = true
```

beyond this there are plenty of additional configuration options that may relate more to design/PENG which will be discovered during implementation

**Comment by mzparacha** [comment]
Facing some widget issues, bumping to 5.

**Comment by mzparacha** [comment]
Update: Got a lot of widget issues resolved.
1. Pricing calculations failed => resolved by a mix of https://github.com/Uniswap/widgets/issues/627#issuecomment-1930627298, https://github.com/Uniswap/widgets/issues/586#issuecomment-1777323003 and adding the `jsbi` pkg as a dependency
2. Gatway URL fails => resolved by https://github.com/Uniswap/widgets/issues/580#issuecomment-2086094025
3. Widget doesn't call any pricing endpoint => resolved by https://github.com/Uniswap/widgets/issues/637#issuecomment-2253135676
4. Vite @fontsource import issue => resolved by https://github.com/Uniswap/widgets/issues/593#issuecomment-1777415001
