### ISSUE TITLE
Allow adding multiple editors to a thread

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#991]

**Comment by gdjohnson** [comment]
Oh, this feature is great.

**Comment by gdjohnson** [comment]
Should this editor permission be limited to members of both on- and off-chain communities?

**Comment by raykyri** [comment]
Yes - if I understand correctly (non members should not be allowed to edit, basically). It's a small detail but otherwise there are edge cases with private communities.
