### ISSUE TITLE
SKALE added to recommended chains in community creation

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#9911]
### Description

Featured alongside the others

Skale: EVM Chain ID: 1564830818 -> https://chainlist.org/chain/1564830818

Logo Here: https://seeklogo.com/vector-logo/452494/skale-skl

To be shown under Ethereum in same format:
![Image](https://github.com/user-attachments/assets/f4518636-3063-49a3-a261-8e87ec316a93)

Copy: "SKALE is the Gas-Free EVM Blockchain Built Different for Mass Adoption"

### User Stories / Acceptance Criteria

tk tk

**Comment by Israellund** [comment]
@KaleemNeslit reassigning this ticket to you. 
@dillchen @sachben91 Any input on what the copy should say? "Skale is a ..."

**Comment by KaleemNeslit** [comment]
@Israellund  i need more information like  text to show and chainId

**Comment by sachben91** [comment]
Text to show: "SKALE is an on-demand blockchain network with zero gas fees, allowing quick deployment of interoperable EVM-compatible chains without compromising security or decentralization.

Seems like Chain ID is provided above 

@Israellund
