### ISSUE TITLE
Breadcrumbs doesn't span full width of screen

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#9917]
## Describe the bug

Breadcrumbs doesn't span full width of screen so it is showing some of the information to the right when you scroll, when it should scroll behind the breadcrumbs. This happens on larger screens. In the below image notice "Dismiss" is partially seen in the upper right. 
![screenshot_2024-11-14_at_2 28 12___pm](https://github.com/user-attachments/assets/dff84769-950a-4b8c-8d7f-c89959b64699)

Either the Breadcrumbs needs to be extended to account for all screen sizes, or a slug needs to be put in place to extend the breadcrumbs so there is no visual break between the end of the breadcrumbs and the edge of the screen.

**Comment by KaleemNeslit** [comment]
![image](https://github.com/user-attachments/assets/09dbccfe-6bc8-4b55-8ab2-6f1adb6fcaef)

@Israellund  i am not able to reproduce this bug as i tested with 4K screen size and  utlraHD  3840 * 2160 can you please you share which screen size you are facing issue
