### ISSUE TITLE
zero weight upvote for contests with no votes 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9922]
### Description

Presently if a contest has zero upvotes, the funds for the contest are stuck within the contract. In the longer term we need a mechanism to return these funds to the user. In the medium term, the solution would be to return the funds to Common, who will then distribute the money back to the user.  The mechanism should work as follows: 

- When a contest has less than 24 hours left, admins should get a message in the contest page that tells them to get upvotes in the contest to avoid funds being returned  (addressed in a separate ticket)
-  When the contest has less than 1 hour left, Common should add a zero weighted vote to a piece of content that is created solely on the contract, so that our account wins the contest and we get the contest funds. The content created is not displayed on the UI. 
- Once the contest funds are returned, Common should transfer the amount to the wallet connected to the admin who funded the contest 
- On the platform side, there will be a default address that will be the address that common votes from. 

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- If a contest ends with zero upvotes from users, then the funds should be returned to Common. Common should then return the funds to the wallet that funded the contest within the shortest time possible (something between 1-24 hours)

### Additional Context

- For the above solution, if the platform goes down while the contest is running/being settled the funds are still lost

**Comment by sachben91** [comment]
@ianrowan can you verify if the above is a feasible solution?  cc @dillchen

**Comment by masvelio** [comment]
@rbennettcw UI is done here https://github.com/hicommonwealth/commonwealth/pull/9952 but won't be visible to the user for now. During development of this ticket, the flag should be removed, so the warning will be visible.
