### ISSUE TITLE
Update designs for user onboarding and admin cards 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9925]
### Description

The admin and user onboarding cards should be updated to the following design that reduces white space and adds a light blue background. 

background color: `#e5f1ff`

<img width="768" alt="Screenshot 2024-11-15 at 3 31 35 PM" src="https://github.com/user-attachments/assets/5b8ba2be-4d8b-4996-ae63-56f4c3271ea7">

### Project Owner

@sachben91

### User Stories / Acceptance Criteria

- admin and user onboarding cards updated to the new design

### Design Devlink

[Figma](https://www.figma.com/board/vCCqpejGDzL7IFKl4vdZuR/Sidebar-and-TX-and-Purchases?node-id=5-17504&node-type=frame&t=nXV0u8f0mabUvNtj-0)

**Comment by KaleemNeslit** [comment]
> @sachben91 Please confirm this is correct. The image above shows a red circled area, which Kaleem changed in another ticket, but I interpreted the user onboarding and admin cards to be the cards under "Welcome to Common" and "Finish setting up your community" (surrounded in blue in the image above). Please correct me if I'm wrong. And @KaleemNeslit For now, please don't close any tickets. If you think a ticket needs to be closed please let me know. Thank you.

@Israellund in attached figma link there is not other cards then this .
from now on you will merge my PR.

**Comment by Israellund** [comment]
@KaleemNeslit No, you will continue to merge your own PRs. I am just asking you to not close any tickets without getting confirmation that the ticket no longer needs work. Sometimes there is not one source of truth and you may be closing the ticket with work still needing to be done. For example, this ticket mentions "User onboarding and Admin cards" in the title, yet the Figma shows something different. That is why I tagged @sachben91 to confirm. The component you already changed to blue is called `VoteWeightModule.tsx`, yet nowhere in the description does it mention Vote Weight. I may be wrong and this ticket no longer needs to be done, but I am asking for confirmation before I close it.

**Comment by sachben91** [comment]
> @sachben91 Please confirm this is correct. The image above shows a red circled area, which Kaleem changed in another ticket, but I interpreted the user onboarding and admin cards to be the cards under "Welcome to Common" and "Finish setting up your community" (surrounded in blue in the image above). Please correct me if I'm wrong. And @KaleemNeslit For now, please don't close any tickets. If you think a ticket needs to be closed please let me know. Thank you.

Yeah the change here should in the cards and not in the red outlined area, sorry about that confusion but was written in the description we want the white space around the admin and user onboarding cards to be reduced, and the blue background added.

**Comment by KaleemNeslit** [comment]
@Israellund  can you show me the user onboarding and admin cards  . i am confused which one is  user onboarding and admin cards.
