### ISSUE TITLE
Editing large comments is broken

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#9960]
## Describe the bug
When editing a large comment you get a warning and the existing content is not editable/is removed from the editor.

![image](https://github.com/user-attachments/assets/ae38e626-3099-4646-bb37-634ff093f5c3)

### Initial conditions

**Environment:** production
**Branch/Release version:** 

**Browser:** 

**Wallet:** 

## Reproduction steps

1. Create comment with more than 2k characters
2. Edit the comment

**Comment by Israellund** [comment]
@KaleemNeslit Take a look at this and see if you can figure out why it shows this modal for editing any comments with more than 2k characters. Let me know if you need any other information.
